export enum ActionEnum {
    ACCEPT_MISSION = "accept_mission",
    ADVANCE_DAEDALUS = "advance_daedalus",
    ANALYZE_PLANET = "analyze_planet",
    CHANGE_NERON_CPU_PRIORITY = "change_neron_cpu_priority",
    CHANGE_NERON_CREW_LOCK = "change_neron_crew_lock",
    COMMANDER_ORDER = "commander_order",
    COM_MANAGER_ANNOUNCEMENT = "com_manager_announcement",
    COMPUTE_EDEN = "compute_eden",
    DELETE_PLANET = "delete_planet",
    ESTABLISH_LINK_WITH_SOL = "establish_link_with_sol",
    EXCHANGE_BODY = "exchange_body",
    EXIT_TERMINAL = "exit_terminal",
    LEAVE_ORBIT = "leave_orbit",
    LEARN = "learn",
    PARTICIPATE = "participate",
    PARTICIPATE_RESEARCH = "participate_research",
    REPAIR_PILGRED = "repair_pilgred",
    REJECT_MISSION = "reject_mission",
    RETURN_TO_SOL = "return_to_sol",
    UPGRADE_NERON = "upgrade_neron",
    SCAN = "scan",
    SHOOT_HUNTER = "shoot_hunter",
    SHOOT_HUNTER_PATROL_SHIP = "shoot_hunter_patrol_ship",
    TOGGLE_MAGNETIC_NET = "toggle_magnetic_net",
    TOGGLE_NERON_INHIBITION = "toggle_neron_inhibition",
    TOGGLE_PLASMA_SHIELD = "toggle_plasma_shield",
    TRAVEL_TO_EDEN = "travel_to_eden",
    TURN_DAEDALUS_LEFT = "turn_daedalus_left",
    TURN_DAEDALUS_RIGHT = "turn_daedalus_right",
    WRITE = "write",
};

export enum ShootHunterActionsEnum {
    SHOOT_HUNTER = "shoot_hunter",
    SHOOT_HUNTER_PATROL_SHIP = "shoot_hunter_patrol_ship",
};

