export enum SkinEnum {
    JANICE_SEXY = "janice_sexy",
    IAN_LABCOAT = "ian_labcoat",
    CHAO_LEATHER = "chao_leather",
    ROLAND_YULE = "roland_yule",
    ELEESHA_CLASSY = "eleesha_classy",
    RALUCA_ADDAMS = "raluca_addams",
    TERRENCE_BIKER = "terrence_biker",
    JIN_SU_GNANGNAN = "jin_su_gnangnan",
    HUA_PUPKIN = "hua_pupkin",
    JIN_SU_VAMPIRE = "jin_su_vampire",
    STEPHEN_SANTA = "stephen_santa",
    PAOLA_SANTA = "paola_santa",
    KUAN_ALBATOR = "kuan_albator",
    FINOLA_SKYWALKER = "finola_skywalker",
    GIOELE_BATHROBE = "gioele_bathrobe",
    CHUN_DALLAS = "chun_dallas",
    FRIEDA_GONADALF = "frieda_gonadalf",

    REACTOR_BROKEN ="reactor_broken",
    BAY_DOOR_EXTRALARGE = "bay_door_extralarge",
    GARDEN_INCUBATOR = "garden_incubator",
    GARDEN_LAMP = "garden_lamp",
    KITCHEN_APERO = 'kitchen_apero',
    PILGRED_ACTIVE = "pilgred_active",
    PLASMA_SHIELD_ACTIVE = "plasma_shield_active",
    SCANNER_OVERCLOCKING = "scanner_overclocking",
    ANTENNA_SPATIAL_WAVE = "antenna_spatial_wave",
    TURRET_TESLA = "turret_tesla",
    TURRET_CHARGES = "turret_charges",
    COFFEE_MACHINE_FISSION = "coffee_machine_fission",
    ICARUS_LARGE = "icarus_large",
    ICARUS_THRUSTER = "icarus_thruster",
    NERON_CORE_PARTICIPATION = "neron_core_participation",
    PATROL_SHIP_BLASTER = "patrol_ship_blaster",
    PATROL_SHIP_GOLD = "patrol_ship_gold",
    PATROL_SHIP_TELSATRON = "patrol_ship_telsatron",
    PATROL_SHIP_RED_BLACK = "patrol_ship_red_black",
    SOFA_BROWN = "sofa_brown",
    SOFA_GREEN = "sofa_green",
    SOFA_PINK = "sofa_pink",
    SOFA_WHITE = "sofa_white",

    ALPHA_POSTER = "alpha_poster",
    TABLE_APERO = "table_apero",
    MAGNETIC_NET = "magnetic_net",
    MAGNETIC_RETURN = "magnetic_return",
    QUANTUM_SENSOR = "quantum_sensor",
    TAKEOFF_PLATFORM_PROPULSION = "takeoff_platform_propulsion",
    WALL_BOX = "wall_box",
    PNEUMATIC_DISTRIBUTOR = "pneumatic_distributor",
}

export interface SkinInfo {
    name: string,
    key: string,
    frameChanges: { initialFrame: string, newFrame: string },
    startFrame?: number,
    endFrame?: number,
}

export const skinEnum : {[index: string]: SkinInfo}  = {
    [SkinEnum.JANICE_SEXY]: {
        name: 'Janice Sexy',
        key: 'janiceSexy',
        frameChanges: { initialFrame: 'janice', newFrame: 'janice_sexy' },
        startFrame: null,
        endFrame: null,
    },
};
