<?php

namespace Mush\Status\ConfigData;

use Mush\Action\Enum\ActionEnum;
use Mush\Equipment\Enum\ItemEnum;
use Mush\Game\Enum\SkillEnum;
use Mush\Game\Enum\VisibilityEnum;
use Mush\Modifier\Enum\ModifierNameEnum;
use Mush\Status\Enum\ChargeStrategyTypeEnum;
use Mush\Status\Enum\DaedalusStatusEnum;
use Mush\Status\Enum\EquipmentStatusEnum;
use Mush\Status\Enum\HunterStatusEnum;
use Mush\Status\Enum\PlayerStatusEnum;

/** @codeCoverageIgnore */
abstract class StatusConfigData
{
    public static array $dataArray = [
        [
            'name' => 'alien_artefact_default',
            'statusName' => 'alien_artefact',
            'visibility' => 'public',
            'type' => 'status_config',
            'chargeVisibility' => null,
            'chargeStrategy' => 'none',
            'maxCharge' => null,
            'startCharge' => null,
            'dischargeStrategies' => ['none'],
            'autoRemove' => null,
            'modifierConfigs' => [],
            'actionConfigs' => [],
        ],
        [
            'name' => 'heavy_default',
            'statusName' => 'heavy',
            'visibility' => 'public',
            'type' => 'status_config',
            'chargeVisibility' => null,
            'chargeStrategy' => 'none',
            'maxCharge' => null,
            'startCharge' => null,
            'dischargeStrategies' => ['none'],
            'autoRemove' => null,
            'modifierConfigs' => [],
            'actionConfigs' => [],
        ],
        [
            'name' => 'module_access_default',
            'statusName' => 'module_access',
            'visibility' => 'public',
            'type' => 'status_config',
            'chargeVisibility' => null,
            'chargeStrategy' => 'none',
            'maxCharge' => null,
            'startCharge' => null,
            'dischargeStrategies' => ['none'],
            'autoRemove' => null,
            'modifierConfigs' => [],
            'actionConfigs' => [],
        ],
        [
            'name' => 'hidden_default',
            'statusName' => 'hidden',
            'visibility' => 'private',
            'type' => 'status_config',
            'chargeVisibility' => null,
            'chargeStrategy' => 'none',
            'maxCharge' => null,
            'startCharge' => null,
            'dischargeStrategies' => ['none'],
            'autoRemove' => null,
            'modifierConfigs' => [],
            'actionConfigs' => [],
        ],
        [
            'name' => 'broken_default',
            'statusName' => 'broken',
            'visibility' => 'public',
            'type' => 'status_config',
            'chargeVisibility' => null,
            'chargeStrategy' => 'none',
            'maxCharge' => null,
            'startCharge' => null,
            'dischargeStrategies' => ['none'],
            'autoRemove' => null,
            'modifierConfigs' => [],
            'actionConfigs' => [],
        ],
        [
            'name' => 'unstable_default',
            'statusName' => 'unstable',
            'visibility' => 'public',
            'type' => 'status_config',
            'chargeVisibility' => null,
            'chargeStrategy' => 'none',
            'maxCharge' => null,
            'startCharge' => null,
            'dischargeStrategies' => ['none'],
            'autoRemove' => null,
            'modifierConfigs' => [],
            'actionConfigs' => [],
        ],
        [
            'name' => 'hazardous_default',
            'statusName' => 'hazardous',
            'visibility' => 'public',
            'type' => 'status_config',
            'chargeVisibility' => null,
            'chargeStrategy' => 'none',
            'maxCharge' => null,
            'startCharge' => null,
            'dischargeStrategies' => ['none'],
            'autoRemove' => null,
            'modifierConfigs' => [],
            'actionConfigs' => [],
        ],
        [
            'name' => 'decomposing_default',
            'statusName' => 'decomposing',
            'visibility' => 'public',
            'type' => 'status_config',
            'chargeVisibility' => null,
            'chargeStrategy' => 'none',
            'maxCharge' => null,
            'startCharge' => null,
            'dischargeStrategies' => ['none'],
            'autoRemove' => null,
            'modifierConfigs' => [],
            'actionConfigs' => [],
        ],
        [
            'name' => 'frozen_default',
            'statusName' => 'frozen',
            'visibility' => 'public',
            'type' => 'status_config',
            'chargeVisibility' => null,
            'chargeStrategy' => 'none',
            'maxCharge' => null,
            'startCharge' => null,
            'dischargeStrategies' => ['none'],
            'autoRemove' => null,
            'modifierConfigs' => [
                'modifier_for_equipment_+1actionPoint_on_consume',
            ],
            'actionConfigs' => [],
        ],
        [
            'name' => 'plant_thirsty_default',
            'statusName' => 'plant_thirsty',
            'visibility' => 'public',
            'type' => 'status_config',
            'chargeVisibility' => null,
            'chargeStrategy' => 'none',
            'maxCharge' => null,
            'startCharge' => null,
            'dischargeStrategies' => ['none'],
            'autoRemove' => null,
            'modifierConfigs' => [],
            'actionConfigs' => [],
        ],
        [
            'name' => 'plant_dry_default',
            'statusName' => 'plant_dry',
            'visibility' => 'public',
            'type' => 'status_config',
            'chargeVisibility' => null,
            'chargeStrategy' => 'none',
            'maxCharge' => null,
            'startCharge' => null,
            'dischargeStrategies' => ['none'],
            'autoRemove' => null,
            'modifierConfigs' => [],
            'actionConfigs' => [],
        ],
        [
            'name' => 'plant_diseased_default',
            'statusName' => 'plant_diseased',
            'visibility' => 'public',
            'type' => 'status_config',
            'chargeVisibility' => null,
            'chargeStrategy' => 'none',
            'maxCharge' => null,
            'startCharge' => null,
            'dischargeStrategies' => ['none'],
            'autoRemove' => null,
            'modifierConfigs' => [],
            'actionConfigs' => [],
        ],
        [
            'name' => 'document_content_default',
            'statusName' => 'document_content',
            'visibility' => 'hidden',
            'type' => 'content_status_config',
            'chargeVisibility' => null,
            'chargeStrategy' => 'none',
            'maxCharge' => null,
            'startCharge' => null,
            'dischargeStrategies' => ['none'],
            'autoRemove' => null,
            'modifierConfigs' => [],
            'actionConfigs' => [],
        ],
        [
            'name' => 'reinforced_default',
            'statusName' => 'reinforced',
            'visibility' => 'hidden',
            'type' => 'status_config',
            'chargeVisibility' => null,
            'chargeStrategy' => 'none',
            'maxCharge' => null,
            'startCharge' => null,
            'dischargeStrategies' => ['none'],
            'autoRemove' => null,
            'modifierConfigs' => [],
            'actionConfigs' => [],
        ],
        [
            'name' => 'antisocial_default',
            'statusName' => 'antisocial',
            'visibility' => 'public',
            'type' => 'status_config',
            'chargeVisibility' => null,
            'chargeStrategy' => 'none',
            'maxCharge' => null,
            'startCharge' => null,
            'dischargeStrategies' => ['none'],
            'autoRemove' => null,
            'modifierConfigs' => [
                'antisocial_modifier_for_player_-1moralPoint_on_new_cycle_if_player_in_room_not_alone',
            ],
            'actionConfigs' => [],
        ],
        [
            'name' => 'berzerk_default',
            'statusName' => 'berzerk',
            'visibility' => 'public',
            'type' => 'status_config',
            'chargeVisibility' => null,
            'chargeStrategy' => 'none',
            'maxCharge' => null,
            'startCharge' => null,
            'dischargeStrategies' => ['none'],
            'autoRemove' => null,
            'modifierConfigs' => [],
            'actionConfigs' => [],
        ],
        [
            'name' => 'brainsync_default',
            'statusName' => 'brainsync',
            'visibility' => 'public',
            'type' => 'status_config',
            'chargeVisibility' => null,
            'chargeStrategy' => 'none',
            'maxCharge' => null,
            'startCharge' => null,
            'dischargeStrategies' => ['none'],
            'autoRemove' => null,
            'modifierConfigs' => [],
            'actionConfigs' => [],
        ],
        [
            'name' => 'burdened_default',
            'statusName' => 'burdened',
            'visibility' => 'private',
            'type' => 'status_config',
            'chargeVisibility' => null,
            'chargeStrategy' => 'none',
            'maxCharge' => null,
            'startCharge' => null,
            'dischargeStrategies' => ['none'],
            'autoRemove' => null,
            'modifierConfigs' => [
                'modifier_for_player_+2movementPoint_on_move',
            ],
            'actionConfigs' => [],
        ],
        [
            'name' => 'demoralized_default',
            'statusName' => 'demoralized',
            'visibility' => 'private',
            'type' => 'status_config',
            'chargeVisibility' => null,
            'chargeStrategy' => 'none',
            'maxCharge' => null,
            'startCharge' => null,
            'dischargeStrategies' => ['none'],
            'autoRemove' => null,
            'modifierConfigs' => [
                'modifier_for_player_+30percentage_on_cycle_disease',
            ],
            'actionConfigs' => [],
        ],
        [
            'name' => 'dirty_default',
            'statusName' => 'dirty',
            'visibility' => 'public',
            'type' => 'status_config',
            'chargeVisibility' => null,
            'chargeStrategy' => 'none',
            'maxCharge' => null,
            'startCharge' => null,
            'dischargeStrategies' => ['none'],
            'autoRemove' => null,
            'modifierConfigs' => [],
            'actionConfigs' => [],
        ],
        [
            'name' => 'disabled_default',
            'statusName' => 'disabled',
            'visibility' => 'public',
            'type' => 'status_config',
            'chargeVisibility' => null,
            'chargeStrategy' => 'none',
            'maxCharge' => null,
            'startCharge' => null,
            'dischargeStrategies' => ['none'],
            'autoRemove' => null,
            'modifierConfigs' => [
                'modifier_for_player_-1movementPoint_on_move_if_player_in_room_not_alone',
                'modifier_for_player_-2movementPoint_on_event_action_movement_conversion',
            ],
            'actionConfigs' => [],
        ],
        [
            'name' => 'focused_default',
            'statusName' => 'focused',
            'visibility' => 'public',
            'type' => 'status_config',
            'chargeVisibility' => null,
            'chargeStrategy' => 'none',
            'maxCharge' => null,
            'startCharge' => null,
            'dischargeStrategies' => ['none'],
            'autoRemove' => null,
            'modifierConfigs' => [],
            'actionConfigs' => [],
        ],
        [
            'name' => 'full_stomach_default',
            'statusName' => 'full_stomach',
            'visibility' => 'private',
            'type' => 'status_config',
            'chargeVisibility' => null,
            'chargeStrategy' => 'none',
            'maxCharge' => null,
            'startCharge' => null,
            'dischargeStrategies' => ['none'],
            'autoRemove' => null,
            'modifierConfigs' => [],
            'actionConfigs' => [],
        ],
        [
            'name' => 'gagged_default',
            'statusName' => 'gagged',
            'visibility' => 'public',
            'type' => 'status_config',
            'chargeVisibility' => null,
            'chargeStrategy' => 'none',
            'maxCharge' => null,
            'startCharge' => null,
            'dischargeStrategies' => ['none'],
            'autoRemove' => null,
            'modifierConfigs' => [
                'mute_modifier',
            ],
            'actionConfigs' => ['ungag'],
        ],
        [
            'name' => 'germaphobe_default',
            'statusName' => 'germaphobe',
            'visibility' => 'public',
            'type' => 'status_config',
            'chargeVisibility' => null,
            'chargeStrategy' => 'none',
            'maxCharge' => null,
            'startCharge' => null,
            'dischargeStrategies' => ['none'],
            'autoRemove' => null,
            'modifierConfigs' => [],
            'actionConfigs' => [],
        ],
        [
            'name' => 'guardian_default',
            'statusName' => 'guardian',
            'visibility' => 'public',
            'type' => 'status_config',
            'chargeVisibility' => null,
            'chargeStrategy' => 'none',
            'maxCharge' => null,
            'startCharge' => null,
            'dischargeStrategies' => ['none'],
            'autoRemove' => null,
            'modifierConfigs' => [],
            'actionConfigs' => [],
        ],
        [
            'name' => 'highly_inactive_default',
            'statusName' => 'highly_inactive',
            'visibility' => 'public',
            'type' => 'status_config',
            'chargeVisibility' => null,
            'chargeStrategy' => 'none',
            'maxCharge' => null,
            'startCharge' => null,
            'dischargeStrategies' => ['none'],
            'autoRemove' => null,
            'modifierConfigs' => [],
            'actionConfigs' => [],
        ],
        [
            'name' => 'hyperactive_default',
            'statusName' => 'hyperactive',
            'visibility' => 'public',
            'type' => 'status_config',
            'chargeVisibility' => null,
            'chargeStrategy' => 'none',
            'maxCharge' => null,
            'startCharge' => null,
            'dischargeStrategies' => ['none'],
            'autoRemove' => null,
            'modifierConfigs' => [],
            'actionConfigs' => [],
        ],
        [
            'name' => 'immunized_default',
            'statusName' => 'immunized',
            'visibility' => 'public',
            'type' => 'status_config',
            'chargeVisibility' => null,
            'chargeStrategy' => 'none',
            'maxCharge' => null,
            'startCharge' => null,
            'dischargeStrategies' => ['none'],
            'autoRemove' => null,
            'modifierConfigs' => [
                'modifier_for_player_set_0spore_on_change.variable',
            ],
            'actionConfigs' => [],
        ],
        [
            'name' => 'inactive_default',
            'statusName' => 'inactive',
            'visibility' => 'public',
            'type' => 'status_config',
            'chargeVisibility' => null,
            'chargeStrategy' => 'none',
            'maxCharge' => null,
            'startCharge' => null,
            'dischargeStrategies' => ['none'],
            'autoRemove' => null,
            'modifierConfigs' => [],
            'actionConfigs' => [],
        ],
        [
            'name' => 'lost_default',
            'statusName' => 'lost',
            'visibility' => 'public',
            'type' => 'status_config',
            'chargeVisibility' => null,
            'chargeStrategy' => 'none',
            'maxCharge' => null,
            'startCharge' => null,
            'dischargeStrategies' => ['none'],
            'autoRemove' => null,
            'modifierConfigs' => [
                'lost_modifier_for_player_-2moralPoint_on_new_cycle',
            ],
            'actionConfigs' => [],
        ],
        [
            'name' => 'lying_down_default',
            'statusName' => 'lying_down',
            'visibility' => 'public',
            'type' => 'status_config',
            'chargeVisibility' => null,
            'chargeStrategy' => 'none',
            'maxCharge' => null,
            'startCharge' => null,
            'dischargeStrategies' => ['none'],
            'autoRemove' => null,
            'modifierConfigs' => [
                'lying_down_modifier_for_player_+1actionPoint_on_new_cycle',
            ],
            'actionConfigs' => ['get_up'],
        ],
        [
            'name' => 'multi_teamster_default',
            'statusName' => 'multi_teamster',
            'visibility' => 'public',
            'type' => 'status_config',
            'chargeVisibility' => null,
            'chargeStrategy' => 'none',
            'maxCharge' => null,
            'startCharge' => null,
            'dischargeStrategies' => ['none'],
            'autoRemove' => null,
            'modifierConfigs' => [],
            'actionConfigs' => [],
        ],
        [
            'name' => 'outcast_default',
            'statusName' => 'outcast',
            'visibility' => 'public',
            'type' => 'status_config',
            'chargeVisibility' => null,
            'chargeStrategy' => 'none',
            'maxCharge' => null,
            'startCharge' => null,
            'dischargeStrategies' => ['none'],
            'autoRemove' => null,
            'modifierConfigs' => [],
            'actionConfigs' => [],
        ],
        [
            'name' => 'pacifist_default',
            'statusName' => 'pacifist',
            'visibility' => 'public',
            'type' => 'status_config',
            'chargeVisibility' => null,
            'chargeStrategy' => 'none',
            'maxCharge' => null,
            'startCharge' => null,
            'dischargeStrategies' => ['none'],
            'autoRemove' => null,
            'modifierConfigs' => [
                'modifier_for_place_+2actionPoint_on_action_aggressive',
            ],
            'actionConfigs' => [],
        ],
        [
            'name' => 'pregnant_default',
            'statusName' => 'pregnant',
            'visibility' => 'public',
            'type' => 'status_config',
            'chargeVisibility' => null,
            'chargeStrategy' => 'none',
            'maxCharge' => null,
            'startCharge' => null,
            'dischargeStrategies' => ['none'],
            'autoRemove' => null,
            'modifierConfigs' => [],
            'actionConfigs' => [],
        ],
        [
            'name' => 'starving_default',
            'statusName' => 'starving',
            'visibility' => 'private',
            'type' => 'status_config',
            'chargeVisibility' => null,
            'chargeStrategy' => 'none',
            'maxCharge' => null,
            'startCharge' => null,
            'dischargeStrategies' => ['none'],
            'autoRemove' => null,
            'modifierConfigs' => [
                'starving_for_player_-1healthPoint_on_new_cycle',
            ],
            'actionConfigs' => [],
        ],
        [
            'name' => 'starving_warning_default',
            'statusName' => 'starving_warning',
            'visibility' => 'private',
            'type' => 'status_config',
            'chargeVisibility' => null,
            'chargeStrategy' => 'none',
            'maxCharge' => null,
            'startCharge' => null,
            'dischargeStrategies' => ['none'],
            'autoRemove' => null,
            'modifierConfigs' => [],
            'actionConfigs' => [],
        ],
        [
            'name' => 'stuck_in_the_ship_default',
            'statusName' => 'stuck_in_the_ship',
            'visibility' => 'public',
            'type' => 'status_config',
            'chargeVisibility' => null,
            'chargeStrategy' => 'none',
            'maxCharge' => null,
            'startCharge' => null,
            'dischargeStrategies' => ['none'],
            'autoRemove' => null,
            'modifierConfigs' => [],
            'actionConfigs' => [],
        ],
        [
            'name' => 'suicidal_default',
            'statusName' => 'suicidal',
            'visibility' => 'private',
            'type' => 'status_config',
            'chargeVisibility' => null,
            'chargeStrategy' => 'none',
            'maxCharge' => null,
            'startCharge' => null,
            'dischargeStrategies' => ['none'],
            'autoRemove' => null,
            'modifierConfigs' => [
                'modifier_for_player_+30percentage_on_cycle_disease',
            ],
            'actionConfigs' => [],
        ],
        [
            'name' => 'WATCHED_PUBLIC_BROADCAST_default',
            'statusName' => 'WATCHED_PUBLIC_BROADCAST',
            'visibility' => 'hidden',
            'type' => 'status_config',
            'chargeVisibility' => null,
            'chargeStrategy' => 'none',
            'maxCharge' => null,
            'startCharge' => null,
            'dischargeStrategies' => ['none'],
            'autoRemove' => null,
            'modifierConfigs' => [],
            'actionConfigs' => [],
        ],
        [
            'name' => 'talkie_screwed_default',
            'statusName' => 'talkie_screwed',
            'visibility' => 'hidden',
            'type' => 'status_config',
            'chargeVisibility' => null,
            'chargeStrategy' => 'none',
            'maxCharge' => null,
            'startCharge' => null,
            'dischargeStrategies' => ['none'],
            'autoRemove' => null,
            'modifierConfigs' => [],
            'actionConfigs' => [],
        ],
        [
            'name' => 'attempt_default',
            'statusName' => 'attempt',
            'visibility' => 'hidden',
            'type' => 'charge_status_config',
            'chargeVisibility' => 'hidden',
            'chargeStrategy' => 'none',
            'maxCharge' => null,
            'startCharge' => 0,
            'dischargeStrategies' => ['none'],
            'autoRemove' => false,
            'modifierConfigs' => [],
            'actionConfigs' => [],
        ],
        [
            'name' => 'electric_charges_microwave_default',
            'statusName' => 'electric_charges',
            'visibility' => 'public',
            'type' => 'charge_status_config',
            'chargeVisibility' => 'public',
            'chargeStrategy' => 'cycle_increment',
            'maxCharge' => 4,
            'startCharge' => 1,
            'dischargeStrategies' => ['express_cook'],
            'autoRemove' => false,
            'modifierConfigs' => [],
            'actionConfigs' => [],
        ],
        [
            'name' => 'electric_charges_antigrav_scooter_default',
            'statusName' => 'electric_charges',
            'visibility' => 'public',
            'type' => 'charge_status_config',
            'chargeVisibility' => 'public',
            'chargeStrategy' => 'cycle_increment',
            'maxCharge' => 8,
            'startCharge' => 2,
            'dischargeStrategies' => [ModifierNameEnum::ANTIGRAV_SCOOTER_CONVERSION_MODIFIER],
            'autoRemove' => false,
            'modifierConfigs' => [],
            'actionConfigs' => [],
        ],
        [
            'name' => 'electric_charges_blaster_default',
            'statusName' => 'electric_charges',
            'visibility' => 'public',
            'type' => 'charge_status_config',
            'chargeVisibility' => 'public',
            'chargeStrategy' => 'cycle_increment',
            'maxCharge' => 3,
            'startCharge' => 1,
            'dischargeStrategies' => ['shoot'],
            'autoRemove' => false,
            'modifierConfigs' => [],
            'actionConfigs' => [],
        ],
        [
            'name' => 'electric_charges_old_faithful_default',
            'statusName' => 'electric_charges',
            'visibility' => 'public',
            'type' => 'charge_status_config',
            'chargeVisibility' => 'public',
            'chargeStrategy' => 'cycle_increment',
            'maxCharge' => 12,
            'startCharge' => 12,
            'dischargeStrategies' => ['shoot'],
            'autoRemove' => false,
            'modifierConfigs' => [],
            'actionConfigs' => [],
        ],
        [
            'name' => 'electric_charges_rocket_launcher_default',
            'statusName' => 'electric_charges',
            'visibility' => 'public',
            'type' => 'charge_status_config',
            'chargeVisibility' => 'public',
            'chargeStrategy' => 'cycle_increment',
            'maxCharge' => 1,
            'startCharge' => 1,
            'dischargeStrategies' => ['shoot'],
            'autoRemove' => false,
            'modifierConfigs' => [],
            'actionConfigs' => [],
        ],
        [
            'name' => 'electric_charges_narcotic_distiller_default',
            'statusName' => 'electric_charges',
            'visibility' => 'hidden',
            'type' => 'charge_status_config',
            'chargeVisibility' => 'hidden',
            'chargeStrategy' => 'daily_increment',
            'maxCharge' => 1,
            'startCharge' => 1,
            'dischargeStrategies' => ['dispense'],
            'autoRemove' => false,
            'modifierConfigs' => [],
            'actionConfigs' => [],
        ],
        [
            'name' => 'electric_charges_coffee_machine_default',
            'statusName' => 'electric_charges',
            'visibility' => 'hidden',
            'type' => 'charge_status_config',
            'chargeVisibility' => 'hidden',
            'chargeStrategy' => 'coffee_machine_charge_increment',
            'maxCharge' => 1,
            'startCharge' => 1,
            'dischargeStrategies' => ['coffee'],
            'autoRemove' => false,
            'modifierConfigs' => [],
            'actionConfigs' => [],
        ],
        [
            'name' => 'electric_charges_turret_command_default',
            'statusName' => 'electric_charges',
            'visibility' => 'public',
            'type' => 'charge_status_config',
            'chargeVisibility' => 'public',
            'chargeStrategy' => 'cycle_increment',
            'maxCharge' => 4,
            'startCharge' => 4,
            'dischargeStrategies' => ['shoot_hunter', ActionEnum::SHOOT_RANDOM_HUNTER],
            'autoRemove' => false,
            'modifierConfigs' => [],
            'actionConfigs' => [],
        ],
        [
            'name' => 'electric_charges_patrol_ship_default',
            'statusName' => 'electric_charges',
            'visibility' => 'public',
            'type' => 'charge_status_config',
            'chargeVisibility' => 'public',
            'chargeStrategy' => ChargeStrategyTypeEnum::PATROL_SHIP_CHARGE_INCREMENT,
            'maxCharge' => 10,
            'startCharge' => 10,
            'dischargeStrategies' => ['shoot_hunter_patrol_ship', ActionEnum::SHOOT_RANDOM_HUNTER_PATROL_SHIP],
            'autoRemove' => false,
            'modifierConfigs' => [],
            'actionConfigs' => [],
        ],
        [
            'name' => 'sink_charge_default',
            'statusName' => 'sink_charge',
            'visibility' => 'hidden',
            'type' => 'charge_status_config',
            'chargeVisibility' => 'hidden',
            'chargeStrategy' => 'daily_increment',
            'maxCharge' => 1,
            'startCharge' => 1,
            'dischargeStrategies' => ['wash_in_sink'],
            'autoRemove' => false,
            'modifierConfigs' => [],
            'actionConfigs' => [],
        ],
        [
            'name' => 'fire_default',
            'statusName' => 'fire',
            'visibility' => 'public',
            'type' => 'charge_status_config',
            'chargeVisibility' => 'hidden',
            'chargeStrategy' => 'cycle_increment',
            'maxCharge' => null,
            'startCharge' => 0,
            'dischargeStrategies' => ['none'],
            'autoRemove' => false,
            'modifierConfigs' => [],
            'actionConfigs' => ['report_fire'],
        ],
        [
            'name' => 'plant_young_default',
            'statusName' => 'plant_young',
            'visibility' => 'public',
            'type' => 'charge_status_config',
            'chargeVisibility' => 'public',
            'chargeStrategy' => 'growing_plant',
            'maxCharge' => null,
            'startCharge' => 0,
            'dischargeStrategies' => ['none'],
            'autoRemove' => false,
            'modifierConfigs' => [],
            'actionConfigs' => [],
        ],
        [
            'name' => 'eureka_moment_default',
            'statusName' => 'eureka_moment',
            'visibility' => 'public',
            'type' => 'charge_status_config',
            'chargeVisibility' => 'hidden',
            'chargeStrategy' => 'none',
            'maxCharge' => 1,
            'startCharge' => 0,
            'dischargeStrategies' => ['none'],
            'autoRemove' => true,
            'modifierConfigs' => [],
            'actionConfigs' => [],
        ],
        [
            'name' => 'first_time_default',
            'statusName' => 'first_time',
            'visibility' => 'public',
            'type' => 'charge_status_config',
            'chargeVisibility' => 'hidden',
            'chargeStrategy' => 'none',
            'maxCharge' => 1,
            'startCharge' => 1,
            'dischargeStrategies' => ['none'],
            'autoRemove' => true,
            'modifierConfigs' => [],
            'actionConfigs' => [],
        ],
        [
            'name' => 'mush_default',
            'statusName' => 'mush',
            'visibility' => 'mush',
            'type' => 'charge_status_config',
            'chargeVisibility' => 'hidden',
            'chargeStrategy' => 'daily_reset',
            'maxCharge' => 1,
            'startCharge' => 1,
            'dischargeStrategies' => ['none'],
            'autoRemove' => false,
            'modifierConfigs' => [
                'mush_shower_malus_for_player_set_-3healthPoint_on_post.action_if_reason_shower',
                'modifier_for_player_prevent_change.variable_if_reason_consume',
                'modifier_for_player_set_4satiety_on_change.variable_if_reason_consume',
                'modifier_for_player_set_0moralPoint_on_change.variable',
            ],
            'actionConfigs' => [
                'infect',
                'eat_spore',
                'extract_spore',
                'make_sick',
                'screw_talkie',
            ],
        ],
        [
            'name' => 'contaminated_default',
            'statusName' => 'contaminated',
            'visibility' => 'mush',
            'type' => 'charge_status_config',
            'chargeVisibility' => 'mush',
            'chargeStrategy' => 'none',
            'maxCharge' => null,
            'startCharge' => 0,
            'dischargeStrategies' => ['none'],
            'autoRemove' => false,
            'modifierConfigs' => [],
            'actionConfigs' => [],
        ],
        [
            'name' => 'drug_eaten_default',
            'statusName' => 'drug_eaten',
            'visibility' => 'hidden',
            'type' => 'charge_status_config',
            'chargeVisibility' => 'hidden',
            'chargeStrategy' => 'cycle_decrement',
            'maxCharge' => 1,
            'startCharge' => 1,
            'dischargeStrategies' => ['none'],
            'autoRemove' => true,
            'modifierConfigs' => [],
            'actionConfigs' => [],
        ],
        [
            'name' => 'did_the_thing_default',
            'statusName' => 'did_the_thing',
            'visibility' => 'hidden',
            'type' => 'charge_status_config',
            'chargeVisibility' => 'hidden',
            'chargeStrategy' => 'daily_decrement',
            'maxCharge' => 1,
            'startCharge' => 1,
            'dischargeStrategies' => ['none'],
            'autoRemove' => true,
            'modifierConfigs' => [],
            'actionConfigs' => [],
        ],
        [
            'name' => 'did_boring_speech_default',
            'statusName' => 'did_boring_speech',
            'visibility' => 'hidden',
            'type' => 'charge_status_config',
            'chargeVisibility' => 'hidden',
            'chargeStrategy' => 'daily_decrement',
            'maxCharge' => 1,
            'startCharge' => 1,
            'dischargeStrategies' => ['none'],
            'autoRemove' => true,
            'modifierConfigs' => [],
            'actionConfigs' => [],
        ],
        [
            'name' => 'already_washed_in_the_sink_default',
            'statusName' => 'already_washed_in_the_sink',
            'visibility' => 'hidden',
            'type' => 'charge_status_config',
            'chargeVisibility' => 'hidden',
            'chargeStrategy' => 'daily_decrement',
            'maxCharge' => 1,
            'startCharge' => 1,
            'dischargeStrategies' => ['none'],
            'autoRemove' => true,
            'modifierConfigs' => [],
            'actionConfigs' => [],
        ],
        [
            'name' => 'updating_default',
            'statusName' => 'updating',
            'visibility' => 'public',
            'type' => 'charge_status_config',
            'chargeVisibility' => 'public',
            'chargeStrategy' => 'cycle_decrement',
            'maxCharge' => 4,
            'startCharge' => 4,
            'dischargeStrategies' => ['none'],
            'autoRemove' => true,
            'modifierConfigs' => [],
            'actionConfigs' => [],
        ],
        [
            'name' => HunterStatusEnum::ASTEROID_TRUCE_CYCLES . '_default',
            'statusName' => HunterStatusEnum::ASTEROID_TRUCE_CYCLES,
            'visibility' => VisibilityEnum::PUBLIC,
            'type' => 'charge_status_config',
            'chargeVisibility' => VisibilityEnum::PUBLIC,
            'chargeStrategy' => 'cycle_decrement',
            'maxCharge' => 6,
            'startCharge' => 6,
            'dischargeStrategies' => ['none'],
            'autoRemove' => true,
            'modifierConfigs' => [],
            'actionConfigs' => [],
        ],
        [
            'name' => PlayerStatusEnum::HAS_REJUVENATED . '_default',
            'statusName' => PlayerStatusEnum::HAS_REJUVENATED,
            'visibility' => VisibilityEnum::HIDDEN,
            'type' => 'charge_status_config',
            'chargeVisibility' => VisibilityEnum::HIDDEN,
            'chargeStrategy' => ChargeStrategyTypeEnum::DAILY_DECREMENT,
            'maxCharge' => 1,
            'startCharge' => 1,
            'dischargeStrategies' => ['none'],
            'autoRemove' => true,
            'modifierConfigs' => [],
            'actionConfigs' => [],
        ],
        [
            'name' => EquipmentStatusEnum::PATROL_SHIP_ARMOR . '_default',
            'statusName' => EquipmentStatusEnum::PATROL_SHIP_ARMOR,
            'visibility' => VisibilityEnum::PUBLIC,
            'type' => 'charge_status_config',
            'chargeVisibility' => VisibilityEnum::HIDDEN,
            'chargeStrategy' => ChargeStrategyTypeEnum::NONE,
            'maxCharge' => 10,
            'startCharge' => 10,
            'dischargeStrategies' => [ChargeStrategyTypeEnum::NONE],
            'autoRemove' => false,
            'modifierConfigs' => [],
            'actionConfigs' => [],
        ],
        [
            'name' => EquipmentStatusEnum::PATROL_SHIP_ARMOR . '_pasiphae_default',
            'statusName' => EquipmentStatusEnum::PATROL_SHIP_ARMOR,
            'visibility' => VisibilityEnum::PUBLIC,
            'type' => 'charge_status_config',
            'chargeVisibility' => VisibilityEnum::HIDDEN,
            'chargeStrategy' => ChargeStrategyTypeEnum::NONE,
            'maxCharge' => 12,
            'startCharge' => 12,
            'dischargeStrategies' => [ChargeStrategyTypeEnum::NONE],
            'autoRemove' => false,
            'modifierConfigs' => [],
            'actionConfigs' => [],
        ],
        [
            'name' => 'traveling_default',
            'statusName' => 'traveling',
            'visibility' => 'public',
            'type' => 'charge_status_config',
            'chargeVisibility' => VisibilityEnum::HIDDEN,
            'chargeStrategy' => ChargeStrategyTypeEnum::CYCLE_DECREMENT,
            'maxCharge' => 1,
            'startCharge' => 1,
            'dischargeStrategies' => [ChargeStrategyTypeEnum::NONE],
            'autoRemove' => true,
            'modifierConfigs' => [],
            'actionConfigs' => [],
        ],
        [
            'name' => 'no_gravity_repaired_default',
            'statusName' => 'no_gravity_repaired',
            'visibility' => 'hidden',
            'type' => 'charge_status_config',
            'chargeVisibility' => VisibilityEnum::HIDDEN,
            'chargeStrategy' => ChargeStrategyTypeEnum::CYCLE_DECREMENT,
            'maxCharge' => 1,
            'startCharge' => 1,
            'dischargeStrategies' => [ChargeStrategyTypeEnum::NONE],
            'autoRemove' => true,
            'modifierConfigs' => [
                'modifier_for_daedalus_-1movementPoint_on_event_action_movement_conversion',
            ],
            'actionConfigs' => [],
        ],
        [
            'name' => 'no_gravity_default',
            'statusName' => 'no_gravity',
            'visibility' => 'hidden',
            'type' => 'status_config',
            'modifierConfigs' => [
                'modifier_for_daedalus_-1movementPoint_on_change.variable_if_reason_new_cycle',
                'modifier_for_daedalus_-1movementPoint_on_event_action_movement_conversion',
            ],
            'actionConfigs' => [],
        ],
        [
            'name' => 'in_orbit_default',
            'statusName' => 'in_orbit',
            'visibility' => 'public',
            'type' => 'status_config',
            'modifierConfigs' => [
                'modifier_for_daedalus_-1actionPoint_on_action_analyze_planet',
                'modifier_for_daedalus_+1sector_revealed_on_action_analyze_planet',
            ],
            'actionConfigs' => [],
        ],
        [
            'name' => 'exploration_oxygen_default',
            'statusName' => 'exploration_oxygen',
            'visibility' => 'hidden',
            'type' => 'charge_status_config',
            'chargeVisibility' => VisibilityEnum::HIDDEN,
            'chargeStrategy' => ChargeStrategyTypeEnum::NONE,
            'maxCharge' => 24,
            'startCharge' => 0,
            'dischargeStrategies' => [ChargeStrategyTypeEnum::NONE],
            'autoRemove' => false,
            'modifierConfigs' => [],
            'actionConfigs' => [],
        ],
        [
            'name' => 'exploration_fuel_default',
            'statusName' => 'exploration_fuel',
            'visibility' => 'hidden',
            'type' => 'charge_status_config',
            'chargeVisibility' => VisibilityEnum::HIDDEN,
            'chargeStrategy' => ChargeStrategyTypeEnum::NONE,
            'maxCharge' => 32,
            'startCharge' => 0,
            'dischargeStrategies' => [ChargeStrategyTypeEnum::NONE],
            'autoRemove' => false,
            'modifierConfigs' => [],
            'actionConfigs' => [],
        ],
        [
            'name' => HunterStatusEnum::TRUCE_CYCLES . '_default',
            'statusName' => HunterStatusEnum::TRUCE_CYCLES,
            'visibility' => VisibilityEnum::HIDDEN,
            'type' => 'charge_status_config',
            'chargeVisibility' => VisibilityEnum::HIDDEN,
            'chargeStrategy' => 'cycle_decrement',
            'maxCharge' => 2,
            'startCharge' => 2,
            'dischargeStrategies' => ['none'],
            'autoRemove' => true,
            'modifierConfigs' => [],
            'actionConfigs' => [],
        ],
        [
            'name' => 'following_hunters_default',
            'statusName' => 'following_hunters',
            'visibility' => 'hidden',
            'type' => 'charge_status_config',
            'chargeVisibility' => VisibilityEnum::HIDDEN,
            'chargeStrategy' => ChargeStrategyTypeEnum::NONE,
            'maxCharge' => null,
            'startCharge' => 0,
            'dischargeStrategies' => [ChargeStrategyTypeEnum::NONE],
            'autoRemove' => false,
            'modifierConfigs' => [],
            'actionConfigs' => [],
        ],
        [
            'name' => SkillEnum::SHOOTER . '_alpha',
            'statusName' => SkillEnum::SHOOTER,
            'visibility' => VisibilityEnum::PUBLIC,
            'type' => 'charge_status_config',
            'chargeVisibility' => VisibilityEnum::PRIVATE,
            'chargeStrategy' => ChargeStrategyTypeEnum::SPECIALIST_POINTS_INCREMENT,
            'maxCharge' => 4,
            'startCharge' => 4,
            'dischargeStrategies' => [ModifierNameEnum::SHOOTER_SPECIALIST_POINT],
            'autoRemove' => true,
            'modifierConfigs' => [
                'modifier_shooter_specialist_point',
            ],
            'actionConfigs' => [],
        ],
        [
            'name' => SkillEnum::PILOT . '_alpha',
            'statusName' => SkillEnum::PILOT,
            'visibility' => VisibilityEnum::PUBLIC,
            'type' => 'status_config',
            'modifierConfigs' => [
                'modifier_pilot_always_critical_success_piloting',
                'modifier_pilot_increased_shoot_hunter_chances',
            ],
            'actionConfigs' => [],
        ],
        [
            'name' => 'astronavigation_neron_cpu_priority_default',
            'statusName' => 'astronavigation_neron_cpu_priority',
            'visibility' => VisibilityEnum::HIDDEN,
            'type' => 'status_config',
            'modifierConfigs' => [
                'modifier_for_daedalus_+1sector_revealed_on_action_analyze_planet',
            ],
            'actionConfigs' => [],
        ],
        [
            'name' => 'defence_neron_cpu_priority_default',
            'statusName' => 'defence_neron_cpu_priority',
            'visibility' => VisibilityEnum::HIDDEN,
            'type' => 'status_config',
            'modifierConfigs' => [
                'modifier_for_daedalus_random50_+1_charge_turret_on_recharge',
                'modifier_for_daedalus_increase_turret_max_charges',
            ],
            'actionConfigs' => [],
        ],
        [
            'name' => 'changed_cpu_priority_default',
            'statusName' => 'changed_cpu_priority',
            'visibility' => 'hidden',
            'type' => 'charge_status_config',
            'chargeVisibility' => 'hidden',
            'chargeStrategy' => 'daily_decrement',
            'maxCharge' => 1,
            'startCharge' => 1,
            'dischargeStrategies' => ['none'],
            'autoRemove' => true,
            'modifierConfigs' => [],
            'actionConfigs' => [],
        ],
        [
            'name' => SkillEnum::TECHNICIAN,
            'statusName' => SkillEnum::TECHNICIAN,
            'visibility' => VisibilityEnum::PUBLIC,
            'type' => 'charge_status_config',
            'chargeVisibility' => VisibilityEnum::PRIVATE,
            'chargeStrategy' => ChargeStrategyTypeEnum::SPECIALIST_POINTS_INCREMENT,
            'maxCharge' => 2,
            'startCharge' => 2,
            'dischargeStrategies' => [ModifierNameEnum::SPECIALIST_POINT_ENGINEER],
            'autoRemove' => true,
            'modifierConfigs' => [
                'modifier_specialist_point_engineer',
                'modifier_technician_double_repair_and_renovate_chance',
            ],
            'actionConfigs' => [],
        ],
        [
            'name' => SkillEnum::CONCEPTOR,
            'statusName' => SkillEnum::CONCEPTOR,
            'visibility' => VisibilityEnum::PUBLIC,
            'type' => 'charge_status_config',
            'chargeVisibility' => VisibilityEnum::PRIVATE,
            'chargeStrategy' => ChargeStrategyTypeEnum::SPECIALIST_POINTS_INCREMENT,
            'maxCharge' => 4,
            'startCharge' => 4,
            'dischargeStrategies' => [ModifierNameEnum::SPECIALIST_POINT_CORE],
            'autoRemove' => true,
            'modifierConfigs' => [
                'modifier_specialist_point_core',
            ],
        ],
        [
            'name' => DaedalusStatusEnum::AUTO_WATERING_KILLED_FIRES . '_default',
            'statusName' => DaedalusStatusEnum::AUTO_WATERING_KILLED_FIRES,
            'visibility' => 'hidden',
            'type' => 'charge_status_config',
            'chargeVisibility' => 'hidden',
            'chargeStrategy' => ChargeStrategyTypeEnum::NONE,
            'maxCharge' => null,
            'startCharge' => 1,
            'dischargeStrategies' => ['none'],
            'autoRemove' => false,
            'modifierConfigs' => [],
        ],
        [
            'name' => EquipmentStatusEnum::ELECTRIC_CHARGES . '_' . ItemEnum::SUPPORT_DRONE . '_default',
            'statusName' => EquipmentStatusEnum::ELECTRIC_CHARGES,
            'visibility' => 'hidden',
            'type' => 'charge_status_config',
            'chargeVisibility' => 'hidden',
            'chargeStrategy' => 'cycle_increment',
            'maxCharge' => null,
            'startCharge' => 0,
            'dischargeStrategies' => ['none'],
            'autoRemove' => false,
            'modifierConfigs' => [],
        ],
    ];
}
