<?php

namespace Mush\Status\ConfigData;

use Mush\Game\Enum\VisibilityEnum;
use Mush\Status\Enum\HunterStatusEnum;

/** @codeCoverageIgnore */
class StatusConfigData
{
    public static array $dataArray = [
        [
            'name' => 'alien_artefact_default',
            'statusName' => 'alien_artefact',
            'visibility' => 'public',
            'type' => 'status_config',
            'chargeVisibility' => null,
            'chargeStrategy' => 'none',
            'maxCharge' => null,
            'startCharge' => null,
            'dischargeStrategy' => 'none',
            'autoRemove' => null,
            'modifierConfigs' => [],
        ],
        [
            'name' => 'heavy_default',
            'statusName' => 'heavy',
            'visibility' => 'public',
            'type' => 'status_config',
            'chargeVisibility' => null,
            'chargeStrategy' => 'none',
            'maxCharge' => null,
            'startCharge' => null,
            'dischargeStrategy' => 'none',
            'autoRemove' => null,
            'modifierConfigs' => [],
        ],
        [
            'name' => 'module_access_default',
            'statusName' => 'module_access',
            'visibility' => 'public',
            'type' => 'status_config',
            'chargeVisibility' => null,
            'chargeStrategy' => 'none',
            'maxCharge' => null,
            'startCharge' => null,
            'dischargeStrategy' => 'none',
            'autoRemove' => null,
            'modifierConfigs' => [],
        ],
        [
            'name' => 'hidden_default',
            'statusName' => 'hidden',
            'visibility' => 'private',
            'type' => 'status_config',
            'chargeVisibility' => null,
            'chargeStrategy' => 'none',
            'maxCharge' => null,
            'startCharge' => null,
            'dischargeStrategy' => 'none',
            'autoRemove' => null,
            'modifierConfigs' => [],
        ],
        [
            'name' => 'broken_default',
            'statusName' => 'broken',
            'visibility' => 'public',
            'type' => 'status_config',
            'chargeVisibility' => null,
            'chargeStrategy' => 'none',
            'maxCharge' => null,
            'startCharge' => null,
            'dischargeStrategy' => 'none',
            'autoRemove' => null,
            'modifierConfigs' => [],
        ],
        [
            'name' => 'unstable_default',
            'statusName' => 'unstable',
            'visibility' => 'public',
            'type' => 'status_config',
            'chargeVisibility' => null,
            'chargeStrategy' => 'none',
            'maxCharge' => null,
            'startCharge' => null,
            'dischargeStrategy' => 'none',
            'autoRemove' => null,
            'modifierConfigs' => [],
        ],
        [
            'name' => 'hazardous_default',
            'statusName' => 'hazardous',
            'visibility' => 'public',
            'type' => 'status_config',
            'chargeVisibility' => null,
            'chargeStrategy' => 'none',
            'maxCharge' => null,
            'startCharge' => null,
            'dischargeStrategy' => 'none',
            'autoRemove' => null,
            'modifierConfigs' => [],
        ],
        [
            'name' => 'decomposing_default',
            'statusName' => 'decomposing',
            'visibility' => 'public',
            'type' => 'status_config',
            'chargeVisibility' => null,
            'chargeStrategy' => 'none',
            'maxCharge' => null,
            'startCharge' => null,
            'dischargeStrategy' => 'none',
            'autoRemove' => null,
            'modifierConfigs' => [],
        ],
        [
            'name' => 'frozen_default',
            'statusName' => 'frozen',
            'visibility' => 'public',
            'type' => 'status_config',
            'chargeVisibility' => null,
            'chargeStrategy' => 'none',
            'maxCharge' => null,
            'startCharge' => null,
            'dischargeStrategy' => 'none',
            'autoRemove' => null,
            'modifierConfigs' => [
                'modifier_for_equipment_+1actionPoint_on_consume',
            ],
        ],
        [
            'name' => 'plant_thirsty_default',
            'statusName' => 'plant_thirsty',
            'visibility' => 'public',
            'type' => 'status_config',
            'chargeVisibility' => null,
            'chargeStrategy' => 'none',
            'maxCharge' => null,
            'startCharge' => null,
            'dischargeStrategy' => 'none',
            'autoRemove' => null,
            'modifierConfigs' => [],
        ],
        [
            'name' => 'plant_dry_default',
            'statusName' => 'plant_dry',
            'visibility' => 'public',
            'type' => 'status_config',
            'chargeVisibility' => null,
            'chargeStrategy' => 'none',
            'maxCharge' => null,
            'startCharge' => null,
            'dischargeStrategy' => 'none',
            'autoRemove' => null,
            'modifierConfigs' => [],
        ],
        [
            'name' => 'plant_diseased_default',
            'statusName' => 'plant_diseased',
            'visibility' => 'public',
            'type' => 'status_config',
            'chargeVisibility' => null,
            'chargeStrategy' => 'none',
            'maxCharge' => null,
            'startCharge' => null,
            'dischargeStrategy' => 'none',
            'autoRemove' => null,
            'modifierConfigs' => [],
        ],
        [
            'name' => 'document_content_default',
            'statusName' => 'document_content',
            'visibility' => 'hidden',
            'type' => 'status_config',
            'chargeVisibility' => null,
            'chargeStrategy' => 'none',
            'maxCharge' => null,
            'startCharge' => null,
            'dischargeStrategy' => 'none',
            'autoRemove' => null,
            'modifierConfigs' => [],
        ],
        [
            'name' => 'reinforced_default',
            'statusName' => 'reinforced',
            'visibility' => 'hidden',
            'type' => 'status_config',
            'chargeVisibility' => null,
            'chargeStrategy' => 'none',
            'maxCharge' => null,
            'startCharge' => null,
            'dischargeStrategy' => 'none',
            'autoRemove' => null,
            'modifierConfigs' => [],
        ],
        [
            'name' => 'antisocial_default',
            'statusName' => 'antisocial',
            'visibility' => 'public',
            'type' => 'status_config',
            'chargeVisibility' => null,
            'chargeStrategy' => 'none',
            'maxCharge' => null,
            'startCharge' => null,
            'dischargeStrategy' => 'none',
            'autoRemove' => null,
            'modifierConfigs' => [
                'antisocial_modifier_for_player_-1moralPoint_on_new_cycle_if_player_in_room_not_alone',
            ],
        ],
        [
            'name' => 'berzerk_default',
            'statusName' => 'berzerk',
            'visibility' => 'public',
            'type' => 'status_config',
            'chargeVisibility' => null,
            'chargeStrategy' => 'none',
            'maxCharge' => null,
            'startCharge' => null,
            'dischargeStrategy' => 'none',
            'autoRemove' => null,
            'modifierConfigs' => [],
        ],
        [
            'name' => 'brainsync_default',
            'statusName' => 'brainsync',
            'visibility' => 'public',
            'type' => 'status_config',
            'chargeVisibility' => null,
            'chargeStrategy' => 'none',
            'maxCharge' => null,
            'startCharge' => null,
            'dischargeStrategy' => 'none',
            'autoRemove' => null,
            'modifierConfigs' => [],
        ],
        [
            'name' => 'burdened_default',
            'statusName' => 'burdened',
            'visibility' => 'public',
            'type' => 'status_config',
            'chargeVisibility' => null,
            'chargeStrategy' => 'none',
            'maxCharge' => null,
            'startCharge' => null,
            'dischargeStrategy' => 'none',
            'autoRemove' => null,
            'modifierConfigs' => [
                'modifier_for_player_+2movementPoint_on_move',
            ],
        ],
        [
            'name' => 'demoralized_default',
            'statusName' => 'demoralized',
            'visibility' => 'private',
            'type' => 'status_config',
            'chargeVisibility' => null,
            'chargeStrategy' => 'none',
            'maxCharge' => null,
            'startCharge' => null,
            'dischargeStrategy' => 'none',
            'autoRemove' => null,
            'modifierConfigs' => [
                'modifier_for_player_+30percentage_on_cycle_disease',
            ],
        ],
        [
            'name' => 'dirty_default',
            'statusName' => 'dirty',
            'visibility' => 'public',
            'type' => 'status_config',
            'chargeVisibility' => null,
            'chargeStrategy' => 'none',
            'maxCharge' => null,
            'startCharge' => null,
            'dischargeStrategy' => 'none',
            'autoRemove' => null,
            'modifierConfigs' => [],
        ],
        [
            'name' => 'disabled_default',
            'statusName' => 'disabled',
            'visibility' => 'public',
            'type' => 'status_config',
            'chargeVisibility' => null,
            'chargeStrategy' => 'none',
            'maxCharge' => null,
            'startCharge' => null,
            'dischargeStrategy' => 'none',
            'autoRemove' => null,
            'modifierConfigs' => [
                'modifier_for_player_-1movementPoint_on_move_if_player_in_room_not_alone',
                'modifier_for_player_-2movementPoint_on_event_action_movement_conversion',
            ],
        ],
        [
            'name' => 'focused_default',
            'statusName' => 'focused',
            'visibility' => 'public',
            'type' => 'status_config',
            'chargeVisibility' => null,
            'chargeStrategy' => 'none',
            'maxCharge' => null,
            'startCharge' => null,
            'dischargeStrategy' => 'none',
            'autoRemove' => null,
            'modifierConfigs' => [],
        ],
        [
            'name' => 'full_stomach_default',
            'statusName' => 'full_stomach',
            'visibility' => 'private',
            'type' => 'status_config',
            'chargeVisibility' => null,
            'chargeStrategy' => 'none',
            'maxCharge' => null,
            'startCharge' => null,
            'dischargeStrategy' => 'none',
            'autoRemove' => null,
            'modifierConfigs' => [],
        ],
        [
            'name' => 'gagged_default',
            'statusName' => 'gagged',
            'visibility' => 'public',
            'type' => 'status_config',
            'chargeVisibility' => null,
            'chargeStrategy' => 'none',
            'maxCharge' => null,
            'startCharge' => null,
            'dischargeStrategy' => 'none',
            'autoRemove' => null,
            'modifierConfigs' => [],
        ],
        [
            'name' => 'germaphobe_default',
            'statusName' => 'germaphobe',
            'visibility' => 'public',
            'type' => 'status_config',
            'chargeVisibility' => null,
            'chargeStrategy' => 'none',
            'maxCharge' => null,
            'startCharge' => null,
            'dischargeStrategy' => 'none',
            'autoRemove' => null,
            'modifierConfigs' => [],
        ],
        [
            'name' => 'guardian_default',
            'statusName' => 'guardian',
            'visibility' => 'public',
            'type' => 'status_config',
            'chargeVisibility' => null,
            'chargeStrategy' => 'none',
            'maxCharge' => null,
            'startCharge' => null,
            'dischargeStrategy' => 'none',
            'autoRemove' => null,
            'modifierConfigs' => [],
        ],
        [
            'name' => 'highly_inactive_default',
            'statusName' => 'highly_inactive',
            'visibility' => 'public',
            'type' => 'status_config',
            'chargeVisibility' => null,
            'chargeStrategy' => 'none',
            'maxCharge' => null,
            'startCharge' => null,
            'dischargeStrategy' => 'none',
            'autoRemove' => null,
            'modifierConfigs' => [],
        ],
        [
            'name' => 'hyperactive_default',
            'statusName' => 'hyperactive',
            'visibility' => 'public',
            'type' => 'status_config',
            'chargeVisibility' => null,
            'chargeStrategy' => 'none',
            'maxCharge' => null,
            'startCharge' => null,
            'dischargeStrategy' => 'none',
            'autoRemove' => null,
            'modifierConfigs' => [],
        ],
        [
            'name' => 'immunized_default',
            'statusName' => 'immunized',
            'visibility' => 'public',
            'type' => 'status_config',
            'chargeVisibility' => null,
            'chargeStrategy' => 'none',
            'maxCharge' => null,
            'startCharge' => null,
            'dischargeStrategy' => 'none',
            'autoRemove' => null,
            'modifierConfigs' => [],
        ],
        [
            'name' => 'inactive_default',
            'statusName' => 'inactive',
            'visibility' => 'public',
            'type' => 'status_config',
            'chargeVisibility' => null,
            'chargeStrategy' => 'none',
            'maxCharge' => null,
            'startCharge' => null,
            'dischargeStrategy' => 'none',
            'autoRemove' => null,
            'modifierConfigs' => [],
        ],
        [
            'name' => 'lost_default',
            'statusName' => 'lost',
            'visibility' => 'public',
            'type' => 'status_config',
            'chargeVisibility' => null,
            'chargeStrategy' => 'none',
            'maxCharge' => null,
            'startCharge' => null,
            'dischargeStrategy' => 'none',
            'autoRemove' => null,
            'modifierConfigs' => [
                'modifier_for_player_-1moralPoint_on_new_cycle',
            ],
        ],
        [
            'name' => 'lying_down_default',
            'statusName' => 'lying_down',
            'visibility' => 'public',
            'type' => 'status_config',
            'chargeVisibility' => null,
            'chargeStrategy' => 'none',
            'maxCharge' => null,
            'startCharge' => null,
            'dischargeStrategy' => 'none',
            'autoRemove' => null,
            'modifierConfigs' => [
                'lying_down_modifier_for_player_+1actionPoint_on_new_cycle',
            ],
        ],
        [
            'name' => 'multi_teamster_default',
            'statusName' => 'multi_teamster',
            'visibility' => 'public',
            'type' => 'status_config',
            'chargeVisibility' => null,
            'chargeStrategy' => 'none',
            'maxCharge' => null,
            'startCharge' => null,
            'dischargeStrategy' => 'none',
            'autoRemove' => null,
            'modifierConfigs' => [],
        ],
        [
            'name' => 'outcast_default',
            'statusName' => 'outcast',
            'visibility' => 'public',
            'type' => 'status_config',
            'chargeVisibility' => null,
            'chargeStrategy' => 'none',
            'maxCharge' => null,
            'startCharge' => null,
            'dischargeStrategy' => 'none',
            'autoRemove' => null,
            'modifierConfigs' => [],
        ],
        [
            'name' => 'pacifist_default',
            'statusName' => 'pacifist',
            'visibility' => 'public',
            'type' => 'status_config',
            'chargeVisibility' => null,
            'chargeStrategy' => 'none',
            'maxCharge' => null,
            'startCharge' => null,
            'dischargeStrategy' => 'none',
            'autoRemove' => null,
            'modifierConfigs' => [
                'modifier_for_place_+2actionPoint_on_action_aggressive',
            ],
        ],
        [
            'name' => 'pregnant_default',
            'statusName' => 'pregnant',
            'visibility' => 'public',
            'type' => 'status_config',
            'chargeVisibility' => null,
            'chargeStrategy' => 'none',
            'maxCharge' => null,
            'startCharge' => null,
            'dischargeStrategy' => 'none',
            'autoRemove' => null,
            'modifierConfigs' => [],
        ],
        [
            'name' => 'starving_default',
            'statusName' => 'starving',
            'visibility' => 'private',
            'type' => 'status_config',
            'chargeVisibility' => null,
            'chargeStrategy' => 'none',
            'maxCharge' => null,
            'startCharge' => null,
            'dischargeStrategy' => 'none',
            'autoRemove' => null,
            'modifierConfigs' => [
                'starving_for_player_-1healthPoint_on_new_cycle',
            ],
        ],
        [
            'name' => 'stuck_in_the_ship_default',
            'statusName' => 'stuck_in_the_ship',
            'visibility' => 'public',
            'type' => 'status_config',
            'chargeVisibility' => null,
            'chargeStrategy' => 'none',
            'maxCharge' => null,
            'startCharge' => null,
            'dischargeStrategy' => 'none',
            'autoRemove' => null,
            'modifierConfigs' => [],
        ],
        [
            'name' => 'suicidal_default',
            'statusName' => 'suicidal',
            'visibility' => 'private',
            'type' => 'status_config',
            'chargeVisibility' => null,
            'chargeStrategy' => 'none',
            'maxCharge' => null,
            'startCharge' => null,
            'dischargeStrategy' => 'none',
            'autoRemove' => null,
            'modifierConfigs' => [
                'modifier_for_player_+30percentage_on_cycle_disease',
            ],
        ],
        [
            'name' => 'WATCHED_PUBLIC_BROADCAST_default',
            'statusName' => 'WATCHED_PUBLIC_BROADCAST',
            'visibility' => 'hidden',
            'type' => 'status_config',
            'chargeVisibility' => null,
            'chargeStrategy' => 'none',
            'maxCharge' => null,
            'startCharge' => null,
            'dischargeStrategy' => 'none',
            'autoRemove' => null,
            'modifierConfigs' => [],
        ],
        [
            'name' => 'talkie_screwed_default',
            'statusName' => 'talkie_screwed',
            'visibility' => 'hidden',
            'type' => 'status_config',
            'chargeVisibility' => null,
            'chargeStrategy' => 'none',
            'maxCharge' => null,
            'startCharge' => null,
            'dischargeStrategy' => 'none',
            'autoRemove' => null,
            'modifierConfigs' => [],
        ],
        [
            'name' => 'attempt_default',
            'statusName' => 'attempt',
            'visibility' => 'hidden',
            'type' => 'charge_status_config',
            'chargeVisibility' => 'hidden',
            'chargeStrategy' => 'none',
            'maxCharge' => 0,
            'startCharge' => 0,
            'dischargeStrategy' => 'none',
            'autoRemove' => false,
            'modifierConfigs' => [],
        ],
        [
            'name' => 'electric_charges_microwave_default',
            'statusName' => 'electric_charges',
            'visibility' => 'public',
            'type' => 'charge_status_config',
            'chargeVisibility' => 'public',
            'chargeStrategy' => 'cycle_increment',
            'maxCharge' => 4,
            'startCharge' => 1,
            'dischargeStrategy' => 'express_cook',
            'autoRemove' => false,
            'modifierConfigs' => [],
        ],
        [
            'name' => 'electric_charges_antigrav_scooter_default',
            'statusName' => 'electric_charges',
            'visibility' => 'public',
            'type' => 'charge_status_config',
            'chargeVisibility' => 'public',
            'chargeStrategy' => 'cycle_increment',
            'maxCharge' => 8,
            'startCharge' => 2,
            'dischargeStrategy' => 'event_action_movement_conversion',
            'autoRemove' => false,
            'modifierConfigs' => [],
        ],
        [
            'name' => 'electric_charges_blaster_default',
            'statusName' => 'electric_charges',
            'visibility' => 'public',
            'type' => 'charge_status_config',
            'chargeVisibility' => 'public',
            'chargeStrategy' => 'cycle_increment',
            'maxCharge' => 3,
            'startCharge' => 1,
            'dischargeStrategy' => 'shoot',
            'autoRemove' => false,
            'modifierConfigs' => [],
        ],
        [
            'name' => 'electric_charges_old_faithful_default',
            'statusName' => 'electric_charges',
            'visibility' => 'public',
            'type' => 'charge_status_config',
            'chargeVisibility' => 'public',
            'chargeStrategy' => 'cycle_increment',
            'maxCharge' => 12,
            'startCharge' => 12,
            'dischargeStrategy' => 'shoot',
            'autoRemove' => false,
            'modifierConfigs' => [],
        ],
        [
            'name' => 'electric_charges_rocket_launcher_default',
            'statusName' => 'electric_charges',
            'visibility' => 'public',
            'type' => 'charge_status_config',
            'chargeVisibility' => 'public',
            'chargeStrategy' => 'cycle_increment',
            'maxCharge' => 1,
            'startCharge' => 1,
            'dischargeStrategy' => 'shoot',
            'autoRemove' => false,
            'modifierConfigs' => [],
        ],
        [
            'name' => 'electric_charges_narcotic_distiller_default',
            'statusName' => 'electric_charges',
            'visibility' => 'hidden',
            'type' => 'charge_status_config',
            'chargeVisibility' => 'hidden',
            'chargeStrategy' => 'daily_increment',
            'maxCharge' => 1,
            'startCharge' => 1,
            'dischargeStrategy' => 'dispense',
            'autoRemove' => false,
            'modifierConfigs' => [],
        ],
        [
            'name' => 'electric_charges_coffee_machine_default',
            'statusName' => 'electric_charges',
            'visibility' => 'hidden',
            'type' => 'charge_status_config',
            'chargeVisibility' => 'hidden',
            'chargeStrategy' => 'daily_increment',
            'maxCharge' => 1,
            'startCharge' => 1,
            'dischargeStrategy' => 'coffee',
            'autoRemove' => false,
            'modifierConfigs' => [],
        ],
        [
            'name' => 'electric_charges_turret_command_default',
            'statusName' => 'electric_charges',
            'visibility' => 'public',
            'type' => 'charge_status_config',
            'chargeVisibility' => 'public',
            'chargeStrategy' => 'cycle_increment',
            'maxCharge' => 4,
            'startCharge' => 4,
            'dischargeStrategy' => 'shoot_hunter',
            'autoRemove' => false,
            'modifierConfigs' => [],
        ],
        [
            'name' => 'fire_default',
            'statusName' => 'fire',
            'visibility' => 'public',
            'type' => 'charge_status_config',
            'chargeVisibility' => 'hidden',
            'chargeStrategy' => 'cycle_increment',
            'maxCharge' => 0,
            'startCharge' => 0,
            'dischargeStrategy' => 'none',
            'autoRemove' => false,
            'modifierConfigs' => [],
        ],
        [
            'name' => 'plant_young_default',
            'statusName' => 'plant_young',
            'visibility' => 'public',
            'type' => 'charge_status_config',
            'chargeVisibility' => 'public',
            'chargeStrategy' => 'growing_plant',
            'maxCharge' => 0,
            'startCharge' => 0,
            'dischargeStrategy' => 'none',
            'autoRemove' => false,
            'modifierConfigs' => [],
        ],
        [
            'name' => 'eureka_moment_default',
            'statusName' => 'eureka_moment',
            'visibility' => 'public',
            'type' => 'charge_status_config',
            'chargeVisibility' => 'hidden',
            'chargeStrategy' => 'none',
            'maxCharge' => 0,
            'startCharge' => 0,
            'dischargeStrategy' => 'none',
            'autoRemove' => true,
            'modifierConfigs' => [],
        ],
        [
            'name' => 'first_time_default',
            'statusName' => 'first_time',
            'visibility' => 'public',
            'type' => 'charge_status_config',
            'chargeVisibility' => 'hidden',
            'chargeStrategy' => 'none',
            'maxCharge' => 0,
            'startCharge' => 1,
            'dischargeStrategy' => 'none',
            'autoRemove' => true,
            'modifierConfigs' => [],
        ],
        [
            'name' => 'mush_default',
            'statusName' => 'mush',
            'visibility' => 'mush',
            'type' => 'charge_status_config',
            'chargeVisibility' => 'hidden',
            'chargeStrategy' => 'dayly_reset',
            'maxCharge' => 1,
            'startCharge' => 1,
            'dischargeStrategy' => 'none',
            'autoRemove' => false,
            'modifierConfigs' => [
                'mush_shower_malus_for_player_set_-3healthPoint_on_post.action_if_reason_shower',
                'modifier_for_player_set_0actionPoint_on_change.variable_if_reason_consume',
                'modifier_for_player_set_0healthPoint_on_change.variable_if_reason_consume',
                'modifier_for_player_set_0moralPoint_on_change.variable_if_reason_consume',
                'modifier_for_player_set_0movementPoint_on_change.variable_if_reason_consume',
                'modifier_for_player_set_4satiety_on_change.variable_if_reason_consume',
            ],
        ],
        [
            'name' => 'contaminated_default',
            'statusName' => 'contaminated',
            'visibility' => 'mush',
            'type' => 'charge_status_config',
            'chargeVisibility' => 'mush',
            'chargeStrategy' => 'none',
            'maxCharge' => 0,
            'startCharge' => 0,
            'dischargeStrategy' => 'none',
            'autoRemove' => false,
            'modifierConfigs' => [],
        ],
        [
            'name' => 'fuel_charge_default',
            'statusName' => 'fuel_charge',
            'visibility' => 'hidden',
            'type' => 'charge_status_config',
            'chargeVisibility' => 'hidden',
            'chargeStrategy' => 'none',
            'maxCharge' => 0,
            'startCharge' => 0,
            'dischargeStrategy' => 'none',
            'autoRemove' => false,
            'modifierConfigs' => [],
        ],
        [
            'name' => 'drug_eaten_default',
            'statusName' => 'drug_eaten',
            'visibility' => 'hidden',
            'type' => 'charge_status_config',
            'chargeVisibility' => 'hidden',
            'chargeStrategy' => 'cycle_decrement',
            'maxCharge' => 0,
            'startCharge' => 2,
            'dischargeStrategy' => 'none',
            'autoRemove' => true,
            'modifierConfigs' => [],
        ],
        [
            'name' => 'did_the_thing_default',
            'statusName' => 'did_the_thing',
            'visibility' => 'hidden',
            'type' => 'charge_status_config',
            'chargeVisibility' => 'hidden',
            'chargeStrategy' => 'daily_decrement',
            'maxCharge' => 0,
            'startCharge' => 1,
            'dischargeStrategy' => 'none',
            'autoRemove' => true,
            'modifierConfigs' => [],
        ],
        [
            'name' => 'did_boring_speech_default',
            'statusName' => 'did_boring_speech',
            'visibility' => 'hidden',
            'type' => 'charge_status_config',
            'chargeVisibility' => 'hidden',
            'chargeStrategy' => 'daily_decrement',
            'maxCharge' => 0,
            'startCharge' => 1,
            'dischargeStrategy' => 'none',
            'autoRemove' => true,
            'modifierConfigs' => [],
        ],
        [
            'name' => 'already_washed_in_the_sink_default',
            'statusName' => 'already_washed_in_the_sink',
            'visibility' => 'hidden',
            'type' => 'charge_status_config',
            'chargeVisibility' => 'hidden',
            'chargeStrategy' => 'daily_decrement',
            'maxCharge' => 0,
            'startCharge' => 1,
            'dischargeStrategy' => 'none',
            'autoRemove' => true,
            'modifierConfigs' => [],
        ],
        [
            'name' => 'updating_default',
            'statusName' => 'updating',
            'visibility' => 'public',
            'type' => 'charge_status_config',
            'chargeVisibility' => 'public',
            'chargeStrategy' => 'cycle_decrement',
            'maxCharge' => 0,
            'startCharge' => 4,
            'dischargeStrategy' => 'none',
            'autoRemove' => true,
            'modifierConfigs' => [],
        ],
        [
            'name' => HunterStatusEnum::HUNTER_CHARGE . '_asteroid_default',
            'statusName' => HunterStatusEnum::HUNTER_CHARGE,
            'visibility' => VisibilityEnum::PUBLIC,
            'type' => 'charge_status_config',
            'chargeVisibility' => VisibilityEnum::PUBLIC,
            'chargeStrategy' => 'cycle_decrement',
            'maxCharge' => 0,
            'startCharge' => 6,
            'dischargeStrategy' => 'none',
            'autoRemove' => true,
            'modifierConfigs' => [],
        ],
        [
            'name' => HunterStatusEnum::HUNTER_CHARGE . '_default',
            'statusName' => HunterStatusEnum::HUNTER_CHARGE,
            'visibility' => VisibilityEnum::HIDDEN,
            'type' => 'charge_status_config',
            'chargeVisibility' => VisibilityEnum::HIDDEN,
            'chargeStrategy' => 'cycle_decrement',
            'maxCharge' => 0,
            'startCharge' => 1,
            'dischargeStrategy' => 'none',
            'autoRemove' => true,
            'modifierConfigs' => [],
        ],
    ];
}
