<?php

namespace Mush\Player\ConfigData;

use Mush\Action\Enum\ActionEnum;
use Mush\Skill\Enum\SkillName;

class CharacterConfigData
{
    public static array $dataArray = [
        [
            'name' => 'andie',
            'characterName' => 'andie',
            'skillConfigs' => [
                SkillName::PILOT,
            ],
            'maxNumberPrivateChannel' => 3,
            'maxHealthPoint' => 14,
            'maxMoralPoint' => 14,
            'maxActionPoint' => 12,
            'maxMovementPoint' => 12,
            'maxItemInInventory' => 3,
            'maxDiscoverablePlanets' => 2,
            'initHealthPoint' => 14,
            'initMoralPoint' => 7,
            'initSatiety' => 0,
            'initActionPoint' => 8,
            'initMovementPoint' => 12,
            'actions' => [
                'hit',
                'hide',
                'search',
                'heal',
                'self_heal',
                'flirt',
                'do_the_thing',
                'auto_destroy',
                'suicide',
                'kill_player',
                'rejuvenate_alpha',
                ActionEnum::RESET_SKILL_POINTS->value,
            ],
            'initDiseases' => [],
            'startingItems' => [
                'itrackie_default',
            ],
            'initStatuses' => [],
        ],
        [
            'name' => 'chao',
            'characterName' => 'chao',
            'skillConfigs' => [
                SkillName::SHOOTER,
            ],
            'maxNumberPrivateChannel' => 3,
            'maxHealthPoint' => 14,
            'maxMoralPoint' => 14,
            'maxActionPoint' => 12,
            'maxMovementPoint' => 12,
            'maxItemInInventory' => 3,
            'maxDiscoverablePlanets' => 2,
            'initHealthPoint' => 14,
            'initMoralPoint' => 7,
            'initSatiety' => 0,
            'initActionPoint' => 8,
            'initMovementPoint' => 12,
            'actions' => [
                'hit',
                'hide',
                'search',
                'heal',
                'self_heal',
                'flirt',
                'do_the_thing',
                'auto_destroy',
                'suicide',
                'kill_player',
                'rejuvenate_alpha',
                ActionEnum::RESET_SKILL_POINTS->value,
            ],
            'initDiseases' => [],
            'startingItems' => [
                'itrackie_default',
            ],
            'initStatuses' => [],
        ],
        [
            'name' => 'chun',
            'characterName' => 'chun',
            'skillConfigs' => [
                SkillName::MANKIND_ONLY_HOPE,
            ],
            'maxNumberPrivateChannel' => 3,
            'maxHealthPoint' => 14,
            'maxMoralPoint' => 14,
            'maxActionPoint' => 12,
            'maxMovementPoint' => 12,
            'maxItemInInventory' => 3,
            'maxDiscoverablePlanets' => 2,
            'initHealthPoint' => 14,
            'initMoralPoint' => 7,
            'initSatiety' => 0,
            'initActionPoint' => 8,
            'initMovementPoint' => 12,
            'actions' => [
                'hit',
                'hide',
                'search',
                'heal',
                'self_heal',
                'flirt',
                'do_the_thing',
                'auto_destroy',
                'suicide',
                'kill_player',
                'rejuvenate_alpha',
                ActionEnum::RESET_SKILL_POINTS->value,
            ],
            'initDiseases' => [],
            'startingItems' => [
                'itrackie_default',
            ],
            'initStatuses' => [
                'immunized_default',
            ],
        ],
        [
            'name' => 'derek',
            'characterName' => 'derek',
            'skillConfigs' => [
                SkillName::SHOOTER,
            ],
            'maxNumberPrivateChannel' => 3,
            'maxHealthPoint' => 14,
            'maxMoralPoint' => 14,
            'maxActionPoint' => 12,
            'maxMovementPoint' => 12,
            'maxItemInInventory' => 3,
            'maxDiscoverablePlanets' => 2,
            'initHealthPoint' => 14,
            'initMoralPoint' => 7,
            'initSatiety' => 0,
            'initActionPoint' => 8,
            'initMovementPoint' => 12,
            'actions' => [
                'hit',
                'hide',
                'search',
                'boring_speech',
                'heal',
                'self_heal',
                'flirt',
                'do_the_thing',
                'auto_destroy',
                'suicide',
                'kill_player',
                'rejuvenate_alpha',
                ActionEnum::RESET_SKILL_POINTS->value,
                ActionEnum::EXTINGUISH_MANUALLY->value,
            ],
            'initDiseases' => [],
            'startingItems' => [
                'itrackie_default',
            ],
            'initStatuses' => [
                'first_time_default',
            ],
        ],
        [
            'name' => 'eleesha',
            'characterName' => 'eleesha',
            'skillConfigs' => [
                SkillName::TECHNICIAN,
            ],
            'maxNumberPrivateChannel' => 3,
            'maxHealthPoint' => 14,
            'maxMoralPoint' => 14,
            'maxActionPoint' => 12,
            'maxMovementPoint' => 12,
            'maxItemInInventory' => 3,
            'maxDiscoverablePlanets' => 2,
            'initHealthPoint' => 14,
            'initMoralPoint' => 7,
            'initSatiety' => 0,
            'initActionPoint' => 8,
            'initMovementPoint' => 12,
            'actions' => [
                'hit',
                'hide',
                'search',
                'heal',
                'self_heal',
                'flirt',
                'extract_spore',
                'do_the_thing',
                'auto_destroy',
                'suicide',
                'kill_player',
                'rejuvenate_alpha',
                ActionEnum::RESET_SKILL_POINTS->value,
            ],
            'initDiseases' => [
                'chronic_vertigo_default',
            ],
            'startingItems' => [
                'itrackie_default',
            ],
            'initStatuses' => [],
        ],
        [
            'name' => 'finola',
            'characterName' => 'finola',
            'skillConfigs' => [],
            'maxNumberPrivateChannel' => 3,
            'maxHealthPoint' => 14,
            'maxMoralPoint' => 14,
            'maxActionPoint' => 12,
            'maxMovementPoint' => 12,
            'maxItemInInventory' => 3,
            'maxDiscoverablePlanets' => 2,
            'initHealthPoint' => 14,
            'initMoralPoint' => 7,
            'initSatiety' => 0,
            'initActionPoint' => 8,
            'initMovementPoint' => 12,
            'actions' => [
                'hit',
                'hide',
                'search',
                'heal',
                'self_heal',
                'flirt',
                'do_the_thing',
                'auto_destroy',
                'suicide',
                'kill_player',
                'rejuvenate_alpha',
                ActionEnum::RESET_SKILL_POINTS->value,
            ],
            'initDiseases' => [],
            'startingItems' => [],
            'initStatuses' => [
                'germaphobe_default',
            ],
        ],
        [
            'name' => 'frieda',
            'characterName' => 'frieda',
            'skillConfigs' => [
                SkillName::PILOT,
            ],
            'maxNumberPrivateChannel' => 3,
            'maxHealthPoint' => 14,
            'maxMoralPoint' => 14,
            'maxActionPoint' => 12,
            'maxMovementPoint' => 12,
            'maxItemInInventory' => 3,
            'maxDiscoverablePlanets' => 2,
            'initHealthPoint' => 14,
            'initMoralPoint' => 7,
            'initSatiety' => 0,
            'initActionPoint' => 8,
            'initMovementPoint' => 12,
            'actions' => [
                'hit',
                'hide',
                'search',
                'heal',
                'self_heal',
                'flirt',
                'do_the_thing',
                'auto_destroy',
                'suicide',
                'kill_player',
                'rejuvenate_alpha',
                ActionEnum::RESET_SKILL_POINTS->value,
            ],
            'initDiseases' => [],
            'startingItems' => [
                'itrackie_default',
            ],
            'initStatuses' => [],
        ],
        [
            'name' => 'gioele',
            'characterName' => 'gioele',
            'skillConfigs' => [],
            'maxNumberPrivateChannel' => 3,
            'maxHealthPoint' => 14,
            'maxMoralPoint' => 14,
            'maxActionPoint' => 12,
            'maxMovementPoint' => 12,
            'maxItemInInventory' => 3,
            'maxDiscoverablePlanets' => 2,
            'initHealthPoint' => 14,
            'initMoralPoint' => 7,
            'initSatiety' => 0,
            'initActionPoint' => 8,
            'initMovementPoint' => 12,
            'actions' => [
                'hit',
                'hide',
                'search',
                'heal',
                'self_heal',
                'flirt',
                'do_the_thing',
                'auto_destroy',
                'suicide',
                'kill_player',
                'rejuvenate_alpha',
                ActionEnum::RESET_SKILL_POINTS->value,
            ],
            'initDiseases' => [],
            'startingItems' => [
                'itrackie_default',
            ],
            'initStatuses' => [],
        ],
        [
            'name' => 'hua',
            'characterName' => 'hua',
            'skillConfigs' => [
                SkillName::PILOT,
                SkillName::TECHNICIAN,
            ],
            'maxNumberPrivateChannel' => 3,
            'maxHealthPoint' => 14,
            'maxMoralPoint' => 14,
            'maxActionPoint' => 12,
            'maxMovementPoint' => 12,
            'maxItemInInventory' => 3,
            'maxDiscoverablePlanets' => 2,
            'initHealthPoint' => 14,
            'initMoralPoint' => 7,
            'initSatiety' => 0,
            'initActionPoint' => 8,
            'initMovementPoint' => 12,
            'actions' => [
                'hit',
                'hide',
                'search',
                'heal',
                'self_heal',
                'flirt',
                'do_the_thing',
                'auto_destroy',
                'suicide',
                'kill_player',
                'rejuvenate_alpha',
                ActionEnum::RESET_SKILL_POINTS->value,
            ],
            'initDiseases' => [],
            'startingItems' => [
                'itrackie_default',
            ],
            'initStatuses' => [],
        ],
        [
            'name' => 'ian',
            'characterName' => 'ian',
            'skillConfigs' => [],
            'maxNumberPrivateChannel' => 3,
            'maxHealthPoint' => 14,
            'maxMoralPoint' => 14,
            'maxActionPoint' => 12,
            'maxMovementPoint' => 12,
            'maxItemInInventory' => 3,
            'maxDiscoverablePlanets' => 2,
            'initHealthPoint' => 14,
            'initMoralPoint' => 7,
            'initSatiety' => 0,
            'initActionPoint' => 8,
            'initMovementPoint' => 12,
            'actions' => [
                'hit',
                'hide',
                'search',
                'heal',
                'self_heal',
                'flirt',
                'do_the_thing',
                'auto_destroy',
                'suicide',
                'kill_player',
                'rejuvenate_alpha',
                ActionEnum::RESET_SKILL_POINTS->value,
                'extinguish_manually',
            ],
            'initDiseases' => [],
            'startingItems' => [
                'itrackie_default',
            ],
            'initStatuses' => [
                'pacifist_default',
            ],
        ],
        [
            'name' => 'janice',
            'characterName' => 'janice',
            'skillConfigs' => [
                SkillName::SHRINK,
            ],
            'maxNumberPrivateChannel' => 3,
            'maxHealthPoint' => 14,
            'maxMoralPoint' => 14,
            'maxActionPoint' => 12,
            'maxMovementPoint' => 12,
            'maxItemInInventory' => 3,
            'maxDiscoverablePlanets' => 2,
            'initHealthPoint' => 14,
            'initMoralPoint' => 7,
            'initSatiety' => 0,
            'initActionPoint' => 8,
            'initMovementPoint' => 12,
            'actions' => [
                'hit',
                'hide',
                'search',
                'heal',
                'self_heal',
                'flirt',
                'comfort',
                'do_the_thing',
                'auto_destroy',
                'suicide',
                'kill_player',
                'rejuvenate_alpha',
                ActionEnum::RESET_SKILL_POINTS->value,
            ],
            'initDiseases' => [],
            'startingItems' => [
                'itrackie_default',
            ],
            'initStatuses' => [],
        ],
        [
            'name' => 'jin_su',
            'characterName' => 'jin_su',
            'skillConfigs' => [
                SkillName::PILOT,
                SkillName::SHOOTER,
            ],
            'maxNumberPrivateChannel' => 3,
            'maxHealthPoint' => 14,
            'maxMoralPoint' => 14,
            'maxActionPoint' => 12,
            'maxMovementPoint' => 12,
            'maxItemInInventory' => 3,
            'maxDiscoverablePlanets' => 2,
            'initHealthPoint' => 14,
            'initMoralPoint' => 7,
            'initSatiety' => 0,
            'initActionPoint' => 8,
            'initMovementPoint' => 12,
            'actions' => [
                'hit',
                'hide',
                'search',
                'motivational_speech',
                'heal',
                'self_heal',
                'flirt',
                'do_the_thing',
                'auto_destroy',
                'suicide',
                'kill_player',
                'rejuvenate_alpha',
                ActionEnum::RESET_SKILL_POINTS->value,
            ],
            'initDiseases' => [],
            'startingItems' => [
                'itrackie_default',
            ],
            'initStatuses' => [],
        ],
        [
            'name' => 'kuan_ti',
            'characterName' => 'kuan_ti',
            'skillConfigs' => [
                SkillName::CONCEPTOR,
                SkillName::TECHNICIAN,
            ],
            'maxNumberPrivateChannel' => 3,
            'maxHealthPoint' => 14,
            'maxMoralPoint' => 14,
            'maxActionPoint' => 12,
            'maxMovementPoint' => 12,
            'maxItemInInventory' => 3,
            'maxDiscoverablePlanets' => 2,
            'initHealthPoint' => 14,
            'initMoralPoint' => 7,
            'initSatiety' => 0,
            'initActionPoint' => 8,
            'initMovementPoint' => 12,
            'actions' => [
                'hit',
                'hide',
                'search',
                'heal',
                'self_heal',
                'flirt',
                'do_the_thing',
                'auto_destroy',
                'suicide',
                'kill_player',
                'rejuvenate_alpha',
                ActionEnum::RESET_SKILL_POINTS->value,
                'motivational_speech',
            ],
            'initDiseases' => [],
            'startingItems' => [
                'itrackie_default',
            ],
            'initStatuses' => [],
        ],
        [
            'name' => 'paola',
            'characterName' => 'paola',
            'skillConfigs' => [
                SkillName::SHOOTER,
            ],
            'maxNumberPrivateChannel' => 3,
            'maxHealthPoint' => 14,
            'maxMoralPoint' => 14,
            'maxActionPoint' => 12,
            'maxMovementPoint' => 12,
            'maxItemInInventory' => 3,
            'maxDiscoverablePlanets' => 2,
            'initHealthPoint' => 14,
            'initMoralPoint' => 7,
            'initSatiety' => 0,
            'initActionPoint' => 8,
            'initMovementPoint' => 12,
            'actions' => [
                'hit',
                'hide',
                'search',
                'heal',
                'self_heal',
                'flirt',
                'do_the_thing',
                'auto_destroy',
                'suicide',
                'kill_player',
                'rejuvenate_alpha',
                ActionEnum::RESET_SKILL_POINTS->value,
            ],
            'initDiseases' => [],
            'startingItems' => [
                'itrackie_default',
            ],
            'initStatuses' => [],
        ],
        [
            'name' => 'raluca',
            'characterName' => 'raluca',
            'skillConfigs' => [
                SkillName::TECHNICIAN,
                SkillName::CONCEPTOR,
            ],
            'maxNumberPrivateChannel' => 3,
            'maxHealthPoint' => 14,
            'maxMoralPoint' => 14,
            'maxActionPoint' => 12,
            'maxMovementPoint' => 12,
            'maxItemInInventory' => 3,
            'maxDiscoverablePlanets' => 2,
            'initHealthPoint' => 14,
            'initMoralPoint' => 7,
            'initSatiety' => 0,
            'initActionPoint' => 8,
            'initMovementPoint' => 12,
            'actions' => [
                'hit',
                'hide',
                'search',
                'heal',
                'self_heal',
                'flirt',
                'do_the_thing',
                'auto_destroy',
                'suicide',
                'kill_player',
                'rejuvenate_alpha',
                ActionEnum::RESET_SKILL_POINTS->value,
            ],
            'initDiseases' => [],
            'startingItems' => [
                'itrackie_default',
            ],
            'initStatuses' => [
                'antisocial_default',
            ],
        ],
        [
            'name' => 'roland',
            'characterName' => 'roland',
            'skillConfigs' => [
                SkillName::PILOT,
                SkillName::SHOOTER,
            ],
            'maxNumberPrivateChannel' => 3,
            'maxHealthPoint' => 14,
            'maxMoralPoint' => 14,
            'maxActionPoint' => 12,
            'maxMovementPoint' => 12,
            'maxItemInInventory' => 3,
            'maxDiscoverablePlanets' => 2,
            'initHealthPoint' => 14,
            'initMoralPoint' => 7,
            'initSatiety' => 0,
            'initActionPoint' => 8,
            'initMovementPoint' => 12,
            'actions' => [
                'hit',
                'hide',
                'search',
                'heal',
                'self_heal',
                'flirt',
                'do_the_thing',
                'auto_destroy',
                'extinguish_manually',
                'suicide',
                'kill_player',
                'rejuvenate_alpha',
                ActionEnum::RESET_SKILL_POINTS->value,
            ],
            'initDiseases' => [],
            'startingItems' => [
                'itrackie_default',
            ],
            'initStatuses' => [],
        ],
        [
            'name' => 'stephen',
            'characterName' => 'stephen',
            'skillConfigs' => [
                SkillName::SHOOTER,
            ],
            'maxNumberPrivateChannel' => 3,
            'maxHealthPoint' => 14,
            'maxMoralPoint' => 14,
            'maxActionPoint' => 12,
            'maxMovementPoint' => 12,
            'maxItemInInventory' => 3,
            'maxDiscoverablePlanets' => 2,
            'initHealthPoint' => 14,
            'initMoralPoint' => 7,
            'initSatiety' => 0,
            'initActionPoint' => 8,
            'initMovementPoint' => 12,
            'actions' => [
                'hit',
                'hide',
                'search',
                'heal',
                'self_heal',
                'flirt',
                'do_the_thing',
                'auto_destroy',
                'suicide',
                'kill_player',
                'rejuvenate_alpha',
                ActionEnum::RESET_SKILL_POINTS->value,
            ],
            'initDiseases' => [],
            'startingItems' => [
                'itrackie_default',
            ],
            'initStatuses' => [],
        ],
        [
            'name' => 'terrence',
            'characterName' => 'terrence',
            'skillConfigs' => [
                SkillName::TECHNICIAN,
                SkillName::PILOT,
                SkillName::SHOOTER,
            ],
            'maxNumberPrivateChannel' => 3,
            'maxHealthPoint' => 14,
            'maxMoralPoint' => 14,
            'maxActionPoint' => 12,
            'maxMovementPoint' => 12,
            'maxItemInInventory' => 3,
            'maxDiscoverablePlanets' => 2,
            'initHealthPoint' => 14,
            'initMoralPoint' => 7,
            'initSatiety' => 0,
            'initActionPoint' => 8,
            'initMovementPoint' => 12,
            'actions' => [
                'hit',
                'hide',
                'search',
                'heal',
                'self_heal',
                'flirt',
                'do_the_thing',
                'auto_destroy',
                'suicide',
                'kill_player',
                'rejuvenate_alpha',
                ActionEnum::RESET_SKILL_POINTS->value,
            ],
            'initDiseases' => [],
            'startingItems' => [
                'itrackie_default',
            ],
            'initStatuses' => [
                'disabled_default',
            ],
        ],
    ];

    public static function getByName(string $name): array
    {
        return current(array_filter(self::$dataArray, static fn (array $data) => $data['name'] === $name));
    }
}
