<?php

namespace Mush\Player\ConfigData;

class CharacterConfigData
{
    public static array $dataArray = [
        [
            'name' => 'andie',
            'characterName' => 'andie',
            'skills' => [
                'confident',
                'devotion',
                'expert',
                'pilot',
                'polyvalent',
            ],
            'maxNumberPrivateChannel' => 3,
            'maxHealthPoint' => 14,
            'maxMoralPoint' => 14,
            'maxActionPoint' => 12,
            'maxMovementPoint' => 12,
            'maxItemInInventory' => 3,
            'maxDiscoverablePlanets' => 2,
            'initHealthPoint' => 14,
            'initMoralPoint' => 7,
            'initSatiety' => 0,
            'initActionPoint' => 8,
            'initMovementPoint' => 12,
            'actions' => [
                'hit',
                'hide',
                'search',
                'eat_spore',
                'report_fire',
                'spread_fire',
                'extract_spore',
                'get_up',
                'comfort',
                'extinguish_manually',
                'motivational_speech',
                'boring_speech',
                'heal',
                'self_heal',
                'infect',
                'flirt',
                'do_the_thing',
                'make_sick',
                'screw_talkie',
                'ungag',
                'auto_destroy',
                'suicide',
                'surgery',
                'kill_player',
                'rejuvenate_alpha',
                'teleport',
            ],
            'initDiseases' => [],
            'startingItems' => [
                'itrackie_default',
            ],
            'initStatuses' => [],
        ],
        [
            'name' => 'chao',
            'characterName' => 'chao',
            'skills' => [
                'crazy_eye',
                'intimidating',
                'shooter',
                'survivalist',
                'torturer',
                'wrestler',
            ],
            'maxNumberPrivateChannel' => 3,
            'maxHealthPoint' => 14,
            'maxMoralPoint' => 14,
            'maxActionPoint' => 12,
            'maxMovementPoint' => 12,
            'maxItemInInventory' => 3,
            'maxDiscoverablePlanets' => 2,
            'initHealthPoint' => 14,
            'initMoralPoint' => 7,
            'initSatiety' => 0,
            'initActionPoint' => 8,
            'initMovementPoint' => 12,
            'actions' => [
                'hit',
                'hide',
                'search',
                'eat_spore',
                'report_fire',
                'spread_fire',
                'extract_spore',
                'get_up',
                'comfort',
                'extinguish_manually',
                'motivational_speech',
                'boring_speech',
                'heal',
                'self_heal',
                'infect',
                'flirt',
                'do_the_thing',
                'make_sick',
                'screw_talkie',
                'ungag',
                'auto_destroy',
                'suicide',
                'surgery',
                'kill_player',
                'rejuvenate_alpha',
                'teleport',
            ],
            'initDiseases' => [],
            'startingItems' => [
                'itrackie_default',
            ],
            'initStatuses' => [],
        ],
        [
            'name' => 'chun',
            'characterName' => 'chun',
            'skills' => [
                'lethargy',
                'mankind_only_hope',
                'nurse',
                'premonition',
                'sneak',
            ],
            'maxNumberPrivateChannel' => 3,
            'maxHealthPoint' => 14,
            'maxMoralPoint' => 14,
            'maxActionPoint' => 12,
            'maxMovementPoint' => 12,
            'maxItemInInventory' => 3,
            'maxDiscoverablePlanets' => 2,
            'initHealthPoint' => 14,
            'initMoralPoint' => 7,
            'initSatiety' => 0,
            'initActionPoint' => 8,
            'initMovementPoint' => 12,
            'actions' => [
                'hit',
                'hide',
                'search',
                'eat_spore',
                'report_fire',
                'spread_fire',
                'extract_spore',
                'get_up',
                'comfort',
                'extinguish_manually',
                'motivational_speech',
                'boring_speech',
                'heal',
                'self_heal',
                'infect',
                'flirt',
                'do_the_thing',
                'make_sick',
                'screw_talkie',
                'ungag',
                'auto_destroy',
                'suicide',
                'surgery',
                'kill_player',
                'rejuvenate_alpha',
                'teleport',
            ],
            'initDiseases' => [],
            'startingItems' => [
                'itrackie_default',
            ],
            'initStatuses' => [
                'immunized_default',
            ],
        ],
        [
            'name' => 'derek',
            'characterName' => 'derek',
            'skills' => [
                'firefighter',
                'motivator',
                'shooter',
                'wrestler',
                'hygienist',
            ],
            'maxNumberPrivateChannel' => 3,
            'maxHealthPoint' => 14,
            'maxMoralPoint' => 14,
            'maxActionPoint' => 12,
            'maxMovementPoint' => 12,
            'maxItemInInventory' => 3,
            'maxDiscoverablePlanets' => 2,
            'initHealthPoint' => 14,
            'initMoralPoint' => 7,
            'initSatiety' => 0,
            'initActionPoint' => 8,
            'initMovementPoint' => 12,
            'actions' => [
                'hit',
                'hide',
                'search',
                'eat_spore',
                'report_fire',
                'spread_fire',
                'extract_spore',
                'get_up',
                'comfort',
                'extinguish_manually',
                'motivational_speech',
                'boring_speech',
                'heal',
                'self_heal',
                'infect',
                'flirt',
                'do_the_thing',
                'make_sick',
                'screw_talkie',
                'ungag',
                'auto_destroy',
                'suicide',
                'surgery',
                'kill_player',
                'rejuvenate_alpha',
                'teleport',
            ],
            'initDiseases' => [],
            'startingItems' => [
                'itrackie_default',
            ],
            'initStatuses' => [
                'first_time_default',
            ],
        ],
        [
            'name' => 'eleesha',
            'characterName' => 'eleesha',
            'skills' => [
                'determined',
                'it_expert',
                'observant',
                'polymath',
                'technician',
                'tracker',
            ],
            'maxNumberPrivateChannel' => 3,
            'maxHealthPoint' => 14,
            'maxMoralPoint' => 14,
            'maxActionPoint' => 12,
            'maxMovementPoint' => 12,
            'maxItemInInventory' => 3,
            'maxDiscoverablePlanets' => 2,
            'initHealthPoint' => 14,
            'initMoralPoint' => 7,
            'initSatiety' => 0,
            'initActionPoint' => 8,
            'initMovementPoint' => 12,
            'actions' => [
                'hit',
                'hide',
                'search',
                'eat_spore',
                'report_fire',
                'spread_fire',
                'extract_spore',
                'get_up',
                'comfort',
                'extinguish_manually',
                'motivational_speech',
                'boring_speech',
                'heal',
                'self_heal',
                'infect',
                'flirt',
                'do_the_thing',
                'make_sick',
                'screw_talkie',
                'ungag',
                'auto_destroy',
                'suicide',
                'surgery',
                'kill_player',
                'rejuvenate_alpha',
                'teleport',
            ],
            'initDiseases' => [
                'chronic_vertigo_default',
            ],
            'startingItems' => [
                'itrackie_default',
            ],
            'initStatuses' => [],
        ],
        [
            'name' => 'finola',
            'characterName' => 'finola',
            'skills' => [
                'biologist',
                'diplomat',
                'medic',
                'nurse',
                'ocd',
            ],
            'maxNumberPrivateChannel' => 3,
            'maxHealthPoint' => 14,
            'maxMoralPoint' => 14,
            'maxActionPoint' => 12,
            'maxMovementPoint' => 12,
            'maxItemInInventory' => 3,
            'maxDiscoverablePlanets' => 2,
            'initHealthPoint' => 14,
            'initMoralPoint' => 7,
            'initSatiety' => 0,
            'initActionPoint' => 8,
            'initMovementPoint' => 12,
            'actions' => [
                'hit',
                'hide',
                'search',
                'eat_spore',
                'report_fire',
                'spread_fire',
                'extract_spore',
                'get_up',
                'comfort',
                'extinguish_manually',
                'motivational_speech',
                'boring_speech',
                'heal',
                'self_heal',
                'infect',
                'flirt',
                'do_the_thing',
                'make_sick',
                'screw_talkie',
                'ungag',
                'auto_destroy',
                'suicide',
                'surgery',
                'kill_player',
                'rejuvenate_alpha',
                'teleport',
            ],
            'initDiseases' => [],
            'startingItems' => [],
            'initStatuses' => [
                'germaphobe_default',
            ],
        ],
        [
            'name' => 'frieda',
            'characterName' => 'frieda',
            'skills' => [
                'antique_perfume',
                'astrophysicist',
                'it_expert',
                'pilot',
                ' radio_expert',
                'survivalist',
            ],
            'maxNumberPrivateChannel' => 3,
            'maxHealthPoint' => 14,
            'maxMoralPoint' => 14,
            'maxActionPoint' => 12,
            'maxMovementPoint' => 12,
            'maxItemInInventory' => 3,
            'maxDiscoverablePlanets' => 2,
            'initHealthPoint' => 14,
            'initMoralPoint' => 7,
            'initSatiety' => 0,
            'initActionPoint' => 8,
            'initMovementPoint' => 12,
            'actions' => [
                'hit',
                'hide',
                'search',
                'eat_spore',
                'report_fire',
                'spread_fire',
                'extract_spore',
                'get_up',
                'comfort',
                'extinguish_manually',
                'motivational_speech',
                'boring_speech',
                'heal',
                'self_heal',
                'infect',
                'flirt',
                'do_the_thing',
                'make_sick',
                'screw_talkie',
                'ungag',
                'auto_destroy',
                'suicide',
                'surgery',
                'kill_player',
                'rejuvenate_alpha',
                'teleport',
            ],
            'initDiseases' => [],
            'startingItems' => [
                'itrackie_default',
            ],
            'initStatuses' => [],
        ],
        [
            'name' => 'gioele',
            'characterName' => 'gioele',
            'skills' => [
                'astrophysicist',
                'caffeine_junkie',
                'panic',
                'paranoid',
                'solid',
                'victimizer',
            ],
            'maxNumberPrivateChannel' => 3,
            'maxHealthPoint' => 14,
            'maxMoralPoint' => 14,
            'maxActionPoint' => 12,
            'maxMovementPoint' => 12,
            'maxItemInInventory' => 3,
            'maxDiscoverablePlanets' => 2,
            'initHealthPoint' => 14,
            'initMoralPoint' => 7,
            'initSatiety' => 0,
            'initActionPoint' => 8,
            'initMovementPoint' => 12,
            'actions' => [
                'hit',
                'hide',
                'search',
                'eat_spore',
                'report_fire',
                'spread_fire',
                'extract_spore',
                'get_up',
                'comfort',
                'extinguish_manually',
                'motivational_speech',
                'boring_speech',
                'heal',
                'self_heal',
                'infect',
                'flirt',
                'do_the_thing',
                'make_sick',
                'screw_talkie',
                'ungag',
                'auto_destroy',
                'suicide',
                'surgery',
                'kill_player',
                'rejuvenate_alpha',
                'teleport',
            ],
            'initDiseases' => [],
            'startingItems' => [
                'itrackie_default',
            ],
            'initStatuses' => [],
        ],
        [
            'name' => 'hua',
            'characterName' => 'hua',
            'skills' => [
                'botanist',
                'determined',
                'pilot',
                'survivalist',
                'technician',
                'u_turn',
            ],
            'maxNumberPrivateChannel' => 3,
            'maxHealthPoint' => 14,
            'maxMoralPoint' => 14,
            'maxActionPoint' => 12,
            'maxMovementPoint' => 12,
            'maxItemInInventory' => 3,
            'maxDiscoverablePlanets' => 2,
            'initHealthPoint' => 14,
            'initMoralPoint' => 7,
            'initSatiety' => 0,
            'initActionPoint' => 8,
            'initMovementPoint' => 12,
            'actions' => [
                'hit',
                'hide',
                'search',
                'eat_spore',
                'report_fire',
                'spread_fire',
                'extract_spore',
                'get_up',
                'comfort',
                'extinguish_manually',
                'motivational_speech',
                'boring_speech',
                'heal',
                'self_heal',
                'infect',
                'flirt',
                'do_the_thing',
                'make_sick',
                'screw_talkie',
                'ungag',
                'auto_destroy',
                'suicide',
                'surgery',
                'kill_player',
                'rejuvenate_alpha',
                'teleport',
            ],
            'initDiseases' => [],
            'startingItems' => [
                'itrackie_default',
            ],
            'initStatuses' => [],
        ],
        [
            'name' => 'ian',
            'characterName' => 'ian',
            'skills' => [
                'biologist',
                'botanist',
                'firefighter',
                'frugivore',
                'green_thumb',
                'mycologist',
            ],
            'maxNumberPrivateChannel' => 3,
            'maxHealthPoint' => 14,
            'maxMoralPoint' => 14,
            'maxActionPoint' => 12,
            'maxMovementPoint' => 12,
            'maxItemInInventory' => 3,
            'maxDiscoverablePlanets' => 2,
            'initHealthPoint' => 14,
            'initMoralPoint' => 7,
            'initSatiety' => 0,
            'initActionPoint' => 8,
            'initMovementPoint' => 12,
            'actions' => [
                'hit',
                'hide',
                'search',
                'eat_spore',
                'report_fire',
                'spread_fire',
                'extract_spore',
                'get_up',
                'comfort',
                'extinguish_manually',
                'motivational_speech',
                'boring_speech',
                'heal',
                'self_heal',
                'infect',
                'flirt',
                'do_the_thing',
                'make_sick',
                'screw_talkie',
                'ungag',
                'auto_destroy',
                'suicide',
                'surgery',
                'kill_player',
                'rejuvenate_alpha',
                'teleport',
            ],
            'initDiseases' => [],
            'startingItems' => [
                'itrackie_default',
            ],
            'initStatuses' => [
                'pacifist_default',
            ],
        ],
        [
            'name' => 'janice',
            'characterName' => 'janice',
            'skills' => [
                'diplomat',
                'it_expert',
                'neron_only_friend',
                ' radio_expert',
                'self_sacrifice',
                'shrink',
            ],
            'maxNumberPrivateChannel' => 3,
            'maxHealthPoint' => 14,
            'maxMoralPoint' => 14,
            'maxActionPoint' => 12,
            'maxMovementPoint' => 12,
            'maxItemInInventory' => 3,
            'maxDiscoverablePlanets' => 2,
            'initHealthPoint' => 14,
            'initMoralPoint' => 7,
            'initSatiety' => 0,
            'initActionPoint' => 8,
            'initMovementPoint' => 12,
            'actions' => [
                'hit',
                'hide',
                'search',
                'eat_spore',
                'report_fire',
                'spread_fire',
                'extract_spore',
                'get_up',
                'comfort',
                'extinguish_manually',
                'motivational_speech',
                'boring_speech',
                'heal',
                'self_heal',
                'infect',
                'flirt',
                'do_the_thing',
                'make_sick',
                'screw_talkie',
                'ungag',
                'auto_destroy',
                'suicide',
                'surgery',
                'kill_player',
                'rejuvenate_alpha',
                'teleport',
            ],
            'initDiseases' => [],
            'startingItems' => [
                'itrackie_default',
            ],
            'initStatuses' => [],
        ],
        [
            'name' => 'jin_su',
            'characterName' => 'jin_su',
            'skills' => [
                'cold_blooded',
                'leader',
                'logistics_expert',
                'pilot',
                'shooter',
                'strateguru',
            ],
            'maxNumberPrivateChannel' => 3,
            'maxHealthPoint' => 14,
            'maxMoralPoint' => 14,
            'maxActionPoint' => 12,
            'maxMovementPoint' => 12,
            'maxItemInInventory' => 3,
            'maxDiscoverablePlanets' => 2,
            'initHealthPoint' => 14,
            'initMoralPoint' => 7,
            'initSatiety' => 0,
            'initActionPoint' => 8,
            'initMovementPoint' => 12,
            'actions' => [
                'hit',
                'hide',
                'search',
                'eat_spore',
                'report_fire',
                'spread_fire',
                'extract_spore',
                'get_up',
                'comfort',
                'extinguish_manually',
                'motivational_speech',
                'boring_speech',
                'heal',
                'self_heal',
                'infect',
                'flirt',
                'do_the_thing',
                'make_sick',
                'screw_talkie',
                'ungag',
                'auto_destroy',
                'suicide',
                'surgery',
                'kill_player',
                'rejuvenate_alpha',
                'teleport',
            ],
            'initDiseases' => [],
            'startingItems' => [
                'itrackie_default',
            ],
            'initStatuses' => [],
        ],
        [
            'name' => 'kuan_ti',
            'characterName' => 'kuan_ti',
            'skills' => [
                'astrophysicist',
                'designer',
                'leader',
                'politician',
                'technician',
                'optimist',
            ],
            'maxNumberPrivateChannel' => 3,
            'maxHealthPoint' => 14,
            'maxMoralPoint' => 14,
            'maxActionPoint' => 12,
            'maxMovementPoint' => 12,
            'maxItemInInventory' => 3,
            'maxDiscoverablePlanets' => 2,
            'initHealthPoint' => 14,
            'initMoralPoint' => 7,
            'initSatiety' => 0,
            'initActionPoint' => 8,
            'initMovementPoint' => 12,
            'actions' => [
                'hit',
                'hide',
                'search',
                'eat_spore',
                'report_fire',
                'spread_fire',
                'extract_spore',
                'get_up',
                'comfort',
                'extinguish_manually',
                'motivational_speech',
                'boring_speech',
                'heal',
                'self_heal',
                'infect',
                'flirt',
                'do_the_thing',
                'make_sick',
                'screw_talkie',
                'ungag',
                'auto_destroy',
                'suicide',
                'surgery',
                'kill_player',
                'rejuvenate_alpha',
                'teleport',
            ],
            'initDiseases' => [],
            'startingItems' => [
                'itrackie_default',
            ],
            'initStatuses' => [],
        ],
        [
            'name' => 'paola',
            'characterName' => 'paola',
            'skills' => [
                'biologist',
                'gunner',
                'logistics_expert',
                ' radio_expert',
                'rebel',
                'shooter',
            ],
            'maxNumberPrivateChannel' => 3,
            'maxHealthPoint' => 14,
            'maxMoralPoint' => 14,
            'maxActionPoint' => 12,
            'maxMovementPoint' => 12,
            'maxItemInInventory' => 3,
            'maxDiscoverablePlanets' => 2,
            'initHealthPoint' => 14,
            'initMoralPoint' => 7,
            'initSatiety' => 0,
            'initActionPoint' => 8,
            'initMovementPoint' => 12,
            'actions' => [
                'hit',
                'hide',
                'search',
                'eat_spore',
                'report_fire',
                'spread_fire',
                'extract_spore',
                'get_up',
                'comfort',
                'extinguish_manually',
                'motivational_speech',
                'boring_speech',
                'heal',
                'self_heal',
                'infect',
                'flirt',
                'do_the_thing',
                'make_sick',
                'screw_talkie',
                'ungag',
                'auto_destroy',
                'suicide',
                'surgery',
                'kill_player',
                'rejuvenate_alpha',
                'teleport',
            ],
            'initDiseases' => [],
            'startingItems' => [
                'itrackie_default',
            ],
            'initStatuses' => [],
        ],
        [
            'name' => 'raluca',
            'characterName' => 'raluca',
            'skills' => [
                'designer',
                'detached_crewmember',
                'genius',
                'physicist',
                'technician',
            ],
            'maxNumberPrivateChannel' => 3,
            'maxHealthPoint' => 14,
            'maxMoralPoint' => 14,
            'maxActionPoint' => 12,
            'maxMovementPoint' => 12,
            'maxItemInInventory' => 3,
            'maxDiscoverablePlanets' => 2,
            'initHealthPoint' => 14,
            'initMoralPoint' => 7,
            'initSatiety' => 0,
            'initActionPoint' => 8,
            'initMovementPoint' => 12,
            'actions' => [
                'hit',
                'hide',
                'search',
                'eat_spore',
                'report_fire',
                'spread_fire',
                'extract_spore',
                'get_up',
                'comfort',
                'extinguish_manually',
                'motivational_speech',
                'boring_speech',
                'heal',
                'self_heal',
                'infect',
                'flirt',
                'do_the_thing',
                'make_sick',
                'screw_talkie',
                'ungag',
                'auto_destroy',
                'suicide',
                'surgery',
                'kill_player',
                'rejuvenate_alpha',
                'teleport',
            ],
            'initDiseases' => [],
            'startingItems' => [
                'itrackie_default',
            ],
            'initStatuses' => [
                'antisocial_default',
            ],
        ],
        [
            'name' => 'roland',
            'characterName' => 'roland',
            'skills' => [
                'creative',
                'firefighter',
                'pilot',
                'shooter',
                'sprinter',
                'optimist',
            ],
            'maxNumberPrivateChannel' => 3,
            'maxHealthPoint' => 14,
            'maxMoralPoint' => 14,
            'maxActionPoint' => 12,
            'maxMovementPoint' => 12,
            'maxItemInInventory' => 3,
            'maxDiscoverablePlanets' => 2,
            'initHealthPoint' => 14,
            'initMoralPoint' => 7,
            'initSatiety' => 0,
            'initActionPoint' => 8,
            'initMovementPoint' => 12,
            'actions' => [
                'hit',
                'hide',
                'search',
                'eat_spore',
                'report_fire',
                'spread_fire',
                'extract_spore',
                'get_up',
                'comfort',
                'extinguish_manually',
                'motivational_speech',
                'boring_speech',
                'heal',
                'self_heal',
                'infect',
                'flirt',
                'do_the_thing',
                'make_sick',
                'screw_talkie',
                'ungag',
                'auto_destroy',
                'suicide',
                'surgery',
                'kill_player',
                'rejuvenate_alpha',
                'teleport',
            ],
            'initDiseases' => [],
            'startingItems' => [
                'itrackie_default',
            ],
            'initStatuses' => [],
        ],
        [
            'name' => 'stephen',
            'characterName' => 'stephen',
            'skills' => [
                'apprentice',
                ' chef',
                'creative',
                'opportunist',
                'shooter',
                'solid',
            ],
            'maxNumberPrivateChannel' => 3,
            'maxHealthPoint' => 14,
            'maxMoralPoint' => 14,
            'maxActionPoint' => 12,
            'maxMovementPoint' => 12,
            'maxItemInInventory' => 3,
            'maxDiscoverablePlanets' => 2,
            'initHealthPoint' => 14,
            'initMoralPoint' => 7,
            'initSatiety' => 0,
            'initActionPoint' => 8,
            'initMovementPoint' => 12,
            'actions' => [
                'hit',
                'hide',
                'search',
                'eat_spore',
                'report_fire',
                'spread_fire',
                'extract_spore',
                'get_up',
                'comfort',
                'extinguish_manually',
                'motivational_speech',
                'boring_speech',
                'heal',
                'self_heal',
                'infect',
                'flirt',
                'do_the_thing',
                'make_sick',
                'screw_talkie',
                'ungag',
                'auto_destroy',
                'suicide',
                'surgery',
                'kill_player',
                'rejuvenate_alpha',
                'teleport',
            ],
            'initDiseases' => [],
            'startingItems' => [
                'itrackie_default',
            ],
            'initStatuses' => [],
        ],
        [
            'name' => 'terrence',
            'characterName' => 'terrence',
            'skills' => [
                'it_expert',
                'metalworker',
                'pilot',
                'robotics_expert',
                'shooter',
                'technician',
            ],
            'maxNumberPrivateChannel' => 3,
            'maxHealthPoint' => 14,
            'maxMoralPoint' => 14,
            'maxActionPoint' => 12,
            'maxMovementPoint' => 12,
            'maxItemInInventory' => 3,
            'maxDiscoverablePlanets' => 2,
            'initHealthPoint' => 14,
            'initMoralPoint' => 7,
            'initSatiety' => 0,
            'initActionPoint' => 8,
            'initMovementPoint' => 12,
            'actions' => [
                'hit',
                'hide',
                'search',
                'eat_spore',
                'report_fire',
                'spread_fire',
                'extract_spore',
                'get_up',
                'comfort',
                'extinguish_manually',
                'motivational_speech',
                'boring_speech',
                'heal',
                'self_heal',
                'infect',
                'flirt',
                'do_the_thing',
                'make_sick',
                'screw_talkie',
                'ungag',
                'auto_destroy',
                'suicide',
                'surgery',
                'kill_player',
                'rejuvenate_alpha',
                'teleport',
            ],
            'initDiseases' => [],
            'startingItems' => [
                'itrackie_default',
            ],
            'initStatuses' => [
                'disabled_default',
            ],
        ],
    ];
}
