import { getImgUrl } from "@/utils/getImgUrl";
import { EmoteCharacterEnum } from "@/enums/emotes/characters.enum";
import { UiIconEnum } from "@/enums/ui_icon.enum";


export enum EmoteIconEnum {
    ATTENTION = 'ic_attention',
    BROKEN = 'ic_alert',
    REPORTED = 'ic_reported',
    COMMS = 'ic_comms',
    COMMS_OK = 'ic_comms_ok',
    DOOR = 'ic_door',
    FIRE = 'ic_fire',
    HUNGER = 'ic_hunger',
    HUNTER = 'ic_hunter',
    OXYGEN = 'ic_oxygen',
    GRAVITY_OFF = 'ic_gravity_off',
    GRAVITY_REBOOT = 'ic_gravity_reboot',
    INFO = 'ic_info',
    LIGHTBULB = 'ic_lightbulb',
    COVERT = 'ic_covert',
    DISCRETE = 'ic_discrete',
    SPOTTED = 'ic_spotted',
    PERSONAL = 'ic_personal',
    PRIVATE = 'ic_private',
    CAT = 'ic_cat',
    CAT2 = 'ic_cat2',
    DOG = 'ic_dog',
    MANKAROG = 'ic_mankarog',
    COFFEE = 'ic_coffee',
    COFFEE_PLUS = 'ic_coffee_plus',
    EXPLO_FEED = 'ic_explo_feed',
    EXPLORER = 'ic_explorer',
    GAME_WITHOUT_SLEEP = 'ic_game_without_sleep',
    NOTE = 'ic_note',
    NOTEBOOK = 'ic_notebook',
    BOOK = 'ic_book',
    WALL = 'ic_wall',
    PLANET_SCANNED = 'ic_planet_scanned',
    SOL = 'ic_sol',
    EDEN = 'ic_eden',
    EDEN_MUSH = 'ic_eden_mush',
    RATION = 'ic_ration',
    RATION_COOKED = 'ic_ration_cooked',
    RATION2 = 'ic_ration2',
    RESEARCH = 'ic_research',
    SERUM = 'ic_serum',
    MYCOALARM = 'ic_mycoalarm',
    SPORE_SUCKER = 'ic_spore_sucker',
    PHEROMODEM = 'ic_pheromodem',
    SEARCH = 'ic_search',
    SIGNAL_FIRE = 'ic_signal_fire',
    BIN = 'ic_bin',
    PILL = 'ic_pill',
    PLUS_BASIC = 'ic_plus_basic',
    PLUS_GOLD = 'ic_plus_gold',
    PLUS_RED = 'ic_plus_red',
    DEAD = 'ic_dead',
    EXTINGUISHER = 'ic_extinguisher',
    GRENADE = 'ic_grenade',
    SOLDIER = 'ic_soldier',
    TALKIE = 'ic_talkie',
    WATCH = 'ic_watch',
    POINT1 = 'ic_point1',
    POINT2 = 'ic_point2',
    OFFLINE = 'ic_offline',
    ONLINE = 'ic_online',
    LEFT = 'ic_left',
    RIGHT = 'ic_right',
    BETA = 'ic_beta',
    CALENDAR = 'ic_calendar',
    CHECK = 'ic_check',
    UNCHECK = 'ic_uncheck',
    CLOSE = 'ic_close',
    FAVORITE = 'ic_favorite',
    UNFAVORITE = 'ic_unfavorite',
    LESS = 'ic_less',
    MORE = 'ic_more',
    STAR = 'ic_star',

}

export const EmoteIconAliases: { [index: string]: string } = {
    ['broken_equipments']: EmoteIconEnum.BROKEN,
    ['beta']: EmoteIconEnum.BETA,
    ['cat']: EmoteIconEnum.CAT,
    ['coffee']: EmoteIconEnum.COFFEE,
    ['communications_down']: EmoteIconEnum.COMMS,
    ['dead']: EmoteIconEnum.DEAD,
    ['dog']: EmoteIconEnum.DOG,
    ['broken_doors']: EmoteIconEnum.DOOR,
    ['eden']: EmoteIconEnum.EDEN,
    ['fire']: EmoteIconEnum.FIRE,
    ['fires']: EmoteIconEnum.FIRE,
    ['low_hull']: EmoteIconEnum.FIRE,
    ['grenade']: EmoteIconEnum.GRENADE,
    ['no_gravity']: EmoteIconEnum.GRAVITY_OFF,
    ['gravity_reboot']: EmoteIconEnum.GRAVITY_REBOOT,
    ['hunger']: EmoteIconEnum.HUNGER,
    ['hunter']: EmoteIconEnum.HUNTER,
    ['no_alert']: EmoteIconEnum.INFO,
    ['left']: EmoteIconEnum.LEFT,
    ['tip']: EmoteIconEnum.LIGHTBULB,
    ['mycoalarm']: EmoteIconEnum.MYCOALARM,
    ['offline']: EmoteIconEnum.OFFLINE,
    ['online']: EmoteIconEnum.ONLINE,
    ['low_oxygen']: EmoteIconEnum.OXYGEN,
    ['pill']: EmoteIconEnum.PILL,
    ['pills']: EmoteIconEnum.PILL,
    ['planet']: EmoteIconEnum.PLANET_SCANNED,
    ['point']: EmoteIconEnum.POINT1,
    ['ration']: EmoteIconEnum.RATION,
    ['signal_equip']: EmoteIconEnum.REPORTED,
    ['right']: EmoteIconEnum.RIGHT,
    ['serum']: EmoteIconEnum.SERUM,
    ['retro_fungal_serum']: EmoteIconEnum.SERUM,
    ['srf']: EmoteIconEnum.SERUM,
    ['rfs']: EmoteIconEnum.SERUM,
    ['spore_sucker']: EmoteIconEnum.SPORE_SUCKER,
    ['talkie']: EmoteIconEnum.TALKIE,
    ['book_open']: EmoteIconEnum.WALL,
    ['wall']: EmoteIconEnum.WALL,
    ['casio']: EmoteIconEnum.WATCH
};


export const EmoteIconIcons: {[index: string]: {img: string; max_height: string;}}= {
    [EmoteIconEnum.ATTENTION]: { img: getImgUrl('att.png'), max_height: "1.2em" },
    [EmoteIconEnum.BROKEN]: { img: getImgUrl('alerts/broken.png'), max_height: "1.2em" },
    [EmoteIconEnum.REPORTED]: { img: getImgUrl('achievements/reported.png'), max_height: "1.2em" },
    [EmoteIconEnum.COMMS]: { img: getImgUrl('alerts/comm.png'), max_height: "1.2em" },
    [EmoteIconEnum.COMMS_OK]: { img: getImgUrl('achievements/revolution.png'), max_height: "1.2em" },
    [EmoteIconEnum.DOOR]: { img: getImgUrl('alerts/door.png'), max_height: "1.2em" },
    [EmoteIconEnum.FIRE]: { img: getImgUrl('alerts/fire.png'), max_height: "1.2em" },
    [EmoteIconEnum.EXTINGUISHER]: { img: getImgUrl('ui_icons/extinguisher.png'), max_height: "1.2em" },
    [EmoteIconEnum.HUNGER]: { img: getImgUrl('alerts/hunger.png'), max_height: "1.2em" },
    [EmoteIconEnum.HUNTER]: { img: getImgUrl('alerts/hunter.png'), max_height: "1.2em" },
    [EmoteIconEnum.OXYGEN]: { img: getImgUrl('alerts/o2alert.png'), max_height: "1.2em" },
    [EmoteIconEnum.GRAVITY_OFF]: { img: getImgUrl('alerts/simulator.png'), max_height: "1.2em" },
    [EmoteIconEnum.GRAVITY_REBOOT]: { img: getImgUrl('alerts/simulator_reboot.png'), max_height: "1.2em" },
    [EmoteIconEnum.INFO]: { img: getImgUrl('alerts/infoalert.png'), max_height: "1.2em" },
    [EmoteIconEnum.LIGHTBULB]: { img: getImgUrl('comms/tip.png'), max_height: "1.2em" },
    [EmoteIconEnum.COVERT]: { img: getImgUrl('comms/covert.png'), max_height: "1.2em" },
    [EmoteIconEnum.DISCRETE]: { img: getImgUrl('comms/discrete.png'), max_height: "1.2em" },
    [EmoteIconEnum.SPOTTED]: { img: getImgUrl('comms/spotted.png'), max_height: "1.2em" },
    [EmoteIconEnum.PERSONAL]: { img: getImgUrl('comms/personal.png'), max_height: "1.2em" },
    [EmoteIconEnum.PRIVATE]: { img: getImgUrl('comms/private.png'), max_height: "1.2em" },
    [EmoteIconEnum.CAT]: { img: getImgUrl('char/body/cat.png'), max_height: "1.2em" },
    [EmoteIconEnum.CAT2]: { img: getImgUrl('achievements/cat.png'), max_height: "1.2em" },
    [EmoteIconEnum.DOG]: { img: getImgUrl('ui_icons/dog.png'), max_height: "1.2em" },
    [EmoteIconEnum.MANKAROG]: { img: getImgUrl('emotes/mankarog.png'), max_height: "1.2em" },
    [EmoteIconEnum.COFFEE]: { img: getImgUrl('ui_icons/coffee.png'), max_height: "1.2em" },
    [EmoteIconEnum.COFFEE_PLUS]: { img: getImgUrl('achievements/coffeeplus.png'), max_height: "1.2em" },
    [EmoteIconEnum.EXPLO_FEED]: { img: getImgUrl('achievements/explo_feed.png'), max_height: "1.2em" },
    [EmoteIconEnum.EXPLORER]: { img: getImgUrl('achievements/explorer.png'), max_height: "1.2em" },
    [EmoteIconEnum.GAME_WITHOUT_SLEEP]: { img: getImgUrl('achievements/game_without_sleep.png'), max_height: "1.2em" },
    [EmoteIconEnum.NOTE]: { img: getImgUrl('notes.gif'), max_height: "1.2em" },
    [EmoteIconEnum.NOTEBOOK]: { img: getImgUrl('achievements/notebook.png'), max_height: "1.2em" },
    [EmoteIconEnum.BOOK]: { img: getImgUrl('ui_icons/book.png'), max_height: "1.2em" },
    [EmoteIconEnum.WALL]: { img: getImgUrl('comms/wall.png'), max_height: "1.2em" },
    [EmoteIconEnum.PLANET_SCANNED]: { img: getImgUrl('achievements/planet_scanned.png'), max_height: "1.2em" },
    [EmoteIconEnum.SOL]: { img: getImgUrl('achievements/sol.png'), max_height: "1.2em" },
    [EmoteIconEnum.EDEN]: { img: getImgUrl('ui_icons/eden1.png'), max_height: "1.2em" },
    [EmoteIconEnum.EDEN_MUSH]: { img: getImgUrl('ui_icons/eden2.png'), max_height: "1.2em" },
    [EmoteIconEnum.RATION]: { img: getImgUrl('ui_icons/ration.png'), max_height: "1.2em" },
    [EmoteIconEnum.RATION_COOKED]: { img: getImgUrl('achievements/rationcooked.png'), max_height: "1.2em" },
    [EmoteIconEnum.RATION2]: { img: getImgUrl('ui_icons/ration_2.png'), max_height: "1.2em" },
    [EmoteIconEnum.RESEARCH]: { img: getImgUrl('ui_icons/research.png'), max_height: "1.2em" },
    [EmoteIconEnum.SERUM]: { img: getImgUrl('ui_icons/rf_serum.png'), max_height: "1.2em" },
    [EmoteIconEnum.MYCOALARM]: { img: getImgUrl('ui_icons/mycoalarm.png'), max_height: "1.2em" },
    [EmoteIconEnum.SPORE_SUCKER]: { img: getImgUrl('ui_icons/spore_sucker.png'), max_height: "1.2em" },
    [EmoteIconEnum.PHEROMODEM]: { img: getImgUrl('comms/pheromodem.png'), max_height: "1.2em" },
    [EmoteIconEnum.SEARCH]: { img: getImgUrl('achievements/search.png'), max_height: "1.2em" },
    [EmoteIconEnum.SIGNAL_FIRE]: { img: getImgUrl('achievements/signal_fire.png'), max_height: "1.2em" },
    [EmoteIconEnum.BIN]: { img: getImgUrl('bin.png'), max_height: "1.2em" },
    [EmoteIconEnum.PILL]: { img: getImgUrl('ui_icons/pill.png'), max_height: "1.2em" },
    [EmoteIconEnum.PLUS_BASIC]: { img: getImgUrl('skills/basicplus.png'), max_height: "1.2em" },
    [EmoteIconEnum.PLUS_GOLD]: { img: getImgUrl('skills/goldplus.png'), max_height: "1.2em" },
    [EmoteIconEnum.PLUS_RED]: { img: getImgUrl('skills/onceplus.png'), max_height: "1.2em" },
    [EmoteIconEnum.DEAD]: { img: getImgUrl('ui_icons/dead.png'), max_height: "1.2em" },
    [EmoteIconEnum.GRENADE]: { img: getImgUrl('ui_icons/grenade.png'), max_height: "1.2em" },
    [EmoteIconEnum.SOLDIER]: { img: getImgUrl('ui_icons/soldier.png'), max_height: "1.2em" },
    [EmoteIconEnum.TALKIE]: { img: getImgUrl('comms/talkie.png'), max_height: "1.2em" },
    [EmoteIconEnum.WATCH]: { img: getImgUrl('casio.png'), max_height: "1.2em" },
    [EmoteIconEnum.POINT1]: { img: getImgUrl('ui_icons/point.png'), max_height: "1.2em" },
    [EmoteIconEnum.POINT2]: { img: getImgUrl('ui_icons/point2.png'), max_height: "1.2em" },
    [EmoteIconEnum.OFFLINE]: { img: getImgUrl('comms/offline.gif'), max_height: "1.2em" },
    [EmoteIconEnum.ONLINE]: { img: getImgUrl('comms/online.gif'), max_height: "1.2em" },
    [EmoteIconEnum.LEFT]: { img: getImgUrl('ui_icons/left.png'), max_height: "1.2em" },
    [EmoteIconEnum.RIGHT]: { img: getImgUrl('ui_icons/right.png'), max_height: "1.2em" },
    [EmoteIconEnum.BETA]: { img: getImgUrl('ui_icons/beta_icon_small.png'), max_height: "1.2em" },
    [EmoteIconEnum.CALENDAR]: { img: getImgUrl('comms/calendar.png'), max_height: "1.2em" },
    [EmoteIconEnum.CHECK]: { img: getImgUrl('comms/check.png'), max_height: "1.2em" },
    [EmoteIconEnum.UNCHECK]: { img: getImgUrl('comms/uncheck.png'), max_height: "1.2em" },
    [EmoteIconEnum.CLOSE]: { img: getImgUrl('comms/close.png'), max_height: "1.2em" },
    [EmoteIconEnum.FAVORITE]: { img: getImgUrl('comms/fav.png'), max_height: "1.2em" },
    [EmoteIconEnum.UNFAVORITE]: { img: getImgUrl('comms/unfav.png'), max_height: "1.2em" },
    [EmoteIconEnum.LESS]: { img: getImgUrl('comms/less.png'), max_height: "1.2em" },
    [EmoteIconEnum.MORE]: { img: getImgUrl('comms/more.png'), max_height: "1.2em" },
    [EmoteIconEnum.STAR]: { img: getImgUrl('comms/star.png'), max_height: "1.2em" }
};
