import { getImgUrl } from "@/utils/getImgUrl";
import { EmoteCharacterEnum } from "@/enums/emotes/characters.enum";
import { UiIconEnum } from "@/enums/ui_icon.enum";


export enum EmoteIconEnum {
    ATTENTION = 'ic_attention',
    BROKEN = 'ic_alert',
    COMMS = 'ic_comms',
    DOOR = 'ic_door',
    FIRE = 'ic_fire',
    HUNGER = 'ic_hunger',
    HUNTER = 'ic_hunter',
    OXYGEN = 'ic_oxygen',
    GRAVITY_OFF = 'ic_gravity_off',
    GRAVITY_REBOOT = 'ic_gravity_reboot',
    INFO = 'ic_info',
    LIGHTBULB = 'ic_lightbulb',
    CAMERA = 'ic_camera',
    CAT = 'ic_cat',
    DOG = 'ic_dog',
    COFFEE = 'ic_coffee',
    COFFEE_PLUS = 'ic_coffee_plus',
    EXPLO_FEED = 'ic_explo_feed',
    EXPLORER = 'ic_explorer',
    GAME_WITHOUT_SLEEP = 'ic_game_without_sleep',
    NOTEBOOK = 'ic_notebook',
    BOOK = 'ic_book',
    WALL = 'ic_wall',
    PLANET_SCANNED = 'ic_planet_scanned',
    SOL = 'ic_sol',
    EDEN = 'ic_eden',
    EDEN_MUSH = 'ic_eden_mush',
    RATION = 'ic_ration',
    RATION_COOKED = 'ic_ration_cooked',
    SERUM = 'ic_serum',
    MYCOALARM = 'ic_mycoalarm',
    SPORE_SUCKER = 'ic_spore_sucker',
    REPORTED = 'ic_reported',
    SEARCH = 'ic_search',
    SIGNAL_FIRE = 'ic_signal_fire',
    BIN = 'ic_bin',
    PILL = 'ic_pill',
    PLUS_BASIC = 'ic_plus_basic',
    PLUS_GOLD = 'ic_plus_gold',
    PLUS_RED = 'ic_plus_red',
    DEAD = 'ic_dead',
    EXTINGUISHER = 'ic_extinguisher',
    GRENADE = 'ic_grenade',
    TALKIE = 'ic_talkie',
    WATCH = 'ic_watch',
    POINT1 = 'ic_point1',
    POINT2 = 'ic_point2',
    OFFLINE = 'ic_offline',
    ONLINE = 'ic_online',
    LEFT = 'ic_left',
    RIGHT = 'ic_right',
    BETA = 'ic_beta',
}

export const EmoteIconAliases: { [index: string]: string } = {
    ['cat'] : EmoteIconEnum.CAT,
    ['dog'] : EmoteIconEnum.DOG,
    ['ration'] : EmoteIconEnum.RATION,
    ['fire']: EmoteIconEnum.FIRE,
    ['no_gravity']: EmoteIconEnum.GRAVITY_OFF,
    ['gravity_reboot']: EmoteIconEnum.GRAVITY_REBOOT,
    ['no_alert']: EmoteIconEnum.INFO,
    ['low_oxygen']: EmoteIconEnum.OXYGEN,
    ['fires']: EmoteIconEnum.FIRE,
    ['low_hull']: EmoteIconEnum.FIRE,
    ['broken_doors']: EmoteIconEnum.DOOR,
    ['broken_equipments']: EmoteIconEnum.BROKEN,
    ['hunger']: EmoteIconEnum.HUNGER,
    ['hunter']: EmoteIconEnum.HUNTER,
    ['communications_down']: EmoteIconEnum.COMMS,
    ['coffee']: EmoteIconEnum.COFFEE,
    ['signal_equip']: EmoteIconEnum.REPORTED,
    ['planet']: EmoteIconEnum.PLANET_SCANNED,
    ['serum']: EmoteIconEnum.SERUM,
    ['retro_fungal_serum']: EmoteIconEnum.SERUM,
    ['srf']: EmoteIconEnum.SERUM,
    ['rfs']: EmoteIconEnum.SERUM,
    ['mycoalarm']: EmoteIconEnum.MYCOALARM,
    ['spore_sucker']: EmoteIconEnum.SPORE_SUCKER,
    ['grenade']: EmoteIconEnum.GRENADE,
    ['book_open']: EmoteIconEnum.WALL,
    ['eden']: EmoteIconEnum.EDEN,
    ['pill']: EmoteIconEnum.PILL,
    ['pills']: EmoteIconEnum.PILL,
    ['dead']: EmoteIconEnum.DEAD,
    ['tip']: EmoteIconEnum.LIGHTBULB,
    ['casio']: EmoteIconEnum.WATCH,
    ['point']: EmoteIconEnum.POINT1,
    ['offline']: EmoteIconEnum.OFFLINE,
    ['online']: EmoteIconEnum.ONLINE,
    ['beta']: EmoteIconEnum.BETA
};

export const EmoteIconIcons: { [index: string]: string } = {
    [EmoteIconEnum.ATTENTION]: getImgUrl('att.png'),
    [EmoteIconEnum.BROKEN]: getImgUrl('alerts/broken.png'),
    [EmoteIconEnum.COMMS]: getImgUrl('alerts/comm.png'),
    [EmoteIconEnum.DOOR]: getImgUrl('alerts/door.png'),
    [EmoteIconEnum.FIRE]: getImgUrl('alerts/fire.png'),
    [EmoteIconEnum.HUNGER]: getImgUrl('alerts/hunger.png'),
    [EmoteIconEnum.HUNTER]: getImgUrl('alerts/hunter.png'),
    [EmoteIconEnum.OXYGEN]: getImgUrl('alerts/o2alert.png'),
    [EmoteIconEnum.GRAVITY_OFF]: getImgUrl('alerts/simulator.png'),
    [EmoteIconEnum.GRAVITY_REBOOT]: getImgUrl('alerts/simulator_reboot.png'),
    [EmoteIconEnum.INFO]: getImgUrl('alerts/infoalert.png'),
    [EmoteIconEnum.LIGHTBULB]: getImgUrl('comms/tip.png'),
    [EmoteIconEnum.CAMERA]: getImgUrl('achievements/camera.png'),
    [EmoteIconEnum.CAT]: getImgUrl('achievements/cat.png'),
    [EmoteIconEnum.DOG]: getImgUrl('ui_icons/dog.png'),
    [EmoteIconEnum.COFFEE]: getImgUrl('ui_icons/coffee.png'),
    [EmoteIconEnum.COFFEE_PLUS]: getImgUrl('achievements/coffeeplus.png'),
    [EmoteIconEnum.EXPLO_FEED]: getImgUrl('achievements/explo_feed.png'),
    [EmoteIconEnum.EXPLORER]: getImgUrl('achievements/explorer.png'),
    [EmoteIconEnum.GAME_WITHOUT_SLEEP]: getImgUrl('achievements/game_without_sleep.png'),
    [EmoteIconEnum.NOTEBOOK]: getImgUrl('achievements/notebook.png'),
    [EmoteIconEnum.BOOK]: getImgUrl('ui_icons/book.png'),
    [EmoteIconEnum.WALL]: getImgUrl('comms/wall.png'),
    [EmoteIconEnum.PLANET_SCANNED]: getImgUrl('achievements/planet_scanned.png'),
    [EmoteIconEnum.SOL]: getImgUrl('achievements/sol.png'),
    [EmoteIconEnum.EDEN]: getImgUrl('ui_icons/eden1.png'),
    [EmoteIconEnum.EDEN_MUSH]: getImgUrl('ui_icons/eden2.png'),
    [EmoteIconEnum.RATION]: getImgUrl('ui_icons/ration.png'),
    [EmoteIconEnum.RATION_COOKED]: getImgUrl('achievements/rationcooked.png'),
    [EmoteIconEnum.SERUM]: getImgUrl('ui_icons/rf_serum.png'),
    [EmoteIconEnum.MYCOALARM]: getImgUrl('ui_icons/mycoalarm.png'),
    [EmoteIconEnum.SPORE_SUCKER]: getImgUrl('ui_icons/spore_sucker.png'),
    [EmoteIconEnum.REPORTED]: getImgUrl('achievements/reported.png'),
    [EmoteIconEnum.SEARCH]: getImgUrl('achievements/search.png'),
    [EmoteIconEnum.SIGNAL_FIRE]: getImgUrl('achievements/signal_fire.png'),
    [EmoteIconEnum.BIN]: getImgUrl('bin.png'),
    [EmoteIconEnum.PILL]: getImgUrl('ui_icons/pill.png'),
    [EmoteIconEnum.PLUS_BASIC]: getImgUrl('skills/basicplus.png'),
    [EmoteIconEnum.PLUS_GOLD]: getImgUrl('skills/goldplus.png'),
    [EmoteIconEnum.PLUS_RED]: getImgUrl('skills/onceplus.png'),
    [EmoteIconEnum.DEAD]: getImgUrl('ui_icons/dead.png'),
    [EmoteIconEnum.EXTINGUISHER]: getImgUrl('ui_icons/extinguisher.png'),
    [EmoteIconEnum.GRENADE]: getImgUrl('ui_icons/grenade.png'),
    [EmoteIconEnum.TALKIE]: getImgUrl('comms/talkie.png'),
    [EmoteIconEnum.WATCH]: getImgUrl('casio.png'),
    [EmoteIconEnum.POINT1]: getImgUrl('ui_icons/point.png'),
    [EmoteIconEnum.POINT2]: getImgUrl('ui_icons/point2.png'),
    [EmoteIconEnum.OFFLINE]: getImgUrl('comms/offline.gif'),
    [EmoteIconEnum.ONLINE]: getImgUrl('comms/online.gif'),
    [EmoteIconEnum.LEFT]: getImgUrl('ui_icons/left.png'),
    [EmoteIconEnum.RIGHT]: getImgUrl('ui_icons/right.png'),
    [EmoteIconEnum.BETA]: getImgUrl('ui_icons/beta_icon_small.png')
};
