import { getImgUrl } from "@/utils/getImgUrl";
import { EmoteCharacterEnum } from "@/enums/emotes/characters.enum";

export enum EmoteMuxxuEnum {
    ARROW = 'muxxu_arrow',
    CHART = 'muxxu_chart',
    CONFUSED = 'muxxu_confused',
    COOL = 'muxxu_cool',
    CROSS = 'muxxu_cross',
    CRY = 'muxxu_cry',
    DONTCARE = 'muxxu_dontcare',
    EEK = 'muxxu_eek',
    EVIL = 'muxxu_evil',
    EXCLAIM = 'muxxu_exclaim',
    HAPPY = 'muxxu_happy',
    HUH = 'muxxu_huh',
    IDEA = 'muxxu_idea',
    KEEPCOOL = 'muxxu_keepcool',
    LOL = 'muxxu_lol',
    LOOKUP = 'muxxu_lookup',
    MAD = 'muxxu_mad',
    NOOO = 'muxxu_nooo',
    QUESTION = 'muxxu_question',
    RAZZ = 'muxxu_razz',
    REDFACE = 'muxxu_redface',
    SAD = 'muxxu_sad',
    SMILE = 'muxxu_smile',
    SURPRISED = 'muxxu_surprised',
    TWISTED = 'muxxu_twisted',
    WINK = 'muxxu_wink',
    WINK2 = 'muxxu_wink2',
    YEAH = 'muxxu_yeah',
}

export const EmoteMuxxuAliases: { [index: string]: string } = { };

export const EmoteMuxxuIcons: {[index: string]: {img: string; max_height: string;}}= {
    [EmoteMuxxuEnum.ARROW]: { img: getImgUrl('emotes/muxxu/arrow.gif'), max_height: "1.2em" },
    [EmoteMuxxuEnum.CHART]: { img: getImgUrl('emotes/muxxu/chart.gif'), max_height: "1.2em" },
    [EmoteMuxxuEnum.CONFUSED]: { img: getImgUrl('emotes/muxxu/confused.gif'), max_height: "1.2em" },
    [EmoteMuxxuEnum.COOL]: { img: getImgUrl('emotes/muxxu/cool.gif'), max_height: "1.2em" },
    [EmoteMuxxuEnum.CROSS]: { img: getImgUrl('emotes/muxxu/cross.gif'), max_height: "1.2em" },
    [EmoteMuxxuEnum.CRY]: { img: getImgUrl('emotes/muxxu/cry.gif'), max_height: "1.2em" },
    [EmoteMuxxuEnum.DONTCARE]: { img: getImgUrl('emotes/muxxu/dontcare.gif'), max_height: "1.2em" },
    [EmoteMuxxuEnum.EEK]: { img: getImgUrl('emotes/muxxu/eek.gif'), max_height: "1.2em" },
    [EmoteMuxxuEnum.EVIL]: { img: getImgUrl('emotes/muxxu/evil.gif'), max_height: "1.2em" },
    [EmoteMuxxuEnum.EXCLAIM]: { img: getImgUrl('emotes/muxxu/exclaim.gif'), max_height: "1.2em" },
    [EmoteMuxxuEnum.HAPPY]: { img: getImgUrl('emotes/muxxu/happy.gif'), max_height: "1.2em" },
    [EmoteMuxxuEnum.HUH]: { img: getImgUrl('emotes/muxxu/huh.gif'), max_height: "1.2em" },
    [EmoteMuxxuEnum.IDEA]: { img: getImgUrl('emotes/muxxu/idea.gif'), max_height: "1.2em" },
    [EmoteMuxxuEnum.KEEPCOOL]: { img: getImgUrl('emotes/muxxu/keepcool.gif'), max_height: "1.2em" },
    [EmoteMuxxuEnum.LOL]: { img: getImgUrl('emotes/muxxu/lol.gif'), max_height: "1.2em" },
    [EmoteMuxxuEnum.LOOKUP]: { img: getImgUrl('emotes/muxxu/lookup.gif'), max_height: "1.2em" },
    [EmoteMuxxuEnum.MAD]: { img: getImgUrl('emotes/muxxu/mad.gif'), max_height: "1.2em" },
    [EmoteMuxxuEnum.NOOO]: { img: getImgUrl('emotes/muxxu/nooo.gif'), max_height: "1.2em" },
    [EmoteMuxxuEnum.QUESTION]: { img: getImgUrl('emotes/muxxu/question.gif'), max_height: "1.2em" },
    [EmoteMuxxuEnum.RAZZ]: { img: getImgUrl('emotes/muxxu/razz.gif'), max_height: "1.2em" },
    [EmoteMuxxuEnum.REDFACE]: { img: getImgUrl('emotes/muxxu/redface.gif'), max_height: "1.2em" },
    [EmoteMuxxuEnum.SAD]: { img: getImgUrl('emotes/muxxu/sad.gif'), max_height: "1.2em" },
    [EmoteMuxxuEnum.SMILE]: { img: getImgUrl('emotes/muxxu/smile.gif'), max_height: "1.2em" },
    [EmoteMuxxuEnum.SURPRISED]: { img: getImgUrl('emotes/muxxu/surprised.gif'), max_height: "1.2em" },
    [EmoteMuxxuEnum.TWISTED]: { img: getImgUrl('emotes/muxxu/twisted.gif'), max_height: "1.2em" },
    [EmoteMuxxuEnum.WINK]: { img: getImgUrl('emotes/muxxu/wink.gif'), max_height: "1.2em" },
    [EmoteMuxxuEnum.WINK2]: { img: getImgUrl('emotes/muxxu/wink2.gif'), max_height: "1.2em" },
    [EmoteMuxxuEnum.YEAH]: { img: getImgUrl('emotes/muxxu/yeah.gif'), max_height: "1.2em" }
};
