import { getImgUrl } from "@/utils/getImgUrl";


export enum EmoteResourcesEnum {
    HP = 'hp',
    MORAL = 'moral',
    AP = 'ap',
    MP = 'mp',
    AP_COMP = 'ap_comp',
    AP_COOK = 'ap_cook',
    AP_CORE = 'ap_core',
    AP_TECH = 'ap_tech',
    AP_GARDEN = 'ap_garden',
    AP_HEAL = 'ap_heal',
    AP_PILGRED = 'ap_pilgred',
    AP_SHOOT = 'ap_shoot',
    ARMOR = 'shield',
    SHIELD = 'plasma',
    SHIELD_OFF = 'plasma_disabled',
    OXYGEN = 'oxygen',
    OXYGEN_ALERT = 'oxygen_alert',
    FUEL = 'fuel',
    TRIUMPH = 'triumph',
    TRIUMP_MUSH = 'triumph_mush',
}

export const EmoteResourcesAliases: { [index: string]: string } = {
    ['pv'] : EmoteResourcesEnum.HP,
    ['morale']: EmoteResourcesEnum.MORAL,
    ['pmo']: EmoteResourcesEnum.MORAL,
    ['pa']: EmoteResourcesEnum.AP,
    ['pm']: EmoteResourcesEnum.MP,
    ['computer']: EmoteResourcesEnum.AP_COMP,
    ['pa_comp']: EmoteResourcesEnum.AP_COMP,
    ['ap_it']: EmoteResourcesEnum.AP_COMP,
    ['pa_it']: EmoteResourcesEnum.AP_COMP,
    ['cook']: EmoteResourcesEnum.AP_COOK,
    ['pa_cook']: EmoteResourcesEnum.AP_COOK,
    ['core']: EmoteResourcesEnum.AP_CORE,
    ['pa_core']: EmoteResourcesEnum.AP_CORE,
    ['pa_design']: EmoteResourcesEnum.AP_CORE,
    ['ap_design']: EmoteResourcesEnum.AP_CORE,
    ['engineer']: EmoteResourcesEnum.AP_TECH,
    ['pa_tech']: EmoteResourcesEnum.AP_TECH,
    ['pa_eng']: EmoteResourcesEnum.AP_TECH,
    ['ap_eng']: EmoteResourcesEnum.AP_TECH,
    ['garden']: EmoteResourcesEnum.AP_GARDEN,
    ['pa_garden']: EmoteResourcesEnum.AP_GARDEN,
    ['pa_plant']: EmoteResourcesEnum.AP_GARDEN,
    ['ap_plant']: EmoteResourcesEnum.AP_GARDEN,
    ['heal']: EmoteResourcesEnum.AP_HEAL,
    ['pa_heal']: EmoteResourcesEnum.AP_HEAL,
    ['pa_nurse']: EmoteResourcesEnum.AP_HEAL,
    ['ap_nurse']: EmoteResourcesEnum.AP_HEAL,
    ['pilgred']: EmoteResourcesEnum.AP_PILGRED,
    ['pa_pilgred']: EmoteResourcesEnum.AP_PILGRED,
    ['pa_phys']: EmoteResourcesEnum.AP_PILGRED,
    ['ap_phys']: EmoteResourcesEnum.AP_PILGRED,
    ['shoot']: EmoteResourcesEnum.AP_SHOOT,
    ['pa_shoot']: EmoteResourcesEnum.AP_SHOOT,
    ['pa_gun']: EmoteResourcesEnum.AP_SHOOT,
    ['ap_gun']: EmoteResourcesEnum.AP_SHOOT,
    ['hull']: EmoteResourcesEnum.ARMOR,
    ['plasma_off']: EmoteResourcesEnum.SHIELD_OFF,
    ['o2']: EmoteResourcesEnum.OXYGEN,
    ['triomphe']: EmoteResourcesEnum.TRIUMPH,
    ['glory']: EmoteResourcesEnum.TRIUMPH,
    ['triomphe_mush']: EmoteResourcesEnum.TRIUMP_MUSH,
    ['glory_mush']: EmoteResourcesEnum.TRIUMP_MUSH
};

export const EmoteResourcesIcons: {[index: string]: {img: string; max_height: string;}}= {
    [EmoteResourcesEnum.HP]: { img: getImgUrl('ui_icons/player_variables/hp.png'), max_height: "1.2em" },
    [EmoteResourcesEnum.MORAL]: { img: getImgUrl('ui_icons/player_variables/moral.png'), max_height: "1.2em" },
    [EmoteResourcesEnum.AP]: { img: getImgUrl('ui_icons/player_variables/pa.png'), max_height: "1.2em" },
    [EmoteResourcesEnum.MP]: { img: getImgUrl('ui_icons/player_variables/pm.png'), max_height: "1.2em" },
    [EmoteResourcesEnum.AP_COMP]: { img: getImgUrl('ui_icons/action_points/pa_comp.png'), max_height: "1.2em" },
    [EmoteResourcesEnum.AP_COOK]: { img: getImgUrl('ui_icons/action_points/pa_cook.png'), max_height: "1.2em" },
    [EmoteResourcesEnum.AP_CORE]: { img: getImgUrl('ui_icons/action_points/pa_core.png'), max_height: "1.2em" },
    [EmoteResourcesEnum.AP_TECH]: { img: getImgUrl('ui_icons/action_points/pa_tech.png'), max_height: "1.2em" },
    [EmoteResourcesEnum.AP_GARDEN]: { img: getImgUrl('ui_icons/action_points/pa_garden.png'), max_height: "1.2em" },
    [EmoteResourcesEnum.AP_HEAL]: { img: getImgUrl('ui_icons/action_points/pa_heal.png'), max_height: "1.2em" },
    [EmoteResourcesEnum.AP_PILGRED]: { img: getImgUrl('ui_icons/action_points/pa_pilgred.png'), max_height: "1.2em" },
    [EmoteResourcesEnum.AP_SHOOT]: { img: getImgUrl('ui_icons/action_points/pa_shoot.png'), max_height: "1.2em" },
    [EmoteResourcesEnum.ARMOR]: { img: getImgUrl('shield.png'), max_height: "1.2em" },
    [EmoteResourcesEnum.SHIELD]: { img: getImgUrl('plasma.png'), max_height: "1.2em" },
    [EmoteResourcesEnum.SHIELD_OFF]: { img: getImgUrl('plasma_off.png'), max_height: "1.2em" },
    [EmoteResourcesEnum.OXYGEN]: { img: getImgUrl('o2.png'), max_height: "1.2em" },
    [EmoteResourcesEnum.OXYGEN_ALERT]: { img: getImgUrl('alerts/o2alert.png'), max_height: "1.2em" },
    [EmoteResourcesEnum.FUEL]: { img: getImgUrl('ui_icons/fuel.png'), max_height: "1.2em" },
    [EmoteResourcesEnum.TRIUMPH]: { img: getImgUrl('ui_icons/player_variables/triumph.png'), max_height: "1.2em" },
    [EmoteResourcesEnum.TRIUMP_MUSH]: { img: getImgUrl('ui_icons/player_variables/triumph_mush.png'), max_height: "1.2em" }
};
