import { getImgUrl } from "@/utils/getImgUrl";


export enum EmoteResourcesEnum {
    HP = 'hp',
    MORAL = 'moral',
    AP = 'ap',
    MP = 'mp',
    AP_COMP = 'ap_comp',
    AP_COOK = 'ap_cook',
    AP_CORE = 'ap_core',
    AP_TECH = 'ap_tech',
    AP_GARDEN = 'ap_garden',
    AP_HEAL = 'ap_heal',
    AP_PILGRED = 'ap_pilgred',
    AP_SHOOT = 'ap_shoot',
    ARMOR = 'shield',
    SHIELD = 'plasma',
    SHIELD_OFF = 'plasma_disabled',
    OXYGEN = 'oxygen',
    OXYGEN_ALERT = 'oxygen_alert',
    FUEL = 'fuel',
    TRIUMPH = 'triumph',
    TRIUMP_MUSH = 'triumph_mush',
}

export const EmoteResourcesAliases: { [index: string]: string } = {
    ['pv'] : EmoteResourcesEnum.HP,
    ['morale']: EmoteResourcesEnum.MORAL,
    ['pmo']: EmoteResourcesEnum.MORAL,
    ['pa']: EmoteResourcesEnum.AP,
    ['pm']: EmoteResourcesEnum.MP,
    ['computer']: EmoteResourcesEnum.AP_COMP,
    ['pa_comp']: EmoteResourcesEnum.AP_COMP,
    ['ap_it']: EmoteResourcesEnum.AP_COMP,
    ['pa_it']: EmoteResourcesEnum.AP_COMP,
    ['cook']: EmoteResourcesEnum.AP_COOK,
    ['pa_cook']: EmoteResourcesEnum.AP_COOK,
    ['core']: EmoteResourcesEnum.AP_CORE,
    ['pa_core']: EmoteResourcesEnum.AP_CORE,
    ['pa_design']: EmoteResourcesEnum.AP_CORE,
    ['ap_design']: EmoteResourcesEnum.AP_CORE,
    ['engineer']: EmoteResourcesEnum.AP_TECH,
    ['pa_tech']: EmoteResourcesEnum.AP_TECH,
    ['pa_eng']: EmoteResourcesEnum.AP_TECH,
    ['ap_eng']: EmoteResourcesEnum.AP_TECH,
    ['garden']: EmoteResourcesEnum.AP_GARDEN,
    ['pa_garden']: EmoteResourcesEnum.AP_GARDEN,
    ['pa_plant']: EmoteResourcesEnum.AP_GARDEN,
    ['ap_plant']: EmoteResourcesEnum.AP_GARDEN,
    ['heal']: EmoteResourcesEnum.AP_HEAL,
    ['pa_heal']: EmoteResourcesEnum.AP_HEAL,
    ['pa_nurse']: EmoteResourcesEnum.AP_HEAL,
    ['ap_nurse']: EmoteResourcesEnum.AP_HEAL,
    ['pilgred']: EmoteResourcesEnum.AP_PILGRED,
    ['pa_pilgred']: EmoteResourcesEnum.AP_PILGRED,
    ['pa_phys']: EmoteResourcesEnum.AP_PILGRED,
    ['ap_phys']: EmoteResourcesEnum.AP_PILGRED,
    ['shoot']: EmoteResourcesEnum.AP_SHOOT,
    ['pa_shoot']: EmoteResourcesEnum.AP_SHOOT,
    ['pa_gun']: EmoteResourcesEnum.AP_SHOOT,
    ['ap_gun']: EmoteResourcesEnum.AP_SHOOT,
    ['hull']: EmoteResourcesEnum.ARMOR,
    ['plasma_off']: EmoteResourcesEnum.SHIELD_OFF,
    ['o2']: EmoteResourcesEnum.OXYGEN,
    ['triomphe']: EmoteResourcesEnum.TRIUMPH,
    ['glory']: EmoteResourcesEnum.TRIUMPH,
    ['triomphe_mush']: EmoteResourcesEnum.TRIUMP_MUSH,
    ['glory_mush']: EmoteResourcesEnum.TRIUMP_MUSH
};

export const EmoteResourcesIcons: { [index: string]: string } = {
    [EmoteResourcesEnum.HP]: getImgUrl('ui_icons/player_variables/hp.png'),
    [EmoteResourcesEnum.MORAL]: getImgUrl('ui_icons/player_variables/moral.png'),
    [EmoteResourcesEnum.AP]: getImgUrl('ui_icons/player_variables/pa.png'),
    [EmoteResourcesEnum.MP]: getImgUrl('ui_icons/player_variables/pm.png'),
    [EmoteResourcesEnum.AP_COMP]: getImgUrl('ui_icons/action_points/pa_comp.png'),
    [EmoteResourcesEnum.AP_COOK]: getImgUrl('ui_icons/action_points/pa_cook.png'),
    [EmoteResourcesEnum.AP_CORE]: getImgUrl('ui_icons/action_points/pa_core.png'),
    [EmoteResourcesEnum.AP_TECH]: getImgUrl('ui_icons/action_points/pa_tech.png'),
    [EmoteResourcesEnum.AP_GARDEN]: getImgUrl('ui_icons/action_points/pa_garden.png'),
    [EmoteResourcesEnum.AP_HEAL]: getImgUrl('ui_icons/action_points/pa_heal.png'),
    [EmoteResourcesEnum.AP_PILGRED]: getImgUrl('ui_icons/action_points/pa_pilgred.png'),
    [EmoteResourcesEnum.AP_SHOOT]: getImgUrl('ui_icons/action_points/pa_shoot.png'),
    [EmoteResourcesEnum.ARMOR]: getImgUrl('shield.png'),
    [EmoteResourcesEnum.SHIELD]: getImgUrl('plasma.png'),
    [EmoteResourcesEnum.SHIELD_OFF]: getImgUrl('plasma_off.png'),
    [EmoteResourcesEnum.OXYGEN]: getImgUrl('o2.png'),
    [EmoteResourcesEnum.OXYGEN_ALERT]: getImgUrl('alerts/o2alert.png'),
    [EmoteResourcesEnum.FUEL]: getImgUrl('ui_icons/fuel.png'),
    [EmoteResourcesEnum.TRIUMPH]: getImgUrl('ui_icons/player_variables/triumph.png'),
    [EmoteResourcesEnum.TRIUMP_MUSH]: getImgUrl('ui_icons/player_variables/triumph_mush.png')
};
