import { getImgUrl } from "@/utils/getImgUrl";
import { EmoteCharacterEnum } from "@/enums/emotes/characters.enum";

export enum EmoteHumanSkillEnum {
    ABNEGATION = 'sk_abnegation',
    ADAPTABLE = 'sk_adaptable',
    ANTIC_PERFUME = 'sk_antic_perfume',
    ASTROPHYSICIST = 'sk_astrophysicist',
    BETA_HUMAN = 'sk_beta_human',
    BIOLOGIST = 'sk_biologist',
    BOTANIC = 'sk_botanic',
    CAFFEINOMANIAC = 'sk_caffeinomaniac',
    COLD_BLOOD = 'sk_cold_blood',
    COMMUNICATION = 'sk_communication',
    CONCEPTOR = 'sk_conceptor',
    CONFIDENT = 'sk_confident',
    COOK = 'sk_cook',
    CRAZY_EYE = 'sk_crazy_eye',
    CREATIVE = 'sk_creative',
    DAUNTING = 'sk_daunting',
    DEVOTION = 'sk_devotion',
    DIPLOMACY = 'sk_diplomacy',
    DISABLED_SPRINTER = 'sk_disabled_sprinter',
    ENGINEER = 'sk_engineer',
    ESCAPE = 'sk_escape',
    EXPERT = 'sk_expert',
    FAST_BACKWARD = 'sk_fast_backward',
    FIREMAN = 'sk_fireman',
    FIRST_AID = 'sk_first_aid',
    FRUGIVORE = 'sk_frugivore',
    GENIUS = 'sk_genius',
    GREEN_THUMB = 'sk_green_thumb',
    GUNMAN = 'sk_gunman',
    GUNNER = 'sk_gunner',
    HUNT = 'sk_hunt',
    IT_EXPERT = 'sk_it_expert',
    JUGE = 'sk_juge',
    LEADERSHIP = 'sk_leadership',
    LETHARGY = 'sk_lethargy',
    LOGISTICS = 'sk_logistics',
    MANKIND_ONLY_HOPE = 'sk_mankind_only_hope',
    MEDIC = 'sk_medic',
    METALICISTE = 'sk_metaliciste',
    MOTIVATOR = 'sk_motivator',
    MYCOLOGIST = 'sk_mycologist',
    NERON_ONLY_FRIEND = 'sk_neron_only_friend',
    OBSERVANT = 'sk_observant',
    OPPORTUNIST = 'sk_opportunist',
    OPTIMISTIC = 'sk_optimistic',
    PANIC = 'sk_panic',
    PARANOID = 'sk_paranoid',
    PERSISTENT = 'sk_persistent',
    PHYSICIST = 'sk_physicist',
    PILOT = 'sk_pilot',
    POLITICIAN = 'sk_politician',
    POLYMATH = 'sk_polymath',
    POLYVALENT = 'sk_polyvalent',
    PREMONITION = 'sk_premonition',
    REBEL = 'sk_rebel',
    ROBOTICS = 'sk_robotics',
    SHRINK = 'sk_shrink',
    SPACE_TACTICS = 'sk_space_tactics',
    SPRINTER = 'sk_sprinter',
    STICKLER = 'sk_stickler',
    STRONG_SKIN = 'sk_strong_skin',
    STURDY = 'sk_sturdy',
    SURVIVAL = 'sk_survival',
    TORTURER = 'sk_torturer',
    UNCONCERNED = 'sk_unconcerned',
    WRESTLER = 'sk_wrestler',
}

export const EmoteHumanSkillAliases: { [index: string]: string } = {
    ['conceptor']: EmoteHumanSkillEnum.CONCEPTOR,
    ['technician']: EmoteHumanSkillEnum.ENGINEER,
    ['shooter']: EmoteHumanSkillEnum.GUNNER,
    ['pilot']: EmoteHumanSkillEnum.PILOT
};


export const EmoteHumanSkillIcons: {[index: string]: {img: string; max_height: string;}}= {
    [EmoteHumanSkillEnum.ABNEGATION]: { img: getImgUrl('skills/human/abnegation.png'), max_height: "1.2em" },
    [EmoteHumanSkillEnum.ADAPTABLE]: { img: getImgUrl('skills/human/adaptable.png'), max_height: "1.2em" },
    [EmoteHumanSkillEnum.ANTIC_PERFUME]: { img: getImgUrl('skills/human/antic_perfume.png'), max_height: "1.2em" },
    [EmoteHumanSkillEnum.ASTROPHYSICIST]: { img: getImgUrl('skills/human/astrophysicist.png'), max_height: "1.2em" },
    [EmoteHumanSkillEnum.BETA_HUMAN]: { img: getImgUrl('skills/human/beta_human.png'), max_height: "1.2em" },
    [EmoteHumanSkillEnum.BIOLOGIST]: { img: getImgUrl('skills/human/biologist.png'), max_height: "1.2em" },
    [EmoteHumanSkillEnum.BOTANIC]: { img: getImgUrl('skills/human/botanic.png'), max_height: "1.2em" },
    [EmoteHumanSkillEnum.CAFFEINOMANIAC]: { img: getImgUrl('skills/human/caffeinomaniac.png'), max_height: "1.2em" },
    [EmoteHumanSkillEnum.COLD_BLOOD]: { img: getImgUrl('skills/human/cold_blood.png'), max_height: "1.2em" },
    [EmoteHumanSkillEnum.COMMUNICATION]: { img: getImgUrl('skills/human/communication.png'), max_height: "1.2em" },
    [EmoteHumanSkillEnum.CONCEPTOR]: { img: getImgUrl('skills/human/conceptor.png'), max_height: "1.2em" },
    [EmoteHumanSkillEnum.CONFIDENT]: { img: getImgUrl('skills/human/confident.png'), max_height: "1.2em" },
    [EmoteHumanSkillEnum.COOK]: { img: getImgUrl('skills/human/cook.png'), max_height: "1.2em" },
    [EmoteHumanSkillEnum.CRAZY_EYE]: { img: getImgUrl('skills/human/crazy_eye.png'), max_height: "1.2em" },
    [EmoteHumanSkillEnum.CREATIVE]: { img: getImgUrl('skills/human/creative.png'), max_height: "1.2em" },
    [EmoteHumanSkillEnum.DAUNTING]: { img: getImgUrl('skills/human/daunting.png'), max_height: "1.2em" },
    [EmoteHumanSkillEnum.DEVOTION]: { img: getImgUrl('skills/human/devotion.png'), max_height: "1.2em" },
    [EmoteHumanSkillEnum.DIPLOMACY]: { img: getImgUrl('skills/human/diplomacy.png'), max_height: "1.2em" },
    [EmoteHumanSkillEnum.DISABLED_SPRINTER]: { img: getImgUrl('skills/human/disabled_sprinter.png'), max_height: "1.2em" },
    [EmoteHumanSkillEnum.ENGINEER]: { img: getImgUrl('skills/human/engineer.png'), max_height: "1.2em" },
    [EmoteHumanSkillEnum.ESCAPE]: { img: getImgUrl('skills/human/escape.png'), max_height: "1.2em" },
    [EmoteHumanSkillEnum.EXPERT]: { img: getImgUrl('skills/human/expert.png'), max_height: "1.2em" },
    [EmoteHumanSkillEnum.FAST_BACKWARD]: { img: getImgUrl('skills/human/fast_backward.png'), max_height: "1.2em" },
    [EmoteHumanSkillEnum.FIREMAN]: { img: getImgUrl('skills/human/fireman.png'), max_height: "1.2em" },
    [EmoteHumanSkillEnum.FIRST_AID]: { img: getImgUrl('skills/human/first_aid.png'), max_height: "1.2em" },
    [EmoteHumanSkillEnum.FRUGIVORE]: { img: getImgUrl('skills/human/frugivore.png'), max_height: "1.2em" },
    [EmoteHumanSkillEnum.GENIUS]: { img: getImgUrl('skills/human/genius.png'), max_height: "1.2em" },
    [EmoteHumanSkillEnum.GREEN_THUMB]: { img: getImgUrl('skills/human/green_thumb.png'), max_height: "1.2em" },
    [EmoteHumanSkillEnum.GUNMAN]: { img: getImgUrl('skills/human/gunman.png'), max_height: "1.2em" },
    [EmoteHumanSkillEnum.GUNNER]: { img: getImgUrl('skills/human/gunner.png'), max_height: "1.2em" },
    [EmoteHumanSkillEnum.HUNT]: { img: getImgUrl('skills/human/hunt.png'), max_height: "1.2em" },
    [EmoteHumanSkillEnum.IT_EXPERT]: { img: getImgUrl('skills/human/it_expert.png'), max_height: "1.2em" },
    [EmoteHumanSkillEnum.JUGE]: { img: getImgUrl('skills/human/juge.png'), max_height: "1.2em" },
    [EmoteHumanSkillEnum.LEADERSHIP]: { img: getImgUrl('skills/human/leadership.png'), max_height: "1.2em" },
    [EmoteHumanSkillEnum.LETHARGY]: { img: getImgUrl('skills/human/lethargy.png'), max_height: "1.2em" },
    [EmoteHumanSkillEnum.LOGISTICS]: { img: getImgUrl('skills/human/logistics.png'), max_height: "1.2em" },
    [EmoteHumanSkillEnum.MANKIND_ONLY_HOPE]: { img: getImgUrl('skills/human/mankind_only_hope.png'), max_height: "1.2em" },
    [EmoteHumanSkillEnum.MEDIC]: { img: getImgUrl('skills/human/medic.png'), max_height: "1.2em" },
    [EmoteHumanSkillEnum.METALICISTE]: { img: getImgUrl('skills/human/metaliciste.png'), max_height: "1.2em" },
    [EmoteHumanSkillEnum.MOTIVATOR]: { img: getImgUrl('skills/human/motivator.png'), max_height: "1.2em" },
    [EmoteHumanSkillEnum.MYCOLOGIST]: { img: getImgUrl('skills/human/mycologist.png'), max_height: "1.2em" },
    [EmoteHumanSkillEnum.NERON_ONLY_FRIEND]: { img: getImgUrl('skills/human/neron_only_friend.png'), max_height: "1.2em" },
    [EmoteHumanSkillEnum.OBSERVANT]: { img: getImgUrl('skills/human/observant.png'), max_height: "1.2em" },
    [EmoteHumanSkillEnum.OPPORTUNIST]: { img: getImgUrl('skills/human/opportunist.png'), max_height: "1.2em" },
    [EmoteHumanSkillEnum.OPTIMISTIC]: { img: getImgUrl('skills/human/optimistic.png'), max_height: "1.2em" },
    [EmoteHumanSkillEnum.PANIC]: { img: getImgUrl('skills/human/panic.png'), max_height: "1.2em" },
    [EmoteHumanSkillEnum.PARANOID]: { img: getImgUrl('skills/human/paranoid.png'), max_height: "1.2em" },
    [EmoteHumanSkillEnum.PERSISTENT]: { img: getImgUrl('skills/human/persistent.png'), max_height: "1.2em" },
    [EmoteHumanSkillEnum.PHYSICIST]: { img: getImgUrl('skills/human/physicist.png'), max_height: "1.2em" },
    [EmoteHumanSkillEnum.PILOT]: { img: getImgUrl('skills/human/pilot.png'), max_height: "1.2em" },
    [EmoteHumanSkillEnum.POLITICIAN]: { img: getImgUrl('skills/human/politician.png'), max_height: "1.2em" },
    [EmoteHumanSkillEnum.POLYMATH]: { img: getImgUrl('skills/human/polymath.png'), max_height: "1.2em" },
    [EmoteHumanSkillEnum.POLYVALENT]: { img: getImgUrl('skills/human/polyvalent.png'), max_height: "1.2em" },
    [EmoteHumanSkillEnum.PREMONITION]: { img: getImgUrl('skills/human/premonition.png'), max_height: "1.2em" },
    [EmoteHumanSkillEnum.REBEL]: { img: getImgUrl('skills/human/rebel.png'), max_height: "1.2em" },
    [EmoteHumanSkillEnum.ROBOTICS]: { img: getImgUrl('skills/human/robotics.png'), max_height: "1.2em" },
    [EmoteHumanSkillEnum.SHRINK]: { img: getImgUrl('skills/human/shrink.png'), max_height: "1.2em" },
    [EmoteHumanSkillEnum.SPACE_TACTICS]: { img: getImgUrl('skills/human/space_tactics.png'), max_height: "1.2em" },
    [EmoteHumanSkillEnum.SPRINTER]: { img: getImgUrl('skills/human/sprinter.png'), max_height: "1.2em" },
    [EmoteHumanSkillEnum.STICKLER]: { img: getImgUrl('skills/human/stickler.png'), max_height: "1.2em" },
    [EmoteHumanSkillEnum.STRONG_SKIN]: { img: getImgUrl('skills/human/strong_skin.png'), max_height: "1.2em" },
    [EmoteHumanSkillEnum.STURDY]: { img: getImgUrl('skills/human/sturdy.png'), max_height: "1.2em" },
    [EmoteHumanSkillEnum.SURVIVAL]: { img: getImgUrl('skills/human/survival.png'), max_height: "1.2em" },
    [EmoteHumanSkillEnum.TORTURER]: { img: getImgUrl('skills/human/torturer.png'), max_height: "1.2em" },
    [EmoteHumanSkillEnum.UNCONCERNED]: { img: getImgUrl('skills/human/unconcerned.png'), max_height: "1.2em" },
    [EmoteHumanSkillEnum.WRESTLER]: { img: getImgUrl('skills/human/wrestler.png'), max_height: "1.2em" }
};

export enum EmoteMushSkillEnum {
    ANONYMOUS = 'sk_anonymous',
    BACTERIAL_CONTACT = 'sk_bacterial_contact',
    BETA_MUSH = 'sk_beta_mush',
    DEFACER = 'sk_defacer',
    DISHEARTENING_CONTACT = 'sk_disheartening_contact',
    DOORMAN = 'sk_doorman',
    ELECTRO_SLIME = 'sk_electro_slime',
    FERTILE = 'sk_fertile',
    FUNGUS_COOK = 'sk_fungus_cook',
    INFECTIOUS_AGENT = 'sk_infectious_agent',
    MASSGGEDON = 'sk_massggedon',
    MYCELLIUM_SPIRIT = 'sk_mycellium_spirit',
    NERON_ACCESS = 'sk_neron_access',
    NERONDEPRESS = 'sk_nerondepress',
    NIGHTMARE = 'sk_nightmare',
    NIMBLE_FINGERS = 'sk_nimble_fingers',
    NINJA = 'sk_ninja',
    PHAGOCYTOSIS = 'sk_phagocytosis',
    PYROMANE = 'sk_pyromane',
    RADIO_PIRACY = 'sk_radio_piracy',
    SAPPER = 'sk_sapper',
    SLIMETRAP = 'sk_slimetrap',
    TOUGH = 'sk_tough',
    TRAITOR = 'sk_traitor',
    TRANSFERT = 'sk_transfert',
    TRAPPER = 'sk_trapper',
    WATER_RESISTANT = 'sk_water_resistant',
}

export const EmoteMushSkillAliases: { [index: string]: string } = { };

export const EmoteMushSkillIcons: {[index: string]: {img: string; max_height: string;}}= {
    [EmoteMushSkillEnum.ANONYMOUS]: { img: getImgUrl('skills/mush/anonymous.png'), max_height: "1.2em" },
    [EmoteMushSkillEnum.BACTERIAL_CONTACT]: { img: getImgUrl('skills/mush/bacterial_contact.png'), max_height: "1.2em" },
    [EmoteMushSkillEnum.BETA_MUSH]: { img: getImgUrl('skills/mush/beta_mush.png'), max_height: "1.2em" },
    [EmoteMushSkillEnum.DEFACER]: { img: getImgUrl('skills/mush/defacer.png'), max_height: "1.2em" },
    [EmoteMushSkillEnum.DISHEARTENING_CONTACT]: { img: getImgUrl('skills/mush/disheartening_contact.png'), max_height: "1.2em" },
    [EmoteMushSkillEnum.DOORMAN]: { img: getImgUrl('skills/mush/doorman.png'), max_height: "1.2em" },
    [EmoteMushSkillEnum.ELECTRO_SLIME]: { img: getImgUrl('skills/mush/electro_slime.png'), max_height: "1.2em" },
    [EmoteMushSkillEnum.FERTILE]: { img: getImgUrl('skills/mush/fertile.png'), max_height: "1.2em" },
    [EmoteMushSkillEnum.FUNGUS_COOK]: { img: getImgUrl('skills/mush/fungus_cook.png'), max_height: "1.2em" },
    [EmoteMushSkillEnum.INFECTIOUS_AGENT]: { img: getImgUrl('skills/mush/infectious_agent.png'), max_height: "1.2em" },
    [EmoteMushSkillEnum.MASSGGEDON]: { img: getImgUrl('skills/mush/massggedon.png'), max_height: "1.2em" },
    [EmoteMushSkillEnum.MYCELLIUM_SPIRIT]: { img: getImgUrl('skills/mush/mycellium_spirit.png'), max_height: "1.2em" },
    [EmoteMushSkillEnum.NERON_ACCESS]: { img: getImgUrl('skills/mush/neron_access.png'), max_height: "1.2em" },
    [EmoteMushSkillEnum.NERONDEPRESS]: { img: getImgUrl('skills/mush/nerondepress.png'), max_height: "1.2em" },
    [EmoteMushSkillEnum.NIGHTMARE]: { img: getImgUrl('skills/mush/nightmare.png'), max_height: "1.2em" },
    [EmoteMushSkillEnum.NIMBLE_FINGERS]: { img: getImgUrl('skills/mush/nimble_fingers.png'), max_height: "1.2em" },
    [EmoteMushSkillEnum.NINJA]: { img: getImgUrl('skills/mush/ninja.png'), max_height: "1.2em" },
    [EmoteMushSkillEnum.PHAGOCYTOSIS]: { img: getImgUrl('skills/mush/phagocytosis.png'), max_height: "1.2em" },
    [EmoteMushSkillEnum.PYROMANE]: { img: getImgUrl('skills/mush/pyromane.png'), max_height: "1.2em" },
    [EmoteMushSkillEnum.RADIO_PIRACY]: { img: getImgUrl('skills/mush/radio_piracy.png'), max_height: "1.2em" },
    [EmoteMushSkillEnum.SAPPER]: { img: getImgUrl('skills/mush/sapper.png'), max_height: "1.2em" },
    [EmoteMushSkillEnum.SLIMETRAP]: { img: getImgUrl('skills/mush/slimetrap.png'), max_height: "1.2em" },
    [EmoteMushSkillEnum.TOUGH]: { img: getImgUrl('skills/mush/tough.png'), max_height: "1.2em" },
    [EmoteMushSkillEnum.TRAITOR]: { img: getImgUrl('skills/mush/traitor.png'), max_height: "1.2em" },
    [EmoteMushSkillEnum.TRANSFERT]: { img: getImgUrl('skills/mush/transfert.png'), max_height: "1.2em" },
    [EmoteMushSkillEnum.TRAPPER]: { img: getImgUrl('skills/mush/trapper.png'), max_height: "1.2em" },
    [EmoteMushSkillEnum.WATER_RESISTANT]: { img: getImgUrl('skills/mush/water_resistant.png'), max_height: "1.2em" }
};
