import { getImgUrl } from "@/utils/getImgUrl";
import { EmoteCharacterEnum } from "@/enums/emotes/characters.enum";

export enum EmoteHumanSkillEnum {
    ABNEGATION = 'sk_abnegation',
    ADAPTABLE = 'sk_adaptable',
    ANTIC_PERFUME = 'sk_antic_perfume',
    ASTROPHYSICIST = 'sk_astrophysicist',
    BIOLOGIST = 'sk_biologist',
    BOTANIC = 'sk_botanic',
    CAFFEINOMANIAC = 'sk_caffeinomaniac',
    COLD_BLOOD = 'sk_cold_blood',
    COMMUNICATION = 'sk_communication',
    CONCEPTOR = 'sk_conceptor',
    CONFIDENT = 'sk_confident',
    COOK = 'sk_cook',
    CRAZY_EYE = 'sk_crazy_eye',
    CREATIVE = 'sk_creative',
    DAUNTING = 'sk_daunting',
    DEVOTION = 'sk_devotion',
    DIPLOMACY = 'sk_diplomacy',
    DISABLED_SPRINTER = 'sk_disabled_sprinter',
    ENGINEER = 'sk_engineer',
    ESCAPE = 'sk_escape',
    EXPERT = 'sk_expert',
    FAST_BACKWARD = 'sk_fast_backward',
    FIREMAN = 'sk_fireman',
    FIRST_AID = 'sk_first_aid',
    FRUGIVORE = 'sk_frugivore',
    GENIUS = 'sk_genius',
    GREEN_THUMB = 'sk_green_thumb',
    GUNMAN = 'sk_gunman',
    GUNNER = 'sk_gunner',
    HUNT = 'sk_hunt',
    IT_EXPERT = 'sk_it_expert',
    JUGE = 'sk_juge',
    LEADERSHIP = 'sk_leadership',
    LETHARGY = 'sk_lethargy',
    LOGISTICS = 'sk_logistics',
    MANKIND_ONLY_HOPE = 'sk_mankind_only_hope',
    MEDIC = 'sk_medic',
    METALICISTE = 'sk_metaliciste',
    MOTIVATOR = 'sk_motivator',
    MYCOLOGIST = 'sk_mycologist',
    NERON_ONLY_FRIEND = 'sk_neron_only_friend',
    OBSERVANT = 'sk_observant',
    OPPORTUNIST = 'sk_opportunist',
    OPTIMISTIC = 'sk_optimistic',
    PANIC = 'sk_panic',
    PARANOID = 'sk_paranoid',
    PERSISTENT = 'sk_persistent',
    PHYSICIST = 'sk_physicist',
    PILOT = 'sk_pilot',
    POLITICIAN = 'sk_politician',
    POLYMATH = 'sk_polymath',
    POLYVALENT = 'sk_polyvalent',
    PREMONITION = 'sk_premonition',
    REBEL = 'sk_rebel',
    ROBOTICS = 'sk_robotics',
    SHRINK = 'sk_shrink',
    SPACE_TACTICS = 'sk_space_tactics',
    SPRINTER = 'sk_sprinter',
    STICKLER = 'sk_stickler',
    STRONG_SKIN = 'sk_strong_skin',
    STURDY = 'sk_sturdy',
    SURVIVAL = 'sk_survival',
    TORTURER = 'sk_torturer',
    UNCONCERNED = 'sk_unconcerned',
    WRESTLER = 'sk_wrestler',
}

export const EmoteHumanSkillAliases: { [index: string]: string } = { };

export const EmoteHumanSkillIcons: { [index: string]: string } = {
    [EmoteHumanSkillEnum.ABNEGATION]: getImgUrl('skills/human/abnegation.png'),
    [EmoteHumanSkillEnum.ADAPTABLE]: getImgUrl('skills/human/adaptable.png'),
    [EmoteHumanSkillEnum.ANTIC_PERFUME]: getImgUrl('skills/human/antic_perfume.png'),
    [EmoteHumanSkillEnum.ASTROPHYSICIST]: getImgUrl('skills/human/astrophysicist.png'),
    [EmoteHumanSkillEnum.BIOLOGIST]: getImgUrl('skills/human/biologist.png'),
    [EmoteHumanSkillEnum.BOTANIC]: getImgUrl('skills/human/botanic.png'),
    [EmoteHumanSkillEnum.CAFFEINOMANIAC]: getImgUrl('skills/human/caffeinomaniac.png'),
    [EmoteHumanSkillEnum.COLD_BLOOD]: getImgUrl('skills/human/cold_blood.png'),
    [EmoteHumanSkillEnum.COMMUNICATION]: getImgUrl('skills/human/communication.png'),
    [EmoteHumanSkillEnum.CONCEPTOR]: getImgUrl('skills/human/conceptor.png'),
    [EmoteHumanSkillEnum.CONFIDENT]: getImgUrl('skills/human/confident.png'),
    [EmoteHumanSkillEnum.COOK]: getImgUrl('skills/human/cook.png'),
    [EmoteHumanSkillEnum.CRAZY_EYE]: getImgUrl('skills/human/crazy_eye.png'),
    [EmoteHumanSkillEnum.CREATIVE]: getImgUrl('skills/human/creative.png'),
    [EmoteHumanSkillEnum.DAUNTING]: getImgUrl('skills/human/daunting.png'),
    [EmoteHumanSkillEnum.DEVOTION]: getImgUrl('skills/human/devotion.png'),
    [EmoteHumanSkillEnum.DIPLOMACY]: getImgUrl('skills/human/diplomacy.png'),
    [EmoteHumanSkillEnum.DISABLED_SPRINTER]: getImgUrl('skills/human/disabled_sprinter.png'),
    [EmoteHumanSkillEnum.ENGINEER]: getImgUrl('skills/human/engineer.png'),
    [EmoteHumanSkillEnum.ESCAPE]: getImgUrl('skills/human/escape.png'),
    [EmoteHumanSkillEnum.EXPERT]: getImgUrl('skills/human/expert.png'),
    [EmoteHumanSkillEnum.FAST_BACKWARD]: getImgUrl('skills/human/fast_backward.png'),
    [EmoteHumanSkillEnum.FIREMAN]: getImgUrl('skills/human/fireman.png'),
    [EmoteHumanSkillEnum.FIRST_AID]: getImgUrl('skills/human/first_aid.png'),
    [EmoteHumanSkillEnum.FRUGIVORE]: getImgUrl('skills/human/frugivore.png'),
    [EmoteHumanSkillEnum.GENIUS]: getImgUrl('skills/human/genius.png'),
    [EmoteHumanSkillEnum.GREEN_THUMB]: getImgUrl('skills/human/green_thumb.png'),
    [EmoteHumanSkillEnum.GUNMAN]: getImgUrl('skills/human/gunman.png'),
    [EmoteHumanSkillEnum.GUNNER]: getImgUrl('skills/human/gunner.png'),
    [EmoteHumanSkillEnum.HUNT]: getImgUrl('skills/human/hunt.png'),
    [EmoteHumanSkillEnum.IT_EXPERT]: getImgUrl('skills/human/it_expert.png'),
    [EmoteHumanSkillEnum.JUGE]: getImgUrl('skills/human/juge.png'),
    [EmoteHumanSkillEnum.LEADERSHIP]: getImgUrl('skills/human/leadership.png'),
    [EmoteHumanSkillEnum.LETHARGY]: getImgUrl('skills/human/lethargy.png'),
    [EmoteHumanSkillEnum.LOGISTICS]: getImgUrl('skills/human/logistics.png'),
    [EmoteHumanSkillEnum.MANKIND_ONLY_HOPE]: getImgUrl('skills/human/mankind_only_hope.png'),
    [EmoteHumanSkillEnum.MEDIC]: getImgUrl('skills/human/medic.png'),
    [EmoteHumanSkillEnum.METALICISTE]: getImgUrl('skills/human/metaliciste.png'),
    [EmoteHumanSkillEnum.MOTIVATOR]: getImgUrl('skills/human/motivator.png'),
    [EmoteHumanSkillEnum.MYCOLOGIST]: getImgUrl('skills/human/mycologist.png'),
    [EmoteHumanSkillEnum.NERON_ONLY_FRIEND]: getImgUrl('skills/human/neron_only_friend.png'),
    [EmoteHumanSkillEnum.OBSERVANT]: getImgUrl('skills/human/observant.png'),
    [EmoteHumanSkillEnum.OPPORTUNIST]: getImgUrl('skills/human/opportunist.png'),
    [EmoteHumanSkillEnum.OPTIMISTIC]: getImgUrl('skills/human/optimistic.png'),
    [EmoteHumanSkillEnum.PANIC]: getImgUrl('skills/human/panic.png'),
    [EmoteHumanSkillEnum.PARANOID]: getImgUrl('skills/human/paranoid.png'),
    [EmoteHumanSkillEnum.PERSISTENT]: getImgUrl('skills/human/persistent.png'),
    [EmoteHumanSkillEnum.PHYSICIST]: getImgUrl('skills/human/physicist.png'),
    [EmoteHumanSkillEnum.PILOT]: getImgUrl('skills/human/pilot.png'),
    [EmoteHumanSkillEnum.POLITICIAN]: getImgUrl('skills/human/politician.png'),
    [EmoteHumanSkillEnum.POLYMATH]: getImgUrl('skills/human/polymath.png'),
    [EmoteHumanSkillEnum.POLYVALENT]: getImgUrl('skills/human/polyvalent.png'),
    [EmoteHumanSkillEnum.PREMONITION]: getImgUrl('skills/human/premonition.png'),
    [EmoteHumanSkillEnum.REBEL]: getImgUrl('skills/human/rebel.png'),
    [EmoteHumanSkillEnum.ROBOTICS]: getImgUrl('skills/human/robotics.png'),
    [EmoteHumanSkillEnum.SHRINK]: getImgUrl('skills/human/shrink.png'),
    [EmoteHumanSkillEnum.SPACE_TACTICS]: getImgUrl('skills/human/space_tactics.png'),
    [EmoteHumanSkillEnum.SPRINTER]: getImgUrl('skills/human/sprinter.png'),
    [EmoteHumanSkillEnum.STICKLER]: getImgUrl('skills/human/stickler.png'),
    [EmoteHumanSkillEnum.STRONG_SKIN]: getImgUrl('skills/human/strong_skin.png'),
    [EmoteHumanSkillEnum.STURDY]: getImgUrl('skills/human/sturdy.png'),
    [EmoteHumanSkillEnum.SURVIVAL]: getImgUrl('skills/human/survival.png'),
    [EmoteHumanSkillEnum.TORTURER]: getImgUrl('skills/human/torturer.png'),
    [EmoteHumanSkillEnum.UNCONCERNED]: getImgUrl('skills/human/unconcerned.png'),
    [EmoteHumanSkillEnum.WRESTLER]: getImgUrl('skills/human/wrestler.png')
};

export enum EmoteMushSkillEnum {
    ANONYMOUS = 'sk_anonymous',
    BACTERIAL_CONTACT = 'sk_bacterial_contact',
    BETA_MUSH = 'sk_beta_mush',
    DEFACER = 'sk_defacer',
    DISHEARTENING_CONTACT = 'sk_disheartening_contact',
    DOORMAN = 'sk_doorman',
    ELECTRO_SLIME = 'sk_electro_slime',
    FERTILE = 'sk_fertile',
    FUNGUS_COOK = 'sk_fungus_cook',
    INFECTIOUS_AGENT = 'sk_infectious_agent',
    MASSGGEDON = 'sk_massggedon',
    MYCELLIUM_SPIRIT = 'sk_mycellium_spirit',
    NERON_ACCESS = 'sk_neron_access',
    NERONDEPRESS = 'sk_nerondepress',
    NIGHTMARE = 'sk_nightmare',
    NIMBLE_FINGERS = 'sk_nimble_fingers',
    NINJA = 'sk_ninja',
    PHAGOCYTOSIS = 'sk_phagocytosis',
    PYROMANE = 'sk_pyromane',
    RADIO_PIRACY = 'sk_radio_piracy',
    SAPPER = 'sk_sapper',
    SLIMETRAP = 'sk_slimetrap',
    TOUGH = 'sk_tough',
    TRAITOR = 'sk_traitor',
    TRANSFERT = 'sk_transfert',
    TRAPPER = 'sk_trapper',
    WATER_RESISTANT = 'sk_water_resistant',
}

export const EmoteMushSkillAliases: { [index: string]: string } = { };

export const EmoteMushSkillIcons: { [index: string]: string } = {
    [EmoteMushSkillEnum.ANONYMOUS]: getImgUrl('skills/mush/anonymous.png'),
    [EmoteMushSkillEnum.BACTERIAL_CONTACT]: getImgUrl('skills/mush/bacterial_contact.png'),
    [EmoteMushSkillEnum.BETA_MUSH]: getImgUrl('skills/mush/beta_mush.png'),
    [EmoteMushSkillEnum.DEFACER]: getImgUrl('skills/mush/defacer.png'),
    [EmoteMushSkillEnum.DISHEARTENING_CONTACT]: getImgUrl('skills/mush/disheartening_contact.png'),
    [EmoteMushSkillEnum.DOORMAN]: getImgUrl('skills/mush/doorman.png'),
    [EmoteMushSkillEnum.ELECTRO_SLIME]: getImgUrl('skills/mush/electro_slime.png'),
    [EmoteMushSkillEnum.FERTILE]: getImgUrl('skills/mush/fertile.png'),
    [EmoteMushSkillEnum.FUNGUS_COOK]: getImgUrl('skills/mush/fungus_cook.png'),
    [EmoteMushSkillEnum.INFECTIOUS_AGENT]: getImgUrl('skills/mush/infectious_agent.png'),
    [EmoteMushSkillEnum.MASSGGEDON]: getImgUrl('skills/mush/massggedon.png'),
    [EmoteMushSkillEnum.MYCELLIUM_SPIRIT]: getImgUrl('skills/mush/mycellium_spirit.png'),
    [EmoteMushSkillEnum.NERON_ACCESS]: getImgUrl('skills/mush/neron_access.png'),
    [EmoteMushSkillEnum.NERONDEPRESS]: getImgUrl('skills/mush/nerondepress.png'),
    [EmoteMushSkillEnum.NIGHTMARE]: getImgUrl('skills/mush/nightmare.png'),
    [EmoteMushSkillEnum.NIMBLE_FINGERS]: getImgUrl('skills/mush/nimble_fingers.png'),
    [EmoteMushSkillEnum.NINJA]: getImgUrl('skills/mush/ninja.png'),
    [EmoteMushSkillEnum.PHAGOCYTOSIS]: getImgUrl('skills/mush/phagocytosis.png'),
    [EmoteMushSkillEnum.PYROMANE]: getImgUrl('skills/mush/pyromane.png'),
    [EmoteMushSkillEnum.RADIO_PIRACY]: getImgUrl('skills/mush/radio_piracy.png'),
    [EmoteMushSkillEnum.SAPPER]: getImgUrl('skills/mush/sapper.png'),
    [EmoteMushSkillEnum.SLIMETRAP]: getImgUrl('skills/mush/slimetrap.png'),
    [EmoteMushSkillEnum.TOUGH]: getImgUrl('skills/mush/tough.png'),
    [EmoteMushSkillEnum.TRAITOR]: getImgUrl('skills/mush/traitor.png'),
    [EmoteMushSkillEnum.TRANSFERT]: getImgUrl('skills/mush/transfert.png'),
    [EmoteMushSkillEnum.TRAPPER]: getImgUrl('skills/mush/trapper.png'),
    [EmoteMushSkillEnum.WATER_RESISTANT]: getImgUrl('skills/mush/water_resistant.png')
};
