import { getImgUrl } from "@/utils/getImgUrl";
import { EmoteCharacterEnum } from "@/enums/emotes/characters.enum";



export enum EmoteStatusEnum {
    ARTEFACT = 'st_artefact',
    BEGINNER = 'st_beginner',
    BELLY_FULL = 'st_belly_full',
    BROKEN = 'st_broken',
    BERZERK = 'st_berzerk',
    CHARGE = 'st_charge',
    DEMORALIZED = 'st_demoralized',
    DISABLED = 'st_disabled',
    DISEASE = 'st_disease',
    DISORDER = 'st_disorder',
    FIRE = 'st_fire',
    FIRST_TIME = 'st_first_time',
    FOOD_FROZEN = 'st_food_frozen',
    FOOD_DECAYING = 'st_food_decaying',
    FOOD_HAZARDOUS = 'st_food_hazardous',
    FOOD_UNSTABLE = 'st_food_unstable',
    GAGGED = 'st_gagged',
    GENIUS_IDEA = 'st_genius_idea',
    GERMAPHOBIC = 'st_germaphobic',
    GUARDIAN = 'st_guardian',
    HAMMER = 'st_hammer',
    HEAVY = 'st_heavy',
    HIDDEN = 'st_hidden',
    SLEEPY = 'st_sleepy',
    HIGHLY_INACTIVE = 'st_highly_inactive',
    HYPERACTIVE = 'st_hyperactive',
    IMMUNE = 'st_immune',
    INJURY = 'st_injury',
    IS_ANONYMOUS = 'st_is_anonymous',
    LAID = 'st_laid',
    LOST_ON_PLANET = 'st_lost_on_planet',
    MODULING = 'st_moduling',
    MULTI = 'st_multi',
    MUSH = 'st_mush',
    PACIFIST = 'st_pacifist',
    PLANT_DISEASED = 'st_plant_diseased',
    PLANT_DRY = 'st_plant_dry',
    PLANT_THIRSTY = 'st_plant_thirsty',
    PLANT_YOUNGLING = 'st_plant_youngling',
    PREGNANT = 'st_pregnant',
    SPORE = 'st_spore',
    STARVING = 'st_starving',
    STINKY = 'st_stinky',
    STUCK_IN_SHIP = 'st_stuck_in_ship',
    SUICIDAL = 'st_suicidal',
    THINKLINKED = 'st_thinklinked',
    UNSOCIABLE = 'st_unsociable',
    UPDATING = 'st_updating',
    COMMANDER = 'st_commander',
    COMMS_MANAGER = 'st_comms_manager',
    NERON_MANAGER = 'st_neron_manager',
}

export const EmoteStatusAliases: { [index: string]: string } = {
    ['demoralized']: EmoteStatusEnum.DEMORALIZED,
    ['hungry']: EmoteStatusEnum.STARVING,
    ['starving']: EmoteStatusEnum.STARVING,
    ['ill']: EmoteStatusEnum.DISEASE,
    ['psy_disease']: EmoteStatusEnum.DISORDER,
    ['hurt']: EmoteStatusEnum.INJURY,
    ['dirty']: EmoteStatusEnum.STINKY,
    ['gagged']: EmoteStatusEnum.GAGGED,
    ['hyperactive']: EmoteStatusEnum.HYPERACTIVE,
    ['broken']: EmoteStatusEnum.BROKEN,
    ['frozen']: EmoteStatusEnum.FOOD_FROZEN,
    ['unstable']: EmoteStatusEnum.FOOD_UNSTABLE,
    ['hazardous']: EmoteStatusEnum.FOOD_HAZARDOUS,
    ['decomposing']: EmoteStatusEnum.FOOD_DECAYING,
    ['updating']: EmoteStatusEnum.UPDATING,
    ['pacifist']: EmoteStatusEnum.PACIFIST,
    ['focused']: EmoteStatusEnum.MODULING,
    ['heavy']: EmoteStatusEnum.HEAVY,
    ['hidden']: EmoteStatusEnum.HIDDEN,
    ['antisocial']: EmoteStatusEnum.UNSOCIABLE,
    ['outcast']: EmoteStatusEnum.UNSOCIABLE,
    ['plant_young']: EmoteStatusEnum.PLANT_YOUNGLING,
    ['plant_thirsty']: EmoteStatusEnum.PLANT_THIRSTY,
    ['plant_dry']: EmoteStatusEnum.PLANT_DRY,
    ['plant_diseased']: EmoteStatusEnum.PLANT_DISEASED,
    ['electric_charges']: EmoteStatusEnum.CHARGE,
    ['contaminated']: EmoteStatusEnum.MUSH,
    ['cat_infected']: EmoteStatusEnum.MUSH,
    ['commander']: EmoteStatusEnum.COMMANDER,
    ['comm_manager']: EmoteStatusEnum.COMMS_MANAGER,
    ['comms_manager']: EmoteStatusEnum.COMMS_MANAGER,
    ['neron_manager']: EmoteStatusEnum.NERON_MANAGER
};

export const EmoteStatusIcons: {[index: string]: {img: string; max_height: string;}}= {
    [EmoteStatusEnum.ARTEFACT]: { img: getImgUrl('status/artefact.png'), max_height: "1.2em" },
    [EmoteStatusEnum.BEGINNER]: { img: getImgUrl('status/beginner.png'), max_height: "1.2em" },
    [EmoteStatusEnum.BELLY_FULL]: { img: getImgUrl('status/belly_full.png'), max_height: "1.2em" },
    [EmoteStatusEnum.BERZERK]: { img: getImgUrl('status/berzerk.png'), max_height: "1.2em" },
    [EmoteStatusEnum.BROKEN]: { img: getImgUrl('status/broken.png'), max_height: "1.2em" },
    [EmoteStatusEnum.CHARGE]: { img: getImgUrl('status/charge.png'), max_height: "1.2em" },
    [EmoteStatusEnum.DEMORALIZED]: { img: getImgUrl('status/demoralized.png'), max_height: "1.2em" },
    [EmoteStatusEnum.DISABLED]: { img: getImgUrl('status/disabled.png'), max_height: "1.2em" },
    [EmoteStatusEnum.DISEASE]: { img: getImgUrl('status/disease.png'), max_height: "1.2em" },
    [EmoteStatusEnum.DISORDER]: { img: getImgUrl('status/disorder.png'), max_height: "1.2em" },
    [EmoteStatusEnum.FIRE]: { img: getImgUrl('status/fire.png'), max_height: "1.2em" },
    [EmoteStatusEnum.FIRST_TIME]: { img: getImgUrl('status/first_time.png'), max_height: "1.2em" },
    [EmoteStatusEnum.FOOD_DECAYING]: { img: getImgUrl('status/food_decaying.png'), max_height: "1.2em" },
    [EmoteStatusEnum.FOOD_FROZEN]: { img: getImgUrl('status/food_frozen.png'), max_height: "1.2em" },
    [EmoteStatusEnum.FOOD_HAZARDOUS]: { img: getImgUrl('status/food_hazardous.png'), max_height: "1.2em" },
    [EmoteStatusEnum.FOOD_UNSTABLE]: { img: getImgUrl('status/food_unstable.png'), max_height: "1.2em" },
    [EmoteStatusEnum.GAGGED]: { img: getImgUrl('status/gagged.png'), max_height: "1.2em" },
    [EmoteStatusEnum.GENIUS_IDEA]: { img: getImgUrl('status/genius_idea.png'), max_height: "1.2em" },
    [EmoteStatusEnum.GERMAPHOBIC]: { img: getImgUrl('status/germaphobic.png'), max_height: "1.2em" },
    [EmoteStatusEnum.GUARDIAN]: { img: getImgUrl('status/guardian.png'), max_height: "1.2em" },
    [EmoteStatusEnum.HAMMER]: { img: getImgUrl('status/hammer.png'), max_height: "1.2em" },
    [EmoteStatusEnum.HEAVY]: { img: getImgUrl('status/heavy.png'), max_height: "1.2em" },
    [EmoteStatusEnum.HIDDEN]: { img: getImgUrl('status/hidden.png'), max_height: "1.2em" },
    [EmoteStatusEnum.HIGHLY_INACTIVE]: { img: getImgUrl('status/highly_inactive.png'), max_height: "1.2em" },
    [EmoteStatusEnum.HYPERACTIVE]: { img: getImgUrl('status/hyperactive.png'), max_height: "1.2em" },
    [EmoteStatusEnum.IMMUNE]: { img: getImgUrl('status/immune.png'), max_height: "1.2em" },
    [EmoteStatusEnum.INJURY]: { img: getImgUrl('status/injury.png'), max_height: "1.2em" },
    [EmoteStatusEnum.IS_ANONYMOUS]: { img: getImgUrl('status/is_anonymous.png'), max_height: "1.2em" },
    [EmoteStatusEnum.LAID]: { img: getImgUrl('status/laid.png'), max_height: "1.2em" },
    [EmoteStatusEnum.LOST_ON_PLANET]: { img: getImgUrl('status/lost_on_planet.png'), max_height: "1.2em" },
    [EmoteStatusEnum.MODULING]: { img: getImgUrl('status/moduling.png'), max_height: "1.2em" },
    [EmoteStatusEnum.MULTI]: { img: getImgUrl('status/multi.png'), max_height: "1.2em" },
    [EmoteStatusEnum.MUSH]: { img: getImgUrl('status/mush.png'), max_height: "1.2em" },
    [EmoteStatusEnum.PACIFIST]: { img: getImgUrl('status/pacifist.png'), max_height: "1.2em" },
    [EmoteStatusEnum.PLANT_DISEASED]: { img: getImgUrl('status/plant_diseased.png'), max_height: "1.2em" },
    [EmoteStatusEnum.PLANT_DRY]: { img: getImgUrl('status/plant_dry.png'), max_height: "1.2em" },
    [EmoteStatusEnum.PLANT_THIRSTY]: { img: getImgUrl('status/plant_thirsty.png'), max_height: "1.2em" },
    [EmoteStatusEnum.PLANT_YOUNGLING]: { img: getImgUrl('status/plant_youngling.png'), max_height: "1.2em" },
    [EmoteStatusEnum.PREGNANT]: { img: getImgUrl('status/pregnant.png'), max_height: "1.2em" },
    [EmoteStatusEnum.SLEEPY]: { img: getImgUrl('status/sleepy.png'), max_height: "1.2em" },
    [EmoteStatusEnum.SPORE]: { img: getImgUrl('status/spore.png'), max_height: "1.2em" },
    [EmoteStatusEnum.STARVING]: { img: getImgUrl('status/starving.png'), max_height: "1.2em" },
    [EmoteStatusEnum.STINKY]: { img: getImgUrl('status/stinky.png'), max_height: "1.2em" },
    [EmoteStatusEnum.STUCK_IN_SHIP]: { img: getImgUrl('status/stuck_in_ship.png'), max_height: "1.2em" },
    [EmoteStatusEnum.SUICIDAL]: { img: getImgUrl('status/suicidal.png'), max_height: "1.2em" },
    [EmoteStatusEnum.THINKLINKED]: { img: getImgUrl('status/thinklinked.png'), max_height: "1.2em" },
    [EmoteStatusEnum.UNSOCIABLE]: { img: getImgUrl('status/unsociable.png'), max_height: "1.2em" },
    [EmoteStatusEnum.UPDATING]: { img: getImgUrl('status/update.png'), max_height: "1.2em" },
    [EmoteStatusEnum.COMMANDER]: { img: getImgUrl('title_commander.png'), max_height: "1.2em" },
    [EmoteStatusEnum.COMMS_MANAGER]: { img: getImgUrl('title_com_manager.png'), max_height: "1.2em" },
    [EmoteStatusEnum.NERON_MANAGER]: { img: getImgUrl('title_neron_manager.png'), max_height: "1.2em" }
};
