import { getImgUrl } from "@/utils/getImgUrl";

export enum EmoteStatusEnum {
    ARTEFACT = 'st_artefact',
    BEGINNER = 'st_beginner',
    BELLY_FULL = 'st_belly_full',
    BROKEN = 'st_broken',
    BERSERK = 'st_berserk',
    CHARGE = 'st_charge',
    NO_CHARGE = 'st_no_charge',
    DEMORALIZED = 'st_demoralized',
    DISABLED = 'st_disabled',
    DISEASE = 'st_disease',
    DISORDER = 'st_disorder',
    FIRST_TIME = 'st_first_time',
    FOOD_FROZEN = 'st_food_frozen',
    FOOD_DECAYING = 'st_food_decaying',
    FOOD_HAZARDOUS = 'st_food_hazardous',
    FOOD_UNSTABLE = 'st_food_unstable',
    GAGGED = 'st_gagged',
    GENIUS_IDEA = 'st_genius_idea',
    GERMAPHOBIC = 'st_germaphobic',
    GUARDIAN = 'st_guardian',
    HAMMER = 'st_hammer',
    HEAVY = 'st_heavy',
    HIDDEN = 'st_hidden',
    HIGHLY_INACTIVE = 'st_highly_inactive',
    HYPERACTIVE = 'st_hyperactive',
    IMMUNE = 'st_immune',
    INACTIVE = 'st_inactive',
    INJURY = 'st_injury',
    IS_ANONYMOUS = 'st_is_anonymous',
    LAID = 'st_laid',
    LOST = 'st_lost',
    MODULING = 'st_moduling',
    MULTI = 'st_multi',
    MUSH = 'st_mush',
    PACIFIST = 'st_pacifist',
    PLANT_DISEASED = 'st_plant_diseased',
    PLANT_DRY = 'st_plant_dry',
    PLANT_THIRSTY = 'st_plant_thirsty',
    PLANT_YOUNGLING = 'st_plant_youngling',
    PREGNANT = 'st_pregnant',
    SPORE = 'st_spore',
    STARVING = 'st_starving',
    STINKY = 'st_stinky',
    STUCK_IN_SHIP = 'st_stuck_in_ship',
    SUICIDAL = 'st_suicidal',
    THINKLINKED = 'st_thinklinked',
    UNSOCIABLE = 'st_unsociable',
    COMMANDER = 'st_commander',
    COMMS_MANAGER = 'st_comms_manager',
    NERON_MANAGER = 'st_neron_manager',
}

export const EmoteStatusAliases: { [index: string]: string } = {
    ['full_stomach']: EmoteStatusEnum.BELLY_FULL,
    ['beginner']: EmoteStatusEnum.BEGINNER,
    ['berserk']: EmoteStatusEnum.BERSERK,
    ['berzerk']: EmoteStatusEnum.BERSERK,
    ['broken']: EmoteStatusEnum.BROKEN,
    ['electric_charges']: EmoteStatusEnum.CHARGE,
    ['commander']: EmoteStatusEnum.COMMANDER,
    ['com_manager']: EmoteStatusEnum.COMMS_MANAGER,
    ['comm_manager']: EmoteStatusEnum.COMMS_MANAGER,
    ['comms_manager']: EmoteStatusEnum.COMMS_MANAGER,
    ['neron_manager']: EmoteStatusEnum.NERON_MANAGER,
    ['neron_admin']: EmoteStatusEnum.NERON_MANAGER,
    ['demoralized']: EmoteStatusEnum.DEMORALIZED,
    ['ill']: EmoteStatusEnum.DISEASE,
    ['disease']: EmoteStatusEnum.DISEASE,
    ['disabled']: EmoteStatusEnum.DISABLED,
    ['psy_disease']: EmoteStatusEnum.DISORDER,
    ['disorder']: EmoteStatusEnum.DISORDER,
    ['first_time']: EmoteStatusEnum.FIRST_TIME,
    ['decomposing']: EmoteStatusEnum.FOOD_DECAYING,
    ['frozen']: EmoteStatusEnum.FOOD_FROZEN,
    ['hazardous']: EmoteStatusEnum.FOOD_HAZARDOUS,
    ['unstable']: EmoteStatusEnum.FOOD_UNSTABLE,
    ['gagged']: EmoteStatusEnum.GAGGED,
    ['genius_idea']: EmoteStatusEnum.GENIUS_IDEA,
    ['germaphobe']: EmoteStatusEnum.GERMAPHOBIC,
    ['guardian']: EmoteStatusEnum.GUARDIAN,
    ['pariah']: EmoteStatusEnum.HAMMER,
    ['heavy']: EmoteStatusEnum.HEAVY,
    ['burdened']: EmoteStatusEnum.HEAVY,
    ['hidden']: EmoteStatusEnum.HIDDEN,
    ['highly_inactive']: EmoteStatusEnum.HIGHLY_INACTIVE,
    ['hyperactive']: EmoteStatusEnum.HYPERACTIVE,
    ['immunized']: EmoteStatusEnum.IMMUNE,
    ['antique_perfume_immunized']: EmoteStatusEnum.IMMUNE,
    ['inactive']: EmoteStatusEnum.INACTIVE,
    ['hurt']: EmoteStatusEnum.INJURY,
    ['injury']: EmoteStatusEnum.INJURY,
    ['is_anonymous']: EmoteStatusEnum.IS_ANONYMOUS,
    ['lying_down']: EmoteStatusEnum.LAID,
    ['lost']: EmoteStatusEnum.LOST,
    ['focused']: EmoteStatusEnum.MODULING,
    ['mush']: EmoteStatusEnum.MUSH,
    ['contaminated']: EmoteStatusEnum.MUSH,
    ['cat_infected']: EmoteStatusEnum.MUSH,
    ['pacifist']: EmoteStatusEnum.PACIFIST,
    ['pregnant']: EmoteStatusEnum.PREGNANT,
    ['plant_diseased']: EmoteStatusEnum.PLANT_DISEASED,
    ['plant_dry']: EmoteStatusEnum.PLANT_DRY,
    ['plant_thirsty']: EmoteStatusEnum.PLANT_THIRSTY,
    ['plant_young']: EmoteStatusEnum.PLANT_YOUNGLING,
    ['hungry']: EmoteStatusEnum.STARVING,
    ['starving']: EmoteStatusEnum.STARVING,
    ['starving_warning']: EmoteStatusEnum.STARVING,
    ['dirty']: EmoteStatusEnum.STINKY,
    ['stuck_in_the_ship']: EmoteStatusEnum.STUCK_IN_SHIP,
    ['suicidal']: EmoteStatusEnum.SUICIDAL,
    ['brainsync']: EmoteStatusEnum.THINKLINKED,
    ['antisocial']: EmoteStatusEnum.UNSOCIABLE,
    ['outcast']: EmoteStatusEnum.UNSOCIABLE
};


export const EmoteStatusIcons: {[index: string]: {img: string; max_height: string;}}= {
    [EmoteStatusEnum.ARTEFACT]: { img: getImgUrl('status/artefact.png'), max_height: "1.2em" },
    [EmoteStatusEnum.BEGINNER]: { img: getImgUrl('status/beginner.png'), max_height: "1.2em" },
    [EmoteStatusEnum.BELLY_FULL]: { img: getImgUrl('status/belly_full.png'), max_height: "1.2em" },
    [EmoteStatusEnum.BERSERK]: { img: getImgUrl('status/berzerk.png'), max_height: "1.2em" },
    [EmoteStatusEnum.BROKEN]: { img: getImgUrl('status/broken.png'), max_height: "1.2em" },
    [EmoteStatusEnum.CHARGE]: { img: getImgUrl('status/charge.png'), max_height: "1.2em" },
    [EmoteStatusEnum.NO_CHARGE]: { img: getImgUrl('status/nocharge.png'), max_height: "1.2em" },
    [EmoteStatusEnum.DEMORALIZED]: { img: getImgUrl('status/demoralized.png'), max_height: "1.2em" },
    [EmoteStatusEnum.DISABLED]: { img: getImgUrl('status/disabled.png'), max_height: "1.2em" },
    [EmoteStatusEnum.DISEASE]: { img: getImgUrl('status/disease.png'), max_height: "1.2em" },
    [EmoteStatusEnum.DISORDER]: { img: getImgUrl('status/disorder.png'), max_height: "1.2em" },
    [EmoteStatusEnum.FIRST_TIME]: { img: getImgUrl('status/first_time.png'), max_height: "1.2em" },
    [EmoteStatusEnum.FOOD_DECAYING]: { img: getImgUrl('status/food_decaying.png'), max_height: "1.2em" },
    [EmoteStatusEnum.FOOD_FROZEN]: { img: getImgUrl('status/food_frozen.png'), max_height: "1.2em" },
    [EmoteStatusEnum.FOOD_HAZARDOUS]: { img: getImgUrl('status/food_hazardous.png'), max_height: "1.2em" },
    [EmoteStatusEnum.FOOD_UNSTABLE]: { img: getImgUrl('status/food_unstable.png'), max_height: "1.2em" },
    [EmoteStatusEnum.GAGGED]: { img: getImgUrl('status/gagged.png'), max_height: "1.2em" },
    [EmoteStatusEnum.GENIUS_IDEA]: { img: getImgUrl('status/genius_idea.png'), max_height: "1.2em" },
    [EmoteStatusEnum.GERMAPHOBIC]: { img: getImgUrl('status/germaphobic.png'), max_height: "1.2em" },
    [EmoteStatusEnum.GUARDIAN]: { img: getImgUrl('status/guardian.png'), max_height: "1.2em" },
    [EmoteStatusEnum.HAMMER]: { img: getImgUrl('status/hammer.png'), max_height: "1.2em" },
    [EmoteStatusEnum.HEAVY]: { img: getImgUrl('status/heavy.png'), max_height: "1.2em" },
    [EmoteStatusEnum.HIDDEN]: { img: getImgUrl('status/hidden.png'), max_height: "1.2em" },
    [EmoteStatusEnum.HIGHLY_INACTIVE]: { img: getImgUrl('status/highly_inactive.png'), max_height: "1.2em" },
    [EmoteStatusEnum.HYPERACTIVE]: { img: getImgUrl('status/hyperactive.png'), max_height: "1.2em" },
    [EmoteStatusEnum.IMMUNE]: { img: getImgUrl('status/immune.png'), max_height: "1.2em" },
    [EmoteStatusEnum.INACTIVE]: { img: getImgUrl('status/sleepy.png'), max_height: "1.2em" },
    [EmoteStatusEnum.INJURY]: { img: getImgUrl('status/injury.png'), max_height: "1.2em" },
    [EmoteStatusEnum.IS_ANONYMOUS]: { img: getImgUrl('status/is_anonymous.png'), max_height: "1.2em" },
    [EmoteStatusEnum.LAID]: { img: getImgUrl('status/laid.png'), max_height: "1.2em" },
    [EmoteStatusEnum.LOST]: { img: getImgUrl('status/lost_on_planet.png'), max_height: "1.2em" },
    [EmoteStatusEnum.MODULING]: { img: getImgUrl('status/moduling.png'), max_height: "1.2em" },
    [EmoteStatusEnum.MULTI]: { img: getImgUrl('status/multi.png'), max_height: "1.2em" },
    [EmoteStatusEnum.MUSH]: { img: getImgUrl('status/mush.png'), max_height: "1.2em" },
    [EmoteStatusEnum.PACIFIST]: { img: getImgUrl('status/pacifist.png'), max_height: "1.2em" },
    [EmoteStatusEnum.PLANT_DISEASED]: { img: getImgUrl('status/plant_diseased.png'), max_height: "1.2em" },
    [EmoteStatusEnum.PLANT_DRY]: { img: getImgUrl('status/plant_dry.png'), max_height: "1.2em" },
    [EmoteStatusEnum.PLANT_THIRSTY]: { img: getImgUrl('status/plant_thirsty.png'), max_height: "1.2em" },
    [EmoteStatusEnum.PLANT_YOUNGLING]: { img: getImgUrl('status/plant_youngling.png'), max_height: "1.2em" },
    [EmoteStatusEnum.PREGNANT]: { img: getImgUrl('status/pregnant.png'), max_height: "1.2em" },
    [EmoteStatusEnum.SPORE]: { img: getImgUrl('status/spore.png'), max_height: "1.2em" },
    [EmoteStatusEnum.STARVING]: { img: getImgUrl('status/starving.png'), max_height: "1.2em" },
    [EmoteStatusEnum.STINKY]: { img: getImgUrl('status/stinky.png'), max_height: "1.2em" },
    [EmoteStatusEnum.STUCK_IN_SHIP]: { img: getImgUrl('status/stuck_in_ship.png'), max_height: "1.2em" },
    [EmoteStatusEnum.SUICIDAL]: { img: getImgUrl('status/suicidal.png'), max_height: "1.2em" },
    [EmoteStatusEnum.THINKLINKED]: { img: getImgUrl('status/thinklinked.png'), max_height: "1.2em" },
    [EmoteStatusEnum.UNSOCIABLE]: { img: getImgUrl('status/unsociable.png'), max_height: "1.2em" },
    [EmoteStatusEnum.COMMANDER]: { img: getImgUrl('title_commander.png'), max_height: "1.2em" },
    [EmoteStatusEnum.COMMS_MANAGER]: { img: getImgUrl('title_com_manager.png'), max_height: "1.2em" },
    [EmoteStatusEnum.NERON_MANAGER]: { img: getImgUrl('title_neron_manager.png'), max_height: "1.2em" }
};
