import { getImgUrl } from "@/utils/getImgUrl";
import { EmoteCharacterEnum } from "@/enums/emotes/characters.enum";



export enum EmoteStatusEnum {
    ARTEFACT = 'st_artefact',
    BEGINNER = 'st_beginner',
    BELLY_FULL = 'st_belly_full',
    BROKEN = 'st_broken',
    BERZERK = 'st_berzerk',
    CHARGE = 'st_charge',
    DEMORALIZED = 'st_demoralized',
    DISABLED = 'st_disabled',
    DISEASE = 'st_disease',
    DISORDER = 'st_disorder',
    FIRE = 'st_fire',
    FIRST_TIME = 'st_first_time',
    FOOD_FROZEN = 'st_food_frozen',
    FOOD_DECAYING = 'st_food_decaying',
    FOOD_HAZARDOUS = 'st_food_hazardous',
    FOOD_UNSTABLE = 'st_food_unstable',
    GAGGED = 'st_gagged',
    GENIUS_IDEA = 'st_genius_idea',
    GERMAPHOBIC = 'st_germaphobic',
    GUARDIAN = 'st_guardian',
    HAMMER = 'st_hammer',
    HEAVY = 'st_heavy',
    HIDDEN = 'st_hidden',
    SLEEPY = 'st_sleepy',
    HIGHLY_INACTIVE = 'st_highly_inactive',
    HYPERACTIVE = 'st_hyperactive',
    IMMUNE = 'st_immune',
    INJURY = 'st_injury',
    IS_ANONYMOUS = 'st_is_anonymous',
    LAID = 'st_laid',
    LOST_ON_PLANET = 'st_lost_on_planet',
    MODULING = 'st_moduling',
    MULTI = 'st_multi',
    MUSH = 'st_mush',
    PACIFIST = 'st_pacifist',
    PLANT_DISEASED = 'st_plant_diseased',
    PLANT_DRY = 'st_plant_dry',
    PLANT_THIRSTY = 'st_plant_thirsty',
    PLANT_YOUNGLING = 'st_plant_youngling',
    PREGNANT = 'st_pregnant',
    SPORE = 'st_spore',
    STARVING = 'st_starving',
    STINKY = 'st_stinky',
    STUCK_IN_SHIP = 'st_stuck_in_ship',
    SUICIDAL = 'st_suicidal',
    THINKLINKED = 'st_thinklinked',
    UNSOCIABLE = 'st_unsociable',
    UPDATING = 'st_updating',
    COMMANDER = 'st_commander',
    COMMS_MANAGER = 'st_comms_manager',
    NERON_MANAGER = 'st_neron_manager',
}

export const EmoteStatusAliases: { [index: string]: string } = {
    ['demoralized']: EmoteStatusEnum.DEMORALIZED,
    ['hungry']: EmoteStatusEnum.STARVING,
    ['starving']: EmoteStatusEnum.STARVING,
    ['ill']: EmoteStatusEnum.DISEASE,
    ['psy_disease']: EmoteStatusEnum.DISORDER,
    ['hurt']: EmoteStatusEnum.INJURY,
    ['dirty']: EmoteStatusEnum.STINKY,
    ['gagged']: EmoteStatusEnum.GAGGED,
    ['hyperactive']: EmoteStatusEnum.HYPERACTIVE,
    ['broken']: EmoteStatusEnum.BROKEN,
    ['frozen']: EmoteStatusEnum.FOOD_FROZEN,
    ['unstable']: EmoteStatusEnum.FOOD_UNSTABLE,
    ['hazardous']: EmoteStatusEnum.FOOD_HAZARDOUS,
    ['decomposing']: EmoteStatusEnum.FOOD_DECAYING,
    ['updating']: EmoteStatusEnum.UPDATING,
    ['pacifist']: EmoteStatusEnum.PACIFIST,
    ['focused']: EmoteStatusEnum.MODULING,
    ['heavy']: EmoteStatusEnum.HEAVY,
    ['hidden']: EmoteStatusEnum.HIDDEN,
    ['antisocial']: EmoteStatusEnum.UNSOCIABLE,
    ['outcast']: EmoteStatusEnum.UNSOCIABLE,
    ['plant_young']: EmoteStatusEnum.PLANT_YOUNGLING,
    ['plant_thirsty']: EmoteStatusEnum.PLANT_THIRSTY,
    ['plant_dry']: EmoteStatusEnum.PLANT_DRY,
    ['plant_diseased']: EmoteStatusEnum.PLANT_DISEASED,
    ['electric_charges']: EmoteStatusEnum.CHARGE,
    ['contaminated']: EmoteStatusEnum.MUSH,
    ['cat_infected']: EmoteStatusEnum.MUSH,
    ['commander']: EmoteStatusEnum.COMMANDER,
    ['comm_manager']: EmoteStatusEnum.COMMS_MANAGER,
    ['comms_manager']: EmoteStatusEnum.COMMS_MANAGER,
    ['neron_manager']: EmoteStatusEnum.NERON_MANAGER
};

export const EmoteStatusIcons: { [index: string]: string } = {
    [EmoteStatusEnum.ARTEFACT]: getImgUrl('status/artefact.png'),
    [EmoteStatusEnum.BEGINNER]: getImgUrl('status/beginner.png'),
    [EmoteStatusEnum.BELLY_FULL]: getImgUrl('status/belly_full.png'),
    [EmoteStatusEnum.BERZERK]: getImgUrl('status/berzerk.png'),
    [EmoteStatusEnum.BROKEN]: getImgUrl('status/broken.png'),
    [EmoteStatusEnum.CHARGE]: getImgUrl('status/charge.png'),
    [EmoteStatusEnum.DEMORALIZED]: getImgUrl('status/demoralized.png'),
    [EmoteStatusEnum.DISABLED]: getImgUrl('status/disabled.png'),
    [EmoteStatusEnum.DISEASE]: getImgUrl('status/disease.png'),
    [EmoteStatusEnum.DISORDER]: getImgUrl('status/disorder.png'),
    [EmoteStatusEnum.FIRE]: getImgUrl('status/fire.png'),
    [EmoteStatusEnum.FIRST_TIME]: getImgUrl('status/first_time.png'),
    [EmoteStatusEnum.FOOD_DECAYING]: getImgUrl('status/food_decaying.png'),
    [EmoteStatusEnum.FOOD_FROZEN]: getImgUrl('status/food_frozen.png'),
    [EmoteStatusEnum.FOOD_HAZARDOUS]: getImgUrl('status/food_hazardous.png'),
    [EmoteStatusEnum.FOOD_UNSTABLE]: getImgUrl('status/food_unstable.png'),
    [EmoteStatusEnum.GAGGED]: getImgUrl('status/gagged.png'),
    [EmoteStatusEnum.GENIUS_IDEA]: getImgUrl('status/genius_idea.png'),
    [EmoteStatusEnum.GERMAPHOBIC]: getImgUrl('status/germaphobic.png'),
    [EmoteStatusEnum.GUARDIAN]: getImgUrl('status/guardian.png'),
    [EmoteStatusEnum.HAMMER]: getImgUrl('status/hammer.png'),
    [EmoteStatusEnum.HEAVY]: getImgUrl('status/heavy.png'),
    [EmoteStatusEnum.HIDDEN]: getImgUrl('status/hidden.png'),
    [EmoteStatusEnum.HIGHLY_INACTIVE]: getImgUrl('status/highly_inactive.png'),
    [EmoteStatusEnum.HYPERACTIVE]: getImgUrl('status/hyperactive.png'),
    [EmoteStatusEnum.IMMUNE]: getImgUrl('status/immune.png'),
    [EmoteStatusEnum.INJURY]: getImgUrl('status/injury.png'),
    [EmoteStatusEnum.IS_ANONYMOUS]: getImgUrl('status/is_anonymous.png'),
    [EmoteStatusEnum.LAID]: getImgUrl('status/laid.png'),
    [EmoteStatusEnum.LOST_ON_PLANET]: getImgUrl('status/lost_on_planet.png'),
    [EmoteStatusEnum.MODULING]: getImgUrl('status/moduling.png'),
    [EmoteStatusEnum.MULTI]: getImgUrl('status/multi.png'),
    [EmoteStatusEnum.MUSH]: getImgUrl('status/mush.png'),
    [EmoteStatusEnum.PACIFIST]: getImgUrl('status/pacifist.png'),
    [EmoteStatusEnum.PLANT_DISEASED]: getImgUrl('status/plant_diseased.png'),
    [EmoteStatusEnum.PLANT_DRY]: getImgUrl('status/plant_dry.png'),
    [EmoteStatusEnum.PLANT_THIRSTY]: getImgUrl('status/plant_thirsty.png'),
    [EmoteStatusEnum.PLANT_YOUNGLING]: getImgUrl('status/plant_youngling.png'),
    [EmoteStatusEnum.PREGNANT]: getImgUrl('status/pregnant.png'),
    [EmoteStatusEnum.SLEEPY]: getImgUrl('status/sleepy.png'),
    [EmoteStatusEnum.SPORE]: getImgUrl('status/spore.png'),
    [EmoteStatusEnum.STARVING]: getImgUrl('status/starving.png'),
    [EmoteStatusEnum.STINKY]: getImgUrl('status/stinky.png'),
    [EmoteStatusEnum.STUCK_IN_SHIP]: getImgUrl('status/stuck_in_ship.png'),
    [EmoteStatusEnum.SUICIDAL]: getImgUrl('status/suicidal.png'),
    [EmoteStatusEnum.THINKLINKED]: getImgUrl('status/thinklinked.png'),
    [EmoteStatusEnum.UNSOCIABLE]: getImgUrl('status/unsociable.png'),
    [EmoteStatusEnum.UPDATING]: getImgUrl('status/update.png'),
    [EmoteStatusEnum.COMMANDER]: getImgUrl('title_commander.png'),
    [EmoteStatusEnum.COMMS_MANAGER]: getImgUrl('title_com_manager.png'),
    [EmoteStatusEnum.NERON_MANAGER]: getImgUrl('title_neron_manager.png')
};
