import { getImgUrl } from "@/utils/getImgUrl";
import { EmoteCharacterEnum } from "@/enums/emotes/characters.enum";

export enum EmoteTwinoidEnum {
    ANGRY = "twinoid_angry",
    ARROW = "twinoid_arrow",
    CALIM = "twinoid_calim",
    CALMOS = "twinoid_calmos",
    CHART = "twinoid_chart",
    CONFUSED = "twinoid_confused",
    COOL = "twinoid_cool",
    CROSS = "twinoid_cross",
    CRY = "twinoid_cry",
    CRYLOT = "twinoid_crylot",
    CUTE = "twinoid_cute",
    DONTCARE = "twinoid_dontcare",
    DROWL = "twinoid_drowl",
    EEK = "twinoid_eek",
    EVIL = "twinoid_evil",
    EXCLAIM = "twinoid_exclaim",
    FACEPALM = "twinoid_facepalm",
    FEAR = "twinoid_fear",
    GETOUT = "twinoid_getout",
    HAPPY = "twinoid_happy",
    HAPPY2 = "twinoid_happy2",
    HMM = "twinoid_hmm",
    HUH = "twinoid_huh",
    IDEA = "twinoid_idea",
    KEEPCOOL = "twinoid_keepcool",
    LOL = "twinoid_lol",
    LOOKUP = "twinoid_lookup",
    MAD = "twinoid_mad",
    NOOO = "twinoid_nooo",
    OMG = "twinoid_omg",
    OUPS = "twinoid_oups",
    PSYCHO = "twinoid_psycho",
    PUKE = "twinoid_puke",
    QUESTION = "twinoid_question",
    RAZZ = "twinoid_razz",
    REDFACE = "twinoid_redface",
    SAD = "twinoid_sad",
    SADIST = "twinoid_sadist",
    SIFFLOTE = "twinoid_sifflote",
    SMILE = "twinoid_smile",
    STOP = "twinoid_stop",
    SURPRISE = "twinoid_surprise",
    SURPRISED = "twinoid_surprised",
    TUSORS = "twinoid_tusors",
    TWINOID = "twinoid_twinoid",
    WINK = "twinoid_wink",
    WINK2 = "twinoid_wink2",
    YEAH = "twinoid_yeah",
    ZOMBIE = "twinoid_zombie",
}

export const EmoteTwinoidAliases: { [index: string]: string } = { };

export const EmoteTwinoidIcons: {[index: string]: {img: string; max_height: string;}}= {
    [EmoteTwinoidEnum.ANGRY]: { img: getImgUrl("emotes/twinoid/angry.gif"), max_height: "1.2em" },
    [EmoteTwinoidEnum.ARROW]: { img: getImgUrl("emotes/twinoid/arrow.png"), max_height: "1.2em" },
    [EmoteTwinoidEnum.CALIM]: { img: getImgUrl("emotes/twinoid/calim.png"), max_height: "1.2em" },
    [EmoteTwinoidEnum.CALMOS]: { img: getImgUrl("emotes/twinoid/calmos.gif"), max_height: "1.2em" },
    [EmoteTwinoidEnum.CHART]: { img: getImgUrl("emotes/twinoid/chart.png"), max_height: "1.2em" },
    [EmoteTwinoidEnum.CONFUSED]: { img: getImgUrl("emotes/twinoid/confused.png"), max_height: "1.2em" },
    [EmoteTwinoidEnum.COOL]: { img: getImgUrl("emotes/twinoid/cool.png"), max_height: "1.2em" },
    [EmoteTwinoidEnum.CROSS]: { img: getImgUrl("emotes/twinoid/cross.png"), max_height: "1.2em" },
    [EmoteTwinoidEnum.CRY]: { img: getImgUrl("emotes/twinoid/cry.png"), max_height: "1.2em" },
    [EmoteTwinoidEnum.CRYLOT]: { img: getImgUrl("emotes/twinoid/crylot.png"), max_height: "1.2em" },
    [EmoteTwinoidEnum.CUTE]: { img: getImgUrl("emotes/twinoid/cute.png"), max_height: "1.2em" },
    [EmoteTwinoidEnum.DONTCARE]: { img: getImgUrl("emotes/twinoid/dontcare.png"), max_height: "1.2em" },
    [EmoteTwinoidEnum.DROWL]: { img: getImgUrl("emotes/twinoid/drowl.png"), max_height: "1.2em" },
    [EmoteTwinoidEnum.EEK]: { img: getImgUrl("emotes/twinoid/eek.png"), max_height: "1.2em" },
    [EmoteTwinoidEnum.EVIL]: { img: getImgUrl("emotes/twinoid/evil.png"), max_height: "1.2em" },
    [EmoteTwinoidEnum.EXCLAIM]: { img: getImgUrl("emotes/twinoid/exclaim.png"), max_height: "1.2em" },
    [EmoteTwinoidEnum.FACEPALM]: { img: getImgUrl("emotes/twinoid/facepalm.png"), max_height: "1.2em" },
    [EmoteTwinoidEnum.FEAR]: { img: getImgUrl("emotes/twinoid/fear.png"), max_height: "1.2em" },
    [EmoteTwinoidEnum.GETOUT]: { img: getImgUrl("emotes/twinoid/getout.png"), max_height: "1.2em" },
    [EmoteTwinoidEnum.HAPPY]: { img: getImgUrl("emotes/twinoid/happy.png"), max_height: "1.2em" },
    [EmoteTwinoidEnum.HAPPY2]: { img: getImgUrl("emotes/twinoid/happy2.png"), max_height: "1.2em" },
    [EmoteTwinoidEnum.HMM]: { img: getImgUrl("emotes/twinoid/hmm.png"), max_height: "1.2em" },
    [EmoteTwinoidEnum.HUH]: { img: getImgUrl("emotes/twinoid/huh.png"), max_height: "1.2em" },
    [EmoteTwinoidEnum.IDEA]: { img: getImgUrl("emotes/twinoid/idea.png"), max_height: "1.2em" },
    [EmoteTwinoidEnum.KEEPCOOL]: { img: getImgUrl("emotes/twinoid/keepcool.png"), max_height: "1.2em" },
    [EmoteTwinoidEnum.LOL]: { img: getImgUrl("emotes/twinoid/lol.png"), max_height: "1.2em" },
    [EmoteTwinoidEnum.LOOKUP]: { img: getImgUrl("emotes/twinoid/lookup.png"), max_height: "1.2em" },
    [EmoteTwinoidEnum.MAD]: { img: getImgUrl("emotes/twinoid/mad.png"), max_height: "1.2em" },
    [EmoteTwinoidEnum.NOOO]: { img: getImgUrl("emotes/twinoid/nooo.png"), max_height: "1.2em" },
    [EmoteTwinoidEnum.OMG]: { img: getImgUrl("emotes/twinoid/omg.png"), max_height: "1.2em" },
    [EmoteTwinoidEnum.OUPS]: { img: getImgUrl("emotes/twinoid/oups.gif"), max_height: "1.2em" },
    [EmoteTwinoidEnum.PSYCHO]: { img: getImgUrl("emotes/twinoid/psycho.png"), max_height: "1.2em" },
    [EmoteTwinoidEnum.PUKE]: { img: getImgUrl("emotes/twinoid/puke.png"), max_height: "1.2em" },
    [EmoteTwinoidEnum.QUESTION]: { img: getImgUrl("emotes/twinoid/question.png"), max_height: "1.2em" },
    [EmoteTwinoidEnum.RAZZ]: { img: getImgUrl("emotes/twinoid/razz.png"), max_height: "1.2em" },
    [EmoteTwinoidEnum.REDFACE]: { img: getImgUrl("emotes/twinoid/redface.png"), max_height: "1.2em" },
    [EmoteTwinoidEnum.SAD]: { img: getImgUrl("emotes/twinoid/sad.png"), max_height: "1.2em" },
    [EmoteTwinoidEnum.SADIST]: { img: getImgUrl("emotes/twinoid/sadist.png"), max_height: "1.2em" },
    [EmoteTwinoidEnum.SIFFLOTE]: { img: getImgUrl("emotes/twinoid/sifflote.gif"), max_height: "1.2em" },
    [EmoteTwinoidEnum.SMILE]: { img: getImgUrl("emotes/twinoid/smile.png"), max_height: "1.2em" },
    [EmoteTwinoidEnum.STOP]: { img: getImgUrl("emotes/twinoid/stop.png"), max_height: "1.2em" },
    [EmoteTwinoidEnum.SURPRISE]: { img: getImgUrl("emotes/twinoid/surprise.gif"), max_height: "1.2em" },
    [EmoteTwinoidEnum.SURPRISED]: { img: getImgUrl("emotes/twinoid/surprised.png"), max_height: "1.2em" },
    [EmoteTwinoidEnum.TUSORS]: { img: getImgUrl("emotes/twinoid/tusors.gif"), max_height: "1.2em" },
    [EmoteTwinoidEnum.TWINOID]: { img: getImgUrl("emotes/twinoid/twinoid.png"), max_height: "1.2em" },
    [EmoteTwinoidEnum.WINK]: { img: getImgUrl("emotes/twinoid/wink.png"), max_height: "1.2em" },
    [EmoteTwinoidEnum.WINK2]: { img: getImgUrl("emotes/twinoid/wink2.png"), max_height: "1.2em" },
    [EmoteTwinoidEnum.YEAH]: { img: getImgUrl("emotes/twinoid/yeah.png"), max_height: "1.2em" },
    [EmoteTwinoidEnum.ZOMBIE]: { img: getImgUrl("emotes/twinoid/zombie.png"), max_height: "1.2em" }
};
