
services:

  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

  # makes classes in src/ available to be used as services
  # this creates a service per class whose id is the fully-qualified class name
  Mush\Chat\:
    resource: '../'
    exclude:
      - '../DependencyInjection/'
      - '../Entity/'
      - '../Kernel.php'
      - '../Tests/'

  # controllers are imported separately to make sure services can be injected
  # as action arguments even if you don't extend any base controller class
  Mush\Chat\Controller\:
    resource: '../Controller/'
    tags: ['controller.service_arguments']

  Mush\Chat\ParamConverter\MessageCreateParamConverter:
    tags:
      - { name: 'request.param_converter', converter: MessageCreateParamConverter }

  Mush\Chat\Repository\ChannelPlayerRepositoryInterface: '@Mush\Chat\Repository\ChannelPlayerRepository'
  Mush\Chat\Repository\ChannelRepositoryInterface: '@Mush\Chat\Repository\ChannelRepository'
  Mush\Chat\Repository\MessageRepositoryInterface: '@Mush\Chat\Repository\MessageRepository'
  Mush\Chat\Gateway\NeronAnswerGatewayInterface: '@Mush\Chat\Gateway\NeronAnswerGateway'
  Mush\Chat\Gateway\NeronAnswerGateway:
    arguments:
      $askNeronEndpoint: '%env(ASK_NERON_ENDPOINT)%'

