base_path: /
preserve_hierarchy: true
base_url: 'https://api.crowdin.com'
files:
  - source: /Api/translations/fr/*+intl-icu.fr.xlf
    translation: /Api/translations/%two_letters_code%/%original_file_name%
