base_path: /
preserve_hierarchy: 1
base_url: 'https://eternaltwin.crowdin.com'
files:
  - source: /Api/translations/fr/*.fr.xlf
    translation: /Api/translations/%two_letters_code%/%original_file_name%
  - source: /App/src/i18n/locales/fr.json
    translation: /App/src/i18n/locales/%two_letters_code%.json
