doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '5.7'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            Daedalus:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Daedalus/Entity'
                prefix: 'Mush\Daedalus\Entity'
                alias: Daedalus
            Player:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Player/Entity'
                prefix: 'Mush\Player\Entity'
                alias: Player
            Item:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Item/Entity'
                prefix: 'Mush\Item\Entity'
                alias: Item
            User:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/User/Entity'
                prefix: 'Mush\User\Entity'
                alias: User
            Room:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Room/Entity'
                prefix: 'Mush\Room\Entity'
                alias: Room
            RoomLog:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/RoomLog/Entity'
                prefix: 'Mush\RoomLog\Entity'
                alias: RoomLog
