# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
fos_rest:
  format_listener:
    rules:
      - { path: '^/api/v1', prefer_extension: true, fallback_format: "json", priorities: [ json ]}
      - { path: '^/', prefer_extension: true, fallback_format: "html", priorities: [ 'html', '*/*' ] }
  body_listener:
    array_normalizer: fos_rest.normalizer.camel_keys
  body_converter:
    enabled: true
    validate: true
    validation_errors_argument: violations

  view:
    view_response_listener: true
    formats:
      rss: false
      xml: false
      json: true