framework:
    validation:
        email_validation_mode: html5
        mapping:
            paths:
                - '%kernel.project_dir%/config/api_platform/validation/gameConfig.yaml' # yaml or xml directory configuration
