<?php

namespace Mush\Equipment\ConfigData;

use Mush\Action\Enum\ActionEnum;
use Mush\Equipment\Enum\EquipmentEnum;
use Mush\Equipment\Enum\EquipmentMechanicEnum;
use Mush\Equipment\Enum\ItemEnum;
use Mush\Place\Enum\RoomEnum;
use Mush\Skill\Enum\SkillEnum;

/** @codeCoverageIgnore */
abstract class MechanicsData
{
    public const string TOOL_COMMS_CENTER = 'tool_comms_center_default';

    public static array $dataArray = [
        [
            'name' => 'document_default',
            'type' => 'document',
            'content' => '',
            'isTranslated' => true,
            'canShred' => true,
            'actions' => [
                'read_document',
                'shred',
            ],
            'modifierConfigs' => [],
        ],
        [
            'name' => 'commanders_manual_default',
            'type' => 'document',
            'content' => 'commanders_manual',
            'isTranslated' => true,
            'canShred' => false,
            'actions' => [
                'read_document',
            ],
            'modifierConfigs' => [],
        ],
        [
            'name' => 'mush_research_review_default',
            'type' => 'document',
            'content' => 'mush_research_review',
            'isTranslated' => true,
            'canShred' => false,
            'actions' => [
                'read_document',
            ],
            'modifierConfigs' => [],
        ],
        [
            'name' => 'post_it_default',
            'type' => 'document',
            'content' => '',
            'isTranslated' => false,
            'canShred' => true,
            'actions' => [
                'read_document',
                'shred',
            ],
            'modifierConfigs' => [],
        ],
        [
            'name' => 'apprentron_astrophysicist_default',
            'type' => 'book',
            'skill' => SkillEnum::ASTROPHYSICIST,
            'actions' => [
                'read_book',
            ],
            'modifierConfigs' => [],
        ],
        [
            'name' => 'apprentron_biologist_default',
            'type' => 'book',
            'skill' => SkillEnum::BIOLOGIST,
            'actions' => [
                'read_book',
            ],
            'modifierConfigs' => [],
        ],
        [
            'name' => 'apprentron_botanist_default',
            'type' => 'book',
            'skill' => SkillEnum::BOTANIST,
            'actions' => [
                'read_book',
            ],
            'modifierConfigs' => [],
        ],
        [
            'name' => 'apprentron_diplomat_default',
            'type' => 'book',
            'skill' => SkillEnum::DIPLOMAT,
            'actions' => [
                'read_book',
            ],
            'modifierConfigs' => [],
        ],
        [
            'name' => 'apprentron_firefighter_default',
            'type' => 'book',
            'skill' => SkillEnum::FIREFIGHTER,
            'actions' => [
                'read_book',
            ],
            'modifierConfigs' => [],
        ],
        [
            'name' => 'apprentron_chef_default',
            'type' => 'book',
            'skill' => SkillEnum::CHEF,
            'actions' => [
                'read_book',
            ],
            'modifierConfigs' => [],
        ],
        [
            'name' => 'apprentron_it_expert_default',
            'type' => 'book',
            'skill' => SkillEnum::IT_EXPERT,
            'actions' => [
                'read_book',
            ],
            'modifierConfigs' => [],
        ],
        [
            'name' => 'apprentron_logistics_expert_default',
            'type' => 'book',
            'skill' => SkillEnum::IT_EXPERT,
            'actions' => [
                'read_book',
            ],
            'modifierConfigs' => [],
        ],
        [
            'name' => 'apprentron_medic_default',
            'type' => 'book',
            'skill' => SkillEnum::MEDIC,
            'actions' => [
                'read_book',
            ],
            'modifierConfigs' => [],
        ],
        [
            'name' => 'apprentron_pilot_default',
            'type' => 'book',
            'skill' => SkillEnum::PILOT,
            'actions' => [
                'read_book',
            ],
            'modifierConfigs' => [],
        ],
        [
            'name' => 'apprentron_radio_expert_default',
            'type' => 'book',
            'skill' => SkillEnum::RADIO_EXPERT,
            'actions' => [
                'read_book',
            ],
            'modifierConfigs' => [],
        ],
        [
            'name' => 'apprentron_robotics_expert_default',
            'type' => 'book',
            'skill' => SkillEnum::ROBOTICS_EXPERT,
            'actions' => [
                'read_book',
            ],
            'modifierConfigs' => [],
        ],
        [
            'name' => 'apprentron_shooter_default',
            'type' => 'book',
            'skill' => SkillEnum::SHOOTER,
            'actions' => [
                'read_book',
            ],
            'modifierConfigs' => [],
        ],
        [
            'name' => 'apprentron_shrink_default',
            'type' => 'book',
            'skill' => SkillEnum::SHRINK,
            'actions' => [
                'read_book',
            ],
            'modifierConfigs' => [],
        ],
        [
            'name' => 'apprentron_sprinter_default',
            'type' => 'book',
            'skill' => SkillEnum::SPRINTER,
            'actions' => [
                'read_book',
            ],
            'modifierConfigs' => [],
        ],
        [
            'name' => 'apprentron_technician_default',
            'type' => 'book',
            'skill' => SkillEnum::TECHNICIAN,
            'actions' => [
                'read_book',
            ],
            'modifierConfigs' => [],
        ],
        [
            'name' => 'drug_default',
            'type' => 'drug',
            'moralPoints' => [0 => 1, -2 => 1, 1 => 1, 3 => 1],
            'actionPoints' => [0 => 3, 1 => 1, 3 => 1],
            'movementPoints' => [0 => 3, 2 => 1, 4 => 1],
            'healthPoints' => [0 => 1],
            'satiety' => null,
            'extraEffects' => [],
            'isPerishable' => false,
            'actions' => [
                'consume_drug',
                ActionEnum::MIX_RATION_SPORE->value,
            ],
            'modifierConfigs' => [],
        ],
        [
            'name' => 'plant_banana_tree_default',
            'type' => 'plant',
            'fruitName' => 'banana',
            'maturationTime' => [36 => 1],
            'oxygen' => [1 => 1],
            'actions' => [
                'treat_plant',
                'water_plant',
            ],
            'modifierConfigs' => [],
        ],
        [
            'name' => 'plant_creepist_default',
            'type' => 'plant',
            'fruitName' => 'creepnut',
            'maturationTime' => [2 => 7, 4 => 7, 8 => 24, 12 => 14, 16 => 7, 24 => 7, 48 => 7],
            'oxygen' => [1 => 1],
            'actions' => [
                'treat_plant',
                'water_plant',
            ],
            'modifierConfigs' => [],
        ],
        [
            'name' => 'plant_cactax_default',
            'type' => 'plant',
            'fruitName' => 'meztine',
            'maturationTime' => [2 => 7, 4 => 7, 8 => 24, 12 => 14, 16 => 7, 24 => 7, 48 => 7],
            'oxygen' => [1 => 1],
            'actions' => [
                'treat_plant',
                'water_plant',
            ],
            'modifierConfigs' => [],
        ],
        [
            'name' => 'plant_bifflon_default',
            'type' => 'plant',
            'fruitName' => 'guntiflop',
            'maturationTime' => [2 => 7, 4 => 7, 8 => 24, 12 => 14, 16 => 7, 24 => 7, 48 => 7],
            'oxygen' => [1 => 1],
            'actions' => [
                'treat_plant',
                'water_plant',
            ],
            'modifierConfigs' => [],
        ],
        [
            'name' => 'plant_pulminagro_default',
            'type' => 'plant',
            'fruitName' => 'ploshmina',
            'maturationTime' => [2 => 7, 4 => 7, 8 => 24, 12 => 14, 16 => 7, 24 => 7, 48 => 7],
            'oxygen' => [1 => 1],
            'actions' => [
                'treat_plant',
                'water_plant',
            ],
            'modifierConfigs' => [],
        ],
        [
            'name' => 'plant_precatus_default',
            'type' => 'plant',
            'fruitName' => 'precati',
            'maturationTime' => [2 => 7, 4 => 7, 8 => 24, 12 => 14, 16 => 7, 24 => 7, 48 => 7],
            'oxygen' => [1 => 1],
            'actions' => [
                'treat_plant',
                'water_plant',
            ],
            'modifierConfigs' => [],
        ],
        [
            'name' => 'plant_buttalien_default',
            'type' => 'plant',
            'fruitName' => 'bottine',
            'maturationTime' => [2 => 7, 4 => 7, 8 => 24, 12 => 14, 16 => 7, 24 => 7, 48 => 7],
            'oxygen' => [1 => 1],
            'actions' => [
                'treat_plant',
                'water_plant',
            ],
            'modifierConfigs' => [],
        ],
        [
            'name' => 'plant_platacia_default',
            'type' => 'plant',
            'fruitName' => 'fragilane',
            'maturationTime' => [2 => 7, 4 => 7, 8 => 24, 12 => 14, 16 => 7, 24 => 7, 48 => 7],
            'oxygen' => [1 => 1],
            'actions' => [
                'treat_plant',
                'water_plant',
            ],
            'modifierConfigs' => [],
        ],
        [
            'name' => 'plant_tubiliscus_default',
            'type' => 'plant',
            'fruitName' => 'anemole',
            'maturationTime' => [2 => 7, 4 => 7, 8 => 24, 12 => 14, 16 => 7, 24 => 7, 48 => 7],
            'oxygen' => [1 => 1],
            'actions' => [
                'treat_plant',
                'water_plant',
            ],
            'modifierConfigs' => [],
        ],
        [
            'name' => 'plant_graapshoot_default',
            'type' => 'plant',
            'fruitName' => 'peniraft',
            'maturationTime' => [2 => 7, 4 => 7, 8 => 24, 12 => 14, 16 => 7, 24 => 7, 48 => 7],
            'oxygen' => [1 => 1],
            'actions' => [
                'treat_plant',
                'water_plant',
            ],
            'modifierConfigs' => [],
        ],
        [
            'name' => 'plant_fiboniccus_default',
            'type' => 'plant',
            'fruitName' => 'kubinus',
            'maturationTime' => [2 => 7, 4 => 7, 8 => 24, 12 => 14, 16 => 7, 24 => 7, 48 => 7],
            'oxygen' => [1 => 1],
            'actions' => [
                'treat_plant',
                'water_plant',
            ],
            'modifierConfigs' => [],
        ],
        [
            'name' => 'plant_mycopia_default',
            'type' => 'plant',
            'fruitName' => 'caleboot',
            'maturationTime' => [2 => 7, 4 => 7, 8 => 24, 12 => 14, 16 => 7, 24 => 7, 48 => 7],
            'oxygen' => [1 => 1],
            'actions' => [
                'treat_plant',
                'water_plant',
            ],
            'modifierConfigs' => [],
        ],
        [
            'name' => 'plant_asperagunk_default',
            'type' => 'plant',
            'fruitName' => 'filandra',
            'maturationTime' => [2 => 7, 4 => 7, 8 => 24, 12 => 14, 16 => 7, 24 => 7, 48 => 7],
            'oxygen' => [1 => 1],
            'actions' => [
                'treat_plant',
                'water_plant',
            ],
            'modifierConfigs' => [],
        ],
        [
            'name' => 'plant_bumpjumpkin_default',
            'type' => 'plant',
            'fruitName' => 'jumpkin',
            'maturationTime' => [8 => 1],
            'oxygen' => [1 => 1],
            'actions' => [
                'treat_plant',
                'water_plant',
            ],
            'modifierConfigs' => [],
        ],
        [
            'name' => 'fruit_banana_default',
            'type' => 'fruit',
            'plantName' => 'banana_tree',
            'moralPoints' => [1 => 1],
            'actionPoints' => [1 => 1],
            'movementPoints' => [0 => 1],
            'healthPoints' => [1 => 1],
            'satiety' => 1.0,
            'extraEffects' => [],
            'isPerishable' => true,
            'actions' => [
                'consume',
                ActionEnum::MIX_RATION_SPORE->value,
                'transplant',
                ActionEnum::GRAFT->value,
            ],
            'modifierConfigs' => [],
        ],
        [
            'name' => 'fruit_creepnut_default',
            'type' => 'fruit',
            'plantName' => 'creepist',
            'moralPoints' => [0 => 30, 1 => 70],
            'actionPoints' => [1 => 90, 2 => 9, 3 => 1],
            'movementPoints' => [0 => 1],
            'healthPoints' => [0 => 1],
            'satiety' => 1.0,
            'extraEffects' => ['extra_pa_gain' => 50],
            'isPerishable' => true,
            'actions' => [
                'consume',
                ActionEnum::MIX_RATION_SPORE->value,
                'transplant',
                ActionEnum::GRAFT->value,
            ],
            'modifierConfigs' => [],
        ],
        [
            'name' => 'fruit_meztine_default',
            'type' => 'fruit',
            'plantName' => 'cactax',
            'moralPoints' => [0 => 30, 1 => 70],
            'actionPoints' => [1 => 90, 2 => 9, 3 => 1],
            'movementPoints' => [0 => 1],
            'healthPoints' => [0 => 1],
            'satiety' => 1.0,
            'extraEffects' => ['extra_pa_gain' => 50],
            'isPerishable' => true,
            'actions' => [
                'consume',
                ActionEnum::MIX_RATION_SPORE->value,
                'transplant',
                ActionEnum::GRAFT->value,
            ],
            'modifierConfigs' => [],
        ],
        [
            'name' => 'fruit_guntiflop_default',
            'type' => 'fruit',
            'plantName' => 'bifflon',
            'moralPoints' => [0 => 30, 1 => 70],
            'actionPoints' => [1 => 90, 2 => 9, 3 => 1],
            'movementPoints' => [0 => 1],
            'healthPoints' => [0 => 1],
            'satiety' => 1.0,
            'extraEffects' => ['extra_pa_gain' => 50],
            'isPerishable' => true,
            'actions' => [
                'consume',
                ActionEnum::MIX_RATION_SPORE->value,
                'transplant',
                ActionEnum::GRAFT->value,
            ],
            'modifierConfigs' => [],
        ],
        [
            'name' => 'fruit_ploshmina_default',
            'type' => 'fruit',
            'plantName' => 'pulminagro',
            'moralPoints' => [0 => 30, 1 => 70],
            'actionPoints' => [1 => 90, 2 => 9, 3 => 1],
            'movementPoints' => [0 => 1],
            'healthPoints' => [0 => 1],
            'satiety' => 1.0,
            'extraEffects' => ['extra_pa_gain' => 50],
            'isPerishable' => true,
            'actions' => [
                'consume',
                ActionEnum::MIX_RATION_SPORE->value,
                'transplant',
                ActionEnum::GRAFT->value,
            ],
            'modifierConfigs' => [],
        ],
        [
            'name' => 'fruit_precati_default',
            'type' => 'fruit',
            'plantName' => 'precatus',
            'moralPoints' => [0 => 30, 1 => 70],
            'actionPoints' => [1 => 90, 2 => 9, 3 => 1],
            'movementPoints' => [0 => 1],
            'healthPoints' => [0 => 1],
            'satiety' => 1.0,
            'extraEffects' => ['extra_pa_gain' => 50],
            'isPerishable' => true,
            'actions' => [
                'consume',
                ActionEnum::MIX_RATION_SPORE->value,
                'transplant',
                ActionEnum::GRAFT->value,
            ],
            'modifierConfigs' => [],
        ],
        [
            'name' => 'fruit_bottine_default',
            'type' => 'fruit',
            'plantName' => 'buttalien',
            'moralPoints' => [0 => 30, 1 => 70],
            'actionPoints' => [1 => 90, 2 => 9, 3 => 1],
            'movementPoints' => [0 => 1],
            'healthPoints' => [0 => 1],
            'satiety' => 1.0,
            'extraEffects' => ['extra_pa_gain' => 50],
            'isPerishable' => true,
            'actions' => [
                'consume',
                ActionEnum::MIX_RATION_SPORE->value,
                'transplant',
                ActionEnum::GRAFT->value,
            ],
            'modifierConfigs' => [],
        ],
        [
            'name' => 'fruit_fragilane_default',
            'type' => 'fruit',
            'plantName' => 'platacia',
            'moralPoints' => [0 => 30, 1 => 70],
            'actionPoints' => [1 => 90, 2 => 9, 3 => 1],
            'movementPoints' => [0 => 1],
            'healthPoints' => [0 => 1],
            'satiety' => 1.0,
            'extraEffects' => ['extra_pa_gain' => 50],
            'isPerishable' => true,
            'actions' => [
                'consume',
                ActionEnum::MIX_RATION_SPORE->value,
                'transplant',
                ActionEnum::GRAFT->value,
            ],
            'modifierConfigs' => [],
        ],
        [
            'name' => 'fruit_anemole_default',
            'type' => 'fruit',
            'plantName' => 'tubiliscus',
            'moralPoints' => [0 => 30, 1 => 70],
            'actionPoints' => [1 => 90, 2 => 9, 3 => 1],
            'movementPoints' => [0 => 1],
            'healthPoints' => [0 => 1],
            'satiety' => 1.0,
            'extraEffects' => ['extra_pa_gain' => 50],
            'isPerishable' => true,
            'actions' => [
                'consume',
                ActionEnum::MIX_RATION_SPORE->value,
                'transplant',
                ActionEnum::GRAFT->value,
            ],
            'modifierConfigs' => [],
        ],
        [
            'name' => 'fruit_peniraft_default',
            'type' => 'fruit',
            'plantName' => 'graapshoot',
            'moralPoints' => [0 => 30, 1 => 70],
            'actionPoints' => [1 => 90, 2 => 9, 3 => 1],
            'movementPoints' => [0 => 1],
            'healthPoints' => [0 => 1],
            'satiety' => 1.0,
            'extraEffects' => ['extra_pa_gain' => 50],
            'isPerishable' => true,
            'actions' => [
                'consume',
                ActionEnum::MIX_RATION_SPORE->value,
                'transplant',
                ActionEnum::GRAFT->value,
            ],
            'modifierConfigs' => [],
        ],
        [
            'name' => 'fruit_kubinus_default',
            'type' => 'fruit',
            'plantName' => 'fiboniccus',
            'moralPoints' => [0 => 30, 1 => 70],
            'actionPoints' => [1 => 90, 2 => 9, 3 => 1],
            'movementPoints' => [0 => 1],
            'healthPoints' => [0 => 1],
            'satiety' => 1.0,
            'extraEffects' => ['extra_pa_gain' => 50],
            'isPerishable' => true,
            'actions' => [
                'consume',
                ActionEnum::MIX_RATION_SPORE->value,
                'transplant',
                ActionEnum::GRAFT->value,
            ],
            'modifierConfigs' => [],
        ],
        [
            'name' => 'fruit_caleboot_default',
            'type' => 'fruit',
            'plantName' => 'mycopia',
            'moralPoints' => [0 => 30, 1 => 70],
            'actionPoints' => [1 => 90, 2 => 9, 3 => 1],
            'movementPoints' => [0 => 1],
            'healthPoints' => [0 => 1],
            'satiety' => 1.0,
            'extraEffects' => ['extra_pa_gain' => 50],
            'isPerishable' => true,
            'actions' => [
                'consume',
                ActionEnum::MIX_RATION_SPORE->value,
                'transplant',
                ActionEnum::GRAFT->value,
            ],
            'modifierConfigs' => [],
        ],
        [
            'name' => 'fruit_filandra_default',
            'type' => 'fruit',
            'plantName' => 'asperagunk',
            'moralPoints' => [0 => 30, 1 => 70],
            'actionPoints' => [1 => 90, 2 => 9, 3 => 1],
            'movementPoints' => [0 => 1],
            'healthPoints' => [0 => 1],
            'satiety' => 1.0,
            'extraEffects' => ['extra_pa_gain' => 50],
            'isPerishable' => true,
            'actions' => [
                'consume',
                ActionEnum::MIX_RATION_SPORE->value,
                'transplant',
                ActionEnum::GRAFT->value,
            ],
            'modifierConfigs' => [],
        ],
        [
            'name' => 'fruit_jumpkin_default',
            'type' => 'fruit',
            'plantName' => 'bumpjumpkin',
            'moralPoints' => [1 => 1],
            'actionPoints' => [3 => 1],
            'movementPoints' => [0 => 0],
            'healthPoints' => [1 => 1],
            'satiety' => 0.0,
            'extraEffects' => [],
            'isPerishable' => true,
            'actions' => [
                'consume',
                ActionEnum::MIX_RATION_SPORE->value,
                'transplant',
                ActionEnum::GRAFT->value,
            ],
            'modifierConfigs' => [],
        ],
        [
            'name' => 'ration_standard_ration_default',
            'type' => 'ration',
            'moralPoints' => [-1 => 1],
            'actionPoints' => [4 => 1],
            'movementPoints' => [0 => 1],
            'healthPoints' => [0 => 1],
            'satiety' => 4.0,
            'extraEffects' => [],
            'isPerishable' => false,
            'actions' => [
                'consume',
                ActionEnum::MIX_RATION_SPORE->value,
            ],
            'modifierConfigs' => [],
        ],
        [
            'name' => 'ration_cooked_ration_default',
            'type' => 'ration',
            'moralPoints' => [0 => 1],
            'actionPoints' => [4 => 1],
            'movementPoints' => [0 => 1],
            'healthPoints' => [0 => 1],
            'satiety' => 4.0,
            'extraEffects' => [],
            'isPerishable' => true,
            'actions' => [
                'consume',
                ActionEnum::MIX_RATION_SPORE->value,
            ],
            'modifierConfigs' => [],
        ],
        [
            'name' => 'ration_alien_steak_default',
            'type' => 'ration',
            'moralPoints' => [-1 => 1],
            'actionPoints' => [4 => 1],
            'movementPoints' => [0 => 1],
            'healthPoints' => [0 => 1],
            'satiety' => 4.0,
            'extraEffects' => [],
            'isPerishable' => true,
            'actions' => [
                'consume',
                ActionEnum::MIX_RATION_SPORE->value,
            ],
            'modifierConfigs' => [],
        ],
        [
            'name' => 'ration_coffee_default',
            'type' => 'ration',
            'moralPoints' => [0 => 1],
            'actionPoints' => [2 => 1],
            'movementPoints' => [0 => 1],
            'healthPoints' => [0 => 1],
            'satiety' => 0.0,
            'extraEffects' => [],
            'isPerishable' => true,
            'actions' => [
                'consume',
                ActionEnum::MIX_RATION_SPORE->value,
            ],
            'modifierConfigs' => [],
        ],
        [
            'name' => 'ration_anabolic_default',
            'type' => 'ration',
            'moralPoints' => [0 => 1],
            'actionPoints' => [0 => 1],
            'movementPoints' => [8 => 1],
            'healthPoints' => [0 => 1],
            'satiety' => 0.0,
            'extraEffects' => [],
            'isPerishable' => false,
            'actions' => [
                'consume',
                ActionEnum::MIX_RATION_SPORE->value,
            ],
            'modifierConfigs' => [],
        ],
        [
            'name' => 'ration_lombrick_bar_default',
            'type' => 'ration',
            'moralPoints' => [2 => 1],
            'actionPoints' => [8 => 1],
            'movementPoints' => [0 => 1],
            'healthPoints' => [0 => 1],
            'satiety' => 8.0,
            'extraEffects' => [],
            'isPerishable' => false,
            'actions' => [
                'consume',
                ActionEnum::MIX_RATION_SPORE->value,
            ],
            'modifierConfigs' => [],
        ],
        [
            'name' => 'ration_organic_waste_default',
            'type' => 'ration',
            'moralPoints' => [-4 => 1],
            'actionPoints' => [6 => 1],
            'movementPoints' => [0 => 1],
            'healthPoints' => [0 => 1],
            'satiety' => 16.0,
            'extraEffects' => [],
            'isPerishable' => false,
            'actions' => [
                'consume',
                ActionEnum::MIX_RATION_SPORE->value,
            ],
            'modifierConfigs' => [],
        ],
        [
            'name' => 'ration_proactive_puffed_rice_default',
            'type' => 'ration',
            'moralPoints' => [0 => 1],
            'actionPoints' => [10 => 1],
            'movementPoints' => [0 => 1],
            'healthPoints' => [0 => 1],
            'satiety' => 5.0,
            'extraEffects' => ['break_door' => 55],
            'isPerishable' => false,
            'actions' => [
                'consume',
                ActionEnum::MIX_RATION_SPORE->value,
            ],
            'modifierConfigs' => [],
        ],
        [
            'name' => 'ration_space_potato_default',
            'type' => 'ration',
            'moralPoints' => [0 => 1],
            'actionPoints' => [8 => 1],
            'movementPoints' => [0 => 1],
            'healthPoints' => [0 => 1],
            'satiety' => 8.0,
            'extraEffects' => [],
            'isPerishable' => false,
            'actions' => [
                'consume',
                ActionEnum::MIX_RATION_SPORE->value,
            ],
            'modifierConfigs' => [],
        ],
        [
            'name' => 'ration_supervitamin_bar_default',
            'type' => 'ration',
            'moralPoints' => [0 => 1],
            'actionPoints' => [8 => 1],
            'movementPoints' => [4 => 1],
            'healthPoints' => [0 => 1],
            'satiety' => 6.0,
            'extraEffects' => [],
            'isPerishable' => false,
            'actions' => [
                'consume',
                ActionEnum::MIX_RATION_SPORE->value,
            ],
            'modifierConfigs' => [],
        ],
        [
            'name' => 'tools_hacker_kit_default',
            'type' => 'tool',
            'actions' => [],
            'modifierConfigs' => [],
        ],
        [
            'name' => 'tools_duct_tape_default',
            'type' => 'tool',
            'actions' => [
                'gag',
            ],
            'modifierConfigs' => [],
        ],
        [
            'name' => 'tools_microwave_default',
            'type' => 'tool',
            'actions' => [
                'express_cook',
            ],
            'modifierConfigs' => [],
        ],
        [
            'name' => 'tools_superfreezer_default',
            'type' => 'tool',
            'actions' => [
                'hyperfreeze',
            ],
            'modifierConfigs' => [],
        ],
        [
            'name' => 'gear_stainproof_apron_default',
            'type' => 'gear',
            'actions' => [],
            'modifierConfigs' => [
                'apron_modifier_for_player_prevent_dirty',
            ],
        ],
        [
            'name' => 'gear_plastenite_armor_default',
            'type' => 'gear',
            'actions' => [],
            'modifierConfigs' => [
                'modifier_for_target_player_+1healthPoint_on_injury',
            ],
        ],
        [
            'name' => 'gear_adjustable_wrench_default',
            'type' => 'gear',
            'actions' => [],
            'modifierConfigs' => [
                'modifier_for_player_x1.5percentage_on_action_technician',
            ],
        ],
        [
            'name' => 'gear_protective_gloves_default',
            'type' => 'gear',
            'actions' => [],
            'modifierConfigs' => [
                'gloves_modifier_for_player_set_0percentage_on_event_clumsiness',
            ],
        ],
        [
            'name' => 'gear_soap_default',
            'type' => 'gear',
            'actions' => [],
            'modifierConfigs' => [
                'modifier_for_player_-1actionPoint_on_shower',
            ],
        ],
        [
            'name' => 'gear_sniper_helmet_default',
            'type' => 'gear',
            'actions' => [],
            'modifierConfigs' => [
                'modifier_for_player_x1.1percentage_on_action_shoot_hunter',
                'modifier_for_player_x1.33percentage_on_action_shoot',
            ],
        ],
        [
            'name' => 'gear_antigrav_scooter_default',
            'type' => 'gear',
            'actions' => [],
            'modifierConfigs' => [
                'modifier_for_player_+2movementPoint_on_event_action_movement_conversion',
            ],
        ],
        [
            'name' => 'gear_rolling_boulder_default',
            'type' => 'gear',
            'actions' => [],
            'modifierConfigs' => [
                'modifier_for_player_+1movementPoint_on_event_action_movement_conversion_if_cycle_even',
            ],
        ],
        [
            'name' => 'gear_ncc_lenses_default',
            'type' => 'gear',
            'actions' => [],
            'modifierConfigs' => [
                'modifier_for_player_x1.1percentage_on_action_shoot_hunter',
                'modifier_for_player_x1.33percentage_on_action_shoot',
            ],
        ],
        [
            'name' => 'gear_oscilloscope_default',
            'type' => 'gear',
            'actions' => [],
            'modifierConfigs' => [
                'modifier_for_player_x2hull_on_change.variable_if_reason_strengthen_hull',
                'modifier_for_player_x2percentage_on_strengthen_hull',
                'modifier_for_player_x2percentage_on_renovate',
            ],
        ],
        [
            'name' => 'weapon_blaster_default',
            'type' => 'weapon',
            'baseAccuracy' => 50.0,
            'baseDamageRange' => [2 => 45, 3 => 45, 4 => 5, 5 => 5],
            'expeditionBonus' => 1.0,
            'criticalSuccessRate' => 5.0,
            'criticalFailRate' => 1.0,
            'oneShotRate' => 1.0,
            'actions' => [
                ActionEnum::SHOOT->value,
                ActionEnum::SHOOT_CAT->value,
            ],
            'modifierConfigs' => [],
        ],
        [
            'name' => 'weapon_knife_default',
            'type' => 'weapon',
            'baseAccuracy' => 60.0,
            'baseDamageRange' => [1 => 25, 2 => 25, 3 => 25, 4 => 12, 5 => 12],
            'expeditionBonus' => 1.0,
            'criticalSuccessRate' => 25.0,
            'criticalFailRate' => 20.0,
            'oneShotRate' => 2.0,
            'actions' => [
                ActionEnum::ATTACK->value,
            ],
            'modifierConfigs' => [],
        ],
        [
            'name' => 'weapon_grenade_default',
            'type' => 'weapon',
            'baseAccuracy' => 100.0,
            'baseDamageRange' => [
                2 => 1,
                3 => 1,
                4 => 1,
                5 => 1,
                6 => 1,
                7 => 1,
                8 => 1,
            ],
            'expeditionBonus' => 3.0,
            'criticalSuccessRate' => 0.0,
            'criticalFailRate' => 0.0,
            'oneShotRate' => 0.0,
            'actions' => [
                ActionEnum::THROW_GRENADE->value,
            ],
            'modifierConfigs' => [],
        ],
        [
            'name' => 'weapon_natamy_rifle_default',
            'type' => 'weapon',
            'baseAccuracy' => 50.0,
            'baseDamageRange' => [2 => 12],
            'expeditionBonus' => 1.0,
            'criticalSuccessRate' => 0.0,
            'criticalFailRate' => 0.0,
            'oneShotRate' => 0.0,
            'actions' => [],
            'modifierConfigs' => [],
        ],
        [
            'name' => 'weapon_old_faithful_default',
            'type' => 'weapon',
            'baseAccuracy' => 50.0,
            'baseDamageRange' => [2 => 3],
            'expeditionBonus' => 2.0,
            'criticalSuccessRate' => 0.0,
            'criticalFailRate' => 0.0,
            'oneShotRate' => 0.0,
            'actions' => [],
            'modifierConfigs' => [],
        ],
        [
            'name' => 'weapon_lizaro_jungle_default',
            'type' => 'weapon',
            'baseAccuracy' => 99.0,
            'baseDamageRange' => [3 => 5],
            'expeditionBonus' => 1.0,
            'criticalSuccessRate' => 0.0,
            'criticalFailRate' => 0.0,
            'oneShotRate' => 0.0,
            'actions' => [],
            'modifierConfigs' => [],
        ],
        [
            'name' => 'weapon_rocket_launcher_default',
            'type' => 'weapon',
            'baseAccuracy' => 50.0,
            'baseDamageRange' => [0 => 8],
            'expeditionBonus' => 3.0,
            'criticalSuccessRate' => 0.0,
            'criticalFailRate' => 0.0,
            'oneShotRate' => 0.0,
            'actions' => [],
            'modifierConfigs' => [],
        ],
        [
            'name' => 'tools_kitchen_default',
            'type' => 'tool',
            'actions' => [
                'cook',
                'wash_in_sink',
            ],
            'modifierConfigs' => [],
        ],
        [
            'name' => 'tools_snc_kitchen_default',
            'type' => 'tool',
            'actions' => [
                'cook',
                'wash_in_sink',
            ],
            'modifierConfigs' => [],
        ],
        [
            'name' => 'tools_surgery_plot_default',
            'type' => 'tool',
            'actions' => [
                'self_surgery',
            ],
            'modifierConfigs' => [],
        ],
        [
            'name' => 'tools_fuel_tank_default',
            'type' => 'tool',
            'actions' => [
                'insert_fuel',
                'retrieve_fuel',
            ],
        ],
        [
            'name' => 'tools_oxygen_tank_default',
            'type' => 'tool',
            'actions' => [
                'insert_oxygen',
                'retrieve_oxygen',
            ],
        ],
        [
            'name' => 'gear_antenna_default',
            'type' => 'gear',
            'actions' => [],
            'modifierConfigs' => [
                'modifier_for_daedalus_-1actionPoint_on_TODO coms. action',
            ],
        ],
        [
            'name' => 'gear_radar_trans_void_antenna_default',
            'type' => 'gear',
            'actions' => [],
            'modifierConfigs' => [
                'modifier_for_daedalus_-1actionPoint_on_TODO coms. action',
                'modifier_for_daedalus_x2_signal_on_action_contact_sol',
            ],
        ],
        [
            'name' => 'gear_oxygen_tank_default',
            'type' => 'gear',
            'actions' => [],
            'modifierConfigs' => [
                'modifier_for_daedalus_+1oxygen_on_change.variable_if_reason_new_cycle',
            ],
        ],
        [
            'name' => 'echolocator_blueprint_default',
            'type' => 'blueprint',
            'craftedEquipmentName' => 'echolocator',
            'ingredients' => ['plastic_scraps' => 1, 'metal_scraps' => 1],
            'actions' => [
                'build',
            ],
            'modifierConfigs' => [],
        ],
        [
            'name' => 'white_flag_blueprint_default',
            'type' => 'blueprint',
            'craftedEquipmentName' => 'white_flag',
            'ingredients' => ['soap' => 1, 'old_t_shirt' => 1],
            'actions' => [
                'build',
            ],
            'modifierConfigs' => [],
        ],
        [
            'name' => 'thermosensor_blueprint_default',
            'type' => 'blueprint',
            'craftedEquipmentName' => 'thermosensor',
            'ingredients' => ['plastic_scraps' => 1, 'metal_scraps' => 1],
            'actions' => [
                'build',
            ],
            'modifierConfigs' => [],
        ],
        [
            'name' => 'babel_module_blueprint_default',
            'type' => 'blueprint',
            'craftedEquipmentName' => 'babel_module',
            'ingredients' => ['plastic_scraps' => 1, 'metal_scraps' => 1],
            'actions' => [
                'build',
            ],
            'modifierConfigs' => [],
        ],
        [
            'name' => 'grenade_blueprint_default',
            'type' => 'blueprint',
            'craftedEquipmentName' => 'grenade',
            'ingredients' => ['oxygen_capsule' => 1, 'fuel_capsule' => 1],
            'actions' => [
                'build',
            ],
            'modifierConfigs' => [],
        ],
        [
            'name' => 'old_faithful_blueprint_default',
            'type' => 'blueprint',
            'craftedEquipmentName' => 'old_faithful',
            'ingredients' => ['metal_scraps' => 4],
            'actions' => [
                'build',
            ],
            'modifierConfigs' => [],
        ],
        [
            'name' => 'lizaro_jungle_blueprint_default',
            'type' => 'blueprint',
            'craftedEquipmentName' => 'lizaro_jungle',
            'ingredients' => ['plastic_scraps' => 1, 'metal_scraps' => 2],
            'actions' => [
                'build',
            ],
            'modifierConfigs' => [],
        ],
        [
            'name' => 'rocket_launcher_blueprint_default',
            'type' => 'blueprint',
            'craftedEquipmentName' => 'rocket_launcher',
            'ingredients' => ['plastic_scraps' => 1, 'metal_scraps' => 1, 'thick_tube' => 1],
            'actions' => [
                'build',
            ],
            'modifierConfigs' => [],
        ],
        [
            'name' => 'extinguisher_blueprint_default',
            'type' => 'blueprint',
            'craftedEquipmentName' => 'extinguisher',
            'ingredients' => ['oxygen_capsule' => 1, 'metal_scraps' => 1],
            'actions' => [
                'build',
            ],
            'modifierConfigs' => [],
        ],
        [
            'name' => 'oscilloscope_blueprint_default',
            'type' => 'blueprint',
            'craftedEquipmentName' => 'oscilloscope',
            'ingredients' => ['plastic_scraps' => 1, 'metal_scraps' => 1],
            'actions' => [
                'build',
            ],
            'modifierConfigs' => [],
        ],
        [
            'name' => 'sniper_helmet_blueprint_default',
            'type' => 'blueprint',
            'craftedEquipmentName' => 'sniper_helmet',
            'ingredients' => ['plastic_scraps' => 1, 'metal_scraps' => 1],
            'actions' => [
                'build',
            ],
            'modifierConfigs' => [],
        ],
        [
            'name' => 'swedish_sofa_blueprint_default',
            'type' => 'blueprint',
            'craftedEquipmentName' => 'swedish_sofa',
            'ingredients' => [ItemEnum::THICK_TUBE => 1, 'metal_scraps' => 1],
            'actions' => [
                'build',
            ],
            'modifierConfigs' => [],
        ],
        [
            'name' => 'jukebox_blueprint_default',
            'type' => EquipmentMechanicEnum::BLUEPRINT,
            'craftedEquipmentName' => EquipmentEnum::JUKEBOX,
            'ingredients' => [ItemEnum::METAL_SCRAPS => 1, ItemEnum::PLASTIC_SCRAPS => 1],
            'actions' => [
                ActionEnum::BUILD->value,
            ],
            'modifierConfigs' => [],
        ],
        [
            'name' => 'support_drone_blueprint_default',
            'type' => EquipmentMechanicEnum::BLUEPRINT,
            'craftedEquipmentName' => ItemEnum::SUPPORT_DRONE,
            'ingredients' => [ItemEnum::METAL_SCRAPS => 4, ItemEnum::PLASTIC_SCRAPS => 1],
            'actions' => [
                ActionEnum::BUILD->value,
            ],
            'modifierConfigs' => [],
        ],
        [
            'name' => 'tool_coffee_machine_default',
            'type' => 'tool',
            'actions' => [
                'coffee',
            ],
            'modifierConfigs' => [],
        ],
        [
            'name' => 'tool_narcotic_distiller_default',
            'type' => 'tool',
            'actions' => [
                'dispense',
            ],
            'modifierConfigs' => [],
        ],
        [
            'name' => 'weapon_turret_default',
            'type' => 'weapon',
            'baseAccuracy' => 30,
            'baseDamageRange' => [2 => 1, 3 => 1, 4 => 1],
            'expeditionBonus' => 0,
            'criticalSuccessRate' => 0,
            'criticalFailRate' => 0,
            'oneShotRate' => 0,
            'actions' => [
                ActionEnum::SHOOT_HUNTER->value . '_turret',
                ActionEnum::SHOOT_RANDOM_HUNTER->value . '_turret',
            ],
            'modifierConfigs' => [],
        ],
        [
            'name' => 'weapon_patrol_ship_default',
            'type' => 'weapon',
            'baseAccuracy' => 40,
            'baseDamageRange' => [3 => 1, 4 => 1, 5 => 1, 6 => 1],
            'expeditionBonus' => 0,
            'criticalSuccessRate' => 0,
            'criticalFailRate' => 0,
            'oneShotRate' => 0,
            'actions' => [
                ActionEnum::SHOOT_HUNTER_PATROL_SHIP->value,
                ActionEnum::SHOOT_RANDOM_HUNTER_PATROL_SHIP->value,
            ],
            'modifierConfigs' => [],
        ],
        [
            'name' => 'patrol_ship_patrol_ship_alpha_longane_default',
            'type' => EquipmentMechanicEnum::PATROL_SHIP,
            'collectScrapNumber' => [
                0 => 3,
                1 => 1,
            ],
            'collectScrapPatrolShipDamage' => [
                2 => 1,
                3 => 1,
                4 => 1,
            ],
            'collectScrapPlayerDamage' => [
                0 => 3,
                2 => 1,
                3 => 1,
                4 => 1,
            ],
            'dockingPlace' => RoomEnum::ALPHA_BAY,
            'failedManoeuvreDaedalusDamage' => [
                2 => 1,
                3 => 1,
                4 => 1,
            ],
            'failedManoeuvrePatrolShipDamage' => [1 => 1],
            'failedManoeuvrePlayerDamage' => [
                0 => 1,
                1 => 1,
                2 => 1,
            ],
            'numberOfExplorationSteps' => 3,
            'actions' => [
                ActionEnum::TAKEOFF->value,
                ActionEnum::LAND->value,
                ActionEnum::COLLECT_SCRAP->value,
                ActionEnum::TAKEOFF_TO_PLANET_PATROL_SHIP->value,
            ],
            'modifierConfigs' => [],
        ],
        [
            'name' => 'patrol_ship_patrol_ship_alpha_jujube_default',
            'type' => EquipmentMechanicEnum::PATROL_SHIP,
            'collectScrapNumber' => [
                0 => 3,
                1 => 1,
            ],
            'collectScrapPatrolShipDamage' => [
                2 => 1,
                3 => 1,
                4 => 1,
            ],
            'collectScrapPlayerDamage' => [
                0 => 3,
                2 => 1,
                3 => 1,
                4 => 1,
            ],
            'dockingPlace' => RoomEnum::ALPHA_BAY,
            'failedManoeuvreDaedalusDamage' => [
                2 => 1,
                3 => 1,
                4 => 1,
            ],
            'failedManoeuvrePatrolShipDamage' => [1 => 1],
            'failedManoeuvrePlayerDamage' => [
                0 => 1,
                1 => 1,
                2 => 1,
            ],
            'numberOfExplorationSteps' => 3,
            'actions' => [
                ActionEnum::TAKEOFF->value,
                ActionEnum::LAND->value,
                ActionEnum::COLLECT_SCRAP->value,
                ActionEnum::TAKEOFF_TO_PLANET_PATROL_SHIP->value,
            ],
            'modifierConfigs' => [],
        ],
        [
            'name' => 'patrol_ship_patrol_ship_alpha_tamarin_default',
            'type' => EquipmentMechanicEnum::PATROL_SHIP,
            'collectScrapNumber' => [
                0 => 3,
                1 => 1,
            ],
            'collectScrapPatrolShipDamage' => [
                2 => 1,
                3 => 1,
                4 => 1,
            ],
            'collectScrapPlayerDamage' => [
                0 => 3,
                2 => 1,
                3 => 1,
                4 => 1,
            ],
            'dockingPlace' => RoomEnum::ALPHA_BAY,
            'failedManoeuvreDaedalusDamage' => [
                2 => 1,
                3 => 1,
                4 => 1,
            ],
            'failedManoeuvrePatrolShipDamage' => [1 => 1],
            'failedManoeuvrePlayerDamage' => [
                0 => 1,
                1 => 1,
                2 => 1,
            ],
            'numberOfExplorationSteps' => 3,
            'actions' => [
                ActionEnum::TAKEOFF->value,
                ActionEnum::LAND->value,
                ActionEnum::COLLECT_SCRAP->value,
                ActionEnum::TAKEOFF_TO_PLANET_PATROL_SHIP->value,
            ],
            'modifierConfigs' => [],
        ],
        [
            'name' => 'patrol_ship_patrol_ship_bravo_socrate_default',
            'type' => EquipmentMechanicEnum::PATROL_SHIP,
            'collectScrapNumber' => [
                0 => 3,
                1 => 1,
            ],
            'collectScrapPatrolShipDamage' => [
                2 => 1,
                3 => 1,
                4 => 1,
            ],
            'collectScrapPlayerDamage' => [
                0 => 3,
                2 => 1,
                3 => 1,
                4 => 1,
            ],
            'dockingPlace' => RoomEnum::BRAVO_BAY,
            'failedManoeuvreDaedalusDamage' => [
                2 => 1,
                3 => 1,
                4 => 1,
            ],
            'failedManoeuvrePatrolShipDamage' => [1 => 1],
            'failedManoeuvrePlayerDamage' => [
                0 => 1,
                1 => 1,
                2 => 1,
            ],
            'numberOfExplorationSteps' => 3,
            'actions' => [
                ActionEnum::TAKEOFF->value,
                ActionEnum::LAND->value,
                ActionEnum::COLLECT_SCRAP->value,
                ActionEnum::TAKEOFF_TO_PLANET_PATROL_SHIP->value,
            ],
            'modifierConfigs' => [],
        ],
        [
            'name' => 'patrol_ship_patrol_ship_bravo_epicure_default',
            'type' => EquipmentMechanicEnum::PATROL_SHIP,
            'collectScrapNumber' => [
                0 => 3,
                1 => 1,
            ],
            'collectScrapPatrolShipDamage' => [
                2 => 1,
                3 => 1,
                4 => 1,
            ],
            'collectScrapPlayerDamage' => [
                0 => 3,
                2 => 1,
                3 => 1,
                4 => 1,
            ],
            'dockingPlace' => RoomEnum::BRAVO_BAY,
            'failedManoeuvreDaedalusDamage' => [
                2 => 1,
                3 => 1,
                4 => 1,
            ],
            'failedManoeuvrePatrolShipDamage' => [1 => 1],
            'failedManoeuvrePlayerDamage' => [
                0 => 1,
                1 => 1,
                2 => 1,
            ],
            'numberOfExplorationSteps' => 3,
            'actions' => [
                ActionEnum::TAKEOFF->value,
                ActionEnum::LAND->value,
                ActionEnum::COLLECT_SCRAP->value,
                ActionEnum::TAKEOFF_TO_PLANET_PATROL_SHIP->value,
            ],
            'modifierConfigs' => [],
        ],
        [
            'name' => 'patrol_ship_patrol_ship_bravo_planton_default',
            'type' => EquipmentMechanicEnum::PATROL_SHIP,
            'collectScrapNumber' => [
                0 => 3,
                1 => 1,
            ],
            'collectScrapPatrolShipDamage' => [
                2 => 1,
                3 => 1,
                4 => 1,
            ],
            'collectScrapPlayerDamage' => [
                0 => 3,
                2 => 1,
                3 => 1,
                4 => 1,
            ],
            'dockingPlace' => RoomEnum::BRAVO_BAY,
            'failedManoeuvreDaedalusDamage' => [
                2 => 1,
                3 => 1,
                4 => 1,
            ],
            'failedManoeuvrePatrolShipDamage' => [1 => 1],
            'failedManoeuvrePlayerDamage' => [
                0 => 1,
                1 => 1,
                2 => 1,
            ],
            'numberOfExplorationSteps' => 3,
            'actions' => [
                ActionEnum::TAKEOFF->value,
                ActionEnum::LAND->value,
                ActionEnum::COLLECT_SCRAP->value,
                ActionEnum::TAKEOFF_TO_PLANET_PATROL_SHIP->value,
            ],
            'modifierConfigs' => [],
        ],
        [
            'name' => 'patrol_ship_patrol_ship_alpha_2_wallis_default',
            'type' => EquipmentMechanicEnum::PATROL_SHIP,
            'collectScrapNumber' => [
                0 => 3,
                1 => 1,
            ],
            'collectScrapPatrolShipDamage' => [
                2 => 1,
                3 => 1,
                4 => 1,
            ],
            'collectScrapPlayerDamage' => [
                0 => 3,
                2 => 1,
                3 => 1,
                4 => 1,
            ],
            'dockingPlace' => RoomEnum::ALPHA_BAY_2,
            'failedManoeuvreDaedalusDamage' => [
                2 => 1,
                3 => 1,
                4 => 1,
            ],
            'failedManoeuvrePatrolShipDamage' => [1 => 1],
            'failedManoeuvrePlayerDamage' => [
                0 => 1,
                1 => 1,
                2 => 1,
            ],
            'numberOfExplorationSteps' => 3,
            'actions' => [
                ActionEnum::TAKEOFF->value,
                ActionEnum::LAND->value,
                ActionEnum::COLLECT_SCRAP->value,
                ActionEnum::TAKEOFF_TO_PLANET_PATROL_SHIP->value,
            ],
            'modifierConfigs' => [],
        ],
        [
            'name' => 'patrol_ship_pasiphae_default',
            'type' => EquipmentMechanicEnum::PATROL_SHIP,
            'collectScrapNumber' => [
                1 => 1,
                2 => 1,
                3 => 1,
            ],
            'collectScrapPatrolShipDamage' => [
                2 => 1,
                3 => 1,
                4 => 1,
            ],
            'collectScrapPlayerDamage' => [
                0 => 3,
                2 => 1,
                3 => 1,
                4 => 1,
            ],
            'dockingPlace' => RoomEnum::ALPHA_BAY_2,
            'failedManoeuvreDaedalusDamage' => [
                2 => 1,
                3 => 1,
                4 => 1,
            ],
            'failedManoeuvrePatrolShipDamage' => [1 => 1],
            'failedManoeuvrePlayerDamage' => [
                0 => 1,
                1 => 1,
                2 => 1,
            ],
            'numberOfExplorationSteps' => 3,
            'actions' => [
                ActionEnum::TAKEOFF->value,
                ActionEnum::LAND->value,
                ActionEnum::COLLECT_SCRAP->value,
                ActionEnum::TAKEOFF_TO_PLANET_PATROL_SHIP->value,
            ],
            'modifierConfigs' => [],
        ],
        [
            'name' => 'patrol_ship_icarus_default',
            'type' => EquipmentMechanicEnum::PATROL_SHIP,
            'collectScrapNumber' => [],
            'collectScrapPatrolShipDamage' => [],
            'collectScrapPlayerDamage' => [],
            'dockingPlace' => RoomEnum::ICARUS_BAY,
            'failedManoeuvreDaedalusDamage' => [],
            'failedManoeuvrePatrolShipDamage' => [],
            'failedManoeuvrePlayerDamage' => [],
            'numberOfExplorationSteps' => 9,
            'actions' => [
                ActionEnum::TAKEOFF_TO_PLANET->value,
            ],
            'modifierConfigs' => [],
        ],
        [
            'name' => 'tool_spacesuit_default',
            'type' => 'tool',
            'actions' => [
                ActionEnum::AUTO_EJECT->value,
            ],
        ],
        [
            'name' => 'tool_door_default',
            'type' => 'tool',
            'actions' => [
                ActionEnum::MOVE->value,
            ],
        ],
        [
            'name' => 'tool_astro_terminal_default',
            'type' => 'tool',
            'actions' => [
                ActionEnum::ANALYZE_PLANET->value,
                ActionEnum::DELETE_PLANET->value,
                ActionEnum::SCAN->value,
                ActionEnum::ACCESS_TERMINAL->value,
                ActionEnum::EXIT_TERMINAL->value,
            ],
        ],
        [
            'name' => 'camera_item_mechanic_default',
            'type' => 'tool',
            'actions' => [
                ActionEnum::INSTALL_CAMERA->value,
            ],
        ],
        [
            'name' => 'camera_equipment_mechanic_default',
            'type' => 'tool',
            'actions' => [
                ActionEnum::REMOVE_CAMERA->value,
            ],
        ],
        [
            'name' => 'tool_combustion_chamber_default',
            'type' => 'tool',
            'actions' => [
                ActionEnum::CHECK_FUEL_CHAMBER_LEVEL->value,
                ActionEnum::RETRIEVE_FUEL_CHAMBER->value,
            ],
        ],
        [
            'name' => 'spore_sucker_mechanic_default',
            'type' => 'tool',
            'actions' => [
                ActionEnum::REMOVE_SPORE->value,
            ],
        ],
        [
            'name' => 'extinguisher_mechanic_default',
            'type' => 'tool',
            'actions' => [
                ActionEnum::EXTINGUISH->value,
            ],
        ],
        [
            'name' => 'alien_tv_mechanic_default',
            'type' => 'tool',
            'actions' => [
                ActionEnum::PUBLIC_BROADCAST->value,
            ],
        ],
        [
            'name' => 'gear_planet_scanner_default',
            'type' => 'gear',
            'actions' => [],
            'modifierConfigs' => [
                'modifier_for_daedalus_+30percentage_on_action_scan',
            ],
        ],
        [
            'name' => 'gear_quantum_sensors_planet_scanner_default',
            'type' => 'gear',
            'actions' => [],
            'modifierConfigs' => [
                'modifier_for_daedalus_+30percentage_on_action_scan',
                'modifier_for_daedalus_+1sector_revealed_on_action_analyze_planet',
            ],
        ],
        [
            'name' => 'gear_magellan_liquid_map_default',
            'type' => 'gear',
            'actions' => [],
            'modifierConfigs' => [
                'modifier_for_place_+1sector_revealed_on_action_scan_planet',
                'modifier_for_place_+1sector_revealed_on_action_scan_planet_random_50',
            ],
        ],
        [
            'name' => 'gear_modifier_for_alien_oil_default',
            'type' => 'gear',
            'actions' => [],
            'modifierConfigs' => [
                'modifier_for_alien_oil_+4_fuel',
            ],
        ],
        [
            'name' => 'gear_invertebrate_shell_default',
            'type' => 'gear',
            'actions' => [],
            'modifierConfigs' => [
                'modifier_for_place_x2_hunter_damage_on_change.variable',
            ],
        ],
        [
            'name' => 'gear_rope_default',
            'type' => 'gear',
            'actions' => [],
            'modifierConfigs' => [
                'rope_modifier_for_player_prevent_change.variable_if_reason_accident_and_variable_healthPoint',
            ],
        ],
        [
            'name' => 'tool_pilgred_terminal_default',
            'type' => 'tool',
            'actions' => [
                ActionEnum::REPAIR_PILGRED->value,
                ActionEnum::ACCESS_TERMINAL->value,
                ActionEnum::EXIT_TERMINAL->value,
            ],
        ],
        [
            'name' => 'tool_bios_terminal_default',
            'type' => 'tool',
            'actions' => [
                ActionEnum::HACK->value,
                ActionEnum::CHANGE_NERON_CPU_PRIORITY->value,
                ActionEnum::CHANGE_NERON_CREW_LOCK->value,
                ActionEnum::TOGGLE_PLASMA_SHIELD->value,
                ActionEnum::TOGGLE_MAGNETIC_NET->value,
                ActionEnum::TOGGLE_NERON_INHIBITION->value,
                ActionEnum::ACCESS_TERMINAL->value,
                ActionEnum::EXIT_TERMINAL->value,
            ],
        ],
        [
            'name' => 'tool_command_default',
            'type' => 'tool',
            'actions' => [
                ActionEnum::HACK->value,
                ActionEnum::RETURN_TO_SOL->value,
                ActionEnum::ADVANCE_DAEDALUS->value,
                ActionEnum::ACCESS_TERMINAL->value,
                ActionEnum::EXIT_TERMINAL->value,
                ActionEnum::TURN_DAEDALUS_LEFT->value,
                ActionEnum::TURN_DAEDALUS_RIGHT->value,
                ActionEnum::LEAVE_ORBIT->value,
            ],
        ],
        [
            'name' => 'tool_neron_core_default',
            'type' => 'tool',
            'actions' => [
                ActionEnum::PARTICIPATE->value,
                ActionEnum::PUTSCH->value,
                ActionEnum::ACCESS_TERMINAL->value,
                ActionEnum::EXIT_TERMINAL->value,
            ],
        ],
        [
            'name' => 'tool_auxiliary_terminal_default',
            'type' => 'tool',
            'actions' => [
                ActionEnum::PARTICIPATE->value,
                ActionEnum::ACCESS_TERMINAL->value,
                ActionEnum::EXIT_TERMINAL->value,
            ],
        ],
        [
            'name' => 'tool_shower_default',
            'type' => 'tool',
            'actions' => [
                ActionEnum::TAKE_SHOWER->value,
            ],
        ],
        [
            'name' => 'tool_dynarcade_default',
            'type' => 'tool',
            'actions' => [
                ActionEnum::PLAY_ARCADE->value,
            ],
        ],
        [
            'name' => 'tool_bed_default',
            'type' => 'tool',
            'actions' => [
                ActionEnum::LIE_DOWN->value,
            ],
        ],
        [
            'name' => 'tool_mycoscan_default',
            'type' => 'tool',
            'actions' => [
                ActionEnum::CHECK_SPORE_LEVEL->value,
            ],
        ],
        [
            'name' => 'tool_tabulatrix_default',
            'type' => 'tool',
            'actions' => [
                ActionEnum::PRINT_ZE_LIST->value,
            ],
        ],
        [
            'name' => 'gear_thalasso_default',
            'type' => 'gear',
            'actions' => [],
            'modifierConfigs' => [
                'modifier_for_player_set_+1moralePoint_on_post.action_if_reason_shower',
                'modifier_for_player_set_+1healthPoint_on_post.action_if_reason_shower',
                'modifier_for_player_set_+2movementPoint_on_post.action_if_reason_shower',
            ],
        ],
        [
            'name' => 'gear_hydroponic_incubator_default',
            'type' => EquipmentMechanicEnum::GEAR,
            'actions' => [],
            'modifierConfigs' => [
                'modifier_for_place_x2_maturation_time',
            ],
        ],
        [
            'name' => 'tool_research_lab_default',
            'type' => EquipmentMechanicEnum::TOOL,
            'actions' => [
                ActionEnum::PARTICIPATE->value,
                ActionEnum::ACCESS_TERMINAL->value,
                ActionEnum::EXIT_TERMINAL->value,
            ],
            'modifierConfigs' => [],
        ],
        [
            'name' => self::TOOL_COMMS_CENTER,
            'type' => EquipmentMechanicEnum::TOOL,
            'actions' => [
                ActionEnum::SEARCH_FOR_MUSH_GENOME->value,
            ],
        ],
    ];
}
