<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20230211113736 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE SEQUENCE abstract_modifier_config_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE action_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE alert_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE alert_element_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE character_config_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE closed_player_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE communication_channel_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE communication_channel_player_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE config_daedalus_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE config_difficulty_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE config_game_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE config_localization_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE config_random_item_place_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE consumable_effect_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE daedalus_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE daedalus_closed_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE daedalus_info_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE disease_cause_config_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE disease_config_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE disease_consummable_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE disease_consummable_attribute_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE disease_consummable_config_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE disease_player_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE equipment_config_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE equipment_mechanic_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE game_equipment_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE game_modifier_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE game_variable_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE game_variable_collection_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE message_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE modifier_activation_requirement_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE neron_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE news_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE place_config_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE plant_effect_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE player_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE player_info_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE room_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE room_log_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE status_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE status_config_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE status_target_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE symptom_activation_requirement_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE symptom_config_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE triumph_config_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE users_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE TABLE abstract_modifier_config (id INT NOT NULL, name VARCHAR(255) NOT NULL, modifier_name VARCHAR(255) DEFAULT NULL, target_event VARCHAR(255) NOT NULL, apply_on_action_parameter BOOLEAN NOT NULL, modifier_holder_class VARCHAR(255) NOT NULL, type VARCHAR(255) NOT NULL, triggered_event VARCHAR(255) DEFAULT NULL, visibility VARCHAR(255) DEFAULT NULL, delta DOUBLE PRECISION DEFAULT NULL, target_variable VARCHAR(255) DEFAULT NULL, mode VARCHAR(255) DEFAULT NULL, applies_on VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_DF12FDD55E237E06 ON abstract_modifier_config (name)');
        $this->addSql('CREATE TABLE abstract_modifier_config_modifier_activation_requirement (abstract_modifier_config_id INT NOT NULL, modifier_activation_requirement_id INT NOT NULL, PRIMARY KEY(abstract_modifier_config_id, modifier_activation_requirement_id))');
        $this->addSql('CREATE INDEX IDX_E2ECCA99BFA8DC8C ON abstract_modifier_config_modifier_activation_requirement (abstract_modifier_config_id)');
        $this->addSql('CREATE INDEX IDX_E2ECCA99F299F7D7 ON abstract_modifier_config_modifier_activation_requirement (modifier_activation_requirement_id)');
        $this->addSql('CREATE TABLE action (id INT NOT NULL, action_variables_id INT DEFAULT NULL, name VARCHAR(255) NOT NULL, action_name VARCHAR(255) NOT NULL, types TEXT NOT NULL, target VARCHAR(255) DEFAULT NULL, scope VARCHAR(255) NOT NULL, visibilities TEXT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_47CC8C925E237E06 ON action (name)');
        $this->addSql('CREATE INDEX IDX_47CC8C9271F0C45C ON action (action_variables_id)');
        $this->addSql('COMMENT ON COLUMN action.types IS \'(DC2Type:array)\'');
        $this->addSql('COMMENT ON COLUMN action.visibilities IS \'(DC2Type:array)\'');
        $this->addSql('CREATE TABLE alert (id INT NOT NULL, daedalus_id INT DEFAULT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_17FD46C174B5A52D ON alert (daedalus_id)');
        $this->addSql('CREATE TABLE alert_element (id INT NOT NULL, alert_id INT DEFAULT NULL, player_info_id INT DEFAULT NULL, place_id INT DEFAULT NULL, equipment_id INT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_DF13F9FB93035F72 ON alert_element (alert_id)');
        $this->addSql('CREATE INDEX IDX_DF13F9FB3C7F3EBD ON alert_element (player_info_id)');
        $this->addSql('CREATE INDEX IDX_DF13F9FBDA6A219 ON alert_element (place_id)');
        $this->addSql('CREATE INDEX IDX_DF13F9FB517FE9FE ON alert_element (equipment_id)');
        $this->addSql('CREATE TABLE character_config (id INT NOT NULL, name VARCHAR(255) NOT NULL, character_name VARCHAR(255) NOT NULL, skills TEXT NOT NULL, max_number_private_channel INT NOT NULL, max_health_point INT NOT NULL, max_moral_point INT NOT NULL, max_action_point INT NOT NULL, max_movement_point INT NOT NULL, max_item_in_inventory INT NOT NULL, init_health_point INT NOT NULL, init_moral_point INT NOT NULL, init_satiety INT NOT NULL, init_action_point INT NOT NULL, init_movement_point INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_77C8ECEF5E237E06 ON character_config (name)');
        $this->addSql('COMMENT ON COLUMN character_config.skills IS \'(DC2Type:array)\'');
        $this->addSql('CREATE TABLE character_config_status_config (character_config_id INT NOT NULL, status_config_id INT NOT NULL, PRIMARY KEY(character_config_id, status_config_id))');
        $this->addSql('CREATE INDEX IDX_2A38BC0EA38BA4B8 ON character_config_status_config (character_config_id)');
        $this->addSql('CREATE INDEX IDX_2A38BC0EAC4E86C2 ON character_config_status_config (status_config_id)');
        $this->addSql('CREATE TABLE character_config_action (character_config_id INT NOT NULL, action_id INT NOT NULL, PRIMARY KEY(character_config_id, action_id))');
        $this->addSql('CREATE INDEX IDX_51C5D29A38BA4B8 ON character_config_action (character_config_id)');
        $this->addSql('CREATE INDEX IDX_51C5D299D32F035 ON character_config_action (action_id)');
        $this->addSql('CREATE TABLE character_config_item_config (character_config_id INT NOT NULL, item_config_id INT NOT NULL, PRIMARY KEY(character_config_id, item_config_id))');
        $this->addSql('CREATE INDEX IDX_E44AA5FDA38BA4B8 ON character_config_item_config (character_config_id)');
        $this->addSql('CREATE INDEX IDX_E44AA5FD28011073 ON character_config_item_config (item_config_id)');
        $this->addSql('CREATE TABLE character_config_disease_config (character_config_id INT NOT NULL, disease_config_id INT NOT NULL, PRIMARY KEY(character_config_id, disease_config_id))');
        $this->addSql('CREATE INDEX IDX_D60B3C3BA38BA4B8 ON character_config_disease_config (character_config_id)');
        $this->addSql('CREATE INDEX IDX_D60B3C3B1998F6F9 ON character_config_disease_config (disease_config_id)');
        $this->addSql('CREATE TABLE closed_player (id INT NOT NULL, daedalus_id INT DEFAULT NULL, message VARCHAR(255) DEFAULT NULL, end_cause VARCHAR(255) NOT NULL, day_death INT NOT NULL, cycle_death INT NOT NULL, likes INT NOT NULL, is_mush BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_F154A5CC74B5A52D ON closed_player (daedalus_id)');
        $this->addSql('CREATE TABLE communication_channel (id INT NOT NULL, daedalus_info_id INT DEFAULT NULL, scope VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_D728A71D40AC2F6A ON communication_channel (daedalus_info_id)');
        $this->addSql('CREATE TABLE communication_channel_player (id INT NOT NULL, channel_id INT DEFAULT NULL, participant_id INT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_2908A45B72F5A1AA ON communication_channel_player (channel_id)');
        $this->addSql('CREATE INDEX IDX_2908A45B9D1C3019 ON communication_channel_player (participant_id)');
        $this->addSql('CREATE TABLE config_daedalus (id INT NOT NULL, random_item_places_id INT DEFAULT NULL, name VARCHAR(255) NOT NULL, init_oxygen INT NOT NULL, init_fuel INT NOT NULL, init_hull INT NOT NULL, init_shield INT NOT NULL, max_oxygen INT NOT NULL, max_fuel INT NOT NULL, max_hull INT NOT NULL, max_shield INT NOT NULL, daily_spore_nb INT NOT NULL, nb_mush INT NOT NULL, cycle_per_game_day INT NOT NULL, cycle_length INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_CC1298D45E237E06 ON config_daedalus (name)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_CC1298D4D5F7B64E ON config_daedalus (random_item_places_id)');
        $this->addSql('CREATE TABLE daedalus_config_place_config (daedalus_config_id INT NOT NULL, place_config_id INT NOT NULL, PRIMARY KEY(daedalus_config_id, place_config_id))');
        $this->addSql('CREATE INDEX IDX_A0E9A0CF201E3C43 ON daedalus_config_place_config (daedalus_config_id)');
        $this->addSql('CREATE INDEX IDX_A0E9A0CF50408FFE ON daedalus_config_place_config (place_config_id)');
        $this->addSql('CREATE TABLE config_difficulty (id INT NOT NULL, name VARCHAR(255) NOT NULL, equipment_break_rate INT NOT NULL, door_break_rate INT NOT NULL, equipment_fire_break_rate INT NOT NULL, starting_fire_rate INT NOT NULL, propagating_fire_rate INT NOT NULL, hull_fire_damage_rate INT NOT NULL, tremor_rate INT NOT NULL, electric_arc_rate INT NOT NULL, metal_plate_rate INT NOT NULL, panic_crisis_rate INT NOT NULL, fire_player_damage TEXT NOT NULL, fire_hull_damage TEXT NOT NULL, electric_arc_player_damage TEXT NOT NULL, tremor_player_damage TEXT NOT NULL, metal_plate_player_damage TEXT NOT NULL, panic_crisis_player_damage TEXT NOT NULL, plant_disease_rate INT NOT NULL, cycle_disease_rate INT NOT NULL, equipment_break_rate_distribution TEXT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_E362F5C95E237E06 ON config_difficulty (name)');
        $this->addSql('COMMENT ON COLUMN config_difficulty.fire_player_damage IS \'(DC2Type:array)\'');
        $this->addSql('COMMENT ON COLUMN config_difficulty.fire_hull_damage IS \'(DC2Type:array)\'');
        $this->addSql('COMMENT ON COLUMN config_difficulty.electric_arc_player_damage IS \'(DC2Type:array)\'');
        $this->addSql('COMMENT ON COLUMN config_difficulty.tremor_player_damage IS \'(DC2Type:array)\'');
        $this->addSql('COMMENT ON COLUMN config_difficulty.metal_plate_player_damage IS \'(DC2Type:array)\'');
        $this->addSql('COMMENT ON COLUMN config_difficulty.panic_crisis_player_damage IS \'(DC2Type:array)\'');
        $this->addSql('COMMENT ON COLUMN config_difficulty.equipment_break_rate_distribution IS \'(DC2Type:array)\'');
        $this->addSql('CREATE TABLE config_game (id INT NOT NULL, daedalus_config_id INT DEFAULT NULL, difficulty_config_id INT DEFAULT NULL, name VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_B38B6D7C5E237E06 ON config_game (name)');
        $this->addSql('CREATE INDEX IDX_B38B6D7C201E3C43 ON config_game (daedalus_config_id)');
        $this->addSql('CREATE INDEX IDX_B38B6D7C838718A0 ON config_game (difficulty_config_id)');
        $this->addSql('CREATE TABLE game_config_character_config (game_config_id INT NOT NULL, character_config_id INT NOT NULL, PRIMARY KEY(game_config_id, character_config_id))');
        $this->addSql('CREATE INDEX IDX_C3CBECE1F67DC781 ON game_config_character_config (game_config_id)');
        $this->addSql('CREATE INDEX IDX_C3CBECE1A38BA4B8 ON game_config_character_config (character_config_id)');
        $this->addSql('CREATE TABLE game_config_equipment_config (game_config_id INT NOT NULL, equipment_config_id INT NOT NULL, PRIMARY KEY(game_config_id, equipment_config_id))');
        $this->addSql('CREATE INDEX IDX_C7075032F67DC781 ON game_config_equipment_config (game_config_id)');
        $this->addSql('CREATE INDEX IDX_C7075032F6E640FA ON game_config_equipment_config (equipment_config_id)');
        $this->addSql('CREATE TABLE game_config_status_config (game_config_id INT NOT NULL, status_config_id INT NOT NULL, PRIMARY KEY(game_config_id, status_config_id))');
        $this->addSql('CREATE INDEX IDX_BBE53156F67DC781 ON game_config_status_config (game_config_id)');
        $this->addSql('CREATE INDEX IDX_BBE53156AC4E86C2 ON game_config_status_config (status_config_id)');
        $this->addSql('CREATE TABLE game_config_triumph_config (game_config_id INT NOT NULL, triumph_config_id INT NOT NULL, PRIMARY KEY(game_config_id, triumph_config_id))');
        $this->addSql('CREATE INDEX IDX_763B15A9F67DC781 ON game_config_triumph_config (game_config_id)');
        $this->addSql('CREATE INDEX IDX_763B15A9D15A829E ON game_config_triumph_config (triumph_config_id)');
        $this->addSql('CREATE TABLE game_config_disease_cause_config (game_config_id INT NOT NULL, disease_cause_config_id INT NOT NULL, PRIMARY KEY(game_config_id, disease_cause_config_id))');
        $this->addSql('CREATE INDEX IDX_E12276B4F67DC781 ON game_config_disease_cause_config (game_config_id)');
        $this->addSql('CREATE INDEX IDX_E12276B48D9CD4C9 ON game_config_disease_cause_config (disease_cause_config_id)');
        $this->addSql('CREATE TABLE game_config_disease_config (game_config_id INT NOT NULL, disease_config_id INT NOT NULL, PRIMARY KEY(game_config_id, disease_config_id))');
        $this->addSql('CREATE INDEX IDX_B32A3870F67DC781 ON game_config_disease_config (game_config_id)');
        $this->addSql('CREATE INDEX IDX_B32A38701998F6F9 ON game_config_disease_config (disease_config_id)');
        $this->addSql('CREATE TABLE game_config_consumable_disease_config (game_config_id INT NOT NULL, consumable_disease_config_id INT NOT NULL, PRIMARY KEY(game_config_id, consumable_disease_config_id))');
        $this->addSql('CREATE INDEX IDX_E6EA1EF67DC781 ON game_config_consumable_disease_config (game_config_id)');
        $this->addSql('CREATE INDEX IDX_E6EA1E8A8FEEED ON game_config_consumable_disease_config (consumable_disease_config_id)');
        $this->addSql('CREATE TABLE config_localization (id INT NOT NULL, name VARCHAR(255) NOT NULL, time_zone VARCHAR(255) NOT NULL, language VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_4BD83E305E237E06 ON config_localization (name)');
        $this->addSql('CREATE TABLE config_random_item_place (id INT NOT NULL, name VARCHAR(255) NOT NULL, places TEXT NOT NULL, items TEXT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('COMMENT ON COLUMN config_random_item_place.places IS \'(DC2Type:array)\'');
        $this->addSql('COMMENT ON COLUMN config_random_item_place.items IS \'(DC2Type:array)\'');
        $this->addSql('CREATE TABLE consumable_effect (id INT NOT NULL, daedalus_id INT DEFAULT NULL, ration_id INT DEFAULT NULL, action_point INT DEFAULT NULL, movement_point INT DEFAULT NULL, health_point INT DEFAULT NULL, moral_point INT DEFAULT NULL, satiety INT DEFAULT NULL, extra_effects TEXT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_C275962674B5A52D ON consumable_effect (daedalus_id)');
        $this->addSql('CREATE INDEX IDX_C27596264A5A89FC ON consumable_effect (ration_id)');
        $this->addSql('COMMENT ON COLUMN consumable_effect.extra_effects IS \'(DC2Type:array)\'');
        $this->addSql('CREATE TABLE daedalus (id INT NOT NULL, daedalus_variables_id INT DEFAULT NULL, day INT NOT NULL, cycle INT NOT NULL, filled_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, finished_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, cycle_started_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, is_cycle_change BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_71DA760AB28A6E7E ON daedalus (daedalus_variables_id)');
        $this->addSql('CREATE TABLE daedalus_closed (id INT NOT NULL, daedalus_info_id INT DEFAULT NULL, end_cause VARCHAR(255) NOT NULL, end_day INT NOT NULL, end_cycle INT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_9439BBF440AC2F6A ON daedalus_closed (daedalus_info_id)');
        $this->addSql('CREATE TABLE daedalus_info (id INT NOT NULL, game_config_id INT DEFAULT NULL, daedalus_id INT DEFAULT NULL, closed_daedalus_id INT DEFAULT NULL, neron_id INT DEFAULT NULL, localization_config_id INT DEFAULT NULL, game_status VARCHAR(255) NOT NULL, name VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_24725EFC5E237E06 ON daedalus_info (name)');
        $this->addSql('CREATE INDEX IDX_24725EFCF67DC781 ON daedalus_info (game_config_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_24725EFC74B5A52D ON daedalus_info (daedalus_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_24725EFCBBC83F78 ON daedalus_info (closed_daedalus_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_24725EFC66BCDEE6 ON daedalus_info (neron_id)');
        $this->addSql('CREATE INDEX IDX_24725EFC8D986DA0 ON daedalus_info (localization_config_id)');
        $this->addSql('CREATE TABLE disease_cause_config (id INT NOT NULL, name VARCHAR(255) NOT NULL, cause_name VARCHAR(255) NOT NULL, diseases TEXT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_E6DC25D15E237E06 ON disease_cause_config (name)');
        $this->addSql('COMMENT ON COLUMN disease_cause_config.diseases IS \'(DC2Type:array)\'');
        $this->addSql('CREATE TABLE disease_config (id INT NOT NULL, disease_name VARCHAR(255) NOT NULL, name VARCHAR(255) NOT NULL, type VARCHAR(255) NOT NULL, resistance INT NOT NULL, delay_min INT NOT NULL, delay_length INT NOT NULL, disease_point_min INT NOT NULL, disease_point_length INT NOT NULL, override TEXT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('COMMENT ON COLUMN disease_config.override IS \'(DC2Type:array)\'');
        $this->addSql('CREATE TABLE disease_config_variable_event_modifier_config (disease_config_id INT NOT NULL, variable_event_modifier_config_id INT NOT NULL, PRIMARY KEY(disease_config_id, variable_event_modifier_config_id))');
        $this->addSql('CREATE INDEX IDX_DA4CA24F1998F6F9 ON disease_config_variable_event_modifier_config (disease_config_id)');
        $this->addSql('CREATE INDEX IDX_DA4CA24F52CFB74C ON disease_config_variable_event_modifier_config (variable_event_modifier_config_id)');
        $this->addSql('CREATE TABLE disease_config_symptom_config (disease_config_id INT NOT NULL, symptom_config_id INT NOT NULL, PRIMARY KEY(disease_config_id, symptom_config_id))');
        $this->addSql('CREATE INDEX IDX_99AA55C81998F6F9 ON disease_config_symptom_config (disease_config_id)');
        $this->addSql('CREATE INDEX IDX_99AA55C89985AC9B ON disease_config_symptom_config (symptom_config_id)');
        $this->addSql('CREATE TABLE disease_consummable (id INT NOT NULL, daedalus_id INT DEFAULT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_B8FE2EE74B5A52D ON disease_consummable (daedalus_id)');
        $this->addSql('CREATE TABLE disease_consummable_attribute (id INT NOT NULL, consumable_disease_id INT DEFAULT NULL, consumable_disease_config_id INT DEFAULT NULL, disease VARCHAR(255) NOT NULL, type VARCHAR(255) NOT NULL, rate INT NOT NULL, delay_min INT NOT NULL, delay_length INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_21119C51491383B ON disease_consummable_attribute (consumable_disease_id)');
        $this->addSql('CREATE INDEX IDX_21119C58A8FEEED ON disease_consummable_attribute (consumable_disease_config_id)');
        $this->addSql('CREATE TABLE disease_consummable_config (id INT NOT NULL, name VARCHAR(255) NOT NULL, cause_name VARCHAR(255) NOT NULL, diseases_name TEXT NOT NULL, cures_name TEXT NOT NULL, diseases_chances TEXT NOT NULL, cures_chances TEXT NOT NULL, diseases_delay_min TEXT NOT NULL, diseases_delay_length TEXT NOT NULL, effect_number TEXT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_C11D0F7E5E237E06 ON disease_consummable_config (name)');
        $this->addSql('COMMENT ON COLUMN disease_consummable_config.diseases_name IS \'(DC2Type:array)\'');
        $this->addSql('COMMENT ON COLUMN disease_consummable_config.cures_name IS \'(DC2Type:array)\'');
        $this->addSql('COMMENT ON COLUMN disease_consummable_config.diseases_chances IS \'(DC2Type:array)\'');
        $this->addSql('COMMENT ON COLUMN disease_consummable_config.cures_chances IS \'(DC2Type:array)\'');
        $this->addSql('COMMENT ON COLUMN disease_consummable_config.diseases_delay_min IS \'(DC2Type:array)\'');
        $this->addSql('COMMENT ON COLUMN disease_consummable_config.diseases_delay_length IS \'(DC2Type:array)\'');
        $this->addSql('COMMENT ON COLUMN disease_consummable_config.effect_number IS \'(DC2Type:array)\'');
        $this->addSql('CREATE TABLE disease_player (id INT NOT NULL, disease_config_id INT DEFAULT NULL, player_id INT DEFAULT NULL, status VARCHAR(255) NOT NULL, disease_point INT NOT NULL, resistance_point INT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_2CBDBC241998F6F9 ON disease_player (disease_config_id)');
        $this->addSql('CREATE INDEX IDX_2CBDBC2499E6F5DF ON disease_player (player_id)');
        $this->addSql('CREATE TABLE equipment_config (id INT NOT NULL, name VARCHAR(255) NOT NULL, equipment_name VARCHAR(255) NOT NULL, is_breakable BOOLEAN NOT NULL, is_fire_destroyable BOOLEAN NOT NULL, is_fire_breakable BOOLEAN NOT NULL, dismounted_products TEXT NOT NULL, is_personal BOOLEAN NOT NULL, type VARCHAR(255) NOT NULL, is_stackable BOOLEAN DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_7304503C5E237E06 ON equipment_config (name)');
        $this->addSql('COMMENT ON COLUMN equipment_config.dismounted_products IS \'(DC2Type:array)\'');
        $this->addSql('CREATE TABLE equipment_config_equipment_mechanic (equipment_config_id INT NOT NULL, equipment_mechanic_id INT NOT NULL, PRIMARY KEY(equipment_config_id, equipment_mechanic_id))');
        $this->addSql('CREATE INDEX IDX_25B54CB4F6E640FA ON equipment_config_equipment_mechanic (equipment_config_id)');
        $this->addSql('CREATE INDEX IDX_25B54CB4FB252F27 ON equipment_config_equipment_mechanic (equipment_mechanic_id)');
        $this->addSql('CREATE TABLE equipment_config_action (equipment_config_id INT NOT NULL, action_id INT NOT NULL, PRIMARY KEY(equipment_config_id, action_id))');
        $this->addSql('CREATE INDEX IDX_51B80572F6E640FA ON equipment_config_action (equipment_config_id)');
        $this->addSql('CREATE INDEX IDX_51B805729D32F035 ON equipment_config_action (action_id)');
        $this->addSql('CREATE TABLE equipment_config_status_config (equipment_config_id INT NOT NULL, status_config_id INT NOT NULL, PRIMARY KEY(equipment_config_id, status_config_id))');
        $this->addSql('CREATE INDEX IDX_2AFF2A7AF6E640FA ON equipment_config_status_config (equipment_config_id)');
        $this->addSql('CREATE INDEX IDX_2AFF2A7AAC4E86C2 ON equipment_config_status_config (status_config_id)');
        $this->addSql('CREATE TABLE equipment_mechanic (id INT NOT NULL, name VARCHAR(255) NOT NULL, type VARCHAR(255) NOT NULL, crafted_equipment_name VARCHAR(255) DEFAULT NULL, ingredients TEXT DEFAULT NULL, skill VARCHAR(255) DEFAULT NULL, content VARCHAR(255) DEFAULT NULL, is_translated BOOLEAN DEFAULT NULL, can_shred BOOLEAN DEFAULT NULL, plant_name VARCHAR(255) DEFAULT NULL, fruit_name VARCHAR(255) DEFAULT NULL, maturation_time TEXT DEFAULT NULL, oxygen TEXT DEFAULT NULL, moral_points TEXT DEFAULT NULL, action_points TEXT DEFAULT NULL, movement_points TEXT DEFAULT NULL, health_points TEXT DEFAULT NULL, satiety INT DEFAULT NULL, extra_effects TEXT DEFAULT NULL, is_perishable BOOLEAN DEFAULT NULL, base_accuracy INT DEFAULT NULL, base_damage_range TEXT DEFAULT NULL, expedition_bonus INT DEFAULT NULL, critical_success_rate INT DEFAULT NULL, critical_fail_rate INT DEFAULT NULL, one_shot_rate INT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_41F45A5F5E237E06 ON equipment_mechanic (name)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_41F45A5F644C44CC ON equipment_mechanic (crafted_equipment_name)');
        $this->addSql('COMMENT ON COLUMN equipment_mechanic.ingredients IS \'(DC2Type:array)\'');
        $this->addSql('COMMENT ON COLUMN equipment_mechanic.maturation_time IS \'(DC2Type:array)\'');
        $this->addSql('COMMENT ON COLUMN equipment_mechanic.oxygen IS \'(DC2Type:array)\'');
        $this->addSql('COMMENT ON COLUMN equipment_mechanic.moral_points IS \'(DC2Type:array)\'');
        $this->addSql('COMMENT ON COLUMN equipment_mechanic.action_points IS \'(DC2Type:array)\'');
        $this->addSql('COMMENT ON COLUMN equipment_mechanic.movement_points IS \'(DC2Type:array)\'');
        $this->addSql('COMMENT ON COLUMN equipment_mechanic.health_points IS \'(DC2Type:array)\'');
        $this->addSql('COMMENT ON COLUMN equipment_mechanic.extra_effects IS \'(DC2Type:array)\'');
        $this->addSql('COMMENT ON COLUMN equipment_mechanic.base_damage_range IS \'(DC2Type:array)\'');
        $this->addSql('CREATE TABLE equipment_mechanic_action (equipment_mechanic_id INT NOT NULL, action_id INT NOT NULL, PRIMARY KEY(equipment_mechanic_id, action_id))');
        $this->addSql('CREATE INDEX IDX_586B101BFB252F27 ON equipment_mechanic_action (equipment_mechanic_id)');
        $this->addSql('CREATE INDEX IDX_586B101B9D32F035 ON equipment_mechanic_action (action_id)');
        $this->addSql('CREATE TABLE gear_abstract_modifier_config (gear_id INT NOT NULL, abstract_modifier_config_id INT NOT NULL, PRIMARY KEY(gear_id, abstract_modifier_config_id))');
        $this->addSql('CREATE INDEX IDX_FCA2C68877201934 ON gear_abstract_modifier_config (gear_id)');
        $this->addSql('CREATE INDEX IDX_FCA2C688BFA8DC8C ON gear_abstract_modifier_config (abstract_modifier_config_id)');
        $this->addSql('CREATE TABLE game_equipment (id INT NOT NULL, place_id INT DEFAULT NULL, equipment_id INT DEFAULT NULL, owner_id INT DEFAULT NULL, player_id INT DEFAULT NULL, name VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, type VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_19E1481DA6A219 ON game_equipment (place_id)');
        $this->addSql('CREATE INDEX IDX_19E1481517FE9FE ON game_equipment (equipment_id)');
        $this->addSql('CREATE INDEX IDX_19E14817E3C61F9 ON game_equipment (owner_id)');
        $this->addSql('CREATE INDEX IDX_19E148199E6F5DF ON game_equipment (player_id)');
        $this->addSql('CREATE TABLE door_place (door_id INT NOT NULL, place_id INT NOT NULL, PRIMARY KEY(door_id, place_id))');
        $this->addSql('CREATE INDEX IDX_8587EFEE58639EAE ON door_place (door_id)');
        $this->addSql('CREATE INDEX IDX_8587EFEEDA6A219 ON door_place (place_id)');
        $this->addSql('CREATE TABLE game_modifier (id INT NOT NULL, modifier_config_id INT DEFAULT NULL, player_id INT DEFAULT NULL, place_id INT DEFAULT NULL, game_equipment_id INT DEFAULT NULL, daedalus_id INT DEFAULT NULL, charge_id INT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_FB26DB7E2B144A ON game_modifier (modifier_config_id)');
        $this->addSql('CREATE INDEX IDX_FB26DB99E6F5DF ON game_modifier (player_id)');
        $this->addSql('CREATE INDEX IDX_FB26DBDA6A219 ON game_modifier (place_id)');
        $this->addSql('CREATE INDEX IDX_FB26DBBFAFDD90 ON game_modifier (game_equipment_id)');
        $this->addSql('CREATE INDEX IDX_FB26DB74B5A52D ON game_modifier (daedalus_id)');
        $this->addSql('CREATE INDEX IDX_FB26DB55284914 ON game_modifier (charge_id)');
        $this->addSql('CREATE TABLE game_variable (id INT NOT NULL, game_variable_collection_id INT DEFAULT NULL, name VARCHAR(255) NOT NULL, value INT NOT NULL, max_value INT DEFAULT NULL, min_value INT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_670978ABFB87ACC7 ON game_variable (game_variable_collection_id)');
        $this->addSql('CREATE TABLE game_variable_collection (id INT NOT NULL, type VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE message (id INT NOT NULL, author_id INT DEFAULT NULL, neron_id INT DEFAULT NULL, parent_id INT DEFAULT NULL, channel_id INT DEFAULT NULL, message VARCHAR(255) NOT NULL, translation_parameters TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_B6BD307FF675F31B ON message (author_id)');
        $this->addSql('CREATE INDEX IDX_B6BD307F66BCDEE6 ON message (neron_id)');
        $this->addSql('CREATE INDEX IDX_B6BD307F727ACA70 ON message (parent_id)');
        $this->addSql('CREATE INDEX IDX_B6BD307F72F5A1AA ON message (channel_id)');
        $this->addSql('COMMENT ON COLUMN message.translation_parameters IS \'(DC2Type:array)\'');
        $this->addSql('CREATE TABLE modifier_activation_requirement (id INT NOT NULL, name VARCHAR(255) NOT NULL, activation_requirement_name VARCHAR(255) NOT NULL, activation_requirement VARCHAR(255) DEFAULT NULL, value INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_50E450D65E237E06 ON modifier_activation_requirement (name)');
        $this->addSql('CREATE TABLE neron (id INT NOT NULL, is_inhibited BOOLEAN NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE news (id INT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, french_title VARCHAR(255) NOT NULL, french_content TEXT NOT NULL, english_title VARCHAR(255) DEFAULT NULL, english_content TEXT DEFAULT NULL, spanish_title VARCHAR(255) DEFAULT NULL, spanish_content TEXT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE place_config (id INT NOT NULL, name VARCHAR(255) NOT NULL, place_name VARCHAR(255) NOT NULL, type VARCHAR(255) NOT NULL, doors TEXT NOT NULL, items TEXT NOT NULL, equipments TEXT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_764428155E237E06 ON place_config (name)');
        $this->addSql('COMMENT ON COLUMN place_config.doors IS \'(DC2Type:array)\'');
        $this->addSql('COMMENT ON COLUMN place_config.items IS \'(DC2Type:array)\'');
        $this->addSql('COMMENT ON COLUMN place_config.equipments IS \'(DC2Type:array)\'');
        $this->addSql('CREATE TABLE plant_effect (id INT NOT NULL, daedalus_id INT DEFAULT NULL, plant_id INT DEFAULT NULL, maturation_time INT DEFAULT NULL, oxygen INT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_55F0407974B5A52D ON plant_effect (daedalus_id)');
        $this->addSql('CREATE INDEX IDX_55F040791D935652 ON plant_effect (plant_id)');
        $this->addSql('CREATE TABLE player (id INT NOT NULL, daedalus_id INT DEFAULT NULL, place_id INT DEFAULT NULL, player_variables_id INT DEFAULT NULL, skills TEXT DEFAULT NULL, triumph INT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_98197A6574B5A52D ON player (daedalus_id)');
        $this->addSql('CREATE INDEX IDX_98197A65DA6A219 ON player (place_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_98197A656DBF405E ON player (player_variables_id)');
        $this->addSql('COMMENT ON COLUMN player.skills IS \'(DC2Type:array)\'');
        $this->addSql('CREATE TABLE player_player_flirts (player_source INT NOT NULL, player_target INT NOT NULL, PRIMARY KEY(player_source, player_target))');
        $this->addSql('CREATE INDEX IDX_EA49A501C08AE9AD ON player_player_flirts (player_source)');
        $this->addSql('CREATE INDEX IDX_EA49A501D96FB922 ON player_player_flirts (player_target)');
        $this->addSql('CREATE TABLE player_info (id INT NOT NULL, player_id INT DEFAULT NULL, user_id INT DEFAULT NULL, character_config_id INT DEFAULT NULL, closed_player_id INT DEFAULT NULL, game_status VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_6993616499E6F5DF ON player_info (player_id)');
        $this->addSql('CREATE INDEX IDX_69936164A76ED395 ON player_info (user_id)');
        $this->addSql('CREATE INDEX IDX_69936164A38BA4B8 ON player_info (character_config_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_69936164418277A4 ON player_info (closed_player_id)');
        $this->addSql('CREATE TABLE room (id INT NOT NULL, daedalus_id INT DEFAULT NULL, name VARCHAR(255) NOT NULL, type VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_729F519B74B5A52D ON room (daedalus_id)');
        $this->addSql('CREATE TABLE place_door (place_id INT NOT NULL, door_id INT NOT NULL, PRIMARY KEY(place_id, door_id))');
        $this->addSql('CREATE INDEX IDX_405024C1DA6A219 ON place_door (place_id)');
        $this->addSql('CREATE INDEX IDX_405024C158639EAE ON place_door (door_id)');
        $this->addSql('CREATE TABLE room_log (id INT NOT NULL, daedalus_info_id INT DEFAULT NULL, player_info_id INT DEFAULT NULL, place VARCHAR(255) NOT NULL, visibility VARCHAR(255) NOT NULL, log VARCHAR(255) NOT NULL, parameters TEXT NOT NULL, type VARCHAR(255) NOT NULL, date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, day INT NOT NULL, cycle INT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_8DB9D5D840AC2F6A ON room_log (daedalus_info_id)');
        $this->addSql('CREATE INDEX IDX_8DB9D5D83C7F3EBD ON room_log (player_info_id)');
        $this->addSql('COMMENT ON COLUMN room_log.parameters IS \'(DC2Type:array)\'');
        $this->addSql('CREATE TABLE status (id INT NOT NULL, owner_id INT DEFAULT NULL, target_id INT DEFAULT NULL, status_config_id INT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, type VARCHAR(255) NOT NULL, charge INT DEFAULT NULL, action VARCHAR(255) DEFAULT NULL, content VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_7B00651C7E3C61F9 ON status (owner_id)');
        $this->addSql('CREATE INDEX IDX_7B00651C158E0B66 ON status (target_id)');
        $this->addSql('CREATE INDEX IDX_7B00651CAC4E86C2 ON status (status_config_id)');
        $this->addSql('CREATE TABLE status_config (id INT NOT NULL, name VARCHAR(255) NOT NULL, status_name VARCHAR(255) NOT NULL, visibility VARCHAR(255) NOT NULL, type VARCHAR(255) NOT NULL, charge_visibility VARCHAR(255) DEFAULT NULL, charge_strategy VARCHAR(255) DEFAULT NULL, max_charge INT DEFAULT NULL, start_charge INT DEFAULT NULL, discharge_strategy VARCHAR(255) DEFAULT NULL, auto_remove BOOLEAN DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_69C087315E237E06 ON status_config (name)');
        $this->addSql('CREATE TABLE status_config_variable_event_modifier_config (status_config_id INT NOT NULL, variable_event_modifier_config_id INT NOT NULL, PRIMARY KEY(status_config_id, variable_event_modifier_config_id))');
        $this->addSql('CREATE INDEX IDX_A055C203AC4E86C2 ON status_config_variable_event_modifier_config (status_config_id)');
        $this->addSql('CREATE INDEX IDX_A055C20352CFB74C ON status_config_variable_event_modifier_config (variable_event_modifier_config_id)');
        $this->addSql('CREATE TABLE status_target (id INT NOT NULL, player_id INT DEFAULT NULL, game_equipment_id INT DEFAULT NULL, place_id INT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_FB2587B199E6F5DF ON status_target (player_id)');
        $this->addSql('CREATE INDEX IDX_FB2587B1BFAFDD90 ON status_target (game_equipment_id)');
        $this->addSql('CREATE INDEX IDX_FB2587B1DA6A219 ON status_target (place_id)');
        $this->addSql('CREATE TABLE symptom_activation_requirement (id INT NOT NULL, name VARCHAR(255) NOT NULL, activation_requirement_name VARCHAR(255) NOT NULL, activation_requirement VARCHAR(255) DEFAULT NULL, value INT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_204533695E237E06 ON symptom_activation_requirement (name)');
        $this->addSql('CREATE TABLE symptom_config (id INT NOT NULL, name VARCHAR(255) NOT NULL, symptom_name VARCHAR(255) NOT NULL, trigger VARCHAR(255) DEFAULT NULL, visibility VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_B5486F5C5E237E06 ON symptom_config (name)');
        $this->addSql('CREATE TABLE symptom_config_symptom_activation_requirement (symptom_config_id INT NOT NULL, symptom_activation_requirement_id INT NOT NULL, PRIMARY KEY(symptom_config_id, symptom_activation_requirement_id))');
        $this->addSql('CREATE INDEX IDX_63CAF879985AC9B ON symptom_config_symptom_activation_requirement (symptom_config_id)');
        $this->addSql('CREATE INDEX IDX_63CAF87D39AE590 ON symptom_config_symptom_activation_requirement (symptom_activation_requirement_id)');
        $this->addSql('CREATE TABLE triumph_config (id INT NOT NULL, name VARCHAR(255) NOT NULL, triumph INT NOT NULL, is_all_crew BOOLEAN NOT NULL, team VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_A53FC4E45E237E06 ON triumph_config (name)');
        $this->addSql('CREATE TABLE users (id INT NOT NULL, user_id VARCHAR(255) NOT NULL, username VARCHAR(255) NOT NULL, is_in_game BOOLEAN NOT NULL, nonce_code VARCHAR(255) DEFAULT NULL, nonce_expiry_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, roles TEXT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_1483A5E9A76ED395 ON users (user_id)');
        $this->addSql('COMMENT ON COLUMN users.roles IS \'(DC2Type:array)\'');
        $this->addSql('ALTER TABLE abstract_modifier_config_modifier_activation_requirement ADD CONSTRAINT FK_E2ECCA99BFA8DC8C FOREIGN KEY (abstract_modifier_config_id) REFERENCES abstract_modifier_config (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE abstract_modifier_config_modifier_activation_requirement ADD CONSTRAINT FK_E2ECCA99F299F7D7 FOREIGN KEY (modifier_activation_requirement_id) REFERENCES modifier_activation_requirement (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE action ADD CONSTRAINT FK_47CC8C9271F0C45C FOREIGN KEY (action_variables_id) REFERENCES game_variable_collection (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE alert ADD CONSTRAINT FK_17FD46C174B5A52D FOREIGN KEY (daedalus_id) REFERENCES daedalus (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE alert_element ADD CONSTRAINT FK_DF13F9FB93035F72 FOREIGN KEY (alert_id) REFERENCES alert (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE alert_element ADD CONSTRAINT FK_DF13F9FB3C7F3EBD FOREIGN KEY (player_info_id) REFERENCES player_info (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE alert_element ADD CONSTRAINT FK_DF13F9FBDA6A219 FOREIGN KEY (place_id) REFERENCES room (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE alert_element ADD CONSTRAINT FK_DF13F9FB517FE9FE FOREIGN KEY (equipment_id) REFERENCES game_equipment (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE character_config_status_config ADD CONSTRAINT FK_2A38BC0EA38BA4B8 FOREIGN KEY (character_config_id) REFERENCES character_config (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE character_config_status_config ADD CONSTRAINT FK_2A38BC0EAC4E86C2 FOREIGN KEY (status_config_id) REFERENCES status_config (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE character_config_action ADD CONSTRAINT FK_51C5D29A38BA4B8 FOREIGN KEY (character_config_id) REFERENCES character_config (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE character_config_action ADD CONSTRAINT FK_51C5D299D32F035 FOREIGN KEY (action_id) REFERENCES action (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE character_config_item_config ADD CONSTRAINT FK_E44AA5FDA38BA4B8 FOREIGN KEY (character_config_id) REFERENCES character_config (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE character_config_item_config ADD CONSTRAINT FK_E44AA5FD28011073 FOREIGN KEY (item_config_id) REFERENCES equipment_config (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE character_config_disease_config ADD CONSTRAINT FK_D60B3C3BA38BA4B8 FOREIGN KEY (character_config_id) REFERENCES character_config (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE character_config_disease_config ADD CONSTRAINT FK_D60B3C3B1998F6F9 FOREIGN KEY (disease_config_id) REFERENCES disease_config (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE closed_player ADD CONSTRAINT FK_F154A5CC74B5A52D FOREIGN KEY (daedalus_id) REFERENCES daedalus_closed (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE communication_channel ADD CONSTRAINT FK_D728A71D40AC2F6A FOREIGN KEY (daedalus_info_id) REFERENCES daedalus_info (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE communication_channel_player ADD CONSTRAINT FK_2908A45B72F5A1AA FOREIGN KEY (channel_id) REFERENCES communication_channel (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE communication_channel_player ADD CONSTRAINT FK_2908A45B9D1C3019 FOREIGN KEY (participant_id) REFERENCES player_info (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE config_daedalus ADD CONSTRAINT FK_CC1298D4D5F7B64E FOREIGN KEY (random_item_places_id) REFERENCES config_random_item_place (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE daedalus_config_place_config ADD CONSTRAINT FK_A0E9A0CF201E3C43 FOREIGN KEY (daedalus_config_id) REFERENCES config_daedalus (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE daedalus_config_place_config ADD CONSTRAINT FK_A0E9A0CF50408FFE FOREIGN KEY (place_config_id) REFERENCES place_config (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE config_game ADD CONSTRAINT FK_B38B6D7C201E3C43 FOREIGN KEY (daedalus_config_id) REFERENCES config_daedalus (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE config_game ADD CONSTRAINT FK_B38B6D7C838718A0 FOREIGN KEY (difficulty_config_id) REFERENCES config_difficulty (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE game_config_character_config ADD CONSTRAINT FK_C3CBECE1F67DC781 FOREIGN KEY (game_config_id) REFERENCES config_game (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE game_config_character_config ADD CONSTRAINT FK_C3CBECE1A38BA4B8 FOREIGN KEY (character_config_id) REFERENCES character_config (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE game_config_equipment_config ADD CONSTRAINT FK_C7075032F67DC781 FOREIGN KEY (game_config_id) REFERENCES config_game (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE game_config_equipment_config ADD CONSTRAINT FK_C7075032F6E640FA FOREIGN KEY (equipment_config_id) REFERENCES equipment_config (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE game_config_status_config ADD CONSTRAINT FK_BBE53156F67DC781 FOREIGN KEY (game_config_id) REFERENCES config_game (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE game_config_status_config ADD CONSTRAINT FK_BBE53156AC4E86C2 FOREIGN KEY (status_config_id) REFERENCES status_config (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE game_config_triumph_config ADD CONSTRAINT FK_763B15A9F67DC781 FOREIGN KEY (game_config_id) REFERENCES config_game (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE game_config_triumph_config ADD CONSTRAINT FK_763B15A9D15A829E FOREIGN KEY (triumph_config_id) REFERENCES triumph_config (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE game_config_disease_cause_config ADD CONSTRAINT FK_E12276B4F67DC781 FOREIGN KEY (game_config_id) REFERENCES config_game (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE game_config_disease_cause_config ADD CONSTRAINT FK_E12276B48D9CD4C9 FOREIGN KEY (disease_cause_config_id) REFERENCES disease_cause_config (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE game_config_disease_config ADD CONSTRAINT FK_B32A3870F67DC781 FOREIGN KEY (game_config_id) REFERENCES config_game (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE game_config_disease_config ADD CONSTRAINT FK_B32A38701998F6F9 FOREIGN KEY (disease_config_id) REFERENCES disease_config (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE game_config_consumable_disease_config ADD CONSTRAINT FK_E6EA1EF67DC781 FOREIGN KEY (game_config_id) REFERENCES config_game (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE game_config_consumable_disease_config ADD CONSTRAINT FK_E6EA1E8A8FEEED FOREIGN KEY (consumable_disease_config_id) REFERENCES disease_consummable_config (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE consumable_effect ADD CONSTRAINT FK_C275962674B5A52D FOREIGN KEY (daedalus_id) REFERENCES daedalus (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE consumable_effect ADD CONSTRAINT FK_C27596264A5A89FC FOREIGN KEY (ration_id) REFERENCES equipment_mechanic (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE daedalus ADD CONSTRAINT FK_71DA760AB28A6E7E FOREIGN KEY (daedalus_variables_id) REFERENCES game_variable_collection (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE daedalus_closed ADD CONSTRAINT FK_9439BBF440AC2F6A FOREIGN KEY (daedalus_info_id) REFERENCES daedalus_info (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE daedalus_info ADD CONSTRAINT FK_24725EFCF67DC781 FOREIGN KEY (game_config_id) REFERENCES config_game (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE daedalus_info ADD CONSTRAINT FK_24725EFC74B5A52D FOREIGN KEY (daedalus_id) REFERENCES daedalus (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE daedalus_info ADD CONSTRAINT FK_24725EFCBBC83F78 FOREIGN KEY (closed_daedalus_id) REFERENCES daedalus_closed (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE daedalus_info ADD CONSTRAINT FK_24725EFC66BCDEE6 FOREIGN KEY (neron_id) REFERENCES neron (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE daedalus_info ADD CONSTRAINT FK_24725EFC8D986DA0 FOREIGN KEY (localization_config_id) REFERENCES config_localization (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE disease_config_variable_event_modifier_config ADD CONSTRAINT FK_DA4CA24F1998F6F9 FOREIGN KEY (disease_config_id) REFERENCES disease_config (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE disease_config_variable_event_modifier_config ADD CONSTRAINT FK_DA4CA24F52CFB74C FOREIGN KEY (variable_event_modifier_config_id) REFERENCES abstract_modifier_config (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE disease_config_symptom_config ADD CONSTRAINT FK_99AA55C81998F6F9 FOREIGN KEY (disease_config_id) REFERENCES disease_config (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE disease_config_symptom_config ADD CONSTRAINT FK_99AA55C89985AC9B FOREIGN KEY (symptom_config_id) REFERENCES symptom_config (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE disease_consummable ADD CONSTRAINT FK_B8FE2EE74B5A52D FOREIGN KEY (daedalus_id) REFERENCES daedalus (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE disease_consummable_attribute ADD CONSTRAINT FK_21119C51491383B FOREIGN KEY (consumable_disease_id) REFERENCES disease_consummable (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE disease_consummable_attribute ADD CONSTRAINT FK_21119C58A8FEEED FOREIGN KEY (consumable_disease_config_id) REFERENCES disease_consummable_config (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE disease_player ADD CONSTRAINT FK_2CBDBC241998F6F9 FOREIGN KEY (disease_config_id) REFERENCES disease_config (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE disease_player ADD CONSTRAINT FK_2CBDBC2499E6F5DF FOREIGN KEY (player_id) REFERENCES player (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE equipment_config_equipment_mechanic ADD CONSTRAINT FK_25B54CB4F6E640FA FOREIGN KEY (equipment_config_id) REFERENCES equipment_config (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE equipment_config_equipment_mechanic ADD CONSTRAINT FK_25B54CB4FB252F27 FOREIGN KEY (equipment_mechanic_id) REFERENCES equipment_mechanic (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE equipment_config_action ADD CONSTRAINT FK_51B80572F6E640FA FOREIGN KEY (equipment_config_id) REFERENCES equipment_config (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE equipment_config_action ADD CONSTRAINT FK_51B805729D32F035 FOREIGN KEY (action_id) REFERENCES action (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE equipment_config_status_config ADD CONSTRAINT FK_2AFF2A7AF6E640FA FOREIGN KEY (equipment_config_id) REFERENCES equipment_config (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE equipment_config_status_config ADD CONSTRAINT FK_2AFF2A7AAC4E86C2 FOREIGN KEY (status_config_id) REFERENCES status_config (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE equipment_mechanic_action ADD CONSTRAINT FK_586B101BFB252F27 FOREIGN KEY (equipment_mechanic_id) REFERENCES equipment_mechanic (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE equipment_mechanic_action ADD CONSTRAINT FK_586B101B9D32F035 FOREIGN KEY (action_id) REFERENCES action (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE gear_abstract_modifier_config ADD CONSTRAINT FK_FCA2C68877201934 FOREIGN KEY (gear_id) REFERENCES equipment_mechanic (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE gear_abstract_modifier_config ADD CONSTRAINT FK_FCA2C688BFA8DC8C FOREIGN KEY (abstract_modifier_config_id) REFERENCES abstract_modifier_config (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE game_equipment ADD CONSTRAINT FK_19E1481DA6A219 FOREIGN KEY (place_id) REFERENCES room (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE game_equipment ADD CONSTRAINT FK_19E1481517FE9FE FOREIGN KEY (equipment_id) REFERENCES equipment_config (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE game_equipment ADD CONSTRAINT FK_19E14817E3C61F9 FOREIGN KEY (owner_id) REFERENCES player (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE game_equipment ADD CONSTRAINT FK_19E148199E6F5DF FOREIGN KEY (player_id) REFERENCES player (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE door_place ADD CONSTRAINT FK_8587EFEE58639EAE FOREIGN KEY (door_id) REFERENCES game_equipment (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE door_place ADD CONSTRAINT FK_8587EFEEDA6A219 FOREIGN KEY (place_id) REFERENCES room (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE game_modifier ADD CONSTRAINT FK_FB26DB7E2B144A FOREIGN KEY (modifier_config_id) REFERENCES abstract_modifier_config (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE game_modifier ADD CONSTRAINT FK_FB26DB99E6F5DF FOREIGN KEY (player_id) REFERENCES player (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE game_modifier ADD CONSTRAINT FK_FB26DBDA6A219 FOREIGN KEY (place_id) REFERENCES room (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE game_modifier ADD CONSTRAINT FK_FB26DBBFAFDD90 FOREIGN KEY (game_equipment_id) REFERENCES game_equipment (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE game_modifier ADD CONSTRAINT FK_FB26DB74B5A52D FOREIGN KEY (daedalus_id) REFERENCES daedalus (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE game_modifier ADD CONSTRAINT FK_FB26DB55284914 FOREIGN KEY (charge_id) REFERENCES status (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE game_variable ADD CONSTRAINT FK_670978ABFB87ACC7 FOREIGN KEY (game_variable_collection_id) REFERENCES game_variable_collection (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE message ADD CONSTRAINT FK_B6BD307FF675F31B FOREIGN KEY (author_id) REFERENCES player_info (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE message ADD CONSTRAINT FK_B6BD307F66BCDEE6 FOREIGN KEY (neron_id) REFERENCES neron (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE message ADD CONSTRAINT FK_B6BD307F727ACA70 FOREIGN KEY (parent_id) REFERENCES message (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE message ADD CONSTRAINT FK_B6BD307F72F5A1AA FOREIGN KEY (channel_id) REFERENCES communication_channel (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE plant_effect ADD CONSTRAINT FK_55F0407974B5A52D FOREIGN KEY (daedalus_id) REFERENCES daedalus (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE plant_effect ADD CONSTRAINT FK_55F040791D935652 FOREIGN KEY (plant_id) REFERENCES equipment_mechanic (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE player ADD CONSTRAINT FK_98197A6574B5A52D FOREIGN KEY (daedalus_id) REFERENCES daedalus (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE player ADD CONSTRAINT FK_98197A65DA6A219 FOREIGN KEY (place_id) REFERENCES room (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE player ADD CONSTRAINT FK_98197A656DBF405E FOREIGN KEY (player_variables_id) REFERENCES game_variable_collection (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE player_player_flirts ADD CONSTRAINT FK_EA49A501C08AE9AD FOREIGN KEY (player_source) REFERENCES player (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE player_player_flirts ADD CONSTRAINT FK_EA49A501D96FB922 FOREIGN KEY (player_target) REFERENCES player (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE player_info ADD CONSTRAINT FK_6993616499E6F5DF FOREIGN KEY (player_id) REFERENCES player (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE player_info ADD CONSTRAINT FK_69936164A76ED395 FOREIGN KEY (user_id) REFERENCES users (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE player_info ADD CONSTRAINT FK_69936164A38BA4B8 FOREIGN KEY (character_config_id) REFERENCES character_config (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE player_info ADD CONSTRAINT FK_69936164418277A4 FOREIGN KEY (closed_player_id) REFERENCES closed_player (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE room ADD CONSTRAINT FK_729F519B74B5A52D FOREIGN KEY (daedalus_id) REFERENCES daedalus (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE place_door ADD CONSTRAINT FK_405024C1DA6A219 FOREIGN KEY (place_id) REFERENCES room (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE place_door ADD CONSTRAINT FK_405024C158639EAE FOREIGN KEY (door_id) REFERENCES game_equipment (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE room_log ADD CONSTRAINT FK_8DB9D5D840AC2F6A FOREIGN KEY (daedalus_info_id) REFERENCES daedalus_info (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE room_log ADD CONSTRAINT FK_8DB9D5D83C7F3EBD FOREIGN KEY (player_info_id) REFERENCES player_info (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE status ADD CONSTRAINT FK_7B00651C7E3C61F9 FOREIGN KEY (owner_id) REFERENCES status_target (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE status ADD CONSTRAINT FK_7B00651C158E0B66 FOREIGN KEY (target_id) REFERENCES status_target (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE status ADD CONSTRAINT FK_7B00651CAC4E86C2 FOREIGN KEY (status_config_id) REFERENCES status_config (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE status_config_variable_event_modifier_config ADD CONSTRAINT FK_A055C203AC4E86C2 FOREIGN KEY (status_config_id) REFERENCES status_config (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE status_config_variable_event_modifier_config ADD CONSTRAINT FK_A055C20352CFB74C FOREIGN KEY (variable_event_modifier_config_id) REFERENCES abstract_modifier_config (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE status_target ADD CONSTRAINT FK_FB2587B199E6F5DF FOREIGN KEY (player_id) REFERENCES player (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE status_target ADD CONSTRAINT FK_FB2587B1BFAFDD90 FOREIGN KEY (game_equipment_id) REFERENCES game_equipment (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE status_target ADD CONSTRAINT FK_FB2587B1DA6A219 FOREIGN KEY (place_id) REFERENCES room (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE symptom_config_symptom_activation_requirement ADD CONSTRAINT FK_63CAF879985AC9B FOREIGN KEY (symptom_config_id) REFERENCES symptom_config (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE symptom_config_symptom_activation_requirement ADD CONSTRAINT FK_63CAF87D39AE590 FOREIGN KEY (symptom_activation_requirement_id) REFERENCES symptom_activation_requirement (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE SCHEMA public');
        $this->addSql('DROP SEQUENCE abstract_modifier_config_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE action_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE alert_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE alert_element_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE character_config_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE closed_player_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE communication_channel_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE communication_channel_player_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE config_daedalus_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE config_difficulty_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE config_game_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE config_localization_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE config_random_item_place_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE consumable_effect_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE daedalus_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE daedalus_closed_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE daedalus_info_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE disease_cause_config_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE disease_config_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE disease_consummable_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE disease_consummable_attribute_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE disease_consummable_config_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE disease_player_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE equipment_config_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE equipment_mechanic_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE game_equipment_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE game_modifier_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE game_variable_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE game_variable_collection_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE message_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE modifier_activation_requirement_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE neron_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE news_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE place_config_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE plant_effect_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE player_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE player_info_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE room_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE room_log_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE status_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE status_config_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE status_target_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE symptom_activation_requirement_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE symptom_config_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE triumph_config_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE users_id_seq CASCADE');
        $this->addSql('ALTER TABLE abstract_modifier_config_modifier_activation_requirement DROP CONSTRAINT FK_E2ECCA99BFA8DC8C');
        $this->addSql('ALTER TABLE abstract_modifier_config_modifier_activation_requirement DROP CONSTRAINT FK_E2ECCA99F299F7D7');
        $this->addSql('ALTER TABLE action DROP CONSTRAINT FK_47CC8C9271F0C45C');
        $this->addSql('ALTER TABLE alert DROP CONSTRAINT FK_17FD46C174B5A52D');
        $this->addSql('ALTER TABLE alert_element DROP CONSTRAINT FK_DF13F9FB93035F72');
        $this->addSql('ALTER TABLE alert_element DROP CONSTRAINT FK_DF13F9FB3C7F3EBD');
        $this->addSql('ALTER TABLE alert_element DROP CONSTRAINT FK_DF13F9FBDA6A219');
        $this->addSql('ALTER TABLE alert_element DROP CONSTRAINT FK_DF13F9FB517FE9FE');
        $this->addSql('ALTER TABLE character_config_status_config DROP CONSTRAINT FK_2A38BC0EA38BA4B8');
        $this->addSql('ALTER TABLE character_config_status_config DROP CONSTRAINT FK_2A38BC0EAC4E86C2');
        $this->addSql('ALTER TABLE character_config_action DROP CONSTRAINT FK_51C5D29A38BA4B8');
        $this->addSql('ALTER TABLE character_config_action DROP CONSTRAINT FK_51C5D299D32F035');
        $this->addSql('ALTER TABLE character_config_item_config DROP CONSTRAINT FK_E44AA5FDA38BA4B8');
        $this->addSql('ALTER TABLE character_config_item_config DROP CONSTRAINT FK_E44AA5FD28011073');
        $this->addSql('ALTER TABLE character_config_disease_config DROP CONSTRAINT FK_D60B3C3BA38BA4B8');
        $this->addSql('ALTER TABLE character_config_disease_config DROP CONSTRAINT FK_D60B3C3B1998F6F9');
        $this->addSql('ALTER TABLE closed_player DROP CONSTRAINT FK_F154A5CC74B5A52D');
        $this->addSql('ALTER TABLE communication_channel DROP CONSTRAINT FK_D728A71D40AC2F6A');
        $this->addSql('ALTER TABLE communication_channel_player DROP CONSTRAINT FK_2908A45B72F5A1AA');
        $this->addSql('ALTER TABLE communication_channel_player DROP CONSTRAINT FK_2908A45B9D1C3019');
        $this->addSql('ALTER TABLE config_daedalus DROP CONSTRAINT FK_CC1298D4D5F7B64E');
        $this->addSql('ALTER TABLE daedalus_config_place_config DROP CONSTRAINT FK_A0E9A0CF201E3C43');
        $this->addSql('ALTER TABLE daedalus_config_place_config DROP CONSTRAINT FK_A0E9A0CF50408FFE');
        $this->addSql('ALTER TABLE config_game DROP CONSTRAINT FK_B38B6D7C201E3C43');
        $this->addSql('ALTER TABLE config_game DROP CONSTRAINT FK_B38B6D7C838718A0');
        $this->addSql('ALTER TABLE game_config_character_config DROP CONSTRAINT FK_C3CBECE1F67DC781');
        $this->addSql('ALTER TABLE game_config_character_config DROP CONSTRAINT FK_C3CBECE1A38BA4B8');
        $this->addSql('ALTER TABLE game_config_equipment_config DROP CONSTRAINT FK_C7075032F67DC781');
        $this->addSql('ALTER TABLE game_config_equipment_config DROP CONSTRAINT FK_C7075032F6E640FA');
        $this->addSql('ALTER TABLE game_config_status_config DROP CONSTRAINT FK_BBE53156F67DC781');
        $this->addSql('ALTER TABLE game_config_status_config DROP CONSTRAINT FK_BBE53156AC4E86C2');
        $this->addSql('ALTER TABLE game_config_triumph_config DROP CONSTRAINT FK_763B15A9F67DC781');
        $this->addSql('ALTER TABLE game_config_triumph_config DROP CONSTRAINT FK_763B15A9D15A829E');
        $this->addSql('ALTER TABLE game_config_disease_cause_config DROP CONSTRAINT FK_E12276B4F67DC781');
        $this->addSql('ALTER TABLE game_config_disease_cause_config DROP CONSTRAINT FK_E12276B48D9CD4C9');
        $this->addSql('ALTER TABLE game_config_disease_config DROP CONSTRAINT FK_B32A3870F67DC781');
        $this->addSql('ALTER TABLE game_config_disease_config DROP CONSTRAINT FK_B32A38701998F6F9');
        $this->addSql('ALTER TABLE game_config_consumable_disease_config DROP CONSTRAINT FK_E6EA1EF67DC781');
        $this->addSql('ALTER TABLE game_config_consumable_disease_config DROP CONSTRAINT FK_E6EA1E8A8FEEED');
        $this->addSql('ALTER TABLE consumable_effect DROP CONSTRAINT FK_C275962674B5A52D');
        $this->addSql('ALTER TABLE consumable_effect DROP CONSTRAINT FK_C27596264A5A89FC');
        $this->addSql('ALTER TABLE daedalus DROP CONSTRAINT FK_71DA760AB28A6E7E');
        $this->addSql('ALTER TABLE daedalus_closed DROP CONSTRAINT FK_9439BBF440AC2F6A');
        $this->addSql('ALTER TABLE daedalus_info DROP CONSTRAINT FK_24725EFCF67DC781');
        $this->addSql('ALTER TABLE daedalus_info DROP CONSTRAINT FK_24725EFC74B5A52D');
        $this->addSql('ALTER TABLE daedalus_info DROP CONSTRAINT FK_24725EFCBBC83F78');
        $this->addSql('ALTER TABLE daedalus_info DROP CONSTRAINT FK_24725EFC66BCDEE6');
        $this->addSql('ALTER TABLE daedalus_info DROP CONSTRAINT FK_24725EFC8D986DA0');
        $this->addSql('ALTER TABLE disease_config_variable_event_modifier_config DROP CONSTRAINT FK_DA4CA24F1998F6F9');
        $this->addSql('ALTER TABLE disease_config_variable_event_modifier_config DROP CONSTRAINT FK_DA4CA24F52CFB74C');
        $this->addSql('ALTER TABLE disease_config_symptom_config DROP CONSTRAINT FK_99AA55C81998F6F9');
        $this->addSql('ALTER TABLE disease_config_symptom_config DROP CONSTRAINT FK_99AA55C89985AC9B');
        $this->addSql('ALTER TABLE disease_consummable DROP CONSTRAINT FK_B8FE2EE74B5A52D');
        $this->addSql('ALTER TABLE disease_consummable_attribute DROP CONSTRAINT FK_21119C51491383B');
        $this->addSql('ALTER TABLE disease_consummable_attribute DROP CONSTRAINT FK_21119C58A8FEEED');
        $this->addSql('ALTER TABLE disease_player DROP CONSTRAINT FK_2CBDBC241998F6F9');
        $this->addSql('ALTER TABLE disease_player DROP CONSTRAINT FK_2CBDBC2499E6F5DF');
        $this->addSql('ALTER TABLE equipment_config_equipment_mechanic DROP CONSTRAINT FK_25B54CB4F6E640FA');
        $this->addSql('ALTER TABLE equipment_config_equipment_mechanic DROP CONSTRAINT FK_25B54CB4FB252F27');
        $this->addSql('ALTER TABLE equipment_config_action DROP CONSTRAINT FK_51B80572F6E640FA');
        $this->addSql('ALTER TABLE equipment_config_action DROP CONSTRAINT FK_51B805729D32F035');
        $this->addSql('ALTER TABLE equipment_config_status_config DROP CONSTRAINT FK_2AFF2A7AF6E640FA');
        $this->addSql('ALTER TABLE equipment_config_status_config DROP CONSTRAINT FK_2AFF2A7AAC4E86C2');
        $this->addSql('ALTER TABLE equipment_mechanic_action DROP CONSTRAINT FK_586B101BFB252F27');
        $this->addSql('ALTER TABLE equipment_mechanic_action DROP CONSTRAINT FK_586B101B9D32F035');
        $this->addSql('ALTER TABLE gear_abstract_modifier_config DROP CONSTRAINT FK_FCA2C68877201934');
        $this->addSql('ALTER TABLE gear_abstract_modifier_config DROP CONSTRAINT FK_FCA2C688BFA8DC8C');
        $this->addSql('ALTER TABLE game_equipment DROP CONSTRAINT FK_19E1481DA6A219');
        $this->addSql('ALTER TABLE game_equipment DROP CONSTRAINT FK_19E1481517FE9FE');
        $this->addSql('ALTER TABLE game_equipment DROP CONSTRAINT FK_19E14817E3C61F9');
        $this->addSql('ALTER TABLE game_equipment DROP CONSTRAINT FK_19E148199E6F5DF');
        $this->addSql('ALTER TABLE door_place DROP CONSTRAINT FK_8587EFEE58639EAE');
        $this->addSql('ALTER TABLE door_place DROP CONSTRAINT FK_8587EFEEDA6A219');
        $this->addSql('ALTER TABLE game_modifier DROP CONSTRAINT FK_FB26DB7E2B144A');
        $this->addSql('ALTER TABLE game_modifier DROP CONSTRAINT FK_FB26DB99E6F5DF');
        $this->addSql('ALTER TABLE game_modifier DROP CONSTRAINT FK_FB26DBDA6A219');
        $this->addSql('ALTER TABLE game_modifier DROP CONSTRAINT FK_FB26DBBFAFDD90');
        $this->addSql('ALTER TABLE game_modifier DROP CONSTRAINT FK_FB26DB74B5A52D');
        $this->addSql('ALTER TABLE game_modifier DROP CONSTRAINT FK_FB26DB55284914');
        $this->addSql('ALTER TABLE game_variable DROP CONSTRAINT FK_670978ABFB87ACC7');
        $this->addSql('ALTER TABLE message DROP CONSTRAINT FK_B6BD307FF675F31B');
        $this->addSql('ALTER TABLE message DROP CONSTRAINT FK_B6BD307F66BCDEE6');
        $this->addSql('ALTER TABLE message DROP CONSTRAINT FK_B6BD307F727ACA70');
        $this->addSql('ALTER TABLE message DROP CONSTRAINT FK_B6BD307F72F5A1AA');
        $this->addSql('ALTER TABLE plant_effect DROP CONSTRAINT FK_55F0407974B5A52D');
        $this->addSql('ALTER TABLE plant_effect DROP CONSTRAINT FK_55F040791D935652');
        $this->addSql('ALTER TABLE player DROP CONSTRAINT FK_98197A6574B5A52D');
        $this->addSql('ALTER TABLE player DROP CONSTRAINT FK_98197A65DA6A219');
        $this->addSql('ALTER TABLE player DROP CONSTRAINT FK_98197A656DBF405E');
        $this->addSql('ALTER TABLE player_player_flirts DROP CONSTRAINT FK_EA49A501C08AE9AD');
        $this->addSql('ALTER TABLE player_player_flirts DROP CONSTRAINT FK_EA49A501D96FB922');
        $this->addSql('ALTER TABLE player_info DROP CONSTRAINT FK_6993616499E6F5DF');
        $this->addSql('ALTER TABLE player_info DROP CONSTRAINT FK_69936164A76ED395');
        $this->addSql('ALTER TABLE player_info DROP CONSTRAINT FK_69936164A38BA4B8');
        $this->addSql('ALTER TABLE player_info DROP CONSTRAINT FK_69936164418277A4');
        $this->addSql('ALTER TABLE room DROP CONSTRAINT FK_729F519B74B5A52D');
        $this->addSql('ALTER TABLE place_door DROP CONSTRAINT FK_405024C1DA6A219');
        $this->addSql('ALTER TABLE place_door DROP CONSTRAINT FK_405024C158639EAE');
        $this->addSql('ALTER TABLE room_log DROP CONSTRAINT FK_8DB9D5D840AC2F6A');
        $this->addSql('ALTER TABLE room_log DROP CONSTRAINT FK_8DB9D5D83C7F3EBD');
        $this->addSql('ALTER TABLE status DROP CONSTRAINT FK_7B00651C7E3C61F9');
        $this->addSql('ALTER TABLE status DROP CONSTRAINT FK_7B00651C158E0B66');
        $this->addSql('ALTER TABLE status DROP CONSTRAINT FK_7B00651CAC4E86C2');
        $this->addSql('ALTER TABLE status_config_variable_event_modifier_config DROP CONSTRAINT FK_A055C203AC4E86C2');
        $this->addSql('ALTER TABLE status_config_variable_event_modifier_config DROP CONSTRAINT FK_A055C20352CFB74C');
        $this->addSql('ALTER TABLE status_target DROP CONSTRAINT FK_FB2587B199E6F5DF');
        $this->addSql('ALTER TABLE status_target DROP CONSTRAINT FK_FB2587B1BFAFDD90');
        $this->addSql('ALTER TABLE status_target DROP CONSTRAINT FK_FB2587B1DA6A219');
        $this->addSql('ALTER TABLE symptom_config_symptom_activation_requirement DROP CONSTRAINT FK_63CAF879985AC9B');
        $this->addSql('ALTER TABLE symptom_config_symptom_activation_requirement DROP CONSTRAINT FK_63CAF87D39AE590');
        $this->addSql('DROP TABLE abstract_modifier_config');
        $this->addSql('DROP TABLE abstract_modifier_config_modifier_activation_requirement');
        $this->addSql('DROP TABLE action');
        $this->addSql('DROP TABLE alert');
        $this->addSql('DROP TABLE alert_element');
        $this->addSql('DROP TABLE character_config');
        $this->addSql('DROP TABLE character_config_status_config');
        $this->addSql('DROP TABLE character_config_action');
        $this->addSql('DROP TABLE character_config_item_config');
        $this->addSql('DROP TABLE character_config_disease_config');
        $this->addSql('DROP TABLE closed_player');
        $this->addSql('DROP TABLE communication_channel');
        $this->addSql('DROP TABLE communication_channel_player');
        $this->addSql('DROP TABLE config_daedalus');
        $this->addSql('DROP TABLE daedalus_config_place_config');
        $this->addSql('DROP TABLE config_difficulty');
        $this->addSql('DROP TABLE config_game');
        $this->addSql('DROP TABLE game_config_character_config');
        $this->addSql('DROP TABLE game_config_equipment_config');
        $this->addSql('DROP TABLE game_config_status_config');
        $this->addSql('DROP TABLE game_config_triumph_config');
        $this->addSql('DROP TABLE game_config_disease_cause_config');
        $this->addSql('DROP TABLE game_config_disease_config');
        $this->addSql('DROP TABLE game_config_consumable_disease_config');
        $this->addSql('DROP TABLE config_localization');
        $this->addSql('DROP TABLE config_random_item_place');
        $this->addSql('DROP TABLE consumable_effect');
        $this->addSql('DROP TABLE daedalus');
        $this->addSql('DROP TABLE daedalus_closed');
        $this->addSql('DROP TABLE daedalus_info');
        $this->addSql('DROP TABLE disease_cause_config');
        $this->addSql('DROP TABLE disease_config');
        $this->addSql('DROP TABLE disease_config_variable_event_modifier_config');
        $this->addSql('DROP TABLE disease_config_symptom_config');
        $this->addSql('DROP TABLE disease_consummable');
        $this->addSql('DROP TABLE disease_consummable_attribute');
        $this->addSql('DROP TABLE disease_consummable_config');
        $this->addSql('DROP TABLE disease_player');
        $this->addSql('DROP TABLE equipment_config');
        $this->addSql('DROP TABLE equipment_config_equipment_mechanic');
        $this->addSql('DROP TABLE equipment_config_action');
        $this->addSql('DROP TABLE equipment_config_status_config');
        $this->addSql('DROP TABLE equipment_mechanic');
        $this->addSql('DROP TABLE equipment_mechanic_action');
        $this->addSql('DROP TABLE gear_abstract_modifier_config');
        $this->addSql('DROP TABLE game_equipment');
        $this->addSql('DROP TABLE door_place');
        $this->addSql('DROP TABLE game_modifier');
        $this->addSql('DROP TABLE game_variable');
        $this->addSql('DROP TABLE game_variable_collection');
        $this->addSql('DROP TABLE message');
        $this->addSql('DROP TABLE modifier_activation_requirement');
        $this->addSql('DROP TABLE neron');
        $this->addSql('DROP TABLE news');
        $this->addSql('DROP TABLE place_config');
        $this->addSql('DROP TABLE plant_effect');
        $this->addSql('DROP TABLE player');
        $this->addSql('DROP TABLE player_player_flirts');
        $this->addSql('DROP TABLE player_info');
        $this->addSql('DROP TABLE room');
        $this->addSql('DROP TABLE place_door');
        $this->addSql('DROP TABLE room_log');
        $this->addSql('DROP TABLE status');
        $this->addSql('DROP TABLE status_config');
        $this->addSql('DROP TABLE status_config_variable_event_modifier_config');
        $this->addSql('DROP TABLE status_target');
        $this->addSql('DROP TABLE symptom_activation_requirement');
        $this->addSql('DROP TABLE symptom_config');
        $this->addSql('DROP TABLE symptom_config_symptom_activation_requirement');
        $this->addSql('DROP TABLE triumph_config');
        $this->addSql('DROP TABLE users');
    }
}
