<?php

use Mush\Game\Enum\CharacterEnum;
use Mush\Game\Enum\SkillEnum;
use Mush\Game\Enum\StatusEnum;

const CharacterConfigs = [
    [
        'name'=>CharacterEnum::ANDIE,
        'statuses'=>[],
        'skills'=>[
            SkillEnum::CONFIDENT,
            SkillEnum::DEVOTION,
            SkillEnum::EXPERT,
            SkillEnum::PILOT,
            SkillEnum::POLYVALENT,
        ],
    ],
    [
        'name'=>CharacterEnum::CHAO,
        'statuses'=>[StatusEnum::HYPERACTIVE],
        'skills'=>[
            SkillEnum::CRAZY_EYE,
            SkillEnum::INTIMIDATING,
            SkillEnum::SHOOTER,
            SkillEnum::SURVIVALIST,
            SkillEnum::TORTURER,
            SkillEnum::WRESTLER,
        ],
    ],
    [
        'name'=>CharacterEnum::CHUN,
        'statuses'=>[StatusEnum::IMMUNIZED],
        'skills'=>[
            SkillEnum::LETHARGY,
            SkillEnum::MANKINDS_ONLY_HOPE,
            SkillEnum::NURSE,
            SkillEnum::PREMONITION,
            SkillEnum::SNEAK,
        ],
    ],
    [
        'name'=>CharacterEnum::DEREK,
        'statuses'=>[],
        'skills'=>[
            SkillEnum::FIREFIGHTER,
            SkillEnum::MOTIVATOR,
            SkillEnum::SHOOTER,
            SkillEnum::WRESTLER,
            SkillEnum::HYGIENIST,
        ],
    ],
    [
        'name'=>CharacterEnum::ELEESHA,
        'statuses'=>[],
        'skills'=>[
            SkillEnum::DETERMINED,
            SkillEnum::IT_EXPERT,
            SkillEnum::OBSERVANT,
            SkillEnum::POLYMATH,
            SkillEnum::TECHNICIAN,
            SkillEnum::TRACKER,
        ],
    ],
    [
        'name'=>CharacterEnum::FINOLA,
        'statuses'=>[StatusEnum::GERMAPHOBE],
        'skills'=>[
            SkillEnum::BIOLOGIST,
            SkillEnum::DIPLOMAT,
            SkillEnum::MEDIC,
            SkillEnum::NURSE,
            SkillEnum::OCD,
            SkillEnum::TRACKER,
        ],
    ],
    [
        'name'=>CharacterEnum::FRIEDA,
        'statuses'=>[],
        'skills'=>[
            SkillEnum::ANTIQUE_PERFUME,
            SkillEnum::ASTROPHYSICIST,
            SkillEnum::IT_EXPERT,
            SkillEnum::PILOT,
            SkillEnum::RADIO_EXPERT,
            SkillEnum::SURVIVALIST,
        ],
    ],
    [
        'name'=>CharacterEnum::GIOELE,
        'statuses'=>[],
        'skills'=>[
            SkillEnum::ASTROPHYSICIST,
            SkillEnum::CAFFEINE_JUNKIE,
            SkillEnum::PANIC,
            SkillEnum::PARANOID,
            SkillEnum::SOLID,
            SkillEnum::VICTIMIZER,
        ],
    ],
    [
        'name'=>CharacterEnum::HUA,
        'statuses'=>[],
        'skills'=>[
            SkillEnum::BOTANIST,
            SkillEnum::DETERMINED,
            SkillEnum::PILOT,
            SkillEnum::SURVIVALIST,
            SkillEnum::TECHNICIAN,
            SkillEnum::U_TURN,
        ],
    ],
    [
        'name'=>CharacterEnum::IAN,
        'statuses'=>[StatusEnum::PACIFIST],
        'skills'=>[
            SkillEnum::BIOLOGIST,
            SkillEnum::BOTANIST,
            SkillEnum::FIREFIGHTER,
            SkillEnum::FRUGIVORE,
            SkillEnum::GREEN_THUMB,
            SkillEnum::MYCOLOGIST,
        ],
    ],
    [
        'name'=>CharacterEnum::JANICE,
        'statuses'=>[],
        'skills'=>[
            SkillEnum::DIPLOMAT,
            SkillEnum::IT_EXPERT,
            SkillEnum::NERON_ONLY_FRIEND,
            SkillEnum::RADIO_EXPERT,
            SkillEnum::SELF_SACRIFICE,
            SkillEnum::SHRINK,
        ],
    ],
    [
        'name'=>CharacterEnum::KIM_JUN_SU,
        'statuses'=>[],
        'skills'=>[
            SkillEnum::COLD_BLOODED,
            SkillEnum::LEADER,
            SkillEnum::LOGISTICS_EXPERT,
            SkillEnum::PILOT,
            SkillEnum::SHOOTER,
            SkillEnum::STRATEGURU,
        ],
    ],
    [
        'name'=>CharacterEnum::KUAN_TI,
        'statuses'=>[],
        'skills'=>[
            SkillEnum::ASTROPHYSICIST,
            SkillEnum::DESIGNER,
            SkillEnum::LEADER,
            SkillEnum::POLITICIAN,
            SkillEnum::TECHNICIAN,
            SkillEnum::OPTIMIST,
        ],
    ],
    [
        'name'=>CharacterEnum::PAOLA,
        'statuses'=>[],
        'skills'=>[
            SkillEnum::BIOLOGIST,
            SkillEnum::GUNNER,
            SkillEnum::LOGISTICS_EXPERT,
            SkillEnum::RADIO_EXPERT,
            SkillEnum::REBEL,
            SkillEnum::SHOOTER,
        ],
    ],
    [
        'name'=>CharacterEnum::RALUCA,
        'statuses'=>[StatusEnum::ANTISOCIAL],
        'skills'=>[
            SkillEnum::DESIGNER,
            SkillEnum::DETACHED_CREWMEMBER,
            SkillEnum::GENIUS,
            SkillEnum::PHYSICIST,
            SkillEnum::TECHNICIAN,
        ],
    ],
    [
        'name'=>CharacterEnum::ROLAND,
        'statuses'=>[],
        'skills'=>[
            SkillEnum::CREATIVE,
            SkillEnum::FIREFIGHTER,
            SkillEnum::PILOT,
            SkillEnum::SHOOTER,
            SkillEnum::SPRINTER,
            SkillEnum::OPTIMIST,
        ],
    ],
    [
        'name'=>CharacterEnum::STEPHEN,
        'statuses'=>[],
        'skills'=>[
            SkillEnum::APPRENTICE,
            SkillEnum::CHEF,
            SkillEnum::CREATIVE,
            SkillEnum::OPPORTUNIST,
            SkillEnum::SHOOTER,
            SkillEnum::SOLID,
        ],
    ],
    [
        'name'=>CharacterEnum::TERRENCE,
        'statuses'=>[StatusEnum::DISABLED],
        'skills'=>[
            SkillEnum::IT_EXPERT,
            SkillEnum::METALWORKER,
            SkillEnum::PILOT,
            SkillEnum::ROBOTICS_EXPERT,
            SkillEnum::SHOOTER,
            SkillEnum::TECHNICIAN,
        ],
    ],
];