<?php

namespace Mush\Game\ConfigData;

use Mush\Exploration\Event\PlanetSectorEvent;
use Mush\Game\Event\VariableEventInterface;
use Mush\Modifier\Enum\ModifierHolderClassEnum;
use Mush\Player\Enum\PlayerVariableEnum;

/** @codeCoverageIgnore */
class EventConfigData
{
    public static array $dataArray = [
        [
            'type' => 'variable_event_config',
            'quantity' => -1,
            'targetVariable' => PlayerVariableEnum::HEALTH_POINT,
            'variableHolderClass' => ModifierHolderClassEnum::PLAYER,
            'eventName' => VariableEventInterface::CHANGE_VALUE_MAX,
            'name' => 'change.value.max_player_-1_healthPoint',
        ],
        [
            'type' => 'variable_event_config',
            'quantity' => -2,
            'targetVariable' => PlayerVariableEnum::HEALTH_POINT,
            'variableHolderClass' => ModifierHolderClassEnum::PLAYER,
            'eventName' => VariableEventInterface::CHANGE_VALUE_MAX,
            'name' => 'change.value.max_player_-2_healthPoint',
        ],
        [
            'type' => 'variable_event_config',
            'quantity' => -4,
            'targetVariable' => PlayerVariableEnum::HEALTH_POINT,
            'variableHolderClass' => ModifierHolderClassEnum::PLAYER,
            'eventName' => VariableEventInterface::CHANGE_VALUE_MAX,
            'name' => 'change.value.max_player_-4_healthPoint',
        ],
        [
            'type' => 'variable_event_config',
            'quantity' => -1,
            'targetVariable' => PlayerVariableEnum::MORAL_POINT,
            'variableHolderClass' => ModifierHolderClassEnum::PLAYER,
            'eventName' => VariableEventInterface::CHANGE_VALUE_MAX,
            'name' => 'change.value.max_player_-1_moralPoint',
        ],
        [
            'type' => 'variable_event_config',
            'quantity' => -2,
            'targetVariable' => PlayerVariableEnum::MORAL_POINT,
            'variableHolderClass' => ModifierHolderClassEnum::PLAYER,
            'eventName' => VariableEventInterface::CHANGE_VALUE_MAX,
            'name' => 'change.value.max_player_-2_moralPoint',
        ],
        [
            'type' => 'variable_event_config',
            'quantity' => -3,
            'targetVariable' => PlayerVariableEnum::MORAL_POINT,
            'variableHolderClass' => ModifierHolderClassEnum::PLAYER,
            'eventName' => VariableEventInterface::CHANGE_VALUE_MAX,
            'name' => 'change.value.max_player_-3_moralPoint',
        ],
        [
            'type' => 'variable_event_config',
            'quantity' => -4,
            'targetVariable' => PlayerVariableEnum::MORAL_POINT,
            'variableHolderClass' => ModifierHolderClassEnum::PLAYER,
            'eventName' => VariableEventInterface::CHANGE_VALUE_MAX,
            'name' => 'change.value.max_player_-4_moralPoint',
        ],
        [
            'type' => 'variable_event_config',
            'quantity' => -2,
            'targetVariable' => PlayerVariableEnum::ACTION_POINT,
            'variableHolderClass' => ModifierHolderClassEnum::PLAYER,
            'eventName' => VariableEventInterface::CHANGE_VALUE_MAX,
            'name' => 'change.value.max_player_-2_actionPoint',
        ],
        [
            'type' => 'variable_event_config',
            'quantity' => 1,
            'targetVariable' => PlayerVariableEnum::MOVEMENT_POINT,
            'variableHolderClass' => ModifierHolderClassEnum::PLAYER,
            'eventName' => VariableEventInterface::CHANGE_VALUE_MAX,
            'name' => 'change.value.max_player_1_movementPoint',
        ],
        [
            'type' => 'variable_event_config',
            'quantity' => -3,
            'targetVariable' => PlayerVariableEnum::MOVEMENT_POINT,
            'variableHolderClass' => ModifierHolderClassEnum::PLAYER,
            'eventName' => VariableEventInterface::CHANGE_VALUE_MAX,
            'name' => 'change.value.max_player_-3_movementPoint',
        ],
        [
            'type' => 'variable_event_config',
            'quantity' => -5,
            'targetVariable' => PlayerVariableEnum::MOVEMENT_POINT,
            'variableHolderClass' => ModifierHolderClassEnum::PLAYER,
            'eventName' => VariableEventInterface::CHANGE_VALUE_MAX,
            'name' => 'change.value.max_player_-5_movementPoint',
        ],
        [
            'type' => 'variable_event_config',
            'quantity' => -12,
            'targetVariable' => PlayerVariableEnum::MOVEMENT_POINT,
            'variableHolderClass' => ModifierHolderClassEnum::PLAYER,
            'eventName' => VariableEventInterface::CHANGE_VALUE_MAX,
            'name' => 'change.value.max_player_-12_movementPoint',
        ],
        [
            'type' => 'variable_event_config',
            'quantity' => -1,
            'targetVariable' => PlayerVariableEnum::HEALTH_POINT,
            'variableHolderClass' => ModifierHolderClassEnum::PLAYER,
            'eventName' => VariableEventInterface::CHANGE_VARIABLE,
            'name' => 'change.variable_player_-1_healthPoint',
        ],
        [
            'type' => 'variable_event_config',
            'quantity' => -2,
            'targetVariable' => PlayerVariableEnum::HEALTH_POINT,
            'variableHolderClass' => ModifierHolderClassEnum::PLAYER,
            'eventName' => VariableEventInterface::CHANGE_VARIABLE,
            'name' => 'change.variable_player_-2_healthPoint',
        ],
        [
            'type' => 'variable_event_config',
            'quantity' => -3,
            'targetVariable' => PlayerVariableEnum::HEALTH_POINT,
            'variableHolderClass' => ModifierHolderClassEnum::PLAYER,
            'eventName' => VariableEventInterface::CHANGE_VARIABLE,
            'name' => 'change.variable_player_-3_healthPoint',
        ],
        [
            'type' => 'variable_event_config',
            'quantity' => -4,
            'targetVariable' => PlayerVariableEnum::HEALTH_POINT,
            'variableHolderClass' => ModifierHolderClassEnum::PLAYER,
            'eventName' => VariableEventInterface::CHANGE_VARIABLE,
            'name' => 'change.variable_player_-4_healthPoint',
        ],
        [
            'type' => 'variable_event_config',
            'quantity' => -6,
            'targetVariable' => PlayerVariableEnum::HEALTH_POINT,
            'variableHolderClass' => ModifierHolderClassEnum::PLAYER,
            'eventName' => VariableEventInterface::CHANGE_VARIABLE,
            'name' => 'change.variable_player_-6_healthPoint',
        ],
        [
            'type' => 'variable_event_config',
            'quantity' => -1,
            'targetVariable' => PlayerVariableEnum::MORAL_POINT,
            'variableHolderClass' => ModifierHolderClassEnum::PLAYER,
            'eventName' => VariableEventInterface::CHANGE_VARIABLE,
            'name' => 'change.variable_player_-1_moralPoint',
        ],
        [
            'type' => 'variable_event_config',
            'quantity' => 1,
            'targetVariable' => PlayerVariableEnum::ACTION_POINT,
            'variableHolderClass' => ModifierHolderClassEnum::PLAYER,
            'eventName' => VariableEventInterface::CHANGE_VARIABLE,
            'name' => 'change.variable_player_1_actionPoint',
        ],
        [
            'type' => 'variable_event_config',
            'quantity' => -1,
            'targetVariable' => PlayerVariableEnum::ACTION_POINT,
            'variableHolderClass' => ModifierHolderClassEnum::PLAYER,
            'eventName' => VariableEventInterface::CHANGE_VARIABLE,
            'name' => 'change.variable_player_-1_actionPoint',
        ],
        [
            'type' => 'variable_event_config',
            'quantity' => -2,
            'targetVariable' => PlayerVariableEnum::ACTION_POINT,
            'variableHolderClass' => ModifierHolderClassEnum::PLAYER,
            'eventName' => VariableEventInterface::CHANGE_VARIABLE,
            'name' => 'change.variable_player_-2_actionPoint',
        ],
        [
            'type' => 'variable_event_config',
            'quantity' => -1,
            'targetVariable' => PlayerVariableEnum::MOVEMENT_POINT,
            'variableHolderClass' => ModifierHolderClassEnum::PLAYER,
            'eventName' => VariableEventInterface::CHANGE_VARIABLE,
            'name' => 'change.variable_player_-1_movementPoint',
        ],
        [
            'type' => 'variable_event_config',
            'quantity' => -2,
            'targetVariable' => PlayerVariableEnum::MOVEMENT_POINT,
            'variableHolderClass' => ModifierHolderClassEnum::PLAYER,
            'eventName' => VariableEventInterface::CHANGE_VARIABLE,
            'name' => 'change.variable_player_-2_movementPoint',
        ],
        [
            'type' => 'variable_event_config',
            'quantity' => 1,
            'targetVariable' => PlayerVariableEnum::MOVEMENT_POINT,
            'variableHolderClass' => ModifierHolderClassEnum::PLAYER,
            'eventName' => VariableEventInterface::CHANGE_VARIABLE,
            'name' => 'change.variable_player_1_movementPoint',
        ],
        [
            'type' => 'variable_event_config',
            'quantity' => -1,
            'targetVariable' => PlayerVariableEnum::SATIETY,
            'variableHolderClass' => ModifierHolderClassEnum::PLAYER,
            'eventName' => VariableEventInterface::CHANGE_VARIABLE,
            'name' => 'change.variable_player_-1_satiety',
        ],
        [
            'type' => 'variable_event_config',
            'quantity' => 1,
            'targetVariable' => PlayerVariableEnum::SATIETY,
            'variableHolderClass' => ModifierHolderClassEnum::PLAYER,
            'eventName' => VariableEventInterface::CHANGE_VARIABLE,
            'name' => 'change.variable_player_1_satiety',
        ],
        [
            'type' => 'planet_sector_event_config',
            'name' => PlanetSectorEvent::ACCIDENT . '_3_5',
            'eventName' => PlanetSectorEvent::ACCIDENT,
            'outputQuantityTable' => [
                // 3 => 1,
                // 4 => 1,
                // 5 => 1,
                1 => 1,
            ],
        ],
        [
            'type' => 'planet_sector_event_config',
            'name' => PlanetSectorEvent::DISASTER . '_3_5',
            'eventName' => PlanetSectorEvent::DISASTER,
            'outputQuantityTable' => [
                // 3 => 1,
                // 4 => 1,
                // 5 => 1,
                1 => 1,
            ],
        ],
        [
            'type' => 'planet_sector_event_config',
            'name' => PlanetSectorEvent::NOTHING_TO_REPORT,
            'eventName' => PlanetSectorEvent::NOTHING_TO_REPORT,
        ],
        [
            'type' => 'planet_sector_event_config',
            'name' => PlanetSectorEvent::TIRED . '_2',
            'eventName' => PlanetSectorEvent::TIRED,
            'outputQuantityTable' => [
                // 2 => 1,
                1 => 1,
            ],
        ],
    ];
}
