<?php

namespace Mush\Game\ConfigData;

use Mush\Daedalus\Enum\DaedalusVariableEnum;
use Mush\Equipment\Enum\EquipmentEnum;
use Mush\Equipment\Enum\ItemEnum;
use Mush\Exploration\Event\PlanetSectorEvent;
use Mush\Game\Event\VariableEventInterface;
use Mush\Modifier\Enum\ModifierHolderClassEnum;
use Mush\Place\Enum\RoomEnum;
use Mush\Player\Enum\PlayerVariableEnum;
use Mush\Status\Enum\EquipmentStatusEnum;

/** @codeCoverageIgnore */
class EventConfigData
{
    public static array $variableEventConfigData = [
        [
            'type' => 'variable_event_config',
            'quantity' => -1,
            'targetVariable' => PlayerVariableEnum::HEALTH_POINT,
            'variableHolderClass' => ModifierHolderClassEnum::PLAYER,
            'eventName' => VariableEventInterface::CHANGE_VALUE_MAX,
            'name' => 'change.value.max_player_-1_healthPoint',
        ],
        [
            'type' => 'variable_event_config',
            'quantity' => -2,
            'targetVariable' => PlayerVariableEnum::HEALTH_POINT,
            'variableHolderClass' => ModifierHolderClassEnum::PLAYER,
            'eventName' => VariableEventInterface::CHANGE_VALUE_MAX,
            'name' => 'change.value.max_player_-2_healthPoint',
        ],
        [
            'type' => 'variable_event_config',
            'quantity' => -4,
            'targetVariable' => PlayerVariableEnum::HEALTH_POINT,
            'variableHolderClass' => ModifierHolderClassEnum::PLAYER,
            'eventName' => VariableEventInterface::CHANGE_VALUE_MAX,
            'name' => 'change.value.max_player_-4_healthPoint',
        ],
        [
            'type' => 'variable_event_config',
            'quantity' => -1,
            'targetVariable' => PlayerVariableEnum::MORAL_POINT,
            'variableHolderClass' => ModifierHolderClassEnum::PLAYER,
            'eventName' => VariableEventInterface::CHANGE_VALUE_MAX,
            'name' => 'change.value.max_player_-1_moralPoint',
        ],
        [
            'type' => 'variable_event_config',
            'quantity' => -2,
            'targetVariable' => PlayerVariableEnum::MORAL_POINT,
            'variableHolderClass' => ModifierHolderClassEnum::PLAYER,
            'eventName' => VariableEventInterface::CHANGE_VALUE_MAX,
            'name' => 'change.value.max_player_-2_moralPoint',
        ],
        [
            'type' => 'variable_event_config',
            'quantity' => -3,
            'targetVariable' => PlayerVariableEnum::MORAL_POINT,
            'variableHolderClass' => ModifierHolderClassEnum::PLAYER,
            'eventName' => VariableEventInterface::CHANGE_VALUE_MAX,
            'name' => 'change.value.max_player_-3_moralPoint',
        ],
        [
            'type' => 'variable_event_config',
            'quantity' => -4,
            'targetVariable' => PlayerVariableEnum::MORAL_POINT,
            'variableHolderClass' => ModifierHolderClassEnum::PLAYER,
            'eventName' => VariableEventInterface::CHANGE_VALUE_MAX,
            'name' => 'change.value.max_player_-4_moralPoint',
        ],
        [
            'type' => 'variable_event_config',
            'quantity' => -2,
            'targetVariable' => PlayerVariableEnum::ACTION_POINT,
            'variableHolderClass' => ModifierHolderClassEnum::PLAYER,
            'eventName' => VariableEventInterface::CHANGE_VALUE_MAX,
            'name' => 'change.value.max_player_-2_actionPoint',
        ],
        [
            'type' => 'variable_event_config',
            'quantity' => 1,
            'targetVariable' => PlayerVariableEnum::MOVEMENT_POINT,
            'variableHolderClass' => ModifierHolderClassEnum::PLAYER,
            'eventName' => VariableEventInterface::CHANGE_VALUE_MAX,
            'name' => 'change.value.max_player_1_movementPoint',
        ],
        [
            'type' => 'variable_event_config',
            'quantity' => -3,
            'targetVariable' => PlayerVariableEnum::MOVEMENT_POINT,
            'variableHolderClass' => ModifierHolderClassEnum::PLAYER,
            'eventName' => VariableEventInterface::CHANGE_VALUE_MAX,
            'name' => 'change.value.max_player_-3_movementPoint',
        ],
        [
            'type' => 'variable_event_config',
            'quantity' => -5,
            'targetVariable' => PlayerVariableEnum::MOVEMENT_POINT,
            'variableHolderClass' => ModifierHolderClassEnum::PLAYER,
            'eventName' => VariableEventInterface::CHANGE_VALUE_MAX,
            'name' => 'change.value.max_player_-5_movementPoint',
        ],
        [
            'type' => 'variable_event_config',
            'quantity' => -12,
            'targetVariable' => PlayerVariableEnum::MOVEMENT_POINT,
            'variableHolderClass' => ModifierHolderClassEnum::PLAYER,
            'eventName' => VariableEventInterface::CHANGE_VALUE_MAX,
            'name' => 'change.value.max_player_-12_movementPoint',
        ],
        [
            'type' => 'variable_event_config',
            'quantity' => -1,
            'targetVariable' => PlayerVariableEnum::HEALTH_POINT,
            'variableHolderClass' => ModifierHolderClassEnum::PLAYER,
            'eventName' => VariableEventInterface::CHANGE_VARIABLE,
            'name' => 'change.variable_player_-1_healthPoint',
        ],
        [
            'type' => 'variable_event_config',
            'quantity' => -2,
            'targetVariable' => PlayerVariableEnum::HEALTH_POINT,
            'variableHolderClass' => ModifierHolderClassEnum::PLAYER,
            'eventName' => VariableEventInterface::CHANGE_VARIABLE,
            'name' => 'change.variable_player_-2_healthPoint',
        ],
        [
            'type' => 'variable_event_config',
            'quantity' => -3,
            'targetVariable' => PlayerVariableEnum::HEALTH_POINT,
            'variableHolderClass' => ModifierHolderClassEnum::PLAYER,
            'eventName' => VariableEventInterface::CHANGE_VARIABLE,
            'name' => 'change.variable_player_-3_healthPoint',
        ],
        [
            'type' => 'variable_event_config',
            'quantity' => -4,
            'targetVariable' => PlayerVariableEnum::HEALTH_POINT,
            'variableHolderClass' => ModifierHolderClassEnum::PLAYER,
            'eventName' => VariableEventInterface::CHANGE_VARIABLE,
            'name' => 'change.variable_player_-4_healthPoint',
        ],
        [
            'type' => 'variable_event_config',
            'quantity' => -6,
            'targetVariable' => PlayerVariableEnum::HEALTH_POINT,
            'variableHolderClass' => ModifierHolderClassEnum::PLAYER,
            'eventName' => VariableEventInterface::CHANGE_VARIABLE,
            'name' => 'change.variable_player_-6_healthPoint',
        ],
        [
            'type' => 'variable_event_config',
            'quantity' => -1,
            'targetVariable' => PlayerVariableEnum::MORAL_POINT,
            'variableHolderClass' => ModifierHolderClassEnum::PLAYER,
            'eventName' => VariableEventInterface::CHANGE_VARIABLE,
            'name' => 'change.variable_player_-1_moralPoint',
        ],
        [
            'type' => 'variable_event_config',
            'quantity' => -2,
            'targetVariable' => PlayerVariableEnum::MORAL_POINT,
            'variableHolderClass' => ModifierHolderClassEnum::PLAYER,
            'eventName' => VariableEventInterface::CHANGE_VARIABLE,
            'name' => 'change.variable_player_-2_moralPoint',
        ],
        [
            'type' => 'variable_event_config',
            'quantity' => 1,
            'targetVariable' => PlayerVariableEnum::ACTION_POINT,
            'variableHolderClass' => ModifierHolderClassEnum::PLAYER,
            'eventName' => VariableEventInterface::CHANGE_VARIABLE,
            'name' => 'change.variable_player_1_actionPoint',
        ],
        [
            'type' => 'variable_event_config',
            'quantity' => -1,
            'targetVariable' => PlayerVariableEnum::ACTION_POINT,
            'variableHolderClass' => ModifierHolderClassEnum::PLAYER,
            'eventName' => VariableEventInterface::CHANGE_VARIABLE,
            'name' => 'change.variable_player_-1_actionPoint',
        ],
        [
            'type' => 'variable_event_config',
            'quantity' => -2,
            'targetVariable' => PlayerVariableEnum::ACTION_POINT,
            'variableHolderClass' => ModifierHolderClassEnum::PLAYER,
            'eventName' => VariableEventInterface::CHANGE_VARIABLE,
            'name' => 'change.variable_player_-2_actionPoint',
        ],
        [
            'type' => 'variable_event_config',
            'quantity' => -1,
            'targetVariable' => PlayerVariableEnum::MOVEMENT_POINT,
            'variableHolderClass' => ModifierHolderClassEnum::PLAYER,
            'eventName' => VariableEventInterface::CHANGE_VARIABLE,
            'name' => 'change.variable_player_-1_movementPoint',
        ],
        [
            'type' => 'variable_event_config',
            'quantity' => -2,
            'targetVariable' => PlayerVariableEnum::MOVEMENT_POINT,
            'variableHolderClass' => ModifierHolderClassEnum::PLAYER,
            'eventName' => VariableEventInterface::CHANGE_VARIABLE,
            'name' => 'change.variable_player_-2_movementPoint',
        ],
        [
            'type' => 'variable_event_config',
            'quantity' => 1,
            'targetVariable' => PlayerVariableEnum::MOVEMENT_POINT,
            'variableHolderClass' => ModifierHolderClassEnum::PLAYER,
            'eventName' => VariableEventInterface::CHANGE_VARIABLE,
            'name' => 'change.variable_player_1_movementPoint',
        ],
        [
            'type' => 'variable_event_config',
            'quantity' => -1,
            'targetVariable' => PlayerVariableEnum::SATIETY,
            'variableHolderClass' => ModifierHolderClassEnum::PLAYER,
            'eventName' => VariableEventInterface::CHANGE_VARIABLE,
            'name' => 'change.variable_player_-1_satiety',
        ],
        [
            'type' => 'variable_event_config',
            'quantity' => 1,
            'targetVariable' => PlayerVariableEnum::SATIETY,
            'variableHolderClass' => ModifierHolderClassEnum::PLAYER,
            'eventName' => VariableEventInterface::CHANGE_VARIABLE,
            'name' => 'change.variable_player_1_satiety',
        ],
        [
            'type' => 'variable_event_config',
            'quantity' => 2,
            'targetVariable' => EquipmentStatusEnum::ELECTRIC_CHARGES,
            'variableHolderClass' => ModifierHolderClassEnum::EQUIPMENT,
            'eventName' => VariableEventInterface::CHANGE_VALUE_MAX,
            'name' => 'change.variable_turret_max_charge_+2',
        ],
        [
            'type' => 'variable_event_config',
            'quantity' => 50,
            'targetVariable' => DaedalusVariableEnum::SHIELD,
            'variableHolderClass' => ModifierHolderClassEnum::DAEDALUS,
            'eventName' => VariableEventInterface::SET_VALUE,
            'name' => 'set.value_daedalus_shield_50',
        ],
        [
            'type' => 'variable_event_config',
            'quantity' => 5,
            'targetVariable' => DaedalusVariableEnum::SHIELD,
            'variableHolderClass' => ModifierHolderClassEnum::DAEDALUS,
            'eventName' => VariableEventInterface::CHANGE_VARIABLE,
            'name' => 'change.variable_daedalus_shield_+5',
        ],
    ];

    public static array $planetSectorEventConfigData = [
        [
            'type' => 'planet_sector_event_config',
            'name' => PlanetSectorEvent::ACCIDENT_3_5,
            'eventName' => PlanetSectorEvent::ACCIDENT,
            'outputQuantity' => [1 => 1],
            'outputTable' => [
                3 => 1,
                4 => 1,
                5 => 1,
            ],
        ],
        [
            'type' => 'planet_sector_event_config',
            'name' => PlanetSectorEvent::DISASTER_3_5,
            'eventName' => PlanetSectorEvent::DISASTER,
            'outputQuantity' => [1 => 1],
            'outputTable' => [
                3 => 1,
                4 => 1,
                5 => 1,
            ],
        ],
        [
            'type' => 'planet_sector_event_config',
            'name' => PlanetSectorEvent::NOTHING_TO_REPORT,
            'eventName' => PlanetSectorEvent::NOTHING_TO_REPORT,
            'outputQuantity' => [0 => 1],
            'outputTable' => [0 => 1],
        ],
        [
            'type' => 'planet_sector_event_config',
            'name' => PlanetSectorEvent::TIRED_2,
            'eventName' => PlanetSectorEvent::TIRED,
            'outputQuantity' => [1 => 1],
            'outputTable' => [
                2 => 1,
            ],
        ],
        [
            'type' => 'planet_sector_event_config',
            'name' => PlanetSectorEvent::OXYGEN_8,
            'eventName' => PlanetSectorEvent::OXYGEN,
            'outputQuantity' => [1 => 1],
            'outputTable' => [
                8 => 1,
            ],
        ],
        [
            'type' => 'planet_sector_event_config',
            'name' => PlanetSectorEvent::OXYGEN_16,
            'eventName' => PlanetSectorEvent::OXYGEN,
            'outputQuantity' => [1 => 1],
            'outputTable' => [
                16 => 1,
            ],
        ],
        [
            'type' => 'planet_sector_event_config',
            'name' => PlanetSectorEvent::OXYGEN_24,
            'eventName' => PlanetSectorEvent::OXYGEN,
            'outputQuantity' => [1 => 1],
            'outputTable' => [
                24 => 1,
            ],
        ],
        [
            'type' => 'planet_sector_event_config',
            'name' => PlanetSectorEvent::FUEL_1,
            'eventName' => PlanetSectorEvent::FUEL,
            'outputQuantity' => [],
            'outputTable' => [
                1 => 1,
            ],
        ],
        [
            'type' => 'planet_sector_event_config',
            'name' => PlanetSectorEvent::FUEL_2,
            'eventName' => PlanetSectorEvent::FUEL,
            'outputQuantity' => [1 => 1],
            'outputTable' => [
                2 => 1,
            ],
        ],
        [
            'type' => 'planet_sector_event_config',
            'name' => PlanetSectorEvent::FUEL_3,
            'eventName' => PlanetSectorEvent::FUEL,
            'outputQuantity' => [1 => 1],
            'outputTable' => [
                3 => 1,
            ],
        ],
        [
            'type' => 'planet_sector_event_config',
            'name' => PlanetSectorEvent::FUEL_4,
            'eventName' => PlanetSectorEvent::FUEL,
            'outputQuantity' => [1 => 1],
            'outputTable' => [
                4 => 1,
            ],
        ],
        [
            'type' => 'planet_sector_event_config',
            'name' => PlanetSectorEvent::FUEL_5,
            'eventName' => PlanetSectorEvent::FUEL,
            'outputQuantity' => [1 => 1],
            'outputTable' => [
                5 => 1,
            ],
        ],
        [
            'type' => 'planet_sector_event_config',
            'name' => PlanetSectorEvent::FUEL_6,
            'eventName' => PlanetSectorEvent::FUEL,
            'outputQuantity' => [1 => 1],
            'outputTable' => [
                6 => 1,
            ],
        ],
        [
            'type' => 'planet_sector_event_config',
            'name' => 'artefact',
            'eventName' => 'artefact',
            'outputQuantity' => [1 => 1],
            'outputTable' => [
                'alien_bottle_opener' => 1,
                'alien_holographic_tv' => 1,
                'invertebrate_shell' => 1,
                'jar_of_alien_oil' => 1,
                'magellan_liquid_map' => 1,
                'printed_circuit_jelly' => 1,
                'rolling_boulder' => 1,
                'starmap_fragment' => 1,
                'water_stick' => 1,
            ],
        ],
        [
            'type' => 'planet_sector_event_config',
            'name' => 'kill_random',
            'eventName' => 'kill_random',
            'outputQuantity' => [],
            'outputTable' => [],
        ],
        [
            'type' => 'planet_sector_event_config',
            'name' => 'kill_all',
            'eventName' => 'kill_all',
            'outputQuantity' => [],
            'outputTable' => [],
        ],
        [
            'type' => 'planet_sector_event_config',
            'name' => 'provision_1',
            'eventName' => 'provision',
            'outputQuantity' => [1 => 1],
            'outputTable' => [
                'alien_steak' => 1,
            ],
        ],
        [
            'type' => 'planet_sector_event_config',
            'name' => 'provision_2',
            'eventName' => 'provision',
            'outputQuantity' => [2 => 1],
            'outputTable' => [
                'alien_steak' => 1,
            ],
        ],
        [
            'type' => 'planet_sector_event_config',
            'name' => 'provision_3',
            'eventName' => 'provision',
            'outputQuantity' => [3 => 1],
            'outputTable' => [
                'alien_steak' => 1,
            ],
        ],
        [
            'type' => 'planet_sector_event_config',
            'name' => 'provision_4',
            'eventName' => 'provision',
            'outputQuantity' => [4 => 1],
            'outputTable' => [
                'alien_steak' => 1,
            ],
        ],
        [
            'type' => 'planet_sector_event_config',
            'name' => 'fight_8',
            'eventName' => 'fight',
            'outputQuantity' => [5 => 1],
            'outputTable' => [
                8 => 1,
            ],
        ],
        [
            'type' => 'planet_sector_event_config',
            'name' => 'fight_10',
            'eventName' => 'fight',
            'outputQuantity' => [5 => 1],
            'outputTable' => [
                10 => 1,
            ],
        ],
        [
            'type' => 'planet_sector_event_config',
            'name' => 'fight_12',
            'eventName' => 'fight',
            'outputQuantity' => [5 => 1],
            'outputTable' => [
                12 => 1,
            ],
        ],
        [
            'type' => 'planet_sector_event_config',
            'name' => 'fight_15',
            'eventName' => 'fight',
            'outputQuantity' => [5 => 1],
            'outputTable' => [
                15 => 1,
            ],
        ],
        [
            'type' => 'planet_sector_event_config',
            'name' => 'fight_18',
            'eventName' => 'fight',
            'outputQuantity' => [5 => 1],
            'outputTable' => [
                18 => 1,
            ],
        ],
        [
            'type' => 'planet_sector_event_config',
            'name' => 'fight_32',
            'eventName' => 'fight',
            'outputQuantity' => [5 => 1],
            'outputTable' => [
                32 => 1,
            ],
        ],
        [
            'type' => 'planet_sector_event_config',
            'name' => 'fight_8_10_12_15_18_32',
            'eventName' => 'fight',
            'outputQuantity' => [5 => 1],
            'outputTable' => [
                8 => 1,
                10 => 1,
                12 => 1,
                15 => 1,
                18 => 1,
                32 => 1,
            ],
        ],
        [
            'type' => 'planet_sector_event_config',
            'name' => 'harvest_1',
            'eventName' => 'harvest',
            'outputQuantity' => [1 => 1],
            'outputTable' => [
                'creepnut' => 1,
                'meztine' => 1,
                'guntiflop' => 1,
                'ploshmina' => 1,
                'precati' => 1,
                'bottine' => 1,
                'fragilane' => 1,
                'anemole' => 1,
                'peniraft' => 1,
                'kubinus' => 1,
                'caleboot' => 1,
                'filandra' => 1,
            ],
        ],
        [
            'type' => 'planet_sector_event_config',
            'name' => 'harvest_2',
            'eventName' => 'harvest',
            'outputQuantity' => [2 => 1],
            'outputTable' => [
                'creepnut' => 1,
                'meztine' => 1,
                'guntiflop' => 1,
                'ploshmina' => 1,
                'precati' => 1,
                'bottine' => 1,
                'fragilane' => 1,
                'anemole' => 1,
                'peniraft' => 1,
                'kubinus' => 1,
                'caleboot' => 1,
                'filandra' => 1,
            ],
        ],
        [
            'type' => 'planet_sector_event_config',
            'name' => 'harvest_3',
            'eventName' => 'harvest',
            'outputQuantity' => [3 => 1],
            'outputTable' => [
                'creepnut' => 1,
                'meztine' => 1,
                'guntiflop' => 1,
                'ploshmina' => 1,
                'precati' => 1,
                'bottine' => 1,
                'fragilane' => 1,
                'anemole' => 1,
                'peniraft' => 1,
                'kubinus' => 1,
                'caleboot' => 1,
                'filandra' => 1,
            ],
        ],
        [
            'type' => 'planet_sector_event_config',
            'name' => 'disease',
            'eventName' => 'disease',
            'outputQuantity' => [],
            'outputTable' => [],
        ],
        [
            'type' => 'planet_sector_event_config',
            'name' => 'starmap',
            'eventName' => 'starmap',
            'outputQuantity' => [1 => 1],
            'outputTable' => [
                'starmap_fragment' => 1,
            ],
        ],
        [
            'type' => 'planet_sector_event_config',
            'name' => 'mush_trap',
            'eventName' => 'mush_trap',
            'outputQuantity' => [50 => 1],
            'outputTable' => [],
        ],
        [
            'type' => 'planet_sector_event_config',
            'name' => 'again',
            'eventName' => 'again',
            'outputQuantity' => [],
            'outputTable' => [],
        ],
        [
            'type' => 'planet_sector_event_config',
            'name' => 'item_lost',
            'eventName' => 'item_lost',
            'outputQuantity' => [],
            'outputTable' => [],
        ],
        [
            'type' => 'planet_sector_event_config',
            'name' => 'back',
            'eventName' => 'back',
            'outputQuantity' => [],
            'outputTable' => [],
        ],
        [
            'type' => 'planet_sector_event_config',
            'name' => 'player_lost',
            'eventName' => 'player_lost',
            'outputQuantity' => [],
            'outputTable' => [],
        ],
        [
            'type' => 'planet_sector_event_config',
            'name' => 'find_lost',
            'eventName' => 'find_lost',
            'outputQuantity' => [],
            'outputTable' => [],
        ],
        [
            'type' => 'planet_sector_event_config',
            'name' => 'kill_lost',
            'eventName' => 'kill_lost',
            'outputQuantity' => [],
            'outputTable' => [],
        ],
    ];

    public static array $spawnEquipmentEventConfigData = [
        [
            'name' => '5_metal_scraps_in_engine_room',
            'eventName' => 'spawn',
            'equipmentName' => ItemEnum::METAL_SCRAPS,
            'roomName' => RoomEnum::ENGINE_ROOM,
            'quantity' => 5,
        ],
        [
            'name' => '3_hydropot_in_garden',
            'eventName' => 'spawn',
            'equipmentName' => ItemEnum::HYDROPOT,
            'roomName' => RoomEnum::HYDROPONIC_GARDEN,
            'quantity' => 3,
        ],
        [
            'name' => '1_thalasso_in_alpha_dorm',
            'eventName' => 'spawn',
            'equipmentName' => EquipmentEnum::THALASSO,
            'replacedEquipment' => EquipmentEnum::SHOWER,
            'roomName' => RoomEnum::ALPHA_DORM,
            'quantity' => 1,
        ],
        [
            'name' => '1_thalasso_in_bravo_dorm',
            'eventName' => 'spawn',
            'equipmentName' => EquipmentEnum::THALASSO,
            'replacedEquipment' => EquipmentEnum::SHOWER,
            'roomName' => RoomEnum::BRAVO_DORM,
            'quantity' => 1,
        ],
        [
            'name' => '1_auxiliary_neron_core_in_medlab',
            'eventName' => 'spawn',
            'equipmentName' => EquipmentEnum::AUXILIARY_TERMINAL,
            'roomName' => RoomEnum::MEDLAB,
            'quantity' => 1,
        ],
        [
            'name' => '1_auxiliary_neron_core_in_engine_room',
            'eventName' => 'spawn',
            'equipmentName' => EquipmentEnum::AUXILIARY_TERMINAL,
            'roomName' => RoomEnum::ENGINE_ROOM,
            'quantity' => 1,
        ],
    ];

    // Use that once all constructors are refactored
    public static function getAllEventConfig(): array
    {
        return array_merge(
            self::$variableEventConfigData,
            self::$planetSectorEventConfigData,
            self::$spawnEquipmentEventConfigData,
        );
    }
}
