<?php

namespace Mush\Game\ConfigData;

use Mush\Communications\Enum\RebelBaseEnum;
use Mush\Communications\Enum\TradeEnum;
use Mush\Communications\Enum\XylophEnum;
use Mush\Equipment\Enum\ItemEnum;
use Mush\Exploration\Enum\PlanetSectorEnum;
use Mush\Game\Enum\GameConfigEnum;
use Mush\Game\Enum\TitleEnum;
use Mush\Hunter\Enum\HunterEnum;
use Mush\Project\Enum\ProjectName;
use Mush\Skill\Enum\SkillEnum;
use Mush\Status\Enum\DaedalusStatusEnum;
use Mush\Status\Enum\EquipmentStatusEnum;
use Mush\Status\Enum\HunterStatusEnum;
use Mush\Status\Enum\PlaceStatusEnum;
use Mush\Status\Enum\PlayerStatusEnum;
use Mush\Status\Enum\SkillPointsEnum;
use Mush\Triumph\ConfigData\TriumphConfigData;
use Mush\Triumph\Dto\TriumphConfigDto;

/** @codeCoverageIgnore */
class GameConfigData
{
    public static function getAll(): array
    {
        return [
            [
                'daedalusConfig' => 'default',
                'difficultyConfig' => 'default',
                'name' => 'default',
                'characterConfigs' => [
                    'andie',
                    'chun',
                    'chao',
                    'derek',
                    'eleesha',
                    'finola',
                    'frieda',
                    'gioele',
                    'hua',
                    'ian',
                    'janice',
                    'jin_su',
                    'kuan_ti',
                    'paola',
                    'raluca',
                    'roland',
                    'stephen',
                    'terrence',
                ],
                'consumableDiseaseConfigs' => [
                    'creepnut_default',
                    'meztine_default',
                    'guntiflop_default',
                    'ploshmina_default',
                    'precati_default',
                    'bottine_default',
                    'fragilane_default',
                    'anemole_default',
                    'peniraft_default',
                    'kubinus_default',
                    'caleboot_default',
                    'filandra_default',
                    'jumpkin_default',
                    'alien_steak_default',
                    'supervitamin_bar_default',
                    'bacta_default',
                    'betapropyl_default',
                    'eufurylate_default',
                    'newke_default',
                    'phuxx_default',
                    'pinq_default',
                    'pymp_default',
                    'rosebud_default',
                    'soma_default',
                    'spyce_default',
                    'twinoid_default',
                    'xenox_default',
                ],
                'diseaseCauseConfigs' => [
                    'alien_fruit_default',
                    'perished_food_default',
                    'cat_allergy_cause_default',
                    'cycle_default',
                    'cycle_low_morale_default',
                    'make_sick_default',
                    'surgery_default',
                    'infection_default',
                    'sex_default',
                    'trauma_default',
                    'contact_default',
                    'exploration_default',
                    'alien_fight_default',
                ],
                'diseaseConfigs' => [
                    'food_poisoning_default',
                    'vitamin_deficiency_default',
                    'tapeworm_default',
                    'syphilis_default',
                    'space_rabies_default',
                    'smallpox_default',
                    'slight_nausea_default',
                    'skin_inflammation_default',
                    'sinus_storm_default',
                    'sepsis_default',
                    'rubella_default',
                    'rejuvenation_default',
                    'quincks_oedema_default',
                    'mush_allergy_default',
                    'migraine_default',
                    'junkbumpkinitis_default',
                    'gastroenteritis_default',
                    'fungic_infection_default',
                    'flu_default',
                    'extreme_tinnitus_default',
                    'cold_default',
                    'cat_allergy_default',
                    'black_bite_default',
                    'acid_reflux_default',
                    'broken_finger_default',
                    'broken_foot_default',
                    'broken_leg_default',
                    'broken_ribs_default',
                    'bruised_shoulder_default',
                    'burns_50_of_body_default',
                    'burns_90_of_body_default',
                    'burnt_arms_default',
                    'burnt_hand_default',
                    'burst_nose_default',
                    'busted_arm_joint_default',
                    'busted_shoulder_default',
                    'critical_haemorrhage_default',
                    'haemorrhage_default',
                    'damaged_ears_default',
                    'destroyed_ears_default',
                    'dysfunctional_liver_default',
                    'head_trauma_default',
                    'implanted_bullet_default',
                    'inner_ear_damaged_default',
                    'mashed_foot_default',
                    'mashed_hand_default',
                    'missing_finger_default',
                    'open_air_brain_default',
                    'punctured_lung_default',
                    'mashed_arms_default',
                    'mashed_legs_default',
                    'torn_tongue_default',
                    'broken_shoulder_default',
                    'agoraphobia_default',
                    'ailurophobia_default',
                    'chronic_migraine_default',
                    'chronic_vertigo_default',
                    'coprolalia_default',
                    'crabism_default',
                    'depression_default',
                    'paranoia_default',
                    'psychotic_episodes_default',
                    'spleen_default',
                    'vertigo_default',
                    'weapon_phobia_default',
                ],
                'statusConfigs' => [
                    'alien_artefact_default',
                    'heavy_default',
                    'module_access_default',
                    'hidden_default',
                    'broken_default',
                    'unstable_default',
                    'hazardous_default',
                    'decomposing_default',
                    'frozen_default',
                    'plant_thirsty_default',
                    'plant_dry_default',
                    'plant_diseased_default',
                    'document_content_default',
                    'reinforced_default',
                    'antisocial_default',
                    'berzerk_default',
                    'brainsync_default',
                    'burdened_default',
                    'demoralized_default',
                    'dirty_default',
                    'disabled_default',
                    'focused_default',
                    'full_stomach_default',
                    'gagged_default',
                    'germaphobe_default',
                    'guardian_default',
                    'highly_inactive_default',
                    'hyperactive_default',
                    'immunized_default',
                    'inactive_default',
                    'lost_default',
                    'lying_down_default',
                    'multi_teamster_default',
                    'outcast_default',
                    'pacifist_default',
                    'pregnant_default',
                    'starving_default',
                    'starving_warning_default',
                    'stuck_in_the_ship_default',
                    'suicidal_default',
                    'WATCHED_PUBLIC_BROADCAST_default',
                    'attempt_default',
                    'electric_charges_antigrav_scooter_default',
                    'electric_charges_old_faithful_default',
                    'electric_charges_rocket_launcher_default',
                    'electric_charges_turret_command_default',
                    'electric_charges_microwave_default',
                    'electric_charges_coffee_machine_default',
                    'electric_charges_narcotic_distiller_default',
                    'electric_charges_blaster_default',
                    'sink_charge_default',
                    'fire_default',
                    'plant_young_default',
                    'eureka_moment_default',
                    'first_time_default',
                    'mush_default',
                    'contaminated_default',
                    'drug_eaten_default',
                    'did_the_thing_default',
                    'did_boring_speech_default',
                    'updating_default',
                    'already_washed_in_the_sink_default',
                    'talkie_screwed_default',
                    HunterStatusEnum::ASTEROID_TRUCE_CYCLES . '_default',
                    HunterStatusEnum::TRUCE_CYCLES . '_default',
                    PlayerStatusEnum::HAS_REJUVENATED . '_default',
                    EquipmentStatusEnum::PATROL_SHIP_ARMOR . '_default',
                    EquipmentStatusEnum::PATROL_SHIP_ARMOR . '_pasiphae_default',
                    'electric_charges_patrol_ship_default',
                    'traveling_default',
                    'no_gravity_default',
                    'no_gravity_repaired_default',
                    'in_orbit_default',
                    'exploration_oxygen_default',
                    'exploration_fuel_default',
                    'following_hunters_default',
                    'astronavigation_neron_cpu_priority_default',
                    'changed_cpu_priority_default',
                    'electric_charges_support_drone_default',
                    DaedalusStatusEnum::AUTO_WATERING_KILLED_FIRES . '_default',
                    PlaceStatusEnum::MUSH_TRAPPED->value . '_default',
                    EquipmentStatusEnum::JUKEBOX_SONG . '_default',
                    SkillPointsEnum::CONCEPTOR_POINTS->value,
                    SkillPointsEnum::SHOOTER_POINTS->value,
                    SkillPointsEnum::TECHNICIAN_POINTS->value,
                    SkillPointsEnum::IT_EXPERT_POINTS->value,
                    PlayerStatusEnum::HAS_CHITCHATTED . '_default',
                    SkillPointsEnum::BOTANIST_POINTS->value,
                    SkillPointsEnum::PILGRED_POINTS->value,
                    SkillPointsEnum::NURSE_POINTS->value,
                    PlayerStatusEnum::HAS_LEARNED_SKILL . '_default',
                    PlayerStatusEnum::GENIUS_IDEA . '_default',
                    PlayerStatusEnum::HAS_USED_GENIUS . '_default',
                    PlaceStatusEnum::CEASEFIRE->value . '_default',
                    PlayerStatusEnum::HAS_CEASEFIRED . '_default',
                    PlayerStatusEnum::PREVIOUS_ROOM . '_default',
                    PlayerStatusEnum::HAS_EXCHANGED_BODY . '_default',
                    PlayerStatusEnum::HAS_ISSUED_MISSION . '_default',
                    DaedalusStatusEnum::ZE_LIST_HAS_BEEN_PRINTED . '_default',
                    SkillPointsEnum::CHEF_POINTS->value,
                    PlaceStatusEnum::DELOGGED->value . '_default',
                    PlayerStatusEnum::HAS_USED_DELOG . '_default',
                    PlayerStatusEnum::HAS_USED_PUTSCH . '_default',
                    PlayerStatusEnum::PARIAH . '_default',
                    PlayerStatusEnum::SLIME_TRAP . '_default',
                    EquipmentStatusEnum::SLIMED . '_default',
                    PlayerStatusEnum::HAS_USED_MASS_GGEDON . '_default',
                    PlayerStatusEnum::HAS_READ_MAGE_BOOK . '_default',
                    PlayerStatusEnum::HAS_USED_OPPORTUNIST_AS_COMMANDER . '_default',
                    PlayerStatusEnum::HAS_USED_OPPORTUNIST_AS_NERON_MANAGER . '_default',
                    PlayerStatusEnum::HAS_USED_OPPORTUNIST_AS_COM_MANAGER . '_default',
                    EquipmentStatusEnum::TURBO_DRONE_UPGRADE . '_default',
                    EquipmentStatusEnum::FIREFIGHTER_DRONE_UPGRADE . '_default',
                    EquipmentStatusEnum::DRONE_REPAIR_FAILED_ATTEMPTS . '_default',
                    EquipmentStatusEnum::DRONE_EXTINGUISH_FAILED_ATTEMPTS . '_default',
                    EquipmentStatusEnum::PILOT_DRONE_UPGRADE . '_default',
                    EquipmentStatusEnum::SENSOR_DRONE_UPGRADE . '_default',
                    EquipmentStatusEnum::DRONE_SHOOT_HUNTER_FAILED_ATTEMPTS . '_default',
                    PlayerStatusEnum::CAT_OWNER . '_default',
                    PlayerStatusEnum::HAS_PETTED_CAT . '_default',
                    EquipmentStatusEnum::CAT_INFECTED . '_default',
                    PlayerStatusEnum::ANTIQUE_PERFUME_IMMUNIZED . '_default',
                    PlayerStatusEnum::HAS_DAUNTED . '_default',
                    PlayerStatusEnum::HAS_GEN_METAL . '_default',
                    PlayerStatusEnum::HAS_SABOTAGED_DOOR . '_default',
                    PlayerStatusEnum::FITFUL_SLEEP . '_default',
                    DaedalusStatusEnum::NERON_DEPRESSION . '_default',
                    DaedalusStatusEnum::EDEN_COMPUTED . '_default',
                    'container_3_charges_default',
                    'container_4_charges_default',
                    'container_1_charge_daily_default',
                    PlayerStatusEnum::CONTACTED_SOL_TODAY . '_default',
                    DaedalusStatusEnum::LINK_WITH_SOL_ESTABLISHED_ONCE . '_default',
                    DaedalusStatusEnum::REBEL_BASE_CONTACT_DURATION . '_default',
                    DaedalusStatusEnum::GHOST_SAMPLE . '_default',
                    DaedalusStatusEnum::GHOST_CHUN . '_default',
                    HunterStatusEnum::AGGROED . '_default',
                    PlayerStatusEnum::BEGINNER . '_default',
                    PlayerStatusEnum::SELECTED_FOR_STEEL_PLATE . '_default',
                    PlayerStatusEnum::SELECTED_FOR_ANXIETY_ATTACK . '_default',
                    PlaceStatusEnum::SELECTED_FOR_JOLT->value . '_default',
                    PlaceStatusEnum::SELECTED_FOR_ELECTROCUTION->value . '_default',
                    PlaceStatusEnum::SELECTED_FOR_FIRE->value . '_default',
                    PlayerStatusEnum::SELECTED_FOR_BOARD_DISEASE . '_default',
                    PlayerStatusEnum::HAS_GAINED_COMMANDER_TITLE . '_default',
                    PlayerStatusEnum::HAS_GAINED_NERON_MANAGER_TITLE . '_default',
                    PlayerStatusEnum::HAS_GAINED_COM_MANAGER_TITLE . '_default',
                    PlayerStatusEnum::POINTLESS_PLAYER . '_default',
                    DaedalusStatusEnum::FIRST_STARMAP_FRAGMENT . '_default',
                    PlayerStatusEnum::PERSONAL_TRIUMPH_REGRESSION . '_default',
                    PlayerStatusEnum::FIRST . '_default',
                    PlayerStatusEnum::HAS_ADAPTED_EPIGENETICS . '_default',
                    PlayerStatusEnum::IS_ANONYMOUS . '_default',
                    DaedalusStatusEnum::COMMUNICATIONS_EXPERT . '_default',
                    PlayerStatusEnum::HAS_USED_FERTILE_TODAY . '_default',
                    PlayerStatusEnum::HAS_USED_TRAITOR_THIS_EXPEDITION . '_default',
                    PlayerStatusEnum::HAS_EXTRA_MUSH_SLOT_ANNIVERSARY . '_default',
                    ItemEnum::ANTIQUE_PERFUME_ITEM . '_charge_default',
                    PlayerStatusEnum::HAS_READ_SCHOOLBOOKS_ANNIVERSARY . '_default',
                    DaedalusStatusEnum::REMOVED_COMPLETELY_REVEALED_PLANETS . '_default',
                    EquipmentStatusEnum::EVIL_DRONE_TARGET . '_default',
                    EquipmentStatusEnum::ELECTRIC_CHARGES . '_' . ItemEnum::EVIL_DRONE . '_default',
                    PlayerStatusEnum::HAS_USED_MYCOSCAN . '_default',
                ],
                'triumphConfigs' => array_map(static fn (TriumphConfigDto $triumphConfig) => $triumphConfig->name->toConfigKey('default'), TriumphConfigData::getAll()),
                'hunterConfigs' => [
                    HunterEnum::ASTEROID . '_default',
                    HunterEnum::DICE . '_default',
                    HunterEnum::HUNTER . '_default',
                    HunterEnum::SPIDER . '_default',
                    HunterEnum::TRAX . '_default',
                    HunterEnum::TRANSPORT . '_default',
                ],
                'planetSectorConfigs' => [
                    PlanetSectorEnum::LANDING . '_default',
                    PlanetSectorEnum::FOREST . '_default',
                    PlanetSectorEnum::MOUNTAIN . '_default',
                    PlanetSectorEnum::SWAMP . '_default',
                    PlanetSectorEnum::DESERT . '_default',
                    PlanetSectorEnum::OCEAN . '_default',
                    PlanetSectorEnum::CAVE . '_default',
                    PlanetSectorEnum::RUMINANT . '_default',
                    PlanetSectorEnum::PREDATOR . '_default',
                    PlanetSectorEnum::INTELLIGENT . '_default',
                    PlanetSectorEnum::INSECT . '_default',
                    PlanetSectorEnum::MANKAROG . '_default',
                    PlanetSectorEnum::HYDROCARBON . '_default',
                    PlanetSectorEnum::OXYGEN . '_default',
                    PlanetSectorEnum::COLD . '_default',
                    PlanetSectorEnum::HOT . '_default',
                    PlanetSectorEnum::STRONG_WIND . '_default',
                    PlanetSectorEnum::SEISMIC_ACTIVITY . '_default',
                    PlanetSectorEnum::VOLCANIC_ACTIVITY . '_default',
                    PlanetSectorEnum::RUINS . '_default',
                    PlanetSectorEnum::WRECK . '_default',
                    PlanetSectorEnum::FRUIT_TREES . '_default',
                    PlanetSectorEnum::LOST . '_default',
                    PlanetSectorEnum::CRISTAL_FIELD . '_default',
                ],
                'titleConfigs' => [
                    TitleEnum::COMMANDER,
                    TitleEnum::NERON_MANAGER,
                    TitleEnum::COM_MANAGER,
                ],
                'projectConfigs' => [
                    ProjectName::AUTO_WATERING,
                    ProjectName::AUXILIARY_TERMINAL,
                    ProjectName::BRIC_BROC,
                    ProjectName::CHIPSET_ACCELERATION,
                    ProjectName::DISMANTLING,
                    ProjectName::DOOR_SENSOR,
                    ProjectName::EQUIPMENT_SENSOR,
                    ProjectName::EXTRA_HYDROPONPOTS,
                    ProjectName::FIRE_SENSOR,
                    ProjectName::HEAT_LAMP,
                    ProjectName::PILGRED,
                    ProjectName::PLASMA_SHIELD,
                    ProjectName::THALASSO,
                    ProjectName::TRAIL_REDUCER,
                    ProjectName::MAGNETIC_NET,
                    ProjectName::ICARUS_ANTIGRAV_PROPELLER,
                    ProjectName::FISSION_COFFEE_ROASTER,
                    ProjectName::ARMOUR_CORRIDOR,
                    ProjectName::CALL_OF_DIRTY,
                    ProjectName::EXTRA_DRONE,
                    ProjectName::PATROLSHIP_BLASTER_GUN,
                    ProjectName::BAY_DOOR_XXL,
                    ProjectName::TRASH_LOAD,
                    ProjectName::FOOD_RETAILER,
                    ProjectName::AUTO_RETURN_ICARUS,
                    ProjectName::RADAR_TRANS_VOID,
                    ProjectName::NERON_TARGETING_ASSIST,
                    ProjectName::WHOS_WHO,
                    ProjectName::HYDROPONIC_INCUBATOR,
                    ProjectName::ICARUS_LAVATORY,
                    ProjectName::ICARUS_LARGER_BAY,
                    ProjectName::PATROL_SHIP_LAUNCHER,
                    ProjectName::NERON_PROJECT_THREAD,
                    ProjectName::TURRET_EXTRA_FIRE_RATE,
                    ProjectName::QUANTUM_SENSORS,
                    ProjectName::PATROLSHIP_EXTRA_AMMO,
                    ProjectName::NOISE_REDUCER,
                    ProjectName::APERO_KITCHEN,
                    ProjectName::FLOOR_HEATING,
                    ProjectName::PARASITE_ELIM,
                    ProjectName::OXY_MORE,
                    ProjectName::BEAT_BOX,
                    ProjectName::ANABOLICS,
                    ProjectName::ANTISPORE_GAS,
                    ProjectName::CONSTIPASPORE_SERUM,
                    ProjectName::CREATE_MYCOSCAN,
                    ProjectName::GUARANA_CAPPUCCINO,
                    ProjectName::MERIDON_SCRAMBLER,
                    ProjectName::MUSH_HUNTER_ZC16H,
                    ProjectName::MUSH_LANGUAGE,
                    ProjectName::MUSH_RACES,
                    ProjectName::MUSH_REPRODUCTIVE_SYSTEM,
                    ProjectName::MUSHICIDE_SOAP,
                    ProjectName::MUSHOVORE_BACTERIA,
                    ProjectName::MYCOALARM,
                    ProjectName::NARCOTICS_DISTILLER,
                    ProjectName::NATAMY_RIFLE,
                    ProjectName::NCC_CONTACT_LENSES,
                    ProjectName::PATULINE_SCRAMBLER,
                    ProjectName::PERPETUAL_HYDRATION,
                    ProjectName::PHEROMODEM,
                    ProjectName::RETRO_FUNGAL_SERUM,
                    ProjectName::SPORE_SUCKER,
                    ProjectName::SUPER_CALCULATOR,
                    ProjectName::TESLA_SUP2X,
                    ProjectName::ULTRA_HEALING_POMADE,
                    ProjectName::ZETA_WAVES,
                ],
                'skillConfigs' => [
                    SkillEnum::ANONYMUSH,
                    SkillEnum::ANTIQUE_PERFUME,
                    SkillEnum::APPRENTICE,
                    SkillEnum::ASTROPHYSICIST,
                    SkillEnum::BACTEROPHILIAC,
                    SkillEnum::BIOLOGIST,
                    SkillEnum::BOTANIST,
                    SkillEnum::BYPASS,
                    SkillEnum::CAFFEINE_JUNKIE,
                    SkillEnum::CHEF,
                    SkillEnum::COLD_BLOODED,
                    SkillEnum::CONCEPTOR,
                    SkillEnum::CONFIDENT,
                    SkillEnum::CRAZY_EYE,
                    SkillEnum::CREATIVE,
                    SkillEnum::DEFACER,
                    SkillEnum::DETACHED_CREWMEMBER,
                    SkillEnum::DETERMINED,
                    SkillEnum::DEVOTION,
                    SkillEnum::DOORMAN,
                    SkillEnum::DIPLOMAT,
                    SkillEnum::DISHEARTENING_CONTACT,
                    SkillEnum::EXPERT,
                    SkillEnum::EPIGENETICS,
                    SkillEnum::FERTILE,
                    SkillEnum::FIREFIGHTER,
                    SkillEnum::FRUGIVORE,
                    SkillEnum::FUNGAL_KITCHEN,
                    SkillEnum::GENIUS,
                    SkillEnum::GREEN_JELLY,
                    SkillEnum::GREEN_THUMB,
                    SkillEnum::GUNNER,
                    SkillEnum::HARD_BOILED,
                    SkillEnum::HYGIENIST,
                    SkillEnum::INFECTOR,
                    SkillEnum::INTIMIDATING,
                    SkillEnum::IT_EXPERT,
                    SkillEnum::LEADER,
                    SkillEnum::LETHARGY,
                    SkillEnum::LOGISTICS_EXPERT,
                    SkillEnum::MANKIND_ONLY_HOPE,
                    SkillEnum::MASSIVE_MUSHIFICATION,
                    SkillEnum::MEDIC,
                    SkillEnum::METALWORKER,
                    SkillEnum::MOTIVATOR,
                    SkillEnum::MYCELIUM_SPIRIT,
                    SkillEnum::MYCOLOGIST,
                    SkillEnum::NERON_DEPRESSION,
                    SkillEnum::NERON_ONLY_FRIEND,
                    SkillEnum::NIMBLE_FINGERS,
                    SkillEnum::NIGHTMARISH,
                    SkillEnum::NINJA,
                    SkillEnum::NURSE,
                    SkillEnum::OBSERVANT,
                    SkillEnum::OCD,
                    SkillEnum::OPPORTUNIST,
                    SkillEnum::OPTIMIST,
                    SkillEnum::PANIC,
                    SkillEnum::PARANOID,
                    SkillEnum::PHAGOCYTE,
                    SkillEnum::PHYSICIST,
                    SkillEnum::PILOT,
                    SkillEnum::POLITICIAN,
                    SkillEnum::POLYMATH,
                    SkillEnum::POLYVALENT,
                    SkillEnum::PRESENTIMENT,
                    SkillEnum::PYROMANIAC,
                    SkillEnum::RADIO_EXPERT,
                    SkillEnum::RADIO_PIRACY,
                    SkillEnum::REBEL,
                    SkillEnum::ROBOTICS_EXPERT,
                    SkillEnum::SABOTEUR,
                    SkillEnum::SELF_SACRIFICE,
                    SkillEnum::SHOOTER,
                    SkillEnum::SHRINK,
                    SkillEnum::SLIMETRAP,
                    SkillEnum::SNEAK,
                    SkillEnum::SOLID,
                    SkillEnum::SPLASHPROOF,
                    SkillEnum::SPRINTER,
                    SkillEnum::STRATEGURU,
                    SkillEnum::SURVIVALIST,
                    SkillEnum::TECHNICIAN,
                    SkillEnum::TORTURER,
                    SkillEnum::TRACKER,
                    SkillEnum::TRAITOR,
                    SkillEnum::TRANSFER,
                    SkillEnum::TRAPPER,
                    SkillEnum::U_TURN,
                    SkillEnum::VICTIMIZER,
                    SkillEnum::WRESTLER,
                ],
                'rebelBaseConfigs' => [
                    RebelBaseEnum::WOLF,
                    RebelBaseEnum::SIRIUS,
                    RebelBaseEnum::CENTAURI,
                    RebelBaseEnum::KALADAAN,
                    RebelBaseEnum::LUYTEN_CETI,
                    RebelBaseEnum::CYGNI,
                    RebelBaseEnum::ERIDIANI,
                ],
                'xylophConfigs' => [
                    XylophEnum::BLUEPRINTS,
                    XylophEnum::COOK,
                    XylophEnum::DISK,
                    XylophEnum::KIVANC,
                    XylophEnum::GHOST_CHUN,
                    XylophEnum::GHOST_SAMPLE,
                    XylophEnum::LIST,
                    XylophEnum::MAGE_BOOKS,
                    XylophEnum::MAGNETITE,
                    XylophEnum::NOTHING,
                    XylophEnum::SNOW,
                    XylophEnum::VERSION,
                ],
                'tradeConfigs' => [
                    TradeEnum::FOREST_DEAL,
                    TradeEnum::PILGREDISSIM,
                    TradeEnum::GOOD_PROJECTIONS,
                    TradeEnum::TECHNO_REWRITE,
                    TradeEnum::HUMAN_VS_FUEL,
                    TradeEnum::HUMAN_VS_OXY,
                    TradeEnum::HUMAN_VS_TREE,
                ],
                'specialOptions' => [
                    GameConfigEnum::OPTION_RANDOM_SPORE,
                ],
            ],
        ];
    }
}
