Mush\Equipment\Entity\Config\EquipmentConfig:
  properties:
    name:
      - NotBlank: ~
      - Length:
          max: 48
      - Type: string  
    equipmentName:
      - NotBlank: ~
      - Length:
          max: 48
      - Type: string    
    isFireDestroyable:
      - Type: boolean
    isFireBreakable:
      - Type: boolean
    isBreakable:
      - Type: boolean
    dismountedProducts:
      - Type: array
    isPersonal:
      - Type: boolean