Mush\Equipment\Entity\Config\EquipmentConfig:
  properties:
    name:
      - NotBlank: ~
      - Length:
          max: 48
      - Type: string  
    equipmentName:
      - NotBlank: ~
      - Length:
          max: 48
      - Type: string    
    breakableType:
      - NotBlank: ~
      - Type: string
    dismountedProducts:
      - Type: array
    isPersonal:
      - Type: boolean