Mush\Equipment\Entity\Config\EquipmentConfig:
  properties:
    name:
      - NotBlank: ~
      - Length:
          max: 48
      - Type: string  
    equipmentName:
      - NotBlank: ~
      - Length:
          max: 48
      - Type: string    
    breakableType:
      - NotBlank: ~
      - Type: string
    dismountedProducts:
      - Type: array
    isPersonal:
      - Type: boolean
    collectScrapNumber:
      - Type: array
    collectScrapPatrolShipDamage:
      - Type: array
    collectScrapPlayerDamage:
      - Type: array
    failedManoeuvreDaedalusDamage:
      - Type: array
    failedManoeuvrePatrolShipDamage:
      - Type: array
    failedManoeuvrePlayerDamage:
      - Type: array