Mush\Game\Entity\GameConfig:
  properties:
    name:
      - NotBlank: ~
      - Length:
          max: 48
      - Type: string
    nbMush:
      - NotBlank: ~
      - PositiveOrZero: ~
      - Type: integer
    cyclePerGameDay:
      - NotBlank: ~
      - Positive: ~
      - Type: integer
    cycleLength:
      - NotBlank: ~
      - Positive: ~
      - Type: integer
    timeZone:
      - NotBlank: ~
      - Type: string
    maxNumberPrivateChannel:
      - NotBlank: ~
      - PositiveOrZero: ~
      - Type: integer
    language:
      - NotBlank: ~
      - Type: string
    initHealthPoint:
      - NotBlank: ~
      - Positive: ~
      - Type: integer
    maxHealthPoint:
      - NotBlank: ~
      - Positive: ~
      - Type: integer
    initMoralPoint:
      - NotBlank: ~
      - Positive: ~
      - Type: integer
    maxMoralPoint:
      - NotBlank: ~
      - Positive: ~
      - Type: integer
    initSatiety:
      - NotBlank: ~
      - Type: integer
    initActionPoint:
      - NotBlank: ~
      - PositiveOrZero: ~
      - Type: integer
    maxActionPoint:
      - NotBlank: ~
      - Positive: ~
      - Type: integer
    initMovementPoint:
      - NotBlank: ~
      - PositiveOrZero: ~
      - Type: integer
    maxMovementPoint:
      - NotBlank: ~
      - Positive: ~
      - Type: integer
    maxItemInInventory:
      - NotBlank: ~
      - PositiveOrZero: ~
      - Type: integer
