Mush\Hunter\Entity\Config\HunterConfig:
  properties:
    name:
      - NotBlank: ~
      - Length:
          max: 48
      - Type: string  
    waveConfigName:
      - NotBlank: ~
      - Length:
          max: 48
      - Type: string    
  