Mush\Modifier\Entity\ModifierCondition:
  properties:
    name:
      - NotBlank: ~
      - Length:
          max: 48
      - Type: string
    condition:
      - NotBlank: ~
      - Type: string
    value:
      - NotBlank: ~
      - Type: integer
    modifierConditions: ~