Mush\Modifier\Entity\ModifierConfig:
  properties:
    name:
      - NotBlank: ~
      - Type: string
    delta:
      - NotBlank: ~
      - Type: float
    targetVariable:
      - NotBlank: ~
      - Type: string
    targetEvent:
      - NotBlank: ~
      - Type: string
    modifierHolderClass:
      - NotBlank: ~
      - Type: string
    mode:
      - NotBlank: ~
      - Type: string
