Mush\Modifier\Entity\ModifierActivationRequirement:
  properties:
    name:
      - NotBlank: ~
      - Length:
          max: 48
      - Type: string
    activationRequirement:
      - NotBlank: ~
      - Type: string
    value:
      - NotBlank: ~
      - Type: integer