Mush\Modifier\Entity\Config\ModifierConfig:
  properties:
    name:
      - Length:
          max: 48
      - Type: string
    value:
      - NotBlank: ~
      - Type: float
    reach:
      - NotBlank: ~
      - Type: string
    mode:
      - NotBlank: ~
      - Type: string
