Mush\Equipment\Entity\Config\PatrolShipConfig:
  properties:
    collectScrapNumber:
      - Type: array
    collectScrapPatrolShipDamage:
      - Type: array
    collectScrapPlayerDamage:
      - Type: array
    failedManoeuvreDaedalusDamage:
      - Type: array
    failedManoeuvrePatrolShipDamage:
      - Type: array
    failedManoeuvrePlayerDamage:
      - Type: array