Mush\Disease\Entity\Config\SymptomConfig:
  properties:                          # optional
    name:
      - Type: string
    symptomName:
      - Type: string
    trigger:
      - Type: string
    visibility:
      - Type: string