Mush\Disease\Entity\Config\SymptomActivationRequirement:
  properties:                        # optional
    name:
      - Type: string
    activationRequirementName:
      - Type: string
    activationRequirement:
      - Type: string
    value:
      - Type: integer

