Mush\Modifier\Entity\Config\TriggerEventModifierConfig:
  properties:
    name:
      - NotBlank: ~
      - Type: string
    modifierName:
      - Type: string
    modifierRange:
      - NotBlank: ~
      - Type: string
    targetEvent:
      - NotBlank: ~
      - Type: string
    applyOnTarget:
      - NotBlank: ~
      - Type: boolean
    tagConstraints:
      - Type: array
