Mush\Modifier\Entity\Config\TriggerEventModifierConfig:
  properties:
    name:
      - NotBlank: ~
      - Type: string
    modifierName:
      - Type: string
    delta:
      - Type: int
    targetVariable:
      - Type: string
    targetEvent:
      - NotBlank: ~
      - Type: string
    modifierHolderClass:
      - NotBlank: ~
      - Type: string
    triggeredEvent:
      - NotBlank: ~
      - Type: string
    applyOnActionParameter:
      - NotBlank: ~
      - Type: boolean
