Mush\Triumph\Entity\TriumphConfig:
  properties:
    name:
      - NotBlank: ~
      - Type: string
    scope:
      - NotBlank: ~
      - Type: string
    target:
      - NotBlank: ~
      - Type: string
    quantity:
      - NotBlank: ~
      - Type: integer
    visibility:
      - NotBlank: ~
      - Type: string
    regressiveFactor:
      - NotBlank: ~
      - Type: integer
    hasComputeStrategy:
      - NotBlank: ~
      - Type: boolean
    applicationStrategies:
      - NotBlank: ~
      - Type: array
