Mush\Triumph\Entity\TriumphConfig:
  properties:
    key:
      - NotBlank: ~
      - Type: string
    name:
      - NotBlank: ~
      - Type: Mush\Triumph\Enum\TriumphEnum
    scope:
      - NotBlank: ~
      - Type: Mush\Triumph\Enum\TriumphScope
    targetedEvent:
      - NotBlank: ~
      - Type: string
    targetedEventExpectedTags:
      - NotBlank: ~
      - Type: array
    target:
      - NotBlank: ~
      - Type: string
    quantity:
      - NotBlank: ~
      - Type: integer
    visibility:
      - NotBlank: ~
      - Type: Mush\Triumph\Enum\TriumphVisibility
    regressiveFactor:
      - NotBlank: ~
      - Type: integer
    registerWhenZero:
      - NotBlank: ~
      - Type: boolean
