services:
  mush-apache:
    ports:
      - "8080:80"
      - "8443:8443"

  mush-php:
    build:
      args:
        - UID=1000
        - GID=1000

  mush-database:
    ports:
      - "5432:5432"

  mush-front:
    ports:
      - "80:5173"
    build:
      args:
        - UID=1000
        - GID=1000

  mush-eternaltwin:
    ports:
      - "50320:50320"
    build:
      args:
        - UID=1000
        - GID=1000
