services:
  mush-apache:
    ports:
      - 8080:80
      - 8443:8443

  mush-php:
    build:
      args:
        - UID=33333
        - GID=33333

  mush-database:
    ports:
      - 5432:5432

  mush-front:
    ports:
      - 4173:5173
    build:
      args:
        - UID=33333
        - GID=33333

  mush-eternaltwin:
    ports:
      - 50320:50320
    build:
      args:
        - UID=33333
        - GID=33333
