services:
  mush_apache:
    ports:
      - 8080:80
      - 8443:8443

  mush_php:
    build:
      args:
        - UID=33333
        - GID=33333

  mush_database:
    ports:
      - 5432:5432

  mush_front:
    ports:
      - 4173:5173
    build:
      args:
        - UID=33333
        - GID=33333

  eternaltwin:
    ports:
      - 50320:50320
      - 50321:50321
    build:
      args:
        - UID=33333
        - GID=33333
