version: '3'

services:
  mush_apache:
    ports:
      - "8080:80"
      - "8443:8443"

  mush_php:
    build:
      args:
        - UID=1000
        - GID=1000

  mush_database:
    ports:
      - "5432:5432"

  mush_front:
    ports:
      - "80:5173"
    build:
      args:
        - UID=1000
        - GID=1000

  eternal_twin:
    ports:
      - "50320:50320"
    build:
      args:
        - UID=1000
        - GID=1000
