Mush\Action\Entity\ActionConfig:
  attributes:
    pagination_items_per_page: 25
    normalization_context:
      groups:
      - action_read
    denormalization_context:
      groups:
      - action_write
  operations:
    ApiPlatform\Metadata\GetCollection:
      filters:
      - default.search_filter
      - default.order_filter
      security: is_granted("ROLE_ADMIN")
    ApiPlatform\Metadata\Post:
      security: is_granted("ROLE_ADMIN")
    ApiPlatform\Metadata\Get: {}
    ApiPlatform\Metadata\Put:
      security: is_granted("ROLE_ADMIN")
