Mush\Action\Entity\ActionCost:
  shortName: 'ActionCost'
  description: 'eMush Actions Cost'
  attributes:
    pagination_items_per_page: 25
    normalization_context:
      groups: [ 'action_cost_read' ]
    denormalization_context:
      groups: [ 'action_cost_write' ]
  collectionOperations:
    get:
      filters: [ 'default.search_filter', 'default.order_filter' ]
  itemOperations:
    get: ~
    put:
      security: 'is_granted("ROLE_ADMIN")'
