Mush\Equipment\Entity\Mechanics\Book:
  attributes:
    pagination_items_per_page: 25
    normalization_context:
      groups:
      - book_read
    denormalization_context:
      groups:
      - book_write
  operations:
    ApiPlatform\Metadata\GetCollection:
      filters:
      - default.search_filter
      - default.order_filter
    ApiPlatform\Metadata\Post:
      security: is_granted("ROLE_ADMIN")
    ApiPlatform\Metadata\Get:
      security: is_granted("ROLE_ADMIN")
    ApiPlatform\Metadata\Put:
      security: is_granted("ROLE_ADMIN")
