Mush\Equipment\Entity\Mechanics\Book:
  shortName: 'Book'
  description: 'eMush Book'
  attributes:
    pagination_items_per_page: 25
    normalization_context:
      groups: [ 'book_read' ]
    denormalization_context:
      groups: [ 'book_write' ]
  collectionOperations:
    get:
      filters: [ 'default.search_filter', 'default.order_filter' ]
    post:
      security: 'is_granted("ROLE_ADMIN")'
  itemOperations:
    get:
      security: 'is_granted("ROLE_ADMIN")'
    put:
      security: 'is_granted("ROLE_ADMIN")'
