Mush\Status\Entity\Config\ChargeStatusConfig:
  attributes:
    pagination_items_per_page: 25
    security: is_granted("ROLE_MODERATOR")
    normalization_context:
      groups:
      - status_config_read
    denormalization_context:
      groups:
      - status_config_write
  operations:
    ApiPlatform\Metadata\GetCollection:
      security: is_granted("ROLE_MODERATOR")
      filters:
      - default.search_filter
      - default.order_filter
    ApiPlatform\Metadata\Get:
      security: is_granted("ROLE_MODERATOR")
    ApiPlatform\Metadata\Put:
      security: is_granted("ROLE_ADMIN")
