Mush\Status\Entity\Config\ChargeStatusConfig:
  shortName: 'ChargeStatusConfig'
  description: 'eMush StatusConfig'
  attributes:
    pagination_items_per_page: 25
    security: 'is_granted("ROLE_MODERATOR")'
    normalization_context:
      groups: [ 'status_config_read' ]
    denormalization_context:
      groups: [ 'status_config_write' ]
  collectionOperations:
    get:
      security: 'is_granted("ROLE_MODERATOR")'
      filters: [ 'default.search_filter', 'default.order_filter' ]
  itemOperations:
    get:
      security: 'is_granted("ROLE_MODERATOR")'
    put:
      security: 'is_granted("ROLE_ADMIN")'
