Mush\Disease\Entity\ConsumableDiseaseAttribute:
  shortName: 'ConsumableDiseaseAttribute'
  description: 'eMush Consumable Disease Attribute'
  attributes:
    pagination_items_per_page: 25
    normalization_context:
      groups: [ 'consumable_disease_attribute_read' ]
    denormalization_context:
      groups: [ 'consumable_disease_attribute_write' ]
  collectionOperations:
    get:
      filters: [ 'default.search_filter', 'default.order_filter' ]
  itemOperations:
    get: 
      security: 'is_granted("ROLE_ADMIN")'


