Mush\Disease\Entity\Config\ConsumableDiseaseConfig:
  attributes:
    pagination_items_per_page: 25
    normalization_context:
      groups:
      - consumable_disease_config_read
    denormalization_context:
      groups:
      - consumable_disease_config_write
  operations:
    ApiPlatform\Metadata\GetCollection:
      filters:
      - default.search_filter
      - default.order_filter
      security: is_granted("ROLE_ADMIN")
    ApiPlatform\Metadata\Post:
      security: is_granted("ROLE_ADMIN")
    ApiPlatform\Metadata\Get:
      security: is_granted("ROLE_ADMIN")
    ApiPlatform\Metadata\Put:
      security: is_granted("ROLE_ADMIN")
