Mush\Disease\Entity\ConsumableDiseaseAttribute:
  attributes:
    pagination_items_per_page: 25
    normalization_context:
      groups:
      - consumable_disease_attribute_read
    denormalization_context:
      groups:
      - consumable_disease_attribute_write
  operations:
    ApiPlatform\Metadata\GetCollection:
      filters:
      - default.search_filter
      - default.order_filter
    ApiPlatform\Metadata\Get:
      security: is_granted("ROLE_ADMIN")
