Mush\Game\Entity\AbstractEventConfig:
  attributes:
    pagination_items_per_page: 25
    security: is_granted("ROLE_USER")
    normalization_context:
      groups:
      - event_config_read
    denormalization_context:
      groups:
      - event_config_write
  operations:
    ApiPlatform\Metadata\GetCollection:
      filters:
      - default.search_filter
      - default.order_filter
      security: is_granted("ROLE_MODERATOR")
    ApiPlatform\Metadata\Post:
      security: is_granted("ROLE_ADMIN")
    ApiPlatform\Metadata\Get:
      security: is_granted("ROLE_MODERATOR")
    ApiPlatform\Metadata\Put:
      security: is_granted("ROLE_ADMIN")
