Mush\Game\Entity\AbstractEventConfig:
  shortName: 'EventConfig'
  description: 'eMush AbstractEventConfig'
  attributes:
    pagination_items_per_page: 25
    security: 'is_granted("ROLE_USER")'
    normalization_context:
      groups: [ 'event_config_read' ]
    denormalization_context:
      groups: [ 'event_config_write' ]
  collectionOperations:
    get:
      filters: [ 'default.search_filter', 'default.order_filter' ]
      security: 'is_granted("ROLE_MODERATOR")'
    post:
      security: 'is_granted("ROLE_ADMIN")'
  itemOperations:
    get:
      security: 'is_granted("ROLE_MODERATOR")'
    put:
      security: 'is_granted("ROLE_ADMIN")'