Mush\Game\Entity\GameConfig:
  shortName: 'GameConfig'
  description: 'eMush GameConfig'
  attributes:
    pagination_items_per_page: 25
    security: 'is_granted("ROLE_USER")'
    normalization_context:
      groups: [ 'game_config_read' ]
    denormalization_context:
      groups: [ 'game_config_write' ]
  collectionOperations:
    get: ~
  itemOperations:
    get: ~
    put:
      security: 'is_granted("ROLE_ADMIN")'
