Mush\Equipment\Entity\Mechanics\Gear:
  shortName: 'Gear'
  description: 'eMush Gear'
  attributes:
    pagination_items_per_page: 25
    normalization_context:
      groups: [ 'gear_read' ]
    denormalization_context:
      groups: [ 'gear_write' ]
  collectionOperations:
    get:
      filters: [ 'default.search_filter', 'default.order_filter' ]
    post:
      security: 'is_granted("ROLE_ADMIN")'
  itemOperations:
    get:
      security: 'is_granted("ROLE_ADMIN")'
    put:
      security: 'is_granted("ROLE_ADMIN")'
  properties:
    modifierConfigs:
      subresource:
        resourceClass: 'Mush\Modifier\Entity\ModifierConfig'
        collection: true
