Mush\Hunter\Entity\HunterWaveConfig:
  shortName: 'HunterWaveConfig'
  description: 'eMush HunterWaveConfig'
  attributes:
    pagination_items_per_page: 25
    security: 'is_granted("ROLE_USER")'
    normalization_context:
      groups: [ 'hunter_wave_config_read' ]
    denormalization_context:
      groups: [ 'hunter_wave_config_write' ]
  collectionOperations:
    get:
      filters: [ 'default.search_filter', 'default.order_filter' ]
    post:
      security: 'is_granted("ROLE_ADMIN")'
  itemOperations:
    get: 
      security: 'is_granted("ROLE_USER")'
    put:
      security: 'is_granted("ROLE_ADMIN")'