Mush\Equipment\Entity\Config\ItemConfig:
  shortName: 'ItemConfig'
  description: 'eMush Item Config'
  attributes:
    pagination_items_per_page: 25
    normalization_context:
      groups: [ 'item_config_read' ]
    denormalization_context:
      groups: [ 'item_config_write' ]
  collectionOperations:
    get:
      filters: [ 'default.search_filter', 'default.order_filter' ]
    post:
      security: 'is_granted("ROLE_ADMIN")'
  itemOperations:
    get:
