Mush\Equipment\Entity\Config\ItemConfig:
  shortName: 'ItemConfig'
  description: 'eMush Item Config'
  attributes:
    pagination_items_per_page: 25
    normalization_context:
      groups: [ 'item_config_read' ]
    denormalization_context:
      groups: [ 'item_config_write' ]
  collectionOperations:
    get:
      filters: [ 'default.search_filter', 'default.order_filter' ]
    post:
      security: 'is_granted("ROLE_ADMIN")'
  itemOperations:
    get:
      security: 'is_granted("ROLE_ADMIN")'
    put:
      security: 'is_granted("ROLE_ADMIN")'
  properties:
    mechanics:
      subresource:
        resourceClass: 'Mush\Equipment\Entity\EquipmentMechanic'
        collection: true
    actions:
      subresource:
        resourceClass: 'Mush\Action\Entity\Action'
        collection: true
    initStatus:
      subresource:
        resourceClass: 'Mush\Status\Entity\Config\StatusConfig'
        collection: true