Mush\MetaGame\Entity\ModerationSanction:
  attributes:
    pagination_items_per_page: 25
    normalization_context:
      groups:
      - moderation_sanction_read
  operations:
    ApiPlatform\Metadata\GetCollection:
      security: is_granted("ROLE_MODERATOR")
      filters:
      - adminSanction.order_filter
      - adminSanction.date_filter
      - adminSanction.search_filter
      - moderationSanction.boolean_filter
    ApiPlatform\Metadata\Get:
      security: is_granted("ROLE_MODERATOR")
