Mush\Modifier\Entity\ModifierCondition:
  shortName: 'ModifierCondition'
  description: 'eMush modifierCondition'
  attributes:
    pagination_items_per_page: 25
    security: 'is_granted("ROLE_MODERATOR")'
    normalization_context:
      groups: [ 'modifier_condition_read' ]
    denormalization_context:
      groups: [ 'modifier_condition_write' ]
  collectionOperations:
    get:
      security: 'is_granted("ROLE_MODERATOR")'
      filters: [ 'default.search_filter', 'default.order_filter' ]
  itemOperations:
    get:
      security: 'is_granted("ROLE_MODERATOR")'
    put:
      security: 'is_granted("ROLE_ADMIN")'
