Mush\Modifier\Entity\Config\ModifierActivationRequirement:
  attributes:
    pagination_items_per_page: 25
    security: is_granted("ROLE_MODERATOR")
    normalization_context:
      groups:
      - modifier_activation_requirement_read
    denormalization_context:
      groups:
      - modifier_activation_requirement_write
  operations:
    ApiPlatform\Metadata\GetCollection:
      security: is_granted("ROLE_MODERATOR")
      filters:
      - default.search_filter
      - default.order_filter
    ApiPlatform\Metadata\Post:
      security: is_granted("ROLE_ADMIN")
    ApiPlatform\Metadata\Get:
      security: is_granted("ROLE_MODERATOR")
    ApiPlatform\Metadata\Put:
      security: is_granted("ROLE_ADMIN")
