Mush\Modifier\Entity\Config\ModifierActivationRequirement:
  shortName: 'ModifierActivationRequirement'
  description: 'eMush modifierActivationRequirement'
  attributes:
    pagination_items_per_page: 25
    security: 'is_granted("ROLE_MODERATOR")'
    normalization_context:
      groups: [ 'modifier_activation_requirement_read' ]
    denormalization_context:
      groups: [ 'modifier_activation_requirement_write' ]
  collectionOperations:
    get:
      security: 'is_granted("ROLE_MODERATOR")'
      filters: [ 'default.search_filter', 'default.order_filter' ]
    post:
      security: 'is_granted("ROLE_ADMIN")'
  itemOperations:
    get:
      security: 'is_granted("ROLE_MODERATOR")'
    put:
      security: 'is_granted("ROLE_ADMIN")'
