Mush\Place\Entity\PlaceConfig:
  shortName: 'PlaceConfig'
  description: 'eMush PlaceConfig'
  attributes:
    pagination_items_per_page: 25
    normalization_context:
      groups: [ 'place_config_read' ]
    denormalization_context:
      groups: [ 'place_config_write' ]
  collectionOperations:
    get:
      filters: [ 'default.search_filter', 'default.order_filter' ]
    post:
      security: 'is_granted("ROLE_ADMIN")'
  itemOperations:
    get:
