Mush\Player\Entity\PlayerInfo:
  shortName: 'PlayerInfo'
  description: 'eMush PlayerInfo'
  attributes:
    pagination_items_per_page: 25
    security: 'is_granted("ROLE_MODERATOR")'
    normalization_context:
      groups: [ 'player_info_read' ]
  collectionOperations:
    get:
      filters: [ 
        'default.order_filter' , 
        'moderationPlayerInfo.search_filter' , 
        'moderationPlayerInfo.boolean_filter',
      ]
      security: 'is_granted("ROLE_MODERATOR")'
  itemOperations:
    get:
      security: 'is_granted("ROLE_MODERATOR")'
