Mush\Daedalus\Entity\RandomItemPlaces:
  shortName: 'RandomItemPlaces'
  description: 'eMush RandomItemPlaces'
  attributes:
    pagination_items_per_page: 25
    normalization_context:
      groups: [ 'random_item_place_read' ]
    denormalization_context:
      groups: [ 'random_item_place_write' ]
  collectionOperations:
    get:
      filters: [ 'default.search_filter', 'default.order_filter' ]
      security: 'is_granted("ROLE_ADMIN")'
    post:
      security: 'is_granted("ROLE_ADMIN")'
  itemOperations:
    get:
      security: 'is_granted("ROLE_ADMIN")'
    put:
      security: 'is_granted("ROLE_ADMIN")'
