Mush\Status\Entity\Config\StatusConfig:
  attributes:
    pagination_items_per_page: 25
    security: is_granted("ROLE_MODERATOR")
    normalization_context:
      groups:
      - status_config_read
    denormalization_context:
      groups:
      - status_config_write
  properties:
    modifierConfigs:
      subresource:
        resourceClass: Mush\Modifier\Entity\ModifierConfig
        collection: true
    actionConfigs:
      subresource:
        resourceClass: Mush\Action\Entity\ActionConfig
        collection: true
  operations:
    ApiPlatform\Metadata\GetCollection:
      filters:
      - default.search_filter
      - default.order_filter
      security: is_granted("ROLE_MODERATOR")
    ApiPlatform\Metadata\Post:
      security: is_granted("ROLE_ADMIN")
    ApiPlatform\Metadata\Get:
      security: is_granted("ROLE_MODERATOR")
    ApiPlatform\Metadata\Put:
      security: is_granted("ROLE_ADMIN")
