Mush\Disease\Entity\Config\SymptomActivationRequirement:
  shortName: 'SymptomActivationRequirement'
  description: 'eMush SymptomActivationRequirement'
  attributes:
    pagination_items_per_page: 25
    normalization_context:
      groups: [ 'symptom_activation_requirement_read' ]
    denormalization_context:
      groups: [ 'symptom_activation_requirement_write' ]
  collectionOperations:
    get:
      filters: [ 'default.search_filter', 'default.order_filter' ]
  itemOperations:
    get: 
      security: 'is_granted("ROLE_ADMIN")'
    put:
      security: 'is_granted("ROLE_ADMIN")'
