Mush\Disease\Entity\Config\SymptomCondition:
  shortName: 'SymptomCondition'
  description: 'eMush SymptomCondition'
  attributes:
    pagination_items_per_page: 25
    normalization_context:
      groups: [ 'symptom_condition_read' ]
    denormalization_context:
      groups: [ 'symptom_condition_write' ]
  collectionOperations:
    get:
      filters: [ 'default.search_filter', 'default.order_filter' ]
  itemOperations:
    get: 
      security: 'is_granted("ROLE_ADMIN")'
    put:
      security: 'is_granted("ROLE_ADMIN")'
