Mush\User\Entity\User:
  attributes:
    pagination_items_per_page: 25
    normalization_context:
      groups: [ 'user_read' ]
    denormalization_context:
      groups: [ 'user_write' ]
  operations:
    ApiPlatform\Metadata\GetCollection:
      security: 'is_granted("ROLE_MODERATOR")'
      filters: ['user.search_filter', 'user.order_filter']
    ApiPlatform\Metadata\Patch:
      security: 'is_granted("ROLE_ADMIN") and is_granted("EDIT_USER_ROLE", object)'
    ApiPlatform\Metadata\Get:
      security: 'is_granted("ROLE_USER") or object == user'