parameters:
  actions:
    move: Mush\Action\Actions\Move
    take: Mush\Action\Actions\Take
    drop: Mush\Action\Actions\Drop
    consume: Mush\Action\Actions\Consume
    read_book: Mush\Action\Actions\ReadBook
