services:
    _defaults:
        autowire: true
        autoconfigure: true

    Mush\Triumph\:
        resource: '../'
        exclude:
            - '../DependencyInjection/'
            - '../Entity/'
            - '../Kernel.php'
            - '../Tests/'