<?php

namespace Mush\Equipment\Enum;

class ContainerContentEnum
{
    public const FILTER_BY_CHARACTER = 'character';
    public const array SPACE_CAPSULE_CONTENT = [
        ItemEnum::FUEL_CAPSULE => 1,
        ItemEnum::OXYGEN_CAPSULE => 1,
        ItemEnum::METAL_SCRAPS => 1,
        ItemEnum::PLASTIC_SCRAPS => 1,
    ];

    public const array COFFEE_THERMOS_CONTENT = [
        [
            'item' => GameRationEnum::COFFEE,
            'quantity' => 1,
            'weight' => 1,
        ],
    ];

    public const array ANNIVERSARY_GIFT_CONTENT = [
        [
            'item' => GearItemEnum::PLASTENITE_ARMOR,
            'quantity' => 1,
            'weight' => 1,
            'filterType' => self::FILTER_BY_CHARACTER,
            'filterValue' => 'chao',
        ],
        [
            'item' => GameRationEnum::ORGANIC_WASTE,
            'quantity' => 4,
            'weight' => 5,
            'filterType' => self::FILTER_BY_CHARACTER,
            'filterValue' => 'chao',
        ],
        [
            'item' => ItemEnum::KNIFE,
            'quantity' => 1,
            'weight' => 5,
            'filterType' => self::FILTER_BY_CHARACTER,
            'filterValue' => 'chao',
        ],
        [
            'item' => ItemEnum::BLASTER,
            'quantity' => 1,
            'weight' => 5,
            'filterType' => self::FILTER_BY_CHARACTER,
            'filterValue' => 'chao',
        ],
        [
            'item' => 'apprentron_medic',
            'quantity' => 1,
            'weight' => 1,
            'filterType' => self::FILTER_BY_CHARACTER,
            'filterValue' => 'chun',
        ],
        [
            'item' => ItemEnum::MUSH_SAMPLE,
            'quantity' => 1,
            'weight' => 5,
            'filterType' => self::FILTER_BY_CHARACTER,
            'filterValue' => 'chun',
        ],
        [
            'item' => ItemEnum::MYCO_ALARM,
            'quantity' => 1,
            'weight' => 5,
            'filterType' => self::FILTER_BY_CHARACTER,
            'filterValue' => 'chun',
        ],
        [
            'item' => 'apprentron_optimist',
            'quantity' => 1,
            'weight' => 5,
            'filterType' => self::FILTER_BY_CHARACTER,
            'filterValue' => 'chun',
        ],
        [
            'item' => 'hacker_kit',
            'quantity' => 1,
            'weight' => 1,
            'filterType' => self::FILTER_BY_CHARACTER,
            'filterValue' => 'eleesha',
        ],
        [
            'item' => 'duct_tape',
            'quantity' => 1,
            'weight' => 5,
            'filterType' => self::FILTER_BY_CHARACTER,
            'filterValue' => 'eleesha',
        ],
        [
            'item' => 'protective_gloves',
            'quantity' => 1,
            'weight' => 5,
            'filterType' => self::FILTER_BY_CHARACTER,
            'filterValue' => 'eleesha',
        ],
        [
            'item' => 'block_of_post_it',
            'quantity' => 2,
            'weight' => 5,
            'filterType' => self::FILTER_BY_CHARACTER,
            'filterValue' => 'eleesha',
        ],
        [
            'item' => 'medikit',
            'quantity' => 1,
            'weight' => 1,
            'filterType' => self::FILTER_BY_CHARACTER,
            'filterValue' => 'finola',
        ],
        [
            'item' => 'bandage',
            'quantity' => 4,
            'weight' => 5,
            'filterType' => self::FILTER_BY_CHARACTER,
            'filterValue' => 'finola',
        ],
        [
            'item' => 'soap',
            'quantity' => 2,
            'weight' => 5,
            'filterType' => self::FILTER_BY_CHARACTER,
            'filterValue' => 'finola',
        ],
        [
            'item' => 'water_stick',
            'quantity' => 1,
            'weight' => 5,
            'filterType' => self::FILTER_BY_CHARACTER,
            'filterValue' => 'finola',
        ],
        [
            'item' => 'magellan_liquid_map',
            'quantity' => 1,
            'weight' => 1,
            'filterType' => self::FILTER_BY_CHARACTER,
            'filterValue' => 'frieda',
        ],
        [
            'item' => 'jar_of_alien_oil',
            'quantity' => 1,
            'weight' => 5,
            'filterType' => self::FILTER_BY_CHARACTER,
            'filterValue' => 'frieda',
        ],
        [
            'item' => 'quadrimetric_compass',
            'quantity' => 1,
            'weight' => 5,
            'filterType' => self::FILTER_BY_CHARACTER,
            'filterValue' => 'frieda',
        ],
        [
            'item' => 'superfreezer',
            'quantity' => 1,
            'weight' => 5,
            'filterType' => self::FILTER_BY_CHARACTER,
            'filterValue' => 'frieda',
        ],
        [
            'item' => 'apprentron_apprentice',
            'quantity' => 1,
            'weight' => 1,
            'filterType' => self::FILTER_BY_CHARACTER,
            'filterValue' => 'gioele',
        ],
        [
            'item' => 'apprentron_sneak',
            'quantity' => 1,
            'weight' => 5,
            'filterType' => self::FILTER_BY_CHARACTER,
            'filterValue' => 'gioele',
        ],
        [
            'item' => ItemEnum::COFFEE_THERMOS,
            'quantity' => 1,
            'weight' => 5,
            'filterType' => self::FILTER_BY_CHARACTER,
            'filterValue' => 'gioele',
        ],
        [
            'item' => 'fuel_capsule',
            'quantity' => 1,
            'weight' => 5,
            'filterType' => self::FILTER_BY_CHARACTER,
            'filterValue' => 'gioele',
        ],
        [
            'item' => 'apprentron_shooter',
            'quantity' => 1,
            'weight' => 1,
            'filterType' => self::FILTER_BY_CHARACTER,
            'filterValue' => 'hua',
        ],
        [
            'item' => 'sniper_helmet',
            'quantity' => 1,
            'weight' => 5,
            'filterType' => self::FILTER_BY_CHARACTER,
            'filterValue' => 'hua',
        ],
        [
            'item' => 'hydropot',
            'quantity' => 2,
            'weight' => 5,
            'filterType' => self::FILTER_BY_CHARACTER,
            'filterValue' => 'hua',
        ],
        [
            'item' => 'quadrimetric_compass',
            'quantity' => 1,
            'weight' => 5,
            'filterType' => self::FILTER_BY_CHARACTER,
            'filterValue' => 'hua',
        ],
        [
            'item' => 'jumpkin',
            'quantity' => 1,
            'weight' => 1,
            'filterType' => self::FILTER_BY_CHARACTER,
            'filterValue' => 'ian',
        ],
        [
            'item' => 'white_flag',
            'quantity' => 1,
            'weight' => 5,
            'filterType' => self::FILTER_BY_CHARACTER,
            'filterValue' => 'ian',
        ],
        [
            'item' => 'extinguisher',
            'quantity' => 1,
            'weight' => 5,
            'filterType' => self::FILTER_BY_CHARACTER,
            'filterValue' => 'ian',
        ],
        [
            'item' => 'hydropot',
            'quantity' => 2,
            'weight' => 5,
            'filterType' => self::FILTER_BY_CHARACTER,
            'filterValue' => 'ian',
        ],
        [
            'item' => 'swedish_sofa',
            'quantity' => 1,
            'weight' => 1,
            'filterType' => self::FILTER_BY_CHARACTER,
            'filterValue' => 'janice',
        ],
        [
            'item' => 'thermosensor',
            'quantity' => 1,
            'weight' => 5,
            'filterType' => self::FILTER_BY_CHARACTER,
            'filterValue' => 'janice',
        ],
        [
            'item' => 'babel_module',
            'quantity' => 1,
            'weight' => 5,
            'filterType' => self::FILTER_BY_CHARACTER,
            'filterValue' => 'janice',
        ],
        [
            'item' => 'alien_holographic_tv',
            'quantity' => 1,
            'weight' => 5,
            'filterType' => self::FILTER_BY_CHARACTER,
            'filterValue' => 'janice',
        ],
        [
            'item' => 'starmap_fragment',
            'quantity' => 1,
            'weight' => 1,
            'filterType' => self::FILTER_BY_CHARACTER,
            'filterValue' => 'jin_su',
        ],
        [
            'item' => 'space_potato',
            'quantity' => 3,
            'weight' => 5,
            'filterType' => self::FILTER_BY_CHARACTER,
            'filterValue' => 'jin_su',
        ],
        [
            'item' => 'apprentron_diplomat',
            'quantity' => 1,
            'weight' => 5,
            'filterType' => self::FILTER_BY_CHARACTER,
            'filterValue' => 'jin_su',
        ],
        [
            'item' => 'apprentron_politician',
            'quantity' => 1,
            'weight' => 5,
            'filterType' => self::FILTER_BY_CHARACTER,
            'filterValue' => 'jin_su',
        ],
        [
            'item' => 'apprentron_it_expert',
            'quantity' => 1,
            'weight' => 1,
            'filterType' => self::FILTER_BY_CHARACTER,
            'filterValue' => 'kuan_ti',
        ],
        [
            'item' => 'adjustable_wrench',
            'quantity' => 1,
            'weight' => 5,
            'filterType' => self::FILTER_BY_CHARACTER,
            'filterValue' => 'kuan_ti',
        ],
        [
            'item' => 'alien_bottle_opener',
            'quantity' => 1,
            'weight' => 5,
            'filterType' => self::FILTER_BY_CHARACTER,
            'filterValue' => 'kuan_ti',
        ],
        [
            'item' => 'spacesuit',
            'quantity' => 10,
            'weight' => 5,
            'filterType' => self::FILTER_BY_CHARACTER,
            'filterValue' => 'kuan_ti',
        ],
        [
            'item' => 'apprentron_creative',
            'quantity' => 1,
            'weight' => 1,
            'filterType' => self::FILTER_BY_CHARACTER,
            'filterValue' => 'paola',
        ],
        [
            'item' => 'jukebox',
            'quantity' => 1,
            'weight' => 5,
            'filterType' => self::FILTER_BY_CHARACTER,
            'filterValue' => 'paola',
        ],
        [
            'item' => 'invertebrate_shell',
            'quantity' => 1,
            'weight' => 5,
            'filterType' => self::FILTER_BY_CHARACTER,
            'filterValue' => 'paola',
        ],
        [
            'item' => 'apprentron_determined_default',
            'quantity' => 1,
            'weight' => 5,
            'filterType' => self::FILTER_BY_CHARACTER,
            'filterValue' => 'paola',
        ],
        [
            'item' => 'apprentron_ocd_default',
            'quantity' => 1,
            'weight' => 1,
            'filterType' => self::FILTER_BY_CHARACTER,
            'filterValue' => 'raluca',
        ],
        [
            'item' => ItemEnum::SCHRODINGER,
            'quantity' => 1,
            'weight' => 5,
            'filterType' => self::FILTER_BY_CHARACTER,
            'filterValue' => 'raluca',
        ],
        [
            'item' => 'oscilloscope',
            'quantity' => 1,
            'weight' => 5,
            'filterType' => self::FILTER_BY_CHARACTER,
            'filterValue' => 'raluca',
        ],
        [
            'item' => 'supervitamin_bar',
            'quantity' => 2,
            'weight' => 5,
            'filterType' => self::FILTER_BY_CHARACTER,
            'filterValue' => 'raluca',
        ],
        [
            'item' => 'rolling_boulder',
            'quantity' => 1,
            'weight' => 1,
            'filterType' => self::FILTER_BY_CHARACTER,
            'filterValue' => 'roland',
        ],
        [
            'item' => 'ncc_lenses',
            'quantity' => 1,
            'weight' => 5,
            'filterType' => self::FILTER_BY_CHARACTER,
            'filterValue' => 'roland',
        ],
        [
            'item' => 'apprentron_motivator',
            'quantity' => 1,
            'weight' => 5,
            'filterType' => self::FILTER_BY_CHARACTER,
            'filterValue' => 'roland',
        ],
        [
            'item' => 'extinguisher',
            'quantity' => 1,
            'weight' => 5,
            'filterType' => self::FILTER_BY_CHARACTER,
            'filterValue' => 'roland',
        ],
        [
            'item' => 'stainproof_apron',
            'quantity' => 1,
            'weight' => 1,
            'filterType' => self::FILTER_BY_CHARACTER,
            'filterValue' => 'stephen',
        ],
        [
            'item' => 'apprentron_caffeine_junkie',
            'quantity' => 1,
            'weight' => 5,
            'filterType' => self::FILTER_BY_CHARACTER,
            'filterValue' => 'stephen',
        ],
        [
            'item' => GameRationEnum::STANDARD_RATION,
            'quantity' => 4,
            'weight' => 5,
            'filterType' => self::FILTER_BY_CHARACTER,
            'filterValue' => 'stephen',
        ],
        [
            'item' => 'mad_kube',
            'quantity' => 1,
            'weight' => 5,
            'filterType' => self::FILTER_BY_CHARACTER,
            'filterValue' => 'stephen',
        ],
        [
            'item' => 'apprentron_sprinter',
            'quantity' => 1,
            'weight' => 1,
            'filterType' => self::FILTER_BY_CHARACTER,
            'filterValue' => 'terrence',
        ],
        [
            'item' => 'antigrav_scooter',
            'quantity' => 1,
            'weight' => 5,
            'filterType' => self::FILTER_BY_CHARACTER,
            'filterValue' => 'terrence',
        ],
        [
            'item' => 'adjustable_wrench',
            'quantity' => 1,
            'weight' => 5,
            'filterType' => self::FILTER_BY_CHARACTER,
            'filterValue' => 'terrence',
        ],
        [
            'item' => ItemEnum::SUPPORT_DRONE,
            'quantity' => 1,
            'weight' => 5,
            'filterType' => self::FILTER_BY_CHARACTER,
            'filterValue' => 'terrence',
        ],
        [
            'item' => 'old_t_shirt',
            'quantity' => 1,
            'weight' => 5,
            'filterType' => self::FILTER_BY_CHARACTER,
            'filterValue' => 'andie',
        ],
        [
            'item' => 'old_t_shirt',
            'quantity' => 1,
            'weight' => 5,
            'filterType' => self::FILTER_BY_CHARACTER,
            'filterValue' => 'derek',
        ],
    ];
}
