<?php

namespace Mush\Equipment\Enum;

use Mush\Game\Enum\CharacterEnum;

class ContainerContentEnum
{
    public const FILTER_BY_CHARACTER = 'character';
    public const array SPACE_CAPSULE_CONTENT = [
        ItemEnum::FUEL_CAPSULE => 1,
        ItemEnum::OXYGEN_CAPSULE => 1,
        ItemEnum::METAL_SCRAPS => 1,
        ItemEnum::PLASTIC_SCRAPS => 1,
    ];

    public const array COFFEE_THERMOS_CONTENT = [
        [
            'item' => GameRationEnum::COFFEE,
            'quantity' => 1,
            'weight' => 1,
        ],
    ];

    public const array ANNIVERSARY_GIFT_CONTENT = [
        [
            'item' => GearItemEnum::PLASTENITE_ARMOR,
            'quantity' => 1,
            'weight' => 1,
            'filterType' => self::FILTER_BY_CHARACTER,
            'filterValue' => CharacterEnum::CHAO,
        ],
        [
            'item' => GameRationEnum::ORGANIC_WASTE,
            'quantity' => 4,
            'weight' => 5,
            'filterType' => self::FILTER_BY_CHARACTER,
            'filterValue' => CharacterEnum::CHAO,
        ],
        [
            'item' => ItemEnum::KNIFE,
            'quantity' => 1,
            'weight' => 5,
            'filterType' => self::FILTER_BY_CHARACTER,
            'filterValue' => CharacterEnum::CHAO,
        ],
        [
            'item' => ItemEnum::BLASTER,
            'quantity' => 1,
            'weight' => 5,
            'filterType' => self::FILTER_BY_CHARACTER,
            'filterValue' => CharacterEnum::CHAO,
        ],
        [
            'item' => 'apprentron_medic',
            'quantity' => 1,
            'weight' => 1,
            'filterType' => self::FILTER_BY_CHARACTER,
            'filterValue' => CharacterEnum::CHUN,
        ],
        [
            'item' => ItemEnum::MUSH_SAMPLE,
            'quantity' => 1,
            'weight' => 5,
            'filterType' => self::FILTER_BY_CHARACTER,
            'filterValue' => CharacterEnum::CHUN,
        ],
        [
            'item' => ItemEnum::MYCO_ALARM,
            'quantity' => 1,
            'weight' => 5,
            'filterType' => self::FILTER_BY_CHARACTER,
            'filterValue' => CharacterEnum::CHUN,
        ],
        [
            'item' => 'apprentron_optimist',
            'quantity' => 1,
            'weight' => 5,
            'filterType' => self::FILTER_BY_CHARACTER,
            'filterValue' => CharacterEnum::CHUN,
        ],
        [
            'item' => ToolItemEnum::HACKER_KIT,
            'quantity' => 1,
            'weight' => 1,
            'filterType' => self::FILTER_BY_CHARACTER,
            'filterValue' => CharacterEnum::ELEESHA,
        ],
        [
            'item' => ToolItemEnum::DUCT_TAPE,
            'quantity' => 1,
            'weight' => 5,
            'filterType' => self::FILTER_BY_CHARACTER,
            'filterValue' => CharacterEnum::ELEESHA,
        ],
        [
            'item' => GearItemEnum::PROTECTIVE_GLOVES,
            'quantity' => 1,
            'weight' => 5,
            'filterType' => self::FILTER_BY_CHARACTER,
            'filterValue' => CharacterEnum::ELEESHA,
        ],
        [
            'item' => ToolItemEnum::BLOCK_OF_POST_IT,
            'quantity' => 2,
            'weight' => 5,
            'filterType' => self::FILTER_BY_CHARACTER,
            'filterValue' => CharacterEnum::ELEESHA,
        ],
        [
            'item' => ToolItemEnum::MEDIKIT,
            'quantity' => 1,
            'weight' => 1,
            'filterType' => self::FILTER_BY_CHARACTER,
            'filterValue' => CharacterEnum::FINOLA,
        ],
        [
            'item' => ToolItemEnum::BANDAGE,
            'quantity' => 4,
            'weight' => 5,
            'filterType' => self::FILTER_BY_CHARACTER,
            'filterValue' => CharacterEnum::FINOLA,
        ],
        [
            'item' => GearItemEnum::SOAP,
            'quantity' => 2,
            'weight' => 5,
            'filterType' => self::FILTER_BY_CHARACTER,
            'filterValue' => CharacterEnum::FINOLA,
        ],
        [
            'item' => ItemEnum::WATER_STICK,
            'quantity' => 1,
            'weight' => 5,
            'filterType' => self::FILTER_BY_CHARACTER,
            'filterValue' => CharacterEnum::FINOLA,
        ],
        [
            'item' => GearItemEnum::MAGELLAN_LIQUID_MAP,
            'quantity' => 1,
            'weight' => 1,
            'filterType' => self::FILTER_BY_CHARACTER,
            'filterValue' => CharacterEnum::FRIEDA,
        ],
        [
            'item' => ToolItemEnum::JAR_OF_ALIEN_OIL,
            'quantity' => 1,
            'weight' => 5,
            'filterType' => self::FILTER_BY_CHARACTER,
            'filterValue' => CharacterEnum::FRIEDA,
        ],
        [
            'item' => ItemEnum::QUADRIMETRIC_COMPASS,
            'quantity' => 1,
            'weight' => 5,
            'filterType' => self::FILTER_BY_CHARACTER,
            'filterValue' => CharacterEnum::FRIEDA,
        ],
        [
            'item' => ToolItemEnum::SUPERFREEZER,
            'quantity' => 1,
            'weight' => 5,
            'filterType' => self::FILTER_BY_CHARACTER,
            'filterValue' => CharacterEnum::FRIEDA,
        ],
        [
            'item' => 'apprentron_apprentice',
            'quantity' => 1,
            'weight' => 1,
            'filterType' => self::FILTER_BY_CHARACTER,
            'filterValue' => CharacterEnum::GIOELE,
        ],
        [
            'item' => 'apprentron_sneak',
            'quantity' => 1,
            'weight' => 5,
            'filterType' => self::FILTER_BY_CHARACTER,
            'filterValue' => CharacterEnum::GIOELE,
        ],
        [
            'item' => ItemEnum::COFFEE_THERMOS,
            'quantity' => 1,
            'weight' => 5,
            'filterType' => self::FILTER_BY_CHARACTER,
            'filterValue' => CharacterEnum::GIOELE,
        ],
        [
            'item' => ItemEnum::FUEL_CAPSULE,
            'quantity' => 1,
            'weight' => 5,
            'filterType' => self::FILTER_BY_CHARACTER,
            'filterValue' => CharacterEnum::GIOELE,
        ],
        [
            'item' => 'apprentron_shooter',
            'quantity' => 1,
            'weight' => 1,
            'filterType' => self::FILTER_BY_CHARACTER,
            'filterValue' => CharacterEnum::HUA,
        ],
        [
            'item' => GearItemEnum::SNIPER_HELMET,
            'quantity' => 1,
            'weight' => 5,
            'filterType' => self::FILTER_BY_CHARACTER,
            'filterValue' => CharacterEnum::HUA,
        ],
        [
            'item' => ItemEnum::HYDROPOT,
            'quantity' => 2,
            'weight' => 5,
            'filterType' => self::FILTER_BY_CHARACTER,
            'filterValue' => CharacterEnum::HUA,
        ],
        [
            'item' => ItemEnum::QUADRIMETRIC_COMPASS,
            'quantity' => 1,
            'weight' => 5,
            'filterType' => self::FILTER_BY_CHARACTER,
            'filterValue' => CharacterEnum::HUA,
        ],
        [
            'item' => GameFruitEnum::JUMPKIN,
            'quantity' => 1,
            'weight' => 1,
            'filterType' => self::FILTER_BY_CHARACTER,
            'filterValue' => CharacterEnum::IAN,
        ],
        [
            'item' => ItemEnum::WHITE_FLAG,
            'quantity' => 1,
            'weight' => 5,
            'filterType' => self::FILTER_BY_CHARACTER,
            'filterValue' => CharacterEnum::IAN,
        ],
        [
            'item' => ToolItemEnum::EXTINGUISHER,
            'quantity' => 1,
            'weight' => 5,
            'filterType' => self::FILTER_BY_CHARACTER,
            'filterValue' => CharacterEnum::IAN,
        ],
        [
            'item' => ItemEnum::HYDROPOT,
            'quantity' => 2,
            'weight' => 5,
            'filterType' => self::FILTER_BY_CHARACTER,
            'filterValue' => CharacterEnum::IAN,
        ],
        [
            'item' => EquipmentEnum::SWEDISH_SOFA,
            'quantity' => 1,
            'weight' => 1,
            'filterType' => self::FILTER_BY_CHARACTER,
            'filterValue' => CharacterEnum::JANICE,
        ],
        [
            'item' => ItemEnum::THERMOSENSOR,
            'quantity' => 1,
            'weight' => 5,
            'filterType' => self::FILTER_BY_CHARACTER,
            'filterValue' => CharacterEnum::JANICE,
        ],
        [
            'item' => ItemEnum::BABEL_MODULE,
            'quantity' => 1,
            'weight' => 5,
            'filterType' => self::FILTER_BY_CHARACTER,
            'filterValue' => CharacterEnum::JANICE,
        ],
        [
            'item' => ToolItemEnum::ALIEN_HOLOGRAPHIC_TV,
            'quantity' => 1,
            'weight' => 5,
            'filterType' => self::FILTER_BY_CHARACTER,
            'filterValue' => CharacterEnum::JANICE,
        ],
        [
            'item' => ItemEnum::STARMAP_FRAGMENT,
            'quantity' => 1,
            'weight' => 1,
            'filterType' => self::FILTER_BY_CHARACTER,
            'filterValue' => CharacterEnum::JIN_SU,
        ],
        [
            'item' => GameRationEnum::SPACE_POTATO,
            'quantity' => 3,
            'weight' => 5,
            'filterType' => self::FILTER_BY_CHARACTER,
            'filterValue' => CharacterEnum::JIN_SU,
        ],
        [
            'item' => 'apprentron_diplomat',
            'quantity' => 1,
            'weight' => 5,
            'filterType' => self::FILTER_BY_CHARACTER,
            'filterValue' => CharacterEnum::JIN_SU,
        ],
        [
            'item' => 'apprentron_politician',
            'quantity' => 1,
            'weight' => 5,
            'filterType' => self::FILTER_BY_CHARACTER,
            'filterValue' => CharacterEnum::JIN_SU,
        ],
        [
            'item' => 'apprentron_it_expert',
            'quantity' => 1,
            'weight' => 1,
            'filterType' => self::FILTER_BY_CHARACTER,
            'filterValue' => CharacterEnum::KUAN_TI,
        ],
        [
            'item' => GearItemEnum::ADJUSTABLE_WRENCH,
            'quantity' => 1,
            'weight' => 5,
            'filterType' => self::FILTER_BY_CHARACTER,
            'filterValue' => CharacterEnum::KUAN_TI,
        ],
        [
            'item' => GearItemEnum::ALIEN_BOTTLE_OPENER,
            'quantity' => 1,
            'weight' => 5,
            'filterType' => self::FILTER_BY_CHARACTER,
            'filterValue' => CharacterEnum::KUAN_TI,
        ],
        [
            'item' => GearItemEnum::SPACESUIT,
            'quantity' => 10,
            'weight' => 5,
            'filterType' => self::FILTER_BY_CHARACTER,
            'filterValue' => CharacterEnum::KUAN_TI,
        ],
        [
            'item' => 'apprentron_creative',
            'quantity' => 1,
            'weight' => 1,
            'filterType' => self::FILTER_BY_CHARACTER,
            'filterValue' => CharacterEnum::PAOLA,
        ],
        [
            'item' => EquipmentEnum::JUKEBOX,
            'quantity' => 1,
            'weight' => 5,
            'filterType' => self::FILTER_BY_CHARACTER,
            'filterValue' => CharacterEnum::PAOLA,
        ],
        [
            'item' => GearItemEnum::INVERTEBRATE_SHELL,
            'quantity' => 1,
            'weight' => 5,
            'filterType' => self::FILTER_BY_CHARACTER,
            'filterValue' => CharacterEnum::PAOLA,
        ],
        [
            'item' => 'apprentron_determined_default',
            'quantity' => 1,
            'weight' => 5,
            'filterType' => self::FILTER_BY_CHARACTER,
            'filterValue' => CharacterEnum::PAOLA,
        ],
        [
            'item' => 'apprentron_ocd_default',
            'quantity' => 1,
            'weight' => 1,
            'filterType' => self::FILTER_BY_CHARACTER,
            'filterValue' => CharacterEnum::RALUCA,
        ],
        [
            'item' => ItemEnum::SCHRODINGER,
            'quantity' => 1,
            'weight' => 5,
            'filterType' => self::FILTER_BY_CHARACTER,
            'filterValue' => CharacterEnum::RALUCA,
        ],
        [
            'item' => GearItemEnum::OSCILLOSCOPE,
            'quantity' => 1,
            'weight' => 5,
            'filterType' => self::FILTER_BY_CHARACTER,
            'filterValue' => CharacterEnum::RALUCA,
        ],
        [
            'item' => GameRationEnum::SUPERVITAMIN_BAR,
            'quantity' => 2,
            'weight' => 5,
            'filterType' => self::FILTER_BY_CHARACTER,
            'filterValue' => CharacterEnum::RALUCA,
        ],
        [
            'item' => GearItemEnum::ROLLING_BOULDER,
            'quantity' => 1,
            'weight' => 1,
            'filterType' => self::FILTER_BY_CHARACTER,
            'filterValue' => CharacterEnum::ROLAND,
        ],
        [
            'item' => GearItemEnum::NCC_LENS,
            'quantity' => 1,
            'weight' => 5,
            'filterType' => self::FILTER_BY_CHARACTER,
            'filterValue' => CharacterEnum::ROLAND,
        ],
        [
            'item' => 'apprentron_motivator',
            'quantity' => 1,
            'weight' => 5,
            'filterType' => self::FILTER_BY_CHARACTER,
            'filterValue' => CharacterEnum::ROLAND,
        ],
        [
            'item' => ToolItemEnum::EXTINGUISHER,
            'quantity' => 1,
            'weight' => 5,
            'filterType' => self::FILTER_BY_CHARACTER,
            'filterValue' => CharacterEnum::ROLAND,
        ],
        [
            'item' => GearItemEnum::STAINPROOF_APRON,
            'quantity' => 1,
            'weight' => 1,
            'filterType' => self::FILTER_BY_CHARACTER,
            'filterValue' => CharacterEnum::STEPHEN,
        ],
        [
            'item' => 'apprentron_caffeine_junkie',
            'quantity' => 1,
            'weight' => 5,
            'filterType' => self::FILTER_BY_CHARACTER,
            'filterValue' => CharacterEnum::STEPHEN,
        ],
        [
            'item' => GameRationEnum::STANDARD_RATION,
            'quantity' => 4,
            'weight' => 5,
            'filterType' => self::FILTER_BY_CHARACTER,
            'filterValue' => CharacterEnum::STEPHEN,
        ],
        [
            'item' => ToolItemEnum::MAD_KUBE,
            'quantity' => 1,
            'weight' => 5,
            'filterType' => self::FILTER_BY_CHARACTER,
            'filterValue' => CharacterEnum::STEPHEN,
        ],
        [
            'item' => 'apprentron_sprinter',
            'quantity' => 1,
            'weight' => 1,
            'filterType' => self::FILTER_BY_CHARACTER,
            'filterValue' => CharacterEnum::TERRENCE,
        ],
        [
            'item' => GearItemEnum::ANTIGRAV_SCOOTER,
            'quantity' => 1,
            'weight' => 5,
            'filterType' => self::FILTER_BY_CHARACTER,
            'filterValue' => CharacterEnum::TERRENCE,
        ],
        [
            'item' => GearItemEnum::ADJUSTABLE_WRENCH,
            'quantity' => 1,
            'weight' => 5,
            'filterType' => self::FILTER_BY_CHARACTER,
            'filterValue' => CharacterEnum::TERRENCE,
        ],
        [
            'item' => ItemEnum::SUPPORT_DRONE,
            'quantity' => 1,
            'weight' => 5,
            'filterType' => self::FILTER_BY_CHARACTER,
            'filterValue' => CharacterEnum::TERRENCE,
        ],
        [
            'item' => 'apprentron_genius',
            'quantity' => 1,
            'weight' => 1,
            'filterType' => self::FILTER_BY_CHARACTER,
            'filterValue' => CharacterEnum::ANDIE,
        ],
        [
            'item' => 'apprentron_opportunist',
            'quantity' => 1,
            'weight' => 5,
            'filterType' => self::FILTER_BY_CHARACTER,
            'filterValue' => CharacterEnum::ANDIE,
        ],
        [
            'item' => 'apprentron_rebel',
            'quantity' => 1,
            'weight' => 5,
            'filterType' => self::FILTER_BY_CHARACTER,
            'filterValue' => CharacterEnum::ANDIE,
        ],
        [
            'item' => 'apprentron_self_sacrifice',
            'quantity' => 1,
            'weight' => 5,
            'filterType' => self::FILTER_BY_CHARACTER,
            'filterValue' => CharacterEnum::ANDIE,
        ],
        [
            'item' => 'apprentron_pilot',
            'quantity' => 1,
            'weight' => 1,
            'filterType' => self::FILTER_BY_CHARACTER,
            'filterValue' => CharacterEnum::DEREK,
        ],
        [
            'item' => ItemEnum::THICK_TUBE,
            'quantity' => 1,
            'weight' => 5,
            'filterType' => self::FILTER_BY_CHARACTER,
            'filterValue' => CharacterEnum::DEREK,
        ],
        [
            'item' => ToolItemEnum::JAR_OF_ALIEN_OIL,
            'quantity' => 1,
            'weight' => 5,
            'filterType' => self::FILTER_BY_CHARACTER,
            'filterValue' => CharacterEnum::DEREK,
        ],
        [
            'item' => GameRationEnum::ANABOLIC,
            'quantity' => 3,
            'weight' => 5,
            'filterType' => self::FILTER_BY_CHARACTER,
            'filterValue' => CharacterEnum::DEREK,
        ],
    ];
}
