Mush\Action\Entity\ActionCost:
  attributes:                          # optional
    id:
      groups: [ 'action_cost_read' ]
    actionPointCost:
      groups: [ 'action_cost_read', 'action_cost_write' ]
    movementPointCost:
      groups: [ 'action_cost_read', 'action_cost_write' ]
    moralPointCost:
      groups: [ 'action_cost_read', 'action_cost_write' ]

