Mush\Action\Entity\ActionConfig:
  attributes:                          # optional
    id:
      groups: [ 'action_read' ]
    name:
      groups: [ 'action_read', 'action_write' ]
    actionName:
      groups: [ 'action_read', 'action_write' ]
    types:
      groups: [ 'action_read', 'action_write' ]
    displayHolder:
      groups: [ 'action_read', 'action_write' ]
    range:
      groups: [ 'action_read', 'action_write' ]
    actionVariablesArray:
      groups: [ 'action_read', 'action_write' ]
