Mush\Equipment\Entity\Mechanics\Blueprint:
  attributes:
    id: 
      groups: [ 'blueprint_read' ]
    name:
      groups: [  'blueprint_write', 'blueprint_read'  ]
    mechanics:
      groups: [  'blueprint_write' ]
    actions:
      groups: [  'blueprint_write' ]
    craftedEquipmentName:
      groups: [ 'blueprint_read', 'blueprint_write' ]
    ingredients:
      groups: [ 'blueprint_read', 'blueprint_write' ]
