Mush\Equipment\Entity\Mechanics\Book:
  attributes:
    id: 
      groups: [ 'book_read' ]
    name:
      groups: [ 'book_write', 'book_read' ]
    mechanics:
      groups: [ 'book_write' ]
    actions:
      groups: [ 'book_write' ]
    skill:
      groups: [ 'book_read', 'book_write' ]