Mush\Disease\Entity\Config\DiseaseCauseConfig:
  attributes:                          # optional
    id:
      groups: [ 'disease_cause_config_read' ]
    name:
      groups: [ 'disease_cause_config_read', 'disease_cause_config_write' ]
    causeName:
      groups: [ 'disease_cause_config_read', 'disease_cause_config_write' ]
    diseases:
      groups: [ 'disease_cause_config_read', 'disease_cause_config_write' ]