Mush\Equipment\Entity\Mechanics\Document:
  attributes:
    id: 
      groups: [ 'document_read' ]
    name:
      groups: [ 'document_write', 'document_read' ]
    mechanics:
      groups: [ 'document_write' ]
    actions:
      groups: [ 'document_write' ]
    content:
      groups: [ 'document_read', 'document_write' ]
    isTranslated:
      groups: [ 'document_read', 'document_write' ]
    canShred:
      groups: [ 'document_read', 'document_write' ]
