Mush\Equipment\Entity\Mechanics\Drug:
  attributes:
    id: 
      groups: [ 'drug_read' ]
    name:
      groups: [ 'drug_write', 'drug_read' ]
    mechanics:
      groups: [ 'drug_write' ]
    actions:
      groups: [ 'drug_write' ]
    moralPoints:
      groups: [ 'drug_read', 'drug_write' ]
    actionPoints:
      groups: [ 'drug_read', 'drug_write' ]
    movementPoints:
      groups: [ 'drug_read', 'drug_write' ]
    healthPoints:
      groups: [ 'drug_read', 'drug_write' ]
    satiety:
      groups: [ 'drug_read', 'drug_write' ]
    extraEffects:
      groups: [ 'drug_read', 'drug_write' ]
    isPerishable:
      groups: [ 'drug_read', 'drug_write' ]