Mush\Equipment\Entity\Config\EquipmentConfig:
  attributes:
    id:
      groups: [ 'equipment_config_read' ]
    name:
      groups: [ 'equipment_config_read', 'equipment_config_write' ]
    equipmentName:
      groups: [ 'equipment_config_read', 'equipment_config_write' ]
    mechanics:
      groups: [ 'equipment_config_read', 'equipment_config_write' ]
    breakableType:
      groups: [ 'equipment_config_read', 'equipment_config_write' ]
    actionConfigs:
      groups: [ 'equipment_config_read', 'equipment_config_write' ]
    initStatuses:
      groups: [ 'equipment_config_read', 'equipment_config_write' ]
    dismountedProducts:
      groups: [ 'equipment_config_read', 'equipment_config_write' ]
    isPersonal:
      groups: [ 'equipment_config_read', 'equipment_config_write' ]
    collectScrapNumber:
      groups: [ 'patrol_ship_read', 'patrol_ship_write' ]
    collectScrapPatrolShipDamage:
      groups: [ 'patrol_ship_read', 'patrol_ship_write' ]
    collectScrapPlayerDamage:
      groups: [ 'patrol_ship_read', 'patrol_ship_write' ]
    failedManoeuvreDaedalusDamage:
      groups: [ 'patrol_ship_read', 'patrol_ship_write' ]
    failedManoeuvrePatrolShipDamage:
      groups: [ 'patrol_ship_read', 'patrol_ship_write' ]
    failedManoeuvrePlayerDamage:
      groups: [ 'patrol_ship_read', 'patrol_ship_write' ]
    