Mush\Equipment\Entity\Mechanics\Fruit:
  attributes:
    id: 
      groups: [ 'fruit_read' ]
    name:
      groups: [ 'fruit_write' ]
    mechanics:
      groups: [ 'fruit_write' ]
    actions:
      groups: [ 'fruit_write' ]
    moralPoints:
      groups: [ 'fruit_read', 'fruit_write' ]
    actionPoints:
      groups: [ 'fruit_read', 'fruit_write' ]
    movementPoints:
      groups: [ 'fruit_read', 'fruit_write' ]
    healthPoints:
      groups: [ 'fruit_read', 'fruit_write' ]
    satiety:
      groups: [ 'fruit_read', 'fruit_write' ]
    extraEffects:
      groups: [ 'fruit_read', 'fruit_write' ]
    isPerishable:
      groups: [ 'fruit_read', 'fruit_write' ]
    plantName:
      groups: [ 'fruit_read', 'fruit_write' ]
    