Mush\Equipment\Entity\Mechanics\Gear:
  attributes:
    id: 
      groups: [ 'gear_read' ]
    name:
      groups: [ 'gear_write', 'gear_read' ]
    mechanics:
      groups: [ 'gear_write' ]
    actions:
      groups: [ 'gear_write' ]
    modifierConfigs:
      groups: [ 'gear_read', 'gear_write' ]