Mush\Hunter\Entity\HunterConfig:
  attributes:
    id:
      groups: [ 'hunter_config_read' ]
    name:
      groups: [ 'hunter_config_read', 'hunter_config_write' ]
    hunterName:
      groups: [ 'hunter_config_read', 'hunter_config_write' ]
    initialHealth:
      groups: [ 'hunter_config_read', 'hunter_config_write' ]
    damageRange:
      groups: [ 'hunter_config_read', 'hunter_config_write' ]
    hitChance:
      groups: [ 'hunter_config_read', 'hunter_config_write' ]
    dodgeChance:
      groups: [ 'hunter_config_read', 'hunter_config_write' ]
    drawCost:
      groups: [ 'hunter_config_read', 'hunter_config_write' ]
    maxPerWave:
      groups: [ 'hunter_config_read', 'hunter_config_write' ]
    drawWeight:
      groups: [ 'hunter_config_read', 'hunter_config_write' ]
    spawnDifficulty:
      groups: [ 'hunter_config_read', 'hunter_config_write' ]
    scrapDropTable:
      groups: [ 'hunter_config_read', 'hunter_config_write' ]
    numberOfDroppedScrap:
      groups: [ 'hunter_config_read', 'hunter_config_write' ]
    initialStatuses:
      groups: [ 'hunter_config_write' ]
    bonusAfterFailedShot:
      groups: [ 'hunter_config_read', 'hunter_config_write' ]
    numberOfActionsPerCycle:
      groups: [ 'hunter_config_read', 'hunter_config_write' ]
 