Mush\Hunter\Entity\HunterWaveConfig:
  attributes:
    id:
      groups: [ 'hunter_wave_config_read' ]
    name:
      groups: [ 'hunter_wave_config_read', 'hunter_wave_config_write' ]
    waveConfigName:
      groups: [ 'hunter_wave_config_read', 'hunter_wave_config_write' ]
    hunterPoolCosts:
      groups: [ 'hunter_wave_config_read', 'hunter_wave_config_write' ]
    maxHunterPerWave:
      groups: [ 'hunter_wave_config_read', 'hunter_wave_config_write' ]
    hunterDrawChances:
      groups: [ 'hunter_wave_config_read', 'hunter_wave_config_write' ]
    
 