Mush\Equipment\Entity\Config\ItemConfig:
  attributes:
    id:
      groups: [ 'item_config_read' ]
    name:
      groups: [ 'item_config_read', 'item_config_write' ]
    mechanics:
      groups: [ 'item_config_read', 'item_config_write' ]
    isFireDestroyable:
      groups: [ 'item_config_read', 'item_config_write' ]
    isFireBreakable:
      groups: [ 'item_config_read', 'item_config_write' ]
    isBreakable:
      groups: [ 'item_config_read', 'item_config_write' ]
    actions:
      groups: [ 'item_config_read', 'item_config_write' ]
    initStatus:
      groups: [ 'item_config_read', 'item_config_write' ]
    dismountedProducts:
      groups: [ 'item_config_read', 'item_config_write' ]
    isPersonal:
      groups: [ 'item_config_read', 'item_config_write' ]
    isStackable:
      groups: [ 'item_config_read', 'item_config_write' ]
    startingItems:
      groups: [ 'item_config_read', 'item_config_write' ]