Mush\Equipment\Entity\EquipmentMechanic:
  attributes:
    id:
      groups: [ 'equipment_mechanic_read' ]
    name:
      groups: [ 'equipment_mechanic_read', 'equipment_mechanic_write' ]
    mechanics:
      groups: [ 'equipment_mechanic_read', 'equipment_mechanic_write' ]
    actions:
      groups: [ 'equipment_mechanic_read', 'equipment_mechanic_write' ]
    craftedEquipmentName:
      groups: [ 'equipment_mechanic_read', 'equipment_mechanic_write' ]
    ingredients:
      groups: [ 'equipment_mechanic_read', 'equipment_mechanic_write' ]
    skill:
      groups: [ 'equipment_mechanic_read', 'equipment_mechanic_write' ]
    content:
      groups: [ 'equipment_mechanic_read', 'equipment_mechanic_write' ]
    isTranslated:
      groups: [ 'equipment_mechanic_read', 'equipment_mechanic_write' ]
    canShred:
      groups: [ 'equipment_mechanic_read', 'equipment_mechanic_write' ]
    isPerishable:
      groups: [ 'equipment_mechanic_read', 'equipment_mechanic_write' ]
    plantName:
      groups: [ 'equipment_mechanic_read', 'equipment_mechanic_write' ]
    modifierConfigs:
      groups: [ 'equipment_mechanic_read', 'equipment_mechanic_write' ]
    fruitName:
      groups: [ 'equipment_mechanic_read', 'equipment_mechanic_write' ]
    maturationTime:
      groups: [ 'equipment_mechanic_read', 'equipment_mechanic_write' ]
    oxygen:
      groups: [ 'equipment_mechanic_read', 'equipment_mechanic_write' ]
    moralPoints:
      groups: [ 'equipment_mechanic_read', 'equipment_mechanic_write' ]
    actionPoints:
      groups: [ 'equipment_mechanic_read', 'equipment_mechanic_write' ]
    movementPoints:
      groups: [ 'equipment_mechanic_read', 'equipment_mechanic_write' ]
    healthPoints:
      groups: [ 'equipment_mechanic_read', 'equipment_mechanic_write' ]
    satiety:
      groups: [ 'equipment_mechanic_read', 'equipment_mechanic_write' ]
    extraEffects:
      groups: [ 'equipment_mechanic_read', 'equipment_mechanic_write' ]
    baseAccuracy:
      groups: [ 'equipment_mechanic_read', 'equipment_mechanic_write' ]
    baseDamageRange:
      groups: [ 'equipment_mechanic_read', 'equipment_mechanic_write' ]
    expeditionBonus:
      groups: [ 'equipment_mechanic_read', 'equipment_mechanic_write' ]
    criticalSuccessRate:
      groups: [ 'equipment_mechanic_read', 'equipment_mechanic_write' ]
    criticalFailRate:
      groups: [ 'equipment_mechanic_read', 'equipment_mechanic_write' ]
    oneShotRate:
      groups: [ 'equipment_mechanic_read', 'equipment_mechanic_write' ]
    collectScrapNumber:
      groups: [ 'equipment_mechanic_read', 'equipment_mechanic_write' ]
    collectScrapPatrolShipDamage:
      groups: [ 'equipment_mechanic_read', 'equipment_mechanic_write' ]
    collectScrapPlayerDamage:
      groups: [ 'equipment_mechanic_read', 'equipment_mechanic_write' ]
    dockingPlace:
      groups: [ 'equipment_mechanic_read', 'equipment_mechanic_write' ]
    failedManoeuvreDaedalusDamage:
      groups: [ 'equipment_mechanic_read', 'equipment_mechanic_write' ]
    failedManoeuvrePatrolShipDamage:
      groups: [ 'equipment_mechanic_read', 'equipment_mechanic_write' ]
    failedManoeuvrePlayerDamage:
      groups: [ 'equipment_mechanic_read', 'equipment_mechanic_write' ]