Mush\Communication\Entity\Message:
  attributes:
    id:
      groups: [ 'message_read' ]
    createdAt:
      groups: [ 'message_read' ]
    author:
      groups: [ 'message_read' ]
    neron:
      groups: [ 'message_read' ]
    child:
      groups: [ 'message_read' ]
    parent:
      groups: [ 'message_read' ]
    channel:
      groups: [ 'message_read' ]
    message:
      groups: [ 'message_read' ]
    translationParameters:
      groups: [ 'message_read' ]