Mush\MetaGame\Entity\ModerationSanction:
  attributes:                          # optional
    id:
      groups: [ 'moderation_sanction_read' ]
    moderationAction:
      groups: [ 'moderation_sanction_read' ]
    reason:
      groups: [ 'moderation_sanction_read' ]
    message:
      groups: [ 'moderation_sanction_read' ]
    isActive:
      groups: [ 'moderation_sanction_read' ]
    startDate:
      groups: [ 'moderation_sanction_read' ]
    endDate:
      groups: [ 'moderation_sanction_read' ]
