Mush\Modifier\Entity\Condition\ModifierCondition:
  attributes:
    id:
      groups: [ 'modifier_condition_read' ]
    configs:
      groups: [ 'modifier_condition_read', 'modifier_condition_write' ]