Mush\Modifier\Entity\Config\AbstractModifierConfig:
  attributes:
    id:
      groups: [ 'modifier_config_read', 'modifier_config_write' ]
    name:
      groups: [ 'modifier_config_read', 'modifier_config_write' ]
    modifierName:
      groups: [ 'modifier_config_read', 'modifier_config_write' ]
    modifierRange:
      groups: [ 'modifier_config_read', 'modifier_config_write' ]
    modifierActivationRequirements:
      groups: [ 'modifier_config_read', 'modifier_config_write' ]
    targetEventRequirements:
      groups: [ 'modifier_config_read', 'modifier_config_write' ]
    delta:
      groups: [ 'modifier_config_read', 'modifier_config_write' ]
    targetVariable:
      groups: [ 'modifier_config_read', 'modifier_config_write' ]
    targetEvent:
      groups: [ 'modifier_config_read', 'modifier_config_write' ]
    mode:
      groups: [ 'modifier_config_read', 'modifier_config_write' ]
    applyOnTarget:
      groups: [ 'modifier_config_read', 'modifier_config_write' ]
    tagConstraints:
      groups: [ 'modifier_config_read', 'modifier_config_write' ]
    triggeredEvent:
      groups: [ 'modifier_config_read' , 'modifier_config_write' ]
    reverseOnRemove:
      groups: [ 'modifier_config_read', 'modifier_config_write' ]
    priority:
      groups: [ 'modifier_config_read', 'modifier_config_write' ]
    modifierStrategy:
      groups: [ 'modifier_config_read', 'modifier_config_write' ]
    targetFilters:
      groups: [ 'modifier_config_read', 'modifier_config_write' ]