Mush\Modifier\Entity\Config\ModifierConfig:
  attributes:
    id:
      groups: [ 'modifier_config_read' ]
    name:
      groups: [ 'modifier_config_read', 'modifier_config_write' ]
    value:
      groups: [ 'modifier_config_read', 'modifier_config_write' ]
    variable:
      groups: [ 'modifier_config_read', 'modifier_config_write' ]
    reach:
      groups: [ 'modifier_config_read', 'modifier_config_write' ]
    mode:
      groups: [ 'modifier_config_read', 'modifier_config_write' ]
    logKeyWhenApplied:
      groups: [ 'modifier_config_read', 'modifier_config_write' ]
    targetEvents:
      groups: [ 'modifier_config_read', 'modifier_config_write' ]
    conditions:
      groups: [ 'modifier_config_read', 'modifier_config_write' ]
