Mush\Modifier\Entity\ModifierConfig:
  attributes:
    id:
      groups: [ 'modifier_config_read' ]
    name:
      groups: [ 'modifier_config_read', 'modifier_config_write' ]
    delta:
      groups: [ 'modifier_config_read', 'modifier_config_write' ]
    target:
      groups: [ 'modifier_config_read', 'modifier_config_write' ]
    scope:
      groups: [ 'modifier_config_read', 'modifier_config_write' ]
    reach:
      groups: [ 'modifier_config_read', 'modifier_config_write' ]
    mode:
      groups: [ 'modifier_config_read', 'modifier_config_write' ]
    modifierConditions:
      groups: [ 'modifier_config_read', 'modifier_config_write' ]
