Mush\Equipment\Entity\PatrolShip:
  attributes:
    id:
      groups: [ 'equipment_mechanic_read' ]
    name:
      groups: [ 'equipment_mechanic_read', 'equipment_mechanic_write' ]
    mechanics:
      groups: [ 'equipment_mechanic_read', 'equipment_mechanic_write' ]
    collectScrapNumber:
      groups: [ 'equipment_mechanic_read', 'equipment_mechanic_write' ]
    collectScrapPlayerDamage:
      groups: [ 'equipment_mechanic_read', 'equipment_mechanic_write' ]
    dockingPlace:
      groups: [ 'equipment_mechanic_read', 'equipment_mechanic_write' ]
    failedManoeuvreDaedalusDamage:
      groups: [ 'equipment_mechanic_read', 'equipment_mechanic_write' ]
    failedManoeuvrePatrolShipDamage:
      groups: [ 'equipment_mechanic_read', 'equipment_mechanic_write' ]
    failedManoeuvrePlayerDamage:
      groups: [ 'equipment_mechanic_read', 'equipment_mechanic_write' ]