Mush\Equipment\Entity\Mechanics\Plant:
  attributes:
    id: 
      groups: [ 'plant_read' ]
    name:
      groups: [ 'plant_write', 'plant_read' ]
    mechanics:
      groups: [ 'plant_write' ]
    actions:
      groups: [ 'plant_write' ]
    fruitName:
      groups: [ 'plant_read', 'plant_write' ]
    maturationTime:
      groups: [ 'plant_read', 'plant_write' ]
    oxygen:
      groups: [ 'plant_read', 'plant_write' ]