Mush\Daedalus\Entity\RandomItemPlaces:
  attributes:
    id:
      groups: [ 'random_item_place_read' ]
    places:
      groups: [ 'random_item_place_read', 'random_item_place_write' ]
    items:
      groups: [ 'random_item_place_read', 'random_item_place_write' ]
