Mush\Equipment\Entity\Mechanics\Ration:
  attributes:
    id: 
      groups: [ 'ration_read' ]
    name:
      groups: [ 'ration_write' ]
    mechanics:
      groups: [ 'ration_write' ]
    actions:
      groups: [ 'ration_write' ]
    moralPoints:
      groups: [ 'ration_read', 'ration_write' ]
    actionPoints:
      groups: [ 'ration_read', 'ration_write' ]
    movementPoints:
      groups: [ 'ration_read', 'ration_write' ]
    healthPoints:
      groups: [ 'ration_read', 'ration_write' ]
    satiety:
      groups: [ 'ration_read', 'ration_write' ]
    extraEffects:
      groups: [ 'ration_read', 'ration_write' ]
    isPerishable:
      groups: [ 'ration_read', 'ration_write' ]