Mush\Disease\Entity\Config\SymptomActivationRequirement:
  attributes:                          # optional
    id:
      groups: [ 'symptom_activation_requirement_read' ]
    name:
      groups: [ 'symptom_activation_requirement_read', 'symptom_activation_requirement_write' ]
    activationRequirementName:
      groups: [ 'symptom_activation_requirement_read', 'symptom_activation_requirement_write' ]
    activationRequirement:
      groups: [ 'symptom_activation_requirement_read', 'symptom_activation_requirement_write' ]
    value:
      groups: [ 'symptom_activation_requirement_read', 'symptom_activation_requirement_write' ]

