Mush\Disease\Entity\Config\SymptomConfig:
  attributes:                          # optional
    id:
      groups: [ 'symptom_config_read' ]
    name:
      groups: [ 'symptom_config_read', 'symptom_config_write' ]
    symptomName:
      groups: [ 'symptom_config_read', 'symptom_config_write' ]
    trigger:
      groups: [ 'symptom_config_read', 'symptom_config_write' ]
    visibility:
      groups: [ 'symptom_config_read', 'symptom_config_write' ]
    symptomConditions:
      groups: [ 'symptom_config_read', 'symptom_config_write' ]