Mush\Modifier\Entity\Config\TriggerEventModifierConfig:
  attributes:
    id:
      groups: [ 'modifier_config_read' ]
    name:
      groups: [ 'modifier_config_read', 'modifier_config_write' ]
    modifierName:
      groups: [ 'modifier_config_read' , 'modifier_config_write' ]
    triggeredEvent:
      groups: [ 'modifier_config_read' , 'modifier_config_write' ]
    delta:
      groups: [ 'modifier_config_read', 'modifier_config_write' ]
    targetVariable:
      groups: [ 'modifier_config_read', 'modifier_config_write' ]
    targetEvent:
      groups: [ 'modifier_config_read', 'modifier_config_write' ]
    modifierHolderClass:
      groups: [ 'modifier_config_read', 'modifier_config_write' ]
    modifierActivationRequirements:
      groups: [ 'modifier_config_read', 'modifier_config_write' ]
    applyOnActionParameter:
      groups: [ 'modifier_config_read', 'modifier_config_write' ]