Mush\Triumph\Entity\TriumphConfig:
  attributes:
    id:
      groups: [ 'triumph_config_read' ]
    name:
      groups: [ 'triumph_config_read', 'triumph_config_write' ]
    triumph:
      groups: [ 'triumph_config_read', 'triumph_config_write' ]
    isIndividual:
      groups: [ 'triumph_config_read', 'triumph_config_write' ]
    team:
      groups: [ 'triumph_config_read', 'triumph_config_write' ]
    target:
      groups: [ 'triumph_config_read', 'triumph_config_write' ]
    quantity:
      groups: [ 'triumph_config_read', 'triumph_config_write' ]
    visibility:
      groups: [ 'triumph_config_read', 'triumph_config_write' ]
    regressiveFactor:
      groups: [ 'triumph_config_read', 'triumph_config_write' ]
    computeStrategy:
      groups: [ 'triumph_config_read', 'triumph_config_write' ]
    applicationStrategies:
      groups: [ 'triumph_config_read', 'triumph_config_write' ]
