Mush\Triumph\Entity\TriumphConfig:
  attributes:
    id:
      groups: [ 'triumph_config_read' ]
    key:
      groups: [ 'triumph_config_read', 'triumph_config_write' ]
    name:
      groups: [ 'triumph_config_read', 'triumph_config_write' ]
    scope:
      groups: [ 'triumph_config_read', 'triumph_config_write' ]
    targetedEvent:
      groups: [ 'triumph_config_read', 'triumph_config_write' ]
    targetedEventExpectedTags:
      groups: [ 'triumph_config_read', 'triumph_config_write' ]
    target:
      groups: [ 'triumph_config_read', 'triumph_config_write' ]
    quantity:
      groups: [ 'triumph_config_read', 'triumph_config_write' ]
    visibility:
      groups: [ 'triumph_config_read', 'triumph_config_write' ]
    regressiveFactor:
      groups: [ 'triumph_config_read', 'triumph_config_write' ]
