Mush\User\Entity\User:
  attributes:                          # optional
    id:
      groups: [ 'player_info_read', 'user_read' ]
    userId:
      groups: [ 'player_info_read', 'user_read' ]
    username:
      groups: [ 'player_info_read', 'user_read' ]
    currentGame:
      groups: [ 'user_read' ]
    roles:
      groups: [ 'player_info_read', 'user_read', 'user_write' ]
    isBanned:
      groups: [ 'user_read' ]
    moderationSanctions:
      groups: [ 'user_read' ]
