Mush\Equipment\Entity\Mechanics\Weapon:
  attributes:
    baseAccuracy:
      groups: [ 'weapon_read', 'weapon_write' ]
    baseDamageRange:
      groups: [ 'weapon_read', 'weapon_write' ]
    expeditionBonus:
      groups: [ 'weapon_read', 'weapon_write' ]
    criticalSuccessRate:
      groups: [ 'weapon_read', 'weapon_write' ]
    criticalFailRate:
      groups: [ 'weapon_read', 'weapon_write' ]
    oneShotRate:
      groups: [ 'weapon_read', 'weapon_write' ]