Mush\Equipment\Entity\Mechanics\Weapon:
  attributes:
    id: 
      groups: [ 'weapon_read' ]
    name:
      groups: [ 'weapon_write', 'weapon_read' ]
    mechanics:
      groups: [ 'weapon_write' ]
    actions:
      groups: [ 'weapon_write' ]
    baseAccuracy:
      groups: [ 'weapon_read', 'weapon_write' ]
    baseDamageRange:
      groups: [ 'weapon_read', 'weapon_write' ]
    expeditionBonus:
      groups: [ 'weapon_read', 'weapon_write' ]
    criticalSuccessRate:
      groups: [ 'weapon_read', 'weapon_write' ]
    criticalFailRate:
      groups: [ 'weapon_read', 'weapon_write' ]
    oneShotRate:
      groups: [ 'weapon_read', 'weapon_write' ]