<?php

namespace Mush\Game\Enum;

abstract class SkillEnum
{
    public const ANTIQUE_PERFUME = 'antique_perfume';
    public const APPRENTICE = 'apprentice';
    public const ASTROPHYSICIST = 'astrophysicist';
    public const BIOLOGIST = 'biologist';
    public const BOTANIST = 'botanist';
    public const CAFFEINE_JUNKIE = 'caffeine_junkie';
    public const CHEF = ' chef';
    public const COLD_BLOODED = 'cold_blooded';
    public const CONFIDENT = 'confident';
    public const CRAZY_EYE = 'crazy_eye';
    public const CREATIVE = 'creative';
    public const DESIGNER = 'designer';
    public const DETACHED_CREWMEMBER = 'detached_crewmember';
    public const DEVOTION = 'devotion';
    public const DETERMINED = 'determined';
    public const DIPLOMAT = 'diplomat';
    public const EXPERT = 'expert';
    public const FIREFIGHTER = 'firefighter';
    public const FRUGIVORE = 'frugivore';
    public const GENIUS = 'genius';
    public const GREEN_THUMB = 'green_thumb';
    public const GUNNER = 'gunner';
    public const INTIMIDATING = 'intimidating';
    public const IT_EXPERT = 'it_expert';
    public const LEADER = 'leader';
    public const LETHARGY = 'lethargy';
    public const LOGISTICS_EXPERT = 'logistics_expert';
    public const MANKIND_ONLY_HOPE = 'mankind_only_hope';
    public const MEDIC = 'medic';
    public const METALWORKER = 'metalworker';
    public const MOTIVATOR = 'motivator';
    public const MYCOLOGIST = 'mycologist';
    public const NERON_ONLY_FRIEND = 'neron_only_friend';
    public const NURSE = 'nurse';
    public const OBSERVANT = 'observant';
    public const OCD = 'ocd';
    public const OPPORTUNIST = 'opportunist';
    public const PANIC = 'panic';
    public const PARANOID = 'paranoid';
    public const PHYSICIST = 'physicist';
    public const PILOT = 'pilot';
    public const POLITICIAN = 'politician';
    public const POLYMATH = 'polymath';
    public const POLYVALENT = 'polyvalent';
    public const PREMONITION = 'premonition';
    public const RADIO_EXPERT = 'radio_expert';
    public const REBEL = 'rebel';
    public const ROBOTICS_EXPERT = 'robotics_expert';
    public const SELF_SACRIFICE = 'self_sacrifice';
    public const SHOOTER = 'shooter';
    public const SHRINK = 'shrink';
    public const SNEAK = 'sneak';
    public const SOLID = 'solid';
    public const SPRINTER = 'sprinter';
    public const STRATEGURU = 'strateguru';
    public const SURVIVALIST = 'survivalist';
    public const TECHNICIAN = 'technician';
    public const OPTIMIST = 'optimist';
    public const TORTURER = 'torturer';
    public const TRACKER = 'tracker';
    public const U_TURN = 'u_turn';
    public const VICTIMIZER = 'victimizer';
    public const WRESTLER = 'wrestler';
    public const HYGIENIST = 'hygienist';
}
