
services:

  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

  # makes classes in src/ available to be used as services
  # this creates a service per class whose id is the fully-qualified class name
  Mush\Status\:
    resource: '../'
    exclude:
      - '../DependencyInjection/'
      - '../Entity/'
      - '../Kernel.php'
      - '../Tests/'

  Mush\Status\ChargeStrategies\:
    resource: '../ChargeStrategies/'
    tags: ['mush.charge_strategy']

  Mush\Status\CycleHandler\:
    resource: '../CycleHandler/'
    tags: ['mush.status.cycle_handler']

  Mush\Status\Service\ConfigData\ChargeStatusConfigDataLoader:
    public: true
  Mush\Status\Service\ConfigData\StatusConfigDataLoader:
    public: true