#!/bin/sh

# Check if php-cs-fixer is available
if ! command -v php-cs-fixer >/dev/null 2>&1; then
    echo "Error: php-cs-fixer not found. Please install it using composer."
    exit 1
fi

# Check if yarn is available
if ! command -v yarn >/dev/null 2>&1; then
    echo "Error: yarn not found. Please install it using 'npm install -g yarn'"
    exit 1
fi

# Run php-cs-fixer if .php files are modified
if git diff --name-only --cached | grep -E '\.php$'; then
    echo 'Running php-cs-fixer'
    php-cs-fixer fix
fi

# Run eslint if .vue, .js, .ts, .scss, or .css files are modified
if git diff --name-only --cached | grep -E '\.(vue|js|ts|scss|css)$'; then
    echo 'Running eslint'
    cd App && yarn lint && cd ..
fi
