#!/bin/sh

docker compose -f docker/docker-compose.yml exec -T -u dev mush_php vendor/bin/php-cs-fixer check --diff || exit 1
docker compose -f docker/docker-compose.yml exec -T -u dev mush_php vendor/bin/psalm || exit 1
docker compose -f docker/docker-compose.yml exec -T -u dev mush_php vendor/bin/phpmd src text phpmd.xml --exclude src/*/DataFixtures/*,src/*/ConfigData/* --ignore-errors-on-exit || exit 1
docker compose -f docker/docker-compose.yml exec -T -u node mush_front yarn lint --no-fix || exit 1