<?php

namespace Mush\Disease\ConfigData;

/** @codeCoverageIgnore */
class ConsumableDiseaseConfigData
{
    public static array $dataArray = [
        [
            'name' => 'creepnut_default',
            'causeName' => 'creepnut',
            'diseasesName' => ['cat_allergy' => 1, 'mush_allergy' => 1, 'sepsis' => 1, 'slight_nausea' => 1, 'smallpox' => 1, 'syphilis' => 1, 'ailurophobia' => 1, 'coprolalia' => 1, 'spleen' => 1, 'weapon_phobia' => 1, 'chronic_vertigo' => 1, 'paranoia' => 1, 'acid_reflux' => 2, 'skin_inflammation' => 2, 'agoraphobia' => 2, 'chronic_migraine' => 2, 'vertigo' => 2, 'depression' => 2, 'psychotic_episodes' => 2, 'crabism' => 4, 'black_bite' => 4, 'cold' => 4, 'extreme_tinnitus' => 4, 'food_poisoning' => 4, 'fungic_infection' => 4, 'rejuvenation' => 4, 'rubella' => 4, 'sinus_storm' => 4, 'space_rabies' => 4, 'vitamin_deficiency' => 4, 'flu' => 8, 'gastroenteritis' => 8, 'migraine' => 8, 'tapeworm' => 8],
            'curesName' => ['cat_allergy' => 1, 'mush_allergy' => 1, 'sepsis' => 1, 'slight_nausea' => 1, 'smallpox' => 1, 'syphilis' => 1, 'ailurophobia' => 1, 'coprolalia' => 1, 'spleen' => 1, 'weapon_phobia' => 1, 'chronic_vertigo' => 1, 'paranoia' => 1, 'acid_reflux' => 2, 'skin_inflammation' => 2, 'agoraphobia' => 2, 'chronic_migraine' => 2, 'vertigo' => 2, 'depression' => 2, 'psychotic_episodes' => 2, 'crabism' => 4, 'black_bite' => 4, 'cold' => 4, 'extreme_tinnitus' => 4, 'food_poisoning' => 4, 'fungic_infection' => 4, 'rejuvenation' => 4, 'rubella' => 4, 'sinus_storm' => 4, 'space_rabies' => 4, 'vitamin_deficiency' => 4, 'flu' => 8, 'gastroenteritis' => 8, 'migraine' => 8, 'tapeworm' => 8],
            'diseasesChances' => [100 => 64, 25 => 1, 30 => 2, 35 => 3, 40 => 4, 45 => 5, 50 => 6, 55 => 5, 60 => 4, 65 => 3, 70 => 2, 75 => 1],
            'curesChances' => [100 => 64, 25 => 1, 30 => 2, 35 => 3, 40 => 4, 45 => 5, 50 => 6, 55 => 5, 60 => 4, 65 => 3, 70 => 2, 75 => 1],
            'diseasesDelayMin' => [0 => 1, 1 => 1, 2 => 1, 3 => 1, 4 => 1, 5 => 1, 6 => 1, 7 => 1, 8 => 1, 9 => 1, 10 => 1, 11 => 1],
            'diseasesDelayLength' => [0 => 1, 1 => 1, 2 => 1, 3 => 1, 4 => 1, 5 => 1, 6 => 1, 7 => 1, 8 => 1],
            'effectNumber' => [0 => 35, 1 => 40, 2 => 15, 3 => 9, 4 => 1],
        ],
        [
            'name' => 'meztine_default',
            'causeName' => 'meztine',
            'diseasesName' => ['cat_allergy' => 1, 'mush_allergy' => 1, 'sepsis' => 1, 'slight_nausea' => 1, 'smallpox' => 1, 'syphilis' => 1, 'ailurophobia' => 1, 'coprolalia' => 1, 'spleen' => 1, 'weapon_phobia' => 1, 'chronic_vertigo' => 1, 'paranoia' => 1, 'acid_reflux' => 2, 'skin_inflammation' => 2, 'agoraphobia' => 2, 'chronic_migraine' => 2, 'vertigo' => 2, 'depression' => 2, 'psychotic_episodes' => 2, 'crabism' => 4, 'black_bite' => 4, 'cold' => 4, 'extreme_tinnitus' => 4, 'food_poisoning' => 4, 'fungic_infection' => 4, 'rejuvenation' => 4, 'rubella' => 4, 'sinus_storm' => 4, 'space_rabies' => 4, 'vitamin_deficiency' => 4, 'flu' => 8, 'gastroenteritis' => 8, 'migraine' => 8, 'tapeworm' => 8],
            'curesName' => ['cat_allergy' => 1, 'mush_allergy' => 1, 'sepsis' => 1, 'slight_nausea' => 1, 'smallpox' => 1, 'syphilis' => 1, 'ailurophobia' => 1, 'coprolalia' => 1, 'spleen' => 1, 'weapon_phobia' => 1, 'chronic_vertigo' => 1, 'paranoia' => 1, 'acid_reflux' => 2, 'skin_inflammation' => 2, 'agoraphobia' => 2, 'chronic_migraine' => 2, 'vertigo' => 2, 'depression' => 2, 'psychotic_episodes' => 2, 'crabism' => 4, 'black_bite' => 4, 'cold' => 4, 'extreme_tinnitus' => 4, 'food_poisoning' => 4, 'fungic_infection' => 4, 'rejuvenation' => 4, 'rubella' => 4, 'sinus_storm' => 4, 'space_rabies' => 4, 'vitamin_deficiency' => 4, 'flu' => 8, 'gastroenteritis' => 8, 'migraine' => 8, 'tapeworm' => 8],
            'diseasesChances' => [100 => 64, 25 => 1, 30 => 2, 35 => 3, 40 => 4, 45 => 5, 50 => 6, 55 => 5, 60 => 4, 65 => 3, 70 => 2, 75 => 1],
            'curesChances' => [100 => 64, 25 => 1, 30 => 2, 35 => 3, 40 => 4, 45 => 5, 50 => 6, 55 => 5, 60 => 4, 65 => 3, 70 => 2, 75 => 1],
            'diseasesDelayMin' => [0 => 1, 1 => 1, 2 => 1, 3 => 1, 4 => 1, 5 => 1, 6 => 1, 7 => 1, 8 => 1, 9 => 1, 10 => 1, 11 => 1],
            'diseasesDelayLength' => [0 => 1, 1 => 1, 2 => 1, 3 => 1, 4 => 1, 5 => 1, 6 => 1, 7 => 1, 8 => 1],
            'effectNumber' => [0 => 35, 1 => 40, 2 => 15, 3 => 9, 4 => 1],
        ],
        [
            'name' => 'guntiflop_default',
            'causeName' => 'guntiflop',
            'diseasesName' => ['cat_allergy' => 1, 'mush_allergy' => 1, 'sepsis' => 1, 'slight_nausea' => 1, 'smallpox' => 1, 'syphilis' => 1, 'ailurophobia' => 1, 'coprolalia' => 1, 'spleen' => 1, 'weapon_phobia' => 1, 'chronic_vertigo' => 1, 'paranoia' => 1, 'acid_reflux' => 2, 'skin_inflammation' => 2, 'agoraphobia' => 2, 'chronic_migraine' => 2, 'vertigo' => 2, 'depression' => 2, 'psychotic_episodes' => 2, 'crabism' => 4, 'black_bite' => 4, 'cold' => 4, 'extreme_tinnitus' => 4, 'food_poisoning' => 4, 'fungic_infection' => 4, 'rejuvenation' => 4, 'rubella' => 4, 'sinus_storm' => 4, 'space_rabies' => 4, 'vitamin_deficiency' => 4, 'flu' => 8, 'gastroenteritis' => 8, 'migraine' => 8, 'tapeworm' => 8],
            'curesName' => ['cat_allergy' => 1, 'mush_allergy' => 1, 'sepsis' => 1, 'slight_nausea' => 1, 'smallpox' => 1, 'syphilis' => 1, 'ailurophobia' => 1, 'coprolalia' => 1, 'spleen' => 1, 'weapon_phobia' => 1, 'chronic_vertigo' => 1, 'paranoia' => 1, 'acid_reflux' => 2, 'skin_inflammation' => 2, 'agoraphobia' => 2, 'chronic_migraine' => 2, 'vertigo' => 2, 'depression' => 2, 'psychotic_episodes' => 2, 'crabism' => 4, 'black_bite' => 4, 'cold' => 4, 'extreme_tinnitus' => 4, 'food_poisoning' => 4, 'fungic_infection' => 4, 'rejuvenation' => 4, 'rubella' => 4, 'sinus_storm' => 4, 'space_rabies' => 4, 'vitamin_deficiency' => 4, 'flu' => 8, 'gastroenteritis' => 8, 'migraine' => 8, 'tapeworm' => 8],
            'diseasesChances' => [100 => 64, 25 => 1, 30 => 2, 35 => 3, 40 => 4, 45 => 5, 50 => 6, 55 => 5, 60 => 4, 65 => 3, 70 => 2, 75 => 1],
            'curesChances' => [100 => 64, 25 => 1, 30 => 2, 35 => 3, 40 => 4, 45 => 5, 50 => 6, 55 => 5, 60 => 4, 65 => 3, 70 => 2, 75 => 1],
            'diseasesDelayMin' => [0 => 1, 1 => 1, 2 => 1, 3 => 1, 4 => 1, 5 => 1, 6 => 1, 7 => 1, 8 => 1, 9 => 1, 10 => 1, 11 => 1],
            'diseasesDelayLength' => [0 => 1, 1 => 1, 2 => 1, 3 => 1, 4 => 1, 5 => 1, 6 => 1, 7 => 1, 8 => 1],
            'effectNumber' => [0 => 35, 1 => 40, 2 => 15, 3 => 9, 4 => 1],
        ],
        [
            'name' => 'ploshmina_default',
            'causeName' => 'ploshmina',
            'diseasesName' => ['cat_allergy' => 1, 'mush_allergy' => 1, 'sepsis' => 1, 'slight_nausea' => 1, 'smallpox' => 1, 'syphilis' => 1, 'ailurophobia' => 1, 'coprolalia' => 1, 'spleen' => 1, 'weapon_phobia' => 1, 'chronic_vertigo' => 1, 'paranoia' => 1, 'acid_reflux' => 2, 'skin_inflammation' => 2, 'agoraphobia' => 2, 'chronic_migraine' => 2, 'vertigo' => 2, 'depression' => 2, 'psychotic_episodes' => 2, 'crabism' => 4, 'black_bite' => 4, 'cold' => 4, 'extreme_tinnitus' => 4, 'food_poisoning' => 4, 'fungic_infection' => 4, 'rejuvenation' => 4, 'rubella' => 4, 'sinus_storm' => 4, 'space_rabies' => 4, 'vitamin_deficiency' => 4, 'flu' => 8, 'gastroenteritis' => 8, 'migraine' => 8, 'tapeworm' => 8],
            'curesName' => ['cat_allergy' => 1, 'mush_allergy' => 1, 'sepsis' => 1, 'slight_nausea' => 1, 'smallpox' => 1, 'syphilis' => 1, 'ailurophobia' => 1, 'coprolalia' => 1, 'spleen' => 1, 'weapon_phobia' => 1, 'chronic_vertigo' => 1, 'paranoia' => 1, 'acid_reflux' => 2, 'skin_inflammation' => 2, 'agoraphobia' => 2, 'chronic_migraine' => 2, 'vertigo' => 2, 'depression' => 2, 'psychotic_episodes' => 2, 'crabism' => 4, 'black_bite' => 4, 'cold' => 4, 'extreme_tinnitus' => 4, 'food_poisoning' => 4, 'fungic_infection' => 4, 'rejuvenation' => 4, 'rubella' => 4, 'sinus_storm' => 4, 'space_rabies' => 4, 'vitamin_deficiency' => 4, 'flu' => 8, 'gastroenteritis' => 8, 'migraine' => 8, 'tapeworm' => 8],
            'diseasesChances' => [100 => 64, 25 => 1, 30 => 2, 35 => 3, 40 => 4, 45 => 5, 50 => 6, 55 => 5, 60 => 4, 65 => 3, 70 => 2, 75 => 1],
            'curesChances' => [100 => 64, 25 => 1, 30 => 2, 35 => 3, 40 => 4, 45 => 5, 50 => 6, 55 => 5, 60 => 4, 65 => 3, 70 => 2, 75 => 1],
            'diseasesDelayMin' => [0 => 1, 1 => 1, 2 => 1, 3 => 1, 4 => 1, 5 => 1, 6 => 1, 7 => 1, 8 => 1, 9 => 1, 10 => 1, 11 => 1],
            'diseasesDelayLength' => [0 => 1, 1 => 1, 2 => 1, 3 => 1, 4 => 1, 5 => 1, 6 => 1, 7 => 1, 8 => 1],
            'effectNumber' => [0 => 35, 1 => 40, 2 => 15, 3 => 9, 4 => 1],
        ],
        [
            'name' => 'bacta_default',
            'causeName' => 'bacta',
            'diseasesName' => [],
            'curesName' => ['vitamin_deficiency' => 1, 'syphilis' => 1, 'skin_inflammation' => 1, 'gastroenteritis' => 1, 'flu' => 1, 'sepsis' => 1, 'cold' => 1, 'rubella' => 1, 'sinus_storm' => 1, 'tapeworm' => 1, 'paranoia' => 1, 'depression' => 1, 'chronic_migraine' => 1],
            'diseasesChances' => [],
            'curesChances' => [100 => 1],
            'diseasesDelayMin' => [],
            'diseasesDelayLength' => [],
            'effectNumber' => [1 => 60, 2 => 30, 3 => 8, 4 => 1],
        ],
        [
            'name' => 'precati_default',
            'causeName' => 'precati',
            'diseasesName' => ['cat_allergy' => 1, 'mush_allergy' => 1, 'sepsis' => 1, 'slight_nausea' => 1, 'smallpox' => 1, 'syphilis' => 1, 'ailurophobia' => 1, 'coprolalia' => 1, 'spleen' => 1, 'weapon_phobia' => 1, 'chronic_vertigo' => 1, 'paranoia' => 1, 'acid_reflux' => 2, 'skin_inflammation' => 2, 'agoraphobia' => 2, 'chronic_migraine' => 2, 'vertigo' => 2, 'depression' => 2, 'psychotic_episodes' => 2, 'crabism' => 4, 'black_bite' => 4, 'cold' => 4, 'extreme_tinnitus' => 4, 'food_poisoning' => 4, 'fungic_infection' => 4, 'rejuvenation' => 4, 'rubella' => 4, 'sinus_storm' => 4, 'space_rabies' => 4, 'vitamin_deficiency' => 4, 'flu' => 8, 'gastroenteritis' => 8, 'migraine' => 8, 'tapeworm' => 8],
            'curesName' => ['cat_allergy' => 1, 'mush_allergy' => 1, 'sepsis' => 1, 'slight_nausea' => 1, 'smallpox' => 1, 'syphilis' => 1, 'ailurophobia' => 1, 'coprolalia' => 1, 'spleen' => 1, 'weapon_phobia' => 1, 'chronic_vertigo' => 1, 'paranoia' => 1, 'acid_reflux' => 2, 'skin_inflammation' => 2, 'agoraphobia' => 2, 'chronic_migraine' => 2, 'vertigo' => 2, 'depression' => 2, 'psychotic_episodes' => 2, 'crabism' => 4, 'black_bite' => 4, 'cold' => 4, 'extreme_tinnitus' => 4, 'food_poisoning' => 4, 'fungic_infection' => 4, 'rejuvenation' => 4, 'rubella' => 4, 'sinus_storm' => 4, 'space_rabies' => 4, 'vitamin_deficiency' => 4, 'flu' => 8, 'gastroenteritis' => 8, 'migraine' => 8, 'tapeworm' => 8],
            'diseasesChances' => [100 => 64, 25 => 1, 30 => 2, 35 => 3, 40 => 4, 45 => 5, 50 => 6, 55 => 5, 60 => 4, 65 => 3, 70 => 2, 75 => 1],
            'curesChances' => [100 => 64, 25 => 1, 30 => 2, 35 => 3, 40 => 4, 45 => 5, 50 => 6, 55 => 5, 60 => 4, 65 => 3, 70 => 2, 75 => 1],
            'diseasesDelayMin' => [0 => 1, 1 => 1, 2 => 1, 3 => 1, 4 => 1, 5 => 1, 6 => 1, 7 => 1, 8 => 1, 9 => 1, 10 => 1, 11 => 1],
            'diseasesDelayLength' => [0 => 1, 1 => 1, 2 => 1, 3 => 1, 4 => 1, 5 => 1, 6 => 1, 7 => 1, 8 => 1],
            'effectNumber' => [0 => 35, 1 => 40, 2 => 15, 3 => 9, 4 => 1],
        ],
        [
            'name' => 'bottine_default',
            'causeName' => 'bottine',
            'diseasesName' => ['cat_allergy' => 1, 'mush_allergy' => 1, 'sepsis' => 1, 'slight_nausea' => 1, 'smallpox' => 1, 'syphilis' => 1, 'ailurophobia' => 1, 'coprolalia' => 1, 'spleen' => 1, 'weapon_phobia' => 1, 'chronic_vertigo' => 1, 'paranoia' => 1, 'acid_reflux' => 2, 'skin_inflammation' => 2, 'agoraphobia' => 2, 'chronic_migraine' => 2, 'vertigo' => 2, 'depression' => 2, 'psychotic_episodes' => 2, 'crabism' => 4, 'black_bite' => 4, 'cold' => 4, 'extreme_tinnitus' => 4, 'food_poisoning' => 4, 'fungic_infection' => 4, 'rejuvenation' => 4, 'rubella' => 4, 'sinus_storm' => 4, 'space_rabies' => 4, 'vitamin_deficiency' => 4, 'flu' => 8, 'gastroenteritis' => 8, 'migraine' => 8, 'tapeworm' => 8],
            'curesName' => ['cat_allergy' => 1, 'mush_allergy' => 1, 'sepsis' => 1, 'slight_nausea' => 1, 'smallpox' => 1, 'syphilis' => 1, 'ailurophobia' => 1, 'coprolalia' => 1, 'spleen' => 1, 'weapon_phobia' => 1, 'chronic_vertigo' => 1, 'paranoia' => 1, 'acid_reflux' => 2, 'skin_inflammation' => 2, 'agoraphobia' => 2, 'chronic_migraine' => 2, 'vertigo' => 2, 'depression' => 2, 'psychotic_episodes' => 2, 'crabism' => 4, 'black_bite' => 4, 'cold' => 4, 'extreme_tinnitus' => 4, 'food_poisoning' => 4, 'fungic_infection' => 4, 'rejuvenation' => 4, 'rubella' => 4, 'sinus_storm' => 4, 'space_rabies' => 4, 'vitamin_deficiency' => 4, 'flu' => 8, 'gastroenteritis' => 8, 'migraine' => 8, 'tapeworm' => 8],
            'diseasesChances' => [100 => 64, 25 => 1, 30 => 2, 35 => 3, 40 => 4, 45 => 5, 50 => 6, 55 => 5, 60 => 4, 65 => 3, 70 => 2, 75 => 1],
            'curesChances' => [100 => 64, 25 => 1, 30 => 2, 35 => 3, 40 => 4, 45 => 5, 50 => 6, 55 => 5, 60 => 4, 65 => 3, 70 => 2, 75 => 1],
            'diseasesDelayMin' => [0 => 1, 1 => 1, 2 => 1, 3 => 1, 4 => 1, 5 => 1, 6 => 1, 7 => 1, 8 => 1, 9 => 1, 10 => 1, 11 => 1],
            'diseasesDelayLength' => [0 => 1, 1 => 1, 2 => 1, 3 => 1, 4 => 1, 5 => 1, 6 => 1, 7 => 1, 8 => 1],
            'effectNumber' => [0 => 35, 1 => 40, 2 => 15, 3 => 9, 4 => 1],
        ],
        [
            'name' => 'fragilane_default',
            'causeName' => 'fragilane',
            'diseasesName' => ['cat_allergy' => 1, 'mush_allergy' => 1, 'sepsis' => 1, 'slight_nausea' => 1, 'smallpox' => 1, 'syphilis' => 1, 'ailurophobia' => 1, 'coprolalia' => 1, 'spleen' => 1, 'weapon_phobia' => 1, 'chronic_vertigo' => 1, 'paranoia' => 1, 'acid_reflux' => 2, 'skin_inflammation' => 2, 'agoraphobia' => 2, 'chronic_migraine' => 2, 'vertigo' => 2, 'depression' => 2, 'psychotic_episodes' => 2, 'crabism' => 4, 'black_bite' => 4, 'cold' => 4, 'extreme_tinnitus' => 4, 'food_poisoning' => 4, 'fungic_infection' => 4, 'rejuvenation' => 4, 'rubella' => 4, 'sinus_storm' => 4, 'space_rabies' => 4, 'vitamin_deficiency' => 4, 'flu' => 8, 'gastroenteritis' => 8, 'migraine' => 8, 'tapeworm' => 8],
            'curesName' => ['cat_allergy' => 1, 'mush_allergy' => 1, 'sepsis' => 1, 'slight_nausea' => 1, 'smallpox' => 1, 'syphilis' => 1, 'ailurophobia' => 1, 'coprolalia' => 1, 'spleen' => 1, 'weapon_phobia' => 1, 'chronic_vertigo' => 1, 'paranoia' => 1, 'acid_reflux' => 2, 'skin_inflammation' => 2, 'agoraphobia' => 2, 'chronic_migraine' => 2, 'vertigo' => 2, 'depression' => 2, 'psychotic_episodes' => 2, 'crabism' => 4, 'black_bite' => 4, 'cold' => 4, 'extreme_tinnitus' => 4, 'food_poisoning' => 4, 'fungic_infection' => 4, 'rejuvenation' => 4, 'rubella' => 4, 'sinus_storm' => 4, 'space_rabies' => 4, 'vitamin_deficiency' => 4, 'flu' => 8, 'gastroenteritis' => 8, 'migraine' => 8, 'tapeworm' => 8],
            'diseasesChances' => [100 => 64, 25 => 1, 30 => 2, 35 => 3, 40 => 4, 45 => 5, 50 => 6, 55 => 5, 60 => 4, 65 => 3, 70 => 2, 75 => 1],
            'curesChances' => [100 => 64, 25 => 1, 30 => 2, 35 => 3, 40 => 4, 45 => 5, 50 => 6, 55 => 5, 60 => 4, 65 => 3, 70 => 2, 75 => 1],
            'diseasesDelayMin' => [0 => 1, 1 => 1, 2 => 1, 3 => 1, 4 => 1, 5 => 1, 6 => 1, 7 => 1, 8 => 1, 9 => 1, 10 => 1, 11 => 1],
            'diseasesDelayLength' => [0 => 1, 1 => 1, 2 => 1, 3 => 1, 4 => 1, 5 => 1, 6 => 1, 7 => 1, 8 => 1],
            'effectNumber' => [0 => 35, 1 => 40, 2 => 15, 3 => 9, 4 => 1],
        ],
        [
            'name' => 'anemole_default',
            'causeName' => 'anemole',
            'diseasesName' => ['cat_allergy' => 1, 'mush_allergy' => 1, 'sepsis' => 1, 'slight_nausea' => 1, 'smallpox' => 1, 'syphilis' => 1, 'ailurophobia' => 1, 'coprolalia' => 1, 'spleen' => 1, 'weapon_phobia' => 1, 'chronic_vertigo' => 1, 'paranoia' => 1, 'acid_reflux' => 2, 'skin_inflammation' => 2, 'agoraphobia' => 2, 'chronic_migraine' => 2, 'vertigo' => 2, 'depression' => 2, 'psychotic_episodes' => 2, 'crabism' => 4, 'black_bite' => 4, 'cold' => 4, 'extreme_tinnitus' => 4, 'food_poisoning' => 4, 'fungic_infection' => 4, 'rejuvenation' => 4, 'rubella' => 4, 'sinus_storm' => 4, 'space_rabies' => 4, 'vitamin_deficiency' => 4, 'flu' => 8, 'gastroenteritis' => 8, 'migraine' => 8, 'tapeworm' => 8],
            'curesName' => ['cat_allergy' => 1, 'mush_allergy' => 1, 'sepsis' => 1, 'slight_nausea' => 1, 'smallpox' => 1, 'syphilis' => 1, 'ailurophobia' => 1, 'coprolalia' => 1, 'spleen' => 1, 'weapon_phobia' => 1, 'chronic_vertigo' => 1, 'paranoia' => 1, 'acid_reflux' => 2, 'skin_inflammation' => 2, 'agoraphobia' => 2, 'chronic_migraine' => 2, 'vertigo' => 2, 'depression' => 2, 'psychotic_episodes' => 2, 'crabism' => 4, 'black_bite' => 4, 'cold' => 4, 'extreme_tinnitus' => 4, 'food_poisoning' => 4, 'fungic_infection' => 4, 'rejuvenation' => 4, 'rubella' => 4, 'sinus_storm' => 4, 'space_rabies' => 4, 'vitamin_deficiency' => 4, 'flu' => 8, 'gastroenteritis' => 8, 'migraine' => 8, 'tapeworm' => 8],
            'diseasesChances' => [100 => 64, 25 => 1, 30 => 2, 35 => 3, 40 => 4, 45 => 5, 50 => 6, 55 => 5, 60 => 4, 65 => 3, 70 => 2, 75 => 1],
            'curesChances' => [100 => 64, 25 => 1, 30 => 2, 35 => 3, 40 => 4, 45 => 5, 50 => 6, 55 => 5, 60 => 4, 65 => 3, 70 => 2, 75 => 1],
            'diseasesDelayMin' => [0 => 1, 1 => 1, 2 => 1, 3 => 1, 4 => 1, 5 => 1, 6 => 1, 7 => 1, 8 => 1, 9 => 1, 10 => 1, 11 => 1],
            'diseasesDelayLength' => [0 => 1, 1 => 1, 2 => 1, 3 => 1, 4 => 1, 5 => 1, 6 => 1, 7 => 1, 8 => 1],
            'effectNumber' => [0 => 35, 1 => 40, 2 => 15, 3 => 9, 4 => 1],
        ],
        [
            'name' => 'betapropyl_default',
            'causeName' => 'betapropyl',
            'diseasesName' => [],
            'curesName' => ['vitamin_deficiency' => 1, 'syphilis' => 1, 'skin_inflammation' => 1, 'gastroenteritis' => 1, 'flu' => 1, 'sepsis' => 1, 'cold' => 1, 'rubella' => 1, 'sinus_storm' => 1, 'tapeworm' => 1, 'paranoia' => 1, 'depression' => 1, 'chronic_migraine' => 1],
            'diseasesChances' => [],
            'curesChances' => [100 => 1],
            'diseasesDelayMin' => [],
            'diseasesDelayLength' => [],
            'effectNumber' => [1 => 60, 2 => 30, 3 => 8, 4 => 1],
        ],
        [
            'name' => 'peniraft_default',
            'causeName' => 'peniraft',
            'diseasesName' => ['cat_allergy' => 1, 'mush_allergy' => 1, 'sepsis' => 1, 'slight_nausea' => 1, 'smallpox' => 1, 'syphilis' => 1, 'ailurophobia' => 1, 'coprolalia' => 1, 'spleen' => 1, 'weapon_phobia' => 1, 'chronic_vertigo' => 1, 'paranoia' => 1, 'acid_reflux' => 2, 'skin_inflammation' => 2, 'agoraphobia' => 2, 'chronic_migraine' => 2, 'vertigo' => 2, 'depression' => 2, 'psychotic_episodes' => 2, 'crabism' => 4, 'black_bite' => 4, 'cold' => 4, 'extreme_tinnitus' => 4, 'food_poisoning' => 4, 'fungic_infection' => 4, 'rejuvenation' => 4, 'rubella' => 4, 'sinus_storm' => 4, 'space_rabies' => 4, 'vitamin_deficiency' => 4, 'flu' => 8, 'gastroenteritis' => 8, 'migraine' => 8, 'tapeworm' => 8],
            'curesName' => ['cat_allergy' => 1, 'mush_allergy' => 1, 'sepsis' => 1, 'slight_nausea' => 1, 'smallpox' => 1, 'syphilis' => 1, 'ailurophobia' => 1, 'coprolalia' => 1, 'spleen' => 1, 'weapon_phobia' => 1, 'chronic_vertigo' => 1, 'paranoia' => 1, 'acid_reflux' => 2, 'skin_inflammation' => 2, 'agoraphobia' => 2, 'chronic_migraine' => 2, 'vertigo' => 2, 'depression' => 2, 'psychotic_episodes' => 2, 'crabism' => 4, 'black_bite' => 4, 'cold' => 4, 'extreme_tinnitus' => 4, 'food_poisoning' => 4, 'fungic_infection' => 4, 'rejuvenation' => 4, 'rubella' => 4, 'sinus_storm' => 4, 'space_rabies' => 4, 'vitamin_deficiency' => 4, 'flu' => 8, 'gastroenteritis' => 8, 'migraine' => 8, 'tapeworm' => 8],
            'diseasesChances' => [100 => 64, 25 => 1, 30 => 2, 35 => 3, 40 => 4, 45 => 5, 50 => 6, 55 => 5, 60 => 4, 65 => 3, 70 => 2, 75 => 1],
            'curesChances' => [100 => 64, 25 => 1, 30 => 2, 35 => 3, 40 => 4, 45 => 5, 50 => 6, 55 => 5, 60 => 4, 65 => 3, 70 => 2, 75 => 1],
            'diseasesDelayMin' => [0 => 1, 1 => 1, 2 => 1, 3 => 1, 4 => 1, 5 => 1, 6 => 1, 7 => 1, 8 => 1, 9 => 1, 10 => 1, 11 => 1],
            'diseasesDelayLength' => [0 => 1, 1 => 1, 2 => 1, 3 => 1, 4 => 1, 5 => 1, 6 => 1, 7 => 1, 8 => 1],
            'effectNumber' => [0 => 35, 1 => 40, 2 => 15, 3 => 9, 4 => 1],
        ],
        [
            'name' => 'kubinus_default',
            'causeName' => 'kubinus',
            'diseasesName' => ['cat_allergy' => 1, 'mush_allergy' => 1, 'sepsis' => 1, 'slight_nausea' => 1, 'smallpox' => 1, 'syphilis' => 1, 'ailurophobia' => 1, 'coprolalia' => 1, 'spleen' => 1, 'weapon_phobia' => 1, 'chronic_vertigo' => 1, 'paranoia' => 1, 'acid_reflux' => 2, 'skin_inflammation' => 2, 'agoraphobia' => 2, 'chronic_migraine' => 2, 'vertigo' => 2, 'depression' => 2, 'psychotic_episodes' => 2, 'crabism' => 4, 'black_bite' => 4, 'cold' => 4, 'extreme_tinnitus' => 4, 'food_poisoning' => 4, 'fungic_infection' => 4, 'rejuvenation' => 4, 'rubella' => 4, 'sinus_storm' => 4, 'space_rabies' => 4, 'vitamin_deficiency' => 4, 'flu' => 8, 'gastroenteritis' => 8, 'migraine' => 8, 'tapeworm' => 8],
            'curesName' => ['cat_allergy' => 1, 'mush_allergy' => 1, 'sepsis' => 1, 'slight_nausea' => 1, 'smallpox' => 1, 'syphilis' => 1, 'ailurophobia' => 1, 'coprolalia' => 1, 'spleen' => 1, 'weapon_phobia' => 1, 'chronic_vertigo' => 1, 'paranoia' => 1, 'acid_reflux' => 2, 'skin_inflammation' => 2, 'agoraphobia' => 2, 'chronic_migraine' => 2, 'vertigo' => 2, 'depression' => 2, 'psychotic_episodes' => 2, 'crabism' => 4, 'black_bite' => 4, 'cold' => 4, 'extreme_tinnitus' => 4, 'food_poisoning' => 4, 'fungic_infection' => 4, 'rejuvenation' => 4, 'rubella' => 4, 'sinus_storm' => 4, 'space_rabies' => 4, 'vitamin_deficiency' => 4, 'flu' => 8, 'gastroenteritis' => 8, 'migraine' => 8, 'tapeworm' => 8],
            'diseasesChances' => [100 => 64, 25 => 1, 30 => 2, 35 => 3, 40 => 4, 45 => 5, 50 => 6, 55 => 5, 60 => 4, 65 => 3, 70 => 2, 75 => 1],
            'curesChances' => [100 => 64, 25 => 1, 30 => 2, 35 => 3, 40 => 4, 45 => 5, 50 => 6, 55 => 5, 60 => 4, 65 => 3, 70 => 2, 75 => 1],
            'diseasesDelayMin' => [0 => 1, 1 => 1, 2 => 1, 3 => 1, 4 => 1, 5 => 1, 6 => 1, 7 => 1, 8 => 1, 9 => 1, 10 => 1, 11 => 1],
            'diseasesDelayLength' => [0 => 1, 1 => 1, 2 => 1, 3 => 1, 4 => 1, 5 => 1, 6 => 1, 7 => 1, 8 => 1],
            'effectNumber' => [0 => 35, 1 => 40, 2 => 15, 3 => 9, 4 => 1],
        ],
        [
            'name' => 'caleboot_default',
            'causeName' => 'caleboot',
            'diseasesName' => ['cat_allergy' => 1, 'mush_allergy' => 1, 'sepsis' => 1, 'slight_nausea' => 1, 'smallpox' => 1, 'syphilis' => 1, 'ailurophobia' => 1, 'coprolalia' => 1, 'spleen' => 1, 'weapon_phobia' => 1, 'chronic_vertigo' => 1, 'paranoia' => 1, 'acid_reflux' => 2, 'skin_inflammation' => 2, 'agoraphobia' => 2, 'chronic_migraine' => 2, 'vertigo' => 2, 'depression' => 2, 'psychotic_episodes' => 2, 'crabism' => 4, 'black_bite' => 4, 'cold' => 4, 'extreme_tinnitus' => 4, 'food_poisoning' => 4, 'fungic_infection' => 4, 'rejuvenation' => 4, 'rubella' => 4, 'sinus_storm' => 4, 'space_rabies' => 4, 'vitamin_deficiency' => 4, 'flu' => 8, 'gastroenteritis' => 8, 'migraine' => 8, 'tapeworm' => 8],
            'curesName' => ['cat_allergy' => 1, 'mush_allergy' => 1, 'sepsis' => 1, 'slight_nausea' => 1, 'smallpox' => 1, 'syphilis' => 1, 'ailurophobia' => 1, 'coprolalia' => 1, 'spleen' => 1, 'weapon_phobia' => 1, 'chronic_vertigo' => 1, 'paranoia' => 1, 'acid_reflux' => 2, 'skin_inflammation' => 2, 'agoraphobia' => 2, 'chronic_migraine' => 2, 'vertigo' => 2, 'depression' => 2, 'psychotic_episodes' => 2, 'crabism' => 4, 'black_bite' => 4, 'cold' => 4, 'extreme_tinnitus' => 4, 'food_poisoning' => 4, 'fungic_infection' => 4, 'rejuvenation' => 4, 'rubella' => 4, 'sinus_storm' => 4, 'space_rabies' => 4, 'vitamin_deficiency' => 4, 'flu' => 8, 'gastroenteritis' => 8, 'migraine' => 8, 'tapeworm' => 8],
            'diseasesChances' => [100 => 64, 25 => 1, 30 => 2, 35 => 3, 40 => 4, 45 => 5, 50 => 6, 55 => 5, 60 => 4, 65 => 3, 70 => 2, 75 => 1],
            'curesChances' => [100 => 64, 25 => 1, 30 => 2, 35 => 3, 40 => 4, 45 => 5, 50 => 6, 55 => 5, 60 => 4, 65 => 3, 70 => 2, 75 => 1],
            'diseasesDelayMin' => [0 => 1, 1 => 1, 2 => 1, 3 => 1, 4 => 1, 5 => 1, 6 => 1, 7 => 1, 8 => 1, 9 => 1, 10 => 1, 11 => 1],
            'diseasesDelayLength' => [0 => 1, 1 => 1, 2 => 1, 3 => 1, 4 => 1, 5 => 1, 6 => 1, 7 => 1, 8 => 1],
            'effectNumber' => [0 => 35, 1 => 40, 2 => 15, 3 => 9, 4 => 1],
        ],
        [
            'name' => 'filandra_default',
            'causeName' => 'filandra',
            'diseasesName' => ['cat_allergy' => 1, 'mush_allergy' => 1, 'sepsis' => 1, 'slight_nausea' => 1, 'smallpox' => 1, 'syphilis' => 1, 'ailurophobia' => 1, 'coprolalia' => 1, 'spleen' => 1, 'weapon_phobia' => 1, 'chronic_vertigo' => 1, 'paranoia' => 1, 'acid_reflux' => 2, 'skin_inflammation' => 2, 'agoraphobia' => 2, 'chronic_migraine' => 2, 'vertigo' => 2, 'depression' => 2, 'psychotic_episodes' => 2, 'crabism' => 4, 'black_bite' => 4, 'cold' => 4, 'extreme_tinnitus' => 4, 'food_poisoning' => 4, 'fungic_infection' => 4, 'rejuvenation' => 4, 'rubella' => 4, 'sinus_storm' => 4, 'space_rabies' => 4, 'vitamin_deficiency' => 4, 'flu' => 8, 'gastroenteritis' => 8, 'migraine' => 8, 'tapeworm' => 8],
            'curesName' => ['cat_allergy' => 1, 'mush_allergy' => 1, 'sepsis' => 1, 'slight_nausea' => 1, 'smallpox' => 1, 'syphilis' => 1, 'ailurophobia' => 1, 'coprolalia' => 1, 'spleen' => 1, 'weapon_phobia' => 1, 'chronic_vertigo' => 1, 'paranoia' => 1, 'acid_reflux' => 2, 'skin_inflammation' => 2, 'agoraphobia' => 2, 'chronic_migraine' => 2, 'vertigo' => 2, 'depression' => 2, 'psychotic_episodes' => 2, 'crabism' => 4, 'black_bite' => 4, 'cold' => 4, 'extreme_tinnitus' => 4, 'food_poisoning' => 4, 'fungic_infection' => 4, 'rejuvenation' => 4, 'rubella' => 4, 'sinus_storm' => 4, 'space_rabies' => 4, 'vitamin_deficiency' => 4, 'flu' => 8, 'gastroenteritis' => 8, 'migraine' => 8, 'tapeworm' => 8],
            'diseasesChances' => [100 => 64, 25 => 1, 30 => 2, 35 => 3, 40 => 4, 45 => 5, 50 => 6, 55 => 5, 60 => 4, 65 => 3, 70 => 2, 75 => 1],
            'curesChances' => [100 => 64, 25 => 1, 30 => 2, 35 => 3, 40 => 4, 45 => 5, 50 => 6, 55 => 5, 60 => 4, 65 => 3, 70 => 2, 75 => 1],
            'diseasesDelayMin' => [0 => 1, 1 => 1, 2 => 1, 3 => 1, 4 => 1, 5 => 1, 6 => 1, 7 => 1, 8 => 1, 9 => 1, 10 => 1, 11 => 1],
            'diseasesDelayLength' => [0 => 1, 1 => 1, 2 => 1, 3 => 1, 4 => 1, 5 => 1, 6 => 1, 7 => 1, 8 => 1],
            'effectNumber' => [0 => 35, 1 => 40, 2 => 15, 3 => 9, 4 => 1],
        ],
        [
            'name' => 'jumpkin_default',
            'causeName' => 'jumpkin',
            'diseasesName' => [],
            'curesName' => [],
            'diseasesChances' => [],
            'curesChances' => [],
            'diseasesDelayMin' => [],
            'diseasesDelayLength' => [],
            'effectNumber' => [],
        ],
        [
            'name' => 'alien_steak_default',
            'causeName' => 'alien_steak',
            'diseasesName' => [],
            'curesName' => [],
            'diseasesChances' => [],
            'curesChances' => [],
            'diseasesDelayMin' => [],
            'diseasesDelayLength' => [],
            'effectNumber' => [],
        ],
        [
            'name' => 'supervitamin_bar_default',
            'causeName' => 'supervitamin_bar',
            'diseasesName' => [],
            'curesName' => [],
            'diseasesChances' => [],
            'curesChances' => [],
            'diseasesDelayMin' => [],
            'diseasesDelayLength' => [],
            'effectNumber' => [],
        ],
        [
            'name' => 'eufurylate_default',
            'causeName' => 'eufurylate',
            'diseasesName' => [],
            'curesName' => ['vitamin_deficiency' => 1, 'syphilis' => 1, 'skin_inflammation' => 1, 'gastroenteritis' => 1, 'flu' => 1, 'sepsis' => 1, 'cold' => 1, 'rubella' => 1, 'sinus_storm' => 1, 'tapeworm' => 1, 'paranoia' => 1, 'depression' => 1, 'chronic_migraine' => 1],
            'diseasesChances' => [],
            'curesChances' => [100 => 1],
            'diseasesDelayMin' => [],
            'diseasesDelayLength' => [],
            'effectNumber' => [1 => 60, 2 => 30, 3 => 8, 4 => 1],
        ],
        [
            'name' => 'newke_default',
            'causeName' => 'newke',
            'diseasesName' => [],
            'curesName' => ['vitamin_deficiency' => 1, 'syphilis' => 1, 'skin_inflammation' => 1, 'gastroenteritis' => 1, 'flu' => 1, 'sepsis' => 1, 'cold' => 1, 'rubella' => 1, 'sinus_storm' => 1, 'tapeworm' => 1, 'paranoia' => 1, 'depression' => 1, 'chronic_migraine' => 1],
            'diseasesChances' => [],
            'curesChances' => [100 => 1],
            'diseasesDelayMin' => [],
            'diseasesDelayLength' => [],
            'effectNumber' => [1 => 60, 2 => 30, 3 => 8, 4 => 1],
        ],
        [
            'name' => 'phuxx_default',
            'causeName' => 'phuxx',
            'diseasesName' => [],
            'curesName' => ['vitamin_deficiency' => 1, 'syphilis' => 1, 'skin_inflammation' => 1, 'gastroenteritis' => 1, 'flu' => 1, 'sepsis' => 1, 'cold' => 1, 'rubella' => 1, 'sinus_storm' => 1, 'tapeworm' => 1, 'paranoia' => 1, 'depression' => 1, 'chronic_migraine' => 1],
            'diseasesChances' => [],
            'curesChances' => [100 => 1],
            'diseasesDelayMin' => [],
            'diseasesDelayLength' => [],
            'effectNumber' => [1 => 60, 2 => 30, 3 => 8, 4 => 1],
        ],
        [
            'name' => 'pinq_default',
            'causeName' => 'pinq',
            'diseasesName' => [],
            'curesName' => ['vitamin_deficiency' => 1, 'syphilis' => 1, 'skin_inflammation' => 1, 'gastroenteritis' => 1, 'flu' => 1, 'sepsis' => 1, 'cold' => 1, 'rubella' => 1, 'sinus_storm' => 1, 'tapeworm' => 1, 'paranoia' => 1, 'depression' => 1, 'chronic_migraine' => 1],
            'diseasesChances' => [],
            'curesChances' => [100 => 1],
            'diseasesDelayMin' => [],
            'diseasesDelayLength' => [],
            'effectNumber' => [1 => 60, 2 => 30, 3 => 8, 4 => 1],
        ],
        [
            'name' => 'pymp_default',
            'causeName' => 'pymp',
            'diseasesName' => [],
            'curesName' => ['vitamin_deficiency' => 1, 'syphilis' => 1, 'skin_inflammation' => 1, 'gastroenteritis' => 1, 'flu' => 1, 'sepsis' => 1, 'cold' => 1, 'rubella' => 1, 'sinus_storm' => 1, 'tapeworm' => 1, 'paranoia' => 1, 'depression' => 1, 'chronic_migraine' => 1],
            'diseasesChances' => [],
            'curesChances' => [100 => 1],
            'diseasesDelayMin' => [],
            'diseasesDelayLength' => [],
            'effectNumber' => [1 => 60, 2 => 30, 3 => 8, 4 => 1],
        ],
        [
            'name' => 'rosebud_default',
            'causeName' => 'rosebud',
            'diseasesName' => [],
            'curesName' => ['vitamin_deficiency' => 1, 'syphilis' => 1, 'skin_inflammation' => 1, 'gastroenteritis' => 1, 'flu' => 1, 'sepsis' => 1, 'cold' => 1, 'rubella' => 1, 'sinus_storm' => 1, 'tapeworm' => 1, 'paranoia' => 1, 'depression' => 1, 'chronic_migraine' => 1],
            'diseasesChances' => [],
            'curesChances' => [100 => 1],
            'diseasesDelayMin' => [],
            'diseasesDelayLength' => [],
            'effectNumber' => [1 => 60, 2 => 30, 3 => 8, 4 => 1],
        ],
        [
            'name' => 'soma_default',
            'causeName' => 'soma',
            'diseasesName' => [],
            'curesName' => ['vitamin_deficiency' => 1, 'syphilis' => 1, 'skin_inflammation' => 1, 'gastroenteritis' => 1, 'flu' => 1, 'sepsis' => 1, 'cold' => 1, 'rubella' => 1, 'sinus_storm' => 1, 'tapeworm' => 1, 'paranoia' => 1, 'depression' => 1, 'chronic_migraine' => 1],
            'diseasesChances' => [],
            'curesChances' => [100 => 1],
            'diseasesDelayMin' => [],
            'diseasesDelayLength' => [],
            'effectNumber' => [1 => 60, 2 => 30, 3 => 8, 4 => 1],
        ],
        [
            'name' => 'spyce_default',
            'causeName' => 'spyce',
            'diseasesName' => [],
            'curesName' => ['vitamin_deficiency' => 1, 'syphilis' => 1, 'skin_inflammation' => 1, 'gastroenteritis' => 1, 'flu' => 1, 'sepsis' => 1, 'cold' => 1, 'rubella' => 1, 'sinus_storm' => 1, 'tapeworm' => 1, 'paranoia' => 1, 'depression' => 1, 'chronic_migraine' => 1],
            'diseasesChances' => [],
            'curesChances' => [100 => 1],
            'diseasesDelayMin' => [],
            'diseasesDelayLength' => [],
            'effectNumber' => [1 => 60, 2 => 30, 3 => 8, 4 => 1],
        ],
        [
            'name' => 'twinoid_default',
            'causeName' => 'twinoid',
            'diseasesName' => [],
            'curesName' => ['vitamin_deficiency' => 1, 'syphilis' => 1, 'skin_inflammation' => 1, 'gastroenteritis' => 1, 'flu' => 1, 'sepsis' => 1, 'cold' => 1, 'rubella' => 1, 'sinus_storm' => 1, 'tapeworm' => 1, 'paranoia' => 1, 'depression' => 1, 'chronic_migraine' => 1],
            'diseasesChances' => [],
            'curesChances' => [100 => 1],
            'diseasesDelayMin' => [],
            'diseasesDelayLength' => [],
            'effectNumber' => [1 => 60, 2 => 30, 3 => 8, 4 => 1],
        ],
        [
            'name' => 'xenox_default',
            'causeName' => 'xenox',
            'diseasesName' => [],
            'curesName' => ['vitamin_deficiency' => 1, 'syphilis' => 1, 'skin_inflammation' => 1, 'gastroenteritis' => 1, 'flu' => 1, 'sepsis' => 1, 'cold' => 1, 'rubella' => 1, 'sinus_storm' => 1, 'tapeworm' => 1, 'paranoia' => 1, 'depression' => 1, 'chronic_migraine' => 1],
            'diseasesChances' => [],
            'curesChances' => [100 => 1],
            'diseasesDelayMin' => [],
            'diseasesDelayLength' => [],
            'effectNumber' => [1 => 60, 2 => 30, 3 => 8, 4 => 1],
        ],
    ];
}
