<?php

namespace Mush\Disease\ConfigData;

/** @codeCoverageIgnore */
class DiseaseConfigData
{
    public static array $dataArray = [
        [
            'diseaseName' => 'food_poisoning',
            'name' => 'food_poisoning_default',
            'type' => 'disease',
            'resistance' => 0,
            'delayMin' => 0,
            'delayLength' => 0,
            'diseasePointMin' => 4,
            'diseasePointLength' => 4,
            'override' => [],
            'modifierConfigs' => [
                'direct_modifier_player_-1_max_healthPoint',
            ],
            'symptomConfigs' => [
                'vomiting_ON_post.action_consume_drug_default',
                'vomiting_ON_post.action_move_default',
                'vomiting_ON_post.action_consume_default',
            ],
        ],
        [
            'diseaseName' => 'acid_reflux',
            'name' => 'acid_reflux_default',
            'type' => 'disease',
            'resistance' => 0,
            'delayMin' => 0,
            'delayLength' => 0,
            'diseasePointMin' => 4,
            'diseasePointLength' => 4,
            'override' => [],
            'modifierConfigs' => [
                'modifier_for_player_set_-2actionPoint_on_post.action_if_reason_consume',
            ],
            'symptomConfigs' => [
                'vomiting_ON_post.action_consume_drug_default',
                'vomiting_ON_post.action_move_default',
                'vomiting_ON_post.action_consume_default',
            ],
        ],
        [
            'diseaseName' => 'black_bite',
            'name' => 'black_bite_default',
            'type' => 'disease',
            'resistance' => 0,
            'delayMin' => 0,
            'delayLength' => 0,
            'diseasePointMin' => 4,
            'diseasePointLength' => 4,
            'override' => [],
            'modifierConfigs' => [
                'modifier_for_player_set_-4healthPoint_on_infection.player',
                'modifier_for_player_set_-1actionPoint_on_new_cycle_if_random_10',
            ],
            'symptomConfigs' => [],
        ],
        [
            'diseaseName' => 'cat_allergy',
            'name' => 'cat_allergy_default',
            'type' => 'disease',
            'resistance' => 0,
            'delayMin' => 0,
            'delayLength' => 0,
            'diseasePointMin' => 4,
            'diseasePointLength' => 4,
            'override' => [],
            'modifierConfigs' => [],
            'symptomConfigs' => [
                'sneezing_ON_post.action_cat_default',
                'cat_allergy_ON_post.action_default',
            ],
        ],
        [
            'diseaseName' => 'cold',
            'name' => 'cold_default',
            'type' => 'disease',
            'resistance' => 0,
            'delayMin' => 0,
            'delayLength' => 0,
            'diseasePointMin' => 4,
            'diseasePointLength' => 4,
            'override' => [],
            'modifierConfigs' => [
                'modifier_for_player_set_-1actionPoint_on_new_cycle_if_random_20',
            ],
            'symptomConfigs' => [],
        ],
        [
            'diseaseName' => 'extreme_tinnitus',
            'name' => 'extreme_tinnitus_default',
            'type' => 'disease',
            'resistance' => 0,
            'delayMin' => 0,
            'delayLength' => 0,
            'diseasePointMin' => 4,
            'diseasePointLength' => 4,
            'override' => [],
            'modifierConfigs' => [
                'direct_modifier_player_-2_max_moralPoint',
                'modifier_for_player_set_-1actionPoint_on_new_cycle_if_random_16',
            ],
            'symptomConfigs' => [],
        ],
        [
            'diseaseName' => 'flu',
            'name' => 'flu_default',
            'type' => 'disease',
            'resistance' => 0,
            'delayMin' => 0,
            'delayLength' => 0,
            'diseasePointMin' => 4,
            'diseasePointLength' => 4,
            'override' => [],
            'modifierConfigs' => [
                'modifier_for_player_set_-1actionPoint_on_new_cycle_if_random_20',
                'direct_modifier_player_-2_max_healthPoint',
                'direct_modifier_player_-2_max_moralPoint',
                'modifier_for_player_set_-1healthPoint_on_new_cycle_if_random_10',
            ],
            'symptomConfigs' => [
                'dirtiness_ON_new_cycle_random_40_default',
                'vomiting_ON_post.action_move_default',
                'vomiting_ON_post.action_consume_default',
                'vomiting_ON_post.action_consume_drug_default',
            ],
        ],
        [
            'diseaseName' => 'fungic_infection',
            'name' => 'fungic_infection_default',
            'type' => 'disease',
            'resistance' => 0,
            'delayMin' => 0,
            'delayLength' => 0,
            'diseasePointMin' => 4,
            'diseasePointLength' => 4,
            'override' => [],
            'modifierConfigs' => [
                'direct_modifier_player_-2_max_healthPoint',
                'direct_modifier_player_-2_max_moralPoint',
            ],
            'symptomConfigs' => [
                'dirtiness_ON_new_cycle_default',
            ],
        ],
        [
            'diseaseName' => 'gastroenteritis',
            'name' => 'gastroenteritis_default',
            'type' => 'disease',
            'resistance' => 0,
            'delayMin' => 0,
            'delayLength' => 0,
            'diseasePointMin' => 4,
            'diseasePointLength' => 4,
            'override' => [],
            'modifierConfigs' => [
                'modifier_for_player_set_-1movementPoint_on_new_cycle',
                'direct_modifier_player_-1_max_healthPoint',
                'modifier_for_player_set_-1healthPoint_on_new_cycle_if_random_16',
                'modifier_for_player_set_-1actionPoint_on_post.action_if_reason_consume',
            ],
            'symptomConfigs' => [
                'dirtiness_ON_new_cycle_default',
                'vomiting_ON_post.action_move_default',
                'vomiting_ON_post.action_consume_default',
                'vomiting_ON_post.action_consume_drug_default',
            ],
        ],
        [
            'diseaseName' => 'junkbumpkinitis',
            'name' => 'junkbumpkinitis_default',
            'type' => 'disease',
            'resistance' => 0,
            'delayMin' => 0,
            'delayLength' => 0,
            'diseasePointMin' => 4,
            'diseasePointLength' => 4,
            'override' => [],
            'modifierConfigs' => [],
            'symptomConfigs' => [],
        ],
        [
            'diseaseName' => 'migraine',
            'name' => 'migraine_default',
            'type' => 'disease',
            'resistance' => 0,
            'delayMin' => 0,
            'delayLength' => 0,
            'diseasePointMin' => 4,
            'diseasePointLength' => 4,
            'override' => [],
            'modifierConfigs' => [
                'modifier_for_player_set_-1actionPoint_on_new_cycle_if_random_20',
            ],
            'symptomConfigs' => [],
        ],
        [
            'diseaseName' => 'mush_allergy',
            'name' => 'mush_allergy_default',
            'type' => 'disease',
            'resistance' => 0,
            'delayMin' => 0,
            'delayLength' => 0,
            'diseasePointMin' => 4,
            'diseasePointLength' => 4,
            'override' => [],
            'modifierConfigs' => [
                'modifier_for_player_set_-4healthPoint_on_infection.player',
            ],
            'symptomConfigs' => [
                'sneezing_ON_post.action_mush_default',
            ],
        ],
        [
            'diseaseName' => 'quincks_oedema',
            'name' => 'quincks_oedema_default',
            'type' => 'disease',
            'resistance' => 0,
            'delayMin' => 0,
            'delayLength' => 0,
            'diseasePointMin' => 4,
            'diseasePointLength' => 4,
            'override' => [],
            'modifierConfigs' => [
                'modifier_for_player_+1movementPoint_on_move',
                'direct_modifier_player_-4_max_healthPoint',
            ],
            'symptomConfigs' => [],
        ],
        [
            'diseaseName' => 'rejuvenation',
            'name' => 'rejuvenation_default',
            'type' => 'disease',
            'resistance' => 0,
            'delayMin' => 0,
            'delayLength' => 0,
            'diseasePointMin' => 4,
            'diseasePointLength' => 4,
            'override' => [],
            'modifierConfigs' => [
                'modifier_for_player_set_-1actionPoint_on_new_cycle_if_random_20',
                'fitful_sleep_for_player_-1actionPoint_on_new_cycle_if_random_16_if_player_status_lying_down',
                'modifier_for_player_+10percentage_on_cycle_disease',
            ],
            'symptomConfigs' => [],
        ],
        [
            'diseaseName' => 'rubella',
            'name' => 'rubella_default',
            'type' => 'disease',
            'resistance' => 0,
            'delayMin' => 0,
            'delayLength' => 0,
            'diseasePointMin' => 4,
            'diseasePointLength' => 4,
            'override' => [],
            'modifierConfigs' => [
                'direct_modifier_player_-1_max_healthPoint',
                'direct_modifier_player_-1_max_moralPoint',
                'modifier_for_player_set_-1movementPoint_on_new_cycle_if_random_50',
            ],
            'symptomConfigs' => [],
        ],
        [
            'diseaseName' => 'sepsis',
            'name' => 'sepsis_default',
            'type' => 'disease',
            'resistance' => 0,
            'delayMin' => 0,
            'delayLength' => 0,
            'diseasePointMin' => 4,
            'diseasePointLength' => 4,
            'override' => [],
            'modifierConfigs' => [
                'modifier_for_player_set_-4healthPoint_on_new_cycle',
            ],
            'symptomConfigs' => [],
        ],
        [
            'diseaseName' => 'sinus_storm',
            'name' => 'sinus_storm_default',
            'type' => 'disease',
            'resistance' => 0,
            'delayMin' => 0,
            'delayLength' => 0,
            'diseasePointMin' => 4,
            'diseasePointLength' => 4,
            'override' => [],
            'modifierConfigs' => [
                'modifier_for_player_set_-1actionPoint_on_new_cycle_if_random_30',
            ],
            'symptomConfigs' => [],
        ],
        [
            'diseaseName' => 'skin_inflammation',
            'name' => 'skin_inflammation_default',
            'type' => 'disease',
            'resistance' => 0,
            'delayMin' => 0,
            'delayLength' => 0,
            'diseasePointMin' => 4,
            'diseasePointLength' => 4,
            'override' => [],
            'modifierConfigs' => [],
            'symptomConfigs' => [
                'breakouts_ON_post.action_default',
            ],
        ],
        [
            'diseaseName' => 'slight_nausea',
            'name' => 'slight_nausea_default',
            'type' => 'disease',
            'resistance' => 0,
            'delayMin' => 0,
            'delayLength' => 0,
            'diseasePointMin' => 4,
            'diseasePointLength' => 4,
            'override' => [],
            'modifierConfigs' => [
                'modifier_for_player_+1satiety_on_new_cycle',
            ],
            'symptomConfigs' => [
                'vomiting_ON_post.action_move_default',
            ],
        ],
        [
            'diseaseName' => 'smallpox',
            'name' => 'smallpox_default',
            'type' => 'disease',
            'resistance' => 0,
            'delayMin' => 0,
            'delayLength' => 0,
            'diseasePointMin' => 4,
            'diseasePointLength' => 4,
            'override' => [],
            'modifierConfigs' => [
                'modifier_for_player_set_-1healthPoint_on_new_cycle_if_random_50',
                'modifier_for_player_set_-2actionPoint_on_new_cycle_if_random_40',
                'direct_modifier_player_-2_max_healthPoint',
                'direct_modifier_player_-2_max_moralPoint',
            ],
            'symptomConfigs' => [],
        ],
        [
            'diseaseName' => 'space_rabies',
            'name' => 'space_rabies_default',
            'type' => 'disease',
            'resistance' => 0,
            'delayMin' => 0,
            'delayLength' => 0,
            'diseasePointMin' => 4,
            'diseasePointLength' => 4,
            'override' => [],
            'modifierConfigs' => [
                'modifier_for_player_set_-2healthPoint_on_new_cycle',
            ],
            'symptomConfigs' => [
                'foaming_mouth_ON_post.action_default',
                'drooling_ON_post.action_default',
                'biting_ON_new_cycle_default',
                'psychotic_attacks_ON_post.action_default',
            ],
        ],
        [
            'diseaseName' => 'syphilis',
            'name' => 'syphilis_default',
            'type' => 'disease',
            'resistance' => 0,
            'delayMin' => 0,
            'delayLength' => 0,
            'diseasePointMin' => 4,
            'diseasePointLength' => 4,
            'override' => [],
            'modifierConfigs' => [
                'modifier_for_player_set_-2actionPoint_on_new_cycle_if_random_40',
                'modifier_for_player_x0.9percentage_on_action_shoot',
                'direct_modifier_player_-2_max_moralPoint',
            ],
            'symptomConfigs' => [],
        ],
        [
            'diseaseName' => 'tapeworm',
            'name' => 'tapeworm_default',
            'type' => 'disease',
            'resistance' => 0,
            'delayMin' => 0,
            'delayLength' => 0,
            'diseasePointMin' => 4,
            'diseasePointLength' => 4,
            'override' => [],
            'modifierConfigs' => [
                'modifier_for_player_set_-1satiety_on_new_cycle',
            ],
            'symptomConfigs' => [],
        ],
        [
            'diseaseName' => 'vitamin_deficiency',
            'name' => 'vitamin_deficiency_default',
            'type' => 'disease',
            'resistance' => 0,
            'delayMin' => 0,
            'delayLength' => 0,
            'diseasePointMin' => 4,
            'diseasePointLength' => 4,
            'override' => [],
            'modifierConfigs' => [
                'modifier_for_player_set_-1actionPoint_on_new_cycle_if_random_10',
            ],
            'symptomConfigs' => [],
        ],
        [
            'diseaseName' => 'burns_50_of_body',
            'name' => 'burns_50_of_body_default',
            'type' => 'injury',
            'resistance' => 0,
            'delayMin' => 0,
            'delayLength' => 0,
            'diseasePointMin' => 4,
            'diseasePointLength' => 4,
            'override' => [],
            'modifierConfigs' => [
                'modifier_for_player_+10percentage_on_cycle_disease',
                'modifier_for_player_+1actionPoint_on_actions_if_not_reason_move_if_not_reason_consume_if_not_reason_consume_drug_if_not_reason_surgery_if_not_reason_self_surgery',
            ],
            'symptomConfigs' => [],
        ],
        [
            'diseaseName' => 'burns_90_of_body',
            'name' => 'burns_90_of_body_default',
            'type' => 'injury',
            'resistance' => 0,
            'delayMin' => 0,
            'delayLength' => 0,
            'diseasePointMin' => 4,
            'diseasePointLength' => 4,
            'override' => ['burns_50_of_body'],
            'modifierConfigs' => [
                'modifier_for_player_+10percentage_on_cycle_disease',
            ],
            'symptomConfigs' => [
                'septicemia_ON_status.applied_default',
                'septicemia_ON_post.action_default',
                'septicemia_ON_new_cycle_default',
            ],
        ],
        [
            'diseaseName' => 'burst_nose',
            'name' => 'burst_nose_default',
            'type' => 'injury',
            'resistance' => 0,
            'delayMin' => 0,
            'delayLength' => 0,
            'diseasePointMin' => 4,
            'diseasePointLength' => 4,
            'override' => [],
            'modifierConfigs' => [
                'direct_modifier_player_-2_max_moralPoint',
            ],
            'symptomConfigs' => [],
        ],
        [
            'diseaseName' => 'critical_haemorrhage',
            'name' => 'critical_haemorrhage_default',
            'type' => 'injury',
            'resistance' => 0,
            'delayMin' => 0,
            'delayLength' => 0,
            'diseasePointMin' => 4,
            'diseasePointLength' => 4,
            'override' => [],
            'modifierConfigs' => [
                'modifier_for_player_set_-2healthPoint_on_new_cycle',
                'direct_modifier_player_-2_max_healthPoint',
            ],
            'symptomConfigs' => [],
        ],
        [
            'diseaseName' => 'haemorrhage',
            'name' => 'haemorrhage_default',
            'type' => 'injury',
            'resistance' => 0,
            'delayMin' => 0,
            'delayLength' => 0,
            'diseasePointMin' => 4,
            'diseasePointLength' => 4,
            'override' => [],
            'modifierConfigs' => [
                'direct_modifier_player_-1_max_healthPoint',
                'modifier_for_player_set_-1healthPoint_on_new_cycle',
            ],
            'symptomConfigs' => [],
        ],
        [
            'diseaseName' => 'minor_haemorrhage',
            'name' => 'minor_haemorrhage_default',
            'type' => 'injury',
            'resistance' => 0,
            'delayMin' => 0,
            'delayLength' => 0,
            'diseasePointMin' => 4,
            'diseasePointLength' => 4,
            'override' => [],
            'modifierConfigs' => [
                'modifier_for_player_set_-1healthPoint_on_new_cycle',
            ],
            'symptomConfigs' => [],
        ],
        [
            'diseaseName' => 'damaged_ears',
            'name' => 'damaged_ears_default',
            'type' => 'injury',
            'resistance' => 0,
            'delayMin' => 0,
            'delayLength' => 0,
            'diseasePointMin' => 4,
            'diseasePointLength' => 4,
            'override' => [],
            'modifierConfigs' => [],
            'symptomConfigs' => [
                'deaf_ON_new_message_default',
            ],
        ],
        [
            'diseaseName' => 'destroyed_ears',
            'name' => 'destroyed_ears_default',
            'type' => 'injury',
            'resistance' => 0,
            'delayMin' => 0,
            'delayLength' => 0,
            'diseasePointMin' => 4,
            'diseasePointLength' => 4,
            'override' => ['damaged_ears'],
            'modifierConfigs' => [
                'direct_modifier_player_-1_max_moralPoint',
            ],
            'symptomConfigs' => [
                'deaf_ON_new_message_default',
            ],
        ],
        [
            'diseaseName' => 'head_trauma',
            'name' => 'head_trauma_default',
            'type' => 'injury',
            'resistance' => 0,
            'delayMin' => 0,
            'delayLength' => 0,
            'diseasePointMin' => 4,
            'diseasePointLength' => 4,
            'override' => [],
            'modifierConfigs' => [
                'direct_modifier_player_-3_max_moralPoint',
            ],
            'symptomConfigs' => [
                'septicemia_ON_status.applied_default',
                'septicemia_ON_post.action_default',
                'septicemia_ON_new_cycle_default',
            ],
        ],
        [
            'diseaseName' => 'open_air_brain',
            'name' => 'open_air_brain_default',
            'type' => 'injury',
            'resistance' => 0,
            'delayMin' => 0,
            'delayLength' => 0,
            'diseasePointMin' => 4,
            'diseasePointLength' => 4,
            'override' => ['head_trauma'],
            'modifierConfigs' => [
                'direct_modifier_player_-2_max_moralPoint',
            ],
            'symptomConfigs' => [
                'septicemia_ON_status.applied_default',
                'septicemia_ON_post.action_default',
                'septicemia_ON_new_cycle_default',
            ],
        ],
        [
            'diseaseName' => 'implanted_bullet',
            'name' => 'implanted_bullet_default',
            'type' => 'injury',
            'resistance' => 0,
            'delayMin' => 0,
            'delayLength' => 0,
            'diseasePointMin' => 4,
            'diseasePointLength' => 4,
            'override' => [],
            'modifierConfigs' => [
                'modifier_for_player_+1actionPoint_on_actions_if_not_reason_move_if_not_reason_consume_if_not_reason_consume_drug_if_not_reason_surgery_if_not_reason_self_surgery',
            ],
            'symptomConfigs' => [],
        ],
        [
            'diseaseName' => 'inner_ear_damaged',
            'name' => 'inner_ear_damaged_default',
            'type' => 'injury',
            'resistance' => 0,
            'delayMin' => 0,
            'delayLength' => 0,
            'diseasePointMin' => 4,
            'diseasePointLength' => 4,
            'override' => [],
            'modifierConfigs' => [
                'modifier_for_player_+1actionPoint_on_actions_if_not_reason_move_if_not_reason_consume_if_not_reason_consume_drug_if_not_reason_surgery_if_not_reason_self_surgery',
                'modifier_for_player_+1movementPoint_on_move',
            ],
            'symptomConfigs' => [
                'no_piloting_actions_ON_action_pilot_default',
            ],
        ],
        [
            'diseaseName' => 'torn_tongue',
            'name' => 'torn_tongue_default',
            'type' => 'injury',
            'resistance' => 0,
            'delayMin' => 0,
            'delayLength' => 0,
            'diseasePointMin' => 4,
            'diseasePointLength' => 4,
            'override' => [],
            'modifierConfigs' => [],
            'symptomConfigs' => [
                'mute_ON_action_spoken_default',
            ],
        ],
        [
            'diseaseName' => 'broken_foot',
            'name' => 'broken_foot_default',
            'type' => 'injury',
            'resistance' => 0,
            'delayMin' => 0,
            'delayLength' => 0,
            'diseasePointMin' => 4,
            'diseasePointLength' => 4,
            'override' => [],
            'modifierConfigs' => [
                'modifier_for_player_+1movementPoint_on_move',
            ],
            'symptomConfigs' => [],
        ],
        [
            'diseaseName' => 'mashed_foot',
            'name' => 'mashed_foot_default',
            'type' => 'injury',
            'resistance' => 0,
            'delayMin' => 0,
            'delayLength' => 0,
            'diseasePointMin' => 4,
            'diseasePointLength' => 4,
            'override' => ['broken_foot'],
            'modifierConfigs' => [
                'direct_modifier_player_-3_max_movementPoint',
                'modifier_for_player_+1movementPoint_on_move',
            ],
            'symptomConfigs' => [],
        ],
        [
            'diseaseName' => 'broken_leg',
            'name' => 'broken_leg_default',
            'type' => 'injury',
            'resistance' => 0,
            'delayMin' => 0,
            'delayLength' => 0,
            'diseasePointMin' => 4,
            'diseasePointLength' => 4,
            'override' => [],
            'modifierConfigs' => [
                'direct_modifier_player_-5_max_movementPoint',
                'modifier_for_player_+1movementPoint_on_move',
            ],
            'symptomConfigs' => [],
        ],
        [
            'diseaseName' => 'mashed_legs',
            'name' => 'mashed_legs_default',
            'type' => 'injury',
            'resistance' => 0,
            'delayMin' => 0,
            'delayLength' => 0,
            'diseasePointMin' => 4,
            'diseasePointLength' => 4,
            'override' => ['broken_leg', 'broken_foot', 'mashed_foot'],
            'modifierConfigs' => [
                'direct_modifier_player_-12_max_movementPoint',
            ],
            'symptomConfigs' => [
                'cant_move_ON_move_default',
            ],
        ],
        [
            'diseaseName' => 'dysfunctional_liver',
            'name' => 'dysfunctional_liver_default',
            'type' => 'injury',
            'resistance' => 0,
            'delayMin' => 0,
            'delayLength' => 0,
            'diseasePointMin' => 4,
            'diseasePointLength' => 4,
            'override' => [],
            'modifierConfigs' => [
                'modifier_for_player_set_-2actionPoint_on_post.action_if_reason_consume',
                'modifier_for_player_+1actionPoint_on_actions_if_not_reason_move_if_not_reason_consume_if_not_reason_consume_drug_if_not_reason_surgery_if_not_reason_self_surgery',
            ],
            'symptomConfigs' => [
                'vomiting_ON_post.action_move_default',
                'drooling_ON_post.action_default',
                'vomiting_ON_post.action_consume_default',
            ],
        ],
        [
            'diseaseName' => 'punctured_lung',
            'name' => 'punctured_lung_default',
            'type' => 'injury',
            'resistance' => 0,
            'delayMin' => 0,
            'delayLength' => 0,
            'diseasePointMin' => 4,
            'diseasePointLength' => 4,
            'override' => [],
            'modifierConfigs' => [
                'modifier_for_player_set_-2healthPoint_on_new_cycle',
                'modifier_for_player_+2actionPoint_on_actions_if_not_reason_move_if_not_reason_consume_if_not_reason_consume_drug_if_not_reason_surgery_if_not_reason_self_surgery',
            ],
            'symptomConfigs' => [
                'mute_ON_action_spoken_default',
            ],
        ],
        [
            'diseaseName' => 'broken_ribs',
            'name' => 'broken_ribs_default',
            'type' => 'injury',
            'resistance' => 0,
            'delayMin' => 0,
            'delayLength' => 0,
            'diseasePointMin' => 4,
            'diseasePointLength' => 4,
            'override' => [],
            'modifierConfigs' => [
                'modifier_for_player_x0.8percentage_on_action_shoot',
            ],
            'symptomConfigs' => [],
        ],
        [
            'diseaseName' => 'broken_finger',
            'name' => 'broken_finger_default',
            'type' => 'injury',
            'resistance' => 0,
            'delayMin' => 0,
            'delayLength' => 0,
            'diseasePointMin' => 4,
            'diseasePointLength' => 4,
            'override' => [],
            'modifierConfigs' => [
                'modifier_for_player_+1actionPoint_on_actions_if_not_reason_move_if_not_reason_consume_if_not_reason_consume_drug_if_not_reason_surgery_if_not_reason_self_surgery',
            ],
            'symptomConfigs' => [],
        ],
        [
            'diseaseName' => 'missing_finger',
            'name' => 'missing_finger_default',
            'type' => 'injury',
            'resistance' => 0,
            'delayMin' => 0,
            'delayLength' => 0,
            'diseasePointMin' => 4,
            'diseasePointLength' => 4,
            'override' => ['broken_finger'],
            'modifierConfigs' => [
                'modifier_for_player_+1actionPoint_on_actions_if_not_reason_move_if_not_reason_consume_if_not_reason_consume_drug_if_not_reason_surgery_if_not_reason_self_surgery',
            ],
            'symptomConfigs' => [],
        ],
        [
            'diseaseName' => 'burnt_hand',
            'name' => 'burnt_hand_default',
            'type' => 'injury',
            'resistance' => 0,
            'delayMin' => 0,
            'delayLength' => 0,
            'diseasePointMin' => 4,
            'diseasePointLength' => 4,
            'override' => [],
            'modifierConfigs' => [
                'direct_modifier_player_-1_max_healthPoint',
                'modifier_for_player_+1actionPoint_on_actions_if_not_reason_move_if_not_reason_consume_if_not_reason_consume_drug_if_not_reason_surgery_if_not_reason_self_surgery',
            ],
            'symptomConfigs' => [],
        ],
        [
            'diseaseName' => 'mashed_hand',
            'name' => 'mashed_hand_default',
            'type' => 'injury',
            'resistance' => 0,
            'delayMin' => 0,
            'delayLength' => 0,
            'diseasePointMin' => 4,
            'diseasePointLength' => 4,
            'override' => ['missing_finger', 'broken_finger', 'burnt_hand'],
            'modifierConfigs' => [
                'modifier_for_player_x0.6percentage_on_action_shoot',
                'modifier_for_player_+2actionPoint_on_actions_if_not_reason_move_if_not_reason_consume_if_not_reason_consume_drug_if_not_reason_surgery_if_not_reason_self_surgery',
            ],
            'symptomConfigs' => [],
        ],
        [
            'diseaseName' => 'burnt_arms',
            'name' => 'burnt_arms_default',
            'type' => 'injury',
            'resistance' => 0,
            'delayMin' => 0,
            'delayLength' => 0,
            'diseasePointMin' => 4,
            'diseasePointLength' => 4,
            'override' => [],
            'modifierConfigs' => [
                'modifier_for_player_+10percentage_on_cycle_disease',
                'modifier_for_player_+2actionPoint_on_actions_if_not_reason_move_if_not_reason_consume_if_not_reason_consume_drug_if_not_reason_surgery_if_not_reason_self_surgery',
                'modifier_for_player_x0.8percentage_on_action_shoot',
            ],
            'symptomConfigs' => [],
        ],
        [
            'diseaseName' => 'busted_arm_joint',
            'name' => 'busted_arm_joint_default',
            'type' => 'injury',
            'resistance' => 0,
            'delayMin' => 0,
            'delayLength' => 0,
            'diseasePointMin' => 4,
            'diseasePointLength' => 4,
            'override' => ['mashed_arms'],
            'modifierConfigs' => [
                'modifier_for_player_x0.6percentage_on_action_shoot',
                'modifier_for_player_+2actionPoint_on_actions_if_not_reason_move_if_not_reason_consume_if_not_reason_consume_drug_if_not_reason_surgery_if_not_reason_self_surgery',
            ],
            'symptomConfigs' => [],
        ],
        [
            'diseaseName' => 'mashed_arms',
            'name' => 'mashed_arms_default',
            'type' => 'injury',
            'resistance' => 0,
            'delayMin' => 0,
            'delayLength' => 0,
            'diseasePointMin' => 4,
            'diseasePointLength' => 4,
            'override' => ['burnt_hand', 'broken_finger', 'missing_finger', 'mashed_hand', 'busted_arm_joint'],
            'modifierConfigs' => [
                'modifier_for_player_+3actionPoint_on_actions_if_not_reason_move_if_not_reason_consume_if_not_reason_consume_drug_if_not_reason_surgery_if_not_reason_self_surgery',
                'modifier_for_player_x0.6percentage_on_action_shoot',
            ],
            'symptomConfigs' => [],
        ],
        [
            'diseaseName' => 'bruised_shoulder',
            'name' => 'bruised_shoulder_default',
            'type' => 'injury',
            'resistance' => 0,
            'delayMin' => 0,
            'delayLength' => 0,
            'diseasePointMin' => 4,
            'diseasePointLength' => 4,
            'override' => [],
            'modifierConfigs' => [
                'direct_modifier_player_-1_max_healthPoint',
                'modifier_for_player_x0.9percentage_on_action_shoot',
            ],
            'symptomConfigs' => [],
        ],
        [
            'diseaseName' => 'broken_shoulder',
            'name' => 'broken_shoulder_default',
            'type' => 'injury',
            'resistance' => 0,
            'delayMin' => 0,
            'delayLength' => 0,
            'diseasePointMin' => 4,
            'diseasePointLength' => 4,
            'override' => ['bruised_shoulder'],
            'modifierConfigs' => [
                'direct_modifier_player_-1_max_healthPoint',
                'modifier_for_player_x0.8percentage_on_action_shoot',
            ],
            'symptomConfigs' => [
                'cant_pick_up_heavy_items_ON_take_default',
            ],
        ],
        [
            'diseaseName' => 'busted_shoulder',
            'name' => 'busted_shoulder_default',
            'type' => 'injury',
            'resistance' => 0,
            'delayMin' => 0,
            'delayLength' => 0,
            'diseasePointMin' => 4,
            'diseasePointLength' => 4,
            'override' => ['burnt_hand', 'broken_finger', 'missing_finger', 'mashed_hand', 'busted_arm_joint', 'mashed_arms', 'bruised_shoulder', 'broken_shoulder'],
            'modifierConfigs' => [
                'modifier_for_player_x0.6percentage_on_action_shoot',
                'modifier_for_player_+2actionPoint_on_actions_if_not_reason_move_if_not_reason_consume_if_not_reason_consume_drug_if_not_reason_surgery_if_not_reason_self_surgery',
            ],
            'symptomConfigs' => [
                'cant_pick_up_heavy_items_ON_take_default',
            ],
        ],
        [
            'diseaseName' => 'agoraphobia',
            'name' => 'agoraphobia_default',
            'type' => 'disorder',
            'resistance' => 0,
            'delayMin' => 0,
            'delayLength' => 0,
            'diseasePointMin' => 4,
            'diseasePointLength' => 4,
            'override' => [],
            'modifierConfigs' => [
                'modifier_for_player_+1actionPoint_on_actions_if_player_in_room_four_people',
                'modifier_for_player_+1movementPoint_on_actions_if_player_in_room_four_people',
            ],
            'symptomConfigs' => [
                'no_piloting_actions_ON_action_pilot_default',
            ],
        ],
        [
            'diseaseName' => 'ailurophobia',
            'name' => 'ailurophobia_default',
            'type' => 'disorder',
            'resistance' => 0,
            'delayMin' => 0,
            'delayLength' => 0,
            'diseasePointMin' => 4,
            'diseasePointLength' => 4,
            'override' => [],
            'modifierConfigs' => [
                'modifier_for_player_+2movementPoint_on_move_if_item_in_room_schrodinger',
                'modifier_for_player_+2actionPoint_on_actions_if_item_in_room_schrodinger_if_not_reason_move',
            ],
            'symptomConfigs' => [
                'fear_of_cats_ON_post.action_default',
            ],
        ],
        [
            'diseaseName' => 'chronic_migraine',
            'name' => 'chronic_migraine_default',
            'type' => 'disorder',
            'resistance' => 0,
            'delayMin' => 0,
            'delayLength' => 0,
            'diseasePointMin' => 4,
            'diseasePointLength' => 4,
            'override' => ['migraine'],
            'modifierConfigs' => [
                'direct_modifier_player_-2_max_moralPoint',
                'modifier_for_player_set_-1actionPoint_on_new_cycle_if_random_16',
            ],
            'symptomConfigs' => [],
        ],
        [
            'diseaseName' => 'chronic_vertigo',
            'name' => 'chronic_vertigo_default',
            'type' => 'disorder',
            'resistance' => 0,
            'delayMin' => 0,
            'delayLength' => 0,
            'diseasePointMin' => 4,
            'diseasePointLength' => 4,
            'override' => [],
            'modifierConfigs' => [],
            'symptomConfigs' => [
                'no_piloting_actions_ON_action_pilot_default',
            ],
        ],
        [
            'diseaseName' => 'coprolalia',
            'name' => 'coprolalia_default',
            'type' => 'disorder',
            'resistance' => 0,
            'delayMin' => 0,
            'delayLength' => 0,
            'diseasePointMin' => 4,
            'diseasePointLength' => 4,
            'override' => [],
            'modifierConfigs' => [
                'direct_modifier_player_-4_max_moralPoint',
            ],
            'symptomConfigs' => [
                'coprolalia_messages_ON_new_message_default',
            ],
        ],
        [
            'diseaseName' => 'crabism',
            'name' => 'crabism_default',
            'type' => 'disorder',
            'resistance' => 0,
            'delayMin' => 0,
            'delayLength' => 0,
            'diseasePointMin' => 4,
            'diseasePointLength' => 4,
            'override' => [],
            'modifierConfigs' => [
                'run_in_circles_for_player_set_-2movementPoint_on_new_cycle_if_random_16',
                'wall_head_bang_for_player_set_-1healthPoint_on_new_cycle_if_random_16',
                'screaming_for_player_set_-1actionPoint_on_new_cycle_if_random_16',
                'direct_modifier_player_-4_max_moralPoint',
            ],
            'symptomConfigs' => [],
        ],
        [
            'diseaseName' => 'depression',
            'name' => 'depression_default',
            'type' => 'disorder',
            'resistance' => 0,
            'delayMin' => 0,
            'delayLength' => 0,
            'diseasePointMin' => 4,
            'diseasePointLength' => 4,
            'override' => [],
            'modifierConfigs' => [
                'direct_modifier_player_-2_max_actionPoint',
                'direct_modifier_player_-2_max_moralPoint',
            ],
            'symptomConfigs' => [],
        ],
        [
            'diseaseName' => 'paranoia',
            'name' => 'paranoia_default',
            'type' => 'disorder',
            'resistance' => 0,
            'delayMin' => 0,
            'delayLength' => 0,
            'diseasePointMin' => 4,
            'diseasePointLength' => 4,
            'override' => [],
            'modifierConfigs' => [
                'direct_modifier_player_-3_max_moralPoint',
            ],
            'symptomConfigs' => [
                'paranoia_messages_ON_new_message_default',
            ],
        ],
        [
            'diseaseName' => 'psychotic_episodes',
            'name' => 'psychotic_episodes_default',
            'type' => 'disorder',
            'resistance' => 0,
            'delayMin' => 0,
            'delayLength' => 0,
            'diseasePointMin' => 4,
            'diseasePointLength' => 4,
            'override' => [],
            'modifierConfigs' => [],
            'symptomConfigs' => [
                'psychotic_attacks_ON_post.action_default',
                'biting_ON_new_cycle_default',
            ],
        ],
        [
            'diseaseName' => 'spleen',
            'name' => 'spleen_default',
            'type' => 'disorder',
            'resistance' => 0,
            'delayMin' => 0,
            'delayLength' => 0,
            'diseasePointMin' => 4,
            'diseasePointLength' => 4,
            'override' => [],
            'modifierConfigs' => [
                'modifier_for_player_set_-1moralPoint_on_new_cycle_if_random_70',
            ],
            'symptomConfigs' => [],
        ],
        [
            'diseaseName' => 'vertigo',
            'name' => 'vertigo_default',
            'type' => 'disorder',
            'resistance' => 0,
            'delayMin' => 0,
            'delayLength' => 0,
            'diseasePointMin' => 4,
            'diseasePointLength' => 4,
            'override' => [],
            'modifierConfigs' => [],
            'symptomConfigs' => [
                'no_piloting_actions_ON_action_pilot_default',
            ],
        ],
        [
            'diseaseName' => 'weapon_phobia',
            'name' => 'weapon_phobia_default',
            'type' => 'disorder',
            'resistance' => 0,
            'delayMin' => 0,
            'delayLength' => 0,
            'diseasePointMin' => 4,
            'diseasePointLength' => 4,
            'override' => [],
            'modifierConfigs' => [],
            'symptomConfigs' => [
                'no_attack_actions_ON_action_attack_default',
                'no_shoot_actions_ON_action_shoot_default',
            ],
        ],
    ];
}
