<?php

declare(strict_types=1);

namespace Mush\Project\ConfigData;

use Mush\Project\Enum\ProjectName;
use Mush\Project\Enum\ProjectType;
use Mush\Skill\Enum\SkillName;

/**
 * @codeCoverageIgnore
 */
abstract class ProjectConfigData
{
    public static function getAll(): array
    {
        return [
            [
                'name' => ProjectName::PILGRED,
                'type' => ProjectType::PILGRED,
                'efficiency' => 1,
                'bonusSkills' => [SkillName::PHYSICIST, SkillName::TECHNICIAN],
                'activationRate' => 100,
                'modifierConfigs' => [],
                'spawnEquipmentConfigs' => [],
                'replaceEquipmentConfigs' => [],
            ],
            [
                'name' => ProjectName::FIRE_SENSOR,
                'type' => ProjectType::NERON_PROJECT,
                'efficiency' => 18,
                'bonusSkills' => [SkillName::RADIO_EXPERT, SkillName::FIREFIGHTER],
                'activationRate' => 100,
                'modifierConfigs' => [],
                'spawnEquipmentConfigs' => [],
                'replaceEquipmentConfigs' => [],
            ],
            [
                'name' => ProjectName::DOOR_SENSOR,
                'type' => ProjectType::NERON_PROJECT,
                'efficiency' => 18,
                'bonusSkills' => [SkillName::RADIO_EXPERT, SkillName::ROBOTICS_EXPERT],
                'activationRate' => 100,
                'modifierConfigs' => [],
                'spawnEquipmentConfigs' => [],
                'replaceEquipmentConfigs' => [],
            ],
            [
                'name' => ProjectName::EQUIPMENT_SENSOR,
                'type' => ProjectType::NERON_PROJECT,
                'efficiency' => 18,
                'bonusSkills' => [SkillName::RADIO_EXPERT, SkillName::TECHNICIAN],
                'activationRate' => 100,
                'modifierConfigs' => [],
                'spawnEquipmentConfigs' => [],
                'replaceEquipmentConfigs' => [],
            ],
            [
                'name' => ProjectName::PLASMA_SHIELD,
                'type' => ProjectType::NERON_PROJECT,
                'efficiency' => 1,
                'bonusSkills' => [SkillName::TECHNICIAN, SkillName::PHYSICIST],
                'activationRate' => 100,
                'modifierConfigs' => [
                    'modifier_for_daedalus_+5shield_on_new_cycle',
                ],
                'spawnEquipmentConfigs' => [],
                'replaceEquipmentConfigs' => [],
            ],
            [
                'name' => ProjectName::HEAT_LAMP,
                'type' => ProjectType::NERON_PROJECT,
                'efficiency' => 3,
                'bonusSkills' => [SkillName::TECHNICIAN, SkillName::BOTANIST],
                'activationRate' => 50,
                'modifierConfigs' => [],
                'spawnEquipmentConfigs' => [],
                'replaceEquipmentConfigs' => [],
            ],
            [
                'name' => ProjectName::TRAIL_REDUCER,
                'type' => ProjectType::NERON_PROJECT,
                'efficiency' => 6,
                'bonusSkills' => [SkillName::PILOT, SkillName::TECHNICIAN],
                'activationRate' => 100,
                'modifierConfigs' => [
                    'modifier_for_daedalus_-25percentage_following_hunters_on_daedalus_travel',
                ],
                'spawnEquipmentConfigs' => [],
                'replaceEquipmentConfigs' => [],
            ],
            [
                'name' => ProjectName::CHIPSET_ACCELERATION,
                'type' => ProjectType::NERON_PROJECT,
                'efficiency' => 6,
                'bonusSkills' => [SkillName::ASTROPHYSICIST, SkillName::IT_EXPERT],
                'activationRate' => 100,
                'modifierConfigs' => [
                    'modifier_for_daedalus_-1actionPoint_on_action_scan_planet',
                ],
                'spawnEquipmentConfigs' => [],
                'replaceEquipmentConfigs' => [],
            ],
            [
                'name' => ProjectName::DISMANTLING,
                'type' => ProjectType::NERON_PROJECT,
                'efficiency' => 12,
                'bonusSkills' => [SkillName::TECHNICIAN, SkillName::ROBOTICS_EXPERT],
                'activationRate' => 100,
                'modifierConfigs' => [],
                'replaceEquipmentConfigs' => [],
                'spawnEquipmentConfigs' => [
                    '5_metal_scraps_in_engine_room',
                ],
            ],
            [
                'name' => ProjectName::EXTRA_HYDROPONPOTS,
                'type' => ProjectType::NERON_PROJECT,
                'efficiency' => 6,
                'bonusSkills' => [SkillName::TECHNICIAN, SkillName::BOTANIST],
                'activationRate' => 100,
                'modifierConfigs' => [],
                'spawnEquipmentConfigs' => [
                    '3_hydropots_in_hydroponic_garden',
                ],
                'replaceEquipmentConfigs' => [],
            ],
            [
                'name' => ProjectName::AUXILIARY_TERMINAL,
                'type' => ProjectType::NERON_PROJECT,
                'efficiency' => 6,
                'bonusSkills' => [SkillName::RADIO_EXPERT, SkillName::IT_EXPERT],
                'activationRate' => 100,
                'modifierConfigs' => [],
                'spawnEquipmentConfigs' => [
                    '1_auxiliary_terminal_in_medlab',
                    '1_auxiliary_terminal_in_engine_room',
                ],
                'replaceEquipmentConfigs' => [],
            ],
            [
                'name' => ProjectName::THALASSO,
                'type' => ProjectType::NERON_PROJECT,
                'efficiency' => 18,
                'bonusSkills' => [SkillName::TECHNICIAN, SkillName::NURSE],
                'activationRate' => 100,
                'modifierConfigs' => [],
                'spawnEquipmentConfigs' => [],
                'replaceEquipmentConfigs' => [
                    'replace_all_showers_by_thalasso',
                ],
            ],
            [
                'name' => ProjectName::BRIC_BROC,
                'type' => ProjectType::NERON_PROJECT,
                'efficiency' => 6,
                'bonusSkills' => [SkillName::CONCEPTOR, SkillName::CREATIVE],
                'activationRate' => 15,
                'modifierConfigs' => [],
                'spawnEquipmentConfigs' => [],
                'replaceEquipmentConfigs' => [],
            ],
            [
                'name' => ProjectName::AUTO_WATERING,
                'type' => ProjectType::NERON_PROJECT,
                'efficiency' => 3,
                'bonusSkills' => [SkillName::TECHNICIAN, SkillName::FIREFIGHTER],
                'activationRate' => 25,
                'modifierConfigs' => [],
                'spawnEquipmentConfigs' => [],
                'replaceEquipmentConfigs' => [],
            ],
            [
                'name' => ProjectName::MAGNETIC_NET,
                'type' => ProjectType::NERON_PROJECT,
                'efficiency' => 6,
                'bonusSkills' => [SkillName::PILOT, SkillName::PHYSICIST],
                'activationRate' => 100,
                'modifierConfigs' => [],
                'spawnEquipmentConfigs' => [],
                'replaceEquipmentConfigs' => [],
            ],
            [
                'name' => ProjectName::ICARUS_ANTIGRAV_PROPELLER,
                'type' => ProjectType::NERON_PROJECT,
                'efficiency' => 12,
                'bonusSkills' => [SkillName::PILOT, SkillName::PHYSICIST],
                'activationRate' => 100,
                'modifierConfigs' => [],
                'spawnEquipmentConfigs' => [],
                'replaceEquipmentConfigs' => [],
            ],
            [
                'name' => ProjectName::FISSION_COFFEE_ROASTER,
                'type' => ProjectType::NERON_PROJECT,
                'efficiency' => 6,
                'bonusSkills' => [SkillName::CAFFEINE_JUNKIE, SkillName::PHYSICIST],
                'activationRate' => 100,
                'modifierConfigs' => [],
                'spawnEquipmentConfigs' => [],
                'replaceEquipmentConfigs' => [],
            ],
            [
                'name' => ProjectName::ARMOUR_CORRIDOR,
                'type' => ProjectType::NERON_PROJECT,
                'efficiency' => 3,
                'bonusSkills' => [SkillName::TECHNICIAN, SkillName::PHYSICIST],
                'activationRate' => 100,
                'modifierConfigs' => [
                    'modifier_for_daedalus_+1hull_on_change.variable_if_reason_hunter_shot',
                ],
                'spawnEquipmentConfigs' => [],
                'replaceEquipmentConfigs' => [],
            ],
            [
                'name' => ProjectName::CALL_OF_DIRTY,
                'type' => ProjectType::NERON_PROJECT,
                'efficiency' => 18,
                'bonusSkills' => [SkillName::TECHNICIAN, SkillName::SHOOTER],
                'activationRate' => 100,
                'modifierConfigs' => [],
                'spawnEquipmentConfigs' => [
                    '1_dynarcade_in_alpha_bay_2',
                ],
                'replaceEquipmentConfigs' => [],
            ],
            [
                'name' => ProjectName::EXTRA_DRONE,
                'type' => ProjectType::NERON_PROJECT,
                'efficiency' => 6,
                'bonusSkills' => [SkillName::TECHNICIAN, SkillName::ROBOTICS_EXPERT],
                'activationRate' => 100,
                'modifierConfigs' => [],
                'spawnEquipmentConfigs' => [
                    '1_support_drone_in_nexus',
                ],
                'replaceEquipmentConfigs' => [],
            ],
            [
                'name' => ProjectName::PATROLSHIP_BLASTER_GUN,
                'type' => ProjectType::NERON_PROJECT,
                'efficiency' => 6,
                'bonusSkills' => [SkillName::PILOT, SkillName::SHOOTER],
                'activationRate' => 100,
                'modifierConfigs' => [
                    'modifier_for_daedalus_-1hunter_health_on_change.variable',
                ],
                'spawnEquipmentConfigs' => [],
                'replaceEquipmentConfigs' => [],
            ],
            [
                'name' => ProjectName::BAY_DOOR_XXL,
                'type' => ProjectType::NERON_PROJECT,
                'efficiency' => 6,
                'bonusSkills' => [SkillName::PILOT, SkillName::TECHNICIAN],
                'activationRate' => 100,
                'modifierConfigs' => [
                    'modifier_for_player_x1.5percentage_for_takeoff_and_land_actions',
                ],
                'spawnEquipmentConfigs' => [],
                'replaceEquipmentConfigs' => [],
            ],
            [
                'name' => ProjectName::TRASH_LOAD,
                'type' => ProjectType::NERON_PROJECT,
                'efficiency' => 18,
                'bonusSkills' => [SkillName::TECHNICIAN, SkillName::ROBOTICS_EXPERT],
                'activationRate' => 100,
                'modifierConfigs' => [],
                'spawnEquipmentConfigs' => [
                    '4_metal_scraps_in_engine_room',
                    '4_plastic_scraps_in_engine_room',
                ],
                'replaceEquipmentConfigs' => [],
            ],
            [
                'name' => ProjectName::FOOD_RETAILER,
                'type' => ProjectType::NERON_PROJECT,
                'efficiency' => 6,
                'bonusSkills' => [SkillName::ROBOTICS_EXPERT, SkillName::CHEF],
                'activationRate' => 100,
                'modifierConfigs' => [],
                'spawnEquipmentConfigs' => [],
                'replaceEquipmentConfigs' => [],
            ],
            [
                'name' => ProjectName::AUTO_RETURN_ICARUS,
                'type' => ProjectType::NERON_PROJECT,
                'efficiency' => 12,
                'bonusSkills' => [SkillName::IT_EXPERT, SkillName::ROBOTICS_EXPERT],
                'activationRate' => 100,
                'modifierConfigs' => [],
                'spawnEquipmentConfigs' => [],
                'replaceEquipmentConfigs' => [],
            ],
            [
                'name' => ProjectName::RADAR_TRANS_VOID,
                'type' => ProjectType::NERON_PROJECT,
                'efficiency' => 12,
                'bonusSkills' => [SkillName::TECHNICIAN, SkillName::RADIO_EXPERT],
                'activationRate' => 100,
                'modifierConfigs' => [],
                'spawnEquipmentConfigs' => [],
                'replaceEquipmentConfigs' => [
                    'replace_antenna_by_radar_trans_void_antenna',
                ],
            ],
            [
                'name' => ProjectName::NERON_TARGETING_ASSIST,
                'type' => ProjectType::NERON_PROJECT,
                'efficiency' => 3,
                'bonusSkills' => [SkillName::PILOT, SkillName::SHOOTER],
                'activationRate' => 100,
                'modifierConfigs' => [
                    'modifier_for_daedalus_x1.25_percentage_on_shoot_hunter',
                ],
                'spawnEquipmentConfigs' => [],
                'replaceEquipmentConfigs' => [],
            ],
            [
                'name' => ProjectName::WHOS_WHO,
                'type' => ProjectType::NERON_PROJECT,
                'efficiency' => 18,
                'bonusSkills' => [SkillName::RADIO_EXPERT, SkillName::PARANOID],
                'activationRate' => 100,
                'modifierConfigs' => [],
                'spawnEquipmentConfigs' => [],
                'replaceEquipmentConfigs' => [],
            ],
            [
                'name' => ProjectName::HYDROPONIC_INCUBATOR,
                'type' => ProjectType::NERON_PROJECT,
                'efficiency' => 6,
                'bonusSkills' => [SkillName::PHYSICIST, SkillName::BOTANIST],
                'activationRate' => 100,
                'modifierConfigs' => [],
                'spawnEquipmentConfigs' => [
                    '1_hydroponic_incubator_in_hydroponic_garden',
                ],
                'replaceEquipmentConfigs' => [],
            ],
            [
                'name' => ProjectName::ICARUS_LAVATORY,
                'type' => ProjectType::NERON_PROJECT,
                'efficiency' => 18,
                'bonusSkills' => [SkillName::BIOLOGIST, SkillName::TECHNICIAN],
                'activationRate' => 100,
                'modifierConfigs' => [
                    'modifier_for_player_prevent_dirty_for_exploration_finished',
                ],
                'spawnEquipmentConfigs' => [],
                'replaceEquipmentConfigs' => [],
            ],
            [
                'name' => ProjectName::ICARUS_LARGER_BAY,
                'type' => ProjectType::NERON_PROJECT,
                'efficiency' => 6,
                'bonusSkills' => [SkillName::PILOT, SkillName::TECHNICIAN],
                'activationRate' => 100,
                'modifierConfigs' => [
                    'modifier_for_daedalus_+2players_allowed_on_takeoff_to_planet',
                ],
                'spawnEquipmentConfigs' => [],
                'replaceEquipmentConfigs' => [],
            ],
            [
                'name' => ProjectName::PATROL_SHIP_LAUNCHER,
                'type' => ProjectType::NERON_PROJECT,
                'efficiency' => 6,
                'bonusSkills' => [SkillName::PILOT, SkillName::PHYSICIST],
                'activationRate' => 100,
                'modifierConfigs' => [
                    'modifier_for_daedalus_-1action_point_on_action_take_off',
                ],
                'spawnEquipmentConfigs' => [],
                'replaceEquipmentConfigs' => [],
            ],
            [
                'name' => ProjectName::NERON_PROJECT_THREAD,
                'type' => ProjectType::NERON_PROJECT,
                'efficiency' => 6,
                'bonusSkills' => [SkillName::IT_EXPERT, SkillName::SHRINK],
                'activationRate' => 5,
                'modifierConfigs' => [],
                'spawnEquipmentConfigs' => [],
                'replaceEquipmentConfigs' => [],
            ],
            [
                'name' => ProjectName::TURRET_EXTRA_FIRE_RATE,
                'type' => ProjectType::NERON_PROJECT,
                'efficiency' => 12,
                'bonusSkills' => [SkillName::PHYSICIST, SkillName::TECHNICIAN],
                'activationRate' => 100,
                'modifierConfigs' => [
                    'modifier_for_daedalus_x2_turret_charges_on_new_cycle',
                ],
                'spawnEquipmentConfigs' => [],
                'replaceEquipmentConfigs' => [],
            ],
            [
                'name' => ProjectName::QUANTUM_SENSORS,
                'type' => ProjectType::NERON_PROJECT,
                'efficiency' => 6,
                'bonusSkills' => [SkillName::ASTROPHYSICIST, SkillName::RADIO_EXPERT],
                'activationRate' => 100,
                'modifierConfigs' => [],
                'spawnEquipmentConfigs' => [],
                'replaceEquipmentConfigs' => [
                    'replace_planet_scanner_by_quantum_sensors_planet_scanner',
                ],
            ],
            [
                'name' => ProjectName::PATROLSHIP_EXTRA_AMMO,
                'type' => ProjectType::NERON_PROJECT,
                'efficiency' => 6,
                'bonusSkills' => [SkillName::PHYSICIST, SkillName::TECHNICIAN],
                'activationRate' => 100,
                'modifierConfigs' => [
                    'modifier_for_daedalus_+6_patrol_ship_alpha_tamarin_max_charges',
                    'modifier_for_daedalus_+6_patrol_ship_alpha_longane_max_charges',
                    'modifier_for_daedalus_+6_patrol_ship_alpha_jujube_max_charges',
                    'modifier_for_daedalus_+6_patrol_ship_bravo_planton_max_charges',
                    'modifier_for_daedalus_+6_patrol_ship_bravo_epicure_max_charges',
                    'modifier_for_daedalus_+6_patrol_ship_bravo_socrate_max_charges',
                    'modifier_for_daedalus_+6_patrol_ship_alpha_2_wallis_max_charges',
                    'modifier_for_daedalus_patrol_ship_alpha_tamarin_set_charges_to_maximum',
                    'modifier_for_daedalus_patrol_ship_alpha_longane_set_charges_to_maximum',
                    'modifier_for_daedalus_patrol_ship_alpha_jujube_set_charges_to_maximum',
                    'modifier_for_daedalus_patrol_ship_bravo_planton_set_charges_to_maximum',
                    'modifier_for_daedalus_patrol_ship_bravo_epicure_set_charges_to_maximum',
                    'modifier_for_daedalus_patrol_ship_bravo_socrate_set_charges_to_maximum',
                    'modifier_for_daedalus_patrol_ship_alpha_2_wallis_set_charges_to_maximum',
                ],
                'spawnEquipmentConfigs' => [],
                'replaceEquipmentConfigs' => [],
            ],
            [
                'name' => ProjectName::NOISE_REDUCER,
                'type' => ProjectType::NERON_PROJECT,
                'efficiency' => 3,
                'bonusSkills' => [SkillName::PHYSICIST, SkillName::BIOLOGIST],
                'activationRate' => 100,
                'modifierConfigs' => [
                    'direct_modifier_player_+2_max_actionPoint',
                ],
                'spawnEquipmentConfigs' => [],
                'replaceEquipmentConfigs' => [],
            ],
            [
                'name' => ProjectName::APERO_KITCHEN,
                'type' => ProjectType::NERON_PROJECT,
                'efficiency' => 18,
                'bonusSkills' => [SkillName::CHEF, SkillName::CREATIVE],
                'activationRate' => 100,
                'modifierConfigs' => [],
                'spawnEquipmentConfigs' => [],
                'replaceEquipmentConfigs' => [
                    'replace_kitchen_by_snc_kitchen',
                ],
            ],
            [
                'name' => ProjectName::FLOOR_HEATING,
                'type' => ProjectType::NERON_PROJECT,
                'efficiency' => 12,
                'bonusSkills' => [SkillName::TECHNICIAN, SkillName::CONCEPTOR],
                'activationRate' => 100,
                'modifierConfigs' => [
                    'modifier_for_daedalus_x0.5clumsiness',
                ],
                'spawnEquipmentConfigs' => [],
                'replaceEquipmentConfigs' => [],
            ],
            [
                'name' => ProjectName::PARASITE_ELIM,
                'type' => ProjectType::NERON_PROJECT,
                'efficiency' => 12,
                'bonusSkills' => [SkillName::BOTANIST, SkillName::ROBOTICS_EXPERT],
                'activationRate' => 4,
                'modifierConfigs' => [
                ],
                'spawnEquipmentConfigs' => [],
                'replaceEquipmentConfigs' => [],
            ],
            [
                'name' => ProjectName::OXY_MORE,
                'type' => ProjectType::NERON_PROJECT,
                'efficiency' => 6,
                'bonusSkills' => [SkillName::TECHNICIAN, SkillName::BIOLOGIST],
                'activationRate' => 100,
                'modifierConfigs' => [
                    'modifier_for_daedalus_+1oxygen_on_change.variable_if_reason_new_cycle_random_20',
                ],
                'spawnEquipmentConfigs' => [],
                'replaceEquipmentConfigs' => [],
            ],
            [
                'name' => ProjectName::BEAT_BOX,
                'type' => ProjectType::NERON_PROJECT,
                'efficiency' => 18,
                'bonusSkills' => [SkillName::RADIO_EXPERT, SkillName::CREATIVE],
                'activationRate' => 2,
                'modifierConfigs' => [],
                'spawnEquipmentConfigs' => [
                    '1_jukebox_blueprint_in_nexus',
                ],
                'replaceEquipmentConfigs' => [],
            ],
        ];
    }
}
