<?php

declare(strict_types=1);

namespace Mush\Project\ConfigData;

use Mush\Chat\Enum\MessageModificationEnum;
use Mush\Equipment\ConfigData\ReplaceEquipmentConfigData;
use Mush\Equipment\ConfigData\SpawnEquipmentConfigData;
use Mush\MetaGame\Enum\SkinEnum;
use Mush\Modifier\Enum\ModifierNameEnum;
use Mush\Project\Enum\ProjectName;
use Mush\Project\Enum\ProjectRequirementName;
use Mush\Project\Enum\ProjectType;
use Mush\Skill\Enum\SkillEnum;

/**
 * @codeCoverageIgnore
 */
abstract class ProjectConfigData
{
    public static function getAll(): array
    {
        return [
            [
                'name' => ProjectName::PILGRED,
                'type' => ProjectType::PILGRED,
                'efficiency' => 100,
                'bonusSkills' => [SkillEnum::PHYSICIST, SkillEnum::TECHNICIAN],
                'activationRate' => 100,
                'modifierConfigs' => [],
                'spawnEquipmentConfigs' => [],
                'replaceEquipmentConfigs' => [],
                'requirements' => [],
                'skins' => [SkinEnum::PILGRED_ACTIVE],
            ],
            [
                'name' => ProjectName::FIRE_SENSOR,
                'type' => ProjectType::NERON_PROJECT,
                'efficiency' => 18,
                'bonusSkills' => [SkillEnum::RADIO_EXPERT, SkillEnum::FIREFIGHTER],
                'activationRate' => 100,
                'modifierConfigs' => [],
                'spawnEquipmentConfigs' => [],
                'replaceEquipmentConfigs' => [],
                'requirements' => [],
            ],
            [
                'name' => ProjectName::DOOR_SENSOR,
                'type' => ProjectType::NERON_PROJECT,
                'efficiency' => 18,
                'bonusSkills' => [SkillEnum::RADIO_EXPERT, SkillEnum::ROBOTICS_EXPERT],
                'activationRate' => 100,
                'modifierConfigs' => [],
                'spawnEquipmentConfigs' => [],
                'replaceEquipmentConfigs' => [],
                'requirements' => [],
            ],
            [
                'name' => ProjectName::EQUIPMENT_SENSOR,
                'type' => ProjectType::NERON_PROJECT,
                'efficiency' => 18,
                'bonusSkills' => [SkillEnum::RADIO_EXPERT, SkillEnum::TECHNICIAN],
                'activationRate' => 100,
                'modifierConfigs' => [],
                'spawnEquipmentConfigs' => [],
                'replaceEquipmentConfigs' => [],
                'requirements' => [],
            ],
            [
                'name' => ProjectName::PLASMA_SHIELD,
                'type' => ProjectType::NERON_PROJECT,
                'efficiency' => 100,
                'bonusSkills' => [SkillEnum::TECHNICIAN, SkillEnum::PHYSICIST],
                'activationRate' => 100,
                'modifierConfigs' => [
                    'modifier_for_daedalus_+5shield_on_new_cycle',
                ],
                'spawnEquipmentConfigs' => [],
                'replaceEquipmentConfigs' => [],
                'requirements' => [],
                'skins' => [SkinEnum::PLASMA_SHIELD_ACTIVE],
            ],
            [
                'name' => ProjectName::HEAT_LAMP,
                'type' => ProjectType::NERON_PROJECT,
                'efficiency' => 100,
                'bonusSkills' => [SkillEnum::TECHNICIAN, SkillEnum::BOTANIST],
                'activationRate' => 50,
                'modifierConfigs' => [],
                'spawnEquipmentConfigs' => [],
                'replaceEquipmentConfigs' => [],
                'requirements' => [],
                'skins' => [SkinEnum::GARDEN_LAMP],
            ],
            [
                'name' => ProjectName::TRAIL_REDUCER,
                'type' => ProjectType::NERON_PROJECT,
                'efficiency' => 6,
                'bonusSkills' => [SkillEnum::PILOT, SkillEnum::TECHNICIAN],
                'activationRate' => 100,
                'modifierConfigs' => [
                    'modifier_for_daedalus_-25percentage_following_hunters_on_daedalus_travel',
                ],
                'spawnEquipmentConfigs' => [],
                'replaceEquipmentConfigs' => [],
                'requirements' => [],
            ],
            [
                'name' => ProjectName::CHIPSET_ACCELERATION,
                'type' => ProjectType::NERON_PROJECT,
                'efficiency' => 6,
                'bonusSkills' => [SkillEnum::ASTROPHYSICIST, SkillEnum::IT_EXPERT],
                'activationRate' => 100,
                'modifierConfigs' => [
                    'modifier_for_daedalus_-1actionPoint_on_action_scan_planet',
                ],
                'spawnEquipmentConfigs' => [],
                'replaceEquipmentConfigs' => [],
                'requirements' => [],
            ],
            [
                'name' => ProjectName::DISMANTLING,
                'type' => ProjectType::NERON_PROJECT,
                'efficiency' => 12,
                'bonusSkills' => [SkillEnum::TECHNICIAN, SkillEnum::ROBOTICS_EXPERT],
                'activationRate' => 100,
                'modifierConfigs' => [],
                'replaceEquipmentConfigs' => [],
                'spawnEquipmentConfigs' => [
                    '5_metal_scraps_in_engine_room',
                ],
                'requirements' => [],
            ],
            [
                'name' => ProjectName::EXTRA_HYDROPONPOTS,
                'type' => ProjectType::NERON_PROJECT,
                'efficiency' => 6,
                'bonusSkills' => [SkillEnum::TECHNICIAN, SkillEnum::BOTANIST],
                'activationRate' => 100,
                'modifierConfigs' => [],
                'spawnEquipmentConfigs' => [
                    '3_hydropots_in_hydroponic_garden',
                ],
                'replaceEquipmentConfigs' => [],
                'requirements' => [],
            ],
            [
                'name' => ProjectName::AUXILIARY_TERMINAL,
                'type' => ProjectType::NERON_PROJECT,
                'efficiency' => 6,
                'bonusSkills' => [SkillEnum::RADIO_EXPERT, SkillEnum::IT_EXPERT],
                'activationRate' => 100,
                'modifierConfigs' => [],
                'spawnEquipmentConfigs' => [
                    '1_auxiliary_terminal_in_medlab',
                    '1_auxiliary_terminal_in_engine_room',
                ],
                'replaceEquipmentConfigs' => [],
                'requirements' => [],
            ],
            [
                'name' => ProjectName::THALASSO,
                'type' => ProjectType::NERON_PROJECT,
                'efficiency' => 18,
                'bonusSkills' => [SkillEnum::TECHNICIAN, SkillEnum::NURSE],
                'activationRate' => 100,
                'modifierConfigs' => [],
                'spawnEquipmentConfigs' => [],
                'replaceEquipmentConfigs' => [
                    'replace_all_showers_by_thalasso',
                ],
                'requirements' => [],
            ],
            [
                'name' => ProjectName::BRIC_BROC,
                'type' => ProjectType::NERON_PROJECT,
                'efficiency' => 6,
                'bonusSkills' => [SkillEnum::CONCEPTOR, SkillEnum::CREATIVE],
                'activationRate' => 15,
                'modifierConfigs' => [],
                'spawnEquipmentConfigs' => [],
                'replaceEquipmentConfigs' => [],
                'requirements' => [],
            ],
            [
                'name' => ProjectName::AUTO_WATERING,
                'type' => ProjectType::NERON_PROJECT,
                'efficiency' => 3,
                'bonusSkills' => [SkillEnum::TECHNICIAN, SkillEnum::FIREFIGHTER],
                'activationRate' => 25,
                'modifierConfigs' => [],
                'spawnEquipmentConfigs' => [],
                'replaceEquipmentConfigs' => [],
                'requirements' => [],
            ],
            [
                'name' => ProjectName::MAGNETIC_NET,
                'type' => ProjectType::NERON_PROJECT,
                'efficiency' => 6,
                'bonusSkills' => [SkillEnum::PILOT, SkillEnum::PHYSICIST],
                'activationRate' => 100,
                'modifierConfigs' => [],
                'spawnEquipmentConfigs' => [],
                'replaceEquipmentConfigs' => [],
                'requirements' => [],
            ],
            [
                'name' => ProjectName::ICARUS_ANTIGRAV_PROPELLER,
                'type' => ProjectType::NERON_PROJECT,
                'efficiency' => 100,
                'bonusSkills' => [SkillEnum::PILOT, SkillEnum::PHYSICIST],
                'activationRate' => 100,
                'modifierConfigs' => [],
                'spawnEquipmentConfigs' => [],
                'replaceEquipmentConfigs' => [],
                'requirements' => [],
                'skins' => [SkinEnum::ICARUS_THRUSTER],
            ],
            [
                'name' => ProjectName::FISSION_COFFEE_ROASTER,
                'type' => ProjectType::NERON_PROJECT,
                'efficiency' => 100,
                'bonusSkills' => [SkillEnum::CAFFEINE_JUNKIE, SkillEnum::PHYSICIST],
                'activationRate' => 100,
                'modifierConfigs' => [],
                'spawnEquipmentConfigs' => [],
                'replaceEquipmentConfigs' => [],
                'requirements' => [],
                'skins' => [SkinEnum::COFFEE_MACHINE_FISSION],
            ],
            [
                'name' => ProjectName::ARMOUR_CORRIDOR,
                'type' => ProjectType::NERON_PROJECT,
                'efficiency' => 3,
                'bonusSkills' => [SkillEnum::TECHNICIAN, SkillEnum::PHYSICIST],
                'activationRate' => 100,
                'modifierConfigs' => [
                    'modifier_for_daedalus_+1hull_on_change.variable_if_reason_hunter_shot',
                ],
                'spawnEquipmentConfigs' => [],
                'replaceEquipmentConfigs' => [],
                'requirements' => [],
            ],
            [
                'name' => ProjectName::CALL_OF_DIRTY,
                'type' => ProjectType::NERON_PROJECT,
                'efficiency' => 18,
                'bonusSkills' => [SkillEnum::TECHNICIAN, SkillEnum::SHOOTER],
                'activationRate' => 100,
                'modifierConfigs' => [],
                'spawnEquipmentConfigs' => [
                    '1_dynarcade_in_alpha_bay_2',
                ],
                'replaceEquipmentConfigs' => [],
                'requirements' => [],
            ],
            [
                'name' => ProjectName::EXTRA_DRONE,
                'type' => ProjectType::NERON_PROJECT,
                'efficiency' => 6,
                'bonusSkills' => [SkillEnum::TECHNICIAN, SkillEnum::ROBOTICS_EXPERT],
                'activationRate' => 100,
                'modifierConfigs' => [],
                'spawnEquipmentConfigs' => [
                    '1_support_drone_in_nexus',
                ],
                'replaceEquipmentConfigs' => [],
                'requirements' => [],
            ],
            [
                'name' => ProjectName::PATROLSHIP_BLASTER_GUN,
                'type' => ProjectType::NERON_PROJECT,
                'efficiency' => 100,
                'bonusSkills' => [SkillEnum::PILOT, SkillEnum::SHOOTER],
                'activationRate' => 100,
                'modifierConfigs' => [
                    'modifier_for_daedalus_-1hunter_health_on_change.variable',
                ],
                'spawnEquipmentConfigs' => [],
                'replaceEquipmentConfigs' => [],
                'requirements' => [],
                'skins' => [SkinEnum::PATROL_SHIP_BLASTER],
            ],
            [
                'name' => ProjectName::BAY_DOOR_XXL,
                'type' => ProjectType::NERON_PROJECT,
                'efficiency' => 6,
                'bonusSkills' => [SkillEnum::PILOT, SkillEnum::TECHNICIAN],
                'activationRate' => 100,
                'modifierConfigs' => [
                    'modifier_for_player_x1.5percentage_for_takeoff_and_land_actions',
                ],
                'spawnEquipmentConfigs' => [],
                'replaceEquipmentConfigs' => [],
                'requirements' => [],
            ],
            [
                'name' => ProjectName::TRASH_LOAD,
                'type' => ProjectType::NERON_PROJECT,
                'efficiency' => 18,
                'bonusSkills' => [SkillEnum::TECHNICIAN, SkillEnum::ROBOTICS_EXPERT],
                'activationRate' => 100,
                'modifierConfigs' => [],
                'spawnEquipmentConfigs' => [
                    '4_metal_scraps_in_engine_room',
                    '4_plastic_scraps_in_engine_room',
                ],
                'replaceEquipmentConfigs' => [],
                'requirements' => [],
            ],
            [
                'name' => ProjectName::FOOD_RETAILER,
                'type' => ProjectType::NERON_PROJECT,
                'efficiency' => 6,
                'bonusSkills' => [SkillEnum::ROBOTICS_EXPERT, SkillEnum::CHEF],
                'activationRate' => 100,
                'modifierConfigs' => [],
                'spawnEquipmentConfigs' => [],
                'replaceEquipmentConfigs' => [],
                'requirements' => [],
            ],
            [
                'name' => ProjectName::AUTO_RETURN_ICARUS,
                'type' => ProjectType::NERON_PROJECT,
                'efficiency' => 12,
                'bonusSkills' => [SkillEnum::IT_EXPERT, SkillEnum::ROBOTICS_EXPERT],
                'activationRate' => 100,
                'modifierConfigs' => [],
                'spawnEquipmentConfigs' => [],
                'replaceEquipmentConfigs' => [],
                'requirements' => [],
            ],
            [
                'name' => ProjectName::RADAR_TRANS_VOID,
                'type' => ProjectType::NERON_PROJECT,
                'efficiency' => 100,
                'bonusSkills' => [SkillEnum::TECHNICIAN, SkillEnum::RADIO_EXPERT],
                'activationRate' => 100,
                'modifierConfigs' => [],
                'spawnEquipmentConfigs' => [],
                'replaceEquipmentConfigs' => [
                    'replace_antenna_by_radar_trans_void_antenna',
                ],
                'requirements' => [],
                'skins' => [SkinEnum::ANTENNA_SPATIAL_WAVE],
            ],
            [
                'name' => ProjectName::NERON_TARGETING_ASSIST,
                'type' => ProjectType::NERON_PROJECT,
                'efficiency' => 3,
                'bonusSkills' => [SkillEnum::PILOT, SkillEnum::SHOOTER],
                'activationRate' => 100,
                'modifierConfigs' => [
                    'modifier_for_daedalus_x1.25_percentage_on_shoot_hunter',
                ],
                'spawnEquipmentConfigs' => [],
                'replaceEquipmentConfigs' => [],
                'requirements' => [],
            ],
            [
                'name' => ProjectName::WHOS_WHO,
                'type' => ProjectType::NERON_PROJECT,
                'efficiency' => 18,
                'bonusSkills' => [SkillEnum::RADIO_EXPERT, SkillEnum::PARANOID],
                'activationRate' => 100,
                'modifierConfigs' => [],
                'spawnEquipmentConfigs' => [],
                'replaceEquipmentConfigs' => [],
                'requirements' => [],
            ],
            [
                'name' => ProjectName::HYDROPONIC_INCUBATOR,
                'type' => ProjectType::NERON_PROJECT,
                'efficiency' => 100,
                'bonusSkills' => [SkillEnum::PHYSICIST, SkillEnum::BOTANIST],
                'activationRate' => 100,
                'modifierConfigs' => [],
                'spawnEquipmentConfigs' => [
                    '1_hydroponic_incubator_in_hydroponic_garden',
                ],
                'replaceEquipmentConfigs' => [],
                'requirements' => [],
                'skins' => [SkinEnum::GARDEN_INCUBATOR],
            ],
            [
                'name' => ProjectName::ICARUS_LAVATORY,
                'type' => ProjectType::NERON_PROJECT,
                'efficiency' => 18,
                'bonusSkills' => [SkillEnum::BIOLOGIST, SkillEnum::TECHNICIAN],
                'activationRate' => 100,
                'modifierConfigs' => [
                    'modifier_for_player_prevent_dirty_for_exploration_finished',
                ],
                'spawnEquipmentConfigs' => [],
                'replaceEquipmentConfigs' => [],
                'requirements' => [],
            ],
            [
                'name' => ProjectName::ICARUS_LARGER_BAY,
                'type' => ProjectType::NERON_PROJECT,
                'efficiency' => 100,
                'bonusSkills' => [SkillEnum::PILOT, SkillEnum::TECHNICIAN],
                'activationRate' => 100,
                'modifierConfigs' => [
                    'modifier_for_daedalus_+2players_allowed_on_takeoff_to_planet',
                ],
                'spawnEquipmentConfigs' => [],
                'replaceEquipmentConfigs' => [],
                'requirements' => [],
                'skins' => [SkinEnum::ICARUS_LARGE],
            ],
            [
                'name' => ProjectName::PATROL_SHIP_LAUNCHER,
                'type' => ProjectType::NERON_PROJECT,
                'efficiency' => 6,
                'bonusSkills' => [SkillEnum::PILOT, SkillEnum::PHYSICIST],
                'activationRate' => 100,
                'modifierConfigs' => [
                    'modifier_for_daedalus_-1action_point_on_action_take_off',
                ],
                'spawnEquipmentConfigs' => [],
                'replaceEquipmentConfigs' => [],
                'requirements' => [],
            ],
            [
                'name' => ProjectName::NERON_PROJECT_THREAD,
                'type' => ProjectType::NERON_PROJECT,
                'efficiency' => 100,
                'bonusSkills' => [SkillEnum::IT_EXPERT, SkillEnum::SHRINK],
                'activationRate' => 5,
                'modifierConfigs' => [],
                'spawnEquipmentConfigs' => [],
                'replaceEquipmentConfigs' => [],
                'requirements' => [],
                'skins' => [SkinEnum::NERON_PARTICIPATION_AUXILIARY_TERMINAL, SkinEnum::NERON_CORE_PARTICIPATION],
            ],
            [
                'name' => ProjectName::TURRET_EXTRA_FIRE_RATE,
                'type' => ProjectType::NERON_PROJECT,
                'efficiency' => 100,
                'bonusSkills' => [SkillEnum::PHYSICIST, SkillEnum::TECHNICIAN],
                'activationRate' => 100,
                'modifierConfigs' => [
                    'modifier_for_daedalus_x2_turret_charges_on_new_cycle',
                ],
                'spawnEquipmentConfigs' => [],
                'replaceEquipmentConfigs' => [],
                'requirements' => [],
                'skins' => [SkinEnum::TURRET_CHARGES],
            ],
            [
                'name' => ProjectName::QUANTUM_SENSORS,
                'type' => ProjectType::NERON_PROJECT,
                'efficiency' => 6,
                'bonusSkills' => [SkillEnum::ASTROPHYSICIST, SkillEnum::RADIO_EXPERT],
                'activationRate' => 100,
                'modifierConfigs' => [],
                'spawnEquipmentConfigs' => [],
                'replaceEquipmentConfigs' => [
                    'replace_planet_scanner_by_quantum_sensors_planet_scanner',
                ],
                'requirements' => [],
            ],
            [
                'name' => ProjectName::PATROLSHIP_EXTRA_AMMO,
                'type' => ProjectType::NERON_PROJECT,
                'efficiency' => 100,
                'bonusSkills' => [SkillEnum::PHYSICIST, SkillEnum::TECHNICIAN],
                'activationRate' => 100,
                'modifierConfigs' => [
                    'modifier_for_daedalus_+6_patrol_ship_max_charges',
                    'modifier_for_daedalus_patrol_ship_set_charges_to_maximum',
                ],
                'spawnEquipmentConfigs' => [],
                'replaceEquipmentConfigs' => [],
                'requirements' => [],
                'skins' => [SkinEnum::PATROL_SHIP_TELSATRON],
            ],
            [
                'name' => ProjectName::NOISE_REDUCER,
                'type' => ProjectType::NERON_PROJECT,
                'efficiency' => 3,
                'bonusSkills' => [SkillEnum::PHYSICIST, SkillEnum::BIOLOGIST],
                'activationRate' => 100,
                'modifierConfigs' => [
                    'direct_modifier_player_+2_max_actionPoint',
                ],
                'spawnEquipmentConfigs' => [],
                'replaceEquipmentConfigs' => [],
                'requirements' => [],
            ],
            [
                'name' => ProjectName::APERO_KITCHEN,
                'type' => ProjectType::NERON_PROJECT,
                'efficiency' => 18,
                'bonusSkills' => [SkillEnum::CHEF, SkillEnum::CREATIVE],
                'activationRate' => 100,
                'modifierConfigs' => [],
                'spawnEquipmentConfigs' => [],
                'replaceEquipmentConfigs' => [
                    'replace_kitchen_by_snc_kitchen',
                ],
                'requirements' => [],
                'skins' => [SkinEnum::KITCHEN_APERO, SkinEnum::KITCHEN_APERO_TABLE],
            ],
            [
                'name' => ProjectName::FLOOR_HEATING,
                'type' => ProjectType::NERON_PROJECT,
                'efficiency' => 12,
                'bonusSkills' => [SkillEnum::TECHNICIAN, SkillEnum::CONCEPTOR],
                'activationRate' => 100,
                'modifierConfigs' => [
                    'modifier_for_daedalus_x0.5clumsiness',
                ],
                'spawnEquipmentConfigs' => [],
                'replaceEquipmentConfigs' => [],
                'requirements' => [],
            ],
            [
                'name' => ProjectName::PARASITE_ELIM,
                'type' => ProjectType::NERON_PROJECT,
                'efficiency' => 12,
                'bonusSkills' => [SkillEnum::BOTANIST, SkillEnum::ROBOTICS_EXPERT],
                'activationRate' => 4,
                'modifierConfigs' => [
                ],
                'spawnEquipmentConfigs' => [],
                'replaceEquipmentConfigs' => [],
                'requirements' => [],
            ],
            [
                'name' => ProjectName::OXY_MORE,
                'type' => ProjectType::NERON_PROJECT,
                'efficiency' => 6,
                'bonusSkills' => [SkillEnum::TECHNICIAN, SkillEnum::BIOLOGIST],
                'activationRate' => 100,
                'modifierConfigs' => [
                    'modifier_for_daedalus_+1oxygen_on_change.variable_if_reason_new_cycle_random_20',
                ],
                'spawnEquipmentConfigs' => [],
                'replaceEquipmentConfigs' => [],
                'requirements' => [],
            ],
            [
                'name' => ProjectName::BEAT_BOX,
                'type' => ProjectType::NERON_PROJECT,
                'efficiency' => 18,
                'bonusSkills' => [SkillEnum::RADIO_EXPERT, SkillEnum::CREATIVE],
                'activationRate' => 2,
                'modifierConfigs' => [],
                'spawnEquipmentConfigs' => [
                    '1_jukebox_blueprint_in_nexus',
                ],
                'replaceEquipmentConfigs' => [],
                'requirements' => [],
            ],
            [
                'name' => ProjectName::ANABOLICS,
                'type' => ProjectType::RESEARCH,
                'efficiency' => 12,
                'bonusSkills' => [SkillEnum::BIOLOGIST, SkillEnum::MEDIC],
                'activationRate' => 100,
                'modifierConfigs' => [],
                'spawnEquipmentConfigs' => [
                    SpawnEquipmentConfigData::FOUR_ANABOLICS_IN_LABORATORY,
                ],
                'replaceEquipmentConfigs' => [],
                'requirements' => [],
            ],
            [
                'name' => ProjectName::ANTISPORE_GAS,
                'type' => ProjectType::RESEARCH,
                'efficiency' => 6,
                'bonusSkills' => [SkillEnum::BIOLOGIST, SkillEnum::MEDIC],
                'activationRate' => 100,
                'modifierConfigs' => [
                    ModifierNameEnum::DAEDALUS_MINUS_2_MAX_SPORES,
                ],
                'spawnEquipmentConfigs' => [],
                'replaceEquipmentConfigs' => [],
                'requirements' => [
                    ProjectRequirementName::GAME_STARTED,
                    ProjectRequirementName::MUSH_SAMPLE_IN_LABORATORY,
                ],
            ],
            [
                'name' => ProjectName::CONSTIPASPORE_SERUM,
                'type' => ProjectType::RESEARCH,
                'efficiency' => 6,
                'bonusSkills' => [SkillEnum::BIOLOGIST, SkillEnum::MEDIC],
                'activationRate' => 100,
                'modifierConfigs' => [
                    ModifierNameEnum::PLUS_2_ACTION_POINTS_ON_EXTRACT_SPORE,
                ],
                'spawnEquipmentConfigs' => [],
                'replaceEquipmentConfigs' => [],
                'requirements' => [
                    ProjectRequirementName::GAME_STARTED,
                    ProjectRequirementName::MUSH_SAMPLE_IN_LABORATORY,
                    ProjectRequirementName::FOOD_IN_LABORATORY,
                ],
            ],
            [
                'name' => ProjectName::MERIDON_SCRAMBLER,
                'type' => ProjectType::RESEARCH,
                'efficiency' => 3,
                'bonusSkills' => [SkillEnum::BIOLOGIST, SkillEnum::MEDIC],
                'activationRate' => 20,
                'modifierConfigs' => [],
                'spawnEquipmentConfigs' => [],
                'replaceEquipmentConfigs' => [],
                'requirements' => [
                    ProjectRequirementName::MUSH_PLAYER_DEAD,
                ],
            ],
            [
                'name' => ProjectName::MUSHICIDE_SOAP,
                'type' => ProjectType::RESEARCH,
                'efficiency' => 3,
                'bonusSkills' => [SkillEnum::BIOLOGIST, SkillEnum::MEDIC],
                'activationRate' => 100,
                'modifierConfigs' => [],
                'spawnEquipmentConfigs' => [],
                'replaceEquipmentConfigs' => [
                    ReplaceEquipmentConfigData::REPLACE_SOAP_BY_SUPER_SOAP,
                ],
                'requirements' => [
                    ProjectRequirementName::GAME_STARTED,
                    ProjectRequirementName::SOAP_IN_LABORATORY,
                    ProjectRequirementName::CHUN_IN_LABORATORY,
                ],
            ],
            [
                'name' => ProjectName::MUSHOVORE_BACTERIA,
                'type' => ProjectType::RESEARCH,
                'efficiency' => 12,
                'bonusSkills' => [SkillEnum::BIOLOGIST, SkillEnum::MEDIC],
                'activationRate' => 100,
                'modifierConfigs' => [
                    ModifierNameEnum::PLAYER_PLUS_1_MAX_SPORES,
                ],
                'spawnEquipmentConfigs' => [],
                'replaceEquipmentConfigs' => [],
                'requirements' => [
                    ProjectRequirementName::GAME_STARTED,
                    ProjectRequirementName::MUSH_PLAYER_DEAD,
                    ProjectRequirementName::CHUN_IN_LABORATORY,
                ],
            ],
            [
                'name' => ProjectName::MUSH_HUNTER_ZC16H,
                'type' => ProjectType::RESEARCH,
                'efficiency' => 6,
                'bonusSkills' => [SkillEnum::BIOLOGIST, SkillEnum::MEDIC],
                'activationRate' => 100,
                'modifierConfigs' => [],
                'spawnEquipmentConfigs' => [],
                'replaceEquipmentConfigs' => [],
                'requirements' => [
                    ProjectRequirementName::MUSH_SAMPLE_IN_LABORATORY,
                    ProjectRequirementName::CHUN_IN_LABORATORY,
                ],
            ],
            [
                'name' => ProjectName::MUSH_LANGUAGE,
                'type' => ProjectType::RESEARCH,
                'efficiency' => 6,
                'bonusSkills' => [SkillEnum::BIOLOGIST, SkillEnum::MEDIC],
                'activationRate' => 100,
                'modifierConfigs' => [],
                'spawnEquipmentConfigs' => [],
                'replaceEquipmentConfigs' => [],
                'requirements' => [
                    ProjectRequirementName::MUSH_GENOME_DISK_IN_LABORATORY,
                ],
            ],
            [
                'name' => ProjectName::MUSH_RACES,
                'type' => ProjectType::RESEARCH,
                'efficiency' => 6,
                'bonusSkills' => [SkillEnum::BIOLOGIST, SkillEnum::MEDIC],
                'activationRate' => 100,
                'modifierConfigs' => [],
                'spawnEquipmentConfigs' => [],
                'replaceEquipmentConfigs' => [],
                'requirements' => [
                    ProjectRequirementName::MUSH_PLAYER_DEAD,
                ],
            ],
            [
                'name' => ProjectName::MUSH_REPRODUCTIVE_SYSTEM,
                'type' => ProjectType::RESEARCH,
                'efficiency' => 18,
                'bonusSkills' => [SkillEnum::BIOLOGIST, SkillEnum::MEDIC],
                'activationRate' => 100,
                'modifierConfigs' => [],
                'spawnEquipmentConfigs' => [],
                'replaceEquipmentConfigs' => [],
                'requirements' => [
                    ProjectRequirementName::MUSH_PLAYER_DEAD,
                    ProjectRequirementName::MUSH_GENOME_DISK_IN_LABORATORY,
                ],
            ],
            [
                'name' => ProjectName::MYCOALARM,
                'type' => ProjectType::RESEARCH,
                'efficiency' => 6,
                'bonusSkills' => [SkillEnum::BIOLOGIST, SkillEnum::MEDIC],
                'activationRate' => 100,
                'modifierConfigs' => [],
                'spawnEquipmentConfigs' => [
                    SpawnEquipmentConfigData::FIVE_MYCOALARMS_IN_LABORATORY,
                ],
                'replaceEquipmentConfigs' => [],
                'requirements' => [
                    ProjectRequirementName::GAME_STARTED,
                    ProjectRequirementName::MUSH_SAMPLE_IN_LABORATORY,
                ],
            ],
            [
                'name' => ProjectName::CREATE_MYCOSCAN,
                'type' => ProjectType::RESEARCH,
                'efficiency' => 4,
                'bonusSkills' => [SkillEnum::BIOLOGIST, SkillEnum::MEDIC],
                'activationRate' => 100,
                'modifierConfigs' => [],
                'spawnEquipmentConfigs' => [
                    SpawnEquipmentConfigData::ONE_MYCOSCAN_IN_LABORATORY,
                ],
                'replaceEquipmentConfigs' => [],
                'requirements' => [
                    ProjectRequirementName::GAME_STARTED,
                    ProjectRequirementName::CHUN_IN_LABORATORY,
                ],
            ],
            [
                'name' => ProjectName::NARCOTICS_DISTILLER,
                'type' => ProjectType::RESEARCH,
                'efficiency' => 6,
                'bonusSkills' => [SkillEnum::BIOLOGIST, SkillEnum::MEDIC],
                'activationRate' => 100,
                'modifierConfigs' => [],
                'spawnEquipmentConfigs' => [
                    SpawnEquipmentConfigData::ONE_NARCOTICS_DISTILLER_IN_MEDLAB,
                ],
                'replaceEquipmentConfigs' => [],
                'requirements' => [],
            ],
            [
                'name' => ProjectName::NATAMY_RIFLE,
                'type' => ProjectType::RESEARCH,
                'efficiency' => 6,
                'bonusSkills' => [SkillEnum::BIOLOGIST, SkillEnum::MEDIC],
                'activationRate' => 100,
                'modifierConfigs' => [],
                'spawnEquipmentConfigs' => [],
                'replaceEquipmentConfigs' => [
                    ReplaceEquipmentConfigData::REPLACE_1_LABORATORY_BY_NATAMY_RIFLE,
                ],
                'requirements' => [
                    ProjectRequirementName::GAME_STARTED,
                    ProjectRequirementName::BLASTER_IN_LABORATORY,
                    ProjectRequirementName::MUSH_SAMPLE_IN_LABORATORY,
                ],
            ],
            [
                'name' => ProjectName::NCC_CONTACT_LENSES,
                'type' => ProjectType::RESEARCH,
                'efficiency' => 12,
                'bonusSkills' => [SkillEnum::BIOLOGIST, SkillEnum::MEDIC],
                'activationRate' => 100,
                'modifierConfigs' => [],
                'spawnEquipmentConfigs' => [
                    SpawnEquipmentConfigData::TWO_NCC_LENSES_IN_LABORATORY,
                ],
                'replaceEquipmentConfigs' => [],
                'requirements' => [
                    ProjectRequirementName::SCHRODINGER_IN_PLAYER_INVENTORY,
                ],
            ],
            [
                'name' => ProjectName::PATULINE_SCRAMBLER,
                'type' => ProjectType::RESEARCH,
                'efficiency' => 6,
                'bonusSkills' => [SkillEnum::BIOLOGIST, SkillEnum::MEDIC],
                'activationRate' => 100,
                'modifierConfigs' => [
                    MessageModificationEnum::PATULINE_SCRAMBLER_MODIFICATION,
                ],
                'spawnEquipmentConfigs' => [],
                'replaceEquipmentConfigs' => [],
                'requirements' => [
                    ProjectRequirementName::GAME_STARTED,
                    ProjectRequirementName::MUSH_PLAYER_DEAD,
                ],
            ],
            [
                'name' => ProjectName::PERPETUAL_HYDRATION,
                'type' => ProjectType::RESEARCH,
                'efficiency' => 6,
                'bonusSkills' => [SkillEnum::BIOLOGIST, SkillEnum::MEDIC],
                'activationRate' => 100,
                'modifierConfigs' => [],
                'spawnEquipmentConfigs' => [],
                'replaceEquipmentConfigs' => [],
                'requirements' => [
                    ProjectRequirementName::WATER_STICK_IN_LABORATORY,
                ],
            ],
            [
                'name' => ProjectName::PHEROMODEM,
                'type' => ProjectType::RESEARCH,
                'efficiency' => 3,
                'bonusSkills' => [SkillEnum::BIOLOGIST, SkillEnum::MEDIC],
                'activationRate' => 100,
                'modifierConfigs' => [],
                'spawnEquipmentConfigs' => [],
                'replaceEquipmentConfigs' => [],
                'requirements' => [
                    ProjectRequirementName::GAME_STARTED,
                    ProjectRequirementName::MUSH_PLAYER_DEAD,
                    ProjectRequirementName::MUSH_GENOME_DISK_IN_LABORATORY,
                ],
            ],
            [
                'name' => ProjectName::RETRO_FUNGAL_SERUM,
                'type' => ProjectType::RESEARCH,
                'efficiency' => 1,
                'bonusSkills' => [SkillEnum::BIOLOGIST, SkillEnum::MEDIC],
                'activationRate' => 100,
                'modifierConfigs' => [],
                'spawnEquipmentConfigs' => [
                    SpawnEquipmentConfigData::ONE_RETRO_FUNGAL_SERUM_IN_LABORATORY,
                ],
                'replaceEquipmentConfigs' => [],
                'requirements' => [
                    ProjectRequirementName::GAME_STARTED,
                    ProjectRequirementName::MUSH_SAMPLE_IN_LABORATORY,
                    ProjectRequirementName::MUSH_PLAYER_DEAD,
                    ProjectRequirementName::CHUN_IN_LABORATORY,
                    ProjectRequirementName::MUSH_GENOME_DISK_IN_LABORATORY,
                ],
            ],
            [
                'name' => ProjectName::SPORE_SUCKER,
                'type' => ProjectType::RESEARCH,
                'efficiency' => 4,
                'bonusSkills' => [SkillEnum::BIOLOGIST, SkillEnum::MEDIC],
                'activationRate' => 100,
                'modifierConfigs' => [],
                'spawnEquipmentConfigs' => [
                    SpawnEquipmentConfigData::ONE_SPORE_SUCKER_IN_LABORATORY,
                ],
                'replaceEquipmentConfigs' => [],
                'requirements' => [
                    ProjectRequirementName::GAME_STARTED,
                    ProjectRequirementName::MUSH_SAMPLE_IN_LABORATORY,
                ],
            ],
            [
                'name' => ProjectName::SUPER_CALCULATOR,
                'type' => ProjectType::RESEARCH,
                'efficiency' => 3,
                'bonusSkills' => [SkillEnum::BIOLOGIST, SkillEnum::MEDIC],
                'activationRate' => 100,
                'modifierConfigs' => [],
                'spawnEquipmentConfigs' => [
                    SpawnEquipmentConfigData::ONE_CALCULATOR_IN_NEXUS,
                ],
                'replaceEquipmentConfigs' => [],
                'requirements' => [
                    ProjectRequirementName::STARMAP_FRAGMENT_IN_LABORATORY,
                ],
            ],
            [
                'name' => ProjectName::TESLA_SUP2X,
                'type' => ProjectType::RESEARCH,
                'efficiency' => 12,
                'bonusSkills' => [SkillEnum::BIOLOGIST, SkillEnum::MEDIC],
                'activationRate' => 100,
                'modifierConfigs' => [
                    ModifierNameEnum::TURRET_MAX_CHARGES_PLUS_4,
                    ModifierNameEnum::TURRET_CHARGES_PLUS_8,
                ],
                'spawnEquipmentConfigs' => [],
                'replaceEquipmentConfigs' => [],
                'requirements' => [
                    ProjectRequirementName::WATER_STICK_IN_LABORATORY,
                ],
            ],
            [
                'name' => ProjectName::ULTRA_HEALING_POMADE,
                'type' => ProjectType::RESEARCH,
                'efficiency' => 6,
                'bonusSkills' => [SkillEnum::BIOLOGIST, SkillEnum::MEDIC],
                'activationRate' => 100,
                'modifierConfigs' => [
                    ModifierNameEnum::PLUS_1_HEALTH_POINTS_ON_HEAL,
                ],
                'spawnEquipmentConfigs' => [],
                'replaceEquipmentConfigs' => [],
                'requirements' => [
                    ProjectRequirementName::MEDIKIT_IN_LABORATORY,
                ],
            ],
            [
                'name' => ProjectName::GUARANA_CAPPUCCINO,
                'type' => ProjectType::RESEARCH,
                'efficiency' => 100,
                'bonusSkills' => [SkillEnum::BIOLOGIST, SkillEnum::MEDIC],
                'activationRate' => 100,
                'modifierConfigs' => [
                    ModifierNameEnum::PLAYER_PLUS_1_ACTION_POINTS_ON_CONSUME_ACTION_IF_COFFEE,
                ],
                'spawnEquipmentConfigs' => [],
                'replaceEquipmentConfigs' => [],
                'requirements' => [
                    ProjectRequirementName::COFFEE_IN_LABORATORY,
                ],
                'skins' => [SkinEnum::COFFEE_MACHINE_GUARANA],
            ],
        ];
    }
}
