<?php

namespace Mush\Action\ConfigData;

use Mush\Action\Enum\ActionEnum;
use Mush\Action\Enum\ActionScopeEnum;
use Mush\Action\Enum\ActionTypeEnum;
use Mush\Equipment\Entity\GameEquipment;
use Mush\Game\Enum\ActionOutputEnum;
use Mush\Game\Enum\VisibilityEnum;
use Mush\Hunter\Entity\Hunter;

/**
 * @codeCoverageIgnore
 */
class ActionData
{
    public static array $dataArray = [
        [
            'name' => 'suicide',
            'action_name' => 'suicide',
            'types' => [ActionTypeEnum::ACTION_ADMIN],
            'target' => null,
            'scope' => 'self',
            'visibilities' => ['success' => 'public', 'fail' => 'private'],
            'actionPoint' => ['value' => 0, 'min_value' => 0, 'max_value' => null],
            'movementPoint' => ['value' => 0, 'min_value' => 0, 'max_value' => null],
            'moralPoint' => ['value' => 0, 'min_value' => 0, 'max_value' => null],
            'percentageInjury' => ['value' => 0, 'min_value' => 0, 'max_value' => 100],
            'percentageDirtiness' => ['value' => 0, 'min_value' => 0, 'max_value' => 100],
            'percentageSuccess' => ['value' => 100, 'min_value' => 1, 'max_value' => 100],
            'percentageCritical' => ['value' => 0, 'min_value' => 0, 'max_value' => 100],
        ],
        [
            'name' => 'auto_destroy',
            'action_name' => 'auto_destroy',
            'types' => [ActionTypeEnum::ACTION_ADMIN],
            'target' => null,
            'scope' => 'self',
            'visibilities' => ['success' => 'private', 'fail' => 'private'],
            'actionPoint' => ['value' => 0, 'min_value' => 0, 'max_value' => null],
            'movementPoint' => ['value' => 0, 'min_value' => 0, 'max_value' => null],
            'moralPoint' => ['value' => 0, 'min_value' => 0, 'max_value' => null],
            'percentageInjury' => ['value' => 0, 'min_value' => 0, 'max_value' => 100],
            'percentageDirtiness' => ['value' => 0, 'min_value' => 0, 'max_value' => 100],
            'percentageSuccess' => ['value' => 100, 'min_value' => 1, 'max_value' => 100],
            'percentageCritical' => ['value' => 0, 'min_value' => 0, 'max_value' => 100],
        ],
        [
            'name' => 'kill_player',
            'action_name' => 'kill_player',
            'types' => [ActionTypeEnum::ACTION_ADMIN],
            'target' => null,
            'scope' => 'other_player',
            'visibilities' => ['success' => 'public', 'fail' => 'private'],
            'actionPoint' => ['value' => 0, 'min_value' => 0, 'max_value' => null],
            'movementPoint' => ['value' => 0, 'min_value' => 0, 'max_value' => null],
            'moralPoint' => ['value' => 0, 'min_value' => 0, 'max_value' => null],
            'percentageInjury' => ['value' => 0, 'min_value' => 0, 'max_value' => 100],
            'percentageDirtiness' => ['value' => 0, 'min_value' => 0, 'max_value' => 100],
            'percentageSuccess' => ['value' => 100, 'min_value' => 1, 'max_value' => 100],
            'percentageCritical' => ['value' => 0, 'min_value' => 0, 'max_value' => 100],
        ],
        [
            'name' => 'rejuvenate_alpha',
            'action_name' => 'rejuvenate',
            'types' => [ActionTypeEnum::ACTION_ADMIN],
            'target' => null,
            'scope' => 'self',
            'visibilities' => ['success' => 'public', 'fail' => 'private'],
            'actionPoint' => ['value' => 0, 'min_value' => 0, 'max_value' => null],
            'movementPoint' => ['value' => 0, 'min_value' => 0, 'max_value' => null],
            'moralPoint' => ['value' => 0, 'min_value' => 0, 'max_value' => null],
            'percentageInjury' => ['value' => 0, 'min_value' => 0, 'max_value' => 100],
            'percentageDirtiness' => ['value' => 0, 'min_value' => 0, 'max_value' => 100],
            'percentageSuccess' => ['value' => 100, 'min_value' => 1, 'max_value' => 100],
            'percentageCritical' => ['value' => 0, 'min_value' => 0, 'max_value' => 100],
        ],
        [
            'name' => 'update_talkie',
            'action_name' => 'update_talkie',
            'types' => [],
            'target' => null,
            'scope' => 'current',
            'visibilities' => ['success' => 'private', 'fail' => 'private'],
            'actionPoint' => ['value' => 1, 'min_value' => 0, 'max_value' => null],
            'movementPoint' => ['value' => 0, 'min_value' => 0, 'max_value' => null],
            'moralPoint' => ['value' => 0, 'min_value' => 0, 'max_value' => null],
            'percentageInjury' => ['value' => 10, 'min_value' => 0, 'max_value' => 100],
            'percentageDirtiness' => ['value' => 0, 'min_value' => 0, 'max_value' => 100],
            'percentageSuccess' => ['value' => 100, 'min_value' => 1, 'max_value' => 100],
            'percentageCritical' => ['value' => 0, 'min_value' => 0, 'max_value' => 100],
        ],
        [
            'name' => 'move',
            'action_name' => 'move',
            'types' => [],
            'target' => null,
            'scope' => 'current',
            'visibilities' => ['success' => 'public', 'fail' => 'private'],
            'actionPoint' => ['value' => 0, 'min_value' => 0, 'max_value' => null],
            'movementPoint' => ['value' => 1, 'min_value' => 0, 'max_value' => null],
            'moralPoint' => ['value' => 0, 'min_value' => 0, 'max_value' => null],
            'percentageInjury' => ['value' => 0, 'min_value' => 0, 'max_value' => 100],
            'percentageDirtiness' => ['value' => 0, 'min_value' => 0, 'max_value' => 100],
            'percentageSuccess' => ['value' => 100, 'min_value' => 1, 'max_value' => 100],
            'percentageCritical' => ['value' => 0, 'min_value' => 0, 'max_value' => 100],
        ],
        [
            'name' => 'search',
            'action_name' => 'search',
            'types' => [],
            'target' => null,
            'scope' => 'self',
            'visibilities' => ['success' => 'public', 'fail' => 'private'],
            'actionPoint' => ['value' => 1, 'min_value' => 0, 'max_value' => null],
            'movementPoint' => ['value' => 0, 'min_value' => 0, 'max_value' => null],
            'moralPoint' => ['value' => 0, 'min_value' => 0, 'max_value' => null],
            'percentageInjury' => ['value' => 0, 'min_value' => 0, 'max_value' => 100],
            'percentageDirtiness' => ['value' => 0, 'min_value' => 0, 'max_value' => 100],
            'percentageSuccess' => ['value' => 100, 'min_value' => 1, 'max_value' => 100],
            'percentageCritical' => ['value' => 0, 'min_value' => 0, 'max_value' => 100],
        ],
        [
            'name' => 'hit',
            'action_name' => 'hit',
            'types' => ['action_aggressive'],
            'target' => null,
            'scope' => 'other_player',
            'visibilities' => ['success' => 'public', 'fail' => 'public', ActionOutputEnum::CRITICAL_SUCCESS => VisibilityEnum::PUBLIC],
            'actionPoint' => ['value' => 1, 'min_value' => 0, 'max_value' => null],
            'movementPoint' => ['value' => 0, 'min_value' => 0, 'max_value' => null],
            'moralPoint' => ['value' => 0, 'min_value' => 0, 'max_value' => null],
            'percentageInjury' => ['value' => 0, 'min_value' => 0, 'max_value' => 100],
            'percentageDirtiness' => ['value' => 15, 'min_value' => 0, 'max_value' => 100],
            'percentageSuccess' => ['value' => 60, 'min_value' => 1, 'max_value' => 99],
            'percentageCritical' => ['value' => 40, 'min_value' => 0, 'max_value' => 100],
        ],
        [
            'name' => 'hide',
            'action_name' => 'hide',
            'types' => [],
            'target' => null,
            'scope' => 'current',
            'visibilities' => ['success' => 'secret', 'fail' => 'private'],
            'actionPoint' => ['value' => 1, 'min_value' => 0, 'max_value' => null],
            'movementPoint' => ['value' => 0, 'min_value' => 0, 'max_value' => null],
            'moralPoint' => ['value' => 0, 'min_value' => 0, 'max_value' => null],
            'percentageInjury' => ['value' => 0, 'min_value' => 0, 'max_value' => 100],
            'percentageDirtiness' => ['value' => 0, 'min_value' => 0, 'max_value' => 100],
            'percentageSuccess' => ['value' => 100, 'min_value' => 1, 'max_value' => 100],
            'percentageCritical' => ['value' => 0, 'min_value' => 0, 'max_value' => 100],
        ],
        [
            'name' => 'take',
            'action_name' => 'take',
            'types' => [],
            'target' => null,
            'scope' => 'current',
            'visibilities' => ['success' => 'public', 'fail' => 'private'],
            'actionPoint' => ['value' => 0, 'min_value' => 0, 'max_value' => null],
            'movementPoint' => ['value' => 0, 'min_value' => 0, 'max_value' => null],
            'moralPoint' => ['value' => 0, 'min_value' => 0, 'max_value' => null],
            'percentageInjury' => ['value' => 1, 'min_value' => 0, 'max_value' => 100],
            'percentageDirtiness' => ['value' => 0, 'min_value' => 0, 'max_value' => 100],
            'percentageSuccess' => ['value' => 100, 'min_value' => 1, 'max_value' => 100],
            'percentageCritical' => ['value' => 0, 'min_value' => 0, 'max_value' => 100],
        ],
        [
            'name' => 'drop',
            'action_name' => 'drop',
            'types' => [],
            'target' => null,
            'scope' => 'current',
            'visibilities' => ['success' => 'public', 'fail' => 'private'],
            'actionPoint' => ['value' => 0, 'min_value' => 0, 'max_value' => null],
            'movementPoint' => ['value' => 0, 'min_value' => 0, 'max_value' => null],
            'moralPoint' => ['value' => 0, 'min_value' => 0, 'max_value' => null],
            'percentageInjury' => ['value' => 0, 'min_value' => 0, 'max_value' => 100],
            'percentageDirtiness' => ['value' => 0, 'min_value' => 0, 'max_value' => 100],
            'percentageSuccess' => ['value' => 100, 'min_value' => 1, 'max_value' => 100],
            'percentageCritical' => ['value' => 0, 'min_value' => 0, 'max_value' => 100],
        ],
        [
            'name' => 'consume',
            'action_name' => 'consume',
            'types' => [],
            'target' => null,
            'scope' => 'current',
            'visibilities' => ['success' => 'secret', 'fail' => 'private'],
            'actionPoint' => ['value' => 0, 'min_value' => 0, 'max_value' => null],
            'movementPoint' => ['value' => 0, 'min_value' => 0, 'max_value' => null],
            'moralPoint' => ['value' => 0, 'min_value' => 0, 'max_value' => null],
            'percentageInjury' => ['value' => 0, 'min_value' => 0, 'max_value' => 100],
            'percentageDirtiness' => ['value' => 15, 'min_value' => 0, 'max_value' => 100],
            'percentageSuccess' => ['value' => 100, 'min_value' => 1, 'max_value' => 100],
            'percentageCritical' => ['value' => 0, 'min_value' => 0, 'max_value' => 100],
        ],
        [
            'name' => 'consume_drug',
            'action_name' => 'consume_drug',
            'types' => [],
            'target' => null,
            'scope' => 'current',
            'visibilities' => ['success' => 'secret', 'fail' => 'private'],
            'actionPoint' => ['value' => 0, 'min_value' => 0, 'max_value' => null],
            'movementPoint' => ['value' => 0, 'min_value' => 0, 'max_value' => null],
            'moralPoint' => ['value' => 0, 'min_value' => 0, 'max_value' => null],
            'percentageInjury' => ['value' => 0, 'min_value' => 0, 'max_value' => 100],
            'percentageDirtiness' => ['value' => 15, 'min_value' => 0, 'max_value' => 100],
            'percentageSuccess' => ['value' => 100, 'min_value' => 1, 'max_value' => 100],
            'percentageCritical' => ['value' => 0, 'min_value' => 0, 'max_value' => 100],
        ],
        [
            'name' => 'build',
            'action_name' => 'build',
            'types' => [],
            'target' => null,
            'scope' => 'current',
            'visibilities' => ['success' => 'public', 'fail' => 'private'],
            'actionPoint' => ['value' => 3, 'min_value' => 0, 'max_value' => null],
            'movementPoint' => ['value' => 0, 'min_value' => 0, 'max_value' => null],
            'moralPoint' => ['value' => 0, 'min_value' => 0, 'max_value' => null],
            'percentageInjury' => ['value' => 5, 'min_value' => 0, 'max_value' => 100],
            'percentageDirtiness' => ['value' => 25, 'min_value' => 0, 'max_value' => 100],
            'percentageSuccess' => ['value' => 100, 'min_value' => 1, 'max_value' => 100],
            'percentageCritical' => ['value' => 0, 'min_value' => 0, 'max_value' => 100],
        ],
        [
            'name' => 'read_book',
            'action_name' => 'read_book',
            'types' => [],
            'target' => null,
            'scope' => 'current',
            'visibilities' => ['success' => 'public', 'fail' => 'private'],
            'actionPoint' => ['value' => 2, 'min_value' => 0, 'max_value' => null],
            'movementPoint' => ['value' => 0, 'min_value' => 0, 'max_value' => null],
            'moralPoint' => ['value' => 0, 'min_value' => 0, 'max_value' => null],
            'percentageInjury' => ['value' => 0, 'min_value' => 0, 'max_value' => 100],
            'percentageDirtiness' => ['value' => 0, 'min_value' => 0, 'max_value' => 100],
            'percentageSuccess' => ['value' => 100, 'min_value' => 1, 'max_value' => 100],
            'percentageCritical' => ['value' => 0, 'min_value' => 0, 'max_value' => 100],
        ],
        [
            'name' => 'read_document',
            'action_name' => 'read_document',
            'types' => [],
            'target' => null,
            'scope' => 'current',
            'visibilities' => ['success' => 'public', 'fail' => 'private'],
            'actionPoint' => ['value' => 0, 'min_value' => 0, 'max_value' => null],
            'movementPoint' => ['value' => 0, 'min_value' => 0, 'max_value' => null],
            'moralPoint' => ['value' => 0, 'min_value' => 0, 'max_value' => null],
            'percentageInjury' => ['value' => 0, 'min_value' => 0, 'max_value' => 100],
            'percentageDirtiness' => ['value' => 0, 'min_value' => 0, 'max_value' => 100],
            'percentageSuccess' => ['value' => 100, 'min_value' => 1, 'max_value' => 100],
            'percentageCritical' => ['value' => 0, 'min_value' => 0, 'max_value' => 100],
        ],
        [
            'name' => 'attack',
            'action_name' => 'attack',
            'types' => ['action_aggressive', ActionTypeEnum::ACTION_ATTACK],
            'target' => null,
            'scope' => 'other_player',
            'visibilities' => ['success' => 'public', 'fail' => 'public', 'critical_success' => 'public', 'critical_fail' => 'public', 'one_shot' => 'public'],
            'actionPoint' => ['value' => 1, 'min_value' => 0, 'max_value' => null],
            'movementPoint' => ['value' => 0, 'min_value' => 0, 'max_value' => null],
            'moralPoint' => ['value' => 0, 'min_value' => 0, 'max_value' => null],
            'percentageInjury' => ['value' => 0, 'min_value' => 0, 'max_value' => 100],
            'percentageDirtiness' => ['value' => 15, 'min_value' => 0, 'max_value' => 100],
            'percentageSuccess' => ['value' => 60, 'min_value' => 1, 'max_value' => 99],
            'percentageCritical' => ['value' => 0, 'min_value' => 0, 'max_value' => 100],
        ],
        [
            'name' => 'extinguish',
            'action_name' => 'extinguish',
            'types' => [],
            'target' => null,
            'scope' => 'current',
            'visibilities' => ['success' => 'public', 'fail' => 'private'],
            'actionPoint' => ['value' => 1, 'min_value' => 0, 'max_value' => null],
            'movementPoint' => ['value' => 0, 'min_value' => 0, 'max_value' => null],
            'moralPoint' => ['value' => 0, 'min_value' => 0, 'max_value' => null],
            'percentageInjury' => ['value' => 1, 'min_value' => 0, 'max_value' => 100],
            'percentageDirtiness' => ['value' => 0, 'min_value' => 0, 'max_value' => 100],
            'percentageSuccess' => ['value' => 50, 'min_value' => 1, 'max_value' => 99],
            'percentageCritical' => ['value' => 0, 'min_value' => 0, 'max_value' => 100],
        ],
        [
            'name' => 'try_kube',
            'action_name' => 'try_kube',
            'types' => [],
            'target' => null,
            'scope' => 'current',
            'visibilities' => ['success' => 'public', 'fail' => 'private'],
            'actionPoint' => ['value' => 1, 'min_value' => 0, 'max_value' => null],
            'movementPoint' => ['value' => 0, 'min_value' => 0, 'max_value' => null],
            'moralPoint' => ['value' => 0, 'min_value' => 0, 'max_value' => null],
            'percentageInjury' => ['value' => 0, 'min_value' => 0, 'max_value' => 100],
            'percentageDirtiness' => ['value' => 0, 'min_value' => 0, 'max_value' => 100],
            'percentageSuccess' => ['value' => 100, 'min_value' => 1, 'max_value' => 100],
            'percentageCritical' => ['value' => 0, 'min_value' => 0, 'max_value' => 100],
        ],
        [
            'name' => 'open',
            'action_name' => 'open',
            'types' => [],
            'target' => null,
            'scope' => 'current',
            'visibilities' => ['success' => 'public', 'fail' => 'private'],
            'actionPoint' => ['value' => 1, 'min_value' => 0, 'max_value' => null],
            'movementPoint' => ['value' => 0, 'min_value' => 0, 'max_value' => null],
            'moralPoint' => ['value' => 0, 'min_value' => 0, 'max_value' => null],
            'percentageInjury' => ['value' => 1, 'min_value' => 0, 'max_value' => 100],
            'percentageDirtiness' => ['value' => 0, 'min_value' => 0, 'max_value' => 100],
            'percentageSuccess' => ['value' => 100, 'min_value' => 1, 'max_value' => 100],
            'percentageCritical' => ['value' => 0, 'min_value' => 0, 'max_value' => 100],
        ],
        [
            'name' => 'cure',
            'action_name' => 'cure',
            'types' => [],
            'target' => null,
            'scope' => 'other_player',
            'visibilities' => ['success' => 'public', 'fail' => 'private'],
            'actionPoint' => ['value' => 1, 'min_value' => 0, 'max_value' => null],
            'movementPoint' => ['value' => 0, 'min_value' => 0, 'max_value' => null],
            'moralPoint' => ['value' => 0, 'min_value' => 0, 'max_value' => null],
            'percentageInjury' => ['value' => 0, 'min_value' => 0, 'max_value' => 100],
            'percentageDirtiness' => ['value' => 0, 'min_value' => 0, 'max_value' => 100],
            'percentageSuccess' => ['value' => 100, 'min_value' => 1, 'max_value' => 100],
            'percentageCritical' => ['value' => 0, 'min_value' => 0, 'max_value' => 100],
        ],
        [
            'name' => 'use_bandage',
            'action_name' => 'use_bandage',
            'types' => [],
            'target' => null,
            'scope' => 'current',
            'visibilities' => ['success' => 'private', 'fail' => 'private'],
            'actionPoint' => ['value' => 1, 'min_value' => 0, 'max_value' => null],
            'movementPoint' => ['value' => 0, 'min_value' => 0, 'max_value' => null],
            'moralPoint' => ['value' => 0, 'min_value' => 0, 'max_value' => null],
            'percentageInjury' => ['value' => 0, 'min_value' => 0, 'max_value' => 100],
            'percentageDirtiness' => ['value' => 5, 'min_value' => 0, 'max_value' => 100],
            'percentageSuccess' => ['value' => 100, 'min_value' => 1, 'max_value' => 100],
            'percentageCritical' => ['value' => 0, 'min_value' => 0, 'max_value' => 100],
        ],
        [
            'name' => 'express_cook',
            'action_name' => 'express_cook',
            'types' => [],
            'target' => 'Mush\\Equipment\\Entity\\GameItem',
            'scope' => 'room',
            'visibilities' => ['success' => 'public', 'fail' => 'private'],
            'actionPoint' => ['value' => 0, 'min_value' => 0, 'max_value' => null],
            'movementPoint' => ['value' => 0, 'min_value' => 0, 'max_value' => null],
            'moralPoint' => ['value' => 0, 'min_value' => 0, 'max_value' => null],
            'percentageInjury' => ['value' => 0, 'min_value' => 0, 'max_value' => 100],
            'percentageDirtiness' => ['value' => 20, 'min_value' => 0, 'max_value' => 100],
            'percentageSuccess' => ['value' => 100, 'min_value' => 1, 'max_value' => 100],
            'percentageCritical' => ['value' => 0, 'min_value' => 0, 'max_value' => 100],
        ],
        [
            'name' => 'cook',
            'action_name' => 'cook',
            'types' => [],
            'target' => 'Mush\\Equipment\\Entity\\GameItem',
            'scope' => 'room',
            'visibilities' => ['success' => 'public', 'fail' => 'private'],
            'actionPoint' => ['value' => 1, 'min_value' => 0, 'max_value' => null],
            'movementPoint' => ['value' => 0, 'min_value' => 0, 'max_value' => null],
            'moralPoint' => ['value' => 0, 'min_value' => 0, 'max_value' => null],
            'percentageInjury' => ['value' => 0, 'min_value' => 0, 'max_value' => 100],
            'percentageDirtiness' => ['value' => 20, 'min_value' => 0, 'max_value' => 100],
            'percentageSuccess' => ['value' => 100, 'min_value' => 1, 'max_value' => 100],
            'percentageCritical' => ['value' => 0, 'min_value' => 0, 'max_value' => 100],
        ],
        [
            'name' => 'self_heal',
            'action_name' => 'self_heal',
            'types' => [],
            'target' => null,
            'scope' => 'self',
            'visibilities' => ['success' => 'private', 'fail' => 'private'],
            'actionPoint' => ['value' => 3, 'min_value' => 0, 'max_value' => null],
            'movementPoint' => ['value' => 0, 'min_value' => 0, 'max_value' => null],
            'moralPoint' => ['value' => 0, 'min_value' => 0, 'max_value' => null],
            'percentageInjury' => ['value' => 0, 'min_value' => 0, 'max_value' => 100],
            'percentageDirtiness' => ['value' => 0, 'min_value' => 0, 'max_value' => 100],
            'percentageSuccess' => ['value' => 100, 'min_value' => 1, 'max_value' => 100],
            'percentageCritical' => ['value' => 0, 'min_value' => 0, 'max_value' => 100],
        ],
        [
            'name' => 'heal',
            'action_name' => 'heal',
            'types' => [],
            'target' => null,
            'scope' => 'other_player',
            'visibilities' => ['success' => 'public', 'fail' => 'private'],
            'actionPoint' => ['value' => 2, 'min_value' => 0, 'max_value' => null],
            'movementPoint' => ['value' => 0, 'min_value' => 0, 'max_value' => null],
            'moralPoint' => ['value' => 0, 'min_value' => 0, 'max_value' => null],
            'percentageInjury' => ['value' => 0, 'min_value' => 0, 'max_value' => 100],
            'percentageDirtiness' => ['value' => 0, 'min_value' => 0, 'max_value' => 100],
            'percentageSuccess' => ['value' => 100, 'min_value' => 1, 'max_value' => 100],
            'percentageCritical' => ['value' => 0, 'min_value' => 0, 'max_value' => 100],
        ],
        [
            'name' => 'comfort',
            'action_name' => 'comfort',
            'types' => ['action_spoken'],
            'target' => null,
            'scope' => 'other_player',
            'visibilities' => ['success' => 'public', 'fail' => 'private'],
            'actionPoint' => ['value' => 1, 'min_value' => 0, 'max_value' => null],
            'movementPoint' => ['value' => 0, 'min_value' => 0, 'max_value' => null],
            'moralPoint' => ['value' => 0, 'min_value' => 0, 'max_value' => null],
            'percentageInjury' => ['value' => 0, 'min_value' => 0, 'max_value' => 100],
            'percentageDirtiness' => ['value' => 0, 'min_value' => 0, 'max_value' => 100],
            'percentageSuccess' => ['value' => 100, 'min_value' => 1, 'max_value' => 100],
            'percentageCritical' => ['value' => 0, 'min_value' => 0, 'max_value' => 100],
        ],
        [
            'name' => 'ultraheal',
            'action_name' => 'ultraheal',
            'types' => [],
            'target' => null,
            'scope' => 'current',
            'visibilities' => ['success' => 'public', 'fail' => 'private'],
            'actionPoint' => ['value' => 0, 'min_value' => 0, 'max_value' => null],
            'movementPoint' => ['value' => 0, 'min_value' => 0, 'max_value' => null],
            'moralPoint' => ['value' => 0, 'min_value' => 0, 'max_value' => null],
            'percentageInjury' => ['value' => 0, 'min_value' => 0, 'max_value' => 100],
            'percentageDirtiness' => ['value' => 0, 'min_value' => 0, 'max_value' => 100],
            'percentageSuccess' => ['value' => 100, 'min_value' => 1, 'max_value' => 100],
            'percentageCritical' => ['value' => 0, 'min_value' => 0, 'max_value' => 100],
        ],
        [
            'name' => 'write',
            'action_name' => 'write',
            'types' => [],
            'target' => null,
            'scope' => 'current',
            'visibilities' => ['success' => 'public', 'fail' => 'private'],
            'actionPoint' => ['value' => 0, 'min_value' => 0, 'max_value' => null],
            'movementPoint' => ['value' => 0, 'min_value' => 0, 'max_value' => null],
            'moralPoint' => ['value' => 0, 'min_value' => 0, 'max_value' => null],
            'percentageInjury' => ['value' => 0, 'min_value' => 0, 'max_value' => 100],
            'percentageDirtiness' => ['value' => 0, 'min_value' => 0, 'max_value' => 100],
            'percentageSuccess' => ['value' => 100, 'min_value' => 1, 'max_value' => 100],
            'percentageCritical' => ['value' => 0, 'min_value' => 0, 'max_value' => 100],
        ],
        [
            'name' => 'hyperfreeze',
            'action_name' => 'hyperfreeze',
            'types' => [],
            'target' => 'Mush\\Equipment\\Entity\\GameItem',
            'scope' => 'room',
            'visibilities' => ['success' => 'private', 'fail' => 'private'],
            'actionPoint' => ['value' => 1, 'min_value' => 0, 'max_value' => null],
            'movementPoint' => ['value' => 0, 'min_value' => 0, 'max_value' => null],
            'moralPoint' => ['value' => 0, 'min_value' => 0, 'max_value' => null],
            'percentageInjury' => ['value' => 0, 'min_value' => 0, 'max_value' => 100],
            'percentageDirtiness' => ['value' => 0, 'min_value' => 0, 'max_value' => 100],
            'percentageSuccess' => ['value' => 100, 'min_value' => 1, 'max_value' => 100],
            'percentageCritical' => ['value' => 0, 'min_value' => 0, 'max_value' => 100],
        ],
        [
            'name' => 'gag',
            'action_name' => 'gag',
            'types' => [],
            'target' => null,
            'scope' => 'other_player',
            'visibilities' => ['success' => 'public', 'fail' => 'private'],
            'actionPoint' => ['value' => 1, 'min_value' => 0, 'max_value' => null],
            'movementPoint' => ['value' => 0, 'min_value' => 0, 'max_value' => null],
            'moralPoint' => ['value' => 0, 'min_value' => 0, 'max_value' => null],
            'percentageInjury' => ['value' => 0, 'min_value' => 0, 'max_value' => 100],
            'percentageDirtiness' => ['value' => 0, 'min_value' => 0, 'max_value' => 100],
            'percentageSuccess' => ['value' => 100, 'min_value' => 1, 'max_value' => 100],
            'percentageCritical' => ['value' => 0, 'min_value' => 0, 'max_value' => 100],
        ],
        [
            'name' => 'ungag',
            'action_name' => 'ungag',
            'types' => [],
            'target' => null,
            'scope' => 'self',
            'visibilities' => ['success' => 'public', 'fail' => 'private'],
            'actionPoint' => ['value' => 1, 'min_value' => 0, 'max_value' => null],
            'movementPoint' => ['value' => 0, 'min_value' => 0, 'max_value' => null],
            'moralPoint' => ['value' => 0, 'min_value' => 0, 'max_value' => null],
            'percentageInjury' => ['value' => 0, 'min_value' => 0, 'max_value' => 100],
            'percentageDirtiness' => ['value' => 0, 'min_value' => 0, 'max_value' => 100],
            'percentageSuccess' => ['value' => 100, 'min_value' => 1, 'max_value' => 100],
            'percentageCritical' => ['value' => 0, 'min_value' => 0, 'max_value' => 100],
        ],
        [
            'name' => 'shower',
            'action_name' => 'shower',
            'types' => [],
            'target' => null,
            'scope' => 'current',
            'visibilities' => ['success' => 'private', 'fail' => 'private'],
            'actionPoint' => ['value' => 2, 'min_value' => 0, 'max_value' => null],
            'movementPoint' => ['value' => 0, 'min_value' => 0, 'max_value' => null],
            'moralPoint' => ['value' => 0, 'min_value' => 0, 'max_value' => null],
            'percentageInjury' => ['value' => 2, 'min_value' => 0, 'max_value' => 100],
            'percentageDirtiness' => ['value' => 0, 'min_value' => 0, 'max_value' => 100],
            'percentageSuccess' => ['value' => 100, 'min_value' => 1, 'max_value' => 100],
            'percentageCritical' => ['value' => 0, 'min_value' => 0, 'max_value' => 100],
        ],
        [
            'name' => 'wash_in_sink',
            'action_name' => 'wash_in_sink',
            'types' => [],
            'target' => null,
            'scope' => 'current',
            'visibilities' => ['success' => 'private', 'fail' => 'private'],
            'actionPoint' => ['value' => 3, 'min_value' => 0, 'max_value' => null],
            'movementPoint' => ['value' => 0, 'min_value' => 0, 'max_value' => null],
            'moralPoint' => ['value' => 0, 'min_value' => 0, 'max_value' => null],
            'percentageInjury' => ['value' => 0, 'min_value' => 0, 'max_value' => 100],
            'percentageDirtiness' => ['value' => 0, 'min_value' => 0, 'max_value' => 100],
            'percentageSuccess' => ['value' => 100, 'min_value' => 1, 'max_value' => 100],
            'percentageCritical' => ['value' => 0, 'min_value' => 0, 'max_value' => 100],
        ],
        [
            'name' => 'insert_fuel',
            'action_name' => 'insert_fuel',
            'types' => [],
            'target' => 'Mush\\Equipment\\Entity\\GameItem',
            'scope' => 'room',
            'visibilities' => ['success' => 'public', 'fail' => 'private'],
            'actionPoint' => ['value' => 0, 'min_value' => 0, 'max_value' => null],
            'movementPoint' => ['value' => 0, 'min_value' => 0, 'max_value' => null],
            'moralPoint' => ['value' => 0, 'min_value' => 0, 'max_value' => null],
            'percentageInjury' => ['value' => 1, 'min_value' => 0, 'max_value' => 100],
            'percentageDirtiness' => ['value' => 10, 'min_value' => 0, 'max_value' => 100],
            'percentageSuccess' => ['value' => 100, 'min_value' => 1, 'max_value' => 100],
            'percentageCritical' => ['value' => 0, 'min_value' => 0, 'max_value' => 100],
        ],
        [
            'name' => 'retrieve_fuel',
            'action_name' => 'retrieve_fuel',
            'types' => [],
            'target' => null,
            'scope' => 'current',
            'visibilities' => ['success' => 'secret', 'fail' => 'private'],
            'actionPoint' => ['value' => 0, 'min_value' => 0, 'max_value' => null],
            'movementPoint' => ['value' => 0, 'min_value' => 0, 'max_value' => null],
            'moralPoint' => ['value' => 0, 'min_value' => 0, 'max_value' => null],
            'percentageInjury' => ['value' => 1, 'min_value' => 0, 'max_value' => 100],
            'percentageDirtiness' => ['value' => 15, 'min_value' => 0, 'max_value' => 100],
            'percentageSuccess' => ['value' => 100, 'min_value' => 1, 'max_value' => 100],
            'percentageCritical' => ['value' => 0, 'min_value' => 0, 'max_value' => 100],
        ],
        [
            'name' => 'insert_oxygen',
            'action_name' => 'insert_oxygen',
            'types' => [],
            'target' => 'Mush\\Equipment\\Entity\\GameItem',
            'scope' => 'room',
            'visibilities' => ['success' => 'private', 'fail' => 'private'],
            'actionPoint' => ['value' => 0, 'min_value' => 0, 'max_value' => null],
            'movementPoint' => ['value' => 0, 'min_value' => 0, 'max_value' => null],
            'moralPoint' => ['value' => 0, 'min_value' => 0, 'max_value' => null],
            'percentageInjury' => ['value' => 1, 'min_value' => 0, 'max_value' => 100],
            'percentageDirtiness' => ['value' => 0, 'min_value' => 0, 'max_value' => 100],
            'percentageSuccess' => ['value' => 100, 'min_value' => 1, 'max_value' => 100],
            'percentageCritical' => ['value' => 0, 'min_value' => 0, 'max_value' => 100],
        ],
        [
            'name' => 'retrieve_oxygen',
            'action_name' => 'retrieve_oxygen',
            'types' => [],
            'target' => null,
            'scope' => 'current',
            'visibilities' => ['success' => 'secret', 'fail' => 'private'],
            'actionPoint' => ['value' => 0, 'min_value' => 0, 'max_value' => null],
            'movementPoint' => ['value' => 0, 'min_value' => 0, 'max_value' => null],
            'moralPoint' => ['value' => 0, 'min_value' => 0, 'max_value' => null],
            'percentageInjury' => ['value' => 1, 'min_value' => 0, 'max_value' => 100],
            'percentageDirtiness' => ['value' => 0, 'min_value' => 0, 'max_value' => 100],
            'percentageSuccess' => ['value' => 100, 'min_value' => 1, 'max_value' => 100],
            'percentageCritical' => ['value' => 0, 'min_value' => 0, 'max_value' => 100],
        ],
        [
            'name' => 'strengthen_hull',
            'action_name' => 'strengthen_hull',
            'types' => ['action_technician'],
            'target' => 'Mush\\Equipment\\Entity\\GameItem',
            'scope' => 'current',
            'visibilities' => ['success' => 'public', 'fail' => 'private'],
            'actionPoint' => ['value' => 1, 'min_value' => 0, 'max_value' => null],
            'movementPoint' => ['value' => 0, 'min_value' => 0, 'max_value' => null],
            'moralPoint' => ['value' => 0, 'min_value' => 0, 'max_value' => null],
            'percentageInjury' => ['value' => 5, 'min_value' => 0, 'max_value' => 100],
            'percentageDirtiness' => ['value' => 50, 'min_value' => 0, 'max_value' => 100],
            'percentageSuccess' => ['value' => 25, 'min_value' => 1, 'max_value' => 99],
            'percentageCritical' => ['value' => 0, 'min_value' => 0, 'max_value' => 100],
        ],
        [
            'name' => 'lie_down',
            'action_name' => 'lie_down',
            'types' => [],
            'target' => null,
            'scope' => 'current',
            'visibilities' => ['success' => 'public', 'fail' => 'private'],
            'actionPoint' => ['value' => 0, 'min_value' => 0, 'max_value' => null],
            'movementPoint' => ['value' => 0, 'min_value' => 0, 'max_value' => null],
            'moralPoint' => ['value' => 0, 'min_value' => 0, 'max_value' => null],
            'percentageInjury' => ['value' => 0, 'min_value' => 0, 'max_value' => 100],
            'percentageDirtiness' => ['value' => 0, 'min_value' => 0, 'max_value' => 100],
            'percentageSuccess' => ['value' => 100, 'min_value' => 1, 'max_value' => 100],
            'percentageCritical' => ['value' => 0, 'min_value' => 0, 'max_value' => 100],
        ],
        [
            'name' => 'get_up',
            'action_name' => 'get_up',
            'types' => [],
            'target' => null,
            'scope' => 'self',
            'visibilities' => ['success' => 'public', 'fail' => 'private'],
            'actionPoint' => ['value' => 0, 'min_value' => 0, 'max_value' => null],
            'movementPoint' => ['value' => 0, 'min_value' => 0, 'max_value' => null],
            'moralPoint' => ['value' => 0, 'min_value' => 0, 'max_value' => null],
            'percentageInjury' => ['value' => 0, 'min_value' => 0, 'max_value' => 100],
            'percentageDirtiness' => ['value' => 0, 'min_value' => 0, 'max_value' => 100],
            'percentageSuccess' => ['value' => 100, 'min_value' => 1, 'max_value' => 100],
            'percentageCritical' => ['value' => 0, 'min_value' => 0, 'max_value' => 100],
        ],
        [
            'name' => 'coffee',
            'action_name' => 'coffee',
            'types' => [],
            'target' => null,
            'scope' => 'current',
            'visibilities' => ['success' => 'public', 'fail' => 'private'],
            'actionPoint' => ['value' => 0, 'min_value' => 0, 'max_value' => null],
            'movementPoint' => ['value' => 0, 'min_value' => 0, 'max_value' => null],
            'moralPoint' => ['value' => 0, 'min_value' => 0, 'max_value' => null],
            'percentageInjury' => ['value' => 0, 'min_value' => 0, 'max_value' => 100],
            'percentageDirtiness' => ['value' => 3, 'min_value' => 0, 'max_value' => 100],
            'percentageSuccess' => ['value' => 100, 'min_value' => 1, 'max_value' => 100],
            'percentageCritical' => ['value' => 0, 'min_value' => 0, 'max_value' => 100],
        ],
        [
            'name' => 'dispense',
            'action_name' => 'dispense',
            'types' => [],
            'target' => null,
            'scope' => 'current',
            'visibilities' => ['success' => 'public', 'fail' => 'private'],
            'actionPoint' => ['value' => 0, 'min_value' => 0, 'max_value' => null],
            'movementPoint' => ['value' => 0, 'min_value' => 0, 'max_value' => null],
            'moralPoint' => ['value' => 0, 'min_value' => 0, 'max_value' => null],
            'percentageInjury' => ['value' => 0, 'min_value' => 0, 'max_value' => 100],
            'percentageDirtiness' => ['value' => 0, 'min_value' => 0, 'max_value' => 100],
            'percentageSuccess' => ['value' => 100, 'min_value' => 1, 'max_value' => 100],
            'percentageCritical' => ['value' => 0, 'min_value' => 0, 'max_value' => 100],
        ],
        [
            'name' => 'transplant',
            'action_name' => 'transplant',
            'types' => [],
            'target' => null,
            'scope' => 'current',
            'visibilities' => ['success' => 'public', 'fail' => 'private'],
            'actionPoint' => ['value' => 2, 'min_value' => 0, 'max_value' => null],
            'movementPoint' => ['value' => 0, 'min_value' => 0, 'max_value' => null],
            'moralPoint' => ['value' => 0, 'min_value' => 0, 'max_value' => null],
            'percentageInjury' => ['value' => 0, 'min_value' => 0, 'max_value' => 100],
            'percentageDirtiness' => ['value' => 15, 'min_value' => 0, 'max_value' => 100],
            'percentageSuccess' => ['value' => 100, 'min_value' => 1, 'max_value' => 100],
            'percentageCritical' => ['value' => 0, 'min_value' => 0, 'max_value' => 100],
        ],
        [
            'name' => 'treat_plant',
            'action_name' => 'treat_plant',
            'types' => [],
            'target' => null,
            'scope' => 'current',
            'visibilities' => ['success' => 'private', 'fail' => 'private'],
            'actionPoint' => ['value' => 2, 'min_value' => 0, 'max_value' => null],
            'movementPoint' => ['value' => 0, 'min_value' => 0, 'max_value' => null],
            'moralPoint' => ['value' => 0, 'min_value' => 0, 'max_value' => null],
            'percentageInjury' => ['value' => 1, 'min_value' => 0, 'max_value' => 100],
            'percentageDirtiness' => ['value' => 15, 'min_value' => 0, 'max_value' => 100],
            'percentageSuccess' => ['value' => 100, 'min_value' => 1, 'max_value' => 100],
            'percentageCritical' => ['value' => 0, 'min_value' => 0, 'max_value' => 100],
        ],
        [
            'name' => 'water_plant',
            'action_name' => 'water_plant',
            'types' => [],
            'target' => null,
            'scope' => 'current',
            'visibilities' => ['success' => 'private', 'fail' => 'private'],
            'actionPoint' => ['value' => 1, 'min_value' => 0, 'max_value' => null],
            'movementPoint' => ['value' => 0, 'min_value' => 0, 'max_value' => null],
            'moralPoint' => ['value' => 0, 'min_value' => 0, 'max_value' => null],
            'percentageInjury' => ['value' => 0, 'min_value' => 0, 'max_value' => 100],
            'percentageDirtiness' => ['value' => 15, 'min_value' => 0, 'max_value' => 100],
            'percentageSuccess' => ['value' => 100, 'min_value' => 1, 'max_value' => 100],
            'percentageCritical' => ['value' => 0, 'min_value' => 0, 'max_value' => 100],
        ],
        [
            'name' => 'report_equipment',
            'action_name' => 'report_equipment',
            'types' => [],
            'target' => null,
            'scope' => 'current',
            'visibilities' => ['success' => 'public', 'fail' => 'private'],
            'actionPoint' => ['value' => 0, 'min_value' => 0, 'max_value' => null],
            'movementPoint' => ['value' => 0, 'min_value' => 0, 'max_value' => null],
            'moralPoint' => ['value' => 0, 'min_value' => 0, 'max_value' => null],
            'percentageInjury' => ['value' => 0, 'min_value' => 0, 'max_value' => 100],
            'percentageDirtiness' => ['value' => 0, 'min_value' => 0, 'max_value' => 100],
            'percentageSuccess' => ['value' => 100, 'min_value' => 1, 'max_value' => 100],
            'percentageCritical' => ['value' => 0, 'min_value' => 0, 'max_value' => 100],
        ],
        [
            'name' => 'report_fire',
            'action_name' => 'report_fire',
            'types' => [],
            'target' => null,
            'scope' => 'self',
            'visibilities' => ['success' => 'public', 'fail' => 'private'],
            'actionPoint' => ['value' => 0, 'min_value' => 0, 'max_value' => null],
            'movementPoint' => ['value' => 0, 'min_value' => 0, 'max_value' => null],
            'moralPoint' => ['value' => 0, 'min_value' => 0, 'max_value' => null],
            'percentageInjury' => ['value' => 0, 'min_value' => 0, 'max_value' => 100],
            'percentageDirtiness' => ['value' => 0, 'min_value' => 0, 'max_value' => 100],
            'percentageSuccess' => ['value' => 100, 'min_value' => 1, 'max_value' => 100],
            'percentageCritical' => ['value' => 0, 'min_value' => 0, 'max_value' => 100],
        ],
        [
            'name' => 'install_camera',
            'action_name' => 'install_camera',
            'types' => [],
            'target' => null,
            'scope' => 'current',
            'visibilities' => ['success' => 'public', 'fail' => 'private'],
            'actionPoint' => ['value' => 2, 'min_value' => 0, 'max_value' => null],
            'movementPoint' => ['value' => 0, 'min_value' => 0, 'max_value' => null],
            'moralPoint' => ['value' => 0, 'min_value' => 0, 'max_value' => null],
            'percentageInjury' => ['value' => 0, 'min_value' => 0, 'max_value' => 100],
            'percentageDirtiness' => ['value' => 15, 'min_value' => 0, 'max_value' => 100],
            'percentageSuccess' => ['value' => 100, 'min_value' => 1, 'max_value' => 100],
            'percentageCritical' => ['value' => 0, 'min_value' => 0, 'max_value' => 100],
        ],
        [
            'name' => 'remove_camera',
            'action_name' => 'remove_camera',
            'types' => [],
            'target' => null,
            'scope' => 'current',
            'visibilities' => ['success' => 'public', 'fail' => 'private'],
            'actionPoint' => ['value' => 1, 'min_value' => 0, 'max_value' => null],
            'movementPoint' => ['value' => 0, 'min_value' => 0, 'max_value' => null],
            'moralPoint' => ['value' => 0, 'min_value' => 0, 'max_value' => null],
            'percentageInjury' => ['value' => 0, 'min_value' => 0, 'max_value' => 100],
            'percentageDirtiness' => ['value' => 5, 'min_value' => 0, 'max_value' => 100],
            'percentageSuccess' => ['value' => 100, 'min_value' => 1, 'max_value' => 100],
            'percentageCritical' => ['value' => 0, 'min_value' => 0, 'max_value' => 100],
        ],
        [
            'name' => 'examine',
            'action_name' => 'examine',
            'types' => [],
            'target' => null,
            'scope' => 'current',
            'visibilities' => ['success' => 'public', 'fail' => 'private'],
            'actionPoint' => ['value' => 0, 'min_value' => 0, 'max_value' => null],
            'movementPoint' => ['value' => 0, 'min_value' => 0, 'max_value' => null],
            'moralPoint' => ['value' => 0, 'min_value' => 0, 'max_value' => null],
            'percentageInjury' => ['value' => 0, 'min_value' => 0, 'max_value' => 100],
            'percentageDirtiness' => ['value' => 0, 'min_value' => 0, 'max_value' => 100],
            'percentageSuccess' => ['value' => 100, 'min_value' => 1, 'max_value' => 100],
            'percentageCritical' => ['value' => 0, 'min_value' => 0, 'max_value' => 100],
        ],
        [
            'name' => 'check_spore_level',
            'action_name' => 'check_spore_level',
            'types' => [],
            'target' => null,
            'scope' => 'current',
            'visibilities' => ['success' => 'private', 'fail' => 'private'],
            'actionPoint' => ['value' => 0, 'min_value' => 0, 'max_value' => null],
            'movementPoint' => ['value' => 0, 'min_value' => 0, 'max_value' => null],
            'moralPoint' => ['value' => 0, 'min_value' => 0, 'max_value' => null],
            'percentageInjury' => ['value' => 0, 'min_value' => 0, 'max_value' => 100],
            'percentageDirtiness' => ['value' => 0, 'min_value' => 0, 'max_value' => 100],
            'percentageSuccess' => ['value' => 100, 'min_value' => 1, 'max_value' => 100],
            'percentageCritical' => ['value' => 0, 'min_value' => 0, 'max_value' => 100],
        ],
        [
            'name' => 'flirt',
            'action_name' => 'flirt',
            'types' => [],
            'target' => null,
            'scope' => 'other_player',
            'visibilities' => ['success' => 'public', 'fail' => 'private'],
            'actionPoint' => ['value' => 1, 'min_value' => 0, 'max_value' => null],
            'movementPoint' => ['value' => 0, 'min_value' => 0, 'max_value' => null],
            'moralPoint' => ['value' => 0, 'min_value' => 0, 'max_value' => null],
            'percentageInjury' => ['value' => 0, 'min_value' => 0, 'max_value' => 100],
            'percentageDirtiness' => ['value' => 0, 'min_value' => 0, 'max_value' => 100],
            'percentageSuccess' => ['value' => 100, 'min_value' => 1, 'max_value' => 100],
            'percentageCritical' => ['value' => 0, 'min_value' => 0, 'max_value' => 100],
        ],
        [
            'name' => 'do_the_thing',
            'action_name' => 'do_the_thing',
            'types' => [],
            'target' => null,
            'scope' => 'other_player',
            'visibilities' => ['success' => 'public', 'fail' => 'private'],
            'actionPoint' => ['value' => 1, 'min_value' => 0, 'max_value' => null],
            'movementPoint' => ['value' => 0, 'min_value' => 0, 'max_value' => null],
            'moralPoint' => ['value' => 0, 'min_value' => 0, 'max_value' => null],
            'percentageInjury' => ['value' => 0, 'min_value' => 0, 'max_value' => 100],
            'percentageDirtiness' => ['value' => 0, 'min_value' => 0, 'max_value' => 100],
            'percentageSuccess' => ['value' => 100, 'min_value' => 1, 'max_value' => 100],
            'percentageCritical' => ['value' => 0, 'min_value' => 0, 'max_value' => 100],
        ],
        [
            'name' => 'remove_spore',
            'action_name' => 'remove_spore',
            'types' => [],
            'target' => null,
            'scope' => 'current',
            'visibilities' => ['success' => 'private', 'fail' => 'private'],
            'actionPoint' => ['value' => 1, 'min_value' => 0, 'max_value' => null],
            'movementPoint' => ['value' => 0, 'min_value' => 0, 'max_value' => null],
            'moralPoint' => ['value' => 0, 'min_value' => 0, 'max_value' => null],
            'percentageInjury' => ['value' => 0, 'min_value' => 0, 'max_value' => 100],
            'percentageDirtiness' => ['value' => 0, 'min_value' => 0, 'max_value' => 100],
            'percentageSuccess' => ['value' => 100, 'min_value' => 1, 'max_value' => 100],
            'percentageCritical' => ['value' => 0, 'min_value' => 0, 'max_value' => 100],
        ],
        [
            'name' => 'public_broadcast',
            'action_name' => 'public_broadcast',
            'types' => [],
            'target' => null,
            'scope' => 'current',
            'visibilities' => ['success' => 'public', 'fail' => 'private'],
            'actionPoint' => ['value' => 2, 'min_value' => 0, 'max_value' => null],
            'movementPoint' => ['value' => 0, 'min_value' => 0, 'max_value' => null],
            'moralPoint' => ['value' => 0, 'min_value' => 0, 'max_value' => null],
            'percentageInjury' => ['value' => 0, 'min_value' => 0, 'max_value' => 100],
            'percentageDirtiness' => ['value' => 0, 'min_value' => 0, 'max_value' => 100],
            'percentageSuccess' => ['value' => 100, 'min_value' => 1, 'max_value' => 100],
            'percentageCritical' => ['value' => 0, 'min_value' => 0, 'max_value' => 100],
        ],
        [
            'name' => 'extinguish_manually',
            'action_name' => 'extinguish_manually',
            'types' => [],
            'target' => null,
            'scope' => 'self',
            'visibilities' => ['success' => 'public', 'fail' => 'private'],
            'actionPoint' => ['value' => 1, 'min_value' => 0, 'max_value' => null],
            'movementPoint' => ['value' => 0, 'min_value' => 0, 'max_value' => null],
            'moralPoint' => ['value' => 0, 'min_value' => 0, 'max_value' => null],
            'percentageInjury' => ['value' => 5, 'min_value' => 0, 'max_value' => 100],
            'percentageDirtiness' => ['value' => 50, 'min_value' => 0, 'max_value' => 100],
            'percentageSuccess' => ['value' => 10, 'min_value' => 1, 'max_value' => 99],
            'percentageCritical' => ['value' => 0, 'min_value' => 0, 'max_value' => 100],
        ],
        [
            'name' => 'motivational_speech',
            'action_name' => 'motivational_speech',
            'types' => ['action_spoken'],
            'target' => null,
            'scope' => 'self',
            'visibilities' => ['success' => 'public', 'fail' => 'private'],
            'actionPoint' => ['value' => 2, 'min_value' => 0, 'max_value' => null],
            'movementPoint' => ['value' => 0, 'min_value' => 0, 'max_value' => null],
            'moralPoint' => ['value' => 0, 'min_value' => 0, 'max_value' => null],
            'percentageInjury' => ['value' => 0, 'min_value' => 0, 'max_value' => 100],
            'percentageDirtiness' => ['value' => 0, 'min_value' => 0, 'max_value' => 100],
            'percentageSuccess' => ['value' => 100, 'min_value' => 1, 'max_value' => 100],
            'percentageCritical' => ['value' => 0, 'min_value' => 0, 'max_value' => 100],
        ],
        [
            'name' => 'boring_speech',
            'action_name' => 'boring_speech',
            'types' => ['action_spoken'],
            'target' => null,
            'scope' => 'self',
            'visibilities' => ['success' => 'public', 'fail' => 'private'],
            'actionPoint' => ['value' => 2, 'min_value' => 0, 'max_value' => null],
            'movementPoint' => ['value' => 0, 'min_value' => 0, 'max_value' => null],
            'moralPoint' => ['value' => 0, 'min_value' => 0, 'max_value' => null],
            'percentageInjury' => ['value' => 0, 'min_value' => 0, 'max_value' => 100],
            'percentageDirtiness' => ['value' => 0, 'min_value' => 0, 'max_value' => 100],
            'percentageSuccess' => ['value' => 100, 'min_value' => 1, 'max_value' => 100],
            'percentageCritical' => ['value' => 0, 'min_value' => 0, 'max_value' => 100],
        ],
        [
            'name' => 'surgery',
            'action_name' => 'surgery',
            'types' => [],
            'target' => null,
            'scope' => 'other_player',
            'visibilities' => ['success' => 'public', 'fail' => 'public'],
            'actionPoint' => ['value' => 2, 'min_value' => 0, 'max_value' => null],
            'movementPoint' => ['value' => 0, 'min_value' => 0, 'max_value' => null],
            'moralPoint' => ['value' => 0, 'min_value' => 0, 'max_value' => null],
            'percentageInjury' => ['value' => 0, 'min_value' => 0, 'max_value' => 100],
            'percentageDirtiness' => ['value' => 80, 'min_value' => 0, 'max_value' => 100],
            'percentageSuccess' => ['value' => 100, 'min_value' => 1, 'max_value' => 100],
            'percentageCritical' => ['value' => 0, 'min_value' => 0, 'max_value' => 100],
        ],
        [
            'name' => 'self_surgery',
            'action_name' => 'self_surgery',
            'types' => [],
            'target' => null,
            'scope' => 'current',
            'visibilities' => ['success' => 'public', 'fail' => 'public'],
            'actionPoint' => ['value' => 4, 'min_value' => 0, 'max_value' => null],
            'movementPoint' => ['value' => 0, 'min_value' => 0, 'max_value' => null],
            'moralPoint' => ['value' => 0, 'min_value' => 0, 'max_value' => null],
            'percentageInjury' => ['value' => 0, 'min_value' => 0, 'max_value' => 100],
            'percentageDirtiness' => ['value' => 100, 'min_value' => 0, 'max_value' => 100],
            'percentageSuccess' => ['value' => 100, 'min_value' => 1, 'max_value' => 100],
            'percentageCritical' => ['value' => 0, 'min_value' => 0, 'max_value' => 100],
        ],
        [
            'name' => 'shoot',
            'action_name' => 'shoot',
            'types' => ['action_aggressive', 'action_shoot'],
            'target' => null,
            'scope' => 'other_player',
            'visibilities' => ['success' => 'public', 'fail' => 'public', 'critical_success' => 'public', 'critical_fail' => 'public', 'one_shot' => 'public'],
            'actionPoint' => ['value' => 1, 'min_value' => 0, 'max_value' => null],
            'movementPoint' => ['value' => 0, 'min_value' => 0, 'max_value' => null],
            'moralPoint' => ['value' => 0, 'min_value' => 0, 'max_value' => null],
            'percentageInjury' => ['value' => 0, 'min_value' => 0, 'max_value' => 100],
            'percentageDirtiness' => ['value' => 0, 'min_value' => 0, 'max_value' => 100],
            'percentageSuccess' => ['value' => 50, 'min_value' => 1, 'max_value' => 99],
            'percentageCritical' => ['value' => 0, 'min_value' => 0, 'max_value' => 100],
        ],
        [
            'name' => 'repair_percent_1',
            'action_name' => 'repair',
            'types' => ['action_technician'],
            'target' => null,
            'scope' => 'current',
            'visibilities' => ['success' => 'public', 'fail' => 'private'],
            'actionPoint' => ['value' => 1, 'min_value' => 0, 'max_value' => null],
            'movementPoint' => ['value' => 0, 'min_value' => 0, 'max_value' => null],
            'moralPoint' => ['value' => 0, 'min_value' => 0, 'max_value' => null],
            'percentageInjury' => ['value' => 4, 'min_value' => 0, 'max_value' => 100],
            'percentageDirtiness' => ['value' => 20, 'min_value' => 0, 'max_value' => 100],
            'percentageSuccess' => ['value' => 1, 'min_value' => 1, 'max_value' => 99],
            'percentageCritical' => ['value' => 0, 'min_value' => 0, 'max_value' => 100],
        ],
        [
            'name' => 'repair_percent_3',
            'action_name' => 'repair',
            'types' => ['action_technician'],
            'target' => null,
            'scope' => 'current',
            'visibilities' => ['success' => 'public', 'fail' => 'private'],
            'actionPoint' => ['value' => 1, 'min_value' => 0, 'max_value' => null],
            'movementPoint' => ['value' => 0, 'min_value' => 0, 'max_value' => null],
            'moralPoint' => ['value' => 0, 'min_value' => 0, 'max_value' => null],
            'percentageInjury' => ['value' => 4, 'min_value' => 0, 'max_value' => 100],
            'percentageDirtiness' => ['value' => 20, 'min_value' => 0, 'max_value' => 100],
            'percentageSuccess' => ['value' => 3, 'min_value' => 1, 'max_value' => 99],
            'percentageCritical' => ['value' => 0, 'min_value' => 0, 'max_value' => 100],
        ],
        [
            'name' => 'repair_percent_6',
            'action_name' => 'repair',
            'types' => ['action_technician'],
            'target' => null,
            'scope' => 'current',
            'visibilities' => ['success' => 'public', 'fail' => 'private'],
            'actionPoint' => ['value' => 1, 'min_value' => 0, 'max_value' => null],
            'movementPoint' => ['value' => 0, 'min_value' => 0, 'max_value' => null],
            'moralPoint' => ['value' => 0, 'min_value' => 0, 'max_value' => null],
            'percentageInjury' => ['value' => 4, 'min_value' => 0, 'max_value' => 100],
            'percentageDirtiness' => ['value' => 20, 'min_value' => 0, 'max_value' => 100],
            'percentageSuccess' => ['value' => 6, 'min_value' => 1, 'max_value' => 99],
            'percentageCritical' => ['value' => 0, 'min_value' => 0, 'max_value' => 100],
        ],
        [
            'name' => 'repair_percent_12',
            'action_name' => 'repair',
            'types' => ['action_technician'],
            'target' => null,
            'scope' => 'current',
            'visibilities' => ['success' => 'public', 'fail' => 'private'],
            'actionPoint' => ['value' => 1, 'min_value' => 0, 'max_value' => null],
            'movementPoint' => ['value' => 0, 'min_value' => 0, 'max_value' => null],
            'moralPoint' => ['value' => 0, 'min_value' => 0, 'max_value' => null],
            'percentageInjury' => ['value' => 4, 'min_value' => 0, 'max_value' => 100],
            'percentageDirtiness' => ['value' => 20, 'min_value' => 0, 'max_value' => 100],
            'percentageSuccess' => ['value' => 12, 'min_value' => 1, 'max_value' => 99],
            'percentageCritical' => ['value' => 0, 'min_value' => 0, 'max_value' => 100],
        ],
        [
            'name' => 'repair_percent_25',
            'action_name' => 'repair',
            'types' => ['action_technician'],
            'target' => null,
            'scope' => 'current',
            'visibilities' => ['success' => 'public', 'fail' => 'private'],
            'actionPoint' => ['value' => 1, 'min_value' => 0, 'max_value' => null],
            'movementPoint' => ['value' => 0, 'min_value' => 0, 'max_value' => null],
            'moralPoint' => ['value' => 0, 'min_value' => 0, 'max_value' => null],
            'percentageInjury' => ['value' => 4, 'min_value' => 0, 'max_value' => 100],
            'percentageDirtiness' => ['value' => 20, 'min_value' => 0, 'max_value' => 100],
            'percentageSuccess' => ['value' => 25, 'min_value' => 1, 'max_value' => 99],
            'percentageCritical' => ['value' => 0, 'min_value' => 0, 'max_value' => 100],
        ],
        [
            'name' => 'repair_percent_50',
            'action_name' => 'repair',
            'types' => ['action_technician'],
            'target' => null,
            'scope' => 'current',
            'visibilities' => ['success' => 'public', 'fail' => 'private'],
            'actionPoint' => ['value' => 1, 'min_value' => 0, 'max_value' => null],
            'movementPoint' => ['value' => 0, 'min_value' => 0, 'max_value' => null],
            'moralPoint' => ['value' => 0, 'min_value' => 0, 'max_value' => null],
            'percentageInjury' => ['value' => 4, 'min_value' => 0, 'max_value' => 100],
            'percentageDirtiness' => ['value' => 20, 'min_value' => 0, 'max_value' => 100],
            'percentageSuccess' => ['value' => 50, 'min_value' => 1, 'max_value' => 99],
            'percentageCritical' => ['value' => 0, 'min_value' => 0, 'max_value' => 100],
        ],
        [
            'name' => 'disassemble_percent_12_cost_3',
            'action_name' => 'disassemble',
            'types' => ['action_technician'],
            'target' => null,
            'scope' => 'current',
            'visibilities' => ['success' => 'public', 'fail' => 'private'],
            'actionPoint' => ['value' => 3, 'min_value' => 0, 'max_value' => null],
            'movementPoint' => ['value' => 0, 'min_value' => 0, 'max_value' => null],
            'moralPoint' => ['value' => 0, 'min_value' => 0, 'max_value' => null],
            'percentageInjury' => ['value' => 5, 'min_value' => 0, 'max_value' => 100],
            'percentageDirtiness' => ['value' => 25, 'min_value' => 0, 'max_value' => 100],
            'percentageSuccess' => ['value' => 12, 'min_value' => 1, 'max_value' => 99],
            'percentageCritical' => ['value' => 0, 'min_value' => 0, 'max_value' => 100],
        ],
        [
            'name' => 'disassemble_percent_25_cost_3',
            'action_name' => 'disassemble',
            'types' => ['action_technician'],
            'target' => null,
            'scope' => 'current',
            'visibilities' => ['success' => 'public', 'fail' => 'private'],
            'actionPoint' => ['value' => 3, 'min_value' => 0, 'max_value' => null],
            'movementPoint' => ['value' => 0, 'min_value' => 0, 'max_value' => null],
            'moralPoint' => ['value' => 0, 'min_value' => 0, 'max_value' => null],
            'percentageInjury' => ['value' => 5, 'min_value' => 0, 'max_value' => 100],
            'percentageDirtiness' => ['value' => 25, 'min_value' => 0, 'max_value' => 100],
            'percentageSuccess' => ['value' => 25, 'min_value' => 1, 'max_value' => 99],
            'percentageCritical' => ['value' => 0, 'min_value' => 0, 'max_value' => 100],
        ],
        [
            'name' => 'disassemble_percent_50_cost_3',
            'action_name' => 'disassemble',
            'types' => ['action_technician'],
            'target' => null,
            'scope' => 'current',
            'visibilities' => ['success' => 'public', 'fail' => 'private'],
            'actionPoint' => ['value' => 3, 'min_value' => 0, 'max_value' => null],
            'movementPoint' => ['value' => 0, 'min_value' => 0, 'max_value' => null],
            'moralPoint' => ['value' => 0, 'min_value' => 0, 'max_value' => null],
            'percentageInjury' => ['value' => 5, 'min_value' => 0, 'max_value' => 100],
            'percentageDirtiness' => ['value' => 25, 'min_value' => 0, 'max_value' => 100],
            'percentageSuccess' => ['value' => 50, 'min_value' => 1, 'max_value' => 99],
            'percentageCritical' => ['value' => 0, 'min_value' => 0, 'max_value' => 100],
        ],
        [
            'name' => 'disassemble_percent_6_cost_4',
            'action_name' => 'disassemble',
            'types' => ['action_technician'],
            'target' => null,
            'scope' => 'current',
            'visibilities' => ['success' => 'public', 'fail' => 'private'],
            'actionPoint' => ['value' => 4, 'min_value' => 0, 'max_value' => null],
            'movementPoint' => ['value' => 0, 'min_value' => 0, 'max_value' => null],
            'moralPoint' => ['value' => 0, 'min_value' => 0, 'max_value' => null],
            'percentageInjury' => ['value' => 5, 'min_value' => 0, 'max_value' => 100],
            'percentageDirtiness' => ['value' => 25, 'min_value' => 0, 'max_value' => 100],
            'percentageSuccess' => ['value' => 6, 'min_value' => 1, 'max_value' => 99],
            'percentageCritical' => ['value' => 0, 'min_value' => 0, 'max_value' => 100],
        ],
        [
            'name' => 'disassemble_percent_12_cost_4',
            'action_name' => 'disassemble',
            'types' => ['action_technician'],
            'target' => null,
            'scope' => 'current',
            'visibilities' => ['success' => 'public', 'fail' => 'private'],
            'actionPoint' => ['value' => 4, 'min_value' => 0, 'max_value' => null],
            'movementPoint' => ['value' => 0, 'min_value' => 0, 'max_value' => null],
            'moralPoint' => ['value' => 0, 'min_value' => 0, 'max_value' => null],
            'percentageInjury' => ['value' => 5, 'min_value' => 0, 'max_value' => 100],
            'percentageDirtiness' => ['value' => 25, 'min_value' => 0, 'max_value' => 100],
            'percentageSuccess' => ['value' => 12, 'min_value' => 1, 'max_value' => 99],
            'percentageCritical' => ['value' => 0, 'min_value' => 0, 'max_value' => 100],
        ],
        [
            'name' => 'disassemble_percent_25_cost_4',
            'action_name' => 'disassemble',
            'types' => ['action_technician'],
            'target' => null,
            'scope' => 'current',
            'visibilities' => ['success' => 'public', 'fail' => 'private'],
            'actionPoint' => ['value' => 4, 'min_value' => 0, 'max_value' => null],
            'movementPoint' => ['value' => 0, 'min_value' => 0, 'max_value' => null],
            'moralPoint' => ['value' => 0, 'min_value' => 0, 'max_value' => null],
            'percentageInjury' => ['value' => 5, 'min_value' => 0, 'max_value' => 100],
            'percentageDirtiness' => ['value' => 25, 'min_value' => 0, 'max_value' => 100],
            'percentageSuccess' => ['value' => 25, 'min_value' => 1, 'max_value' => 99],
            'percentageCritical' => ['value' => 0, 'min_value' => 0, 'max_value' => 100],
        ],
        [
            'name' => 'sabotage_percent_1',
            'action_name' => 'sabotage',
            'types' => [],
            'target' => null,
            'scope' => 'current',
            'visibilities' => ['success' => 'secret', 'fail' => 'private'],
            'actionPoint' => ['value' => 2, 'min_value' => 0, 'max_value' => null],
            'movementPoint' => ['value' => 0, 'min_value' => 0, 'max_value' => null],
            'moralPoint' => ['value' => 0, 'min_value' => 0, 'max_value' => null],
            'percentageInjury' => ['value' => 0, 'min_value' => 0, 'max_value' => 100],
            'percentageDirtiness' => ['value' => 25, 'min_value' => 0, 'max_value' => 100],
            'percentageSuccess' => ['value' => 1, 'min_value' => 1, 'max_value' => 99],
            'percentageCritical' => ['value' => 0, 'min_value' => 0, 'max_value' => 100],
        ],
        [
            'name' => 'sabotage_percent_3',
            'action_name' => 'sabotage',
            'types' => [],
            'target' => null,
            'scope' => 'current',
            'visibilities' => ['success' => 'secret', 'fail' => 'private'],
            'actionPoint' => ['value' => 2, 'min_value' => 0, 'max_value' => null],
            'movementPoint' => ['value' => 0, 'min_value' => 0, 'max_value' => null],
            'moralPoint' => ['value' => 0, 'min_value' => 0, 'max_value' => null],
            'percentageInjury' => ['value' => 0, 'min_value' => 0, 'max_value' => 100],
            'percentageDirtiness' => ['value' => 25, 'min_value' => 0, 'max_value' => 100],
            'percentageSuccess' => ['value' => 3, 'min_value' => 1, 'max_value' => 99],
            'percentageCritical' => ['value' => 0, 'min_value' => 0, 'max_value' => 100],
        ],
        [
            'name' => 'sabotage_percent_6',
            'action_name' => 'sabotage',
            'types' => [],
            'target' => null,
            'scope' => 'current',
            'visibilities' => ['success' => 'secret', 'fail' => 'private'],
            'actionPoint' => ['value' => 2, 'min_value' => 0, 'max_value' => null],
            'movementPoint' => ['value' => 0, 'min_value' => 0, 'max_value' => null],
            'moralPoint' => ['value' => 0, 'min_value' => 0, 'max_value' => null],
            'percentageInjury' => ['value' => 0, 'min_value' => 0, 'max_value' => 100],
            'percentageDirtiness' => ['value' => 25, 'min_value' => 0, 'max_value' => 100],
            'percentageSuccess' => ['value' => 6, 'min_value' => 1, 'max_value' => 99],
            'percentageCritical' => ['value' => 0, 'min_value' => 0, 'max_value' => 100],
        ],
        [
            'name' => 'sabotage_percent_12',
            'action_name' => 'sabotage',
            'types' => [],
            'target' => null,
            'scope' => 'current',
            'visibilities' => ['success' => 'secret', 'fail' => 'private'],
            'actionPoint' => ['value' => 2, 'min_value' => 0, 'max_value' => null],
            'movementPoint' => ['value' => 0, 'min_value' => 0, 'max_value' => null],
            'moralPoint' => ['value' => 0, 'min_value' => 0, 'max_value' => null],
            'percentageInjury' => ['value' => 0, 'min_value' => 0, 'max_value' => 100],
            'percentageDirtiness' => ['value' => 25, 'min_value' => 0, 'max_value' => 100],
            'percentageSuccess' => ['value' => 12, 'min_value' => 1, 'max_value' => 99],
            'percentageCritical' => ['value' => 0, 'min_value' => 0, 'max_value' => 100],
        ],
        [
            'name' => 'sabotage_percent_25',
            'action_name' => 'sabotage',
            'types' => [],
            'target' => null,
            'scope' => 'current',
            'visibilities' => ['success' => 'secret', 'fail' => 'private'],
            'actionPoint' => ['value' => 2, 'min_value' => 0, 'max_value' => null],
            'movementPoint' => ['value' => 0, 'min_value' => 0, 'max_value' => null],
            'moralPoint' => ['value' => 0, 'min_value' => 0, 'max_value' => null],
            'percentageInjury' => ['value' => 0, 'min_value' => 0, 'max_value' => 100],
            'percentageDirtiness' => ['value' => 25, 'min_value' => 0, 'max_value' => 100],
            'percentageSuccess' => ['value' => 25, 'min_value' => 1, 'max_value' => 99],
            'percentageCritical' => ['value' => 0, 'min_value' => 0, 'max_value' => 100],
        ],
        [
            'name' => 'sabotage_percent_50',
            'action_name' => 'sabotage',
            'types' => [],
            'target' => null,
            'scope' => 'current',
            'visibilities' => ['success' => 'secret', 'fail' => 'private'],
            'actionPoint' => ['value' => 2, 'min_value' => 0, 'max_value' => null],
            'movementPoint' => ['value' => 0, 'min_value' => 0, 'max_value' => null],
            'moralPoint' => ['value' => 0, 'min_value' => 0, 'max_value' => null],
            'percentageInjury' => ['value' => 0, 'min_value' => 0, 'max_value' => 100],
            'percentageDirtiness' => ['value' => 25, 'min_value' => 0, 'max_value' => 100],
            'percentageSuccess' => ['value' => 50, 'min_value' => 1, 'max_value' => 99],
            'percentageCritical' => ['value' => 0, 'min_value' => 0, 'max_value' => 100],
        ],
        [
            'name' => 'extract_spore',
            'action_name' => 'extract_spore',
            'types' => [],
            'target' => null,
            'scope' => 'self',
            'visibilities' => ['success' => 'secret', 'fail' => 'private'],
            'actionPoint' => ['value' => 2, 'min_value' => 0, 'max_value' => null],
            'movementPoint' => ['value' => 0, 'min_value' => 0, 'max_value' => null],
            'moralPoint' => ['value' => 0, 'min_value' => 0, 'max_value' => null],
            'percentageInjury' => ['value' => 0, 'min_value' => 0, 'max_value' => 100],
            'percentageDirtiness' => ['value' => 100, 'min_value' => 100, 'max_value' => 100],
            'percentageSuccess' => ['value' => 100, 'min_value' => 1, 'max_value' => 100],
            'percentageCritical' => ['value' => 0, 'min_value' => 0, 'max_value' => 100],
        ],
        [
            'name' => 'infect',
            'action_name' => 'infect',
            'types' => ['action_aggressive'],
            'target' => null,
            'scope' => 'other_player',
            'visibilities' => ['success' => 'covert', 'fail' => 'private'],
            'actionPoint' => ['value' => 1, 'min_value' => 0, 'max_value' => null],
            'movementPoint' => ['value' => 0, 'min_value' => 0, 'max_value' => null],
            'moralPoint' => ['value' => 0, 'min_value' => 0, 'max_value' => null],
            'percentageInjury' => ['value' => 0, 'min_value' => 0, 'max_value' => 100],
            'percentageDirtiness' => ['value' => 0, 'min_value' => 0, 'max_value' => 100],
            'percentageSuccess' => ['value' => 100, 'min_value' => 1, 'max_value' => 100],
            'percentageCritical' => ['value' => 0, 'min_value' => 0, 'max_value' => 100],
        ],
        [
            'name' => 'spread_fire',
            'action_name' => 'spread_fire',
            'types' => [],
            'target' => null,
            'scope' => 'self',
            'visibilities' => ['success' => 'secret', 'fail' => 'private'],
            'actionPoint' => ['value' => 4, 'min_value' => 0, 'max_value' => null],
            'movementPoint' => ['value' => 0, 'min_value' => 0, 'max_value' => null],
            'moralPoint' => ['value' => 0, 'min_value' => 0, 'max_value' => null],
            'percentageInjury' => ['value' => 0, 'min_value' => 0, 'max_value' => 100],
            'percentageDirtiness' => ['value' => 0, 'min_value' => 0, 'max_value' => 100],
            'percentageSuccess' => ['value' => 100, 'min_value' => 1, 'max_value' => 100],
            'percentageCritical' => ['value' => 0, 'min_value' => 0, 'max_value' => 100],
        ],
        [
            'name' => 'make_sick',
            'action_name' => 'make_sick',
            'types' => ['action_aggressive'],
            'target' => null,
            'scope' => 'other_player',
            'visibilities' => ['success' => 'covert', 'fail' => 'private'],
            'actionPoint' => ['value' => 1, 'min_value' => 0, 'max_value' => null],
            'movementPoint' => ['value' => 0, 'min_value' => 0, 'max_value' => null],
            'moralPoint' => ['value' => 0, 'min_value' => 0, 'max_value' => null],
            'percentageInjury' => ['value' => 0, 'min_value' => 0, 'max_value' => 100],
            'percentageDirtiness' => ['value' => 0, 'min_value' => 0, 'max_value' => 100],
            'percentageSuccess' => ['value' => 100, 'min_value' => 1, 'max_value' => 100],
            'percentageCritical' => ['value' => 0, 'min_value' => 0, 'max_value' => 100],
        ],
        [
            'name' => 'fake_disease',
            'action_name' => 'fake_disease',
            'types' => [],
            'target' => null,
            'scope' => 'self',
            'visibilities' => ['success' => 'secret', 'fail' => 'private'],
            'actionPoint' => ['value' => 1, 'min_value' => 0, 'max_value' => null],
            'movementPoint' => ['value' => 0, 'min_value' => 0, 'max_value' => null],
            'moralPoint' => ['value' => 0, 'min_value' => 0, 'max_value' => null],
            'percentageInjury' => ['value' => 0, 'min_value' => 0, 'max_value' => 100],
            'percentageDirtiness' => ['value' => 0, 'min_value' => 0, 'max_value' => 100],
            'percentageSuccess' => ['value' => 100, 'min_value' => 1, 'max_value' => 100],
            'percentageCritical' => ['value' => 0, 'min_value' => 0, 'max_value' => 100],
        ],
        [
            'name' => 'screw_talkie',
            'action_name' => 'screw_talkie',
            'types' => [],
            'target' => null,
            'scope' => 'other_player',
            'visibilities' => ['success' => 'covert', 'fail' => 'private'],
            'actionPoint' => ['value' => 3, 'min_value' => 0, 'max_value' => null],
            'movementPoint' => ['value' => 0, 'min_value' => 0, 'max_value' => null],
            'moralPoint' => ['value' => 0, 'min_value' => 0, 'max_value' => null],
            'percentageInjury' => ['value' => 0, 'min_value' => 0, 'max_value' => 100],
            'percentageDirtiness' => ['value' => 0, 'min_value' => 0, 'max_value' => 100],
            'percentageSuccess' => ['value' => 100, 'min_value' => 1, 'max_value' => 100],
            'percentageCritical' => ['value' => 0, 'min_value' => 0, 'max_value' => 100],
        ],
        [
            'name' => 'eat_spore',
            'action_name' => 'eat_spore',
            'types' => [],
            'target' => null,
            'scope' => 'self',
            'visibilities' => ['success' => 'private', 'fail' => 'private'],
            'actionPoint' => ['value' => 0, 'min_value' => 0, 'max_value' => null],
            'movementPoint' => ['value' => 0, 'min_value' => 0, 'max_value' => null],
            'moralPoint' => ['value' => 0, 'min_value' => 0, 'max_value' => null],
            'percentageInjury' => ['value' => 0, 'min_value' => 0, 'max_value' => 100],
            'percentageDirtiness' => ['value' => 0, 'min_value' => 0, 'max_value' => 100],
            'percentageSuccess' => ['value' => 100, 'min_value' => 1, 'max_value' => 100],
            'percentageCritical' => ['value' => 0, 'min_value' => 0, 'max_value' => 100],
        ],
        [
            'name' => ActionEnum::PLAY_ARCADE,
            'action_name' => ActionEnum::PLAY_ARCADE,
            'types' => [],
            'target' => null,
            'scope' => ActionScopeEnum::CURRENT,
            'visibilities' => [ActionOutputEnum::SUCCESS => VisibilityEnum::PUBLIC, ActionOutputEnum::FAIL => VisibilityEnum::PRIVATE],
            'actionPoint' => ['value' => 1, 'min_value' => 0, 'max_value' => null],
            'movementPoint' => ['value' => 0, 'min_value' => 0, 'max_value' => null],
            'moralPoint' => ['value' => 0, 'min_value' => 0, 'max_value' => null],
            'percentageInjury' => ['value' => 0, 'min_value' => 0, 'max_value' => 100],
            'percentageDirtiness' => ['value' => 0, 'min_value' => 0, 'max_value' => 100],
            'percentageSuccess' => ['value' => 33, 'min_value' => 1, 'max_value' => 99],
            'percentageCritical' => ['value' => 0, 'min_value' => 0, 'max_value' => 100],
        ],
        [
            'name' => ActionEnum::SHOOT_HUNTER . '_turret',
            'action_name' => ActionEnum::SHOOT_HUNTER,
            'types' => [ActionTypeEnum::ACTION_SHOOT_HUNTER],
            'target' => Hunter::class,
            'scope' => ActionScopeEnum::ROOM,
            'visibilities' => [ActionOutputEnum::SUCCESS => VisibilityEnum::HIDDEN, ActionOutputEnum::FAIL => VisibilityEnum::PRIVATE],
            'actionPoint' => ['value' => 1, 'min_value' => 0, 'max_value' => null],
            'movementPoint' => ['value' => 0, 'min_value' => 0, 'max_value' => null],
            'moralPoint' => ['value' => 0, 'min_value' => 0, 'max_value' => null],
            'percentageInjury' => ['value' => 0, 'min_value' => 0, 'max_value' => 100],
            'percentageDirtiness' => ['value' => 0, 'min_value' => 0, 'max_value' => 100],
            'percentageSuccess' => ['value' => 30, 'min_value' => 1, 'max_value' => 99],
            'percentageCritical' => ['value' => 0, 'min_value' => 0, 'max_value' => 100],
        ],
        [
            'name' => ActionEnum::SHOOT_RANDOM_HUNTER . '_turret',
            'action_name' => ActionEnum::SHOOT_RANDOM_HUNTER,
            'types' => [ActionTypeEnum::ACTION_SHOOT_HUNTER],
            'target' => null,
            'scope' => ActionScopeEnum::CURRENT,
            'visibilities' => [ActionOutputEnum::SUCCESS => VisibilityEnum::HIDDEN, ActionOutputEnum::FAIL => VisibilityEnum::PRIVATE],
            'actionPoint' => ['value' => 1, 'min_value' => 0, 'max_value' => null],
            'movementPoint' => ['value' => 0, 'min_value' => 0, 'max_value' => null],
            'moralPoint' => ['value' => 0, 'min_value' => 0, 'max_value' => null],
            'percentageInjury' => ['value' => 0, 'min_value' => 0, 'max_value' => 100],
            'percentageDirtiness' => ['value' => 0, 'min_value' => 0, 'max_value' => 100],
            'percentageSuccess' => ['value' => 30, 'min_value' => 1, 'max_value' => 99],
            'percentageCritical' => ['value' => 0, 'min_value' => 0, 'max_value' => 100],
        ],
        [
            'name' => ActionEnum::SHOOT_HUNTER_PATROL_SHIP,
            'action_name' => ActionEnum::SHOOT_HUNTER_PATROL_SHIP,
            'types' => [ActionTypeEnum::ACTION_SHOOT_HUNTER],
            'target' => Hunter::class,
            'scope' => ActionScopeEnum::ROOM,
            'visibilities' => [ActionOutputEnum::SUCCESS => VisibilityEnum::HIDDEN, ActionOutputEnum::FAIL => VisibilityEnum::PRIVATE],
            'actionPoint' => ['value' => 1, 'min_value' => 0, 'max_value' => null],
            'movementPoint' => ['value' => 0, 'min_value' => 0, 'max_value' => null],
            'moralPoint' => ['value' => 0, 'min_value' => 0, 'max_value' => null],
            'percentageInjury' => ['value' => 0, 'min_value' => 0, 'max_value' => 100],
            'percentageDirtiness' => ['value' => 0, 'min_value' => 0, 'max_value' => 100],
            'percentageSuccess' => ['value' => 40, 'min_value' => 1, 'max_value' => 99],
            'percentageCritical' => ['value' => 0, 'min_value' => 0, 'max_value' => 100],
        ],
        [
            'name' => ActionEnum::SHOOT_RANDOM_HUNTER_PATROL_SHIP,
            'action_name' => ActionEnum::SHOOT_RANDOM_HUNTER_PATROL_SHIP,
            'types' => [ActionTypeEnum::ACTION_SHOOT_HUNTER],
            'target' => null,
            'scope' => ActionScopeEnum::CURRENT,
            'visibilities' => [ActionOutputEnum::SUCCESS => VisibilityEnum::HIDDEN, ActionOutputEnum::FAIL => VisibilityEnum::PRIVATE],
            'actionPoint' => ['value' => 1, 'min_value' => 0, 'max_value' => null],
            'movementPoint' => ['value' => 0, 'min_value' => 0, 'max_value' => null],
            'moralPoint' => ['value' => 0, 'min_value' => 0, 'max_value' => null],
            'percentageInjury' => ['value' => 0, 'min_value' => 0, 'max_value' => 100],
            'percentageDirtiness' => ['value' => 0, 'min_value' => 0, 'max_value' => 100],
            'percentageSuccess' => ['value' => 40, 'min_value' => 1, 'max_value' => 99],
            'percentageCritical' => ['value' => 0, 'min_value' => 0, 'max_value' => 100],
        ],
        [
            'name' => ActionEnum::TAKEOFF,
            'action_name' => ActionEnum::TAKEOFF,
            'types' => [],
            'target' => null,
            'scope' => ActionScopeEnum::CURRENT,
            'visibilities' => ['success' => VisibilityEnum::PUBLIC, ActionOutputEnum::FAIL => VisibilityEnum::PUBLIC],
            'actionPoint' => ['value' => 2, 'min_value' => 0, 'max_value' => null],
            'movementPoint' => ['value' => 0, 'min_value' => 0, 'max_value' => null],
            'moralPoint' => ['value' => 0, 'min_value' => 0, 'max_value' => null],
            'percentageInjury' => ['value' => 2, 'min_value' => 0, 'max_value' => 100],
            'percentageDirtiness' => ['value' => 0, 'min_value' => 0, 'max_value' => 100],
            'percentageSuccess' => ['value' => 100, 'min_value' => 1, 'max_value' => 100],
            'percentageCritical' => ['value' => 20, 'min_value' => 0, 'max_value' => 100],
        ],
        [
            'name' => ActionEnum::LAND,
            'action_name' => ActionEnum::LAND,
            'types' => [],
            'target' => null,
            'scope' => ActionScopeEnum::CURRENT,
            'visibilities' => [ActionOutputEnum::SUCCESS => VisibilityEnum::HIDDEN, ActionOutputEnum::FAIL => VisibilityEnum::HIDDEN],
            'actionPoint' => ['value' => 2, 'min_value' => 0, 'max_value' => null],
            'movementPoint' => ['value' => 0, 'min_value' => 0, 'max_value' => null],
            'moralPoint' => ['value' => 0, 'min_value' => 0, 'max_value' => null],
            'percentageInjury' => ['value' => 2, 'min_value' => 0, 'max_value' => 100],
            'percentageDirtiness' => ['value' => 0, 'min_value' => 0, 'max_value' => 100],
            'percentageSuccess' => ['value' => 100, 'min_value' => 1, 'max_value' => 100],
            'percentageCritical' => ['value' => 20, 'min_value' => 0, 'max_value' => 100],
        ],
        [
            'name' => ActionEnum::COLLECT_SCRAP,
            'action_name' => ActionEnum::COLLECT_SCRAP,
            'types' => [],
            'target' => null,
            'scope' => ActionScopeEnum::CURRENT,
            'visibilities' => [ActionOutputEnum::SUCCESS => VisibilityEnum::HIDDEN, ActionOutputEnum::FAIL => VisibilityEnum::HIDDEN],
            'actionPoint' => ['value' => 2, 'min_value' => 0, 'max_value' => null],
            'movementPoint' => ['value' => 0, 'min_value' => 0, 'max_value' => null],
            'moralPoint' => ['value' => 0, 'min_value' => 0, 'max_value' => null],
            'percentageInjury' => ['value' => 0, 'min_value' => 0, 'max_value' => 100],
            'percentageDirtiness' => ['value' => 0, 'min_value' => 0, 'max_value' => 100],
            'percentageSuccess' => ['value' => 100, 'min_value' => 1, 'max_value' => 100],
            'percentageCritical' => ['value' => 0, 'min_value' => 0, 'max_value' => 100],
        ],
        [
            'name' => ActionEnum::RENOVATE,
            'action_name' => ActionEnum::RENOVATE,
            'types' => [ActionTypeEnum::ACTION_TECHNICIAN],
            'target' => null,
            'scope' => ActionScopeEnum::CURRENT,
            'visibilities' => [ActionOutputEnum::SUCCESS => VisibilityEnum::PUBLIC, ActionOutputEnum::FAIL => VisibilityEnum::PRIVATE],
            'actionPoint' => ['value' => 2, 'min_value' => 0, 'max_value' => null],
            'movementPoint' => ['value' => 0, 'min_value' => 0, 'max_value' => null],
            'moralPoint' => ['value' => 0, 'min_value' => 0, 'max_value' => null],
            'percentageInjury' => ['value' => 0, 'min_value' => 0, 'max_value' => 100],
            'percentageDirtiness' => ['value' => 0, 'min_value' => 0, 'max_value' => 100],
            'percentageSuccess' => ['value' => 12, 'min_value' => 1, 'max_value' => 99],
            'percentageCritical' => ['value' => 0, 'min_value' => 0, 'max_value' => 100],
        ],
        [
            'name' => ActionEnum::CONVERT_ACTION_TO_MOVEMENT,
            'action_name' => ActionEnum::CONVERT_ACTION_TO_MOVEMENT,
            'types' => [],
            'target' => null,
            'scope' => 'self',
            'visibilities' => ['success' => 'hidden', 'fail' => 'hidden'],
            'actionPoint' => ['value' => 1, 'min_value' => 0, 'max_value' => null],
            'movementPoint' => ['value' => -2, 'min_value' => null, 'max_value' => 0],
            'moralPoint' => ['value' => 0, 'min_value' => 0, 'max_value' => null],
            'percentageInjury' => ['value' => 0, 'min_value' => 0, 'max_value' => 100],
            'percentageDirtiness' => ['value' => 0, 'min_value' => 0, 'max_value' => 100],
            'percentageSuccess' => ['value' => 100, 'min_value' => 1, 'max_value' => 100],
            'percentageCritical' => ['value' => 0, 'min_value' => 0, 'max_value' => 100],
        ],
        [
            'name' => ActionEnum::AUTO_EJECT,
            'action_name' => ActionEnum::AUTO_EJECT,
            'types' => [],
            'target' => GameEquipment::class,
            'scope' => ActionScopeEnum::ROOM,
            'visibilities' => ['success' => VisibilityEnum::PUBLIC, 'fail' => 'hidden'],
            'actionPoint' => ['value' => 1, 'min_value' => 0, 'max_value' => null],
            'movementPoint' => ['value' => 0, 'min_value' => null, 'max_value' => 0],
            'moralPoint' => ['value' => 0, 'min_value' => 0, 'max_value' => null],
            'percentageInjury' => ['value' => 25, 'min_value' => 0, 'max_value' => 100],
            'percentageDirtiness' => ['value' => 25, 'min_value' => 0, 'max_value' => 100],
            'percentageSuccess' => ['value' => 100, 'min_value' => 1, 'max_value' => 100],
            'percentageCritical' => ['value' => 0, 'min_value' => 0, 'max_value' => 100],
        ],
        [
            'name' => ActionEnum::INSERT_FUEL_CHAMBER,
            'action_name' => ActionEnum::INSERT_FUEL_CHAMBER,
            'types' => [],
            'target' => null,
            'scope' => ActionScopeEnum::CURRENT,
            'visibilities' => ['success' => VisibilityEnum::PUBLIC, 'fail' => 'hidden'],
            'actionPoint' => ['value' => 0, 'min_value' => 0, 'max_value' => null],
            'movementPoint' => ['value' => 0, 'min_value' => null, 'max_value' => 0],
            'moralPoint' => ['value' => 0, 'min_value' => 0, 'max_value' => null],
            'percentageInjury' => ['value' => 1, 'min_value' => 0, 'max_value' => 100],
            'percentageDirtiness' => ['value' => 15, 'min_value' => 0, 'max_value' => 100],
            'percentageSuccess' => ['value' => 100, 'min_value' => 1, 'max_value' => 100],
            'percentageCritical' => ['value' => 0, 'min_value' => 0, 'max_value' => 100],
        ],
        [
            'name' => ActionEnum::RETRIEVE_FUEL_CHAMBER,
            'action_name' => ActionEnum::RETRIEVE_FUEL_CHAMBER,
            'types' => [],
            'target' => null,
            'scope' => ActionScopeEnum::CURRENT,
            'visibilities' => ['success' => VisibilityEnum::SECRET, 'fail' => 'hidden'],
            'actionPoint' => ['value' => 0, 'min_value' => 0, 'max_value' => null],
            'movementPoint' => ['value' => 0, 'min_value' => null, 'max_value' => 0],
            'moralPoint' => ['value' => 0, 'min_value' => 0, 'max_value' => null],
            'percentageInjury' => ['value' => 1, 'min_value' => 0, 'max_value' => 100],
            'percentageDirtiness' => ['value' => 15, 'min_value' => 0, 'max_value' => 100],
            'percentageSuccess' => ['value' => 100, 'min_value' => 1, 'max_value' => 100],
            'percentageCritical' => ['value' => 0, 'min_value' => 0, 'max_value' => 100],
        ],
        [
            'name' => ActionEnum::HACK,
            'action_name' => ActionEnum::HACK,
            'types' => [],
            'target' => null,
            'scope' => ActionScopeEnum::CURRENT,
            'visibilities' => ['success' => VisibilityEnum::PRIVATE, 'fail' => VisibilityEnum::PRIVATE],
            'actionPoint' => ['value' => 2, 'min_value' => 0, 'max_value' => null],
            'movementPoint' => ['value' => 0, 'min_value' => null, 'max_value' => 0],
            'moralPoint' => ['value' => 0, 'min_value' => 0, 'max_value' => null],
            'percentageInjury' => ['value' => 0, 'min_value' => 0, 'max_value' => 100],
            'percentageDirtiness' => ['value' => 0, 'min_value' => 0, 'max_value' => 100],
            'percentageSuccess' => ['value' => 25, 'min_value' => 1, 'max_value' => 99],
            'percentageCritical' => ['value' => 0, 'min_value' => 0, 'max_value' => 100],
        ],
    ];
}
