services:
    default.order_filter:
        parent: 'api_platform.doctrine.orm.order_filter'
        arguments:
            $properties: { id: ~, name: ~ }
            $orderParameterName: order
        tags: [ 'api_platform.filter' ]
        autowire: false
        autoconfigure: false
        public: false
    date.order_filter:
        parent: 'api_platform.doctrine.orm.order_filter'
        arguments:
            $properties: { updatedAt: ~, createdAt:  ~ }
            $orderParameterName: order
        tags: [ 'api_platform.filter' ]
        autowire: false
        autoconfigure: false
        public: false
    default.search_filter:
        parent: 'api_platform.doctrine.orm.search_filter'
        arguments: [ { name: 'ipartial' } ]
        tags: [ 'api_platform.filter' ]
        autowire: false
        autoconfigure: false
        public: false
    user.order_filter:
        parent: 'api_platform.doctrine.orm.order_filter'
        arguments:
            $properties: { username: ~, userId: ~ }
            $orderParameterName: order
        tags:  [ 'api_platform.filter' ]
        autowire: false
        autoconfigure: false
        public: false
    user.search_filter:
        parent: 'api_platform.doctrine.orm.search_filter'
        arguments: [ { username: 'ipartial' } ]
        tags: [ 'api_platform.filter' ]
        autowire: false
        autoconfigure: false
        public: false
    daedalus.order_filter:
        parent: 'api_platform.doctrine.orm.order_filter'
        arguments:
            $properties: { id: ~, name: ~, gameStatus: ~ }
            $orderParameterName: order
        tags:  [ 'api_platform.filter' ]
        autowire: false
        autoconfigure: false
        public: false
    closedPlayer.search_filter:
        parent: 'api_platform.doctrine.orm.search_filter'
        arguments: [ { playerInfo.user.userId: 'exact' } ]
        tags:  [ 'api_platform.filter' ]
        autowire: false
        autoconfigure: false
        public: false
    news.order_filter:
        parent: 'api_platform.doctrine.orm.order_filter'
        arguments:
            $properties: { isPinned: ~, publicationDate: ~ }
            $orderParameterName: order
        tags: [ 'api_platform.filter' ]
        autowire: false
        autoconfigure: false
        public: false
    newsPinned.search_filter:
        parent: 'api_platform.doctrine.orm.boolean_filter'
        arguments: [ { news.isPinned: ~ } ]
        tags: [ 'api_platform.filter' ]
        autowire: false
        autoconfigure: false
        public: false
    newsPublished.search_filter:
        parent: 'api_platform.doctrine.orm.boolean_filter'
        arguments: [ { news.isPublished: ~ } ]
        tags: [ 'api_platform.filter' ]
        autowire: false
        autoconfigure: false
        public: false
