import {CharactersEnum} from '../src/enums/characters.enum';
import {SkillsEnum} from '../src/enums/skills.enum';
import {StatusEnum} from '../src/enums/status.enum';

export default [
    {
        name: CharactersEnum.ANDIE,
        statuses: [],
        skills: [
            SkillsEnum.CONFIDENT,
            SkillsEnum.DEVOTION,
            SkillsEnum.EXPERT,
            SkillsEnum.PILOT,
            SkillsEnum.POLYVALENT,
        ],
    },
    {
        name: CharactersEnum.CHAO,
        statuses: [StatusEnum.HYPERACTIVE],
        skills: [
            SkillsEnum.CRAZY_EYE,
            SkillsEnum.INTIMIDATING,
            SkillsEnum.SHOOTER,
            SkillsEnum.SURVIVALIST,
            SkillsEnum.TORTURER,
            SkillsEnum.WRESTLER,
        ],
    },
    {
        name: CharactersEnum.CHUN,
        statuses: [StatusEnum.IMMUNIZED],
        skills: [
            SkillsEnum.LETHARGY,
            SkillsEnum.MANKINDS_ONLY_HOPE,
            SkillsEnum.NURSE,
            SkillsEnum.PREMONITION,
            SkillsEnum.SNEAK,
        ],
    },
    {
        name: CharactersEnum.DEREK,
        statuses: [],
        skills: [
            SkillsEnum.FIREFIGHTER,
            SkillsEnum.MOTIVATOR,
            SkillsEnum.SHOOTER,
            SkillsEnum.WRESTLER,
            SkillsEnum.HYGIENIST,
        ],
    },
    {
        name: CharactersEnum.ELEESHA,
        statuses: [],
        skills: [
            SkillsEnum.DETERMINED,
            SkillsEnum.IT_EXPERT,
            SkillsEnum.OBSERVANT,
            SkillsEnum.POLYMATH,
            SkillsEnum.TECHNICIAN,
            SkillsEnum.TRACKER,
        ],
    },
    {
        name: CharactersEnum.FINOLA,
        statuses: [StatusEnum.GERMAPHOBE],
        skills: [
            SkillsEnum.BIOLOGIST,
            SkillsEnum.DIPLOMAT,
            SkillsEnum.MEDIC,
            SkillsEnum.NURSE,
            SkillsEnum.OCD,
            SkillsEnum.TRACKER,
        ],
    },
    {
        name: CharactersEnum.FRIEDA,
        statuses: [],
        skills: [
            SkillsEnum.ANTIQUE_PERFUME,
            SkillsEnum.ASTROPHYSICIST,
            SkillsEnum.IT_EXPERT,
            SkillsEnum.PILOT,
            SkillsEnum.RADIO_EXPERT,
            SkillsEnum.SURVIVALIST,
        ],
    },
    {
        name: CharactersEnum.GIOELE,
        statuses: [],
        skills: [
            SkillsEnum.ASTROPHYSICIST,
            SkillsEnum.CAFFEINE_JUNKIE,
            SkillsEnum.PANIC,
            SkillsEnum.PARANOID,
            SkillsEnum.SOLID,
            SkillsEnum.VICTIMIZER,
        ],
    },
    {
        name: CharactersEnum.HUA,
        statuses: [],
        skills: [
            SkillsEnum.BOTANIST,
            SkillsEnum.DETERMINED,
            SkillsEnum.PILOT,
            SkillsEnum.SURVIVALIST,
            SkillsEnum.TECHNICIAN,
            SkillsEnum.U_TURN,
        ],
    },
    {
        name: CharactersEnum.IAN,
        statuses: [StatusEnum.PACIFIST],
        skills: [
            SkillsEnum.BIOLOGIST,
            SkillsEnum.BOTANIST,
            SkillsEnum.FIREFIGHTER,
            SkillsEnum.FRUGIVORE,
            SkillsEnum.GREEN_THUMB,
            SkillsEnum.MYCOLOGIST,
        ],
    },
    {
        name: CharactersEnum.JANICE,
        statuses: [],
        skills: [
            SkillsEnum.DIPLOMAT,
            SkillsEnum.IT_EXPERT,
            SkillsEnum.NERON_ONLY_FRIEND,
            SkillsEnum.RADIO_EXPERT,
            SkillsEnum.SELF_SACRIFICE,
            SkillsEnum.SHRINK,
        ],
    },
    {
        name: CharactersEnum.KIM_JUN_SU,
        statuses: [],
        skills: [
            SkillsEnum.COLD_BLOODED,
            SkillsEnum.LEADER,
            SkillsEnum.LOGISTICS_EXPERT,
            SkillsEnum.PILOT,
            SkillsEnum.SHOOTER,
            SkillsEnum.STRATEGURU,
        ],
    },
    {
        name: CharactersEnum.KUAN_TI,
        statuses: [],
        skills: [
            SkillsEnum.ASTROPHYSICIST,
            SkillsEnum.DESIGNER,
            SkillsEnum.LEADER,
            SkillsEnum.POLITICIAN,
            SkillsEnum.TECHNICIAN,
            SkillsEnum.OPTIMIST,
        ],
    },
    {
        name: CharactersEnum.PAOLA,
        skills: [
            SkillsEnum.BIOLOGIST,
            SkillsEnum.GUNNER,
            SkillsEnum.LOGISTICS_EXPERT,
            SkillsEnum.RADIO_EXPERT,
            SkillsEnum.REBEL,
            SkillsEnum.SHOOTER,
        ],
    },
    {
        name: CharactersEnum.RALUCA,
        statuses: [StatusEnum.ANTISOCIAL],
        skills: [
            SkillsEnum.DESIGNER,
            SkillsEnum.DETACHED_CREWMEMBER,
            SkillsEnum.GENIUS,
            SkillsEnum.PHYSICIST,
            SkillsEnum.TECHNICIAN,
        ],
    },
    {
        name: CharactersEnum.ROLAND,
        statuses: [],
        skills: [
            SkillsEnum.CREATIVE,
            SkillsEnum.FIREFIGHTER,
            SkillsEnum.PILOT,
            SkillsEnum.SHOOTER,
            SkillsEnum.SPRINTER,
            SkillsEnum.OPTIMIST,
        ],
    },
    {
        name: CharactersEnum.STEPHEN,
        statuses: [],
        skills: [
            SkillsEnum.APPRENTICE,
            SkillsEnum.CHEF,
            SkillsEnum.CREATIVE,
            SkillsEnum.OPPORTUNIST,
            SkillsEnum.SHOOTER,
            SkillsEnum.SOLID,
        ],
    },
    {
        name: CharactersEnum.TERRENCE,
        statuses: [StatusEnum.DISABLED],
        skills: [
            SkillsEnum.IT_EXPERT,
            SkillsEnum.METALWORKER,
            SkillsEnum.PILOT,
            SkillsEnum.ROBOTICS_EXPERT,
            SkillsEnum.SHOOTER,
            SkillsEnum.TECHNICIAN,
        ],
    },
];
