export enum CharactersEnum {
    ANDIE = 'andie',
    DEREK = 'derek',
    ELEESHA = 'eleesha',
    FINOLA = 'finola',
    FRIEDA = 'frieda',
    GIOELE = 'gioele',
    IAN = 'ian',
    JANICE = 'janice',
    HUA = 'hua',
    KIM_JUN_SU = 'kim_jun_su',
    KUAN_TI = 'kuan_ti',
    PAOLA = 'paola',
    RALUCA = 'raluca',
    ROLAND = 'roland',
    STEPHEN = 'stephen',
    TERRENCE = 'terrence',
    CHAO = 'chao',
    CHUN = 'chun',
}

export function getAllCharacter(): string[] {
    return [
        CharactersEnum.ANDIE,
        CharactersEnum.DEREK,
        CharactersEnum.ELEESHA,
        CharactersEnum.FINOLA,
        CharactersEnum.FRIEDA,
        CharactersEnum.GIOELE,
        CharactersEnum.IAN,
        CharactersEnum.JANICE,
        CharactersEnum.HUA,
        CharactersEnum.KIM_JUN_SU,
        CharactersEnum.KUAN_TI,
        CharactersEnum.PAOLA,
        CharactersEnum.RALUCA,
        CharactersEnum.ROLAND,
        CharactersEnum.STEPHEN,
        CharactersEnum.TERRENCE,
        CharactersEnum.CHAO,
        CharactersEnum.CHUN,
    ];
}
