export enum Character {
    ANDIE = 'andie',
    DEREK = 'derek',
    ELEESHA = 'eleesha',
    FINOLA = 'finola',
    FRIEDA = 'frieda',
    GIOELE = 'gioele',
    IAN = 'ian',
    JANICE = 'janice',
    HUA = 'hua',
    KIM_JUN_SU = 'kim_jun_su',
    KUAN_TI = 'kuan_ti',
    PAOLA = 'paola',
    RALUCA = 'raluca',
    ROLAND = 'roland',
    STEPHEN = 'stephen',
    TERRENCE = 'terrence',
    CHAO = 'chao',
    CHUN = 'chun',
}

export function getAllCharacter(): string[] {
    return [
        Character.ANDIE,
        Character.DEREK,
        Character.ELEESHA,
        Character.FINOLA,
        Character.FRIEDA,
        Character.GIOELE,
        Character.IAN,
        Character.JANICE,
        Character.HUA,
        Character.KIM_JUN_SU,
        Character.KUAN_TI,
        Character.PAOLA,
        Character.RALUCA,
        Character.ROLAND,
        Character.STEPHEN,
        Character.TERRENCE,
        Character.CHAO,
        Character.CHUN,
    ];
}
