export enum LogEnum {
    EXIT_ROOM = 'exit_room',
    ENTER_ROOM = 'enter_room',
    EAT = 'eat',
    AWAKEN = 'awaken',
    NEW_DAY = 'new_day',
    GAIN_ACTION_POINT = 'gain_action_point',
    LOSS_ACTION_POINT = 'loss_action_point',
    GAIN_MOVEMENT_POINT = 'gain_movement_point',
    LOSS_MOVEMENT_POINT = 'loss_movementpoint',
    GAIN_HEALTH_POINT = 'gain_health_point',
    LOSS_HEALTH_POINT = 'loss_health_point',
    GAIN_MORAL_POINT = 'gain_moral_point',
    LOSS_MORAL_POINT = 'loss_moral_point',
}
