export enum StatusEnum {
    ANTISOCIAL = 'antisocial',
    DISABLED = 'disabled',
    GERMAPHOBE = 'germaphobe',
    HYPERACTIVE = 'hyperactive',
    IMMUNIZED = 'immunized',
    PACIFIST = 'pacifist',
    EUREKA = 'eureka',
    OUTCAST = 'outcast',
    FULL_STOMACH = 'full_stomach',
    STARVING = 'starving',
    DEMORALIZED = 'demoralized',
    SUICIDAL = 'suicidal',
    BURDENED = 'BURDENED',
}
