<?php

declare(strict_types=1);

namespace Mush\Exploration\ConfigData;

use Mush\Exploration\Enum\PlanetSectorEnum;
use Mush\Exploration\Event\ExplorationSectorEvent;

/** @codeCoverageIgnore */
final class PlanetSectorConfigData
{
    public static array $dataArray = [
        [
            'name' => PlanetSectorEnum::LANDING . '_default',
            'sectorName' => PlanetSectorEnum::LANDING,
            'weightAtPlanetGeneration' => 0,
            'weightAtPlanetAnalysis' => 0,
            'weightAtPlanetExploration' => 0,
            'maxPerPlanet' => 0,
            'explorationEvents' => [
                ExplorationSectorEvent::NOTHING_TO_REPORT => 4,
                ExplorationSectorEvent::TIRED => 3,
                ExplorationSectorEvent::ACCIDENT => 2,
                ExplorationSectorEvent::DISASTER => 1,
            ],
        ],
        [
            'name' => PlanetSectorEnum::FOREST . '_default',
            'sectorName' => PlanetSectorEnum::FOREST,
            'weightAtPlanetGeneration' => 8,
            'weightAtPlanetAnalysis' => 12,
            'weightAtPlanetExploration' => 8,
            'maxPerPlanet' => 4,
            'explorationEvents' => [
                ExplorationSectorEvent::HARVEST . '_2' => 4,
                ExplorationSectorEvent::AGAIN => 3,
                ExplorationSectorEvent::DISEASE => 2,
                ExplorationSectorEvent::PLAYER_LOST => 1,
            ],
        ],
        [
            'name' => PlanetSectorEnum::MOUNTAIN . '_default',
            'sectorName' => PlanetSectorEnum::MOUNTAIN,
            'weightAtPlanetGeneration' => 8,
            'weightAtPlanetAnalysis' => 8,
            'weightAtPlanetExploration' => 8,
            'maxPerPlanet' => 4,
            'explorationEvents' => [
                ExplorationSectorEvent::ACCIDENT => 4,
                ExplorationSectorEvent::FUEL . '_1' => 3,
                ExplorationSectorEvent::TIRED => 2,
                ExplorationSectorEvent::HARVEST . '_1' => 1,
            ],
        ],
        [
            'name' => PlanetSectorEnum::SWAMP . '_default',
            'sectorName' => PlanetSectorEnum::SWAMP,
            'weightAtPlanetGeneration' => 8,
            'weightAtPlanetAnalysis' => 8,
            'weightAtPlanetExploration' => 8,
            'maxPerPlanet' => 4,
            'explorationEvents' => [
                ExplorationSectorEvent::DISEASE => 4,
                ExplorationSectorEvent::HARVEST . '_2' => 3,
                ExplorationSectorEvent::TIRED => 2,
                ExplorationSectorEvent::NOTHING_TO_REPORT => 1,
            ],
        ],
        [
            'name' => PlanetSectorEnum::DESERT . '_default',
            'sectorName' => PlanetSectorEnum::DESERT,
            'weightAtPlanetGeneration' => 12,
            'weightAtPlanetAnalysis' => 12,
            'weightAtPlanetExploration' => 8,
            'maxPerPlanet' => 4,
            'explorationEvents' => [
                ExplorationSectorEvent::AGAIN => 4,
                ExplorationSectorEvent::TIRED => 3,
                ExplorationSectorEvent::NOTHING_TO_REPORT => 3,
            ],
        ],
        [
            'name' => PlanetSectorEnum::OCEAN . '_default',
            'sectorName' => PlanetSectorEnum::OCEAN,
            'weightAtPlanetGeneration' => 8,
            'weightAtPlanetAnalysis' => 12,
            'weightAtPlanetExploration' => 8,
            'maxPerPlanet' => 4,
            'explorationEvents' => [
                ExplorationSectorEvent::NOTHING_TO_REPORT => 6,
                ExplorationSectorEvent::PROVISION . '_3' => 3,
                ExplorationSectorEvent::PLAYER_LOST => 1,
            ],
        ],
        [
            'name' => PlanetSectorEnum::CAVE . '_default',
            'sectorName' => PlanetSectorEnum::CAVE,
            'weightAtPlanetGeneration' => 4,
            'weightAtPlanetAnalysis' => 2,
            'weightAtPlanetExploration' => 8,
            'maxPerPlanet' => 4,
            'explorationEvents' => [
                ExplorationSectorEvent::FUEL . '_2' => 4,
                ExplorationSectorEvent::ACCIDENT => 3,
                ExplorationSectorEvent::AGAIN => 2,
                ExplorationSectorEvent::ARTEFACT => 1,
            ],
        ],
        [
            'name' => PlanetSectorEnum::RUMINANT . '_default',
            'sectorName' => PlanetSectorEnum::RUMINANT,
            'weightAtPlanetGeneration' => 8,
            'weightAtPlanetAnalysis' => 4,
            'weightAtPlanetExploration' => 8,
            'maxPerPlanet' => 4,
            'explorationEvents' => [
                ExplorationSectorEvent::PROVISION . '_4' => 4,
                ExplorationSectorEvent::PROVISION . '_2' => 3,
                ExplorationSectorEvent::ACCIDENT => 2,
                ExplorationSectorEvent::FIGHT . '_12' => 1,
            ],
        ],
        [
            'name' => PlanetSectorEnum::PREDATOR . '_default',
            'sectorName' => PlanetSectorEnum::PREDATOR,
            'weightAtPlanetGeneration' => 8,
            'weightAtPlanetAnalysis' => 2,
            'weightAtPlanetExploration' => 6,
            'maxPerPlanet' => 4,
            'explorationEvents' => [
                ExplorationSectorEvent::FIGHT . '_12' => 4,
                ExplorationSectorEvent::ACCIDENT => 3,
                ExplorationSectorEvent::NOTHING_TO_REPORT => 2,
                ExplorationSectorEvent::PROVISION . '_3' => 1,
            ],
        ],
        [
            'name' => PlanetSectorEnum::INTELLIGENT . '_default',
            'sectorName' => PlanetSectorEnum::INTELLIGENT,
            'weightAtPlanetGeneration' => 8,
            'weightAtPlanetAnalysis' => 4,
            'weightAtPlanetExploration' => 8,
            'maxPerPlanet' => 4,
            'explorationEvents' => [
                ExplorationSectorEvent::FIGHT . '_12' => 4,
                ExplorationSectorEvent::PROVISION . '_2' => 3,
                ExplorationSectorEvent::ARTEFACT => 2,
                ExplorationSectorEvent::ITEM_LOST => 1,
            ],
        ],
        [
            'name' => PlanetSectorEnum::INSECT . '_default',
            'sectorName' => PlanetSectorEnum::INSECT,
            'weightAtPlanetGeneration' => 10,
            'weightAtPlanetAnalysis' => 2,
            'weightAtPlanetExploration' => 8,
            'maxPerPlanet' => 4,
            'explorationEvents' => [
                ExplorationSectorEvent::ACCIDENT => 4,
                ExplorationSectorEvent::DISEASE => 3,
                ExplorationSectorEvent::PROVISION . '_1' => 2,
                ExplorationSectorEvent::FIGHT . '_12' => 1,
            ],
        ],
        [
            'name' => PlanetSectorEnum::MANKAROG . '_default',
            'sectorName' => PlanetSectorEnum::MANKAROG,
            'weightAtPlanetGeneration' => 2,
            'weightAtPlanetAnalysis' => 4,
            'weightAtPlanetExploration' => 6,
            'maxPerPlanet' => 1,
            'explorationEvents' => [
                ExplorationSectorEvent::KILL_RANDOM => 4,
                ExplorationSectorEvent::FIGHT . '_12' => 3,
                ExplorationSectorEvent::BACK => 2,
                ExplorationSectorEvent::ARTEFACT => 1,
            ],
        ],
        [
            'name' => PlanetSectorEnum::HYDROCARBON . '_default',
            'sectorName' => PlanetSectorEnum::HYDROCARBON,
            'weightAtPlanetGeneration' => 5,
            'weightAtPlanetAnalysis' => 2,
            'weightAtPlanetExploration' => 8,
            'maxPerPlanet' => 2,
            'explorationEvents' => [
                ExplorationSectorEvent::FUEL . '_3' => 4,
                ExplorationSectorEvent::FUEL . '_4' => 3,
                ExplorationSectorEvent::FUEL . '_5' => 2,
                ExplorationSectorEvent::FUEL . '_6' => 1,
            ],
        ],
        [
            'name' => PlanetSectorEnum::OXYGEN . '_default',
            'sectorName' => PlanetSectorEnum::OXYGEN,
            'weightAtPlanetGeneration' => 8,
            'weightAtPlanetAnalysis' => 12,
            'weightAtPlanetExploration' => 8,
            'maxPerPlanet' => 1,
            'explorationEvents' => [
                ExplorationSectorEvent::OXYGEN . '_24' => 4,
                ExplorationSectorEvent::OXYGEN . '_16' => 3,
                ExplorationSectorEvent::OXYGEN . '_8' => 2,
                ExplorationSectorEvent::NOTHING_TO_REPORT => 1,
            ],
        ],
        [
            'name' => PlanetSectorEnum::COLD . '_default',
            'sectorName' => PlanetSectorEnum::COLD,
            'weightAtPlanetGeneration' => 8,
            'weightAtPlanetAnalysis' => 8,
            'weightAtPlanetExploration' => 8,
            'maxPerPlanet' => 4,
            'explorationEvents' => [
                ExplorationSectorEvent::NOTHING_TO_REPORT => 4,
                ExplorationSectorEvent::TIRED => 3,
                ExplorationSectorEvent::PLAYER_LOST => 2,
                ExplorationSectorEvent::ACCIDENT => 1,
            ],
        ],
        [
            'name' => PlanetSectorEnum::HOT . '_default',
            'sectorName' => PlanetSectorEnum::HOT,
            'weightAtPlanetGeneration' => 8,
            'weightAtPlanetAnalysis' => 8,
            'weightAtPlanetExploration' => 8,
            'maxPerPlanet' => 4,
            'explorationEvents' => [
                ExplorationSectorEvent::TIRED => 4,
                ExplorationSectorEvent::NOTHING_TO_REPORT => 3,
                ExplorationSectorEvent::HARVEST . '_2' => 2,
                ExplorationSectorEvent::ACCIDENT => 1,
            ],
        ],
        [
            'name' => PlanetSectorEnum::STRONG_WIND . '_default',
            'sectorName' => PlanetSectorEnum::STRONG_WIND,
            'weightAtPlanetGeneration' => 8,
            'weightAtPlanetAnalysis' => 8,
            'weightAtPlanetExploration' => 8,
            'maxPerPlanet' => 4,
            'explorationEvents' => [
                ExplorationSectorEvent::NOTHING_TO_REPORT => 6,
                ExplorationSectorEvent::TIRED => 3,
                ExplorationSectorEvent::ITEM_LOST => 1,
            ],
        ],
        [
            'name' => PlanetSectorEnum::SISMIC_ACTIVITY . '_default',
            'sectorName' => PlanetSectorEnum::SISMIC_ACTIVITY,
            'weightAtPlanetGeneration' => 3,
            'weightAtPlanetAnalysis' => 8,
            'weightAtPlanetExploration' => 8,
            'maxPerPlanet' => 4,
            'explorationEvents' => [
                ExplorationSectorEvent::NOTHING_TO_REPORT => 4,
                ExplorationSectorEvent::BACK => 3,
                ExplorationSectorEvent::ACCIDENT => 2,
                ExplorationSectorEvent::KILL_RANDOM => 1,
            ],
        ],
        [
            'name' => PlanetSectorEnum::VOLCANIC_ACTIVITY . '_default',
            'sectorName' => PlanetSectorEnum::VOLCANIC_ACTIVITY,
            'weightAtPlanetGeneration' => 3,
            'weightAtPlanetAnalysis' => 8,
            'weightAtPlanetExploration' => 6,
            'maxPerPlanet' => 4,
            'explorationEvents' => [
                ExplorationSectorEvent::NOTHING_TO_REPORT => 6,
                ExplorationSectorEvent::BACK => 2,
                ExplorationSectorEvent::KILL_ALL => 1,
            ],
        ],
        [
            'name' => PlanetSectorEnum::RUINS . '_default',
            'sectorName' => PlanetSectorEnum::RUINS,
            'weightAtPlanetGeneration' => 2,
            'weightAtPlanetAnalysis' => 2,
            'weightAtPlanetExploration' => 8,
            'maxPerPlanet' => 4,
            'explorationEvents' => [
                ExplorationSectorEvent::ARTEFACT => 4,
                ExplorationSectorEvent::NOTHING_TO_REPORT => 3,
                ExplorationSectorEvent::FIGHT . '_12' => 2,
                ExplorationSectorEvent::ACCIDENT => 1,
            ],
        ],
        [
            'name' => PlanetSectorEnum::WRECK . '_default',
            'sectorName' => PlanetSectorEnum::WRECK,
            'weightAtPlanetGeneration' => 2,
            'weightAtPlanetAnalysis' => 1,
            'weightAtPlanetExploration' => 8,
            'maxPerPlanet' => 4,
            'explorationEvents' => [
                ExplorationSectorEvent::ARTEFACT => 4,
                ExplorationSectorEvent::FUEL . '_3' => 3,
                ExplorationSectorEvent::NOTHING_TO_REPORT => 2,
                ExplorationSectorEvent::FIGHT . '_12' => 1,
            ],
        ],
        [
            'name' => PlanetSectorEnum::FRUIT_TREES . '_default',
            'sectorName' => PlanetSectorEnum::FRUIT_TREES,
            'weightAtPlanetGeneration' => 3,
            'weightAtPlanetAnalysis' => 1,
            'weightAtPlanetExploration' => 8,
            'maxPerPlanet' => 4,
            'explorationEvents' => [
                ExplorationSectorEvent::HARVEST . '_3' => 4,
                ExplorationSectorEvent::HARVEST . '_1' => 3,
                ExplorationSectorEvent::NOTHING_TO_REPORT => 3,
            ],
        ],
        [
            'name' => PlanetSectorEnum::LOST . '_default',
            'sectorName' => PlanetSectorEnum::LOST,
            'weightAtPlanetGeneration' => 0,
            'weightAtPlanetAnalysis' => 0,
            'weightAtPlanetExploration' => 8,
            'maxPerPlanet' => 0,
            'explorationEvents' => [
                ExplorationSectorEvent::FIND_LOST => 7,
                ExplorationSectorEvent::AGAIN => 2,
                ExplorationSectorEvent::KILL_LOST => 1,
            ],
        ],
        [
            'name' => PlanetSectorEnum::CRISTAL_FIELD . '_default',
            'sectorName' => PlanetSectorEnum::CRISTAL_FIELD,
            'weightAtPlanetGeneration' => 2,
            'weightAtPlanetAnalysis' => 4,
            'weightAtPlanetExploration' => 10,
            'maxPerPlanet' => 1,
            'explorationEvents' => [
                ExplorationSectorEvent::MUSH_TRAP => 4,
                ExplorationSectorEvent::STARMAP => 3,
                ExplorationSectorEvent::FIGHT . '_12' => 2,
                ExplorationSectorEvent::ACCIDENT => 1,
            ],
        ],
    ];
}
