<?php

declare(strict_types=1);

namespace Mush\Exploration\ConfigData;

use Mush\Exploration\Enum\PlanetSectorEnum;
use Mush\Exploration\Event\ExplorationEvent;

/** @codeCoverageIgnore */
final class PlanetSectorConfigData
{
    public static array $dataArray = [
        [
            'name' => PlanetSectorEnum::LANDING,
            'weightAtPlanetGeneration' => 0,
            'weightAtPlanetAnalysis' => 0,
            'weightAtPlanetExploration' => 0,
            'maxPerPlanet' => 0,
            'explorationEvents' => [
                ExplorationEvent::NOTHING_TO_REPORT => 4,
                ExplorationEvent::TIRED => 3,
                ExplorationEvent::ACCIDENT => 2,
                ExplorationEvent::DISASTER => 1,
            ],
        ],
        [
            'name' => PlanetSectorEnum::FOREST,
            'weightAtPlanetGeneration' => 8,
            'weightAtPlanetAnalysis' => 12,
            'weightAtPlanetExploration' => 8,
            'maxPerPlanet' => 4,
            'explorationEvents' => [
                ExplorationEvent::HARVEST . '_2' => 4,
                ExplorationEvent::AGAIN => 3,
                ExplorationEvent::DISEASE => 2,
                ExplorationEvent::PLAYER_LOST => 1,
            ],
        ],
        [
            'name' => PlanetSectorEnum::MOUNTAIN,
            'weightAtPlanetGeneration' => 8,
            'weightAtPlanetAnalysis' => 8,
            'weightAtPlanetExploration' => 8,
            'maxPerPlanet' => 4,
            'explorationEvents' => [
                ExplorationEvent::ACCIDENT => 4,
                ExplorationEvent::FUEL . '_1' => 3,
                ExplorationEvent::TIRED => 2,
                ExplorationEvent::HARVEST . '_1' => 1,
            ],
        ],
        [
            'name' => PlanetSectorEnum::SWAMP,
            'weightAtPlanetGeneration' => 8,
            'weightAtPlanetAnalysis' => 8,
            'weightAtPlanetExploration' => 8,
            'maxPerPlanet' => 4,
            'explorationEvents' => [
                ExplorationEvent::DISEASE => 4,
                ExplorationEvent::HARVEST . '_2' => 3,
                ExplorationEvent::TIRED => 2,
                ExplorationEvent::NOTHING_TO_REPORT => 1,
            ],
        ],
        [
            'name' => PlanetSectorEnum::DESERT,
            'weightAtPlanetGeneration' => 12,
            'weightAtPlanetAnalysis' => 12,
            'weightAtPlanetExploration' => 8,
            'maxPerPlanet' => 4,
            'explorationEvents' => [
                ExplorationEvent::AGAIN => 4,
                ExplorationEvent::TIRED => 3,
                ExplorationEvent::NOTHING_TO_REPORT => 3,
            ],
        ],
        [
            'name' => PlanetSectorEnum::OCEAN,
            'weightAtPlanetGeneration' => 8,
            'weightAtPlanetAnalysis' => 12,
            'weightAtPlanetExploration' => 8,
            'maxPerPlanet' => 4,
            'explorationEvents' => [
                ExplorationEvent::NOTHING_TO_REPORT => 6,
                ExplorationEvent::PROVISION . '_3' => 3,
                ExplorationEvent::PLAYER_LOST => 1,
            ],
        ],
        [
            'name' => PlanetSectorEnum::CAVE,
            'weightAtPlanetGeneration' => 4,
            'weightAtPlanetAnalysis' => 2,
            'weightAtPlanetExploration' => 8,
            'maxPerPlanet' => 4,
            'explorationEvents' => [
                ExplorationEvent::FUEL . '_2' => 4,
                ExplorationEvent::ACCIDENT => 3,
                ExplorationEvent::AGAIN => 2,
                ExplorationEvent::ARTEFACT => 1,
            ],
        ],
        [
            'name' => PlanetSectorEnum::RUMINANT,
            'weightAtPlanetGeneration' => 8,
            'weightAtPlanetAnalysis' => 4,
            'weightAtPlanetExploration' => 8,
            'maxPerPlanet' => 4,
            'explorationEvents' => [
                ExplorationEvent::PROVISION . '_4' => 4,
                ExplorationEvent::PROVISION . '_2' => 3,
                ExplorationEvent::ACCIDENT => 2,
                ExplorationEvent::FIGHT . '_12' => 1,
            ],
        ],
        [
            'name' => PlanetSectorEnum::PREDATOR,
            'weightAtPlanetGeneration' => 8,
            'weightAtPlanetAnalysis' => 2,
            'weightAtPlanetExploration' => 6,
            'maxPerPlanet' => 4,
            'explorationEvents' => [
                ExplorationEvent::FIGHT . '_12' => 4,
                ExplorationEvent::ACCIDENT => 3,
                ExplorationEvent::NOTHING_TO_REPORT => 2,
                ExplorationEvent::PROVISION . '_3' => 1,
            ],
        ],
        [
            'name' => PlanetSectorEnum::INTELLIGENT,
            'weightAtPlanetGeneration' => 8,
            'weightAtPlanetAnalysis' => 4,
            'weightAtPlanetExploration' => 8,
            'maxPerPlanet' => 4,
            'explorationEvents' => [
                ExplorationEvent::FIGHT . '_12' => 4,
                ExplorationEvent::PROVISION . '_2' => 3,
                ExplorationEvent::ARTEFACT => 2,
                ExplorationEvent::ITEM_LOST => 1,
            ],
        ],
        [
            'name' => PlanetSectorEnum::INSECT,
            'weightAtPlanetGeneration' => 10,
            'weightAtPlanetAnalysis' => 2,
            'weightAtPlanetExploration' => 8,
            'maxPerPlanet' => 4,
            'explorationEvents' => [
                ExplorationEvent::ACCIDENT => 4,
                ExplorationEvent::DISEASE => 3,
                ExplorationEvent::PROVISION . '_1' => 2,
                ExplorationEvent::FIGHT . '_12' => 1,
            ],
        ],
        [
            'name' => PlanetSectorEnum::MANKAROG,
            'weightAtPlanetGeneration' => 2,
            'weightAtPlanetAnalysis' => 4,
            'weightAtPlanetExploration' => 6,
            'maxPerPlanet' => 1,
            'explorationEvents' => [
                ExplorationEvent::KILL_RANDOM => 4,
                ExplorationEvent::FIGHT . '_12' => 3,
                ExplorationEvent::BACK => 2,
                ExplorationEvent::ARTEFACT => 1,
            ],
        ],
        [
            'name' => PlanetSectorEnum::HYDROCARBON,
            'weightAtPlanetGeneration' => 5,
            'weightAtPlanetAnalysis' => 2,
            'weightAtPlanetExploration' => 8,
            'maxPerPlanet' => 2,
            'explorationEvents' => [
                ExplorationEvent::FUEL . '_3' => 4,
                ExplorationEvent::FUEL . '_4' => 3,
                ExplorationEvent::FUEL . '_5' => 2,
                ExplorationEvent::FUEL . '_6' => 1,
            ],
        ],
        [
            'name' => PlanetSectorEnum::OXYGEN,
            'weightAtPlanetGeneration' => 8,
            'weightAtPlanetAnalysis' => 12,
            'weightAtPlanetExploration' => 8,
            'maxPerPlanet' => 1,
            'explorationEvents' => [
                ExplorationEvent::OXYGEN . '_24' => 4,
                ExplorationEvent::OXYGEN . '_16' => 3,
                ExplorationEvent::OXYGEN . '_8' => 2,
                ExplorationEvent::NOTHING_TO_REPORT => 1,
            ],
        ],
        [
            'name' => PlanetSectorEnum::COLD,
            'weightAtPlanetGeneration' => 8,
            'weightAtPlanetAnalysis' => 8,
            'weightAtPlanetExploration' => 8,
            'maxPerPlanet' => 4,
            'explorationEvents' => [
                ExplorationEvent::NOTHING_TO_REPORT => 4,
                ExplorationEvent::TIRED => 3,
                ExplorationEvent::PLAYER_LOST => 2,
                ExplorationEvent::ACCIDENT => 1,
            ],
        ],
        [
            'name' => PlanetSectorEnum::HOT,
            'weightAtPlanetGeneration' => 8,
            'weightAtPlanetAnalysis' => 8,
            'weightAtPlanetExploration' => 8,
            'maxPerPlanet' => 4,
            'explorationEvents' => [
                ExplorationEvent::TIRED => 4,
                ExplorationEvent::NOTHING_TO_REPORT => 3,
                ExplorationEvent::HARVEST . '_2' => 2,
                ExplorationEvent::ACCIDENT => 1,
            ],
        ],
        [
            'name' => PlanetSectorEnum::STRONG_WIND,
            'weightAtPlanetGeneration' => 8,
            'weightAtPlanetAnalysis' => 8,
            'weightAtPlanetExploration' => 8,
            'maxPerPlanet' => 4,
            'explorationEvents' => [
                ExplorationEvent::NOTHING_TO_REPORT => 6,
                ExplorationEvent::TIRED => 3,
                ExplorationEvent::ITEM_LOST => 1,
            ],
        ],
        [
            'name' => PlanetSectorEnum::SISMIC_ACTIVITY,
            'weightAtPlanetGeneration' => 3,
            'weightAtPlanetAnalysis' => 8,
            'weightAtPlanetExploration' => 8,
            'maxPerPlanet' => 4,
            'explorationEvents' => [
                ExplorationEvent::NOTHING_TO_REPORT => 4,
                ExplorationEvent::BACK => 3,
                ExplorationEvent::ACCIDENT => 2,
                ExplorationEvent::KILL_RANDOM => 1,
            ],
        ],
        [
            'name' => PlanetSectorEnum::VOLCANIC_ACTIVITY,
            'weightAtPlanetGeneration' => 3,
            'weightAtPlanetAnalysis' => 8,
            'weightAtPlanetExploration' => 6,
            'maxPerPlanet' => 4,
            'explorationEvents' => [
                ExplorationEvent::NOTHING_TO_REPORT => 6,
                ExplorationEvent::BACK => 2,
                ExplorationEvent::KILL_ALL => 1,
            ],
        ],
        [
            'name' => PlanetSectorEnum::RUINS,
            'weightAtPlanetGeneration' => 2,
            'weightAtPlanetAnalysis' => 2,
            'weightAtPlanetExploration' => 8,
            'maxPerPlanet' => 4,
            'explorationEvents' => [
                ExplorationEvent::ARTEFACT => 4,
                ExplorationEvent::NOTHING_TO_REPORT => 3,
                ExplorationEvent::FIGHT . '_12' => 2,
                ExplorationEvent::ACCIDENT => 1,
            ],
        ],
        [
            'name' => PlanetSectorEnum::WRECK,
            'weightAtPlanetGeneration' => 2,
            'weightAtPlanetAnalysis' => 1,
            'weightAtPlanetExploration' => 8,
            'maxPerPlanet' => 4,
            'explorationEvents' => [
                ExplorationEvent::ARTEFACT => 4,
                ExplorationEvent::FUEL . '_3' => 3,
                ExplorationEvent::NOTHING_TO_REPORT => 2,
                ExplorationEvent::FIGHT . '_12' => 1,
            ],
        ],
        [
            'name' => PlanetSectorEnum::FRUIT_TREES,
            'weightAtPlanetGeneration' => 3,
            'weightAtPlanetAnalysis' => 1,
            'weightAtPlanetExploration' => 8,
            'maxPerPlanet' => 4,
            'explorationEvents' => [
                ExplorationEvent::HARVEST . '_3' => 4,
                ExplorationEvent::HARVEST . '_1' => 3,
                ExplorationEvent::NOTHING_TO_REPORT => 3,
            ],
        ],
        [
            'name' => PlanetSectorEnum::LOST,
            'weightAtPlanetGeneration' => 0,
            'weightAtPlanetAnalysis' => 0,
            'weightAtPlanetExploration' => 8,
            'maxPerPlanet' => 0,
            'explorationEvents' => [
                ExplorationEvent::FIND_LOST => 7,
                ExplorationEvent::AGAIN => 2,
                ExplorationEvent::KILL_LOST => 1,
            ],
        ],
        [
            'name' => PlanetSectorEnum::CRISTAL_FIELD,
            'weightAtPlanetGeneration' => 2,
            'weightAtPlanetAnalysis' => 4,
            'weightAtPlanetExploration' => 10,
            'maxPerPlanet' => 1,
            'explorationEvents' => [
                ExplorationEvent::MUSH_TRAP => 4,
                ExplorationEvent::STARMAP => 3,
                ExplorationEvent::FIGHT . '_12' => 2,
                ExplorationEvent::ACCIDENT => 1,
            ],
        ],
    ];
}
