<?php

declare(strict_types=1);

namespace Mush\Exploration\ConfigData;

use Mush\Exploration\Enum\PlanetConfigsEnum;
use Mush\Exploration\Enum\PlanetSectorEnum;

/** @codeCoverageIgnore */
final class PlanetConfigData
{
    public static array $dataArray = [
        [
            'name' => PlanetConfigsEnum::REGULAR,
            'maximumSectors' => [
                PlanetSectorEnum::FOREST => 4,
                PlanetSectorEnum::MOUNTAIN => 4,
                PlanetSectorEnum::SWAMP => 4,
                PlanetSectorEnum::DESERT => 4,
                PlanetSectorEnum::OCEAN => 4,
                PlanetSectorEnum::CAVE => 4,
                PlanetSectorEnum::RUMINANT => 4,
                PlanetSectorEnum::PREDATOR => 4,
                PlanetSectorEnum::INTELLIGENT => 4,
                PlanetSectorEnum::INSECT => 4,
                PlanetSectorEnum::MANKAROG => 1,
                PlanetSectorEnum::HYDROCARBON => 2,
                PlanetSectorEnum::OXYGEN => 1,
                PlanetSectorEnum::COLD => 4,
                PlanetSectorEnum::HOT => 4,
                PlanetSectorEnum::STRONG_WIND => 4,
                PlanetSectorEnum::SEISMIC_ACTIVITY => 4,
                PlanetSectorEnum::VOLCANIC_ACTIVITY => 4,
                PlanetSectorEnum::RUINS => 4,
                PlanetSectorEnum::WRECK => 4,
                PlanetSectorEnum::FRUIT_TREES => 4,
                PlanetSectorEnum::CRISTAL_FIELD => 1,
            ],
            'sectorsWeight' => [
                PlanetSectorEnum::FOREST => 8,
                PlanetSectorEnum::MOUNTAIN => 8,
                PlanetSectorEnum::SWAMP => 8,
                PlanetSectorEnum::DESERT => 12,
                PlanetSectorEnum::OCEAN => 8,
                PlanetSectorEnum::CAVE => 4,
                PlanetSectorEnum::RUMINANT => 8,
                PlanetSectorEnum::PREDATOR => 8,
                PlanetSectorEnum::INTELLIGENT => 8,
                PlanetSectorEnum::INSECT => 10,
                PlanetSectorEnum::MANKAROG => 2,
                PlanetSectorEnum::HYDROCARBON => 5,
                PlanetSectorEnum::OXYGEN => 8,
                PlanetSectorEnum::COLD => 8,
                PlanetSectorEnum::HOT => 8,
                PlanetSectorEnum::STRONG_WIND => 8,
                PlanetSectorEnum::SEISMIC_ACTIVITY => 3,
                PlanetSectorEnum::VOLCANIC_ACTIVITY => 3,
                PlanetSectorEnum::RUINS => 2,
                PlanetSectorEnum::WRECK => 2,
                PlanetSectorEnum::FRUIT_TREES => 3,
                PlanetSectorEnum::CRISTAL_FIELD => 2,
            ],
        ],
        [
            'name' => PlanetConfigsEnum::SUMMER_EVENT_1, // a planet without mankarog, sismic or fuel. it is themed around forests. High chance of oxygen since there won't be any after that. Only one where you can find a cristalite
            'maximumSectors' => [
                PlanetSectorEnum::FOREST => 2,
                PlanetSectorEnum::SWAMP => 2,
                PlanetSectorEnum::OCEAN => 2,
                PlanetSectorEnum::RUMINANT => 2,
                PlanetSectorEnum::PREDATOR => 1,
                PlanetSectorEnum::INSECT => 2,
                PlanetSectorEnum::HOT => 2,
                PlanetSectorEnum::RUINS => 2,
                PlanetSectorEnum::WRECK => 2,
                PlanetSectorEnum::FRUIT_TREES => 2,
                PlanetSectorEnum::CRISTAL_FIELD => 1,
                PlanetSectorEnum::OXYGEN => 1,
            ],
            'sectorsWeight' => [
                PlanetSectorEnum::FOREST => 8,
                PlanetSectorEnum::SWAMP => 8,
                PlanetSectorEnum::OCEAN => 8,
                PlanetSectorEnum::RUMINANT => 8,
                PlanetSectorEnum::PREDATOR => 8,
                PlanetSectorEnum::INSECT => 10,
                PlanetSectorEnum::HOT => 8,
                PlanetSectorEnum::RUINS => 2,
                PlanetSectorEnum::WRECK => 2,
                PlanetSectorEnum::FRUIT_TREES => 3,
                PlanetSectorEnum::CRISTAL_FIELD => 4,
                PlanetSectorEnum::OXYGEN => 100,
            ],
        ],
        [
            'name' => PlanetConfigsEnum::SUMMER_EVENT_2, // a planet without mankarog, sismic or fuel. No oxygen from here until the end. Themed around ocean
            'maximumSectors' => [
                PlanetSectorEnum::SWAMP => 2,
                PlanetSectorEnum::OCEAN => 3,
                PlanetSectorEnum::CAVE => 2,
                PlanetSectorEnum::PREDATOR => 1,
                PlanetSectorEnum::COLD => 2,
                PlanetSectorEnum::STRONG_WIND => 2,
                PlanetSectorEnum::RUINS => 2,
                PlanetSectorEnum::WRECK => 3,
            ],
            'sectorsWeight' => [
                PlanetSectorEnum::SWAMP => 8,
                PlanetSectorEnum::OCEAN => 12,
                PlanetSectorEnum::CAVE => 4,
                PlanetSectorEnum::PREDATOR => 8,
                PlanetSectorEnum::COLD => 8,
                PlanetSectorEnum::STRONG_WIND => 8,
                PlanetSectorEnum::RUINS => 4,
                PlanetSectorEnum::WRECK => 8,
            ],
        ],
        [
            'name' => PlanetConfigsEnum::SUMMER_EVENT_3, // a planet without mankarog, sismic or fuel nor oxygen. No theme, it's supposed to be very similar to regular to allow players to try to find the treasure
            'maximumSectors' => [
                PlanetSectorEnum::FOREST => 2,
                PlanetSectorEnum::MOUNTAIN => 2,
                PlanetSectorEnum::SWAMP => 2,
                PlanetSectorEnum::DESERT => 2,
                PlanetSectorEnum::OCEAN => 2,
                PlanetSectorEnum::CAVE => 2,
                PlanetSectorEnum::RUMINANT => 2,
                PlanetSectorEnum::PREDATOR => 2,
                PlanetSectorEnum::INTELLIGENT => 2,
                PlanetSectorEnum::INSECT => 2,
                PlanetSectorEnum::COLD => 2,
                PlanetSectorEnum::HOT => 2,
                PlanetSectorEnum::STRONG_WIND => 2,
                PlanetSectorEnum::RUINS => 2,
                PlanetSectorEnum::WRECK => 2,
                PlanetSectorEnum::FRUIT_TREES => 2,
            ],
            'sectorsWeight' => [
                PlanetSectorEnum::FOREST => 8,
                PlanetSectorEnum::MOUNTAIN => 8,
                PlanetSectorEnum::SWAMP => 8,
                PlanetSectorEnum::DESERT => 12,
                PlanetSectorEnum::OCEAN => 8,
                PlanetSectorEnum::CAVE => 4,
                PlanetSectorEnum::RUMINANT => 8,
                PlanetSectorEnum::PREDATOR => 8,
                PlanetSectorEnum::INTELLIGENT => 8,
                PlanetSectorEnum::INSECT => 10,
                PlanetSectorEnum::COLD => 8,
                PlanetSectorEnum::HOT => 8,
                PlanetSectorEnum::STRONG_WIND => 8,
                PlanetSectorEnum::RUINS => 2,
                PlanetSectorEnum::WRECK => 2,
                PlanetSectorEnum::FRUIT_TREES => 3,
            ],
        ],
        [
            'name' => PlanetConfigsEnum::SUMMER_EVENT_4, // a planet without mankarog, sismic or fuel nor oxygen. We increase the heat here. Last chance for the crew before we add instant death sectors
            'maximumSectors' => [
                PlanetSectorEnum::FOREST => 2,
                PlanetSectorEnum::MOUNTAIN => 2,
                PlanetSectorEnum::SWAMP => 2,
                PlanetSectorEnum::DESERT => 2,
                PlanetSectorEnum::OCEAN => 2,
                PlanetSectorEnum::CAVE => 2,
                PlanetSectorEnum::RUMINANT => 2,
                PlanetSectorEnum::PREDATOR => 2,
                PlanetSectorEnum::INTELLIGENT => 2,
                PlanetSectorEnum::INSECT => 2,
                PlanetSectorEnum::COLD => 2,
                PlanetSectorEnum::HOT => 2,
                PlanetSectorEnum::STRONG_WIND => 2,
                PlanetSectorEnum::RUINS => 2,
                PlanetSectorEnum::WRECK => 2,
                PlanetSectorEnum::FRUIT_TREES => 2,
            ],
            'sectorsWeight' => [
                PlanetSectorEnum::FOREST => 8,
                PlanetSectorEnum::MOUNTAIN => 16,
                PlanetSectorEnum::SWAMP => 8,
                PlanetSectorEnum::DESERT => 16,
                PlanetSectorEnum::OCEAN => 8,
                PlanetSectorEnum::CAVE => 4,
                PlanetSectorEnum::RUMINANT => 8,
                PlanetSectorEnum::PREDATOR => 16,
                PlanetSectorEnum::INTELLIGENT => 8,
                PlanetSectorEnum::INSECT => 16,
                PlanetSectorEnum::COLD => 12,
                PlanetSectorEnum::HOT => 8,
                PlanetSectorEnum::STRONG_WIND => 12,
                PlanetSectorEnum::RUINS => 2,
                PlanetSectorEnum::WRECK => 2,
                PlanetSectorEnum::FRUIT_TREES => 3,
            ],
        ],
        [
            'name' => PlanetConfigsEnum::SUMMER_EVENT_5, // death is here. This version is meant to punish players who are trying to explore too much or who took too long to find the treasure.
            'maximumSectors' => [
                PlanetSectorEnum::FOREST => 2,
                PlanetSectorEnum::MOUNTAIN => 2,
                PlanetSectorEnum::SWAMP => 2,
                PlanetSectorEnum::DESERT => 2,
                PlanetSectorEnum::CAVE => 2,
                PlanetSectorEnum::PREDATOR => 2,
                PlanetSectorEnum::INSECT => 2,
                PlanetSectorEnum::MANKAROG => 2,
                PlanetSectorEnum::COLD => 2,
                PlanetSectorEnum::STRONG_WIND => 2,
                PlanetSectorEnum::SEISMIC_ACTIVITY => 2,
                PlanetSectorEnum::VOLCANIC_ACTIVITY => 2,
                PlanetSectorEnum::RUINS => 2,
                PlanetSectorEnum::WRECK => 2,
            ],
            'sectorsWeight' => [
                PlanetSectorEnum::FOREST => 8,
                PlanetSectorEnum::MOUNTAIN => 8,
                PlanetSectorEnum::SWAMP => 8,
                PlanetSectorEnum::DESERT => 12,
                PlanetSectorEnum::CAVE => 4,
                PlanetSectorEnum::PREDATOR => 8,
                PlanetSectorEnum::INSECT => 10,
                PlanetSectorEnum::MANKAROG => 6,
                PlanetSectorEnum::COLD => 8,
                PlanetSectorEnum::STRONG_WIND => 8,
                PlanetSectorEnum::SEISMIC_ACTIVITY => 2,
                PlanetSectorEnum::VOLCANIC_ACTIVITY => 2,
                PlanetSectorEnum::RUINS => 2,
                PlanetSectorEnum::WRECK => 2,
            ],
        ],
    ];
}
