<?php

namespace Mush\Modifier\ConfigData;

use Mush\Action\Enum\ActionEnum;
use Mush\Action\Enum\ActionTypeEnum;
use Mush\Action\Enum\ActionVariableEnum;
use Mush\Action\Event\ActionEvent;
use Mush\Action\Event\ActionVariableEvent;
use Mush\Communication\Enum\MessageModificationEnum;
use Mush\Communication\Event\MessageEvent;
use Mush\Disease\Enum\SymptomEnum;
use Mush\Disease\Event\DiseaseEvent;
use Mush\Equipment\Enum\ItemEnum;
use Mush\Game\Enum\ActionOutputEnum;
use Mush\Game\Event\RollPercentageEvent;
use Mush\Game\Event\VariableEventInterface;
use Mush\Modifier\Enum\ModifierNameEnum;
use Mush\Modifier\Enum\ModifierPriorityEnum;
use Mush\Modifier\Enum\ModifierRequirementEnum;
use Mush\Modifier\Enum\ModifierStrategyEnum;
use Mush\Modifier\Enum\VariableModifierModeEnum;
use Mush\Player\Enum\EndCauseEnum;
use Mush\Player\Enum\PlayerVariableEnum;
use Mush\Player\Event\PlayerEvent;
use Mush\Status\Enum\DaedalusStatusEnum;
use Mush\Status\Enum\PlayerStatusEnum;
use Mush\Status\Event\StatusEvent;

/** @codeCoverageIgnore */
class ModifierConfigData
{
    public static array $dataArray = [
        [
            'name' => 'modifier_for_player_+1movementPoint_on_move',
            'modifierName' => null,
            'targetEvent' => 'apply.cost',
            'strategy' => ModifierStrategyEnum::VARIABLE_MODIFIER,
            'priority' => ModifierPriorityEnum::ADDITIVE_MODIFIER_VALUE,
            'applyOnTarget' => false,
            'modifierRange' => 'player',
            'type' => 'variable_event_modifier',
            'visibility' => null,
            'delta' => 1.0,
            'targetVariable' => 'movementPoint',
            'mode' => 'additive',
            'modifierActivationRequirements' => [],
            'tagConstraints' => [ActionEnum::MOVE => ModifierRequirementEnum::ALL_TAGS],
        ],
        [
            'name' => 'direct_modifier_player_-1_max_healthPoint',
            'modifierName' => null,
            'revertOnRemove' => true,
            'modifierRange' => 'player',
            'type' => 'direct_modifier',
            'triggeredEvent' => 'change.value.max_player_-1_healthPoint',
            'modifierActivationRequirements' => [],
        ],
        [
            'name' => 'direct_modifier_player_-2_max_healthPoint',
            'modifierName' => null,
            'revertOnRemove' => true,
            'modifierRange' => 'player',
            'type' => 'direct_modifier',
            'triggeredEvent' => 'change.value.max_player_-2_healthPoint',
            'modifierActivationRequirements' => [],
        ],
        [
            'name' => 'direct_modifier_player_-4_max_healthPoint',
            'modifierName' => null,
            'revertOnRemove' => true,
            'modifierRange' => 'player',
            'type' => 'direct_modifier',
            'triggeredEvent' => 'change.value.max_player_-4_healthPoint',
            'modifierActivationRequirements' => [],
        ],
        [
            'name' => 'direct_modifier_player_-1_max_moralPoint',
            'modifierName' => null,
            'revertOnRemove' => true,
            'modifierRange' => 'player',
            'type' => 'direct_modifier',
            'triggeredEvent' => 'change.value.max_player_-1_moralPoint',
            'modifierActivationRequirements' => [],
        ],
        [
            'name' => 'direct_modifier_player_-2_max_moralPoint',
            'modifierName' => null,
            'revertOnRemove' => true,
            'modifierRange' => 'player',
            'type' => 'direct_modifier',
            'triggeredEvent' => 'change.value.max_player_-2_moralPoint',
            'modifierActivationRequirements' => [],
        ],
        [
            'name' => 'modifier_for_player_set_-1healthPoint_on_new_cycle',
            'modifierName' => null,
            'strategy' => ModifierStrategyEnum::ADD_EVENT,
            'priority' => ModifierPriorityEnum::AFTER_INITIAL_EVENT,
            'targetEvent' => 'disease.new.cycle',
            'applyOnTarget' => true,
            'modifierRange' => 'player',
            'type' => 'trigger_event_modifier',
            'replaceEvent' => false,
            'triggeredEvent' => 'change.variable_player_-1_healthPoint',
            'modifierActivationRequirements' => [],
            'tagConstraints' => [],
        ],
        [
            'name' => 'modifier_for_player_set_-2healthPoint_on_new_cycle',
            'modifierName' => null,
            'strategy' => ModifierStrategyEnum::ADD_EVENT,
            'priority' => ModifierPriorityEnum::AFTER_INITIAL_EVENT,
            'targetEvent' => 'disease.new.cycle',
            'applyOnTarget' => true,
            'modifierRange' => 'player',
            'type' => 'trigger_event_modifier',
            'replaceEvent' => false,
            'triggeredEvent' => 'change.variable_player_-2_healthPoint',
            'modifierActivationRequirements' => [],
            'tagConstraints' => [],
        ],
        [
            'name' => 'modifier_for_player_set_-4healthPoint_on_new_cycle',
            'modifierName' => null,
            'targetEvent' => 'disease.new.cycle',
            'strategy' => ModifierStrategyEnum::ADD_EVENT,
            'priority' => ModifierPriorityEnum::AFTER_INITIAL_EVENT,
            'applyOnTarget' => true,
            'modifierRange' => 'player',
            'type' => 'trigger_event_modifier',
            'replaceEvent' => false,
            'triggeredEvent' => 'change.variable_player_-4_healthPoint',
            'modifierActivationRequirements' => [],
            'tagConstraints' => [],
        ],
        [
            'name' => 'modifier_for_player_set_-1movementPoint_on_new_cycle',
            'modifierName' => null,
            'targetEvent' => 'disease.new.cycle',
            'strategy' => ModifierStrategyEnum::ADD_EVENT,
            'priority' => ModifierPriorityEnum::AFTER_INITIAL_EVENT,
            'applyOnTarget' => true,
            'modifierRange' => 'player',
            'type' => 'trigger_event_modifier',
            'replaceEvent' => false,
            'triggeredEvent' => 'change.variable_player_-1_movementPoint',
            'modifierActivationRequirements' => [],
            'tagConstraints' => [],
        ],
        [
            'name' => 'modifier_for_player_set_-1satiety_on_new_cycle',
            'modifierName' => null,
            'targetEvent' => 'disease.new.cycle',
            'strategy' => ModifierStrategyEnum::ADD_EVENT,
            'priority' => ModifierPriorityEnum::AFTER_INITIAL_EVENT,
            'applyOnTarget' => true,
            'modifierRange' => 'player',
            'type' => 'trigger_event_modifier',
            'replaceEvent' => false,
            'triggeredEvent' => 'change.variable_player_-1_satiety',
            'modifierActivationRequirements' => [],
            'tagConstraints' => [],
        ],
        [
            'name' => 'modifier_for_player_set_-1actionPoint_on_new_cycle_if_random_10',
            'modifierName' => null,
            'targetEvent' => 'disease.new.cycle',
            'strategy' => ModifierStrategyEnum::ADD_EVENT,
            'priority' => ModifierPriorityEnum::AFTER_INITIAL_EVENT,
            'applyOnTarget' => true,
            'modifierRange' => 'player',
            'type' => 'trigger_event_modifier',
            'replaceEvent' => false,
            'triggeredEvent' => 'change.variable_player_-1_actionPoint',
            'modifierActivationRequirements' => [
                'random_10',
            ],
            'tagConstraints' => [],
        ],
        [
            'name' => 'modifier_for_player_set_-1healthPoint_on_new_cycle_if_random_10',
            'modifierName' => null,
            'targetEvent' => 'disease.new.cycle',
            'strategy' => ModifierStrategyEnum::ADD_EVENT,
            'priority' => ModifierPriorityEnum::AFTER_INITIAL_EVENT,
            'applyOnTarget' => true,
            'modifierRange' => 'player',
            'type' => 'trigger_event_modifier',
            'replaceEvent' => false,
            'triggeredEvent' => 'change.variable_player_-1_healthPoint',
            'modifierActivationRequirements' => [
                'random_10',
            ],
            'tagConstraints' => [],
        ],
        [
            'name' => 'modifier_for_player_set_-1actionPoint_on_new_cycle_if_random_16',
            'modifierName' => null,
            'targetEvent' => 'disease.new.cycle',
            'strategy' => ModifierStrategyEnum::ADD_EVENT,
            'priority' => ModifierPriorityEnum::AFTER_INITIAL_EVENT,
            'applyOnTarget' => true,
            'modifierRange' => 'player',
            'type' => 'trigger_event_modifier',
            'replaceEvent' => false,
            'triggeredEvent' => 'change.variable_player_-1_actionPoint',
            'modifierActivationRequirements' => [
                'random_16',
            ],
            'tagConstraints' => [],
        ],
        [
            'name' => 'modifier_for_player_set_-1healthPoint_on_new_cycle_if_random_16',
            'modifierName' => null,
            'targetEvent' => 'disease.new.cycle',
            'strategy' => ModifierStrategyEnum::ADD_EVENT,
            'priority' => ModifierPriorityEnum::AFTER_INITIAL_EVENT,
            'applyOnTarget' => true,
            'modifierRange' => 'player',
            'type' => 'trigger_event_modifier',
            'replaceEvent' => false,
            'triggeredEvent' => 'change.variable_player_-1_healthPoint',
            'modifierActivationRequirements' => [
                'random_16',
            ],
            'tagConstraints' => [],
        ],
        [
            'name' => 'modifier_for_player_set_-1actionPoint_on_new_cycle_if_random_20',
            'modifierName' => null,
            'targetEvent' => 'disease.new.cycle',
            'strategy' => ModifierStrategyEnum::ADD_EVENT,
            'priority' => ModifierPriorityEnum::AFTER_INITIAL_EVENT,
            'applyOnTarget' => true,
            'modifierRange' => 'player',
            'type' => 'trigger_event_modifier',
            'replaceEvent' => false,
            'triggeredEvent' => 'change.variable_player_-1_actionPoint',
            'modifierActivationRequirements' => [
                'random_20',
            ],
            'tagConstraints' => [],
        ],
        [
            'name' => 'modifier_for_player_set_-1actionPoint_on_new_cycle_if_random_30',
            'modifierName' => null,
            'targetEvent' => 'disease.new.cycle',
            'strategy' => ModifierStrategyEnum::ADD_EVENT,
            'priority' => ModifierPriorityEnum::AFTER_INITIAL_EVENT,
            'applyOnTarget' => true,
            'modifierRange' => 'player',
            'type' => 'trigger_event_modifier',
            'replaceEvent' => false,
            'triggeredEvent' => 'change.variable_player_-1_actionPoint',
            'modifierActivationRequirements' => [
                'random_30',
            ],
            'tagConstraints' => [],
        ],
        [
            'name' => 'modifier_for_player_set_-2actionPoint_on_new_cycle_if_random_40',
            'modifierName' => null,
            'targetEvent' => 'disease.new.cycle',
            'strategy' => ModifierStrategyEnum::ADD_EVENT,
            'priority' => ModifierPriorityEnum::AFTER_INITIAL_EVENT,
            'applyOnTarget' => true,
            'modifierRange' => 'player',
            'type' => 'trigger_event_modifier',
            'replaceEvent' => false,
            'triggeredEvent' => 'change.variable_player_-2_actionPoint',
            'modifierActivationRequirements' => [
                'random_40',
            ],
            'tagConstraints' => [],
        ],
        [
            'name' => 'modifier_for_player_set_-1movementPoint_on_new_cycle_if_random_50',
            'modifierName' => null,
            'targetEvent' => 'disease.new.cycle',
            'strategy' => ModifierStrategyEnum::ADD_EVENT,
            'priority' => ModifierPriorityEnum::AFTER_INITIAL_EVENT,
            'applyOnTarget' => true,
            'modifierRange' => 'player',
            'type' => 'trigger_event_modifier',
            'replaceEvent' => false,
            'triggeredEvent' => 'change.variable_player_-1_movementPoint',
            'modifierActivationRequirements' => [
                'random_50',
            ],
            'tagConstraints' => [],
        ],
        [
            'name' => 'modifier_for_player_set_-1healthPoint_on_new_cycle_if_random_50',
            'modifierName' => null,
            'targetEvent' => 'disease.new.cycle',
            'strategy' => ModifierStrategyEnum::ADD_EVENT,
            'priority' => ModifierPriorityEnum::AFTER_INITIAL_EVENT,
            'applyOnTarget' => true,
            'modifierRange' => 'player',
            'type' => 'trigger_event_modifier',
            'replaceEvent' => false,
            'triggeredEvent' => 'change.variable_player_-1_healthPoint',
            'modifierActivationRequirements' => [
                'random_50',
            ],
            'tagConstraints' => [],
        ],
        [
            'name' => 'modifier_for_player_set_-1actionPoint_on_post.action_if_reason_consume',
            'modifierName' => null,
            'targetEvent' => 'post.action',
            'strategy' => ModifierStrategyEnum::ADD_EVENT,
            'priority' => ModifierPriorityEnum::AFTER_INITIAL_EVENT,
            'applyOnTarget' => false,
            'modifierRange' => 'player',
            'type' => 'trigger_event_modifier',
            'replaceEvent' => false,
            'triggeredEvent' => 'change.variable_player_-1_actionPoint',
            'modifierActivationRequirements' => [],
            'tagConstraints' => [
                ActionEnum::CONSUME => ModifierRequirementEnum::ANY_TAGS,
            ],
        ],
        [
            'name' => 'modifier_for_player_set_-2actionPoint_on_post.action_if_reason_consume',
            'modifierName' => null,
            'targetEvent' => 'post.action',
            'strategy' => ModifierStrategyEnum::ADD_EVENT,
            'priority' => ModifierPriorityEnum::AFTER_INITIAL_EVENT,
            'applyOnTarget' => false,
            'modifierRange' => 'player',
            'type' => 'trigger_event_modifier',
            'replaceEvent' => false,
            'triggeredEvent' => 'change.variable_player_-2_actionPoint',
            'modifierActivationRequirements' => [],
            'tagConstraints' => [
                ActionEnum::CONSUME => ModifierRequirementEnum::ANY_TAGS,
            ],
        ],
        [
            'name' => 'modifier_for_player_set_-4healthPoint_on_infection.player',
            'modifierName' => null,
            'targetEvent' => 'infection.player',
            'strategy' => ModifierStrategyEnum::ADD_EVENT,
            'priority' => ModifierPriorityEnum::AFTER_INITIAL_EVENT,
            'applyOnTarget' => true,
            'modifierRange' => 'player',
            'type' => 'trigger_event_modifier',
            'replaceEvent' => false,
            'triggeredEvent' => 'change.variable_player_-4_healthPoint',
            'modifierActivationRequirements' => [],
            'tagConstraints' => [],
        ],
        [
            'name' => 'modifier_for_player_set_-6healthPoint_on_post.action_if_player_equipment_schrodinger',
            'modifierName' => null,
            'targetEvent' => 'post.action',
            'strategy' => ModifierStrategyEnum::ADD_EVENT,
            'priority' => ModifierPriorityEnum::AFTER_INITIAL_EVENT,
            'applyOnTarget' => false,
            'modifierRange' => 'player',
            'type' => 'trigger_event_modifier',
            'replaceEvent' => false,
            'triggeredEvent' => 'change.variable_player_-6_healthPoint',
            'modifierActivationRequirements' => [
                'player_equipment_schrodinger',
            ],
            'tagConstraints' => [],
        ],
        [
            'name' => 'modifier_for_player_+1satiety_on_new_cycle',
            'modifierName' => null,
            'targetEvent' => 'disease.new.cycle',
            'strategy' => ModifierStrategyEnum::ADD_EVENT,
            'priority' => ModifierPriorityEnum::AFTER_INITIAL_EVENT,
            'applyOnTarget' => false,
            'modifierRange' => 'player',
            'type' => 'trigger_event_modifier',
            'replaceEvent' => false,
            'triggeredEvent' => 'change.variable_player_1_satiety',
            'modifierActivationRequirements' => [],
            'tagConstraints' => [],
        ],
        [
            'name' => 'modifier_for_player_x0.9percentage_on_action_shoot',
            'modifierName' => null,
            'targetEvent' => ActionVariableEvent::ROLL_ACTION_PERCENTAGE,
            'strategy' => ModifierStrategyEnum::VARIABLE_MODIFIER,
            'priority' => ModifierPriorityEnum::MULTIPLICATIVE_MODIFIER_VALUE,
            'applyOnTarget' => false,
            'modifierRange' => 'player',
            'type' => 'variable_event_modifier',
            'triggeredEvent' => null,
            'visibility' => null,
            'delta' => 0.9,
            'targetVariable' => ActionVariableEnum::PERCENTAGE_SUCCESS,
            'mode' => 'multiplicative',
            'modifierActivationRequirements' => [],
            'tagConstraints' => [
                ActionEnum::SHOOT => ModifierRequirementEnum::ANY_TAGS,
            ],
        ],
        [
            'name' => 'modifier_for_player_+10percentage_on_cycle_disease',
            'modifierName' => null,
            'targetEvent' => RollPercentageEvent::ROLL_PERCENTAGE,
            'strategy' => ModifierStrategyEnum::VARIABLE_MODIFIER,
            'priority' => ModifierPriorityEnum::ADDITIVE_MODIFIER_VALUE,
            'applyOnTarget' => false,
            'modifierRange' => 'player',
            'type' => 'variable_event_modifier',
            'triggeredEvent' => null,
            'visibility' => null,
            'delta' => 10.0,
            'targetVariable' => ActionVariableEnum::PERCENTAGE_SUCCESS,
            'mode' => 'additive',
            'modifierActivationRequirements' => [],
            'tagConstraints' => [PlayerEvent::CYCLE_DISEASE => ModifierRequirementEnum::ANY_TAGS],
        ],
        [
            'name' => 'fitful_sleep_for_player_-1actionPoint_on_new_cycle_if_random_16_if_player_status_lying_down',
            'modifierName' => 'fitful_sleep',
            'targetEvent' => 'disease.new.cycle',
            'strategy' => ModifierStrategyEnum::ADD_EVENT,
            'priority' => ModifierPriorityEnum::AFTER_INITIAL_EVENT,
            'applyOnTarget' => true,
            'modifierRange' => 'player',
            'type' => 'trigger_event_modifier',
            'replaceEvent' => false,
            'triggeredEvent' => 'change.variable_player_-1_actionPoint',
            'modifierActivationRequirements' => [
                'random_16',
                'player_status_lying_down',
            ],
            'tagConstraints' => [],
        ],
        [
            'name' => 'apron_modifier_for_player_prevent_dirty',
            'modifierName' => 'apron_modifier',
            'targetEvent' => StatusEvent::STATUS_APPLIED,
            'strategy' => ModifierStrategyEnum::PREVENT_EVENT,
            'priority' => ModifierPriorityEnum::PREVENT_EVENT,
            'applyOnTarget' => true,
            'modifierRange' => 'player',
            'type' => 'event_modifier',
            'replaceEvent' => true,
            'triggeredEvent' => null,
            'modifierActivationRequirements' => [],
            'tagConstraints' => [
                PlayerStatusEnum::DIRTY => ModifierRequirementEnum::ALL_TAGS,
                ActionTypeEnum::ACTION_SUPER_DIRTY => ModifierRequirementEnum::NONE_TAGS,
            ],
        ],
        [
            'name' => 'modifier_for_target_player_-1healthPoint_on_injury',
            'modifierName' => null,
            'targetEvent' => VariableEventInterface::CHANGE_VARIABLE,
            'strategy' => ModifierStrategyEnum::VARIABLE_MODIFIER,
            'priority' => ModifierPriorityEnum::ADDITIVE_MODIFIER_VALUE,
            'applyOnTarget' => true,
            'modifierRange' => 'target_player',
            'type' => 'variable_event_modifier',
            'triggeredEvent' => null,
            'visibility' => null,
            'delta' => -1.0,
            'targetVariable' => 'healthPoint',
            'mode' => 'additive',
            'modifierActivationRequirements' => [],
            'tagConstraints' => [
                EndCauseEnum::INJURY => ModifierRequirementEnum::ALL_TAGS,
                ActionOutputEnum::CRITICAL_SUCCESS => ModifierRequirementEnum::NONE_TAGS,
            ],
        ],
        [
            'name' => 'modifier_for_player_x1.5percentage_on_action_technician',
            'modifierName' => null,
            'targetEvent' => ActionVariableEvent::ROLL_ACTION_PERCENTAGE,
            'strategy' => ModifierStrategyEnum::VARIABLE_MODIFIER,
            'priority' => ModifierPriorityEnum::MULTIPLICATIVE_MODIFIER_VALUE,
            'applyOnTarget' => false,
            'modifierRange' => 'player',
            'type' => 'variable_event_modifier',
            'triggeredEvent' => null,
            'visibility' => null,
            'delta' => 1.5,
            'targetVariable' => ActionVariableEnum::PERCENTAGE_SUCCESS,
            'mode' => 'multiplicative',
            'modifierActivationRequirements' => [],
            'tagConstraints' => [
                ActionTypeEnum::ACTION_TECHNICIAN => ModifierRequirementEnum::ALL_TAGS,
            ],
        ],
        [
            'name' => 'gloves_modifier_for_player_set_0percentage_on_event_clumsiness',
            'modifierName' => 'gloves_modifier',
            'targetEvent' => VariableEventInterface::CHANGE_VARIABLE,
            'strategy' => ModifierStrategyEnum::PREVENT_EVENT,
            'priority' => ModifierPriorityEnum::PREVENT_EVENT,
            'applyOnTarget' => true,
            'modifierRange' => 'player',
            'type' => 'event_modifier',
            'replaceEvent' => true,
            'triggeredEvent' => null,
            'modifierActivationRequirements' => [],
            'tagConstraints' => [EndCauseEnum::CLUMSINESS => ModifierRequirementEnum::ALL_TAGS],
        ],
        [
            'name' => 'modifier_for_player_-1actionPoint_on_shower',
            'modifierName' => null,
            'targetEvent' => ActionVariableEvent::APPLY_COST,
            'strategy' => ModifierStrategyEnum::VARIABLE_MODIFIER,
            'priority' => ModifierPriorityEnum::ADDITIVE_MODIFIER_VALUE,
            'applyOnTarget' => false,
            'modifierRange' => 'player',
            'type' => 'variable_event_modifier',
            'triggeredEvent' => null,
            'visibility' => null,
            'delta' => -1,
            'targetVariable' => PlayerVariableEnum::ACTION_POINT,
            'mode' => 'additive',
            'modifierActivationRequirements' => [],
            'tagConstraints' => [
                ActionEnum::WASH_IN_SINK => ModifierRequirementEnum::ANY_TAGS,
                ActionEnum::SHOWER => ModifierRequirementEnum::ANY_TAGS,
            ],
        ],
        [
            'name' => 'modifier_for_player_x1.1percentage_on_action_shoot_hunter',
            'modifierName' => null,
            'targetEvent' => ActionVariableEvent::ROLL_ACTION_PERCENTAGE,
            'strategy' => ModifierStrategyEnum::VARIABLE_MODIFIER,
            'priority' => ModifierPriorityEnum::MULTIPLICATIVE_MODIFIER_VALUE,
            'applyOnTarget' => false,
            'modifierRange' => 'player',
            'type' => 'variable_event_modifier',
            'triggeredEvent' => null,
            'visibility' => null,
            'delta' => 1.1,
            'targetVariable' => ActionVariableEnum::PERCENTAGE_SUCCESS,
            'mode' => 'multiplicative',
            'modifierActivationRequirements' => [],
            'tagConstraints' => [ActionTypeEnum::ACTION_SHOOT_HUNTER => ModifierRequirementEnum::ANY_TAGS],
        ],
        [
            'name' => 'modifier_for_player_+2movementPoint_on_event_action_movement_conversion',
            'modifierName' => ModifierNameEnum::ANTIGRAV_SCOOTER_CONVERSION_MODIFIER,
            'targetEvent' => ActionVariableEvent::APPLY_COST,
            'strategy' => ModifierStrategyEnum::VARIABLE_MODIFIER,
            'priority' => ModifierPriorityEnum::ADDITIVE_MODIFIER_VALUE,
            'applyOnTarget' => false,
            'modifierRange' => 'player',
            'type' => 'variable_event_modifier',
            'triggeredEvent' => null,
            'visibility' => null,
            'delta' => -2.0,
            'targetVariable' => 'movementPoint',
            'mode' => 'additive',
            'modifierActivationRequirements' => [],
            'tagConstraints' => [ActionEnum::CONVERT_ACTION_TO_MOVEMENT => ModifierRequirementEnum::ALL_TAGS],
        ],
        [
            'name' => 'modifier_for_player_+1movementPoint_on_event_action_movement_conversion_if_cycle_even',
            'modifierName' => null,
            'targetEvent' => ActionVariableEvent::APPLY_COST,
            'strategy' => ModifierStrategyEnum::VARIABLE_MODIFIER,
            'priority' => ModifierPriorityEnum::ADDITIVE_MODIFIER_VALUE,
            'applyOnTarget' => false,
            'modifierRange' => 'player',
            'type' => 'variable_event_modifier',
            'triggeredEvent' => null,
            'visibility' => null,
            'delta' => -1.0,
            'targetVariable' => 'movementPoint',
            'mode' => 'additive',
            'modifierActivationRequirements' => [
                'cycle_even',
            ],
            'tagConstraints' => [ActionEnum::CONVERT_ACTION_TO_MOVEMENT => ModifierRequirementEnum::ALL_TAGS],
        ],
        [
            'name' => 'modifier_for_player_x2percentage_on_strengthen_hull',
            'modifierName' => null,
            'targetEvent' => ActionVariableEvent::ROLL_ACTION_PERCENTAGE,
            'strategy' => ModifierStrategyEnum::VARIABLE_MODIFIER,
            'priority' => ModifierPriorityEnum::MULTIPLICATIVE_MODIFIER_VALUE,
            'applyOnTarget' => false,
            'modifierRange' => 'player',
            'type' => 'variable_event_modifier',
            'triggeredEvent' => null,
            'visibility' => null,
            'delta' => 2.0,
            'targetVariable' => ActionVariableEnum::PERCENTAGE_SUCCESS,
            'mode' => 'multiplicative',
            'modifierActivationRequirements' => [],
            'tagConstraints' => [ActionEnum::STRENGTHEN_HULL => ModifierRequirementEnum::ANY_TAGS],
        ],
        [
            'name' => 'modifier_for_player_x2percentage_on_renovate',
            'modifierName' => null,
            'targetEvent' => ActionVariableEvent::ROLL_ACTION_PERCENTAGE,
            'strategy' => ModifierStrategyEnum::VARIABLE_MODIFIER,
            'priority' => ModifierPriorityEnum::MULTIPLICATIVE_MODIFIER_VALUE,
            'applyOnTarget' => false,
            'modifierRange' => 'player',
            'type' => 'variable_event_modifier',
            'triggeredEvent' => null,
            'visibility' => null,
            'delta' => 2.0,
            'targetVariable' => ActionVariableEnum::PERCENTAGE_SUCCESS,
            'mode' => 'multiplicative',
            'modifierActivationRequirements' => [],
            'tagConstraints' => [ActionEnum::RENOVATE => ModifierRequirementEnum::ANY_TAGS],
        ],
        [
            'name' => 'modifier_for_player_x2hull_on_change.variable_if_reason_strengthen_hull',
            'modifierName' => null,
            'targetEvent' => 'change.variable',
            'strategy' => ModifierStrategyEnum::VARIABLE_MODIFIER,
            'priority' => ModifierPriorityEnum::MULTIPLICATIVE_MODIFIER_VALUE,
            'applyOnTarget' => false,
            'modifierRange' => 'player',
            'type' => 'variable_event_modifier',
            'triggeredEvent' => null,
            'visibility' => null,
            'delta' => 2.0,
            'targetVariable' => 'hull',
            'mode' => 'multiplicative',
            'modifierActivationRequirements' => [],
            'tagConstraints' => [ActionEnum::STRENGTHEN_HULL => ModifierRequirementEnum::ANY_TAGS],
        ],
        [
            'name' => 'modifier_for_daedalus_-1actionPoint_on_TODO coms. action',
            'modifierName' => null,
            'targetEvent' => ActionVariableEvent::APPLY_COST,
            'strategy' => ModifierStrategyEnum::VARIABLE_MODIFIER,
            'priority' => ModifierPriorityEnum::ADDITIVE_MODIFIER_VALUE,
            'applyOnTarget' => false,
            'modifierRange' => 'daedalus',
            'type' => 'variable_event_modifier',
            'triggeredEvent' => null,
            'visibility' => null,
            'delta' => -1.0,
            'targetVariable' => 'actionPoint',
            'mode' => 'additive',
            'modifierActivationRequirements' => [],
            'tagConstraints' => [ActionEnum::CONTACT_SOL => ModifierRequirementEnum::ALL_TAGS],
        ],
        [
            'name' => 'modifier_for_daedalus_-1movementPoint_on_event_action_movement_conversion',
            'modifierName' => null,
            'targetEvent' => ActionVariableEvent::APPLY_COST,
            'strategy' => ModifierStrategyEnum::VARIABLE_MODIFIER,
            'priority' => ModifierPriorityEnum::ADDITIVE_MODIFIER_VALUE,
            'applyOnTarget' => false,
            'modifierRange' => 'daedalus',
            'type' => 'variable_event_modifier',
            'triggeredEvent' => null,
            'visibility' => null,
            'delta' => 1.0,
            'targetVariable' => 'movementPoint',
            'mode' => 'additive',
            'modifierActivationRequirements' => [],
            'tagConstraints' => [ActionEnum::CONVERT_ACTION_TO_MOVEMENT => ModifierRequirementEnum::ALL_TAGS],
        ],
        [
            'name' => 'modifier_for_daedalus_-1movementPoint_on_change.variable_if_reason_new_cycle',
            'modifierName' => null,
            'targetEvent' => 'change.variable',
            'strategy' => ModifierStrategyEnum::VARIABLE_MODIFIER,
            'priority' => ModifierPriorityEnum::ADDITIVE_MODIFIER_VALUE,
            'applyOnTarget' => true,
            'modifierRange' => 'daedalus',
            'type' => 'variable_event_modifier',
            'delta' => -1.0,
            'targetVariable' => PlayerVariableEnum::MOVEMENT_POINT,
            'mode' => 'additive',
            'modifierActivationRequirements' => [],
            'tagConstraints' => ['base_player_cycle_change' => ModifierRequirementEnum::ALL_TAGS],
        ],
        [
            'name' => 'modifier_for_daedalus_+1oxygen_on_change.variable_if_reason_new_cycle',
            'modifierName' => null,
            'targetEvent' => 'change.variable',
            'strategy' => ModifierStrategyEnum::VARIABLE_MODIFIER,
            'priority' => ModifierPriorityEnum::ADDITIVE_MODIFIER_VALUE,
            'applyOnTarget' => false,
            'modifierRange' => 'daedalus',
            'type' => 'variable_event_modifier',
            'triggeredEvent' => null,
            'visibility' => null,
            'delta' => 1.0,
            'targetVariable' => 'oxygen',
            'mode' => 'additive',
            'modifierActivationRequirements' => [],
            'tagConstraints' => ['base_daedalus_cycle_change' => ModifierRequirementEnum::ALL_TAGS],
        ],
        [
            'name' => 'modifier_for_player_+2movementPoint_on_move_if_item_in_room_schrodinger',
            'modifierName' => null,
            'targetEvent' => ActionVariableEvent::APPLY_COST,
            'strategy' => ModifierStrategyEnum::VARIABLE_MODIFIER,
            'priority' => ModifierPriorityEnum::ADDITIVE_MODIFIER_VALUE,
            'applyOnTarget' => false,
            'modifierRange' => 'player',
            'type' => 'variable_event_modifier',
            'triggeredEvent' => null,
            'visibility' => null,
            'delta' => 2.0,
            'targetVariable' => 'movementPoint',
            'mode' => 'additive',
            'modifierActivationRequirements' => [
                'item_in_room_schrodinger',
            ],
            'tagConstraints' => [
                ActionEnum::MOVE => ModifierRequirementEnum::ALL_TAGS,
                ActionTypeEnum::ACTION_ADMIN => ModifierRequirementEnum::NONE_TAGS,
            ],
        ],
        [
            'name' => 'modifier_for_player_+2actionPoint_on_actions_if_item_in_room_schrodinger_if_not_reason_move',
            'modifierName' => null,
            'targetEvent' => ActionVariableEvent::APPLY_COST,
            'strategy' => ModifierStrategyEnum::VARIABLE_MODIFIER,
            'priority' => ModifierPriorityEnum::ADDITIVE_MODIFIER_VALUE,
            'applyOnTarget' => false,
            'modifierRange' => 'player',
            'type' => 'variable_event_modifier',
            'triggeredEvent' => null,
            'visibility' => null,
            'delta' => 2.0,
            'targetVariable' => 'actionPoint',
            'mode' => 'additive',
            'modifierActivationRequirements' => [
                'item_in_room_schrodinger',
            ],
            'tagConstraints' => [
                ActionEnum::MOVE => ModifierRequirementEnum::NONE_TAGS,
                ActionTypeEnum::ACTION_ADMIN => ModifierRequirementEnum::NONE_TAGS, ],
        ],
        [
            'name' => 'screaming_for_player_set_-1actionPoint_on_new_cycle_if_random_16',
            'modifierName' => 'screaming',
            'targetEvent' => 'disease.new.cycle',
            'strategy' => ModifierStrategyEnum::ADD_EVENT,
            'priority' => ModifierPriorityEnum::AFTER_INITIAL_EVENT,
            'applyOnTarget' => true,
            'modifierRange' => 'player',
            'type' => 'trigger_event_modifier',
            'replaceEvent' => false,
            'triggeredEvent' => 'change.variable_player_-1_actionPoint',
            'modifierActivationRequirements' => [
                'random_16',
            ],
            'tagConstraints' => [],
        ],
        [
            'name' => 'wall_head_bang_for_player_set_-1healthPoint_on_new_cycle_if_random_16',
            'modifierName' => 'wall_head_bang',
            'targetEvent' => 'disease.new.cycle',
            'strategy' => ModifierStrategyEnum::ADD_EVENT,
            'priority' => ModifierPriorityEnum::AFTER_INITIAL_EVENT,
            'applyOnTarget' => true,
            'modifierRange' => 'player',
            'type' => 'trigger_event_modifier',
            'replaceEvent' => false,
            'triggeredEvent' => 'change.variable_player_-1_healthPoint',
            'modifierActivationRequirements' => [
                'random_16',
            ],
            'tagConstraints' => [],
        ],
        [
            'name' => 'modifier_for_player_set_-1moralPoint_on_new_cycle_if_random_70',
            'modifierName' => null,
            'targetEvent' => 'disease.new.cycle',
            'strategy' => ModifierStrategyEnum::ADD_EVENT,
            'priority' => ModifierPriorityEnum::AFTER_INITIAL_EVENT,
            'applyOnTarget' => true,
            'modifierRange' => 'player',
            'type' => 'trigger_event_modifier',
            'replaceEvent' => false,
            'triggeredEvent' => 'change.variable_player_-1_moralPoint',
            'modifierActivationRequirements' => [
                'random_70',
            ],
            'tagConstraints' => [],
        ],
        [
            'name' => 'run_in_circles_for_player_set_-2movementPoint_on_new_cycle_if_random_16',
            'modifierName' => 'run_in_circles',
            'targetEvent' => 'disease.new.cycle',
            'strategy' => ModifierStrategyEnum::ADD_EVENT,
            'priority' => ModifierPriorityEnum::AFTER_INITIAL_EVENT,
            'applyOnTarget' => true,
            'modifierRange' => 'player',
            'type' => 'trigger_event_modifier',
            'replaceEvent' => false,
            'triggeredEvent' => 'change.variable_player_-2_movementPoint',
            'modifierActivationRequirements' => [
                'random_16',
            ],
            'tagConstraints' => [],
        ],
        [
            'name' => 'modifier_for_player_+1actionPoint_on_actions_if_player_in_room_four_people',
            'modifierName' => null,
            'targetEvent' => ActionVariableEvent::APPLY_COST,
            'strategy' => ModifierStrategyEnum::VARIABLE_MODIFIER,
            'priority' => ModifierPriorityEnum::ADDITIVE_MODIFIER_VALUE,
            'applyOnTarget' => true,
            'modifierRange' => 'player',
            'type' => 'variable_event_modifier',
            'triggeredEvent' => null,
            'visibility' => null,
            'delta' => 1.0,
            'targetVariable' => 'actionPoint',
            'mode' => 'additive',
            'modifierActivationRequirements' => [
                'player_in_room_four_people',
            ],
            'tagConstraints' => [
                ActionTypeEnum::ACTION_ADMIN => ModifierRequirementEnum::NONE_TAGS,
            ],
        ],
        [
            'name' => 'modifier_for_player_+1movementPoint_on_actions_if_player_in_room_four_people',
            'modifierName' => null,
            'targetEvent' => ActionVariableEvent::APPLY_COST,
            'strategy' => ModifierStrategyEnum::VARIABLE_MODIFIER,
            'priority' => ModifierPriorityEnum::ADDITIVE_MODIFIER_VALUE,
            'applyOnTarget' => false,
            'modifierRange' => 'player',
            'type' => 'variable_event_modifier',
            'triggeredEvent' => null,
            'visibility' => null,
            'delta' => 1.0,
            'targetVariable' => 'movementPoint',
            'mode' => 'additive',
            'modifierActivationRequirements' => [
                'player_in_room_four_people',
            ],
            'tagConstraints' => [
                ActionTypeEnum::ACTION_ADMIN => ModifierRequirementEnum::NONE_TAGS,
            ],
        ],
        [
            'name' => 'direct_modifier_player_-2_max_actionPoint',
            'modifierName' => null,
            'revertOnRemove' => true,
            'modifierRange' => 'player',
            'type' => 'direct_modifier',
            'triggeredEvent' => 'change.value.max_player_-2_actionPoint',
            'modifierActivationRequirements' => [],
        ],
        [
            'name' => 'direct_modifier_player_-3_max_moralPoint',
            'modifierName' => null,
            'revertOnRemove' => true,
            'modifierRange' => 'player',
            'type' => 'direct_modifier',
            'triggeredEvent' => 'change.value.max_player_-3_moralPoint',
            'modifierActivationRequirements' => [],
        ],
        [
            'name' => 'direct_modifier_player_-4_max_moralPoint',
            'modifierName' => null,
            'revertOnRemove' => true,
            'modifierRange' => 'player',
            'type' => 'direct_modifier',
            'triggeredEvent' => 'change.value.max_player_-4_moralPoint',
            'modifierActivationRequirements' => [],
        ],
        [
            'name' => 'modifier_for_player_+1actionPoint',
            'modifierName' => null,
            'targetEvent' => ActionVariableEvent::APPLY_COST,
            'strategy' => ModifierStrategyEnum::VARIABLE_MODIFIER,
            'priority' => ModifierPriorityEnum::ADDITIVE_MODIFIER_VALUE,
            'applyOnTarget' => false,
            'modifierRange' => 'player',
            'type' => 'variable_event_modifier',
            'triggeredEvent' => null,
            'visibility' => null,
            'delta' => 1.0,
            'targetVariable' => 'actionPoint',
            'mode' => 'additive',
            'modifierActivationRequirements' => [],
            'tagConstraints' => [
                ActionEnum::MOVE => ModifierRequirementEnum::NONE_TAGS,
                ActionEnum::CONSUME => ModifierRequirementEnum::NONE_TAGS,
                ActionEnum::SURGERY => ModifierRequirementEnum::NONE_TAGS,
                ActionEnum::SELF_SURGERY => ModifierRequirementEnum::NONE_TAGS,
                ActionTypeEnum::ACTION_ADMIN => ModifierRequirementEnum::NONE_TAGS,
            ],
        ],
        [
            'name' => 'modifier_for_player_+2actionPoint',
            'modifierName' => null,
            'targetEvent' => ActionVariableEvent::APPLY_COST,
            'strategy' => ModifierStrategyEnum::VARIABLE_MODIFIER,
            'priority' => ModifierPriorityEnum::ADDITIVE_MODIFIER_VALUE,
            'applyOnTarget' => false,
            'modifierRange' => 'player',
            'type' => 'variable_event_modifier',
            'triggeredEvent' => null,
            'visibility' => null,
            'delta' => 2.0,
            'targetVariable' => 'actionPoint',
            'mode' => 'additive',
            'modifierActivationRequirements' => [],
            'tagConstraints' => [
                ActionEnum::MOVE => ModifierRequirementEnum::NONE_TAGS,
                ActionEnum::CONSUME => ModifierRequirementEnum::NONE_TAGS,
                ActionEnum::SURGERY => ModifierRequirementEnum::NONE_TAGS,
                ActionEnum::SELF_SURGERY => ModifierRequirementEnum::NONE_TAGS,
                ActionTypeEnum::ACTION_ADMIN => ModifierRequirementEnum::NONE_TAGS,
            ],
        ],
        [
            'name' => 'modifier_for_player_+3actionPoint',
            'modifierName' => null,
            'targetEvent' => ActionVariableEvent::APPLY_COST,
            'strategy' => ModifierStrategyEnum::VARIABLE_MODIFIER,
            'priority' => ModifierPriorityEnum::ADDITIVE_MODIFIER_VALUE,
            'applyOnTarget' => false,
            'modifierRange' => 'player',
            'type' => 'variable_event_modifier',
            'triggeredEvent' => null,
            'visibility' => null,
            'delta' => 3.0,
            'targetVariable' => 'actionPoint',
            'mode' => 'additive',
            'modifierActivationRequirements' => [],
            'tagConstraints' => [
                ActionEnum::MOVE => ModifierRequirementEnum::NONE_TAGS,
                ActionEnum::CONSUME => ModifierRequirementEnum::NONE_TAGS,
                ActionEnum::SURGERY => ModifierRequirementEnum::NONE_TAGS,
                ActionEnum::SELF_SURGERY => ModifierRequirementEnum::NONE_TAGS,
                ActionTypeEnum::ACTION_ADMIN => ModifierRequirementEnum::NONE_TAGS,
            ],
        ],
        [
            'name' => 'direct_modifier_player_-3_max_movementPoint',
            'modifierName' => null,
            'revertOnRemove' => true,
            'modifierRange' => 'player',
            'type' => 'direct_modifier',
            'triggeredEvent' => 'change.value.max_player_-3_movementPoint',
            'modifierActivationRequirements' => [],
        ],
        [
            'name' => 'direct_modifier_player_-5_max_movementPoint',
            'modifierName' => null,
            'revertOnRemove' => true,
            'modifierRange' => 'player',
            'type' => 'direct_modifier',
            'triggeredEvent' => 'change.value.max_player_-5_movementPoint',
            'modifierActivationRequirements' => [],
        ],
        [
            'name' => 'direct_modifier_player_-12_max_movementPoint',
            'modifierName' => null,
            'revertOnRemove' => true,
            'modifierRange' => 'player',
            'type' => 'direct_modifier',
            'triggeredEvent' => 'change.value.max_player_-12_movementPoint',
            'modifierActivationRequirements' => [],
        ],
        [
            'name' => 'modifier_for_player_x0.85percentage_on_action_shoot',
            'modifierName' => null,
            'targetEvent' => ActionVariableEvent::ROLL_ACTION_PERCENTAGE,
            'strategy' => ModifierStrategyEnum::VARIABLE_MODIFIER,
            'priority' => ModifierPriorityEnum::MULTIPLICATIVE_MODIFIER_VALUE,
            'applyOnTarget' => false,
            'modifierRange' => 'player',
            'type' => 'variable_event_modifier',
            'triggeredEvent' => null,
            'visibility' => null,
            'delta' => 0.85,
            'targetVariable' => ActionVariableEnum::PERCENTAGE_SUCCESS,
            'mode' => 'multiplicative',
            'modifierActivationRequirements' => [],
            'tagConstraints' => [
                ActionEnum::SHOOT => ModifierRequirementEnum::ANY_TAGS,
            ],
        ],
        [
            'name' => 'modifier_for_player_x0.8percentage_on_action_shoot',
            'modifierName' => null,
            'targetEvent' => ActionVariableEvent::ROLL_ACTION_PERCENTAGE,
            'strategy' => ModifierStrategyEnum::VARIABLE_MODIFIER,
            'priority' => ModifierPriorityEnum::MULTIPLICATIVE_MODIFIER_VALUE,
            'applyOnTarget' => false,
            'modifierRange' => 'player',
            'type' => 'variable_event_modifier',
            'triggeredEvent' => null,
            'visibility' => null,
            'delta' => 0.8,
            'targetVariable' => ActionVariableEnum::PERCENTAGE_SUCCESS,
            'mode' => 'multiplicative',
            'modifierActivationRequirements' => [],
            'tagConstraints' => [
                ActionEnum::SHOOT => ModifierRequirementEnum::ANY_TAGS,
            ],
        ],
        [
            'name' => 'modifier_for_player_x0.6percentage_on_action_shoot',
            'modifierName' => null,
            'targetEvent' => ActionVariableEvent::ROLL_ACTION_PERCENTAGE,
            'strategy' => ModifierStrategyEnum::VARIABLE_MODIFIER,
            'priority' => ModifierPriorityEnum::MULTIPLICATIVE_MODIFIER_VALUE,
            'applyOnTarget' => false,
            'modifierRange' => 'player',
            'type' => 'variable_event_modifier',
            'triggeredEvent' => null,
            'visibility' => null,
            'delta' => 0.6,
            'targetVariable' => ActionVariableEnum::PERCENTAGE_SUCCESS,
            'mode' => 'multiplicative',
            'modifierActivationRequirements' => [],
            'tagConstraints' => [
                ActionEnum::SHOOT => ModifierRequirementEnum::ANY_TAGS,
            ],
        ],
        [
            'name' => 'modifier_for_equipment_+1actionPoint_on_consume',
            'modifierName' => null,
            'targetEvent' => ActionVariableEvent::APPLY_COST,
            'strategy' => ModifierStrategyEnum::VARIABLE_MODIFIER,
            'priority' => ModifierPriorityEnum::ADDITIVE_MODIFIER_VALUE,
            'applyOnTarget' => true,
            'modifierRange' => 'equipment',
            'type' => 'variable_event_modifier',
            'triggeredEvent' => null,
            'visibility' => null,
            'delta' => 1.0,
            'targetVariable' => 'actionPoint',
            'mode' => 'additive',
            'modifierActivationRequirements' => [],
            'tagConstraints' => [
                ActionEnum::CONSUME => ModifierRequirementEnum::ANY_TAGS,
            ],
        ],
        [
            'name' => 'modifier_for_player_-2movementPoint_on_event_action_movement_conversion',
            'modifierName' => null,
            'targetEvent' => ActionVariableEvent::APPLY_COST,
            'strategy' => ModifierStrategyEnum::VARIABLE_MODIFIER,
            'priority' => ModifierPriorityEnum::ADDITIVE_MODIFIER_VALUE,
            'applyOnTarget' => false,
            'modifierRange' => 'player',
            'type' => 'variable_event_modifier',
            'triggeredEvent' => null,
            'visibility' => null,
            'delta' => 2.0,
            'targetVariable' => 'movementPoint',
            'mode' => 'additive',
            'modifierActivationRequirements' => [],
            'tagConstraints' => [ActionEnum::CONVERT_ACTION_TO_MOVEMENT => ModifierRequirementEnum::ALL_TAGS],
        ],
        [
            'name' => 'modifier_for_player_-1movementPoint_on_move_if_player_in_room_not_alone',
            'modifierName' => ModifierNameEnum::DISABLED_MOVE_MODIFIER,
            'targetEvent' => ActionVariableEvent::APPLY_COST,
            'strategy' => ModifierStrategyEnum::VARIABLE_MODIFIER,
            'priority' => ModifierPriorityEnum::ADDITIVE_MODIFIER_VALUE,
            'applyOnTarget' => false,
            'modifierRange' => 'player',
            'type' => 'variable_event_modifier',
            'triggeredEvent' => null,
            'visibility' => null,
            'delta' => -1.0,
            'targetVariable' => 'movementPoint',
            'mode' => 'additive',
            'modifierActivationRequirements' => [
                'player_in_room_not_alone',
            ],
            'tagConstraints' => [
                ActionEnum::MOVE => ModifierRequirementEnum::ANY_TAGS,
            ],
        ],
        [
            'name' => 'modifier_for_place_+2actionPoint_on_action_aggressive',
            'modifierName' => null,
            'targetEvent' => ActionVariableEvent::APPLY_COST,
            'strategy' => ModifierStrategyEnum::VARIABLE_MODIFIER,
            'priority' => ModifierPriorityEnum::ADDITIVE_MODIFIER_VALUE,
            'applyOnTarget' => false,
            'modifierRange' => 'place',
            'type' => 'variable_event_modifier',
            'triggeredEvent' => null,
            'visibility' => null,
            'delta' => 2.0,
            'targetVariable' => 'actionPoint',
            'mode' => 'additive',
            'modifierActivationRequirements' => [],
            'tagConstraints' => [ActionTypeEnum::ACTION_AGGRESSIVE => ModifierRequirementEnum::ALL_TAGS],
        ],
        [
            'name' => 'modifier_for_player_+2movementPoint_on_move',
            'modifierName' => null,
            'targetEvent' => ActionVariableEvent::APPLY_COST,
            'strategy' => ModifierStrategyEnum::VARIABLE_MODIFIER,
            'priority' => ModifierPriorityEnum::ADDITIVE_MODIFIER_VALUE,
            'applyOnTarget' => false,
            'modifierRange' => 'player',
            'type' => 'variable_event_modifier',
            'triggeredEvent' => null,
            'visibility' => null,
            'delta' => 2.0,
            'targetVariable' => 'movementPoint',
            'mode' => 'additive',
            'modifierActivationRequirements' => [],
            'tagConstraints' => [
                ActionEnum::MOVE => ModifierRequirementEnum::ALL_TAGS,
                DaedalusStatusEnum::NO_GRAVITY => ModifierRequirementEnum::NONE_TAGS,
            ],
        ],
        [
            'name' => 'antisocial_modifier_for_player_-1moralPoint_on_new_cycle_if_player_in_room_not_alone',
            'modifierName' => 'antisocial_modifier',
            'targetEvent' => 'disease.new.cycle',
            'strategy' => ModifierStrategyEnum::ADD_EVENT,
            'priority' => ModifierPriorityEnum::AFTER_INITIAL_EVENT,
            'applyOnTarget' => true,
            'modifierRange' => 'player',
            'type' => 'trigger_event_modifier',
            'replaceEvent' => false,
            'triggeredEvent' => 'change.variable_player_-1_moralPoint',
            'modifierActivationRequirements' => [
                'player_in_room_not_alone',
            ],
            'tagConstraints' => [],
        ],
        [
            'name' => 'modifier_for_player_-1moralPoint_on_new_cycle',
            'modifierName' => null,
            'targetEvent' => 'disease.new.cycle',
            'strategy' => ModifierStrategyEnum::ADD_EVENT,
            'priority' => ModifierPriorityEnum::AFTER_INITIAL_EVENT,
            'applyOnTarget' => true,
            'modifierRange' => 'player',
            'type' => 'trigger_event_modifier',
            'replaceEvent' => false,
            'triggeredEvent' => 'change.variable_player_-1_moralPoint',
            'modifierActivationRequirements' => [],
            'tagConstraints' => [],
        ],
        [
            'name' => 'lying_down_modifier_for_player_+1actionPoint_on_new_cycle',
            'modifierName' => 'lying_down_modifier',
            'targetEvent' => VariableEventInterface::CHANGE_VARIABLE,
            'strategy' => ModifierStrategyEnum::VARIABLE_MODIFIER,
            'priority' => ModifierPriorityEnum::ADDITIVE_MODIFIER_VALUE,
            'applyOnTarget' => true,
            'modifierRange' => 'player',
            'type' => 'variable_event_modifier',
            'triggeredEvent' => null,
            'visibility' => null,
            'delta' => 1.0,
            'targetVariable' => 'actionPoint',
            'mode' => 'additive',
            'modifierActivationRequirements' => [],
            'tagConstraints' => ['base_player_cycle_change' => ModifierRequirementEnum::ALL_TAGS],
        ],
        [
            'name' => 'starving_for_player_-1healthPoint_on_new_cycle',
            'modifierName' => 'starving',
            'targetEvent' => 'disease.new.cycle',
            'strategy' => ModifierStrategyEnum::ADD_EVENT,
            'priority' => ModifierPriorityEnum::AFTER_INITIAL_EVENT,
            'applyOnTarget' => true,
            'modifierRange' => 'player',
            'type' => 'trigger_event_modifier',
            'replaceEvent' => false,
            'triggeredEvent' => 'change.variable_player_-1_healthPoint',
            'modifierActivationRequirements' => [],
            'tagConstraints' => [],
        ],
        [
            'name' => 'modifier_for_player_+30percentage_on_cycle_disease',
            'modifierName' => null,
            'targetEvent' => RollPercentageEvent::ROLL_PERCENTAGE,
            'strategy' => ModifierStrategyEnum::VARIABLE_MODIFIER,
            'priority' => ModifierPriorityEnum::ADDITIVE_MODIFIER_VALUE,
            'applyOnTarget' => false,
            'modifierRange' => 'player',
            'type' => 'variable_event_modifier',
            'triggeredEvent' => null,
            'visibility' => null,
            'delta' => 30.0,
            'targetVariable' => ActionVariableEnum::PERCENTAGE_SUCCESS,
            'mode' => 'additive',
            'modifierActivationRequirements' => [],
            'tagConstraints' => [PlayerEvent::CYCLE_DISEASE => ModifierRequirementEnum::ALL_TAGS],
        ],
        [
            'name' => 'mush_shower_malus_for_player_set_-3healthPoint_on_post.action_if_reason_shower',
            'modifierName' => 'mush_shower_malus',
            'targetEvent' => 'post.action',
            'strategy' => ModifierStrategyEnum::ADD_EVENT,
            'priority' => ModifierPriorityEnum::AFTER_INITIAL_EVENT,
            'applyOnTarget' => false,
            'modifierRange' => 'player',
            'type' => 'trigger_event_modifier',
            'replaceEvent' => false,
            'triggeredEvent' => 'change.variable_player_-3_healthPoint',
            'modifierActivationRequirements' => [],
            'tagConstraints' => [
                ActionEnum::SHOWER => ModifierRequirementEnum::ANY_TAGS,
                ActionEnum::WASH_IN_SINK => ModifierRequirementEnum::ANY_TAGS,
            ],
        ],
        [
            'name' => 'modifier_for_player_set_4satiety_on_change.variable_if_reason_consume',
            'modifierName' => ModifierNameEnum::MUSH_CONSUME,
            'targetEvent' => 'change.variable',
            'strategy' => ModifierStrategyEnum::VARIABLE_MODIFIER,
            'priority' => ModifierPriorityEnum::OVERRIDE_VALUE_PRIORITY,
            'applyOnTarget' => true,
            'modifierRange' => 'player',
            'type' => 'variable_event_modifier',
            'triggeredEvent' => null,
            'visibility' => null,
            'delta' => 4.0,
            'targetVariable' => 'satiety',
            'mode' => 'set_value',
            'modifierActivationRequirements' => [],
            'tagConstraints' => [
                ActionEnum::CONSUME => ModifierRequirementEnum::ANY_TAGS,
            ],
        ],
        [
            'name' => 'modifier_for_player_prevent_change.variable_if_reason_consume',
            'modifierName' => null,
            'targetEvent' => 'change.variable',
            'strategy' => ModifierStrategyEnum::PREVENT_EVENT,
            'priority' => ModifierPriorityEnum::PREVENT_EVENT,
            'applyOnTarget' => true,
            'modifierRange' => 'player',
            'type' => 'event_modifier',
            'modifierActivationRequirements' => [],
            'tagConstraints' => [
                ActionEnum::CONSUME => ModifierRequirementEnum::ALL_TAGS,
                PlayerVariableEnum::HEALTH_POINT => ModifierRequirementEnum::ANY_TAGS,
                PlayerVariableEnum::MORAL_POINT => ModifierRequirementEnum::ANY_TAGS,
                PlayerVariableEnum::MOVEMENT_POINT => ModifierRequirementEnum::ANY_TAGS,
                PlayerVariableEnum::ACTION_POINT => ModifierRequirementEnum::ANY_TAGS,
            ],
        ],
        [
            'name' => 'deaf_ON_new_message_default',
            'modifierName' => MessageModificationEnum::DEAF_SPEAK,
            'targetEvent' => 'new_message',
            'strategy' => ModifierStrategyEnum::MESSAGE_MODIFIER,
            'priority' => ModifierPriorityEnum::OVERRIDE_VALUE_PRIORITY,
            'type' => 'event_modifier',
            'applyOnTarget' => true,
            'modifierRange' => 'player',
            'modifierActivationRequirements' => [],
            'tagConstraints' => [],
        ],
        [
            'name' => 'deaf_ON_read_message_default',
            'modifierName' => MessageModificationEnum::DEAF_LISTEN,
            'targetEvent' => 'read_message',
            'strategy' => ModifierStrategyEnum::MESSAGE_MODIFIER,
            'priority' => ModifierPriorityEnum::OVERRIDE_VALUE_PRIORITY,
            'type' => 'event_modifier',
            'applyOnTarget' => true,
            'modifierRange' => 'player',
            'modifierActivationRequirements' => [],
            'tagConstraints' => [],
        ],
        [
            'name' => 'paranoia_ON_read_message_default',
            'modifierName' => MessageModificationEnum::PARANOIA_DENIAL,
            'targetEvent' => 'read_message',
            'strategy' => ModifierStrategyEnum::MESSAGE_MODIFIER,
            'priority' => ModifierPriorityEnum::OVERRIDE_VALUE_PRIORITY,
            'type' => 'event_modifier',
            'applyOnTarget' => true,
            'modifierRange' => 'player',
            'modifierActivationRequirements' => [],
            'tagConstraints' => [],
        ],
        [
            'name' => 'paranoia_ON_new_message_default',
            'modifierName' => MessageModificationEnum::PARANOIA_MESSAGES,
            'targetEvent' => 'new_message',
            'strategy' => ModifierStrategyEnum::MESSAGE_MODIFIER,
            'priority' => ModifierPriorityEnum::OVERRIDE_VALUE_PRIORITY,
            'type' => 'event_modifier',
            'applyOnTarget' => true,
            'modifierRange' => 'player',
            'modifierActivationRequirements' => [],
            'tagConstraints' => [],
        ],
        [
            'name' => 'coprolalia_ON_new_message_default',
            'modifierName' => MessageModificationEnum::COPROLALIA_MESSAGES,
            'targetEvent' => 'new_message',
            'strategy' => ModifierStrategyEnum::MESSAGE_MODIFIER,
            'priority' => ModifierPriorityEnum::OVERRIDE_VALUE_PRIORITY,
            'type' => 'event_modifier',
            'applyOnTarget' => true,
            'modifierRange' => 'player',
            'modifierActivationRequirements' => [],
            'tagConstraints' => [],
        ],
        [
            'name' => 'prevent_move',
            'modifierName' => 'prevent_move',
            'targetEvent' => ActionEvent::PRE_ACTION,
            'strategy' => ModifierStrategyEnum::PREVENT_EVENT,
            'priority' => ModifierPriorityEnum::PREVENT_EVENT,
            'applyOnTarget' => false,
            'modifierRange' => 'player',
            'type' => 'event_modifier',
            'triggeredEvent' => null,
            'modifierActivationRequirements' => [],
            'tagConstraints' => [
                ActionEnum::MOVE => ModifierRequirementEnum::ANY_TAGS,
            ],
        ],
        [
            'name' => 'prevent_pick_heavy_item',
            'modifierName' => 'prevent_pick_heavy_item',
            'targetEvent' => ActionEvent::PRE_ACTION,
            'strategy' => ModifierStrategyEnum::PREVENT_EVENT,
            'priority' => ModifierPriorityEnum::PREVENT_EVENT,
            'applyOnTarget' => true,
            'modifierRange' => 'player',
            'type' => 'event_modifier',
            'triggeredEvent' => null,
            'modifierActivationRequirements' => ['item_status_heavy'],
            'tagConstraints' => [
                ActionEnum::TAKE => ModifierRequirementEnum::ANY_TAGS,
            ],
        ],
        [
            'name' => 'prevent_attack_actions',
            'modifierName' => 'prevent_attack_actions',
            'targetEvent' => ActionEvent::PRE_ACTION,
            'strategy' => ModifierStrategyEnum::PREVENT_EVENT,
            'priority' => ModifierPriorityEnum::PREVENT_EVENT,
            'applyOnTarget' => false,
            'modifierRange' => 'player',
            'type' => 'event_modifier',
            'triggeredEvent' => null,
            'replaceEvent' => true,
            'modifierActivationRequirements' => [],
            'tagConstraints' => [
                ActionTypeEnum::ACTION_ATTACK => ModifierRequirementEnum::ANY_TAGS,
            ],
        ],
        [
            'name' => 'prevent_piloting_actions',
            'modifierName' => 'prevent_piloting_actions',
            'targetEvent' => ActionEvent::PRE_ACTION,
            'strategy' => ModifierStrategyEnum::PREVENT_EVENT,
            'priority' => ModifierPriorityEnum::PREVENT_EVENT,
            'applyOnTarget' => false,
            'modifierRange' => 'player',
            'type' => 'event_modifier',
            'triggeredEvent' => null,
            'modifierActivationRequirements' => [],
            'tagConstraints' => [
                ActionTypeEnum::ACTION_PILOT => ModifierRequirementEnum::ANY_TAGS,
            ],
        ],
        [
            'name' => 'prevent_shoot_actions',
            'modifierName' => 'prevent_shoot_actions',
            'targetEvent' => ActionEvent::PRE_ACTION,
            'strategy' => ModifierStrategyEnum::PREVENT_EVENT,
            'priority' => ModifierPriorityEnum::PREVENT_EVENT,
            'applyOnTarget' => false,
            'modifierRange' => 'player',
            'type' => 'event_modifier',
            'triggeredEvent' => null,
            'modifierActivationRequirements' => [],
            'tagConstraints' => [
                ActionEnum::SHOOT => ModifierRequirementEnum::ANY_TAGS,
            ],
        ],
        [
            'name' => 'mute_modifier',
            'modifierName' => 'mute_modifier',
            'targetEvent' => MessageEvent::NEW_MESSAGE,
            'strategy' => ModifierStrategyEnum::PREVENT_EVENT,
            'priority' => ModifierPriorityEnum::PREVENT_EVENT,
            'applyOnTarget' => false,
            'modifierRange' => 'player',
            'type' => 'event_modifier',
            'triggeredEvent' => null,
            'modifierActivationRequirements' => [],
            'tagConstraints' => [],
        ],
        [
            'name' => 'septicemia_cycle_change',
            'modifierName' => SymptomEnum::SEPTICEMIA,
            'targetEvent' => DiseaseEvent::DISEASE_NEW_CYCLE,
            'strategy' => ModifierStrategyEnum::SYMPTOM_MODIFIER,
            'priority' => ModifierPriorityEnum::PREVENT_EVENT,
            'applyOnTarget' => true,
            'modifierRange' => 'player',
            'type' => 'event_modifier',
            'modifierActivationRequirements' => ['player_status_dirty'],
            'tagConstraints' => [],
        ],
        [
            'name' => 'septicemia_post_action',
            'modifierName' => SymptomEnum::SEPTICEMIA,
            'targetEvent' => ActionEvent::POST_ACTION,
            'strategy' => ModifierStrategyEnum::SYMPTOM_MODIFIER,
            'priority' => ModifierPriorityEnum::PREVENT_EVENT,
            'applyOnTarget' => false,
            'modifierRange' => 'player',
            'type' => 'event_modifier',
            'modifierActivationRequirements' => ['player_status_dirty'],
            'tagConstraints' => [],
        ],
        [
            'name' => 'septicemia_on_dirty',
            'modifierName' => SymptomEnum::SEPTICEMIA,
            'targetEvent' => StatusEvent::STATUS_APPLIED,
            'strategy' => ModifierStrategyEnum::SYMPTOM_MODIFIER,
            'priority' => ModifierPriorityEnum::PREVENT_EVENT,
            'applyOnTarget' => true,
            'modifierRange' => 'player',
            'type' => 'event_modifier',
            'modifierActivationRequirements' => [],
            'tagConstraints' => [
                PlayerStatusEnum::DIRTY => ModifierRequirementEnum::ANY_TAGS,
            ],
        ],
        [
            'name' => 'fear_of_cat_on_move',
            'modifierName' => SymptomEnum::FEAR_OF_CATS,
            'targetEvent' => ActionEvent::POST_ACTION,
            'strategy' => ModifierStrategyEnum::SYMPTOM_MODIFIER,
            'priority' => ModifierPriorityEnum::PREVENT_EVENT,
            'applyOnTarget' => false,
            'modifierRange' => 'player',
            'type' => 'event_modifier',
            'modifierActivationRequirements' => [
                'random_50',
                'player_equipment_schrodinger',
            ],
            'tagConstraints' => [
                ActionEnum::MOVE => ModifierRequirementEnum::ANY_TAGS,
            ],
        ],
        [
            'name' => 'psychotic_attacks_on_move',
            'modifierName' => SymptomEnum::PSYCHOTIC_ATTACKS,
            'targetEvent' => ActionEvent::POST_ACTION,
            'strategy' => ModifierStrategyEnum::SYMPTOM_MODIFIER,
            'priority' => ModifierPriorityEnum::PREVENT_EVENT,
            'applyOnTarget' => false,
            'modifierRange' => 'player',
            'type' => 'event_modifier',
            'modifierActivationRequirements' => [
                'random_16',
            ],
            'tagConstraints' => [
                ActionEnum::MOVE => ModifierRequirementEnum::ANY_TAGS,
            ],
        ],
        [
            'name' => 'biting_on_cycle',
            'modifierName' => SymptomEnum::BITING,
            'targetEvent' => DiseaseEvent::DISEASE_NEW_CYCLE,
            'strategy' => ModifierStrategyEnum::SYMPTOM_MODIFIER,
            'priority' => ModifierPriorityEnum::PREVENT_EVENT,
            'applyOnTarget' => true,
            'modifierRange' => 'player',
            'type' => 'event_modifier',
            'modifierActivationRequirements' => [
                'random_16',
            ],
            'tagConstraints' => [],
        ],
        [
            'name' => 'breakouts_on_move',
            'modifierName' => SymptomEnum::BREAKOUTS,
            'targetEvent' => ActionEvent::POST_ACTION,
            'strategy' => ModifierStrategyEnum::SYMPTOM_MODIFIER,
            'priority' => ModifierPriorityEnum::PREVENT_EVENT,
            'applyOnTarget' => false,
            'modifierRange' => 'player',
            'type' => 'event_modifier',
            'modifierActivationRequirements' => [
                'random_16',
            ],
            'tagConstraints' => [],
        ],
        [
            'name' => 'cat_allergy_on_take_schrodinger_random16',
            'modifierName' => SymptomEnum::CAT_ALLERGY,
            'targetEvent' => ActionEvent::POST_ACTION,
            'strategy' => ModifierStrategyEnum::SYMPTOM_MODIFIER,
            'priority' => ModifierPriorityEnum::PREVENT_EVENT,
            'applyOnTarget' => false,
            'modifierRange' => 'player',
            'type' => 'event_modifier',
            'modifierActivationRequirements' => [
                'random_16',
            ],
            'tagConstraints' => [
                ActionEnum::TAKE => ModifierRequirementEnum::ALL_TAGS,
                ItemEnum::SCHRODINGER => ModifierRequirementEnum::ALL_TAGS,
            ],
        ],
        [
            'name' => 'cat_sneezing_on_move_random16',
            'modifierName' => SymptomEnum::SNEEZING,
            'targetEvent' => ActionEvent::POST_ACTION,
            'strategy' => ModifierStrategyEnum::SYMPTOM_MODIFIER,
            'priority' => ModifierPriorityEnum::PREVENT_EVENT,
            'applyOnTarget' => false,
            'modifierRange' => 'player',
            'type' => 'event_modifier',
            'modifierActivationRequirements' => [
                'random_16',
                'item_in_room_schrodinger',
            ],
            'tagConstraints' => [
                ActionEnum::MOVE => ModifierRequirementEnum::ANY_TAGS,
            ],
        ],
        [
            'name' => 'vomiting_consume',
            'modifierName' => SymptomEnum::VOMITING,
            'targetEvent' => ActionEvent::POST_ACTION,
            'strategy' => ModifierStrategyEnum::SYMPTOM_MODIFIER,
            'priority' => ModifierPriorityEnum::PREVENT_EVENT,
            'applyOnTarget' => false,
            'modifierRange' => 'player',
            'type' => 'event_modifier',
            'modifierActivationRequirements' => [],
            'tagConstraints' => [
                ActionEnum::CONSUME => ModifierRequirementEnum::ANY_TAGS,
            ],
        ],
        [
            'name' => 'vomiting_move_random_40',
            'modifierName' => SymptomEnum::VOMITING,
            'targetEvent' => ActionEvent::POST_ACTION,
            'strategy' => ModifierStrategyEnum::SYMPTOM_MODIFIER,
            'priority' => ModifierPriorityEnum::PREVENT_EVENT,
            'applyOnTarget' => false,
            'modifierRange' => 'player',
            'type' => 'event_modifier',
            'modifierActivationRequirements' => ['random_40'],
            'tagConstraints' => [
                ActionEnum::MOVE => ModifierRequirementEnum::ANY_TAGS,
            ],
        ],
        [
            'name' => 'cycle_dirtiness',
            'modifierName' => SymptomEnum::DIRTINESS,
            'targetEvent' => DiseaseEvent::DISEASE_NEW_CYCLE,
            'strategy' => ModifierStrategyEnum::SYMPTOM_MODIFIER,
            'priority' => ModifierPriorityEnum::PREVENT_EVENT,
            'applyOnTarget' => true,
            'modifierRange' => 'player',
            'type' => 'event_modifier',
            'modifierActivationRequirements' => [],
            'tagConstraints' => [],
        ],
        [
            'name' => 'cycle_dirtiness_random_40',
            'modifierName' => SymptomEnum::DIRTINESS,
            'targetEvent' => DiseaseEvent::DISEASE_NEW_CYCLE,
            'strategy' => ModifierStrategyEnum::SYMPTOM_MODIFIER,
            'priority' => ModifierPriorityEnum::PREVENT_EVENT,
            'applyOnTarget' => true,
            'modifierRange' => 'player',
            'type' => 'event_modifier',
            'modifierActivationRequirements' => ['random_40'],
            'tagConstraints' => [],
        ],
        [
            'name' => 'drooling_on_move',
            'modifierName' => SymptomEnum::DROOLING,
            'targetEvent' => ActionEvent::POST_ACTION,
            'strategy' => ModifierStrategyEnum::SYMPTOM_MODIFIER,
            'priority' => ModifierPriorityEnum::PREVENT_EVENT,
            'applyOnTarget' => false,
            'modifierRange' => 'player',
            'type' => 'event_modifier',
            'modifierActivationRequirements' => ['random_16'],
            'tagConstraints' => [
                ActionEnum::MOVE => ModifierRequirementEnum::ANY_TAGS,
            ],
        ],
        [
            'name' => 'foaming_on_move',
            'modifierName' => SymptomEnum::FOAMING_MOUTH,
            'targetEvent' => ActionEvent::POST_ACTION,
            'strategy' => ModifierStrategyEnum::SYMPTOM_MODIFIER,
            'priority' => ModifierPriorityEnum::PREVENT_EVENT,
            'applyOnTarget' => false,
            'modifierRange' => 'player',
            'type' => 'event_modifier',
            'modifierActivationRequirements' => ['random_16'],
            'tagConstraints' => [
                ActionEnum::MOVE => ModifierRequirementEnum::ANY_TAGS,
            ],
        ],
        [
            'name' => 'mush_sneezing',
            'modifierName' => SymptomEnum::SNEEZING,
            'targetEvent' => ActionEvent::POST_ACTION,
            'strategy' => ModifierStrategyEnum::SYMPTOM_MODIFIER,
            'priority' => ModifierPriorityEnum::PREVENT_EVENT,
            'applyOnTarget' => false,
            'modifierRange' => 'player',
            'type' => 'event_modifier',
            'modifierActivationRequirements' => [
                'random_16',
                'player_in_room_mush',
            ],
            'tagConstraints' => [
                ActionEnum::MOVE => ModifierRequirementEnum::ANY_TAGS,
            ],
        ],
        [
            'name' => 'modifier_for_player_x1.33percentage_on_action_shoot',
            'modifierName' => null,
            'targetEvent' => ActionVariableEvent::ROLL_ACTION_PERCENTAGE,
            'priority' => ModifierPriorityEnum::MULTIPLICATIVE_MODIFIER_VALUE,
            'applyOnTarget' => false,
            'modifierRange' => 'player',
            'type' => 'variable_event_modifier',
            'triggeredEvent' => null,
            'visibility' => null,
            'delta' => 1.33,
            'targetVariable' => ActionVariableEnum::PERCENTAGE_SUCCESS,
            'mode' => 'multiplicative',
            'modifierActivationRequirements' => [],
            'tagConstraints' => [ActionTypeEnum::ACTION_SHOOT => ModifierRequirementEnum::ANY_TAGS],
        ],
        [
            'name' => 'modifier_for_player_set_0moralPoint_on_change.variable',
            'modifierName' => null,
            'targetEvent' => 'change.variable',
            'applyOnTarget' => true,
            'modifierRange' => 'player',
            'triggeredEvent' => null,
            'priority' => ModifierPriorityEnum::PREVENT_EVENT,
            'visibility' => null,
            'delta' => 0.0,
            'targetVariable' => 'moralPoint',
            'mode' => 'set_value',
            'strategy' => ModifierStrategyEnum::PREVENT_EVENT,
            'type' => 'event_modifier',
            'modifierActivationRequirements' => [],
            'tagConstraints' => [
                PlayerVariableEnum::MORAL_POINT => ModifierRequirementEnum::ANY_TAGS,
                VariableEventInterface::LOSS => ModifierRequirementEnum::ANY_TAGS,
            ],
        ],
        [
            'name' => 'modifier_for_daedalus_+30percentage_on_action_scan',
            'modifierName' => null,
            'targetEvent' => ActionVariableEvent::ROLL_ACTION_PERCENTAGE,
            'strategy' => ModifierStrategyEnum::VARIABLE_MODIFIER,
            'priority' => ModifierPriorityEnum::ADDITIVE_MODIFIER_VALUE,
            'applyOnTarget' => false,
            'modifierRange' => 'daedalus',
            'type' => 'variable_event_modifier',
            'triggeredEvent' => null,
            'visibility' => null,
            'delta' => 30,
            'targetVariable' => ActionVariableEnum::PERCENTAGE_SUCCESS,
            'mode' => 'additive',
            'modifierActivationRequirements' => [],
            'tagConstraints' => [
                ActionEnum::SCAN => ModifierRequirementEnum::ANY_TAGS,
            ],
        ],
        [
            'name' => 'modifier_for_daedalus_-1actionPoint_on_action_analyze_planet',
            'modifierName' => null,
            'targetEvent' => ActionVariableEvent::APPLY_COST,
            'strategy' => ModifierStrategyEnum::VARIABLE_MODIFIER,
            'priority' => ModifierPriorityEnum::ADDITIVE_MODIFIER_VALUE,
            'applyOnTarget' => false,
            'modifierRange' => 'daedalus',
            'type' => 'variable_event_modifier',
            'triggeredEvent' => null,
            'visibility' => null,
            'delta' => -1.0,
            'targetVariable' => 'actionPoint',
            'mode' => 'additive',
            'modifierActivationRequirements' => [],
            'tagConstraints' => [
                ActionEnum::ANALYZE_PLANET => ModifierRequirementEnum::ANY_TAGS,
            ],
        ],
        [
            'name' => 'modifier_for_daedalus_+1sector_revealed_on_action_analyze_planet',
            'modifierName' => null,
            'targetEvent' => ActionVariableEvent::GET_OUTPUT_QUANTITY,
            'strategy' => ModifierStrategyEnum::VARIABLE_MODIFIER,
            'priority' => ModifierPriorityEnum::ADDITIVE_MODIFIER_VALUE,
            'applyOnTarget' => false,
            'modifierRange' => 'daedalus',
            'type' => 'variable_event_modifier',
            'triggeredEvent' => null,
            'visibility' => null,
            'delta' => 1.0,
            'targetVariable' => 'outputQuantity',
            'mode' => 'additive',
            'modifierActivationRequirements' => [],
            'tagConstraints' => [
                ActionEnum::ANALYZE_PLANET => ModifierRequirementEnum::ANY_TAGS,
            ],
        ],
        [
            'name' => 'modifier_for_place_+1sector_revealed_on_action_scan_planet',
            'modifierName' => ModifierNameEnum::LIQUID_MAP_MODIFIER,
            'targetEvent' => ActionVariableEvent::GET_OUTPUT_QUANTITY,
            'strategy' => ModifierStrategyEnum::VARIABLE_MODIFIER,
            'priority' => ModifierPriorityEnum::ADDITIVE_MODIFIER_VALUE,
            'applyOnTarget' => false,
            'modifierRange' => 'place',
            'type' => 'variable_event_modifier',
            'triggeredEvent' => null,
            'visibility' => null,
            'delta' => 1.0,
            'targetVariable' => 'outputQuantity',
            'mode' => 'additive',
            'modifierActivationRequirements' => [],
            'tagConstraints' => [
                ActionEnum::SCAN => ModifierRequirementEnum::ANY_TAGS,
                ActionOutputEnum::FAIL => ModifierRequirementEnum::NONE_TAGS,
            ],
        ],
        [
            'name' => 'modifier_for_place_+1sector_revealed_on_action_scan_planet_random_50',
            'modifierName' => null,
            'targetEvent' => ActionVariableEvent::GET_OUTPUT_QUANTITY,
            'strategy' => ModifierStrategyEnum::VARIABLE_MODIFIER,
            'priority' => ModifierPriorityEnum::ADDITIVE_MODIFIER_VALUE,
            'applyOnTarget' => false,
            'modifierRange' => 'place',
            'type' => 'variable_event_modifier',
            'triggeredEvent' => null,
            'visibility' => null,
            'delta' => 1.0,
            'targetVariable' => 'outputQuantity',
            'mode' => 'additive',
            'modifierActivationRequirements' => ['random_50'],
            'tagConstraints' => [
                ActionEnum::SCAN => ModifierRequirementEnum::ANY_TAGS,
                ActionOutputEnum::FAIL => ModifierRequirementEnum::NONE_TAGS,
            ],
        ],
        [
            'name' => 'modifier_pilot_always_critical_success_piloting',
            'modifierName' => null,
            'targetEvent' => ActionVariableEvent::ROLL_ACTION_PERCENTAGE,
            'strategy' => ModifierStrategyEnum::VARIABLE_MODIFIER,
            'priority' => ModifierPriorityEnum::OVERRIDE_VALUE_PRIORITY,
            'applyOnTarget' => false,
            'modifierRange' => 'player',
            'type' => 'variable_event_modifier',
            'visibility' => null,
            'delta' => 100,
            'targetVariable' => ActionVariableEnum::PERCENTAGE_CRITICAL,
            'mode' => VariableModifierModeEnum::SET_VALUE,
            'modifierActivationRequirements' => [],
            'tagConstraints' => [
                ActionTypeEnum::ACTION_PILOT => ModifierRequirementEnum::ANY_TAGS,
            ],
        ],
        [
            'name' => 'modifier_pilot_increased_shoot_hunter_chances',
            'modifierName' => null,
            'targetEvent' => ActionVariableEvent::ROLL_ACTION_PERCENTAGE,
            'strategy' => ModifierStrategyEnum::VARIABLE_MODIFIER,
            'priority' => ModifierPriorityEnum::MULTIPLICATIVE_MODIFIER_VALUE,
            'applyOnTarget' => false,
            'modifierRange' => 'player',
            'type' => 'variable_event_modifier',
            'visibility' => null,
            'delta' => 2,
            'targetVariable' => ActionVariableEnum::PERCENTAGE_SUCCESS,
            'mode' => VariableModifierModeEnum::MULTIPLICATIVE,
            'modifierActivationRequirements' => [],
            'tagConstraints' => [
                ActionEnum::SHOOT_HUNTER_PATROL_SHIP => ModifierRequirementEnum::ANY_TAGS,
                ActionEnum::SHOOT_RANDOM_HUNTER_PATROL_SHIP => ModifierRequirementEnum::ANY_TAGS,
            ],
        ],
        [
            'name' => 'modifier_shooter_specialist_point',
            'modifierName' => ModifierNameEnum::SHOOTER_SPECIALIST_POINT,
            'targetEvent' => ActionVariableEvent::APPLY_COST,
            'strategy' => ModifierStrategyEnum::VARIABLE_MODIFIER,
            'priority' => ModifierPriorityEnum::OVERRIDE_VALUE_PRIORITY,
            'applyOnTarget' => false,
            'modifierRange' => 'player',
            'type' => 'variable_event_modifier',
            'visibility' => null,
            'delta' => 0,
            'targetVariable' => PlayerVariableEnum::ACTION_POINT,
            'mode' => VariableModifierModeEnum::SET_VALUE,
            'modifierActivationRequirements' => [],
            'tagConstraints' => [
                ActionTypeEnum::ACTION_SHOOT_HUNTER => ModifierRequirementEnum::ANY_TAGS,
                ActionTypeEnum::ACTION_SHOOT => ModifierRequirementEnum::ANY_TAGS,
            ],
        ],
    ];
}
