<?php

namespace Mush\Modifier\ConfigData;

/** @codeCoverageIgnore */
class ModifierConfigData
{
    public static array $dataArray = [
        [
            'name' => 'modifier_for_player_+1movementPoint_on_move',
            'modifierName' => null,
            'targetEvent' => 'move',
            'applyOnActionParameter' => false,
            'modifierRange' => 'player',
            'type' => 'variable_event_modifier',
            'triggeredEvent' => null,
            'visibility' => null,
            'delta' => 1.0,
            'targetVariable' => 'movementPoint',
            'mode' => 'additive',
            'modifierActivationRequirements' => [],
        ],
        [
            'name' => 'direct_modifier_player_-1_max_healthPoint',
            'modifierName' => null,
            'revertOnRemove' => true,
            'modifierRange' => 'player',
            'type' => 'direct_modifier',
            'triggeredEvent' => 'change.value.max_player_-1_healthPoint',
            'modifierActivationRequirements' => [],
        ],
        [
            'name' => 'direct_modifier_player_-2_max_healthPoint',
            'modifierName' => null,
            'revertOnRemove' => true,
            'modifierRange' => 'player',
            'type' => 'direct_modifier',
            'triggeredEvent' => 'change.value.max_player_-2_healthPoint',
            'modifierActivationRequirements' => [],
        ],
        [
            'name' => 'direct_modifier_player_-4_max_healthPoint',
            'modifierName' => null,
            'revertOnRemove' => true,
            'modifierRange' => 'player',
            'type' => 'direct_modifier',
            'triggeredEvent' => 'change.value.max_player_-4_healthPoint',
            'modifierActivationRequirements' => [],
        ],
        [
            'name' => 'direct_modifier_player_-1_max_moralPoint',
            'modifierName' => null,
            'revertOnRemove' => true,
            'modifierRange' => 'player',
            'type' => 'direct_modifier',
            'triggeredEvent' => 'change.value.max_player_-1_moralPoint',
            'modifierActivationRequirements' => [],
        ],
        [
            'name' => 'direct_modifier_player_-2_max_moralPoint',
            'modifierName' => null,
            'revertOnRemove' => true,
            'modifierRange' => 'player',
            'type' => 'direct_modifier',
            'triggeredEvent' => 'change.value.max_player_-2_moralPoint',
            'modifierActivationRequirements' => [],
        ],
        [
            'name' => 'modifier_for_player_set_-1healthPoint_on_new_cycle',
            'modifierName' => null,
            'targetEvent' => 'new_cycle',
            'applyOnActionParameter' => false,
            'modifierRange' => 'player',
            'type' => 'variable_event_modifier',
            'triggeredEvent' => null,
            'visibility' => null,
            'delta' => -1.0,
            'targetVariable' => 'healthPoint',
            'mode' => 'set_value',
            'modifierActivationRequirements' => [],
        ],
        [
            'name' => 'modifier_for_player_set_-2healthPoint_on_new_cycle',
            'modifierName' => null,
            'targetEvent' => 'new_cycle',
            'applyOnActionParameter' => false,
            'modifierRange' => 'player',
            'type' => 'variable_event_modifier',
            'triggeredEvent' => null,
            'visibility' => null,
            'delta' => -2.0,
            'targetVariable' => 'healthPoint',
            'mode' => 'set_value',
            'modifierActivationRequirements' => [],
        ],
        [
            'name' => 'modifier_for_player_set_-4healthPoint_on_new_cycle',
            'modifierName' => null,
            'targetEvent' => 'new_cycle',
            'applyOnActionParameter' => false,
            'modifierRange' => 'player',
            'type' => 'variable_event_modifier',
            'triggeredEvent' => null,
            'visibility' => null,
            'delta' => -4.0,
            'targetVariable' => 'healthPoint',
            'mode' => 'set_value',
            'modifierActivationRequirements' => [],
        ],
        [
            'name' => 'modifier_for_player_set_-1movementPoint_on_new_cycle',
            'modifierName' => null,
            'targetEvent' => 'new_cycle',
            'applyOnActionParameter' => false,
            'modifierRange' => 'player',
            'type' => 'variable_event_modifier',
            'triggeredEvent' => null,
            'visibility' => null,
            'delta' => -1.0,
            'targetVariable' => 'movementPoint',
            'mode' => 'set_value',
            'modifierActivationRequirements' => [],
        ],
        [
            'name' => 'modifier_for_player_set_-1satiety_on_new_cycle',
            'modifierName' => null,
            'targetEvent' => 'new_cycle',
            'applyOnActionParameter' => false,
            'modifierRange' => 'player',
            'type' => 'variable_event_modifier',
            'triggeredEvent' => null,
            'visibility' => null,
            'delta' => -1.0,
            'targetVariable' => 'satiety',
            'mode' => 'set_value',
            'modifierActivationRequirements' => [],
        ],
        [
            'name' => 'modifier_for_player_set_-1actionPoint_on_new_cycle_if_random_10',
            'modifierName' => null,
            'targetEvent' => 'new_cycle',
            'applyOnActionParameter' => false,
            'modifierRange' => 'player',
            'type' => 'variable_event_modifier',
            'triggeredEvent' => null,
            'visibility' => null,
            'delta' => -1.0,
            'targetVariable' => 'actionPoint',
            'mode' => 'set_value',
            'modifierActivationRequirements' => [
                'random_10',
            ],
        ],
        [
            'name' => 'modifier_for_player_set_-1healthPoint_on_new_cycle_if_random_10',
            'modifierName' => null,
            'targetEvent' => 'new_cycle',
            'applyOnActionParameter' => false,
            'modifierRange' => 'player',
            'type' => 'variable_event_modifier',
            'triggeredEvent' => null,
            'visibility' => null,
            'delta' => -1.0,
            'targetVariable' => 'healthPoint',
            'mode' => 'set_value',
            'modifierActivationRequirements' => [
                'random_10',
            ],
        ],
        [
            'name' => 'modifier_for_player_set_-1actionPoint_on_new_cycle_if_random_16',
            'modifierName' => null,
            'targetEvent' => 'new_cycle',
            'applyOnActionParameter' => false,
            'modifierRange' => 'player',
            'type' => 'variable_event_modifier',
            'triggeredEvent' => null,
            'visibility' => null,
            'delta' => -1.0,
            'targetVariable' => 'actionPoint',
            'mode' => 'set_value',
            'modifierActivationRequirements' => [
                'random_16',
            ],
        ],
        [
            'name' => 'modifier_for_player_set_-1healthPoint_on_new_cycle_if_random_16',
            'modifierName' => null,
            'targetEvent' => 'new_cycle',
            'applyOnActionParameter' => false,
            'modifierRange' => 'player',
            'type' => 'variable_event_modifier',
            'triggeredEvent' => null,
            'visibility' => null,
            'delta' => -1.0,
            'targetVariable' => 'healthPoint',
            'mode' => 'set_value',
            'modifierActivationRequirements' => [
                'random_16',
            ],
        ],
        [
            'name' => 'modifier_for_player_set_-1actionPoint_on_new_cycle_if_random_20',
            'modifierName' => null,
            'targetEvent' => 'new_cycle',
            'applyOnActionParameter' => false,
            'modifierRange' => 'player',
            'type' => 'variable_event_modifier',
            'triggeredEvent' => null,
            'visibility' => null,
            'delta' => -1.0,
            'targetVariable' => 'actionPoint',
            'mode' => 'set_value',
            'modifierActivationRequirements' => [
                'random_20',
            ],
        ],
        [
            'name' => 'modifier_for_player_set_-1actionPoint_on_new_cycle_if_random_30',
            'modifierName' => null,
            'targetEvent' => 'new_cycle',
            'applyOnActionParameter' => false,
            'modifierRange' => 'player',
            'type' => 'variable_event_modifier',
            'triggeredEvent' => null,
            'visibility' => null,
            'delta' => -1.0,
            'targetVariable' => 'actionPoint',
            'mode' => 'set_value',
            'modifierActivationRequirements' => [
                'random_30',
            ],
        ],
        [
            'name' => 'modifier_for_player_set_-2actionPoint_on_new_cycle_if_random_40',
            'modifierName' => null,
            'targetEvent' => 'new_cycle',
            'applyOnActionParameter' => false,
            'modifierRange' => 'player',
            'type' => 'variable_event_modifier',
            'triggeredEvent' => null,
            'visibility' => null,
            'delta' => -2.0,
            'targetVariable' => 'actionPoint',
            'mode' => 'set_value',
            'modifierActivationRequirements' => [
                'random_40',
            ],
        ],
        [
            'name' => 'modifier_for_player_set_-1movementPoint_on_new_cycle_if_random_50',
            'modifierName' => null,
            'targetEvent' => 'new_cycle',
            'applyOnActionParameter' => false,
            'modifierRange' => 'player',
            'type' => 'variable_event_modifier',
            'triggeredEvent' => null,
            'visibility' => null,
            'delta' => -1.0,
            'targetVariable' => 'movementPoint',
            'mode' => 'set_value',
            'modifierActivationRequirements' => [
                'random_50',
            ],
        ],
        [
            'name' => 'modifier_for_player_set_-1healthPoint_on_new_cycle_if_random_50',
            'modifierName' => null,
            'targetEvent' => 'new_cycle',
            'applyOnActionParameter' => false,
            'modifierRange' => 'player',
            'type' => 'variable_event_modifier',
            'triggeredEvent' => null,
            'visibility' => null,
            'delta' => -1.0,
            'targetVariable' => 'healthPoint',
            'mode' => 'set_value',
            'modifierActivationRequirements' => [
                'random_50',
            ],
        ],
        [
            'name' => 'modifier_for_player_set_-1actionPoint_on_post.action_if_reason_consume',
            'modifierName' => null,
            'targetEvent' => 'post.action',
            'applyOnActionParameter' => false,
            'modifierRange' => 'player',
            'type' => 'variable_event_modifier',
            'triggeredEvent' => null,
            'visibility' => null,
            'delta' => -1.0,
            'targetVariable' => 'actionPoint',
            'mode' => 'set_value',
            'modifierActivationRequirements' => [
                'reason_consume',
            ],
        ],
        [
            'name' => 'modifier_for_player_set_-2actionPoint_on_post.action_if_reason_consume',
            'modifierName' => null,
            'targetEvent' => 'post.action',
            'applyOnActionParameter' => false,
            'modifierRange' => 'player',
            'type' => 'variable_event_modifier',
            'triggeredEvent' => null,
            'visibility' => null,
            'delta' => -2.0,
            'targetVariable' => 'actionPoint',
            'mode' => 'set_value',
            'modifierActivationRequirements' => [
                'reason_consume',
            ],
        ],
        [
            'name' => 'modifier_for_player_set_-4healthPoint_on_infection.player',
            'modifierName' => null,
            'targetEvent' => 'infection.player',
            'applyOnActionParameter' => false,
            'modifierRange' => 'player',
            'type' => 'variable_event_modifier',
            'triggeredEvent' => null,
            'visibility' => null,
            'delta' => -4.0,
            'targetVariable' => 'healthPoint',
            'mode' => 'set_value',
            'modifierActivationRequirements' => [],
        ],
        [
            'name' => 'modifier_for_player_set_-6healthPoint_on_post.action_if_player_equipment_schrodinger',
            'modifierName' => null,
            'targetEvent' => 'post.action',
            'applyOnActionParameter' => false,
            'modifierRange' => 'player',
            'type' => 'variable_event_modifier',
            'triggeredEvent' => null,
            'visibility' => null,
            'delta' => -6.0,
            'targetVariable' => 'healthPoint',
            'mode' => 'set_value',
            'modifierActivationRequirements' => [
                'player_equipment_schrodinger',
            ],
        ],
        [
            'name' => 'modifier_for_player_+1satiety_on_new_cycle',
            'modifierName' => null,
            'targetEvent' => 'new_cycle',
            'applyOnActionParameter' => false,
            'modifierRange' => 'player',
            'type' => 'variable_event_modifier',
            'triggeredEvent' => null,
            'visibility' => null,
            'delta' => 1.0,
            'targetVariable' => 'satiety',
            'mode' => 'additive',
            'modifierActivationRequirements' => [],
        ],
        [
            'name' => 'modifier_for_player_x0.9percentage_on_action_shoot',
            'modifierName' => null,
            'targetEvent' => 'action_shoot',
            'applyOnActionParameter' => false,
            'modifierRange' => 'player',
            'type' => 'variable_event_modifier',
            'triggeredEvent' => null,
            'visibility' => null,
            'delta' => 0.9,
            'targetVariable' => 'percentage',
            'mode' => 'multiplicative',
            'modifierActivationRequirements' => [],
        ],
        [
            'name' => 'modifier_for_player_+10percentage_on_cycle_disease',
            'modifierName' => null,
            'targetEvent' => 'cycle_disease',
            'applyOnActionParameter' => false,
            'modifierRange' => 'player',
            'type' => 'variable_event_modifier',
            'triggeredEvent' => null,
            'visibility' => null,
            'delta' => 10.0,
            'targetVariable' => 'percentage',
            'mode' => 'additive',
            'modifierActivationRequirements' => [],
        ],
        [
            'name' => 'fitfull_sleep_for_player_-1actionPoint_on_new_cycle_if_random_16_if_player_status_lying_down',
            'modifierName' => 'fitfull_sleep',
            'targetEvent' => 'new_cycle',
            'applyOnActionParameter' => false,
            'modifierRange' => 'player',
            'type' => 'variable_event_modifier',
            'triggeredEvent' => null,
            'visibility' => null,
            'delta' => -1.0,
            'targetVariable' => 'actionPoint',
            'mode' => 'additive',
            'modifierActivationRequirements' => [
                'random_16',
                'player_status_lying_down',
            ],
        ],
        [
            'name' => 'apron_modifier_for_player_-100percentage_on_event_dirty',
            'modifierName' => 'apron_modifier',
            'targetEvent' => 'event_dirty',
            'applyOnActionParameter' => false,
            'modifierRange' => 'player',
            'type' => 'variable_event_modifier',
            'triggeredEvent' => null,
            'visibility' => null,
            'delta' => -100.0,
            'targetVariable' => 'percentage',
            'mode' => 'additive',
            'modifierActivationRequirements' => [],
        ],
        [
            'name' => 'modifier_for_target_player_-1healthPoint_on_injury',
            'modifierName' => null,
            'targetEvent' => 'injury',
            'applyOnActionParameter' => true,
            'modifierRange' => 'target_player',
            'type' => 'variable_event_modifier',
            'triggeredEvent' => null,
            'visibility' => null,
            'delta' => -1.0,
            'targetVariable' => 'healthPoint',
            'mode' => 'additive',
            'modifierActivationRequirements' => [],
        ],
        [
            'name' => 'modifier_for_player_x1.5percentage_on_action_technician',
            'modifierName' => null,
            'targetEvent' => 'action_technician',
            'applyOnActionParameter' => false,
            'modifierRange' => 'player',
            'type' => 'variable_event_modifier',
            'triggeredEvent' => null,
            'visibility' => null,
            'delta' => 1.5,
            'targetVariable' => 'percentage',
            'mode' => 'multiplicative',
            'modifierActivationRequirements' => [],
        ],
        [
            'name' => 'gloves_modifier_for_player_set_0percentage_on_event_clumsiness',
            'modifierName' => 'gloves_modifier',
            'targetEvent' => 'event_clumsiness',
            'applyOnActionParameter' => false,
            'modifierRange' => 'player',
            'type' => 'variable_event_modifier',
            'triggeredEvent' => null,
            'visibility' => null,
            'delta' => 0.0,
            'targetVariable' => 'percentage',
            'mode' => 'set_value',
            'modifierActivationRequirements' => [],
        ],
        [
            'name' => 'modifier_for_player_-1actionPoint_on_shower',
            'modifierName' => null,
            'targetEvent' => 'shower',
            'applyOnActionParameter' => false,
            'modifierRange' => 'player',
            'type' => 'variable_event_modifier',
            'triggeredEvent' => null,
            'visibility' => null,
            'delta' => -1.0,
            'targetVariable' => 'actionPoint',
            'mode' => 'additive',
            'modifierActivationRequirements' => [],
        ],
        [
            'name' => 'modifier_for_player_-1actionPoint_on_wash_in_sink',
            'modifierName' => null,
            'targetEvent' => 'wash_in_sink',
            'applyOnActionParameter' => false,
            'modifierRange' => 'player',
            'type' => 'variable_event_modifier',
            'triggeredEvent' => null,
            'visibility' => null,
            'delta' => -1.0,
            'targetVariable' => 'actionPoint',
            'mode' => 'additive',
            'modifierActivationRequirements' => [],
        ],
        [
            'name' => 'modifier_for_player_x1.1percentage_on_action_shoot',
            'modifierName' => null,
            'targetEvent' => 'action_shoot',
            'applyOnActionParameter' => false,
            'modifierRange' => 'player',
            'type' => 'variable_event_modifier',
            'triggeredEvent' => null,
            'visibility' => null,
            'delta' => 1.1,
            'targetVariable' => 'percentage',
            'mode' => 'multiplicative',
            'modifierActivationRequirements' => [],
        ],
        [
            'name' => 'modifier_for_player_+2movementPoint_on_event_action_movement_conversion',
            'modifierName' => null,
            'targetEvent' => 'event_action_movement_conversion',
            'applyOnActionParameter' => false,
            'modifierRange' => 'player',
            'type' => 'variable_event_modifier',
            'triggeredEvent' => null,
            'visibility' => null,
            'delta' => 2.0,
            'targetVariable' => 'movementPoint',
            'mode' => 'additive',
            'modifierActivationRequirements' => [],
        ],
        [
            'name' => 'modifier_for_player_+1movementPoint_on_event_action_movement_conversion_if_cycle_even',
            'modifierName' => null,
            'targetEvent' => 'event_action_movement_conversion',
            'applyOnActionParameter' => false,
            'modifierRange' => 'player',
            'type' => 'variable_event_modifier',
            'triggeredEvent' => null,
            'visibility' => null,
            'delta' => 1.0,
            'targetVariable' => 'movementPoint',
            'mode' => 'additive',
            'modifierActivationRequirements' => [
                'cycle_even',
            ],
        ],
        [
            'name' => 'modifier_for_player_x1.5percentage_on_strengthen_hull',
            'modifierName' => null,
            'targetEvent' => 'strengthen_hull',
            'applyOnActionParameter' => false,
            'modifierRange' => 'player',
            'type' => 'variable_event_modifier',
            'triggeredEvent' => null,
            'visibility' => null,
            'delta' => 1.5,
            'targetVariable' => 'percentage',
            'mode' => 'multiplicative',
            'modifierActivationRequirements' => [],
        ],
        [
            'name' => 'modifier_for_player_x2hull_on_change.variable_if_reason_strengthen_hull',
            'modifierName' => null,
            'targetEvent' => 'change.variable',
            'applyOnActionParameter' => false,
            'modifierRange' => 'player',
            'type' => 'variable_event_modifier',
            'triggeredEvent' => null,
            'visibility' => null,
            'delta' => 2.0,
            'targetVariable' => 'hull',
            'mode' => 'multiplicative',
            'modifierActivationRequirements' => [
                'reason_strengthen_hull',
            ],
        ],
        [
            'name' => 'modifier_for_daedalus_-1actionPoint_on_TODO comms. action',
            'modifierName' => null,
            'targetEvent' => 'TODO comms. action',
            'applyOnActionParameter' => false,
            'modifierRange' => 'daedalus',
            'type' => 'variable_event_modifier',
            'triggeredEvent' => null,
            'visibility' => null,
            'delta' => -1.0,
            'targetVariable' => 'actionPoint',
            'mode' => 'additive',
            'modifierActivationRequirements' => [],
        ],
        [
            'name' => 'modifier_for_daedalus_+1movementPoint_on_event_action_movement_conversion',
            'modifierName' => null,
            'targetEvent' => 'event_action_movement_conversion',
            'applyOnActionParameter' => false,
            'modifierRange' => 'daedalus',
            'type' => 'variable_event_modifier',
            'triggeredEvent' => null,
            'visibility' => null,
            'delta' => 1.0,
            'targetVariable' => 'movementPoint',
            'mode' => 'additive',
            'modifierActivationRequirements' => [],
        ],
        [
            'name' => 'modifier_for_daedalus_+1movementPoint_on_change.variable_if_reason_new_cycle',
            'modifierName' => null,
            'targetEvent' => 'change.variable',
            'applyOnActionParameter' => false,
            'modifierRange' => 'daedalus',
            'type' => 'variable_event_modifier',
            'triggeredEvent' => null,
            'visibility' => null,
            'delta' => 1.0,
            'targetVariable' => 'movementPoint',
            'mode' => 'additive',
            'modifierActivationRequirements' => [
                'reason_new_cycle',
            ],
        ],
        [
            'name' => 'modifier_for_daedalus_+1oxygen_on_change.variable_if_reason_new_cycle',
            'modifierName' => null,
            'targetEvent' => 'change.variable',
            'applyOnActionParameter' => false,
            'modifierRange' => 'daedalus',
            'type' => 'variable_event_modifier',
            'triggeredEvent' => null,
            'visibility' => null,
            'delta' => 1.0,
            'targetVariable' => 'oxygen',
            'mode' => 'additive',
            'modifierActivationRequirements' => [
                'reason_new_cycle',
            ],
        ],
        [
            'name' => 'modifier_for_player_+2movementPoint_on_move_if_item_in_room_schrodinger',
            'modifierName' => null,
            'targetEvent' => 'move',
            'applyOnActionParameter' => false,
            'modifierRange' => 'player',
            'type' => 'variable_event_modifier',
            'triggeredEvent' => null,
            'visibility' => null,
            'delta' => 2.0,
            'targetVariable' => 'movementPoint',
            'mode' => 'additive',
            'modifierActivationRequirements' => [
                'item_in_room_schrodinger',
            ],
        ],
        [
            'name' => 'modifier_for_player_+2actionPoint_on_actions_if_item_in_room_schrodinger_if_not_reason_move',
            'modifierName' => null,
            'targetEvent' => 'actions',
            'applyOnActionParameter' => false,
            'modifierRange' => 'player',
            'type' => 'variable_event_modifier',
            'triggeredEvent' => null,
            'visibility' => null,
            'delta' => 2.0,
            'targetVariable' => 'actionPoint',
            'mode' => 'additive',
            'modifierActivationRequirements' => [
                'item_in_room_schrodinger',
                'not_reason_move',
            ],
        ],
        [
            'name' => 'screaming_for_player_set_-1actionPoint_on_new_cycle_if_random_16',
            'modifierName' => 'screaming',
            'targetEvent' => 'new_cycle',
            'applyOnActionParameter' => false,
            'modifierRange' => 'player',
            'type' => 'variable_event_modifier',
            'triggeredEvent' => null,
            'visibility' => null,
            'delta' => -1.0,
            'targetVariable' => 'actionPoint',
            'mode' => 'set_value',
            'modifierActivationRequirements' => [
                'random_16',
            ],
        ],
        [
            'name' => 'wall_head_bang_for_player_set_-1healthPoint_on_new_cycle_if_random_16',
            'modifierName' => 'wall_head_bang',
            'targetEvent' => 'new_cycle',
            'applyOnActionParameter' => false,
            'modifierRange' => 'player',
            'type' => 'variable_event_modifier',
            'triggeredEvent' => null,
            'visibility' => null,
            'delta' => -1.0,
            'targetVariable' => 'healthPoint',
            'mode' => 'set_value',
            'modifierActivationRequirements' => [
                'random_16',
            ],
        ],
        [
            'name' => 'modifier_for_player_set_-1moralPoint_on_new_cycle_if_random_70',
            'modifierName' => null,
            'targetEvent' => 'new_cycle',
            'applyOnActionParameter' => false,
            'modifierRange' => 'player',
            'type' => 'variable_event_modifier',
            'triggeredEvent' => null,
            'visibility' => null,
            'delta' => -1.0,
            'targetVariable' => 'moralPoint',
            'mode' => 'set_value',
            'modifierActivationRequirements' => [
                'random_70',
            ],
        ],
        [
            'name' => 'run_in_circles_for_player_set_-2movementPoint_on_new_cycle_if_random_16',
            'modifierName' => 'run_in_circles',
            'targetEvent' => 'new_cycle',
            'applyOnActionParameter' => false,
            'modifierRange' => 'player',
            'type' => 'variable_event_modifier',
            'triggeredEvent' => null,
            'visibility' => null,
            'delta' => -2.0,
            'targetVariable' => 'movementPoint',
            'mode' => 'set_value',
            'modifierActivationRequirements' => [
                'random_16',
            ],
        ],
        [
            'name' => 'modifier_for_player_+1actionPoint_on_actions_if_player_in_room_four_people',
            'modifierName' => null,
            'targetEvent' => 'actions',
            'applyOnActionParameter' => false,
            'modifierRange' => 'player',
            'type' => 'variable_event_modifier',
            'triggeredEvent' => null,
            'visibility' => null,
            'delta' => 1.0,
            'targetVariable' => 'actionPoint',
            'mode' => 'additive',
            'modifierActivationRequirements' => [
                'player_in_room_four_people',
            ],
        ],
        [
            'name' => 'modifier_for_player_+1movementPoint_on_actions_if_player_in_room_four_people',
            'modifierName' => null,
            'targetEvent' => 'actions',
            'applyOnActionParameter' => false,
            'modifierRange' => 'player',
            'type' => 'variable_event_modifier',
            'triggeredEvent' => null,
            'visibility' => null,
            'delta' => 1.0,
            'targetVariable' => 'movementPoint',
            'mode' => 'additive',
            'modifierActivationRequirements' => [
                'player_in_room_four_people',
            ],
        ],
        [
            'name' => 'direct_modifier_player_-2_max_actionPoint',
            'modifierName' => null,
            'revertOnRemove' => true,
            'modifierRange' => 'player',
            'type' => 'direct_modifier',
            'triggeredEvent' => 'change.value.max_player_-2_actionPoint',
            'modifierActivationRequirements' => [],
        ],
        [
            'name' => 'direct_modifier_player_-3_max_moralPoint',
            'modifierName' => null,
            'revertOnRemove' => true,
            'modifierRange' => 'player',
            'type' => 'direct_modifier',
            'triggeredEvent' => 'change.value.max_player_-3_moralPoint',
            'modifierActivationRequirements' => [],
        ],
        [
            'name' => 'direct_modifier_player_-4_max_moralPoint',
            'modifierName' => null,
            'revertOnRemove' => true,
            'modifierRange' => 'player',
            'type' => 'direct_modifier',
            'triggeredEvent' => 'change.value.max_player_-4_moralPoint',
            'modifierActivationRequirements' => [],
        ],
        [
            'name' => 'modifier_for_player_+1actionPoint_on_actions_if_not_reason_move_if_not_reason_consume_if_not_reason_consume_drug_if_not_reason_surgery_if_not_reason_self_surgery',
            'modifierName' => null,
            'targetEvent' => 'actions',
            'applyOnActionParameter' => false,
            'modifierRange' => 'player',
            'type' => 'variable_event_modifier',
            'triggeredEvent' => null,
            'visibility' => null,
            'delta' => 1.0,
            'targetVariable' => 'actionPoint',
            'mode' => 'additive',
            'modifierActivationRequirements' => [
                'not_reason_move',
                'not_reason_consume',
                'not_reason_consume_drug',
                'not_reason_surgery',
                'not_reason_self_surgery',
            ],
        ],
        [
            'name' => 'modifier_for_player_+2actionPoint_on_actions_if_not_reason_move_if_not_reason_consume_if_not_reason_consume_drug_if_not_reason_surgery_if_not_reason_self_surgery',
            'modifierName' => null,
            'targetEvent' => 'actions',
            'applyOnActionParameter' => false,
            'modifierRange' => 'player',
            'type' => 'variable_event_modifier',
            'triggeredEvent' => null,
            'visibility' => null,
            'delta' => 2.0,
            'targetVariable' => 'actionPoint',
            'mode' => 'additive',
            'modifierActivationRequirements' => [
                'not_reason_move',
                'not_reason_consume',
                'not_reason_consume_drug',
                'not_reason_surgery',
                'not_reason_self_surgery',
            ],
        ],
        [
            'name' => 'modifier_for_player_+3actionPoint_on_actions_if_not_reason_move_if_not_reason_consume_if_not_reason_consume_drug_if_not_reason_surgery_if_not_reason_self_surgery',
            'modifierName' => null,
            'targetEvent' => 'actions',
            'applyOnActionParameter' => false,
            'modifierRange' => 'player',
            'type' => 'variable_event_modifier',
            'triggeredEvent' => null,
            'visibility' => null,
            'delta' => 3.0,
            'targetVariable' => 'actionPoint',
            'mode' => 'additive',
            'modifierActivationRequirements' => [
                'not_reason_move',
                'not_reason_consume',
                'not_reason_consume_drug',
                'not_reason_surgery',
                'not_reason_self_surgery',
            ],
        ],
        [
            'name' => 'direct_modifier_player_-3_max_movementPoint',
            'modifierName' => null,
            'revertOnRemove' => true,
            'modifierRange' => 'player',
            'type' => 'direct_modifier',
            'triggeredEvent' => 'change.value.max_player_-3_movementPoint',
            'modifierActivationRequirements' => [],
        ],
        [
            'name' => 'direct_modifier_player_-5_max_movementPoint',
            'modifierName' => null,
            'revertOnRemove' => true,
            'modifierRange' => 'player',
            'type' => 'direct_modifier',
            'triggeredEvent' => 'change.value.max_player_-5_movementPoint',
            'modifierActivationRequirements' => [],
        ],
        [
            'name' => 'direct_modifier_player_-12_max_movementPoint',
            'modifierName' => null,
            'revertOnRemove' => true,
            'modifierRange' => 'player',
            'type' => 'direct_modifier',
            'triggeredEvent' => 'change.value.max_player_-12_movementPoint',
            'modifierActivationRequirements' => [],
        ],
        [
            'name' => 'modifier_for_player_x0.85percentage_on_action_shoot',
            'modifierName' => null,
            'targetEvent' => 'action_shoot',
            'applyOnActionParameter' => false,
            'modifierRange' => 'player',
            'type' => 'variable_event_modifier',
            'triggeredEvent' => null,
            'visibility' => null,
            'delta' => 0.85,
            'targetVariable' => 'percentage',
            'mode' => 'multiplicative',
            'modifierActivationRequirements' => [],
        ],
        [
            'name' => 'modifier_for_player_x0.8percentage_on_action_shoot',
            'modifierName' => null,
            'targetEvent' => 'action_shoot',
            'applyOnActionParameter' => false,
            'modifierRange' => 'player',
            'type' => 'variable_event_modifier',
            'triggeredEvent' => null,
            'visibility' => null,
            'delta' => 0.8,
            'targetVariable' => 'percentage',
            'mode' => 'multiplicative',
            'modifierActivationRequirements' => [],
        ],
        [
            'name' => 'modifier_for_player_x0.6percentage_on_action_shoot',
            'modifierName' => null,
            'targetEvent' => 'action_shoot',
            'applyOnActionParameter' => false,
            'modifierRange' => 'player',
            'type' => 'variable_event_modifier',
            'triggeredEvent' => null,
            'visibility' => null,
            'delta' => 0.6,
            'targetVariable' => 'percentage',
            'mode' => 'multiplicative',
            'modifierActivationRequirements' => [],
        ],
        [
            'name' => 'modifier_for_equipment_+1actionPoint_on_consume',
            'modifierName' => null,
            'targetEvent' => 'consume',
            'applyOnActionParameter' => true,
            'modifierRange' => 'equipment',
            'type' => 'variable_event_modifier',
            'triggeredEvent' => null,
            'visibility' => null,
            'delta' => 1.0,
            'targetVariable' => 'actionPoint',
            'mode' => 'additive',
            'modifierActivationRequirements' => [],
        ],
        [
            'name' => 'modifier_for_player_-2movementPoint_on_event_action_movement_conversion',
            'modifierName' => null,
            'targetEvent' => 'event_action_movement_conversion',
            'applyOnActionParameter' => false,
            'modifierRange' => 'player',
            'type' => 'variable_event_modifier',
            'triggeredEvent' => null,
            'visibility' => null,
            'delta' => -2.0,
            'targetVariable' => 'movementPoint',
            'mode' => 'additive',
            'modifierActivationRequirements' => [],
        ],
        [
            'name' => 'modifier_for_player_-1movementPoint_on_move_if_player_in_room_not_alone',
            'modifierName' => null,
            'targetEvent' => 'move',
            'applyOnActionParameter' => false,
            'modifierRange' => 'player',
            'type' => 'variable_event_modifier',
            'triggeredEvent' => null,
            'visibility' => null,
            'delta' => -1.0,
            'targetVariable' => 'movementPoint',
            'mode' => 'additive',
            'modifierActivationRequirements' => [
                'player_in_room_not_alone',
            ],
        ],
        [
            'name' => 'modifier_for_place_+2actionPoint_on_action_aggressive',
            'modifierName' => null,
            'targetEvent' => 'action_aggressive',
            'applyOnActionParameter' => false,
            'modifierRange' => 'place',
            'type' => 'variable_event_modifier',
            'triggeredEvent' => null,
            'visibility' => null,
            'delta' => 2.0,
            'targetVariable' => 'actionPoint',
            'mode' => 'additive',
            'modifierActivationRequirements' => [],
        ],
        [
            'name' => 'modifier_for_player_+2movementPoint_on_move',
            'modifierName' => null,
            'targetEvent' => 'move',
            'applyOnActionParameter' => false,
            'modifierRange' => 'player',
            'type' => 'variable_event_modifier',
            'triggeredEvent' => null,
            'visibility' => null,
            'delta' => 2.0,
            'targetVariable' => 'movementPoint',
            'mode' => 'additive',
            'modifierActivationRequirements' => [],
        ],
        [
            'name' => 'antisocial_modifier_for_player_-1moralPoint_on_new_cycle_if_player_in_room_not_alone',
            'modifierName' => 'antisocial_modifier',
            'targetEvent' => 'new_cycle',
            'applyOnActionParameter' => false,
            'modifierRange' => 'player',
            'type' => 'variable_event_modifier',
            'triggeredEvent' => null,
            'visibility' => null,
            'delta' => -1.0,
            'targetVariable' => 'moralPoint',
            'mode' => 'additive',
            'modifierActivationRequirements' => [
                'player_in_room_not_alone',
            ],
        ],
        [
            'name' => 'modifier_for_player_-1moralPoint_on_new_cycle',
            'modifierName' => null,
            'targetEvent' => 'new_cycle',
            'applyOnActionParameter' => false,
            'modifierRange' => 'player',
            'type' => 'variable_event_modifier',
            'triggeredEvent' => null,
            'visibility' => null,
            'delta' => -1.0,
            'targetVariable' => 'moralPoint',
            'mode' => 'additive',
            'modifierActivationRequirements' => [],
        ],
        [
            'name' => 'lying_down_modifier_for_player_+1actionPoint_on_new_cycle',
            'modifierName' => 'lying_down_modifier',
            'targetEvent' => 'new_cycle',
            'applyOnActionParameter' => false,
            'modifierRange' => 'player',
            'type' => 'variable_event_modifier',
            'triggeredEvent' => null,
            'visibility' => null,
            'delta' => 1.0,
            'targetVariable' => 'actionPoint',
            'mode' => 'additive',
            'modifierActivationRequirements' => [],
        ],
        [
            'name' => 'starving_for_player_-1healthPoint_on_new_cycle',
            'modifierName' => 'starving',
            'targetEvent' => 'new_cycle',
            'applyOnActionParameter' => false,
            'modifierRange' => 'player',
            'type' => 'variable_event_modifier',
            'triggeredEvent' => null,
            'visibility' => null,
            'delta' => -1.0,
            'targetVariable' => 'healthPoint',
            'mode' => 'additive',
            'modifierActivationRequirements' => [],
        ],
        [
            'name' => 'modifier_for_player_+30percentage_on_cycle_disease',
            'modifierName' => null,
            'targetEvent' => 'cycle_disease',
            'applyOnActionParameter' => false,
            'modifierRange' => 'player',
            'type' => 'variable_event_modifier',
            'triggeredEvent' => null,
            'visibility' => null,
            'delta' => 30.0,
            'targetVariable' => 'percentage',
            'mode' => 'additive',
            'modifierActivationRequirements' => [],
        ],
        [
            'name' => 'mush_shower_malus_for_player_set_-3healthPoint_on_post.action_if_reason_shower',
            'modifierName' => 'mush_shower_malus',
            'targetEvent' => 'post.action',
            'applyOnActionParameter' => false,
            'modifierRange' => 'player',
            'type' => 'variable_event_modifier',
            'triggeredEvent' => null,
            'visibility' => null,
            'delta' => -3.0,
            'targetVariable' => 'healthPoint',
            'mode' => 'set_value',
            'modifierActivationRequirements' => [
                'reason_shower',
            ],
        ],
        [
            'name' => 'mush_shower_malus_for_player_set_-3healthPoint_on_post.action_if_reason_wash_in_sink',
            'modifierName' => 'mush_shower_malus',
            'targetEvent' => 'post.action',
            'applyOnActionParameter' => false,
            'modifierRange' => 'player',
            'type' => 'variable_event_modifier',
            'triggeredEvent' => null,
            'visibility' => null,
            'delta' => -3.0,
            'targetVariable' => 'healthPoint',
            'mode' => 'set_value',
            'modifierActivationRequirements' => [
                'reason_wash_in_sink',
            ],
        ],
        [
            'name' => 'modifier_for_player_set_4satiety_on_change.variable_if_reason_consume',
            'modifierName' => null,
            'targetEvent' => 'change.variable',
            'applyOnActionParameter' => false,
            'modifierRange' => 'player',
            'type' => 'variable_event_modifier',
            'triggeredEvent' => null,
            'visibility' => null,
            'delta' => 4.0,
            'targetVariable' => 'satiety',
            'mode' => 'set_value',
            'modifierActivationRequirements' => [
                'reason_consume',
            ],
        ],
        [
            'name' => 'modifier_for_player_set_0healthPoint_on_change.variable_if_reason_consume',
            'modifierName' => null,
            'targetEvent' => 'change.variable',
            'applyOnActionParameter' => false,
            'modifierRange' => 'player',
            'type' => 'variable_event_modifier',
            'triggeredEvent' => null,
            'visibility' => null,
            'delta' => 0.0,
            'targetVariable' => 'healthPoint',
            'mode' => 'set_value',
            'modifierActivationRequirements' => [
                'reason_consume',
            ],
        ],
        [
            'name' => 'modifier_for_player_set_0moralPoint_on_change.variable_if_reason_consume',
            'modifierName' => null,
            'targetEvent' => 'change.variable',
            'applyOnActionParameter' => false,
            'modifierRange' => 'player',
            'type' => 'variable_event_modifier',
            'triggeredEvent' => null,
            'visibility' => null,
            'delta' => 0.0,
            'targetVariable' => 'moralPoint',
            'mode' => 'set_value',
            'modifierActivationRequirements' => [
                'reason_consume',
            ],
        ],
        [
            'name' => 'modifier_for_player_set_0actionPoint_on_change.variable_if_reason_consume',
            'modifierName' => null,
            'targetEvent' => 'change.variable',
            'applyOnActionParameter' => false,
            'modifierRange' => 'player',
            'type' => 'variable_event_modifier',
            'triggeredEvent' => null,
            'visibility' => null,
            'delta' => 0.0,
            'targetVariable' => 'actionPoint',
            'mode' => 'set_value',
            'modifierActivationRequirements' => [
                'reason_consume',
            ],
        ],
        [
            'name' => 'modifier_for_player_set_0movementPoint_on_change.variable_if_reason_consume',
            'modifierName' => null,
            'targetEvent' => 'change.variable',
            'applyOnActionParameter' => false,
            'modifierRange' => 'player',
            'type' => 'variable_event_modifier',
            'triggeredEvent' => null,
            'visibility' => null,
            'delta' => 0.0,
            'targetVariable' => 'movementPoint',
            'mode' => 'set_value',
            'modifierActivationRequirements' => [
                'reason_consume',
            ],
        ],
    ];
}
