<?php

namespace Mush\Modifier\ConfigData;

use Mush\Action\Enum\ActionEnum;
use Mush\Action\Enum\ActionTypeEnum;
use Mush\Action\Enum\ActionVariableEnum;
use Mush\Action\Event\ActionVariableEvent;
use Mush\Daedalus\Event\DaedalusCycleEvent;
use Mush\Game\Enum\ActionOutputEnum;
use Mush\Game\Event\RollPercentageEvent;
use Mush\Game\Event\VariableEventInterface;
use Mush\Modifier\Enum\ModifierNameEnum;
use Mush\Modifier\Enum\ModifierRequirementEnum;
use Mush\Player\Enum\EndCauseEnum;
use Mush\Player\Enum\PlayerVariableEnum;
use Mush\Player\Event\PlayerEvent;
use Mush\Status\Enum\PlayerStatusEnum;
use Mush\Status\Event\StatusEvent;

/** @codeCoverageIgnore */
class ModifierConfigData
{
    public static array $dataArray = [
        [
            'name' => 'modifier_for_player_+1movementPoint_on_move',
            'modifierName' => null,
            'targetEvent' => 'apply.cost',
            'applyOnTarget' => false,
            'modifierRange' => 'player',
            'type' => 'variable_event_modifier',
            'triggeredEvent' => null,
            'visibility' => null,
            'delta' => 1.0,
            'targetVariable' => 'movementPoint',
            'mode' => 'additive',
            'modifierActivationRequirements' => [],
            'tagConstraints' => [ActionEnum::MOVE => ModifierRequirementEnum::ALL_TAGS],
        ],
        [
            'name' => 'direct_modifier_player_-1_max_healthPoint',
            'modifierName' => null,
            'revertOnRemove' => true,
            'modifierRange' => 'player',
            'type' => 'direct_modifier',
            'triggeredEvent' => 'change.value.max_player_-1_healthPoint',
            'modifierActivationRequirements' => [],
        ],
        [
            'name' => 'direct_modifier_player_-2_max_healthPoint',
            'modifierName' => null,
            'revertOnRemove' => true,
            'modifierRange' => 'player',
            'type' => 'direct_modifier',
            'triggeredEvent' => 'change.value.max_player_-2_healthPoint',
            'modifierActivationRequirements' => [],
        ],
        [
            'name' => 'direct_modifier_player_-4_max_healthPoint',
            'modifierName' => null,
            'revertOnRemove' => true,
            'modifierRange' => 'player',
            'type' => 'direct_modifier',
            'triggeredEvent' => 'change.value.max_player_-4_healthPoint',
            'modifierActivationRequirements' => [],
        ],
        [
            'name' => 'direct_modifier_player_-1_max_moralPoint',
            'modifierName' => null,
            'revertOnRemove' => true,
            'modifierRange' => 'player',
            'type' => 'direct_modifier',
            'triggeredEvent' => 'change.value.max_player_-1_moralPoint',
            'modifierActivationRequirements' => [],
        ],
        [
            'name' => 'direct_modifier_player_-2_max_moralPoint',
            'modifierName' => null,
            'revertOnRemove' => true,
            'modifierRange' => 'player',
            'type' => 'direct_modifier',
            'triggeredEvent' => 'change.value.max_player_-2_moralPoint',
            'modifierActivationRequirements' => [],
        ],
        [
            'name' => 'modifier_for_player_set_-1healthPoint_on_new_cycle',
            'modifierName' => null,
            'targetEvent' => 'player.new.cycle',
            'applyOnTarget' => true,
            'modifierRange' => 'player',
            'type' => 'trigger_event_modifier',
            'replaceEvent' => false,
            'triggeredEvent' => 'change.variable_player_-1_healthPoint',
            'modifierActivationRequirements' => [],
            'tagConstraints' => [],
        ],
        [
            'name' => 'modifier_for_player_set_-2healthPoint_on_new_cycle',
            'modifierName' => null,
            'targetEvent' => 'player.new.cycle',
            'applyOnTarget' => true,
            'modifierRange' => 'player',
            'type' => 'trigger_event_modifier',
            'replaceEvent' => false,
            'triggeredEvent' => 'change.variable_player_-2_healthPoint',
            'modifierActivationRequirements' => [],
            'tagConstraints' => [],
        ],
        [
            'name' => 'modifier_for_player_set_-4healthPoint_on_new_cycle',
            'modifierName' => null,
            'targetEvent' => 'player.new.cycle',
            'applyOnTarget' => true,
            'modifierRange' => 'player',
            'type' => 'trigger_event_modifier',
            'replaceEvent' => false,
            'triggeredEvent' => 'change.variable_player_-4_healthPoint',
            'modifierActivationRequirements' => [],
            'tagConstraints' => [],
        ],
        [
            'name' => 'modifier_for_player_set_-1movementPoint_on_new_cycle',
            'modifierName' => null,
            'targetEvent' => 'player.new.cycle',
            'applyOnTarget' => true,
            'modifierRange' => 'player',
            'type' => 'trigger_event_modifier',
            'replaceEvent' => false,
            'triggeredEvent' => 'change.variable_player_-1_movementPoint',
            'modifierActivationRequirements' => [],
            'tagConstraints' => [],
        ],
        [
            'name' => 'modifier_for_player_set_-1satiety_on_new_cycle',
            'modifierName' => null,
            'targetEvent' => 'player.new.cycle',
            'applyOnTarget' => true,
            'modifierRange' => 'player',
            'type' => 'trigger_event_modifier',
            'replaceEvent' => false,
            'triggeredEvent' => 'change.variable_player_-1_satiety',
            'modifierActivationRequirements' => [],
            'tagConstraints' => [],
        ],
        [
            'name' => 'modifier_for_player_set_-1actionPoint_on_new_cycle_if_random_10',
            'modifierName' => null,
            'targetEvent' => 'player.new.cycle',
            'applyOnTarget' => true,
            'modifierRange' => 'player',
            'type' => 'trigger_event_modifier',
            'replaceEvent' => false,
            'triggeredEvent' => 'change.variable_player_-1_actionPoint',
            'modifierActivationRequirements' => [
                'random_10',
            ],
            'tagConstraints' => [],
        ],
        [
            'name' => 'modifier_for_player_set_-1healthPoint_on_new_cycle_if_random_10',
            'modifierName' => null,
            'targetEvent' => 'player.new.cycle',
            'applyOnTarget' => true,
            'modifierRange' => 'player',
            'type' => 'trigger_event_modifier',
            'replaceEvent' => false,
            'triggeredEvent' => 'change.variable_player_-1_healthPoint',
            'modifierActivationRequirements' => [
                'random_10',
            ],
            'tagConstraints' => [],
        ],
        [
            'name' => 'modifier_for_player_set_-1actionPoint_on_new_cycle_if_random_16',
            'modifierName' => null,
            'targetEvent' => 'player.new.cycle',
            'applyOnTarget' => true,
            'modifierRange' => 'player',
            'type' => 'trigger_event_modifier',
            'replaceEvent' => false,
            'triggeredEvent' => 'change.variable_player_-1_actionPoint',
            'modifierActivationRequirements' => [
                'random_16',
            ],
            'tagConstraints' => [],
        ],
        [
            'name' => 'modifier_for_player_set_-1healthPoint_on_new_cycle_if_random_16',
            'modifierName' => null,
            'targetEvent' => 'player.new.cycle',
            'applyOnTarget' => true,
            'modifierRange' => 'player',
            'type' => 'trigger_event_modifier',
            'replaceEvent' => false,
            'triggeredEvent' => 'change.variable_player_-1_healthPoint',
            'modifierActivationRequirements' => [
                'random_16',
            ],
            'tagConstraints' => [],
        ],
        [
            'name' => 'modifier_for_player_set_-1actionPoint_on_new_cycle_if_random_20',
            'modifierName' => null,
            'targetEvent' => 'player.new.cycle',
            'applyOnTarget' => true,
            'modifierRange' => 'player',
            'type' => 'trigger_event_modifier',
            'replaceEvent' => false,
            'triggeredEvent' => 'change.variable_player_-1_actionPoint',
            'modifierActivationRequirements' => [
                'random_20',
            ],
            'tagConstraints' => [],
        ],
        [
            'name' => 'modifier_for_player_set_-1actionPoint_on_new_cycle_if_random_30',
            'modifierName' => null,
            'targetEvent' => 'player.new.cycle',
            'applyOnTarget' => true,
            'modifierRange' => 'player',
            'type' => 'trigger_event_modifier',
            'replaceEvent' => false,
            'triggeredEvent' => 'change.variable_player_-1_actionPoint',
            'modifierActivationRequirements' => [
                'random_30',
            ],
            'tagConstraints' => [],
        ],
        [
            'name' => 'modifier_for_player_set_-2actionPoint_on_new_cycle_if_random_40',
            'modifierName' => null,
            'targetEvent' => 'player.new.cycle',
            'applyOnTarget' => true,
            'modifierRange' => 'player',
            'type' => 'trigger_event_modifier',
            'replaceEvent' => false,
            'triggeredEvent' => 'change.variable_player_-2_actionPoint',
            'modifierActivationRequirements' => [
                'random_40',
            ],
            'tagConstraints' => [],
        ],
        [
            'name' => 'modifier_for_player_set_-1movementPoint_on_new_cycle_if_random_50',
            'modifierName' => null,
            'targetEvent' => 'player.new.cycle',
            'applyOnTarget' => true,
            'modifierRange' => 'player',
            'type' => 'trigger_event_modifier',
            'replaceEvent' => false,
            'triggeredEvent' => 'change.variable_player_-1_movementPoint',
            'modifierActivationRequirements' => [
                'random_50',
            ],
            'tagConstraints' => [],
        ],
        [
            'name' => 'modifier_for_player_set_-1healthPoint_on_new_cycle_if_random_50',
            'modifierName' => null,
            'targetEvent' => 'player.new.cycle',
            'applyOnTarget' => true,
            'modifierRange' => 'player',
            'type' => 'trigger_event_modifier',
            'replaceEvent' => false,
            'triggeredEvent' => 'change.variable_player_-1_healthPoint',
            'modifierActivationRequirements' => [
                'random_50',
            ],
            'tagConstraints' => [],
        ],
        [
            'name' => 'modifier_for_player_set_-1actionPoint_on_post.action_if_reason_consume',
            'modifierName' => null,
            'targetEvent' => 'post.action',
            'applyOnTarget' => false,
            'modifierRange' => 'player',
            'type' => 'trigger_event_modifier',
            'replaceEvent' => false,
            'triggeredEvent' => 'change.variable_player_-1_actionPoint',
            'modifierActivationRequirements' => [],
            'tagConstraints' => [
                ActionEnum::CONSUME => ModifierRequirementEnum::ANY_TAGS,
                ActionEnum::CONSUME_DRUG => ModifierRequirementEnum::ANY_TAGS,
            ],
        ],
        [
            'name' => 'modifier_for_player_set_-2actionPoint_on_post.action_if_reason_consume',
            'modifierName' => null,
            'targetEvent' => 'post.action',
            'applyOnTarget' => false,
            'modifierRange' => 'player',
            'type' => 'trigger_event_modifier',
            'replaceEvent' => false,
            'triggeredEvent' => 'change.variable_player_-2_actionPoint',
            'modifierActivationRequirements' => [],
            'tagConstraints' => [
                ActionEnum::CONSUME => ModifierRequirementEnum::ANY_TAGS,
                ActionEnum::CONSUME_DRUG => ModifierRequirementEnum::ANY_TAGS,
            ],
        ],
        [
            'name' => 'modifier_for_player_set_-4healthPoint_on_infection.player',
            'modifierName' => null,
            'targetEvent' => 'infection.player',
            'applyOnTarget' => true,
            'modifierRange' => 'player',
            'type' => 'trigger_event_modifier',
            'replaceEvent' => false,
            'triggeredEvent' => 'change.variable_player_-4_healthPoint',
            'modifierActivationRequirements' => [],
            'tagConstraints' => [],
        ],
        [
            'name' => 'modifier_for_player_set_-6healthPoint_on_post.action_if_player_equipment_schrodinger',
            'modifierName' => null,
            'targetEvent' => 'post.action',
            'applyOnTarget' => false,
            'modifierRange' => 'player',
            'type' => 'trigger_event_modifier',
            'replaceEvent' => false,
            'triggeredEvent' => 'change.variable_player_-6_healthPoint',
            'modifierActivationRequirements' => [
                'player_equipment_schrodinger',
            ],
            'tagConstraints' => [],
        ],
        [
            'name' => 'modifier_for_player_+1satiety_on_new_cycle',
            'modifierName' => null,
            'targetEvent' => 'player.new.cycle',
            'applyOnTarget' => false,
            'modifierRange' => 'player',
            'type' => 'trigger_event_modifier',
            'replaceEvent' => false,
            'triggeredEvent' => 'change.variable_player_1_satiety',
            'modifierActivationRequirements' => [],
            'tagConstraints' => [],
        ],
        [
            'name' => 'modifier_for_player_x0.9percentage_on_action_shoot',
            'modifierName' => null,
            'targetEvent' => ActionVariableEvent::ROLL_ACTION_PERCENTAGE,
            'applyOnTarget' => false,
            'modifierRange' => 'player',
            'type' => 'variable_event_modifier',
            'triggeredEvent' => null,
            'visibility' => null,
            'delta' => 0.9,
            'targetVariable' => ActionVariableEnum::PERCENTAGE_SUCCESS,
            'mode' => 'multiplicative',
            'modifierActivationRequirements' => [],
            'tagConstraints' => [
                ActionEnum::SHOOT => ModifierRequirementEnum::ANY_TAGS,
            ],
        ],
        [
            'name' => 'modifier_for_player_+10percentage_on_cycle_disease',
            'modifierName' => null,
            'targetEvent' => RollPercentageEvent::ROLL_PERCENTAGE,
            'applyOnTarget' => false,
            'modifierRange' => 'player',
            'type' => 'variable_event_modifier',
            'triggeredEvent' => null,
            'visibility' => null,
            'delta' => 10.0,
            'targetVariable' => ActionVariableEnum::PERCENTAGE_SUCCESS,
            'mode' => 'additive',
            'modifierActivationRequirements' => [],
            'tagConstraints' => [PlayerEvent::CYCLE_DISEASE => ModifierRequirementEnum::ANY_TAGS],
        ],
        [
            'name' => 'fitful_sleep_for_player_-1actionPoint_on_new_cycle_if_random_16_if_player_status_lying_down',
            'modifierName' => 'fitful_sleep',
            'targetEvent' => 'player.new.cycle',
            'applyOnTarget' => true,
            'modifierRange' => 'player',
            'type' => 'trigger_event_modifier',
            'replaceEvent' => false,
            'triggeredEvent' => 'change.variable_player_-1_actionPoint',
            'modifierActivationRequirements' => [
                'random_16',
                'player_status_lying_down',
            ],
            'tagConstraints' => [],
        ],
        [
            'name' => 'apron_modifier_for_player_prevent_dirty',
            'modifierName' => 'apron_modifier',
            'targetEvent' => StatusEvent::STATUS_APPLIED,
            'applyOnTarget' => true,
            'modifierRange' => 'player',
            'type' => 'trigger_event_modifier',
            'replaceEvent' => true,
            'triggeredEvent' => null,
            'modifierActivationRequirements' => [],
            'tagConstraints' => [
                PlayerStatusEnum::DIRTY => ModifierRequirementEnum::ALL_TAGS,
                ActionTypeEnum::ACTION_SUPER_DIRTY => ModifierRequirementEnum::NONE_TAGS,
            ],
        ],
        [
            'name' => 'modifier_for_target_player_-1healthPoint_on_injury',
            'modifierName' => null,
            'targetEvent' => VariableEventInterface::CHANGE_VARIABLE,
            'applyOnTarget' => true,
            'modifierRange' => 'target_player',
            'type' => 'variable_event_modifier',
            'triggeredEvent' => null,
            'visibility' => null,
            'delta' => -1.0,
            'targetVariable' => 'healthPoint',
            'mode' => 'additive',
            'modifierActivationRequirements' => [],
            'tagConstraints' => [
                EndCauseEnum::INJURY => ModifierRequirementEnum::ALL_TAGS,
                ActionOutputEnum::CRITICAL_SUCCESS => ModifierRequirementEnum::NONE_TAGS,
            ],
        ],
        [
            'name' => 'modifier_for_player_x1.5percentage_on_action_technician',
            'modifierName' => null,
            'targetEvent' => ActionVariableEvent::ROLL_ACTION_PERCENTAGE,
            'applyOnTarget' => false,
            'modifierRange' => 'player',
            'type' => 'variable_event_modifier',
            'triggeredEvent' => null,
            'visibility' => null,
            'delta' => 1.5,
            'targetVariable' => ActionVariableEnum::PERCENTAGE_SUCCESS,
            'mode' => 'multiplicative',
            'modifierActivationRequirements' => [],
            'tagConstraints' => [
                ActionTypeEnum::ACTION_TECHNICIAN => ModifierRequirementEnum::ALL_TAGS,
            ],
        ],
        [
            'name' => 'gloves_modifier_for_player_set_0percentage_on_event_clumsiness',
            'modifierName' => 'gloves_modifier',
            'targetEvent' => VariableEventInterface::CHANGE_VARIABLE,
            'applyOnTarget' => true,
            'modifierRange' => 'player',
            'type' => 'trigger_event_modifier',
            'replaceEvent' => true,
            'triggeredEvent' => null,
            'modifierActivationRequirements' => [],
            'tagConstraints' => [EndCauseEnum::CLUMSINESS => ModifierRequirementEnum::ALL_TAGS],
        ],
        [
            'name' => 'modifier_for_player_-1actionPoint_on_shower',
            'modifierName' => null,
            'targetEvent' => ActionVariableEvent::APPLY_COST,
            'applyOnTarget' => false,
            'modifierRange' => 'player',
            'type' => 'variable_event_modifier',
            'triggeredEvent' => null,
            'visibility' => null,
            'delta' => -1,
            'targetVariable' => PlayerVariableEnum::ACTION_POINT,
            'mode' => 'additive',
            'modifierActivationRequirements' => [],
            'tagConstraints' => [
                ActionEnum::WASH_IN_SINK => ModifierRequirementEnum::ANY_TAGS,
                ActionEnum::SHOWER => ModifierRequirementEnum::ANY_TAGS,
            ],
        ],
        [
            'name' => 'modifier_for_player_x1.1percentage_on_action_shoot_hunter',
            'modifierName' => null,
            'targetEvent' => ActionVariableEvent::ROLL_ACTION_PERCENTAGE,
            'applyOnTarget' => false,
            'modifierRange' => 'player',
            'type' => 'variable_event_modifier',
            'triggeredEvent' => null,
            'visibility' => null,
            'delta' => 1.1,
            'targetVariable' => ActionVariableEnum::PERCENTAGE_SUCCESS,
            'mode' => 'multiplicative',
            'modifierActivationRequirements' => [],
            'tagConstraints' => [ActionTypeEnum::ACTION_SHOOT_HUNTER => ModifierRequirementEnum::ANY_TAGS],
        ],
        [
            'name' => 'modifier_for_player_+2movementPoint_on_event_action_movement_conversion',
            'modifierName' => ModifierNameEnum::ANTIGRAV_SCOOTER_CONVERSION_MODIFIER,
            'targetEvent' => ActionVariableEvent::APPLY_COST,
            'applyOnTarget' => false,
            'modifierRange' => 'player',
            'type' => 'variable_event_modifier',
            'triggeredEvent' => null,
            'visibility' => null,
            'delta' => -2.0,
            'targetVariable' => 'movementPoint',
            'mode' => 'additive',
            'modifierActivationRequirements' => [],
            'tagConstraints' => [ActionEnum::CONVERT_ACTION_TO_MOVEMENT => ModifierRequirementEnum::ALL_TAGS],
        ],
        [
            'name' => 'modifier_for_player_+1movementPoint_on_event_action_movement_conversion_if_cycle_even',
            'modifierName' => null,
            'targetEvent' => ActionVariableEvent::APPLY_COST,
            'applyOnTarget' => false,
            'modifierRange' => 'player',
            'type' => 'variable_event_modifier',
            'triggeredEvent' => null,
            'visibility' => null,
            'delta' => -1.0,
            'targetVariable' => 'movementPoint',
            'mode' => 'additive',
            'modifierActivationRequirements' => [
                'cycle_even',
            ],
            'tagConstraints' => [ActionEnum::CONVERT_ACTION_TO_MOVEMENT => ModifierRequirementEnum::ALL_TAGS],
        ],
        [
            'name' => 'modifier_for_player_x2percentage_on_strengthen_hull',
            'modifierName' => null,
            'targetEvent' => ActionVariableEvent::ROLL_ACTION_PERCENTAGE,
            'applyOnTarget' => false,
            'modifierRange' => 'player',
            'type' => 'variable_event_modifier',
            'triggeredEvent' => null,
            'visibility' => null,
            'delta' => 2.0,
            'targetVariable' => ActionVariableEnum::PERCENTAGE_SUCCESS,
            'mode' => 'multiplicative',
            'modifierActivationRequirements' => [],
            'tagConstraints' => [ActionEnum::STRENGTHEN_HULL => ModifierRequirementEnum::ANY_TAGS],
        ],
        [
            'name' => 'modifier_for_player_x2percentage_on_renovate',
            'modifierName' => null,
            'targetEvent' => ActionVariableEvent::ROLL_ACTION_PERCENTAGE,
            'applyOnTarget' => false,
            'modifierRange' => 'player',
            'type' => 'variable_event_modifier',
            'triggeredEvent' => null,
            'visibility' => null,
            'delta' => 2.0,
            'targetVariable' => ActionVariableEnum::PERCENTAGE_SUCCESS,
            'mode' => 'multiplicative',
            'modifierActivationRequirements' => [],
            'tagConstraints' => [ActionEnum::RENOVATE => ModifierRequirementEnum::ANY_TAGS],
        ],
        [
            'name' => 'modifier_for_player_x2hull_on_change.variable_if_reason_strengthen_hull',
            'modifierName' => null,
            'targetEvent' => 'change.variable',
            'applyOnTarget' => false,
            'modifierRange' => 'player',
            'type' => 'variable_event_modifier',
            'triggeredEvent' => null,
            'visibility' => null,
            'delta' => 2.0,
            'targetVariable' => 'hull',
            'mode' => 'multiplicative',
            'modifierActivationRequirements' => [],
            'tagConstraints' => [ActionEnum::STRENGTHEN_HULL => ModifierRequirementEnum::ANY_TAGS],
        ],
        [
            'name' => 'modifier_for_daedalus_-1actionPoint_on_TODO coms. action',
            'modifierName' => null,
            'targetEvent' => ActionVariableEvent::APPLY_COST,
            'applyOnTarget' => false,
            'modifierRange' => 'daedalus',
            'type' => 'variable_event_modifier',
            'triggeredEvent' => null,
            'visibility' => null,
            'delta' => -1.0,
            'targetVariable' => 'actionPoint',
            'mode' => 'additive',
            'modifierActivationRequirements' => [],
            'tagConstraints' => [ActionEnum::CONTACT_SOL => ModifierRequirementEnum::ALL_TAGS],
        ],
        [
            'name' => 'modifier_for_daedalus_+1movementPoint_on_event_action_movement_conversion',
            'modifierName' => null,
            'targetEvent' => ActionVariableEvent::APPLY_COST,
            'applyOnTarget' => false,
            'modifierRange' => 'daedalus',
            'type' => 'variable_event_modifier',
            'triggeredEvent' => null,
            'visibility' => null,
            'delta' => -1.0,
            'targetVariable' => 'movementPoint',
            'mode' => 'additive',
            'modifierActivationRequirements' => [],
            'tagConstraints' => [ActionEnum::CONVERT_ACTION_TO_MOVEMENT => ModifierRequirementEnum::ALL_TAGS],
        ],
        [
            'name' => 'modifier_for_daedalus_+1movementPoint_on_change.variable_if_reason_new_cycle',
            'modifierName' => null,
            'targetEvent' => DaedalusCycleEvent::DAEDALUS_NEW_CYCLE,
            'applyOnTarget' => true,
            'modifierRange' => 'daedalus',
            'type' => 'trigger_event_modifier',
            'replaceEvent' => false,
            'triggeredEvent' => 'change.variable_player_1_movementPoint',
            'modifierActivationRequirements' => [],
            'tagConstraints' => [],
        ],
        [
            'name' => 'modifier_for_daedalus_+1oxygen_on_change.variable_if_reason_new_cycle',
            'modifierName' => null,
            'targetEvent' => 'change.variable',
            'applyOnTarget' => false,
            'modifierRange' => 'daedalus',
            'type' => 'variable_event_modifier',
            'triggeredEvent' => null,
            'visibility' => null,
            'delta' => 1.0,
            'targetVariable' => 'oxygen',
            'mode' => 'additive',
            'modifierActivationRequirements' => [],
            'tagConstraints' => ['base_daedalus_cycle_change' => ModifierRequirementEnum::ALL_TAGS],
        ],
        [
            'name' => 'modifier_for_player_+2movementPoint_on_move_if_item_in_room_schrodinger',
            'modifierName' => null,
            'targetEvent' => ActionVariableEvent::APPLY_COST,
            'applyOnTarget' => false,
            'modifierRange' => 'player',
            'type' => 'variable_event_modifier',
            'triggeredEvent' => null,
            'visibility' => null,
            'delta' => 2.0,
            'targetVariable' => 'movementPoint',
            'mode' => 'additive',
            'modifierActivationRequirements' => [
                'item_in_room_schrodinger',
            ],
            'tagConstraints' => [
                ActionEnum::MOVE => ModifierRequirementEnum::ALL_TAGS,
                ActionTypeEnum::ACTION_ADMIN => ModifierRequirementEnum::NONE_TAGS,
            ],
        ],
        [
            'name' => 'modifier_for_player_+2actionPoint_on_actions_if_item_in_room_schrodinger_if_not_reason_move',
            'modifierName' => null,
            'targetEvent' => ActionVariableEvent::APPLY_COST,
            'applyOnTarget' => false,
            'modifierRange' => 'player',
            'type' => 'variable_event_modifier',
            'triggeredEvent' => null,
            'visibility' => null,
            'delta' => 2.0,
            'targetVariable' => 'actionPoint',
            'mode' => 'additive',
            'modifierActivationRequirements' => [
                'item_in_room_schrodinger',
            ],
            'tagConstraints' => [
                ActionEnum::MOVE => ModifierRequirementEnum::NONE_TAGS,
                ActionTypeEnum::ACTION_ADMIN => ModifierRequirementEnum::NONE_TAGS, ],
        ],
        [
            'name' => 'screaming_for_player_set_-1actionPoint_on_new_cycle_if_random_16',
            'modifierName' => 'screaming',
            'targetEvent' => 'player.new.cycle',
            'applyOnTarget' => true,
            'modifierRange' => 'player',
            'type' => 'trigger_event_modifier',
            'replaceEvent' => false,
            'triggeredEvent' => 'change.variable_player_-1_actionPoint',
            'modifierActivationRequirements' => [
                'random_16',
            ],
            'tagConstraints' => [],
        ],
        [
            'name' => 'wall_head_bang_for_player_set_-1healthPoint_on_new_cycle_if_random_16',
            'modifierName' => 'wall_head_bang',
            'targetEvent' => 'player.new.cycle',
            'applyOnTarget' => true,
            'modifierRange' => 'player',
            'type' => 'trigger_event_modifier',
            'replaceEvent' => false,
            'triggeredEvent' => 'change.variable_player_-1_healthPoint',
            'modifierActivationRequirements' => [
                'random_16',
            ],
            'tagConstraints' => [],
        ],
        [
            'name' => 'modifier_for_player_set_-1moralPoint_on_new_cycle_if_random_70',
            'modifierName' => null,
            'targetEvent' => 'player.new.cycle',
            'applyOnTarget' => true,
            'modifierRange' => 'player',
            'type' => 'trigger_event_modifier',
            'replaceEvent' => false,
            'triggeredEvent' => 'change.variable_player_-1_moralPoint',
            'modifierActivationRequirements' => [
                'random_70',
            ],
            'tagConstraints' => [],
        ],
        [
            'name' => 'run_in_circles_for_player_set_-2movementPoint_on_new_cycle_if_random_16',
            'modifierName' => 'run_in_circles',
            'targetEvent' => 'player.new.cycle',
            'applyOnTarget' => true,
            'modifierRange' => 'player',
            'type' => 'trigger_event_modifier',
            'replaceEvent' => false,
            'triggeredEvent' => 'change.variable_player_-2_movementPoint',
            'modifierActivationRequirements' => [
                'random_16',
            ],
            'tagConstraints' => [],
        ],
        [
            'name' => 'modifier_for_player_+1actionPoint_on_actions_if_player_in_room_four_people',
            'modifierName' => null,
            'targetEvent' => ActionVariableEvent::APPLY_COST,
            'applyOnTarget' => true,
            'modifierRange' => 'player',
            'type' => 'variable_event_modifier',
            'triggeredEvent' => null,
            'visibility' => null,
            'delta' => 1.0,
            'targetVariable' => 'actionPoint',
            'mode' => 'additive',
            'modifierActivationRequirements' => [
                'player_in_room_four_people',
            ],
            'tagConstraints' => [
                ActionTypeEnum::ACTION_ADMIN => ModifierRequirementEnum::NONE_TAGS,
            ],
        ],
        [
            'name' => 'modifier_for_player_+1movementPoint_on_actions_if_player_in_room_four_people',
            'modifierName' => null,
            'targetEvent' => ActionVariableEvent::APPLY_COST,
            'applyOnTarget' => false,
            'modifierRange' => 'player',
            'type' => 'variable_event_modifier',
            'triggeredEvent' => null,
            'visibility' => null,
            'delta' => 1.0,
            'targetVariable' => 'movementPoint',
            'mode' => 'additive',
            'modifierActivationRequirements' => [
                'player_in_room_four_people',
            ],
            'tagConstraints' => [
                ActionTypeEnum::ACTION_ADMIN => ModifierRequirementEnum::NONE_TAGS,
            ],
        ],
        [
            'name' => 'direct_modifier_player_-2_max_actionPoint',
            'modifierName' => null,
            'revertOnRemove' => true,
            'modifierRange' => 'player',
            'type' => 'direct_modifier',
            'triggeredEvent' => 'change.value.max_player_-2_actionPoint',
            'modifierActivationRequirements' => [],
        ],
        [
            'name' => 'direct_modifier_player_-3_max_moralPoint',
            'modifierName' => null,
            'revertOnRemove' => true,
            'modifierRange' => 'player',
            'type' => 'direct_modifier',
            'triggeredEvent' => 'change.value.max_player_-3_moralPoint',
            'modifierActivationRequirements' => [],
        ],
        [
            'name' => 'direct_modifier_player_-4_max_moralPoint',
            'modifierName' => null,
            'revertOnRemove' => true,
            'modifierRange' => 'player',
            'type' => 'direct_modifier',
            'triggeredEvent' => 'change.value.max_player_-4_moralPoint',
            'modifierActivationRequirements' => [],
        ],
        [
            'name' => 'modifier_for_player_+1actionPoint_on_actions_if_not_reason_move_if_not_reason_consume_if_not_reason_consume_drug_if_not_reason_surgery_if_not_reason_self_surgery',
            'modifierName' => null,
            'targetEvent' => ActionVariableEvent::APPLY_COST,
            'applyOnTarget' => false,
            'modifierRange' => 'player',
            'type' => 'variable_event_modifier',
            'triggeredEvent' => null,
            'visibility' => null,
            'delta' => 1.0,
            'targetVariable' => 'actionPoint',
            'mode' => 'additive',
            'modifierActivationRequirements' => [],
            'tagConstraints' => [
                ActionEnum::MOVE => ModifierRequirementEnum::NONE_TAGS,
                ActionEnum::CONSUME => ModifierRequirementEnum::NONE_TAGS,
                ActionEnum::CONSUME_DRUG => ModifierRequirementEnum::NONE_TAGS,
                ActionEnum::SURGERY => ModifierRequirementEnum::NONE_TAGS,
                ActionEnum::SELF_SURGERY => ModifierRequirementEnum::NONE_TAGS,
                ActionTypeEnum::ACTION_ADMIN => ModifierRequirementEnum::NONE_TAGS,
            ],
        ],
        [
            'name' => 'modifier_for_player_+2actionPoint_on_actions_if_not_reason_move_if_not_reason_consume_if_not_reason_consume_drug_if_not_reason_surgery_if_not_reason_self_surgery',
            'modifierName' => null,
            'targetEvent' => ActionVariableEvent::APPLY_COST,
            'applyOnTarget' => false,
            'modifierRange' => 'player',
            'type' => 'variable_event_modifier',
            'triggeredEvent' => null,
            'visibility' => null,
            'delta' => 2.0,
            'targetVariable' => 'actionPoint',
            'mode' => 'additive',
            'modifierActivationRequirements' => [],
            'tagConstraints' => [
                ActionEnum::MOVE => ModifierRequirementEnum::NONE_TAGS,
                ActionEnum::CONSUME => ModifierRequirementEnum::NONE_TAGS,
                ActionEnum::CONSUME_DRUG => ModifierRequirementEnum::NONE_TAGS,
                ActionEnum::SURGERY => ModifierRequirementEnum::NONE_TAGS,
                ActionEnum::SELF_SURGERY => ModifierRequirementEnum::NONE_TAGS,
                ActionTypeEnum::ACTION_ADMIN => ModifierRequirementEnum::NONE_TAGS,
            ],
        ],
        [
            'name' => 'modifier_for_player_+3actionPoint_on_actions_if_not_reason_move_if_not_reason_consume_if_not_reason_consume_drug_if_not_reason_surgery_if_not_reason_self_surgery',
            'modifierName' => null,
            'targetEvent' => ActionVariableEvent::APPLY_COST,
            'applyOnTarget' => false,
            'modifierRange' => 'player',
            'type' => 'variable_event_modifier',
            'triggeredEvent' => null,
            'visibility' => null,
            'delta' => 3.0,
            'targetVariable' => 'actionPoint',
            'mode' => 'additive',
            'modifierActivationRequirements' => [],
            'tagConstraints' => [
                ActionEnum::MOVE => ModifierRequirementEnum::NONE_TAGS,
                ActionEnum::CONSUME => ModifierRequirementEnum::NONE_TAGS,
                ActionEnum::CONSUME_DRUG => ModifierRequirementEnum::NONE_TAGS,
                ActionEnum::SURGERY => ModifierRequirementEnum::NONE_TAGS,
                ActionEnum::SELF_SURGERY => ModifierRequirementEnum::NONE_TAGS,
                ActionTypeEnum::ACTION_ADMIN => ModifierRequirementEnum::NONE_TAGS,
            ],
        ],
        [
            'name' => 'direct_modifier_player_-3_max_movementPoint',
            'modifierName' => null,
            'revertOnRemove' => true,
            'modifierRange' => 'player',
            'type' => 'direct_modifier',
            'triggeredEvent' => 'change.value.max_player_-3_movementPoint',
            'modifierActivationRequirements' => [],
        ],
        [
            'name' => 'direct_modifier_player_-5_max_movementPoint',
            'modifierName' => null,
            'revertOnRemove' => true,
            'modifierRange' => 'player',
            'type' => 'direct_modifier',
            'triggeredEvent' => 'change.value.max_player_-5_movementPoint',
            'modifierActivationRequirements' => [],
        ],
        [
            'name' => 'direct_modifier_player_-12_max_movementPoint',
            'modifierName' => null,
            'revertOnRemove' => true,
            'modifierRange' => 'player',
            'type' => 'direct_modifier',
            'triggeredEvent' => 'change.value.max_player_-12_movementPoint',
            'modifierActivationRequirements' => [],
        ],
        [
            'name' => 'modifier_for_player_x0.85percentage_on_action_shoot',
            'modifierName' => null,
            'targetEvent' => ActionVariableEvent::ROLL_ACTION_PERCENTAGE,
            'applyOnTarget' => false,
            'modifierRange' => 'player',
            'type' => 'variable_event_modifier',
            'triggeredEvent' => null,
            'visibility' => null,
            'delta' => 0.85,
            'targetVariable' => ActionVariableEnum::PERCENTAGE_SUCCESS,
            'mode' => 'multiplicative',
            'modifierActivationRequirements' => [],
            'tagConstraints' => [
                ActionEnum::SHOOT => ModifierRequirementEnum::ANY_TAGS,
            ],
        ],
        [
            'name' => 'modifier_for_player_x0.8percentage_on_action_shoot',
            'modifierName' => null,
            'targetEvent' => ActionVariableEvent::ROLL_ACTION_PERCENTAGE,
            'applyOnTarget' => false,
            'modifierRange' => 'player',
            'type' => 'variable_event_modifier',
            'triggeredEvent' => null,
            'visibility' => null,
            'delta' => 0.8,
            'targetVariable' => ActionVariableEnum::PERCENTAGE_SUCCESS,
            'mode' => 'multiplicative',
            'modifierActivationRequirements' => [],
            'tagConstraints' => [
                ActionEnum::SHOOT => ModifierRequirementEnum::ANY_TAGS,
            ],
        ],
        [
            'name' => 'modifier_for_player_x0.6percentage_on_action_shoot',
            'modifierName' => null,
            'targetEvent' => ActionVariableEvent::ROLL_ACTION_PERCENTAGE,
            'applyOnTarget' => false,
            'modifierRange' => 'player',
            'type' => 'variable_event_modifier',
            'triggeredEvent' => null,
            'visibility' => null,
            'delta' => 0.6,
            'targetVariable' => ActionVariableEnum::PERCENTAGE_SUCCESS,
            'mode' => 'multiplicative',
            'modifierActivationRequirements' => [],
            'tagConstraints' => [
                ActionEnum::SHOOT => ModifierRequirementEnum::ANY_TAGS,
            ],
        ],
        [
            'name' => 'modifier_for_equipment_+1actionPoint_on_consume',
            'modifierName' => null,
            'targetEvent' => ActionVariableEvent::APPLY_COST,
            'applyOnTarget' => true,
            'modifierRange' => 'equipment',
            'type' => 'variable_event_modifier',
            'triggeredEvent' => null,
            'visibility' => null,
            'delta' => 1.0,
            'targetVariable' => 'actionPoint',
            'mode' => 'additive',
            'modifierActivationRequirements' => [],
            'tagConstraints' => [
                ActionEnum::CONSUME => ModifierRequirementEnum::ANY_TAGS,
                ActionEnum::CONSUME_DRUG => ModifierRequirementEnum::ANY_TAGS,
            ],
        ],
        [
            'name' => 'modifier_for_player_-2movementPoint_on_event_action_movement_conversion',
            'modifierName' => null,
            'targetEvent' => ActionVariableEvent::APPLY_COST,
            'applyOnTarget' => false,
            'modifierRange' => 'player',
            'type' => 'variable_event_modifier',
            'triggeredEvent' => null,
            'visibility' => null,
            'delta' => 2.0,
            'targetVariable' => 'movementPoint',
            'mode' => 'additive',
            'modifierActivationRequirements' => [],
            'tagConstraints' => [ActionEnum::CONVERT_ACTION_TO_MOVEMENT => ModifierRequirementEnum::ALL_TAGS],
        ],
        [
            'name' => 'modifier_for_player_-1movementPoint_on_move_if_player_in_room_not_alone',
            'modifierName' => null,
            'targetEvent' => ActionVariableEvent::APPLY_COST,
            'applyOnTarget' => false,
            'modifierRange' => 'player',
            'type' => 'variable_event_modifier',
            'triggeredEvent' => null,
            'visibility' => null,
            'delta' => -1.0,
            'targetVariable' => 'movementPoint',
            'mode' => 'additive',
            'modifierActivationRequirements' => [
                'player_in_room_not_alone',
            ],
            'tagConstraints' => [
                ActionEnum::MOVE => ModifierRequirementEnum::ANY_TAGS,
            ],
        ],
        [
            'name' => 'modifier_for_place_+2actionPoint_on_action_aggressive',
            'modifierName' => null,
            'targetEvent' => ActionVariableEvent::APPLY_COST,
            'applyOnTarget' => false,
            'modifierRange' => 'place',
            'type' => 'variable_event_modifier',
            'triggeredEvent' => null,
            'visibility' => null,
            'delta' => 2.0,
            'targetVariable' => 'actionPoint',
            'mode' => 'additive',
            'modifierActivationRequirements' => [],
            'tagConstraints' => [ActionTypeEnum::ACTION_AGGRESSIVE => ModifierRequirementEnum::ALL_TAGS],
        ],
        [
            'name' => 'modifier_for_player_+2movementPoint_on_move',
            'modifierName' => null,
            'targetEvent' => ActionVariableEvent::APPLY_COST,
            'applyOnTarget' => false,
            'modifierRange' => 'player',
            'type' => 'variable_event_modifier',
            'triggeredEvent' => null,
            'visibility' => null,
            'delta' => 2.0,
            'targetVariable' => 'movementPoint',
            'mode' => 'additive',
            'modifierActivationRequirements' => [],
            'tagConstraints' => [ActionEnum::MOVE => ModifierRequirementEnum::ALL_TAGS],
        ],
        [
            'name' => 'antisocial_modifier_for_player_-1moralPoint_on_new_cycle_if_player_in_room_not_alone',
            'modifierName' => 'antisocial_modifier',
            'targetEvent' => 'player.new.cycle',
            'applyOnTarget' => true,
            'modifierRange' => 'player',
            'type' => 'trigger_event_modifier',
            'replaceEvent' => false,
            'triggeredEvent' => 'change.variable_player_-1_moralPoint',
            'modifierActivationRequirements' => [
                'player_in_room_not_alone',
            ],
            'tagConstraints' => [],
        ],
        [
            'name' => 'modifier_for_player_-1moralPoint_on_new_cycle',
            'modifierName' => null,
            'targetEvent' => 'player.new.cycle',
            'applyOnTarget' => true,
            'modifierRange' => 'player',
            'type' => 'trigger_event_modifier',
            'replaceEvent' => false,
            'triggeredEvent' => 'change.variable_player_-1_moralPoint',
            'modifierActivationRequirements' => [],
            'tagConstraints' => [],
        ],
        [
            'name' => 'lying_down_modifier_for_player_+1actionPoint_on_new_cycle',
            'modifierName' => 'lying_down_modifier',
            'targetEvent' => VariableEventInterface::CHANGE_VARIABLE,
            'applyOnTarget' => true,
            'modifierRange' => 'player',
            'type' => 'variable_event_modifier',
            'triggeredEvent' => null,
            'visibility' => null,
            'delta' => 1.0,
            'targetVariable' => 'actionPoint',
            'mode' => 'additive',
            'modifierActivationRequirements' => [],
            'tagConstraints' => ['base_player_cycle_change' => ModifierRequirementEnum::ALL_TAGS],
        ],
        [
            'name' => 'starving_for_player_-1healthPoint_on_new_cycle',
            'modifierName' => 'starving',
            'targetEvent' => 'player.new.cycle',
            'applyOnTarget' => true,
            'modifierRange' => 'player',
            'type' => 'trigger_event_modifier',
            'replaceEvent' => false,
            'triggeredEvent' => 'change.variable_player_-1_healthPoint',
            'modifierActivationRequirements' => [],
            'tagConstraints' => [],
        ],
        [
            'name' => 'modifier_for_player_+30percentage_on_cycle_disease',
            'modifierName' => null,
            'targetEvent' => RollPercentageEvent::ROLL_PERCENTAGE,
            'applyOnTarget' => false,
            'modifierRange' => 'player',
            'type' => 'variable_event_modifier',
            'triggeredEvent' => null,
            'visibility' => null,
            'delta' => 30.0,
            'targetVariable' => ActionVariableEnum::PERCENTAGE_SUCCESS,
            'mode' => 'additive',
            'modifierActivationRequirements' => [],
            'tagConstraints' => [PlayerEvent::CYCLE_DISEASE => ModifierRequirementEnum::ALL_TAGS],
        ],
        [
            'name' => 'mush_shower_malus_for_player_set_-3healthPoint_on_post.action_if_reason_shower',
            'modifierName' => 'mush_shower_malus',
            'targetEvent' => 'post.action',
            'applyOnTarget' => false,
            'modifierRange' => 'player',
            'type' => 'trigger_event_modifier',
            'replaceEvent' => false,
            'triggeredEvent' => 'change.variable_player_-3_healthPoint',
            'modifierActivationRequirements' => [],
            'tagConstraints' => [
                ActionEnum::SHOWER => ModifierRequirementEnum::ANY_TAGS,
                ActionEnum::WASH_IN_SINK => ModifierRequirementEnum::ANY_TAGS,
            ],
        ],
        [
            'name' => 'modifier_for_player_set_4satiety_on_change.variable_if_reason_consume',
            'modifierName' => null,
            'targetEvent' => 'change.variable',
            'applyOnTarget' => true,
            'modifierRange' => 'player',
            'type' => 'variable_event_modifier',
            'triggeredEvent' => null,
            'visibility' => null,
            'delta' => 4.0,
            'targetVariable' => 'satiety',
            'mode' => 'set_value',
            'modifierActivationRequirements' => [],
            'tagConstraints' => [
                ActionEnum::CONSUME => ModifierRequirementEnum::ANY_TAGS,
                ActionEnum::CONSUME_DRUG => ModifierRequirementEnum::ANY_TAGS,
            ],
        ],
        [
            'name' => 'modifier_for_player_set_0moralPoint_on_change.variable_if_reason_consume',
            'modifierName' => null,
            'targetEvent' => 'change.variable',
            'applyOnTarget' => true,
            'modifierRange' => 'player',
            'type' => 'variable_event_modifier',
            'triggeredEvent' => null,
            'visibility' => null,
            'delta' => 0.0,
            'targetVariable' => 'moralPoint',
            'mode' => 'set_value',
            'modifierActivationRequirements' => [],
            'tagConstraints' => [
                ActionEnum::CONSUME => ModifierRequirementEnum::ANY_TAGS,
                ActionEnum::CONSUME_DRUG => ModifierRequirementEnum::ANY_TAGS,
            ],
        ],
        [
            'name' => 'modifier_for_player_set_0movementPoint_on_change.variable_if_reason_consume',
            'modifierName' => null,
            'targetEvent' => 'change.variable',
            'applyOnTarget' => true,
            'modifierRange' => 'player',
            'type' => 'variable_event_modifier',
            'triggeredEvent' => null,
            'visibility' => null,
            'delta' => 0.0,
            'targetVariable' => 'movementPoint',
            'mode' => 'set_value',
            'modifierActivationRequirements' => [],
            'tagConstraints' => [
                ActionEnum::CONSUME => ModifierRequirementEnum::ANY_TAGS,
                ActionEnum::CONSUME_DRUG => ModifierRequirementEnum::ANY_TAGS,
            ],
        ],
        [
            'name' => 'modifier_for_player_set_0actionPoint_on_change.variable_if_reason_consume',
            'modifierName' => null,
            'targetEvent' => 'change.variable',
            'applyOnTarget' => true,
            'modifierRange' => 'player',
            'type' => 'variable_event_modifier',
            'triggeredEvent' => null,
            'visibility' => null,
            'delta' => 0.0,
            'targetVariable' => 'actionPoint',
            'mode' => 'set_value',
            'modifierActivationRequirements' => [],
            'tagConstraints' => [
                ActionEnum::CONSUME => ModifierRequirementEnum::ANY_TAGS,
                ActionEnum::CONSUME_DRUG => ModifierRequirementEnum::ANY_TAGS,
            ],
        ],
        [
            'name' => 'modifier_for_player_set_0healthPoint_on_change.variable_if_reason_consume',
            'modifierName' => null,
            'targetEvent' => 'change.variable',
            'applyOnTarget' => true,
            'modifierRange' => 'player',
            'type' => 'variable_event_modifier',
            'triggeredEvent' => null,
            'visibility' => null,
            'delta' => 0.0,
            'targetVariable' => 'healthPoint',
            'mode' => 'set_value',
            'modifierActivationRequirements' => [],
            'tagConstraints' => [
                ActionEnum::CONSUME => ModifierRequirementEnum::ANY_TAGS,
                ActionEnum::CONSUME_DRUG => ModifierRequirementEnum::ANY_TAGS,
            ],
        ],
        [
            'name' => 'modifier_for_player_x1.33percentage_on_action_shoot',
            'modifierName' => null,
            'targetEvent' => ActionVariableEvent::ROLL_ACTION_PERCENTAGE,
            'applyOnTarget' => false,
            'modifierRange' => 'player',
            'type' => 'variable_event_modifier',
            'triggeredEvent' => null,
            'visibility' => null,
            'delta' => 1.33,
            'targetVariable' => ActionVariableEnum::PERCENTAGE_SUCCESS,
            'mode' => 'multiplicative',
            'modifierActivationRequirements' => [],
            'tagConstraints' => [ActionTypeEnum::ACTION_SHOOT => ModifierRequirementEnum::ANY_TAGS],
        ],
    ];
}
